### ISSUE TITLE
Improve github actions

### ISSUE THREAD

**Issue by wernerfred** [docker-mailserver/docker-mailserver#12]
# Subject

I would like to propose some improvement changes to the current github actions workflow

## Description

> NOTE: We are currently working on the tests for PRs. They fail for no reason. Again, working on a fix.

_Originally posted by @aendeavor in https://github.com/docker-mailserver/docker-mailserver/issues/9#issuecomment-761568210_

Glad that the initial migration PR went through, now I am trying to improve the workflows. One general question:
Why do we use/build/tag/push to a [testing repository](https://hub.docker.com/r/mailserver/testing) on dockerhub? Is there any specific reason for that? All workflows and CI processes i worked on till now only pushed working/productive images to dockerhub. Building and subsequent testing is all done locally on the CI runners. There is no need to push (and pull?) the local available image. Imho that only adds time to the pipeline run and adds additional complexity to the workflow.

> @radicand This is one of the PRs where the Login Action for Docker fails. Any idea?

_Originally posted by @aendeavor in https://github.com/docker-mailserver/docker-mailserver/issues/9#issuecomment-761568578_

This could also solve a few other error right now. There would for example be no need to log-in to dockerhub in the [test_merge_requests.yml](https://github.com/docker-mailserver/docker-mailserver/blob/master/.github/workflows/test_merge_requests.yml) bc why should we want to push a image which might contain errors?

Am I missing sth obvious here? :)

EDIT: @aendeavor just discovered that the description of the labels priority/medium and priority/low are interchanged

**Comment by aendeavor** [comment]
@radicand Is probably the best one to answer here.

> EDIT: @aendeavor just discovered that the description of the labels priority/medium and priority/low are interchanged

Fixed :D

**Comment by wernerfred** [comment]
Okay so I just discovered the discussion on the [maintainer team](https://github.com/orgs/docker-mailserver/teams/maintainers/discussions/3/) which provides basically [the solution](https://github.com/orgs/docker-mailserver/teams/maintainers/discussions/3/comments/4) I wanted to propose. As #11 is already merged this Issue can be closed I think as it seems that there is no real reason behind pushing every testing image to dockerhub.

**Comment by aendeavor** [comment]
I think we can focus this issue around the `default_on_push.yml` now :)

**Comment by wernerfred** [comment]
Quick notes / Brainstorming:

1. No need to push to testing repository on dockerhub for tests, this can be done locally as in the pr workflow.
2. No need to rebuild the image on the publish stage if [caching the docker layers among stages](https://github.com/docker/buildx#--cache-tonametypetypekeyvalue) just relabel it. (Although it is using only cached layers right now but it adds complexity to the workflow file and changes made on the one build steps might always be copied onto the second one which should be avoided
3. There should be no need to throw the build and test stages together (as in the current pr workflow) which would be a cleaner look/separation in the code as well as in the actions gui and the checks section of PRs

Your opinions on that?

**Comment by aendeavor** [comment]
> 1. No need to push to testing repository on dockerhub for tests, this can be done locally as in the pr workflow.

If possible, I'm all for it.

>     2. No need to rebuild the image on the publish stage if [caching the docker layers among stages](https://github.com/docker/buildx#--cache-tonametypetypekeyvalue) just relabel it. (Although it is using only cached layers right now but it adds complexity to the workflow file and changes made on the one build steps might always be copied onto the second one which should be avoided

That sounds good.

>  3. There should be no need to throw the build and test stages together (as in the current pr workflow) which would be a cleaner look/separation in the code as well as in the actions gui and the checks section of PRs

If possible, sure. But I don't get how you can do that.

---

In the end, this seems absolutely right to me. Could you provide a PR for that so we can see it _in action_? (pun not intended)

**Comment by radicand** [comment]
>     3. There should be no need to throw the build and test stages together (as in the current pr workflow) which would be a cleaner look/separation in the code as well as in the actions gui and the checks section of PRs

If we want to leverage a local build (no push action), we'd need to get creative with how to accomplish the tasks in different jobs. Github Actions runs a clean environment for each job, and the local docker cache would get reset between jobs. There's a possibility of leveraging the cache mechanism, but this would need to be tested further to see if/how that could work.

**Comment by radicand** [comment]
I've concluded some testing and have a way forward here. We can only persist in cache a single arch due to a Docker limitation (no estimated resolution), so it would work like:

1. Build amd64, cache local
2. Test amd64, from cache
3. Build amd64 (pulled from cache, not rebuilt),arm64,armv7
4. Push

I'll work on a PR with this.

**Comment by wernerfred** [comment]
> If we want to leverage a local build (no push action), we'd need to get creative with how to accomplish the tasks in different jobs. Github Actions runs a clean environment for each job, and the local docker cache would get reset between jobs. There's a possibility of leveraging the cache mechanism, but this would need to be tested further to see if/how that could work.

It should be possible using [github artifacts](https://docs.github.com/en/actions/guides/storing-workflow-data-as-artifacts) together with [docker save](https://docs.docker.com/engine/reference/commandline/save/) but it would be indeed an effort to bring this in the workflow right now.

Maybe we can keep this idea for later if the separation (of steps/checks/ui) is required/requested in future

**Comment by aendeavor** [comment]
> Maybe we can keep this idea for later if the separation (of steps/checks/ui) is required/requested in future

That's a good idea. We don't have to do it just for the sake of it:)

**Comment by wernerfred** [comment]
Another idea for the future (just stumbled over it and it fits under the topic "improve github actions") might be to add [triggers to manual run workflows](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow)

**Comment by aendeavor** [comment]
It that becomes necessary we should remember it. Right now, I think we do not need it.
