### ISSUE TITLE
Cannot send emails with SPOOF_PROTECTION=1

### ISSUE THREAD

**Issue by moqmar** [docker-mailserver/docker-mailserver#1340]
## Context

I have an OpenLDAP server ([osixia/openldap](https://hub.docker.com/r/osixia/openldap/) with the [postfix-book.schema](https://github.com/variablenix/ldap-mail-schema/blob/master/postfix-book.schema) added manually - seems like the version from your repository is [a bit different](https://www.diffchecker.com/tYsK8ILf), but this shouldn't change anything regarding this issue), with a user called `uid=momarqua` and `mail=moritz.marquardt@obelix.example.org`. The filters in `docker-compose.yml` are set as follows:

```yaml
LDAP_QUERY_FILTER_USER: (&(mail=%s)(mailEnabled=TRUE))
LDAP_QUERY_FILTER_GROUP: (&(mailGroupMember=%s)(mailEnabled=TRUE))
LDAP_QUERY_FILTER_ALIAS: (&(mailAlias=%s)(mailEnabled=TRUE))
LDAP_QUERY_FILTER_DOMAIN: (&(|(mail=*@%s)(mailalias=*@%s)(mailGroupMember=*@%s))(mailEnabled=TRUE))
DOVECOT_USER_FILTER: (&(objectClass=PostfixBookMailAccount)(|(mail=%u)(mailalias=%u)(uid=%n)))
DOVECOT_PASS_FILTER: (&(objectClass=PostfixBookMailAccount)(|(mail=%u)(mailalias=%u)(uid=%n)))
DOVECOT_PASS_ATTRS: uid=user,userPassword=password
SASLAUTHD_LDAP_FILTER: (&(|(mail=%U)(mailalias=%U)(uid=%U))(mailEnabled=TRUE))
```

I can receive emails without issues, I can send emails without issues, but as soon as I set `SPOOF_PROTECTION=1`, an error occurs.

## Expected Behavior
I should be able to send email as `moritz.marquardt@obelix.example.org`, or at least as any of `momarqua@obelix.example.org`, `moritz.marquardt@example.org` or `momarqua@example.org`, obviously given that I change the `mail` attribute in LDAP to the corresponding address.

## Actual Behavior

I get the following error message:

```
Dec 14 21:52:07 mail postfix/submission/smtpd[1751]: NOQUEUE: reject: RCPT from
port-1-2-3-4.dynamic.as20676.net[1.2.3.4]: 553 5.7.1 <moritz.marquardt@obelix.
example.org>: Sender address rejected: not owned by user momarqua@example.org;
from=<moritz.marquardt@obelix.example.org> to=<test@example.com> proto=ESMTP
helo=<[10.0.0.130]>
```

## Possible Fix

The workaround I'm using is to just disable `SPOOF_PROTECTION`, which obviously isn't a fix at all.

## Steps to Reproduce

TBD

## Your Environment

* Amount of RAM available: 24 GB (~20 GB free)
* Mailserver version used: `tvial/docker-mailserver:latest` pulled on 2019-12-15
* Docker version used: `18.09.6, build 481bc77`
* Environment settings relevant to the config: see **Context** above
* Any relevant stack traces ("Full trace" preferred): see **Actual Behaviour** above
* Also see #892 for a similar issue from 2018

**Comment by erik-wramner** [comment]
I'm not using LDAP. This sounds like a basic configuration mistake or a bug that should hit many installations. Anyone using LDAP who can comment?

**Comment by fbartels** [comment]
I am not using this feature, but looking at https://github.com/tomav/docker-mailserver/commit/a73692cc9fb98849bb0eac72311f4966ecaaca41 it feels like the differing mail domain could be the problem here (obelix.example.org vs example.org).

@moqmar could you retry with accounts on the same domain?

**Comment by moqmar** [comment]
Like I said, also with the "account name" and the email address being the same (momarqua@example.org, also set in LDAP as the mail address), it still doesn't work. I'm a bit confused as I can receive emails without any problems to the correct account without problems, but I cannot send any. Maybe I have understood an LDAP filter setting incorrectly, I'll try out some more things...

**Comment by moqmar** [comment]
I understood correctly that the spoof protection and incoming emails both use the `LDAP_QUERY_FILTER_USER` variable?

**Comment by luke-** [comment]
@moqmar I think so.

I ran into a similar problem, but in my setup I don't use the PostfixBook schema and also instead of the email address as user login I'm using the uid attribute (not in email form).

My workaround was to set SPOOF_PROTECTION to 0 and create an extra "/etc/postfix/ldap-senders.cf" query which returns the uid for the outgoing e-mail.

Additonal tweaks to enable spoof protection:
```
# ENABLE SPOOF PROTECTION
sed -i 's|smtpd_sender_restrictions =|smtpd_sender_restrictions = reject_authenticated_sender_login_mismatch,|' /etc/postfix/main.cf

# USE CUSTOM SENDERS LDAP FILE
postconf -e "smtpd_sender_login_maps=ldap:/etc/postfix/ldap-senders.cf"

# DON'T ADD MAIL SERVER DOMAIN to UID (e.g. uid@mail.server.hostname)
postconf -e "smtpd_sasl_local_domain = "
```

Using this I was able to get the SPOOF_PROTECTION working on my setup.

**Comment by erik-wramner** [comment]
Would it work to put those things in user-patches.sh in the config folder?

**Comment by luke-** [comment]
Yes, that works. 

But the best solution would be to introduce a new `LDAP_QUERY_FILTER_SENDERS` variable and ideally (at least for me) use the `uid` as `result_attribute` in the related ldap config.

The second problem here is the `smtpd_sasl_local_domain`, which need to be empty in my setup.
Related: https://github.com/tomav/docker-mailserver/commit/261a78c036582a57a5b6f25214f9fcbf2623f19c#diff-5114ee56265c2cc7cabd06812ad20a5d

Maybe we can always use an empty `smtpd_sasl_local_domain` if the `LDAP_QUERY_FILTER_SENDERS` returns the full e-mail address or a valid uid.

It will be a bit difficult to get such change backwards compatible, but should be feasible.

What do you think?

**Comment by erik-wramner** [comment]
As I'm not using LDAP myself I can't really test it. It needs to be backwards compatible and ideally I would like to have more than one person testing it. If you can make a PR that does the job in a backwards compatible way I can review the code as best as I can and merge. I'll flag this with help wanted as well, perhaps someone using LDAP will notice.

**Comment by artonge** [comment]
Hi,

Setting `smtpd_sasl_local_domain` to an empty string worked for me.
I have not created a new map file for `smtpd_sender_login_maps`, I have simply setted it to the existing `ldap-users.cf`. I only had to override `main.cf` in `/tmp/docker-mailserver` for that.
I have also overrided the `ldap-users.cf` file to use `uid` as `result_attribute`.

I did not set `SPOOF_PROTECTION` to `0`.

The only problem I see is that the users are able to send mail from a random domain, because we are only checking that the `uid` matches.

**Comment by codejamninja** [comment]
I am having the same issue. I'm using LDAP.

However there is one odd thing that I noticed in my logs. For whatever reason, it is only using the TLD (top level domain name) and completely dropped my main domain. What would cause this?

```
553 5.7.1 <jam@siliconhills.co>: Sender address rejected: not owned by user jam@co
```

**Comment by aendeavor** [comment]
What's the current status here?

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.

**Comment by moqmar** [comment]
This is still relevant, I have created a patch that I'll test, will create a PR if it works for me.

**Comment by moqmar** [comment]
Okay, the original configuration seems to work correctly now, so I guess it has indeed fixed itself... 🙈 

Adding a LDAP_QUERY_FILTER_SENDERS variable still provides a lot of flexibility for those cases, so I'll leave the PR open.
