### ISSUE TITLE
Sender address rejected of alias address defined by regex

### ISSUE THREAD

**Issue by jirislav** [docker-mailserver/docker-mailserver#1437]
When I (`mail@jkozlovsky.cz`) try to send an email using my alias address (`whatever@jkozlovsky.cz`), i get:
```
<whatever@jkozlovsky.cz>: Sender address rejected: not owned by user mail@jkozlovsky.cz
```

What I have in `postfix-regexp.cf`:
```
/.*@jkozlovsky.cz/ mail@jkozlovsky.cz
```

## Context
I cannot respond to people writing me while using the same address they wrote to. So it may seem like somebody else is responding.

## Expected Behavior
I can send email as any user defined by the regex. It's also stated in the documentation of `SPOOF_PROTECTION`.

```env
# Configures the handling of creating mails with forged sender addresses.
#
# empty => (not recommended, but default for backwards compatability reasons)
#           Mail address spoofing allowed. Any logged in user may create email messages with a forged sender address.
#           See also https://en.wikipedia.org/wiki/Email_spoofing
# 1 => (recommended) Mail spoofing denied. Each user may only send with his own or his alias addresses.
#       Addresses with extension delimiters(http://www.postfix.org/postconf.5.html#recipient_delimiter) are not able to send messages.
SPOOF_PROTECTION=1
```

## Actual Behavior
See upper description.

## Possible Fix
I don't know.

## Steps to Reproduce
1. Create similar regex alias.
2. Reload server
3. Send an email as someone matching the alias while having `SPOOF_PROTECTION=1`

## Your Environment
* Mailserver version used: `tvial/docker-mailserver:stable`
* Docker version used: `Docker version 19.03.8, build afacb8b7f0`
* Environment settings relevant to the config: `see upper description`
* Any relevant stack traces ("Full trace" preferred): `none`

**Comment by FlorianWendelborn** [comment]
Since I’m also running into the same issue, is there any security advantage of enabling `SPOOF_PROTECTION=1` for a generic wildcard (`mail@example.com` is allowed to use `.*@example.com`)? As far as I understand, in this specific use-case, there’s nobody else who could abuse the missing spoof protection, so does it matter that I had to temporarily turn it off?

**Comment by jirislav** [comment]
> Since I’m also running into the same issue, is there any security advantage of enabling `SPOOF_PROTECTION=1` for a generic wildcard (`mail@example.com` is allowed to use `.*@example.com`)? As far as I understand, in this specific use-case, there’s nobody else who could abuse the missing spoof protection, so does it matter that I had to temporarily turn it off?

This is a very good question, thank you.

The issue is that I have bunch of other addresses, where each of them should be restricted from using any other. Only the last one is the administrator's mail address, which should be allowed to become anyone who wants.

See
```
/root@jkozlovsky.cz/ root@jkozlovsky.cz
/robozonky@jkozlovsky.cz/ robozonky@jkozlovsky.cz
/gitlab@jkozlovsky.cz/ gitlab@jkozlovsky.cz
/gitlab-incoming@jkozlovsky.cz/ gitlab-incoming@jkozlovsky.cz
/nextcloud@jkozlovsky.cz/ nextcloud@jkozlovsky.cz
/.*@jkozlovsky.cz/ mail@jkozlovsky.cz
```

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.

**Comment by jirislav** [comment]
This issue has not been resolved yet. The sender address is still rejected, will you please open this issue @aendeavor? I don't have rights to do so.

**Comment by aendeavor** [comment]
Of course.

**Comment by aendeavor** [comment]
@jirislav I found this thread: <https://serverfault.com/questions/637726/sender-address-rejected-not-owned-by-user-in-postfix> Maybe it can help you?

Furthermore, you can for total correctness of your regex escape the `.` with `\.` to use `.´ literally (although I do not think this is a problem).

**Comment by aendeavor** [comment]
Please not this has become stale and will be closed due to inactivity soon.

**Comment by jirislav** [comment]
> @jirislav I found this thread: https://serverfault.com/questions/637726/sender-address-rejected-not-owned-by-user-in-postfix Maybe it can help you?
> 
> Furthermore, you can for total correctness of your regex escape the `.` with `\.` to use `.´ literally (although I do not think this is a problem).

I must've overlooked this suggestion.

Now, I've tried out to set it as the most voted answer suggests:
```cf
virtual_mailbox_maps = texthash:/etc/postfix/vmailbox pcre:/etc/postfix/regexp
virtual_alias_maps = texthash:/etc/postfix/virtual pcre:/etc/postfix/regexp
smtpd_sender_login_maps = texthash:/etc/postfix/virtual, hash:/etc/aliases, pcre:/etc/postfix/maps/sender_login_maps.pcre, pcre:/etc/postfix/regexp
```

But with no apparent result. I still see the same issue.

---

### But there's hope :heart_eyes: 

I've come to see that the sender login maps is basically enforced so that logged-in user matches the sender address exactly:
```sh
$ cat /etc/postfix/maps/sender_login_maps.pcre
/^(.*)$/   ${1}
```

.. and there's this "bug" which actually stops `sender_login_maps` from further evaluation once the left side matches the address, so the rule stops with the first `sender_login_maps.pcre` and does not proceed to the `/etc/postfix/regexp`.
- note that flipping these two files would make the "bug" even worse as only the `admin` account would be able to send email, nobody else
- it is actually very descriptively resolved in this answer: https://serverfault.com/a/1005041
- so the solution actually looks like this:

```cf
virtual_mailbox_maps = texthash:/etc/postfix/vmailbox
virtual_alias_maps = texthash:/etc/postfix/virtual pcre:/etc/postfix/regexp
smtpd_sender_login_maps = unionmap:{ texthash:/etc/postfix/virtual, hash:/etc/aliases, pcre:/etc/postfix/maps/sender_login_maps.pcre, pcre:/etc/postfix/regexp }
```

And it works! :tada: 

---

I don't currently have much time to commit the fix to a Pull Request, but it should be very easy to implement.  (I'd like this issue to be closed after it's fixed in `master`, so I'm not closing it now, because it's manual fix, not automatic)

**Comment by aendeavor** [comment]
So changing

``` INI
virtual_mailbox_maps = texthash:/etc/postfix/vmailbox
virtual_alias_maps = texthash:/etc/postfix/virtual
```

in `postfix/main.cf` to

``` INI
virtual_mailbox_maps = texthash:/etc/postfix/vmailbox
virtual_alias_maps = texthash:/etc/postfix/virtual pcre:/etc/postfix/regexp
smtpd_sender_login_maps = unionmap:{ texthash:/etc/postfix/virtual, hash:/etc/aliases, pcre:/etc/postfix/maps/sender_login_maps.pcre, pcre:/etc/postfix/regexp }
```

Is the solution? If that's all, I will take care this is being merged. @jirislav please head back to me as fast as you can to verify this is the solution.

---

**PLEASE NOTE**: This repository was being merged. Please use the currently maintained work: [docker-mailserver/docker-mailserver](https://github.com/docker-mailserver/docker-mailserver)

**Comment by jirislav** [comment]
> So changing
> 
> ```ini
> virtual_mailbox_maps = texthash:/etc/postfix/vmailbox
> virtual_alias_maps = texthash:/etc/postfix/virtual
> ```
> 
> in `target/postfix/main.cf` to
> 
> ```ini
> virtual_mailbox_maps = texthash:/etc/postfix/vmailbox
> virtual_alias_maps = texthash:/etc/postfix/virtual pcre:/etc/postfix/regexp
> smtpd_sender_login_maps = unionmap:{ texthash:/etc/postfix/virtual, hash:/etc/aliases, pcre:/etc/postfix/maps/sender_login_maps.pcre, pcre:/etc/postfix/regexp }
> ```
> 
> Is the solution? If that's all, I will take care this is being merged. @jirislav please head back to me as fast as you can to verify this is the solution.
> 
> **PLEASE NOTE**: This repository was being merged. Please use the currently maintained work: [docker-mailserver/docker-mailserver](https://github.com/docker-mailserver/docker-mailserver)

Yes, this is the solution to my problem, but the solution you have provided in https://github.com/docker-mailserver/docker-mailserver-new/pull/20 does create another issues, so I've created a review there.

**Comment by aendeavor** [comment]
Make sure to review it again please. I will push a new commit in the next few minutes when local tests succeed.
