### ISSUE TITLE
[FR] semver tags for docker images

### ISSUE THREAD

**Issue by euri10** [docker-mailserver/docker-mailserver#1757]
# Feature Request

## Context

when using dependabot or renovate bot (I'm using this one so maybe it's not relevant for dependabot, sorry if that's the case) the bot looks at semver of the docker image tags to tell yes/no there has been a major / minor / patch update (see https://docs.renovatebot.com/modules/versioning/#docker-versioning)

### Is your Feature Request related to a Problem?

on the previous repo the tags where not supported by renovate bot, `release-v7.2.0` isn't a legit semver (https://regex101.com/r/Ly7O1x/797) 

### Describe the Solution you'd like

having tags following semver

### Are you going to implement it?

Yes, because I know the probability of someone else doing it is low and I can learn from it.

### What are you going to contribute??

according to https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string there are 2 regex that could be used to parse the version.
I suggest using one of them and tags the docker image accordingly in the github workflow I suppose

### Alternatives you've considered

none

### Who will that Feature be useful to?

anyone using renovate bot, not sure about other "upgrade" bot tools

### What have you done already?

nothing, just went into this while configuring my numerous personal /homeserver images ! :)

**Comment by wernerfred** [comment]
Hey, take a look at the [lines that handles version tags](https://github.com/docker-mailserver/docker-mailserver/blob/e40c2593cc44d1bf09bec88517821ceb514d5ab9/.github/workflows/default_on_push.yml#L61) in the workflow file:

```
VERSION=latest
[[ $GITHUB_REF == refs/tags/* ]] && VERSION=${GITHUB_REF#refs/tags/v}
[[ $GITHUB_REF == 'refs/heads/stable' ]] && VERSION=stable
TAGS="${DOCKER_IMAGE}:${VERSION}"
[[ $VERSION =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]] && TAGS="$TAGS,${DOCKER_IMAGE}:latest"
```

So the tag used in the docker image will originate from the tags we push to the repository and not be generated through code.

**Comment by euri10** [comment]
ok I'll wait for tags to be pushed on docker hub then and most likely will close this !

can't find he old repo but I kind of remember git tags were exactly the same so there must have been something prepending the `release-` string

**Comment by aendeavor** [comment]
> We switched the CI/CD system that builds and pushes the docker image so i think the ```release-``` part came from the old CI/CD implementation (can someone confirm this?).

Indeed :)

**Comment by aendeavor** [comment]
> ok I'll wait for tags to be pushed on docker hub then and most likely will close this !
> 
> 
> 
> can't find he old repo but I kind of remember git tags were exactly the same so there must have been something prepending the `release-` string

Version `8.0.0` will soon be released when everything is confirmed stable - i.e. no major incident reports in a week.

**Comment by aendeavor** [comment]
I have linked #1763. With this PR, this issue can be closed too. The release of `8.0.0` will follow up soon.
