### ISSUE TITLE
[FR] Push docker images to Gihub Container Registry

### ISSUE THREAD

**Issue by joao-p-marques** [docker-mailserver/docker-mailserver#1759]
# Feature Request

Would it be possible to push the Docker image also to the [Gihub Container Registry](https://docs.github.com/en/packages/guides/about-github-container-registry) (ghcr.io)?

## Context

Images are only on DockerHub,.

### Is your Feature Request related to a Problem?

It would help avoid the new pull limits and some possible network restrictions from DockerHub.

### Describe the Solution you'd like

It can be easily done with the Github Action you already have to push to DockerHub. 

### Are you going to implement it?

Yes, because I know the probability of someone else doing it is low and I can learn from it.

### What are you going to contribute??

An update to the Github action to implement this. Some secrets set up would also be needed from the maintainers.

### Who will that Feature be useful to?

People hitting the DockerHub limits or behind a network that restricts access to it, and not to GHCR.

### What have you done already?

I have applied this approach in some other projects.

cc @Yajo 
@Tecnativa TT27819

**Comment by aendeavor** [comment]
What do you think @radicand?

I've got to admit, not sure about this one. I see little use in pushing to two different registries to be honest. Firstly, why wouldn't you be able to pull from docker.io when you're able to pull from ghcr.io. Secondly, the pull limit can be avoided with local caching registries.

However, if it's easy to implement, and does not increase complexity in the workflow, I guess there's not reason not to do it either.

---

PS: Aren't you guys the maintainers of tecnativa/docker-socket-proxy? What about tecnativa/docker-socket-proxy#33? I'm really tempted to couple this to the release of versioned tags 😆 😆 😆  Of course, I'm not going to do that, but seeing some tags would be really appreciated :D

**Comment by Yajo** [comment]
Oops we can't hide anymore! 🙈 😆 



> why wouldn't you be able to pull from docker.io when you're able to pull from ghcr.io

Docker Hub bans some countries, as you see in https://github.com/docker/hub-feedback/issues/369#issuecomment-214540296. Github doesn't: https://docs.github.com/en/github/site-policy/github-and-trade-controls#what-is-available-and-not-available.

**Comment by wernerfred** [comment]
It's not a big deal to implement. Keep in mind that we build up the tag for the push action through multiple variables (in [this](https://github.com/docker-mailserver/docker-mailserver/blob/master/.github/workflows/default_on_push.yml#L53) step) that already contains docker.io in it (@aendeavor have you kept docker.io in ${{ secrets.DOCKER_REPOSITORY }} or not?).

**Comment by aendeavor** [comment]
Line of reasoning seems fine to me. Please provide a PR.

Also, please note that although I'm fine with it, maybe there are reasons I cannot think of right now and other maintainers come up with them. If you already provided a PR, and there are reasons against it, it will be closed nevertheless. Just as a disclaimer.

We will also keep docker.io as the default registry. If this is approved, tell me what secrets are needed and I will add them.

**Comment by joao-p-marques** [comment]
Ok, thanks! @aendeavor 

I will try to make a PR soon, and we can discuss there.

About the secrets, you'd need to create a Personal Access Token for a user with access to the repo (a bot, if you want), with the following permissions:
* `read:packages`
* `write:packages`
* `delete:packages`

We usually place the necessary information in the variables `BOT_LOGIN` (username) and `BOT_TOKEN` (the PAT itself)

**Comment by wernerfred** [comment]
A separate workflow would be overkill imho. As you can see [here](https://github.com/marketplace/actions/build-and-push-docker-images#push-to-multi-registries) pushing to another registry is just a matter of adding one line.
What basically needs to be done at our repository is:

1. removing docker.io from the var then you don't need to touch the tag handling preparation part. 
2. Add part to login to ghcr
3. Change the almost last [line](https://github.com/docker-mailserver/docker-mailserver/blob/master/.github/workflows/default_on_push.yml#L91) to push to multiple registries

One challenge remains: if the TAGS var contains multiple tags ;)

**Comment by aendeavor** [comment]
> It's not a big deal to implement. Keep in mind that we build up the tag for the push action through multiple variables (in [this](https://github.com/docker-mailserver/docker-mailserver/blob/master/.github/workflows/default_on_push.yml#L53) step) that already contains docker.io in it (@aendeavor have you kept docker.io in ${{ secrets.DOCKER_REPOSITORY }} or not?).

I did.

**Comment by aendeavor** [comment]
> A separate workflow would be overkill imho. As you can see [here](https://github.com/marketplace/actions/build-and-push-docker-images#push-to-multi-registries) pushing to another registry is just a matter of adding one line.
> What basically needs to be done at our repository is:
> 
>     1. removing docker.io from the var then you don't need to touch the tag handling preparation part.
> 
>     2. Add part to login to ghcr
> 
>     3. Change the almost last [line](https://github.com/docker-mailserver/docker-mailserver/blob/master/.github/workflows/default_on_push.yml#L91) to push to multiple registries
> 
> 
> One challenge remains: if the TAGS var contains multiple tags ;)
> 
> EDIT: I wouldn't call the VARs BOT_* but naming them to match their purpose like: GHCR_*

I can update the secret, but I would like to see the "fully qualified registry name" somewhere in the workflow :D

**Comment by aendeavor** [comment]
@wernerfred do we really need another (bot) user to push to GHCR?

**Comment by wernerfred** [comment]
I have no overview of how many private vars exist and whats their purpose. So a new one might not be needed if a current one has the appropriate permissions as listed above.

**Comment by wernerfred** [comment]
When thinking about the push to whatever registry we could switch to use the [action](https://github.com/crazy-max/ghaction-docker-meta) to create correct branch and semver tags automatically by using the [semver configuration](https://github.com/crazy-max/ghaction-docker-meta#semver).

That would result in a push job that looks like this:

```
- name: Build image locally
  uses: docker/build-push-action@v2
  with:
    builder: ${{ steps.buildx.outputs.name }}
    context: .
    file: ./Dockerfile
    build-args: |
      VCS_REF=${{ github.sha }}
      VCS_VER=${{ github.ref }}
    platforms: linux/amd64,linux/arm/v7,linux/arm64
    push: true
    tags: |
      docker.io/${{ steps.docker_meta.outputs.tags }}
      ghcr.io/${{ steps.docker_meta.outputs.tags }}
    cache-from: type=local,src=/tmp/.buildx-cache
```

So it is easy to see where we push to and easy adjustable in the future as its written in the last part:
```
 tags: |
  docker.io/${{ steps.docker_meta.outputs.tags }}
  ghcr.io/${{ steps.docker_meta.outputs.tags }}
```

The mentioned action also has the option to tag every version of the semver automaticall so if we release ```8.0.0``` it will produce ```8.0.0```, ```8.0```, ```8``` and ```latest```. Pushes to branches would be named like the branch so master to ```master``` and stable to ```stable```

**Comment by aendeavor** [comment]
SGTM 👍🏼 

@wernerfred Could we somehow use the `:latest` tag in the action you mentioned when pushing to master?

**Comment by aendeavor** [comment]
We'd need to investigate how to push to GHCR with actions. I do not the idea of a the bot account - somehow overcomplicates an easy problem. @Yajo @joao-p-marques Please check whether a better solution exists

**Comment by joao-p-marques** [comment]
Right now that is the [recommended method](https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token), as the `GITHUB_TOKEN` does not support the permissions needed.

**Comment by wernerfred** [comment]
> @wernerfred Could we somehow use the `:latest` tag in the action you mentioned when pushing to master?

Just had a quick look at the docs but it seems like its not "easy" achievable. They see ```latest``` as the latest published version bc versions/releases are pushed  through tags. And a "normal" push to master is therefore no version (not even the latest one) but represents a specific branch.

**Comment by aendeavor** [comment]
> Right now that is the [recommended method](https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token), as the `GITHUB_TOKEN` does not support the permissions needed.

So no new user required (?). That'd be nice.

@wernerfred we can in the end always resort to a new workflow. Be assured, the creators of this PR can think about this too :D

**Comment by joao-p-marques** [comment]
@aendeavor @wernerfred I am currently testing the best alternative for this on our own repos. Once I have that figured out, I will open the PR here. 

About the user, I am afraid the only option is through a Personal Access Token... Whether that is a bot user or a regular one, shouldn't make a difference.

**Comment by Yajo** [comment]
Since this is a pretty common need (for us and the community), we're developing [a copier template for semver-tagged multiarch multiregistry docker images](https://github.com/Tecnativa/image-template).

We're testing that on some of our images. Once it's ready, it'll be a matter of applying the template to this project, and all will be done.

About the `:latest` tag, my vote is that it should target the latest release, not the latest commit to master. https://github.com/crazy-max/ghaction-docker-meta (the action we'll use to produce the image tags) supports the `:edge` tag for such purpose, which seems more sensible.

**Comment by aendeavor** [comment]
> Since this is a pretty common need (for us and the community), we're developing [a copier template for semver-tagged multiarch multiregistry docker images](https://github.com/Tecnativa/image-template).
> 
> We're testing that on some of our images. Once it's ready, it'll be a matter of applying the template to this project, and all will be done.

SGTM

> About the `:latest` tag, my vote is that it should target the latest release, not the latest commit to master. https://github.com/crazy-max/ghaction-docker-meta (the action we'll use to produce the image tags) supports the `:edge` tag for such purpose, which seems more sensible.

Although reasonable, the implicit Docker convention is to use `:latest` as the latest version of the image. Maintainers should debate about this or vote. When you're done @Yajo, we will decide:)

**Comment by wernerfred** [comment]
> > About the `:latest` tag, my vote is that it should target the latest release, not the latest commit to master. https://github.com/crazy-max/ghaction-docker-meta (the action we'll use to produce the image tags) supports the `:edge` tag for such purpose, which seems more sensible.
> 
> Although reasonable, the implicit Docker convention is to use `:latest` as the latest version of the image. Maintainers should debate about this or vote. When you're done @Yajo, we will decide:)

Can @docker-mailserver/maintainers please provide their opinion on this topic? If a decision is made I can also provide a PR (as I already posted it above) to meet the demand of this issue that we also push images to the github registry. 

To sum it up for the others: We are basically on the point to decide how to label the versions of the created images. The following shows the _current_ implementation:

| Event           | Ref                                       | Commit SHA | Docker Tags                         |
|--------------|-------------------------------|----------------|-------------------------------|
| `push`          | `refs/heads/master`             | `cf20257`       | `latest`                                  |
| `push`          | `refs/heads/stable`              | `cf20257`        | `stable`                                |
| `push tag`    | `refs/tags/v1.2.3`                 | `ad132f5`       | `1.2.3`                                   |

And this is the _proposed_ implementation:

| Event           | Ref                                       | Commit SHA | Docker Tags                         |
|--------------|-------------------------------|----------------|-------------------------------|
| `push`          | `refs/heads/master`             | `cf20257`       | `master`, `edge`                    |
| `push`          | `refs/heads/stable`              | `cf20257`        | `stable`                                |
| `push tag`    | `refs/tags/v1.2.3`                 | `ad132f5`       | `1.2.3`, `1.2`, `1`, `latest`        |

Using `edge` on master is an optional setting.

The semver tagging can be configured by `{{major}}.{{minor}}.{{patch}}` and prefixes as well. So it is possible to generate the following output when using `v{{major}}.{{minor}}` and `v{{version}}`

| Event           | Ref                                       | Commit SHA | Docker Tags                         |
|--------------|-------------------------------|----------------|-------------------------------|
| `push tag`    | `refs/tags/v1.2.3`                 | `ad132f5`       | `v1.2.3`, `v1.2`, `latest`        |

**Comment by aendeavor** [comment]
Decision will be made in the maintainers team in time and we will provide the outcome here when finished.
