### ISSUE TITLE
Issues messed up

### ISSUE THREAD

**Issue by clayrisser** [docker-mailserver/docker-mailserver#1760]
What is going on? I am very confused. I cannot find the pull requests and issues that I created here, and I my issues from the previous repo were moved here. Also, all my references to issues are now referring to random issues that I never created. Does anyone know what happened? 

The pull request to remove $myhostname from mydestination when ldap is enabled has been closed or removed without any explanation. I believe I have a valid case for this pull request, but the discussion on it was shut down.

https://github.com/docker-mailserver/docker-mailserver/pull/1734

**Comment by aendeavor** [comment]
The pull request you're referring to was deleted, since the repository was deleted. This was due to the original creator signaling he would transfer the original repo. _This_ is now the original repo, and not a fork anymore.

But, we made sure nothing got lost. If you look, you will see the change you wanted to implement is already present.

Is there anything else wrong otherwise?

**Comment by clayrisser** [comment]
@aendeavor everything is good. I just need the original pull request opened again. I really appreciate you explaining this. Thanks!

**Comment by aendeavor** [comment]
> I just need the original pull request opened again.

Since the content has already been merged, is there another PR you're referring too?

**Comment by wernerfred** [comment]
Maybe in other words:
We created a fork where you reopened your PR. But then the original repo got transferred to this organization (replacing the fork). Therefore the fork got deleted. But to not loose any work on the fork every PR got transferred or directly merged. The latter one happened to your PR in [this commit](https://github.com/docker-mailserver/docker-mailserver/commit/221d4ce187a9e0ec952bc926edb279cdc825a83e).

Not easy to follow along from an external POV but I hope it's understandable now.

**Comment by clayrisser** [comment]
Thanks so much. I understand now.

**Comment by aendeavor** [comment]
> Thanks so much. I don’t understand why I’m not getting credit for that code change though.

Because the PR was _not_ merged. I couldn't, because your PR had merge conflicts. Therefore I simply added the two lines in `start-mailserver.sh` myself.

**Comment by aendeavor** [comment]
Is there anything else or can this be closed?

**Comment by clayrisser** [comment]
It can be closed. Thanks
