### ISSUE TITLE
How to use an private CA with MailServer

### ISSUE THREAD

**Issue by 2NaughtyDogs** [docker-mailserver/docker-mailserver#1765]
Hello,
Thank you for developing this product. :)
We use a private CA, that the intermediate issuing cert has been signed by an offline Root Cert.
I am trying to get Mailserver to work with our internal certs.  However when I connect to the IMAP or SMTP ports I get an unable to verify CA error in the Docker mailserver logs.

Is there a way I can add our Offline Root Cert and Issuing Cert to MailServer?  

Thank you

**Comment by aendeavor** [comment]
No template, no support.
