### ISSUE TITLE
Using mailserver with default configs. Failing test. 

### ISSUE THREAD

**Issue by dmvict** [docker-mailserver/docker-mailserver#1767]
# Failing autotest. 

Hello, 

We're using Your mailserver in our autests for email-imap provider. 

We'd used [default config](https://github.com/docker-mailserver/docker-mailserver/tree/e198c10fe57522287f6563827b325bbb61b21eff#get-the-tools) and commands to create server. Our workflow: https://github.com/Wandalen/wFilesImap/blob/master/.github/workflows/PushImap.yml#L34 

In new version some features was added and default config is not usable. 
Now, I load old `.env` file: https://github.com/Wandalen/wFilesImap/pull/7/commits/b9594b3a10e1fc709c4aa0e97b4904f192da577e#diff-07eb63d6187af5a7088f430dc8a1789740b13c3547d28445df7d6f8661df3063R25

and run service `mailservice`:  https://github.com/Wandalen/wFilesImap/pull/7/commits/8fc41c8bb76162fb74f993b340fb0949d033dd3d#diff-07eb63d6187af5a7088f430dc8a1789740b13c3547d28445df7d6f8661df3063R26 

After this mail server starts but my client can't connects to it. 
```
          Logging in is disabled on this server
          source : 'authentication' Cannot connect to server
```
 https://github.com/Wandalen/wFilesImap/runs/1761080319#step:13:129

# Questions

What is the reason of it? How we can fix it?

**Comment by aendeavor** [comment]
Your workflow used the old

```
wget https://raw.githubusercontent.com/tomav/docker-mailserver/master/docker-compose.yml
```

This repository is now `docker-mailserver/docker-mailserver`. You must update your URLs, for example:

```
wget https://raw.githubusercontent.com/docker-mailserver/docker-mailserver/master/docker-compose.yml
```

**Comment by dmvict** [comment]
Thanks for Your attention!

I updated URLs. Client still can't connect to server. 
```
        Logging in is disabled on this server
          source : 'authentication' Cannot connect to server
```

Maybe, I will found solution later.

**Comment by aendeavor** [comment]
Interesting. I would try to replicate this issue offline. Maybe you can somehow replicate your workflow offline step by step.

I can only guess at the moment, but I'd say it's a configuration problem.

**Comment by wernerfred** [comment]
I think that we brought in a few problems by migrating the project from tomav to docker-mailserver org as a lot of URLs changed through this and people can't stay "at the old version" as GitHub does automatically redirect or 404.
My hope is that with 8.0.0 all those problems are gone. We should make sure to release 8.0.0 as fast as possible as there are even more things connected to it (like container registries etc.)

**Comment by aendeavor** [comment]
When the solution for #1769 is merged, we will check and release `8.0.0`

**Comment by dmvict** [comment]
Ok, thank you for Your help.

**Comment by aendeavor** [comment]
> Ok, thank you for Your help.
> 
> Can you estimate the time to release 8.0.0?

If everything works fine, today or tomorrow. As soon as #1753 and #1771 are merged:)

**Comment by wernerfred** [comment]
`8.0.0` just got published! Please rerun the tests at your environment and keep us updated. If we missed something additional that you can discover during your tests we will update it accordingly.

**Comment by dmvict** [comment]
> `8.0.0` just got published! Please rerun the tests at your environment and keep us updated. If we missed something additional that you can discover during your tests we will update it accordingly.

I rerun our tests. [Some mistake is still present in our config or on the server.](https://github.com/dmvict/wFilesImap/runs/1782007063?check_suite_focus=true#step:13:309)
Can you say me what IP address is the default for sever?

It seems like we connect to not existed server. 
I'd tried to connect manually using `telnet` 
```
$ telnet localhost imap
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
Connection closed by foreign host.
```

but mail server exists in the docker container and responds on commands like 
``` 
$ sudo ./setup.sh email list
user@domain.com
```

**Comment by wernerfred** [comment]
Can you please try to restart the mailserver after adding the first user and before running the tests?
`docker-compose restart`

@aendeavor as i tried to recreate his test offline i discovered that `SUPERVISOR_LOGLEVEL` is missing in `mailserver.env`

**Comment by aendeavor** [comment]
> Can you please try to restart the mailserver after adding the first user and before running the tests?
> `docker-compose restart`
> 
> @aendeavor as i tried to recreate his test offline i discovered that `SUPERVISOR_LOGLEVEL` is missing in `mailserver.env`

Oh my, you're right. I'm not using Compose and forgot that, but should be an easy fix and is luckily not related to the image. I will push a commit.

**Comment by dmvict** [comment]
So, what should I do? 

Do I wait? Or, do I add the command to workflow?

**Comment by wernerfred** [comment]
The Env is unrelated to your test as it is set to `warn` per default.
So please add the restart step to your workflow

**Comment by dmvict** [comment]
> Can you please try to restart the mailserver after adding the first user and before running the tests?
> `docker-compose restart`
> 
> @aendeavor as i tried to recreate his test offline i discovered that `SUPERVISOR_LOGLEVEL` is missing in `mailserver.env`

I use default server and have no practice with any mail sever. For our test we need mail server which is ready to work out the box.

**Comment by dmvict** [comment]
> The Env is unrelated to your test as it is set to `warn` per default.
> So please add the restart step to your workflow

Ok, thank you for your help.

**Comment by aendeavor** [comment]
If that doesn't work, enable `DMS_DEBUG` with the environment variable `DMS_DEBUG=1` and post the log.

**Comment by dmvict** [comment]
[Now, all is fine with our tests.](https://github.com/dmvict/wFilesImap/actions/runs/517476045)

Thank you for your help! Nice work! :+1:

**Comment by wernerfred** [comment]
Glad to help. I will close this Issue now, feel free to reach back if necessary :)
