### ISSUE TITLE
[BUG] Error when starting a BASH session

### ISSUE THREAD

**Issue by casperklein** [docker-mailserver/docker-mailserver#1769]
# Bug Report

### What is affected by this bug?
Starting a BASH session in the container.

### When does this occur?
When starting BASH.

### How do we replicate the issue?

`docker exec -it mail bash`

### Actual Behavior

`bash: by: command not found`

### Expected Behavior

No error should be shown

## Your Environment

- version: `edge`

## Cause

Missing quoting in the container file `/root/.bashrc`.

See: https://github.com/docker-mailserver/docker-mailserver/blob/1a36641c0c8c685de37f01ae31c7a2b1319989a9/target/scripts/start-mailserver.sh#L408-L449

Variable values with no spaces are no problem when unquoted. However this is a problem:

`POSTGREY_TEXT=Delayed by postgrey`

In that case, BASH tries to execute the `by` command on start.

## Solution

Add quotes to variable values in `/root/.bashrc`.

I will provide a PR.

**Comment by aendeavor** [comment]
Oh my, thank you for noticing this! I was so upset about seeing this but did not have the time to investigate.

Very much appreciated!

**Comment by casperklein** [comment]
Two questsions:

https://github.com/docker-mailserver/docker-mailserver/blob/1a36641c0c8c685de37f01ae31c7a2b1319989a9/target/scripts/start-mailserver.sh#L408-L449

These variables are missing:
```
POSTMASTER_ADDRESS
REPORT_SENDER
PFLOGSUMM_SENDER
PFLOGSUMM_TRIGGER
PFLOGSUMM_RECIPIENT
LOGWATCH_RECIPIENT
```

Should I add these while I am at it? At least `POSTMASTER_ADDRESS` was present before the refactoring.
Also `export` was prefixed to all variables before the change. The removal can lead to problems, when (custom) scripts rely on that.

My proposal is this:

`echo "export POSTMASTER_ADDRESS='${POSTMASTER_ADDRESS}'"`

(for all variables of course.)

**Comment by aendeavor** [comment]
> Two questsions:
> 
> 
> 
> https://github.com/docker-mailserver/docker-mailserver/blob/1a36641c0c8c685de37f01ae31c7a2b1319989a9/target/scripts/start-mailserver.sh#L408-L449
> 
> 
> 
> These variables are missing:
> 
> ```
> 
> POSTMASTER_ADDRESS
> 
> REPORT_SENDER
> 
> PFLOGSUMM_SENDER
> 
> PFLOGSUMM_TRIGGER
> 
> PFLOGSUMM_RECIPIENT
> 
> LOGWATCH_RECIPIENT
> 
> ```
> 
> 
> 
> Should I add these while I am at it? At least `POSTMASTER_ADDRESS` was present before the refactoring.
> 
> Also `export` was prefixed to all variables before the change. The removal can lead to problems, when (custom) scripts rely on that.
> 
> 
> 
> My proposal is this:
> 
> 
> 
> `echo "export POSTMASTER_ADDRESS='${POSTMASTER_ADDRESS}'"`
> 
> 
> 
> (for all variables of course.)

SGTM
