### ISSUE TITLE
Typo in setup.sh

### ISSUE THREAD

**Issue by williamdes** [docker-mailserver/docker-mailserver#1774]
https://github.com/docker-mailserver/docker-mailserver/blob/4616894fbfc4988fcebadaadc0ee7890b85ce874/setup.sh#L108

**Comment by williamdes** [comment]
cc @aendeavor

**Comment by aendeavor** [comment]
Yep, picked it up. Just release `8.0.0`, will resolve this with a future commit on master.

**Comment by aendeavor** [comment]
Done with cc7138e28f0634dc520f4c65c8a4d21d517995f8
