### ISSUE TITLE
[FR]: Please re-open PR #1643 (shared mailboxes) for merge

### ISSUE THREAD

**Issue by nekrondev** [docker-mailserver/docker-mailserver#1777]
# Feature Request
As described in https://github.com/docker-mailserver/docker-mailserver/pull/1643 (shared mailboxes) I would like to see this feature added into next release.

Many Thanks
Nek

**Comment by aendeavor** [comment]
I contacted the original creator of the PR. He must take the changed and re-implement them on the current `master` because the directory and file structure was changed. I will link the PR to this issue once it is opened.

**Comment by nekrondev** [comment]
Thanks for your support I'll keep watching :)

**Comment by aendeavor** [comment]
@nekrondev You can always take the changes form #1643 and open your own PR. This way, this issue won't get lost and maybe you can assist @matejak in writing some tests

**Comment by polarathene** [comment]
It's been two years, but for anyone still following this issue, a [feature request was raised again](https://github.com/docker-mailserver/docker-mailserver/issues/3091), but this time by a contributor that is willing to implement it, so it should be arriving in the near future :+1:
