### ISSUE TITLE
Postfix disconnected from unknown

### ISSUE THREAD

**Issue by springcomp** [docker-mailserver/docker-mailserver#1779]
I have a question with regards to sending emails from the host machine using this software as a docker container.

## Description

Using `msmtp` from the host machine, I send emails using this stack.
Logs report that the host machine's IP address is `unknown` even though `nslookup` reports the domain name correctly.

Is there some extra config to perform?

**Comment by aendeavor** [comment]
Edit `/etc/hosts`?

**Comment by springcomp** [comment]
@aendeavor in the docker container ?

**Comment by aendeavor** [comment]
The answer (how this would work) is actually trickier than you think, but **yes**, in the Docker container. You can use the`user-patches.sh` script for that.

**Comment by aendeavor** [comment]
I've dug this up for you. I'm using something like this myself:

``` BASH
if ! grep '<PUB IP>' /etc/hosts
then
  echo -e '\n<PUB IP> mail.<DOMAIN.TLD> mail' >> /etc/hosts
fi
```

**Comment by springcomp** [comment]
Thanks a lot I will try and apply the suggestion.

**Comment by aendeavor** [comment]
You can even use the `extra_hosts:` section with Docker Compose - may be easier.
