### ISSUE TITLE
Outgoing emails reported as SPAM by recipients.

### ISSUE THREAD

**Issue by springcomp** [docker-mailserver/docker-mailserver#1780]
## Subject 

I have questions about how to prevent emails originating from this stack as being reported as SPAM.

## Description

To the best of my knowledge, I have setup this stack an a host machine.
The DNS entries are configured appropriately.
Certificates are current, reverse DNS lookup points the the domain/machine.
DKIM is correctly setup and the signature is applied to outgoing emails.
SPF and DMARC records restrict senders to the host machine's IP V4 and V6 addresses.

However, mails outgoing from this domain are reported as SPAM by recipients.

Is there some extra checks I need to make ?

**Comment by aendeavor** [comment]
What do recipient logs show?

**Comment by springcomp** [comment]
@aendeavor Please, have a look at [this example](https://gist.github.com/springcomp/17b2bba77ed4db84eb93f86e54b16376).

**Comment by aendeavor** [comment]
There are a lot of MS headers floating around. Not sure whether one interferes, but very likely.

This: `Content-Type: text/plain; ` seems off, since the message looks like HTML. Check if MIME-Type is correct. This should however _not_ be related to the spam thing.

**Comment by springcomp** [comment]
Yes, plain text is correct. It's actually one the children of the `mixed alternative` parent.
The other being `text/html`. Both are present in the same message so that agents can choose which to display depending upon their capabilities.

Thanks for your feedback.

Seems there's not much else I can do...

**Comment by aendeavor** [comment]
Seems weird to me. I see no reason for rejection. SPF, DKIM and DMARC pass. Does this happen to all receivers?

**Comment by springcomp** [comment]
Yes, pretty much.

This is the second domain and server I setup. The first one was not so strict with regards to SPF but otherwise was identical. All messages ended up as spam from day one. To the point that the spam folder is just a regular folder for me 😏.

Until a few days ago, where the domain was explicitly blocked by all major mail vendors.

That's why I had to setup a new domain.

My [Masked Emails](https://github.com/springcomp/masked-emails) system lets users shield their real email address and allows to create unlimited mailboxes that can bounce, store temporarily or forward the incoming messages. In the hope of fighting spam.

Previously, I just blindly used `msmtp <recipient@real-email.address>` on whatever message sat on the corresponding mailboxes. Now to appear even more legitimate, I inject a `forwarded message` notice in the plain text and/or html content as you have seen in the example linked to in my previous answer. This allows me to create simpler headers with sender being an address on my domain and intended recipient.

**Comment by aendeavor** [comment]
I understand. I think the system you designed has to live with these kinds of issues. I mean, potentially being blocked by mail services. If you're really blocked by major blocklists, you should be able to figure this out, and try to solve this with them - there is nothing we can do here about this.

**Comment by springcomp** [comment]
Yes I figured.
Thanks a lot for the feedback.
