### ISSUE TITLE
[BUG] bl.spamcop.net domain expired, resulting in rejected e-mails

### ISSUE THREAD

**Issue by mrPjer** [docker-mailserver/docker-mailserver#1781]
See also https://www.reddit.com/r/sysadmin/comments/l9asw7/spamcop_domain_expiredparked/.

I noticed I'm not receiving e-mails recently. Checked the logs and found this:

```
mail_1                          | Jan 31 12:39:29 mail postfix/smtpd[21240]: NOQUEUE: reject: RCPT from $SERVER: 554 5.7.1 Service unavailable; Client host [$IP] blocked using bl.spamcop.net; from=<$SENDER> to=<$RECIPIENT> proto=ESMTP helo=<$SERVER>
```

Turns out the spamcop domain expired and now all lookups against the blocklist are treated as failures.

I assume spamcop will fix the domain issue. However, can the blocklist check be improved so that it doesn't reject all e-mail if the service is not available?

**Comment by mrPjer** [comment]
Here's a quick fix until this whole situation is resolved. To disable the spamcop check:

```
CONTAINER="your-container-name"
docker cp ${CONTAINER}:/etc/postfix/main.cf main.cf
# edit main.cf to comment out spamcop (in my case on line 47 and line 58)
docker exec $CONTAINER postfix reload
docker main.cf cp ${CONTAINER}:/etc/postfix/main.cf
```

I also tried overriding the hostname with
```
        extra_hosts:
            - "bl.spamcop.net:104.91.4.234"
```

in the compose file, but that didn't work.

**Comment by perry-amsterdam** [comment]
I have the same problem:
NOQUEUE: reject: RCPT from out-18.smtp.github.com[192.30.252.201]: 554 5.7.1 Service unavailable; Client host [192.30.252.201] blocked using bl.spamcop.net; from=<noreply@github.com> to=<perry@couprie.net> proto=ESMTP helo=<smtp.github.com>

**Comment by adrianrudnik** [comment]
Had to kill bl.spamcop.net. Thats quite the mishap sadly. Had to copy out `/etc/postfix/main.cnf` sections that contain `bl.spamcop.net`.

Then put it into the overriding `config/postfix-main.cf` file and remove any breaklines, leading to

```
smtpd_recipient_restrictions = check_recipient_access texthash:/tmp/docker-mailserver/postfix-receive-access.cf, permit_sasl_authenticated, permit_mynetworks, reject_unauth_destination, check_policy_service unix:private/policyd-spf, reject_unauth_pipelining, reject_invalid_helo_hostname, reject_non_fqdn_helo_hostname, reject_unknown_recipient_domain, reject_rbl_client zen.spamhaus.org

postscreen_dnsbl_sites = zen.spamhaus.org*3 bl.mailspike.net b.barracudacentral.org*2 bl.spameatingmonkey.net dnsbl.sorbs.net psbl.surriel.com list.dnswl.org=127.0.[0..255].0*-2 list.dnswl.org=127.0.[0..255].1*-3 list.dnswl.org=127.0.[0..255].[2..3]*-4
```

Not sure if that is the same for everyone, so double check.

At least emails getting delivered again after a container restart.

**Comment by aendeavor** [comment]
cc @casperklein @wernerfred @fbartels

This is concerning. We could remove the spamCop domain and build this into `8.0.1`, so everyone using `:latest` would receive the "patch".

**Comment by aendeavor** [comment]
NOTE: @mrPjer Thank you for reporting this, but we discourage **_not_** using the actual templates. Therefore, your issue is marked with the label `issue/template not used (1)` which is a warning. To remove it, adjust your description to use the templatei

**Comment by fbartels** [comment]
Yes, that sounds like this is something that should be released as a single change on top of the last release.

**Comment by janhoffmann** [comment]
@mrPjer  thank you for your hotfix, saved me!

you have a small error in your command:
> docker main.cf cp ${CONTAINER}:/etc/postfix/main.cf

cp and main.cf need to be switched, i think it would be a good idea to correct the post to have a working hotfix for all.

**Comment by aendeavor** [comment]
`8.0.1` was just released ans should be available in the next few minutes.

**Comment by wernerfred** [comment]
The hotfix patch is now available within `edge`, `8`, `8.0`, `8.0.1` and `latest`. Missing right now: `stable`.

**Comment by aendeavor** [comment]
@wernerfred I could take care of this. Do we want stable to be on `8.0.1` too? I'd say yes.

**Comment by wernerfred** [comment]
I would say every version that got a tag should be merged into stable. I think I could provide a workflow that gets triggered by pushing a release tag then create a PR which wants to merge current master into stable. What do you think about it?

**Comment by williamdes** [comment]
Detail I would ask to have:
- releases *must* have a changelog block
- GitHub releases *should* have an as detailed as possible description

@aendeavor (I have to look at commits and then the PR and then the issue to understand your release message)
My point of view is: having a clear changelog and release message helps immediate updates to be made on production ENVs

**Comment by aendeavor** [comment]
@williamdes updated the release description

**Comment by williamdes** [comment]
> @williamdes I updated the release description

:100: 
Perfect!
You made me happy ^^

**Comment by aendeavor** [comment]
> I would say every version that got a tag should be merged into stable. I think I could provide a workflow that gets triggered by pushing a release tag then create a PR which wants to merge current master into stable. What do you think about it?
> 
> EDIT: `8.0.1` should definitly go straight to `stable` as otherwise `stable` would contain now a faulty/unstable version.

I would rather rebase stable onto `8.0.1` than create a merge. This way the versions are in sync. On the other hand, do we actually need stable?

**Comment by williamdes** [comment]
> > I would say every version that got a tag should be merged into stable. I think I could provide a workflow that gets triggered by pushing a release tag then create a PR which wants to merge current master into stable. What do you think about it?
> > EDIT: `8.0.1` should definitly go straight to `stable` as otherwise `stable` would contain now a faulty/unstable version.
> 
> I would rather rebase stable onto `8.0.1` than create a merge. This way the versions are in sync. On the other hand, do we actually need stable? I mean, a release should be considered stable anyways:) What do you think?

Why not just fast forward ?

I would say we need it just like a branch that anyone can follow

**Comment by aendeavor** [comment]
> Why not just fast forward ?
> 
> I would say we need it just like a branch that anyone can follow

The rebase implicitly is a fast-forward :)

**Comment by casperklein** [comment]
> On the other hand, do we actually need stable? I mean, a release should be considered stable anyways:) What do you think?

I thought about the same / haven't understand why there is a stable branch. If I get it correctly, the stable branch is always identical to the latest version tag (at the moment v8.0.1).

**Comment by wernerfred** [comment]
I will think about how to setup this via workflows and provide a PR. Will also dive into Changelog actions.

**Comment by arkadiusz-wieczorek** [comment]
If someone uses `tvial/docker-mailserver:latest` I recommend to change image to: `ghcr.io/docker-mailserver/docker-mailserver:latest` due to fact that the docker hub needs some time to pull new images.

![image](https://user-images.githubusercontent.com/5663277/106443410-bc220300-647c-11eb-8f65-44cd029cf3e5.png)

**Comment by williamdes** [comment]
> If someone uses `tvial/docker-mailserver:latest` I recommend to change image to: `ghcr.io/docker-mailserver/docker-mailserver:latest` due to fact that the docker hub needs some time to pull new images.
> 
> ![image](https://user-images.githubusercontent.com/5663277/106443410-bc220300-647c-11eb-8f65-44cd029cf3e5.png)

I would say that it is not true and it is more because the image is now at: https://hub.docker.com/r/mailserver/docker-mailserver
![image](https://user-images.githubusercontent.com/7784660/106443750-2b97f280-647d-11eb-9f8c-8f32bbe3cadf.png)

**Comment by aendeavor** [comment]
> If someone uses `tvial/docker-mailserver:latest` I recommend to change image to: `ghcr.io/docker-mailserver/docker-mailserver:latest` due to fact that the docker hub needs some time to pull new images.
> 
> ![image](https://user-images.githubusercontent.com/5663277/106443410-bc220300-647c-11eb-8f65-44cd029cf3e5.png)

Or just use the **_actual new image_** `mailserver/docker-mailserver`.

**Comment by williamdes** [comment]
@tomav Could you change the image description/title on Docker Hub ?

**Comment by arkadiusz-wieczorek** [comment]
@williamdes there is information on https://hub.docker.com/r/tvial/docker-mailserver:

> Migration / Deprecation Notice - We Migrated
> 
> We have migrated this repository to the Docker Mailserver Organization. This repository is therefore not maintained anymore. Please head over to the new repository for issues, pull requests and discussions. All work is now done there.

**Comment by aendeavor** [comment]
> @williamdes there is information on https://hub.docker.com/r/tvial/docker-mailserver:
> 
> > Migration / Deprecation Notice - We Migrated
> > We have migrated this repository to the Docker Mailserver Organization. This repository is therefore not maintained anymore. Please head over to the new repository for issues, pull requests and discussions. All work is now done there.

This is the old master before I force-pushed the new master. Dockerhub seems to still resolve the old README, which is actually fine :D
