### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Petemtl** [docker-mailserver/docker-mailserver#1786]
# Bug Report

### How do we replicate the issue?

1.
2.
3.
4.

## Your Environment

- version: `v`
- available RAM: `GB`
- Docker version: `v`

### Environment Variables

```CFG

```

### Relevant Stack Traces

```BASH
# BEGIN

# END
```

**Comment by fbartels** [comment]
@Petemtl was this issue created by accident? It does not contain any description.

**Comment by Petemtl** [comment]
Yes, it was, sorry  I'm still learning
