### ISSUE TITLE
Spamassassing do not add SPAM tags on tvial/docker-mailserver:release-v7.0.0

### ISSUE THREAD

**Issue by daitangio** [docker-mailserver/docker-mailserver#1790]
# Spamassassing config does not work
First of all, thank you for this fantastic project :)

My email do not get tagged as SPAM, but it is a way long above spam configured levels

I have this setup

Image: tvial/docker-mailserver:release-v7.0.0
env-setup relevant config:
```
  ENABLE_SPAMASSASSIN=1
  
  #If Enabled, SPAM goes to your inbox with added SPAM header, you can then move it to a specific SPAM folder with SIEVE rules
  SPAMASSASSIN_SPAM_TO_INBOX=1
  
  # add spam info headers if at, or above that level:
  SA_TAG=0.1
  
  # add 'spam detected' headers at that level
  SA_TAG2=5.0
  
  # triggers spam evasive actions
  SA_KILL=6.31
  
  # add tag to subject if spam detected
  SA_SPAM_SUBJECT=***SPAM*****
```

I get email with spam headers 

I read in the log

>   Feb  3 10:43:23 juno docker-mail[917]: Feb  3 09:43:23 mail amavis[984]: (00984-01) spam-tag, <asset@formalrefund.guru> -> <jj@gioorgi.com>, No, score=6.01 tagged_above=0.1 required=6.31 tests=[FROM_FMBLA_NEWDOM=1.498, HTML_FONT_LOW_CONTRAST=0.001, HTML_IMAGE_ONLY_32=0.001, HTML_MESSAGE=0.001, HTML_MIME_NO_HTML_TAG=0.635, MIME_HTML_ONLY=0.1, MIME_QP_LONG_LINE=0.001, RDNS_NONE=1.274, SPF_HELO_PASS=-0.001, SPF_PASS=-0.001, URIBL_BLOCKED=0.001, URIBL_DBL_SPAM=2.5] autolearn=no autolearn_force=no

And in the spam email I read

> X-Spam-Flag: NO
> X-Spam-Score: 6.01

Where am I wrong?
Why amavis log talk about spam (it should be spamassassin)?

**Comment by aendeavor** [comment]
Before we debug this, is there any reason you're not using the new `maiserver/docker-mailserver` image? The README will guide you, just click on the badge that shows the amount of pulls.

**Comment by daitangio** [comment]
I have not yet time to upgrade and check for compatibility, sorry :(
By the way I think I have found the issue: every time I change this parameter I also need to do a docker down+up, because the docker restart seems it does not upgrade the parameters.

**Comment by aendeavor** [comment]
> because the "docker restart" seems it does not upgrade the parameters inside amavis etc

Yes

**Comment by daitangio** [comment]
After upgrading to "stable" the problem solved. 
I noted the old version missed also the MOVE_SPAM_TO_JUNK variables.
Leaving the issue for future reference on the old tvial/docker-mailserver:release-v7.0.0 version
