### ISSUE TITLE
Relay Host

### ISSUE THREAD

**Issue by jphilippou** [docker-mailserver/docker-mailserver#1791]
I have questions about configuring the mail relay host. For security purposes, is there any way to not include the RELAY_USER and RELAY_PASSWORD in the env file? Possibly like specifying % or * as the <domain> in the setup.sh commands.

Jim

**Comment by casperklein** [comment]
Probably this is what you are looking for: https://docs.docker.com/compose/environment-variables/#pass-environment-variables-to-containers
