### ISSUE TITLE
[BUG] setup.sh: "The mailserver is not running!"

### ISSUE THREAD

**Issue by swiesend** [docker-mailserver/docker-mailserver#1794]
# Bug Report

The latest version of `setup.sh` does not detect my running `mail` container although it is running with image `tvial/docker-mailserver:latest`.

This is probably __NOT__ a duplicate of https://github.com/docker-mailserver/docker-mailserver/issues/1774, but maybe affected by https://github.com/docker-mailserver/docker-mailserver/commit/cc7138e28f0634dc520f4c65c8a4d21d517995f8#r46825784

```sh
$ cat ./setup.sh | grep 'docker.io/mailserver/docker-mailserver:latest'
                    'docker.io/mailserver/docker-mailserver:latest'
    IMAGE_NAME=${NAME:-docker.io/mailserver/docker-mailserver:latest}
```

## Context

I downloaded the new `setup.sh` from master:
```
mv setup.sh setup.sh.`date -I`
wget -q -O setup.sh https://raw.githubusercontent.com/tomav/docker-mailserver/master/setup.sh
chmod a+x ./setup.sh
```

A previous `setup.sh` from __2021-01-20__ is still working as expected. So the problem must be in one of the [commits](https://github.com/docker-mailserver/docker-mailserver/commits/master/setup.sh):

- 4616894fbfc4988fcebadaadc0ee7890b85ce874
- cc7138e28f0634dc520f4c65c8a4d21d517995f8
- 70267d89e562625a9c7b406796292daea8104cf9

### What is affected by this bug?

All `./setup.sh debug` commands:
```sh
    ./setup.sh debug fetchmail
    ./setup.sh debug fail2ban [<unban> <ip-address>]
    ./setup.sh debug show-mail-logs
    ./setup.sh debug inspect
    ./setup.sh debug login <commands>
```

### When does this occur?

On invocation

### How do we replicate the issue?

Try `./setup.sh debug show-mail-logs` with `tvial/docker-mailserver:latest`

## Your Environment

problematic `setup.sh` with commit `70267d89e562625a9c7b406796292daea8104cf9`: https://github.com/docker-mailserver/docker-mailserver/blob/70267d89e562625a9c7b406796292daea8104cf9/setup.sh

```
latest: Pulling from tvial/docker-mailserver
Digest: sha256:c0d8c767c37c1a7441d89a6db6cdb361ef04470323e5e0a9b262362542a43bc8
```
```
$ docker --version
Docker version 19.03.13, build 4484c46d9d
```

### Relevant Stack Traces

```
$ ./setup.sh debug show-mail-logs
The mailserver is not running!

$ ./setup.sh debug inspect
Image: docker.io/mailserver/docker-mailserver:latest
Container: Not running, please start docker-mailserver.

$ ./setup.sh debug fetchmail
fetchmail: no mailservers have been specified.

––– UNCHECKED ERROR
  – script    = setup.sh
  – function  = _docker_image / ${CRI}
  – line      = run
  – exit code = --rm
```
Container is running:
```sh
$ docker ps -a
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS                  PORTS                                                                                                                       NAMES
2115f3535913        tvial/docker-mailserver:latest   "supervisord -c /etc…"   10 hours ago        Up 10 hours             0.0.0.0:25->25/tcp, 110/tcp, 0.0.0.0:143->143/tcp, 0.0.0.0:587->587/tcp, 465/tcp, 995/tcp, 0.0.0.0:993->993/tcp, 4190/tcp   mail
```

**Comment by aendeavor** [comment]
And here is the problem:

>  it is running with image tvial/docker-mailserver:latest

The latest setup script does not work with **_the new image `mailserver/docker-mailserver`_**. It get's the container name by checking labels, and the new image uses proper OCI compliant labels, the old image has other labels.

Put simply: You're using the wrong image, that's it.

What you can do now: Use the old image and checkout a commit where `setup.sh` was not altered, somewhere before release `v8.0.0`, or use the new image and everything works.

**Comment by swiesend** [comment]
Oh, wait. I guess I have missed some major migration. Thanks for the quick reply!

So I'll go for `https://hub.docker.com/r/mailserver/docker-mailserver/`

**Comment by aendeavor** [comment]
> Oh, wait. I guess I have missed some major migration. Thanks for the quick reply!
> 
> So I'll go for `https://hub.docker.com/r/mailserver/docker-mailserver/`

Yes. You want to use `docker.io/mailserver/docker-mailserver` as the new image.

**Comment by swiesend** [comment]
I went for `mailserver/docker-mailserver:stable` and it works like a charm:
```
$ ./setup.sh debug show-mail-logs
Feb  6 17:14:50 mail dovecot: master: Dovecot v2.3.4.1 (f79e8e7e4) starting up for imap, lmtp
Feb  6 17:14:50 mail opendkim[598]: OpenDKIM Filter v2.11.0 starting (args: -f)
...
```

Thanks again.

**Comment by wernerfred** [comment]
We have to thank you for this awesome issue description ❤️
