### ISSUE TITLE
[BUG] SASL is enabled with ENABLE_SASLAUTHD=0 but only when SMTP_ONLY=1

### ISSUE THREAD

**Issue by dgraziotin** [docker-mailserver/docker-mailserver#1796]
# Bug Report

I believe this is the same as #1687. I do not want SASL.

Using `ENABLE_SASLAUTHD=0` and `SMTP_ONLY=1` results in the following log error (and `could not connect to this SMTP server` error in Apple Mail).

This is the relevant log error:

```
Feb  7 14:15:31 mailer-ams postfix/submission/smtpd[892]: warning: SASL: Connect to private/auth failed: Connection refused
Feb  7 14:15:31 mailer-ams postfix/submission/smtpd[892]: fatal: no SASL authentication mechanisms
```

## Context

Fresh installation.

### What is affected by this bug?

Using SMTP.

### When does this occur?

Every time.

### How do we replicate the issue?

I follow the [default installation instructions](https://github.com/docker-mailserver/docker-mailserver#get-the-tools).

Besides adding domain and hostname to `.env`, this is what I edit in `mailserver.env`:

```
SMTP_ONLY=1
ONE_DIR=1
PERMIT_DOCKER=host
SSL_TYPE=manual
SSL_CERT_PATH=/path/to/fullchain.cer
SSL_KEY_PATH=/path/to/cert.key
```
I keep `ENABLE_SASLAUTHD=0` with its default value.

`docker-compose.yml` only mounts `/path/to/`. https://www.checktls.com is happy with the settings, gives 100% and valid certificate.

# Workaround

Setting `SMTP_ONLY=` (to empty) fixes the issue.

## Your Environment

- version: `docker.io/mailserver/docker-mailserver:latest`
- available RAM: `8GB`
- Docker version: `Docker version 20.10.3, build 48d30b5`

**Comment by aendeavor** [comment]
I will shortly look in the script. In the meantime, you want a mailserver that only sends mails, right (because you want to use `SMTP_ONLY=1`)? If not, why are you using the variable? And why would you try to connect via a MUA?

**Comment by aendeavor** [comment]
@wernerfred These lines in `start-mailserver.sh` seem odd to me:

https://github.com/docker-mailserver/docker-mailserver/blob/df3ef4865f107b38ff8dc034fba03da88de630e3/target/scripts/start-mailserver.sh#L952-L957

I would actually use 

``` BASH
  if [[ ${ENABLE_SASLAUTHD} -eq 1 ]] || [[ ${SMTP_ONLY} -eq 0 ]]
  then
    sed -i -E \
      's+^smtpd_sasl_auth_enable =.*+smtpd_sasl_auth_enable = yes+g' \
      /etc/postfix/main.cf
  else
    sed -i -E \
      's+^smtpd_sasl_auth_enable =.*+smtpd_sasl_auth_enable = no+g' \
      /etc/postfix/main.cf
  fi
```

because I too see `smtpd_sasl_auth_enable = yes` when running `docker exec <MAILCONTAINER> grep "smtpd_sasl_auth_enable" /etc/postfix/main.cf`, which seems off.

**Comment by dgraziotin** [comment]
> I will shortly look in the script. In the meantime, you want a mailserver that only sends mails, right (because you want to use `SMTP_ONLY=1`)? If not, why are you using the variable?
> 

Correct. All I would like it for is to send e-mails, without a relay.

> Please also do me a favor and run `grep "smtpd_sasl_auth_enable" /etc/postfix/main.cf`.

Interestingly,
```
docker exec -it mailer grep "smtpd_sasl_auth_enable" /etc/postfix/main.cf
smtpd_sasl_auth_enable = no
```

**Comment by aendeavor** [comment]
Oh wait, actually this seems to be fine - I incorrectly evaluated the `if` expression. My "improvement" from my second comment is valid though.

Using

``` BASH
if [[ ${ENABLE_SASLAUTHD} -eq 0 ]] && [[ ${SMTP_ONLY} -eq 1 ]]
```

we can see that `smtpd_sasl_auth_enable` will be set to `no` if both `${ENABLE_SASLAUTHD}` is set to `0` and `${SMTP_ONLY}` is set to `1`, which is true in your case. So far, so good. Why is SASL still on? @casperklein @wernerfred any idea?

**Comment by aendeavor** [comment]
There is this line in `master.cf`

https://github.com/docker-mailserver/docker-mailserver/blob/df3ef4865f107b38ff8dc034fba03da88de630e3/target/postfix/master.cf#L20

which is never touched. Could be the "error" source. @dgraziotin Could you replace this line, write a `no` where the `yes` is currently and restart Postfix and try again?

**Comment by dgraziotin** [comment]
That seems to be working. 

Now I am getting login rejected but this is because I am trying from a non-allowed IP (my home IP against my server IP). For that one to work I need `ENABLE_SASLAUTHD=1` in any case, correct?

**Comment by aendeavor** [comment]
> [...] For that one to work I need `ENABLE_SASLAUTHD=1` in any case, correct?

I guess yes :) I will see what the tests say and provide a PR. If this is somehow not compatible with the tests, you can always fall back to using `user-patches.sh`.

**Comment by dgraziotin** [comment]
Thank you. Feel free to leave this open in case you need a reminder. Otherwise close it.

**Comment by aendeavor** [comment]
The PR I will link to this issue will close it :)
