### ISSUE TITLE
[FR] Custom mynetworks Settings

### ISSUE THREAD

**Issue by maxswjeon** [docker-mailserver/docker-mailserver#1806]
# Feature Request

## Context
Cloud Service Providers, especially Oracle Cloud, does not offer your Public IP to an ethernet adapter. Rather, they give you private address (10.0.0.0/24) and redirects all traffic from the public IP.

### Is your Feature Request related to a Problem?
Sort of, since `PERMIT_DOCKER` environment variable does not allow you to set specific IP rather than `host`/`network`/`connected-network`

### Describe the Solution you'd like
Allow `PERMIT_DOCKER` to accept IP Addresses (and ranges) and use it for setting up postfix `mynetworks`

### Are you going to implement it?
Yes, because I know the probability of someone else doing it is low and I can learn from it.

### What are you going to contribute??
Edit [start-mailserver.sh#L1377](https://github.com/docker-mailserver/docker-mailserver/blob/master/target/scripts/start-mailserver.sh#L1377) to recognize IP Ranges and add to `/etc/postfix/main.cf`

### Alternatives you've considered
Mounting the `/etc/postfix/main.cf` via docker bind volume mount, but if then, there is no meaning to this image

### Who will that Feature be useful to?
Cloud users, which I have already described in the first Context

### What have you done already?
Attaching bash to the container and edited the `/etc/postfix/main.cf`

**Comment by casperklein** [comment]
Maybe I am wrong, but I think you misunderstood the `PERMIT_DOCKER` setting. It allows relaying for the IP/Network address of the local Docker network interface. A typical use case is, to allow the host, that runs the docker container, to send (relay) mails without authentication. For example, if you want to use the `mail` command on the host to send (unauthenticated) mails via the docker-mailserver container.

If you are going to implement to allow custom IP/networks for relaying, this should be done with a separate variable, e.g. `$ALLOW_RELAY`, because it's not related to the docker network interface.

> Mounting the /etc/postfix/main.cf via docker bind volume mount, but if then, there is no meaning to this image

There is already an easy way to achieve that. Take a look at https://github.com/docker-mailserver/docker-mailserver/wiki/Override-Default-Postfix-Configuration

**Comment by casperklein** [comment]
> does not offer your Public IP to an ethernet adapter.

That should be no problem for normal operation. What exactly are you trying to achieve?

There is normally no need to include the private/public IP address of the host in `mynetworks`. The host to container communication uses the separate docker host network interface, e.g.

```
br-6d0ab9fde5aa: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.27.0.1  netmask 255.255.0.0  broadcast 172.27.255.255
        ether 02:42:ae:1c:ab:aa  txqueuelen 0  (Ethernet)
        RX packets 78561  bytes 7573214 (7.2 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 78624  bytes 7733897 (7.3 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

So if your container got the IP address 172.27.0.2, communication from host to container is `172.27.0.1 --> 172.27.0.2`.

**Comment by maxswjeon** [comment]
If you use `docker-compose`, there will be servers outside of the network, and there will multiple bridge networks. Yes, setting docker-mailserver with `host` network driver might help, but it is not a must. 

Some linux systems have trouble with connecting host with the bridge driver addres .(this is not docker-mailserver problem rather docker or iptables problem but I had been struggling for solution and I gave up) In those cases, from the other server, we can connect to the mailserver with public IP offered. Then the source IP would be the public IP, not the internal 172.20.0.2 or etc. So trusting (allow relaying) from the public IP is the solution for some cases.
