### ISSUE TITLE
[FR] Persistent OpenDKIM config

### ISSUE THREAD

**Issue by LukeMarlin** [docker-mailserver/docker-mailserver#1807]
# Feature Request

## Context

What headers DKIM should encrypt is a choice that vary between users and usage. Currently, they are not configurable in this image.

### Is your Feature Request related to a Problem?

No

### Describe the Solution you'd like

I guess there are multiple possibilities here, there is the usage of startup scripts as described in the wiki, but it doesn't look practical for this. I see two other solutions:
* A new volume for the entire config of opendkim so it is persisted
* A new env value/config option

### Are you going to implement it?

Yes, because I know the probability of someone else doing it is low and I can learn from it.

### What are you going to contribute??

Well, real answer isn't the one above, it's more nuanced. I'd first need to know what would be a good way, then based on that I could possibly implement it.

### Alternatives you've considered

None

### Who will that Feature be useful to?

Anyone wanting to customize opendkim behaviour, especially header list

### What have you done already?

Modified my DKIM config, lost it through restart, cried a little.
I didn't try the scripts although I read the wiki, I didn't try solutions that could be integrated in the image yet because I'd like to know what would be the best way, or if it would be considered a valuable addition

**Comment by aendeavor** [comment]
I think the disadvantage of the added complexity will outweigh the new added features. Unless the're is a very easy implementation (which may exist, don't get me wrong), this could introduce backwards incompatible behaviour. Of course, you can implement it and open a PR, I just cannot guarantee a merge.

**Comment by LukeMarlin** [comment]
Thanks for the respsonse @aendeavor. At the very least, I'll try to update the current file as there are some things that could be problematic in omit headers, but I need some time to investigate.

Same goes for being able to configure, I'm currently looking into what would be a proper config for me, then I'll try to see if I can provide an easy way into this docker. Otherwise I'll write a script that could be linked somewhere in doc. I hope to be able to bring new elements this week.
