### ISSUE TITLE
Runtime changes for Razor and Clam

### ISSUE THREAD

**Issue by FSeidinger** [docker-mailserver/docker-mailserver#1815]
# I would like some feedback concerning a use case with the razor agent.

## Description

From what I understand of the razor configuration of docker-mailserver, the account/identity creation by the razor-admin is done in the Dockerfile and therefore at build time. The created identity then is the same for all instances (users) of this image. In my case the identity was created on January, 31 at 16:40.

Is this the intended way of using razor? Or should this not be done on a container/user basis?

**Comment by aendeavor** [comment]
I'm not very familiar with razor, but yes, configuration is done at build-time. Does this pose a problem?

**Comment by FSeidinger** [comment]
I checked the razor-admin man page concerning the registration process and its consequences:

```
razor-admin" must have one of the following arguments:
  -register"

  Registers a new identity, used for authenticating with Razor Nomination Servers. Identities are a user + password pair stored
  in "<razorhome>/identity-<user>". The first time "razor-admin -register" exits successfully, a symlink "identity" is created to
  point to the active "identity-<user>" file. After that, new identities can be created, but in order to use them the symlink
  "identity" must be changed to point to them. In general, it should be called once from the command line. Exits 0 for success,
  exits 1 on failure with a human-readable output message.

  Both razor-report(1) and razor-revoke(1) require user authentication to work, razor-check(1) does not. This allows the Razor
  Nomination Server to keep track of how many messages a user reports and revokes. The more messages a user correctly
  reports and/or correctly revokes, the more trust the user earns. Likewise, when messages are incorrectly reported or revoked,
  the trust goes down for that user. Highly trusted users will have the most affect on the Razor database.
```

So I guess the main purpose is to associate some trust or credits to the identity reporting or revoking messages. As with all identities they should not be reused for a lot of users.

No offence, but that is why I asked this question and I guess it is up to you (the maintainers) to reach a decision on that.

**Comment by aendeavor** [comment]
I have not implemented this feature - it was added a long time ago. But since there are no reports about issues, I wouldn't consider it a problem.

/cc @docker-mailserver/maintainers

**Comment by radicand** [comment]
I think this is worth taking a look at the impact and potentially moving to the runtime (saving the identity in local state, etc).

**Comment by aendeavor** [comment]
Alright. While were at it, we could investigate into the `freshclam` command at build time too. This is heavily increasing our image size: I had a look with https://github.com/wagoodman/dive

![2021-02-18-102042_1414x982_scrot](https://user-images.githubusercontent.com/44545919/108335179-f7d60000-71d2-11eb-817a-e3e3c8250670.png)

adding 236MB (uncompressed). If we could outsource this update to the runtime, this would greatly reduce the image's size!

@casperklein @radicand @fbartels Do you think we could let supervisor do this update for us?

**Comment by casperklein** [comment]
I don't use clamav myself. For the same reasons (to save disk space and build time), I've disabled freshclam in my personal build.

`freshclam` takes same time to complete. So moving the initial freshclam call to runtime would significant increase the container startup IMHO.

**Comment by aendeavor** [comment]
Yes, this is true. It would be a tradeoff, between image size and startup time. We don't have to do this, I just wanted to mention it.

**Comment by erik-wramner** [comment]
Apart from adding to the startup time the freshclam call can fail, in which case we would not be able to start or would have to run without any protection. Still, if we were to use a volume for the signatures the initial freshclam and razor calls could be part of the installation procedure. In that case we would still start quickly the second time around.
