### ISSUE TITLE
Image digest mismatch for docker-mailserver:latest?

### ISSUE THREAD

**Issue by FSeidinger** [docker-mailserver/docker-mailserver#1816]
# Image digest mismatch for docker-mailserver:latest

Other

## Description

Maybe I'm paranoid here, but when I pull the latest docker-mailserver image, I get the following output:

```
docker pull mailserver/docker-mailserver:latest
latest: Pulling from mailserver/docker-mailserver
Digest: sha256:cb8ccca90dfe8bcc3ba8114584e655dfad06498b5721ff977bd42927bb34a734
Status: Image is up to date for mailserver/docker-mailserver:latest
docker.io/mailserver/docker-mailserver:latest
```

The latest image points to the 8.0.1 version:

```
docker pull mailserver/docker-mailserver:8.0.1
8.0.1: Pulling from mailserver/docker-mailserver
Digest: sha256:cb8ccca90dfe8bcc3ba8114584e655dfad06498b5721ff977bd42927bb34a734
Status: Downloaded newer image for mailserver/docker-mailserver:8.0.1
docker.io/mailserver/docker-mailserver:8.0.1
```

So the digest of this image is obviously `cb8ccca90dfe8bcc3ba8114584e655dfad06498b5721ff977bd42927bb34a734`. When I try to find that image on hub.docker.com, the latest version of docker-mailserver for amd64 has the digest of `37456d1db3b9a91a4f4ad921ca86d7e3e00ab87153fe943c5898f867ebb61322`. The downloaded digest I cannot find/identify on hub.docker.com.

What did I miss or didn't understand here?

**Comment by aendeavor** [comment]
This is indeed interesting - I can confirm the digests / hash sums though. I wouldn't worry about it.

You might find this interesting: https://github.com/docker/hub-feedback/issues/1925

**Comment by aendeavor** [comment]
I hope this can be closed:) I will do so.
