### ISSUE TITLE
Modified to and from emails if domain not matching 'domainname' variable

### ISSUE THREAD

**Issue by BaileyJM02** [docker-mailserver/docker-mailserver#1818]
Hello, I'm a little confused as how to go about fixing this. I currently have the value `domainname: one.tld` set within my docker compose file. Whenever I send an email from bailey@one.tld, the email is delivered with a from address of bailey@one.tld, which is the expected behaviour. However, if I send an email from [two.tld](), the delivered from address is something like [SRS0=BF5z=HU=two.tld=bailey@one.tld]().

This also *(weirdly?)* occurs to external email addresses when viewing received mail over IMAP, my personal email bailey@hey.com becomes [SRS0=BMdX=HU=hey.com=bailey@one.tld](). If I send an email from bailey@hey.com to bailey@one.tld.

My config/postfix-accounts.cf file looks like below:
```
admin@one.tld|{SHA512-CRYPT}hash.
bailey@one.tld|{SHA512-CRYPT}hash
bailey@two.tld|{SHA512-CRYPT}hash
someone@two.tld{SHA512-CRYPT}hash
```
And I have configured config/postfix-main.cf with the value of `mydestination = localhost.$mydomain, localhost` as I'm not using a hostname, though I'm not sure if this has any relevance.

**Comment by BaileyJM02** [comment]
Ah okay, just as I had posted this I thought about the SRS section and the **SRS_SENDER_CLASSES** variable. Changing this back from `SRS_SENDER_CLASSES=envelope_sender,header_sender` to `SRS_SENDER_CLASSES=envelope_sender` fixed the weird email generation but it says more strict SPF policies may require it. Is it possible to enable something like this without causing such strange addresses?

**Comment by wernerfred** [comment]
Yep you are right. The mail addresses look like SRS activated. You can read more about it here: https://www.axigen.com/articles/email-server-sender-rewriting-scheme-srs_72.html 
I think the behavior you described is exactly how SRS should work.
Where do you see these addresses? In the logs or in your mail client?

**Comment by BaileyJM02** [comment]
Thanks for pointing out the articles, they were really useful and I now understand why it was shown, from what I read that was indeed the expected behaviour, I just didn't fully understand it. The addresses were definitely shown within my mail client, I can't remember about the logs however I presume they were the same there also.

**Comment by wernerfred** [comment]
Always glad to help 👍🏻
