### ISSUE TITLE
open-dkim: No such file or directory

### ISSUE THREAD

**Issue by ThriftyNick** [docker-mailserver/docker-mailserver#1819]
open-dkim: No such file or directory

Other

## Description
I successfully added an email with the setup script and the container is up an running.  I get the following error on the next step from the readme:

``` BASH
$ ./setup.sh config dkim

[dumb-init] open-dkim: No such file or directory

––– UNCHECKED ERROR
  – script    = setup.sh
  – function  = _docker_image / ${CRI}
  – line      = run
  – exit code = --rm

```

**Comment by wernerfred** [comment]
Read this carefully:
https://github.com/docker-mailserver/docker-mailserver#get-the-tools
> Make sure to get the setup.sh that comes with the release you're using. Look up the release and the git commit on which this release is based upon by selecting the appropriate tag on GitHub.

Sadly you did not provide any information about your setup but I think you did not use latest `:edge` with latest `setup.sh`.

If you use `:latest` you need to use `setup.sh` with git tag `8.0.1`.

**Comment by wernerfred** [comment]
Additionally please make sure to use the right Issue template. Imho you described a bug from your perspective as it is code related and not one of the following:
>I would like to contribute to the project
>I would like to configure a not documented mail server use case
>I would like some feedback concerning a use case
>I have questions about TLS/SSL/STARTTLS/OpenSSL
>Other

And the bug template would have asked a lot more information which helps us to help you. We are really happy to help but it is exhausting to ask the same questions every time again as issue templates are ignored frequently.

**Comment by aendeavor** [comment]
@wernerfred I have pushed ed1bd0cc2488c319c2beda07cd7b69441fc535c5 in which I point to this "problem" in an even more verbose manner. There are now two points in the README that state this, the error trap in `setup.sh` will show it and `./setup.sh help` has a `VERSION` paragraph which points this out too.

---

@ThriftyNick Please check the README to get the appropriate version of `setup.sh` for you.
