### ISSUE TITLE
[BUG] Invalid value of SUPERVISOR_LOGLEVEL leads to restart loop

### ISSUE THREAD

**Issue by SebastianMuskalla** [docker-mailserver/docker-mailserver#1838]
The following problem is certainly minor, but maybe somebody wants to fix it.

If `SUPERVISOR_LOGLEVEL` is set to an invalid value (e.g. `"debug"` instead of just `debug`), STDOUT claims
`[  ERROR  ]  SUPERVISOR_LOGLEVEL value '"debug"' unknown. Defaulting to 'warn'`, but actually, the server gets stuck in a restart loop.

STDOUT is essentially an endless iteration of the following snippet

```
[ TASKLOG ]  Initializing setup
[ TASKLOG ]  Checking configuration
[ TASKLOG ]  Configuring mail server
[  ERROR  ]  SUPERVISOR_LOGLEVEL value '"debug"' unknown. Defaulting to 'warn'
[ TASKLOG ]  Initializing setup
[ TASKLOG ]  Checking configuration
[ TASKLOG ]  Configuring mail server
[  ERROR  ]  SUPERVISOR_LOGLEVEL value '"debug"' unknown. Defaulting to 'warn'
[ TASKLOG ]  Initializing setup
[ TASKLOG ]  Checking configuration
[ TASKLOG ]  Configuring mail server
[  ERROR  ]  SUPERVISOR_LOGLEVEL value '"debug"' unknown. Defaulting to 'warn'
Restarted supervisord
```

**Comment by aendeavor** [comment]
I will have a look.

**Comment by aendeavor** [comment]
I have pushed 0d9fb096b78363e57192853e4aa58060945218fd which should solve this issue.
