### ISSUE TITLE
How to send mail from the host?

### ISSUE THREAD

**Issue by kklepper** [docker-mailserver/docker-mailserver#1840]
# Subject

I would like some feedback concerning a use case

## Description

`docker-mailserver` runs on one of my machines (IONOS_2) for about 3/4 of a year now without flaws and serves a domain on another machine (IONOS_1) as well. On both I use `acme.sh` to manage `let's encrypt` certificates.

This script may send emails, e.g. daily notices `Renew Skipped` for certs not due, which is a nice feature. In order to use this, I installed `sendmail` on the second machine and it works fine after figuring out the basics (well, the -F parameter does not work).

```
root@IONOS_1: /var/mail # sendmail -F "kklepper" -f "myaddress@googlemail.com" -v me@docker_ms.tld  < /tmp/mail.txt
me@docker_ms.tld... Connecting to [127.0.0.1] via relay...
220 localhost.localdomain ESMTP Sendmail 8.15.2/8.15.2; Sun, 28 Feb 2021 03:20:25 +0100
>>> EHLO localhost.localdomain
250-localhost.localdomain Hello localhost [127.0.0.1], pleased to meet you
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-8BITMIME
250-SIZE
250-DSN
250-ETRN
250-STARTTLS
250-DELIVERBY
250 HELP
>>> STARTTLS
220 2.0.0 Ready to start TLS
>>> EHLO localhost.localdomain
250-localhost.localdomain Hello localhost [127.0.0.1], pleased to meet you
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-8BITMIME
250-SIZE
250-DSN
250-ETRN
250-DELIVERBY
250 HELP
>>> MAIL From:<myaddress@googlemail.com> SIZE=169
250 2.1.0 <myaddress@googlemail.com>... Sender ok
>>> RCPT To:<me@docker_ms.tld>
>>> DATA
250 2.1.5 <me@docker_ms.tld>... Recipient ok
354 Enter mail, end with "." on a line by itself
>>> .
250 2.0.0 11S2KPDr043115 Message accepted for delivery
wp@wpopken.de... Sent (11S2KPDr043115 Message accepted for delivery)
Closing connection to [127.0.0.1]
>>> QUIT
221 2.0.0 localhost.localdomain closing connection
```

It does not work on the first, however.

``` 
root@IONOS_2: /tmp # sendmail -F "kklepper" -f "myaddress@googlemail.com" -v me@docker_ms.tld  < /tmp/mail.txt
sendmail: warning: /etc/postfix/main.cf, line 137: overriding earlier entry: inet_interfaces=all
sendmail: warning: /etc/postfix/main.cf, line 749: overriding earlier entry: smtpd_tls_key_file=/etc/pki/tls/private/postfix.key
sendmail: warning: /etc/postfix/main.cf, line 750: overriding earlier entry: smtpd_tls_cert_file=/etc/pki/tls/certs/postfix.pem
postdrop: warning: /etc/postfix/main.cf, line 137: overriding earlier entry: inet_interfaces=all
postdrop: warning: /etc/postfix/main.cf, line 749: overriding earlier entry: smtpd_tls_key_file=/etc/pki/tls/private/postfix.key
postdrop: warning: /etc/postfix/main.cf, line 750: overriding earlier entry: smtpd_tls_cert_file=/etc/pki/tls/certs/postfix.pem
Mail Delivery Status Report will be mailed to <myaddress@googlemail.com>.
```
`Ctrl+c` returns to the prompt. No email is delivered.

I installed the `mail` package as well, not really understanding the difference, with exactly the same result.

## Question

What to do to send mail from the shell here with sendmail as well? 

My hypothesis is that the `docker-mailserver` parameters interfere, but I have no idea of how to fix it. 

Or is it possible to use sendmail via `docker-mailserver` MTA directly from the shell?

**Comment by aendeavor** [comment]
Not sure if that helps, but I use `swaks`:

``` BASH
swaks -4 \
	--header 'Subject: My Subject' \
	--server 'mail.domain.tld' \
	-h       'mail.domain.tld' \
	-li      'mail.domain.tld' \
	--from   'myuser@domain.tld' \
	--to     'myuser@domain.tld' \
	-au      'myuser@domain.tld' \
	--auth   LOGIN \
	-ap      '<PASSWORD>' \
	-tls \
	--body   "<BODY>"
```

**Comment by kklepper** [comment]
@aendeavor Thanks a lot for the hint. That's quite a tool, but more than I need. 

Also I'm afraid the `swaks` syntax is not supported by `acme.sh`.

I'll check it if there is no easier and straight-forward solution.

**Comment by casperklein** [comment]
Take a look at [nullmailer](https://wiki.debian.org/nullmailer).

**Comment by kklepper** [comment]
@casperklein Thank you, but on first look I'm afraid that this is pretty much the same problem with `acme.sh`. I better specify my topic.

**Comment by casperklein** [comment]
Sendmail **MTA** will probably trying to listen to tcp/25, but that port is already in use by docker-mailserver.

If you don't need a full blown MTA on your host machine, I suggest `nullmailer`. It provides a `sendmail` **binary** which can be used by `acme.sh`.

**Comment by kklepper** [comment]
@casperklein I tried it.

```
root@IONOS_2: /root # dnf install nullmailer
CentOS-8 - AppStream                                                                                                                                                                12 kB/s | 4.3 kB     00:00
CentOS-8 - Base                                                                                                                                                                     12 kB/s | 3.9 kB     00:00
CentOS-8 - Extras                                                                                                                                                                  4.4 kB/s | 1.5 kB     00:00
Docker CE Stable - x86_64                                                                                                                                                           63 kB/s | 3.5 kB     00:00
Extra Packages for Enterprise Linux Modular 8 - x86_64                                                                                                                              65 kB/s |  34 kB     00:00
Extra Packages for Enterprise Linux 8 - x86_64                                                                                                                                      82 kB/s |  34 kB     00:00
Remi's Modular repository for Enterprise Linux 8 - x86_64                                                                                                                           21 kB/s | 3.5 kB     00:00
Safe Remi's RPM repository for Enterprise Linux 8 - x86_64                                                                                                                          55 kB/s | 3.0 kB     00:00
No match for argument: nullmailer
Error: Unable to find a match: nullmailer
```
#### nullmailer not found
https://forums.centos.org/viewtopic.php?t=43797
#### How to Install an RPM package on RHEL 8 / CentOS 8 Linux
https://linuxconfig.org/how-to-install-rpm-bin-package-in-redhat-linux-8

```
root@IONOS_2: /root # dnf install /www/nullmailer-1.13-1.x86_64.rpm
CentOS-8 - AppStream                                                                                                                                                                15 kB/s | 4.3 kB     00:00
CentOS-8 - Base                                                                                                                                                                     15 kB/s | 3.9 kB     00:00
CentOS-8 - Extras                                                                                                                                                                  5.6 kB/s | 1.5 kB     00:00
Docker CE Stable - x86_64                                                                                                                                                           80 kB/s | 3.5 kB     00:00
Extra Packages for Enterprise Linux Modular 8 - x86_64                                                                                                                             148 kB/s |  34 kB     00:00
Extra Packages for Enterprise Linux 8 - x86_64                                                                                                                                     897 kB/s |  34 kB     00:00
Remi's Modular repository for Enterprise Linux 8 - x86_64                                                                                                                           23 kB/s | 3.5 kB     00:00
Safe Remi's RPM repository for Enterprise Linux 8 - x86_64                                                                                                                          69 kB/s | 3.0 kB     00:00
Error:
 Problem: conflicting requests
  - nothing provides supervise-scripts >= 3.2 needed by nullmailer-1.13-1.x86_64
  - nothing provides libgnutls.so.26()(64bit) needed by nullmailer-1.13-1.x86_64
  - nothing provides libgnutls.so.26(GNUTLS_1_4)(64bit) needed by nullmailer-1.13-1.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```
Also, the binary is not the problem:

```
root@IONOS_2: /root # which sendmail
/usr/sbin/sendmail

```
The problem seems to be conflicting instructions in ` /etc/postfix/main.cf` which I am unable to understand and therefore cannot resolve.

**Comment by casperklein** [comment]
> The problem seems to be conflicting instructions in /etc/postfix/main.cf

That's why I suggested switching to a lightweight sendmail/postfix alternative. (ps: you said before, you installed sendmail, not postfix). 

sendmail is a MTA and also a binary provided by almost all popular MTA, including sendmail MTA itself.

But if nullmailer is not available for your distribution, thats no alternative. Then you have to rule out, what's the problem with postfix.

As written above, at least binding port tcp/25 will fail for postfix on the host maschine, where you run docker-mailserver.

**Comment by kklepper** [comment]
@casperklein That is an interesting comment raising new questions.

Why does the invocation of the `sendmail` executable raise warnings with respect to `postfix`? Which mechanism is responsible for that? How do `sendmail` and `postfix` relate? 

With respect to `nullmailer`: Somebody in that forum created a `rpm`, but that was in 2013. If I interpret the installation errors correctly, some utilities are missing. If so, that probably could be fixed.

**Comment by casperklein** [comment]
The sendmail binary is provided by postfix. If you use this sendmail binary (client) to send an email, it will use postfix MTA (server) for mail delivery. The sendmail binary by itself cannot deliver mails to other hosts (afaik).

**Comment by kklepper** [comment]
@casperklein Thank you!

> PS: Does the second machine use docker-mailserver for sending emails?

No, the domains on that machine use the docker-mailserver from the other machine. Not enough space there to set up a  docker-mailserver on its own.

**Comment by erik-wramner** [comment]
I'm using this script as sendmail:
```
#!/bin/bash
docker exec -i mail /usr/sbin/sendmail "$@"
```
It uses the sendmail binary in the docker container. It works, but I remember that I had some problems at first. You could try!

**Comment by kklepper** [comment]
@erik-wramner Great, thanks a lot! This is what I was looking for but was too lazy to find out myself. Simple and easy.

With a little twist I could send an email from IONOS_2 the same way I can from IONOS_1. i.e.

`sendmail -F "kklepper" -f "myaddress@googlemail.com" -v me@docker_ms.tld  < /tmp/mail.txt` 

works the same on both machines.

#### create shell command file

```
#!/bin/sh
mail=$(docker ps -a  | grep "mta" | grep -v "xited" | awk '{print $1}')
docker exec -i $mail /usr/sbin/sendmail "$@"
```
Make it findable, e.g. put it in `/root/bin`, name it for example `sendm.sh`, then make it executable by `chmod +x sendm.sh`.

#### trick away sendmail executable by soft link

```
mv /usr/sbin/sendmail /usr/sbin/sendmail_org
ln -s /c/bak/sendm.sh /usr/sbin/sendmail 
```

I'll wait until tomorrow to see my reminder mail from `acme.sh` and will tell you if it worked as expected.

**Comment by kklepper** [comment]
Ok, the reminder from `acme.sh` worked for one of the certs on IONOS_2. So sendmail is ok. I guess I did not configure the second cert for `acme.sh` yet, so that will be easy to check and fix.

Thank you all very much for your efforts!

**Comment by kklepper** [comment]
### Addendum

For the record: I need to manage 3 certifications on 2 machines. Initially I used `certbot` via `docker` on both and had quite some trouble managing it. I remember having been upset more than once with not renewed certs. To fix this, I had to walk quite a mile, every time being frustrated about all those complicated details and procedures, no chance to remember for next time.

Finally during Google research I learned that I wasn't alone and somebody recommended `acme.sh`. 

As it turned out now, I was suspicious, so I only used it for one of the two certificates on IONOS_2 at first. 

When the certificate on IONOS_1 was near expiry, instead of researching for the correct procedure once more, I switched to `acme.sh` -- again no problem whatsoever. This time I learned about the notification function.

Having been able to activate the `acme.sh` notification on IONOS_2 with your help, I realized I had not transferred the other certificate to `acme.sh`. 

Well, generating certs with `acme.sh` is a breeze and -- it's hard to believe -- amounts to a one-liner:

```
root@IONOS_2: /root # acme.sh --issue -d mydomain.com -d www.mydomain.com -w /var/www/mydomain.com
[Wed Mar  3 02:29:56 CET 2021] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Wed Mar  3 02:29:56 CET 2021] Creating domain key
[Wed Mar  3 02:29:57 CET 2021] The domain key is here: /root/.acme.sh/mydomain.com/mydomain.com.key
[Wed Mar  3 02:29:57 CET 2021] Multi domain='DNS:mydomain.com,DNS:www.mydomain.com'
[Wed Mar  3 02:29:57 CET 2021] Getting domain auth token for each domain
[Wed Mar  3 02:29:59 CET 2021] Getting webroot for domain='mydomain.com'
[Wed Mar  3 02:29:59 CET 2021] Getting webroot for domain='www.mydomain.com'
[Wed Mar  3 02:29:59 CET 2021] Verifying: mydomain.com
[Wed Mar  3 02:30:03 CET 2021] Success
[Wed Mar  3 02:30:03 CET 2021] Verifying: www.mydomain.com
[Wed Mar  3 02:30:06 CET 2021] Success
[Wed Mar  3 02:30:07 CET 2021] Verify finished, start to sign.
[Wed Mar  3 02:30:07 CET 2021] Lets finalize the order.
[Wed Mar  3 02:30:07 CET 2021] Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/109979297/8222030745'
[Wed Mar  3 02:30:08 CET 2021] Downloading cert.
[Wed Mar  3 02:30:08 CET 2021] Le_LinkCert='https://acme-v02.api.letsencrypt.org/acme/cert/03d5d6ec2c3645e9fd1b1c1e45c4017bfcaa'
[Wed Mar  3 02:30:08 CET 2021] Cert success.
-----BEGIN CERTIFICATE-----
MIIFODCCBCCgAwIBAgISA9XW7Cw2Ren9GxweRcQBe/yqMA0GCSqGSIb3DQEBCwUA
...
D9cOSqcsWvrkaQOF4hw5q09CFLJ9d6BeyjX3gfAdv6q6ioUsu4Jxl3ob4W8=
-----END CERTIFICATE-----
[Wed Mar  3 02:30:08 CET 2021] Your cert is in  /root/.acme.sh/mydomain.com/mydomain.com.cer
[Wed Mar  3 02:30:08 CET 2021] Your cert key is in  /root/.acme.sh/mydomain.com/mydomain.com.key
[Wed Mar  3 02:30:08 CET 2021] The intermediate CA cert is in  /root/.acme.sh/mydomain.com/ca.cer
[Wed Mar  3 02:30:08 CET 2021] And the full chain certs is there:  /root/.acme.sh/mydomain.com/fullchain.cer
```

This is what `letsencrypt` should have been to begin with.

So the only thing left to do was to configure my `nginx` proxy.

And again I was stuck. The old configuration had `pem` files, whereas `acme.sh` does not generate `pem` files, but `cer` and `key` files, the latter not being named `privkey`. Well, that surely is confusing.

I remember having googled for what is what and found that others had been confused as well. I did not want to repeat that process. Instead I manually created a directory `/etc/letsencrypt/live/acme.mydomain.com` and copied the `fullchain.cer` and `mydomain.com.key` files there.

Next I editied my `nginx.conf` and replaced the old instructions:

```        
#ssl_certificate /etc/letsencrypt/live/mydomain.com/fullchain.pem;
#ssl_certificate_key /etc/letsencrypt/live/mydomain.com/privkey.pem;
		ssl_certificate /etc/letsencrypt/live/acme.mydomain.com/fullchain.cer;
		ssl_certificate_key /etc/letsencrypt/live/acme.mydomain.com/mydomain.com.key;
```

Also, `certbot` being absolete now, I removed that section from my proxy  `docker-compose.yml`.

The only thing left to do was restart my proxy:

```
root@IONOS_2: /root/proxy # docker-compose down --remove-orphans;docker-compose up -d; sleep 3; docker ps -a | grep "proxy_n"
Stopping proxy_nginx_1 ... done
Removing proxy_nginx_1 ... done
Network proxy is external, skipping
Removing network proxy_nc
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Creating network "proxy_nc" with the default driver
Creating proxy_nginx_1 ... done
904983a423bc        nginx:1.18.0-alpine                                             "/bin/sh -c 'while :…"   4 seconds ago       Up 3 seconds          0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp                                                                                           proxy_nginx_1
```

The warning refers to my main docker zoo which runs in swarm mode.

In order to not forget reconfiguring `nginx` after renewal, I changed my crontab and added 

```
1 2 * * * cp /root/.acme.sh/mydomain.com/fullchain.cer /etc/letsencrypt/live/acme.mydomain.com
1 2 * * * cp /root/.acme.sh/mydomain.com/mydomain.com.key /etc/letsencrypt/live/acme.mydomain.com
1 2 * * * cp /root/.acme.sh/myotherdomain/fullchain.cer /etc/letsencrypt/live/acme.myotherdomain
1 2 * * * cp /root/.acme.sh/myotherdomain/myotherdomain.key /etc/letsencrypt/live/acme.myotherdomain
```

So every night at 1 minute past 2 those files are copied, renewed or not.

Remains to mention that the `docker-compose.yml` for my proxy contains the line

```
command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
```
to restart `nginx` every 6 hours to pick up new configurations. Well, that 6 hour interval does not make much sense, but I copied this from somewhere else and did not bother to think about it.

**Comment by kklepper** [comment]
### Addendum 2:

It is nice to know that `acme.sh` shows the current state nicely:

```
root@IONOS_2: /root # acme.sh --list
Main_Domain      KeyLength  SAN_Domains                                          CA               Created                       Renew
mydomain.com     ""         www.mydomain.com                                     LetsEncrypt.org  Wed Mar  3 01:30:08 UTC 2021  Sun May  2 01:30:08 UTC 2021
myotherdomain    ""         www.myotherdomain,my.myotherdomain,sm.myotherdomain  LetsEncrypt.org  Tue Jan 19 01:16:00 UTC 2021  Sat Mar 20 01:16:00 UTC 2021
```
