### ISSUE TITLE
Fetchmail in combination with haproxy

### ISSUE THREAD

**Issue by DerOetzi** [docker-mailserver/docker-mailserver#1841]
# Subject

I would like some feedback concerning a use case

## Description

I having a docker-mailserver running behind a haproxy as load-balancer. For this I added the following configurations to postfix-main.cf and postfix-master.cf  

postfix-main.cf
```
postscreen_upstream_proxy_protocol = haproxy
```

postfix-master.cf
```
smtps/inet/smtpd_upstream_proxy_protocol=haproxy
submission/inet/smtpd_upstream_proxy_protocol=haproxy
```

Unfortunately this seems to break fetchmail daemon:

```
mailserver      | Mar  2 13:20:02 b38fd20b0009 fetchmail[1109]: reading message test@example.de:1 of 3 (28757 octets)Trying to connect to 127.0.0.1/25...connected.
mailserver      | Mar  2 13:20:07 b38fd20b0009 postfix/postscreen[11248]: warning: haproxy read: time limit exceeded
mailserver      | Mar  2 13:20:07 b38fd20b0009 fetchmail[1109]: SMTP< 421 4.3.2 No system resources
mailserver      | Mar  2 13:20:07 b38fd20b0009 fetchmail[1109]: Trying to connect to 127.0.0.1/25...connected.
mailserver      | Mar  2 13:20:12 b38fd20b0009 postfix/postscreen[11248]: warning: haproxy read: time limit exceeded
mailserver      | Mar  2 13:20:12 b38fd20b0009 fetchmail[1109]: SMTP< 421 4.3.2 No system resources
mailserver      | Mar  2 13:20:12 b38fd20b0009 fetchmail[1109]: SMTP connect to localhost failed
```

Maybe someone knows a solution howto fix this.

Thanks

**Comment by wernerfred** [comment]
Did you read one of the articles in the wiki dealing with proxy protocol [eg this article](https://github.com/docker-mailserver/docker-mailserver/wiki/Installation-examples#using-docker-mailserver-behind-proxy)? Maybe they have a hint that helps you.

Did you enable the use of proxy-protocol in ha proxy? I'm not using haproxy myself but I think it is `send-proxy` in the backend configuration.

Does haproxy produce any relevant log during connections?

**Comment by DerOetzi** [comment]
Yes I have configured my things after this article. The problem is as you can see in the logs above fetchmail doesn't leave the container but tries to connect directly to localhost postfix via 127.0.0.1/25. For this there are no relevant haproxy logs because these requests are never seen by haproxy. But Postfix doesn't accept such calls without haproxy between.

Possible solutions I already thought about and tried them, but didn't work because I don't know how to configure them, would be:

1. A seperate fetchmail from outside docker-mailserver container. => All messages were rejected because of SPF Check fails with not allowed sender IP
2. Configure docker-mailserver fetchmail daemon not do use localhost, but to go outside via haproxy => Don't know whether this is possible and maybe this will fail for same reason as option 1?
3. Somehow configure postfix not to expect haproxy protocol when called via localhost => Don't know whether this is possible

Maybe this helps to find a solution

**Comment by wernerfred** [comment]
I'm currently Short in time but will Look at this once i have more spare time (y)

**Comment by DanielFuchs98** [comment]
I have the same setup, configs are [here](https://github.com/docker-mailserver/docker-mailserver/issues/1523#issuecomment-633607852). Working without any problems.

**Comment by wernerfred** [comment]
Have you tried @DanielFuchs98 ' answer? Or did you manage to solve the problem in another way? How can we assist further?
