### ISSUE TITLE
Installation issues: "No such service: mail"

### ISSUE THREAD

**Issue by ParzivalWolfram** [docker-mailserver/docker-mailserver#1842]
# Subject

Other

## Description
Running ```docker-compose up -d mail``` as specified in the install instructions produces the following output:

```
Creating network "mailserver_default" with the default driver
Creating volume "mailserver_maildata" with default driver
Creating volume "mailserver_mailstate" with default driver
Creating volume "mailserver_maillogs" with default driver
ERROR: No such service: mail
```

Docker version 19.03.8, docker-compose version 1.25.0

**Comment by ParzivalWolfram** [comment]
It seems your instructions are a problem, as actually looking at the docker-compose.yml file shows it needs to be ```docker-compose up -d mailserver``` and now I hit a wall because somewhere, you're still trying to pass a placeholder value, as shown here:
```
Status: Downloaded newer image for mailserver/docker-mailserver:latest
Creating <INSERT 'CONTAINER NAME' HERE> ... error

ERROR: for <INSERT 'CONTAINER NAME' HERE>  Cannot create container for service mailserver: Invalid container name (<INSERT 'CONTAINER NAME' HERE>), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed

ERROR: for mailserver  Cannot create container for service mailserver: Invalid container name (<INSERT 'CONTAINER NAME' HERE>), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed
ERROR: Encountered errors while bringing up the project.
```

**Comment by wernerfred** [comment]
Did you download/use the `compose.env` file and renamed it to `.env`? There you can set the container name.
Otherwise set it in the `docker-compose.yml` itself

**Comment by casperklein** [comment]
Docu fixed: df54750d02a9a30c472226d1b1030f21d490b704

**Comment by aendeavor** [comment]
> Running ```docker-compose up -d mail``` as specified in the install instructions


Where did you find that?

**Comment by aendeavor** [comment]
Closed with fix by @casperklein
