### ISSUE TITLE
Letsencript settings

### ISSUE THREAD

**Issue by rquevedo** [docker-mailserver/docker-mailserver#1843]
# Subject

I have questions about TLS/SSL/STARTTLS/OpenSSL

## Description

Hi, im setting all params(AFAIK) to enable ssl certificates from letsencript but when config thunderbird only shows self signed certs. This are params in mailserver.env:

TLS_LEVEL=
SSL_TYPE=letsencript

What else i must do to force certs creation?

**Comment by aendeavor** [comment]
Wrong:

> SSL_TYPE=letsencript

Right:

`SSL_TYPE=letsencrypt`

Please be more careful. This issue tracker is not for correcting spelling mistakes...

**Comment by rquevedo** [comment]
Thank you very mucth @aendeavor
