### ISSUE TITLE
Logwatch sends reports to "1@domain" 

### ISSUE THREAD

**Issue by kreuzer82** [docker-mailserver/docker-mailserver#1846]
Hello,

Logwatch sends reports to "1@domain" . I had it running fine until i moved the docker-repo from tomav to the one here i guess.. can't find a variable/option to change that email-address to which logwatch sends to..

Thanks and greez

**Comment by casperklein** [comment]
Please use the issue template. To help you, we need further information, in that case for example your configured ENVs. It's hard for us, to ask the same questions over and over again. That's why we created the templates. Feel free to open a new issue.
