### ISSUE TITLE
CapRover

### ISSUE THREAD

**Issue by kaaax0815** [docker-mailserver/docker-mailserver#1847]
# CapRover Support

I would like to configure a not documented mail server use case

## Description

I use [CapRover](https://caprover.com/) and it uses Docker Swarm. So I can just leave the Swarm and create the MailServer. And CapRover only supports images or Dockerfiles.
But it should work somehow because you can easily access all the other containers using url because it creates its own network. Is there something like a list of images and how to set them up to make it work in CapRover?

The Setup.sh would also not work because caprover prefixes all container with `captain--`

**Comment by casperklein** [comment]
> Is there something like a list of images

Take a look here:
https://github.com/docker-mailserver/docker-mailserver/blob/4ba2315058ccea4f8efca91f66ce2e04583f6536/docker-compose.yml#L5

> The Setup.sh would also not work because caprover prefixes all container with captain--

That shouldn't be a problem, as `setup.sh` auto-detects the container name by the image lables:

https://github.com/docker-mailserver/docker-mailserver/blob/4ba2315058ccea4f8efca91f66ce2e04583f6536/setup.sh#L266-L270

**Comment by kaaax0815** [comment]
I get the Error `[ ERROR ] Setting hostname/domainname is required` can I set this with enviroment variables or is there another way?

**Comment by wernerfred** [comment]
@kaaax0815 is your Issue solved? The answer of @casperklein contains all information you requested. Any further assistance needed?

**Comment by kaaax0815** [comment]
Sorry, I forget to close the issue
