### ISSUE TITLE
Allow a startup script in config/ which will be executed on caintainer startup

### ISSUE THREAD

**Issue by fred727-temp** [docker-mailserver/docker-mailserver#1850]
# Feature Request

Sometimes, we can not configure the container only with the env variables which are proposed.
If we want to override default postfix configuration, [there is solutions](https://github.com/docker-mailserver/docker-mailserver/wiki/Override-Default-Postfix-Configuration) with `config/postfix-main.cf` and `config/postfix-master.cf` files but this do not carry every needs.

For example, I had to add a postmap transport table to slowdown email delivery to certain domain. (If not, we can have emails rejected with errors like "_Too many connections, slow down._")
The only solution I found is to make a patch-config.sh script and injecting it in the container after startup :
```BASH
docker-compose up -d mailserver
docker exec -i mail bash < patch-config.sh
```

It would be great if we can add a script somewhere in `config/`, which will be executed on container startup.

**Comment by casperklein** [comment]
You mean something like this: https://github.com/docker-mailserver/docker-mailserver/blob/master/config/user-patches.sh.dist

**Comment by aendeavor** [comment]
Is this even serious...?

**Comment by fred727-temp** [comment]
Thank you @casperklein, haven't seen it [on the wiki page](https://github.com/docker-mailserver/docker-mailserver/wiki/List-of-optional-config-files-&-directories) !

(I was trying to find a workarround with the `entrypoint` of docker-compose)

**Comment by casperklein** [comment]
You can find more information here: https://github.com/docker-mailserver/docker-mailserver/wiki/FAQ-and-Tips#howto-adjust-settings-with-the-user-patchessh-script

Feel free to enhance the wiki. Everybody can make changes to it 😉

**Comment by fred727-temp** [comment]
done ;)
