### ISSUE TITLE
HP MFP Printer and RFC5322 Missing required header field: "Date"

### ISSUE THREAD

**Issue by rayures** [docker-mailserver/docker-mailserver#1853]
# Subject

I have a HP MFP Printer that can send emails (i.e. for scanned docs). 

The mails that the HP is sending is missing a 'date' header. The mailserver is bouncing this messages. And reports: 
```
INVALID HEADER

Missing required header field: "Date"
```
I this this is as it should be, because it is not per RFC5322 (date header is mandatory). 

BUT:  i do want to get this functionality working on my printer. And a lot of users on the internet seem to have this issue. 

So i went looking the Internets and found this: 
https://www.prosinger.net/amavis-new-bad-header-checks-tweaking/
it says you can add a line in the config file to bypass header checks. 

so i added this line to /etc/amavis/conf.d/50-user, restarted the container and send a testmail from the printer. Emails are delivered. :-)
````
$allowed_header_tests{'missing'} = 0;
````

So, my question is, how can i add this config to the mailserver in a way that is persistent to docker image updates .

**Comment by aendeavor** [comment]
<https://github.com/docker-mailserver/docker-mailserver#custom-user-changes--patches>

It's all there, just read the whole README...

**Comment by johncadengo** [comment]
@rayures did you ever get this working? What's the solution?

**Comment by rayures** [comment]
> @rayures did you ever get this working? What's the solution?

hi, it is like @georglauterbach pointed out. just use the user patches script to add the allowed _header_tests. works great.
