### ISSUE TITLE
Upgrade from 7.x to 9.0.1

### ISSUE THREAD

**Issue by ghnp5** [docker-mailserver/docker-mailserver#1855]
Hello,

I see you've had two major releases in the past few months.

Upgrading a Mail server is not easy to "test", can easily break things, and requires a lot of caution :)

Before I proceed with this upgrade, I'd like to know if there's anything in specific you recommend me being most careful with.

1) Are there any known issues with 9.0.1 at the moment? (that I should wait for the next version)

2) Are these programs still in place? (which I run commands against, using "docker exec"):
`dovecot`
`postfix`
`/usr/sbin/sendmail`

3) Are these paths still the same? (which I map in my docker-compose):
`/var/mail`
`/var/mail-state`
`/var/log/mail`
`/etc/letsencrypt`
`/tmp/docker-mailserver/`

4) Is there a list of new/removed variables for "env-mailserver"? (which seems to have been renamed to mailserver.env)

5) Any migration script I need to run?

6) Do I need to regenerate DKIM, or anything else?

7) Anything in the "config" directory that I need to take special consideration since v7 ?

Generally, it would be nice to have a "migration guide" whenever there is a major new version, as otherwise it can be hard for us to figure out what do we need to change in our custom configs :)

Thank you very much.
Have a great day.

**Comment by wernerfred** [comment]
Hey 👋🏻 

Please have a look at the [CHANGELOG](https://github.com/docker-mailserver/docker-mailserver/blob/master/CHANGELOG.md). I think it will cover most of your questions.

Regarding your questions:

1. Take a look at the [open Issues](https://github.com/docker-mailserver/docker-mailserver/issues) We cannot say more than that what is reported by users. Most of them are Feature Requests or have speacial use cases. Take a look if something matches your setup.
2. + 3. Although I think they are all untouched feel free to spin up a 2nd container and run your commands against it :)
4. See the Changelog mentioned above. There are new variables but chances are high that you do not need to add them explicitly (only if you want to use the feature). New functionality is always backwards compatible with the exception of BREAKING CHANGES which are highlighted in the Changelog.
5. Nope
6. Not if you followed the instructions guide and persisted your `config` directory.
7. If you want to regenerate something (like DKIM) it might now uses new default values.

A migration guide is not needed imho if we have a well changelog and always backwarts compatibility in mind. If you look at the file for the last release we added all PR references to find any change to files or discussions directly.

Feel free to ask further questions if the Changelog does not answer anything for you :)

**Comment by casperklein** [comment]
If you encounter any problems, you can easily switch back to the old version, just by changing the _image_ line in your docker-compose.yml.

**Comment by wernerfred** [comment]
So @ghnp5 did you encounter any issue during upgrade or need further assistance? Please let us know. Otherwise I would like to close this Issue then.

**Comment by ghnp5** [comment]
@wernerfred - Thank you very much for the time in replying to my questions above. While I've had this issue open in a browser tab since, I have been extremely busy and haven't had the time yet to upgrade! 😁

 I'm happy to close this, anyway, and if I find any issue, I can open a new ticket specifically for it.
 
 Again - thank you very much!

**Comment by ghnp5** [comment]
@wernerfred - Stupid question. I've gone through all configs, updated stuff, etc.
I'm still on v7 🤣
Is it safe to upgrade to v10 directly from v7, or should I incrementally upgrade to v8, then v9, then v10?
