### ISSUE TITLE
STARTTLS - could not retrieve policy: 500 Can't connect to mta-sts.example.com

### ISSUE THREAD

**Issue by moookino** [docker-mailserver/docker-mailserver#1856]
# How to resolve STARTTLS + traefik TCP exposed ports

I have questions about TLS/SSL/STARTTLS/OpenSSL

## Description

I've followed installation guide for Traefik + docker-mailserver, but failing to pass any of the tests on the checktls
When trying to run check testTo: getting failure with **could not retrieve policy: 500 Can't connect to mta-sts.example.com**
After reading some information about how to configure it properly i've found https://github.com/traefik/traefik/issues/7366

Traefik version: 2.4.7
Docker-mailserver: latest docker tag

I've not touched any settings except domain name from the https://github.com/docker-mailserver/docker-mailserver/wiki/Installation-examples

Does anyone run traefik+mailserver setup successfully with TCP exposed ports in Traefik?

**Comment by wernerfred** [comment]
Please post your relevant configuration. If you followed the [these instructions](https://github.com/docker-mailserver/docker-mailserver/wiki/Installation-examples#configuration-of-the-used-proxy-software) we need at least:
- traefik docker(-compose) configuration
- docker-mailserver docker(-compose) configuration
- `dovecot.cf`
- `postfix-main.cf`
- `postfix-master.cf`

Please make sure to format your code properly to keep it readable.

**Comment by moookino** [comment]
<details>
  <summary>docker-mailserver docker-compose </summary>
  
  ```version: '2'

services:
  mail:
    image: docker.io/mailserver/docker-mailserver:latest
    hostname: mail
    domainname: example.com
    container_name: mail
#   ports:
#   - "25:25"
#   - "587:587"
#   - "465:465"
    volumes:
    - ./data/:/var/mail/
    - ./state/:/var/mail-state/
    - ./config/:/tmp/docker-mailserver/
    - ./traefik/acme.json:/etc/letsencrypt/acme.json:ro 
    environment:
    - PERMIT_DOCKER=network
    - SSL_TYPE=letsencrypt
    - ONE_DIR=1
    - DMS_DEBUG=1
    - SPOOF_PROTECTION=0
    - REPORT_RECIPIENT=1
    - ENABLE_SPAMASSASSIN=0
    - ENABLE_CLAMAV=0
    - ENABLE_FAIL2BAN=1
    - ENABLE_POSTGREY=0
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE
    restart: always
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.smtp.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.smtp.entrypoints=smtp"
      - "traefik.tcp.routers.smtp.service=smtp"
      - "traefik.tcp.services.smtp.loadbalancer.server.port=25"
      - "traefik.tcp.services.smtp.loadbalancer.proxyProtocol.version=1"
      - "traefik.tcp.routers.smtp-ssl.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.smtp-ssl.entrypoints=smtp-ssl"
      - "traefik.tcp.routers.smtp-ssl.service=smtp-ssl"
      - "traefik.tcp.services.smtp-ssl.loadbalancer.server.port=465"
      - "traefik.tcp.services.smtp-ssl.loadbalancer.proxyProtocol.version=1"
      - "traefik.tcp.routers.imap-ssl.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.imap-ssl.entrypoints=imap-ssl"
      - "traefik.tcp.routers.imap-ssl.service=imap-ssl"
      - "traefik.tcp.services.imap-ssl.loadbalancer.server.port=10993"
      - "traefik.tcp.services.imap-ssl.loadbalancer.proxyProtocol.version=2"
      - "traefik.tcp.routers.sieve.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.sieve.entrypoints=sieve"
      - "traefik.tcp.routers.sieve.service=sieve"
      - "traefik.tcp.services.sieve.loadbalancer.server.port=4190"

networks:
    proxy:
          external: true
```
</details>

<details>
  <summary>Traefik.yml</summary>
  
  ```api:
  dashboard: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
  smtp:
    address: ":25"
  smtp-ssl:
    address: ":465"
  imap-ssl:
    address: ":993"
  sieve:
    address: ":4190"
  wg:
    address: ":51820/udp"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  http:
    acme:
      email: "admin@example.com"
      storage: acme.json
      httpChallenge:
        entryPoint: http
      tlschallenge: true
# Configuring Multiple Filters
accessLog:
  filePath: "./access.log"
  format: json
  filters:    
    statusCodes:
      - "200"
      - "300-302"
    retryAttempts: true
    minDuration: "10ms"
```
</details>

<details>
  <summary>Traefik docker-compose</summary>
  
  ```version: '3'

services:
  traefik:
    image: traefik:v2.4
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
      - 25:25
      - 465:465
      - 993:993
      - 4190:4190
      - 587:587
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./acme.json:/acme.json
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.example.com`)"
      - "traefik.http.routers.traefik.middlewares=secured"

      - 'traefik.http.middlewares.authelia.forwardAuth.address=http://authentication.example.com/'
      - "traefik.http.routers.traefik-secure.middlewares=secured"
      - "traefik.http.middlewares.secured.chain.middlewares=https-only,authelia"
      - "traefik.http.middlewares.https-only.redirectscheme.scheme=https"

      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.example.com`)"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=http"
      - "traefik.http.routers.traefik-secure.service=api@internal"

  whoami:
      image: containous/whoami
      labels:
        - "traefik.http.routers.whoami.rule=Host(`mail.example.com`)"

networks:
  proxy:
    external: true
```
</details>

dovecot.cf
postfix-main.cf
postfix-master.cf
I don't have any of those in the config or any other folder created by running with docker-compose

**Comment by wernerfred** [comment]
Thanks for providing the information in a proper format (really you cannot image how many are malformated which is often the reason for the error)

One thing comes directly into my mind:
You are mapping port 587 in traefik but you do not have an entrypoint for this point defined in treafik and no label on the mailserver to define the entrypoint. So connections on port 587 will likely always get lost at traefik

> I don't have any of those in the config or any other folder created by running with docker-compose

The steps you performed from the instructions are the one to configure the proxy (traefik) software. But you are likely missing the [backend configuration](https://github.com/docker-mailserver/docker-mailserver/wiki/Installation-examples#configuration-of-the-backend-dovecot-and-postfix). Like stated in the wiki:

> The is only one condition: BOTH endpoints of the connection MUST be compatible with proxy protocol. 

Other than that the instructions in the wiki relates to 465 and 993 so implicit TLS/SSL Ports. As your are using 587 (explicit TLS/STARTTLS) there might be further configuration on the proxy and backend needed.

Keep us updated with your ongoing investigations ;)

**Comment by moookino** [comment]
port 587 is by mistake here, i want to have it same way as it's recommended on the wiki page. TLS/STARTTLS isn't mandatory for me, just trying to make things working for me 🙂 
i've removed and changed dovecot config:

```
service imap-login {
  inet_listener imaps {
    ssl = yes
    port = 10993
  }
}
```

but removed sections as i'm not using any haproxy and don't know what should i provide in that case:
```
haproxy_trusted_networks = <your-proxy-ip>, <optional-cidr-notation>
haproxy_timeout = 3 secs
    haproxy = yes

```

i've also added checktls run when trying to get updates, maybe it will help to find the right direction for me
<details>
  <summary>Checktls test</summary>
```
CheckTLS Confidence Factor for "mail@example.org": 50 (121 max)
MX Server 	Pref 	Answer 	Connect 	HELO 	TLS 	Cert 	Secure 	From 	MTA-STS 	DANE 	Score
mail.example.org
[server_ip_address:25] 	10 	FAIL 	FAIL 	FAIL 	FAIL 	FAIL 	FAIL 	FAIL 	no policy 	no TLSA 	50
Average 		0% 	0% 	0% 	0% 	0% 	0% 	0% 			50

Scan down DETAIL output below for info on errors and warnings.

Checking mail@example.org from www12-do.checktls.com:
seconds 		test stage and result
[000.000] 	     	DNS LOOKUPS
[000.000] 	     	created RESOLVER
[000.411] 	     	NS	10.132.36.231
[000.411] 	     	MX	(10) mail.example.org
[000.515] 	     	A-->example.org	unresolvable
[000.621] 	     	STS	no _mta-sts.example.org DNS record
[000.725] 	     	TLSRPT	no _smtp._tls.example.org DNS record found
[000.825] 	     	A-->mail.example.org	server_ip_address
[000.825] 	     	primary	mail.example.org
[000.825] 	     	primary-->type	MX
[000.825] 	     	primary-->DNSSEC?	no
[001.257] 	     	policy-->error	could not retrieve policy: 500 Can't connect to mta-sts.example.org:443 (certificate verify failed)
[001.257] 	     	mail.example.org	MTA-STS not OK
seconds 		test stage and result
[000.000] 		Trying TLS on mail.example.org[server_ip_address:25] (10)
[000.100] 		Cannot contact server (reason: Connection refused)
```
</details>

**Comment by wernerfred** [comment]
> but removed sections as i'm not using any haproxy and don't know what should i provide in that case:

Not haproxy but you are using traefik with the proxy protocol enabled:
` - "traefik.tcp.services.imap-ssl.loadbalancer.proxyProtocol.version=2"`

As HAProxy Technologies ["invented/described"](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt) the proxy protocol initially it's behaviour/compatibility is often reffered as "haproxy mode" by other systems. So you enabled proxy protocol on the traefik side, now you need to enable "awareness" of the proxy protocol on the backend side (like shown in the wiki page). This "awareness" is described/enabled by using the "haproxy" mode for all the settings. So this block you mentioned:

```
haproxy_trusted_networks = <your-proxy-ip>, <optional-cidr-notation>
haproxy_timeout = 3 secs
    haproxy = yes
```

is mandatory and the `haproxy_trusted_networks` option needs to be set to the IP which is assigned to traefik (see traefik = haproxy for now)

Same counts for `postfix-master.cf` and `postfix-main.cf`

Is it now clearer?

**Comment by pintoflager** [comment]
https://mta-sts.domain.com should return a textfile with mta-sts policy.

This is something you have to do by yourself. Keypoints:

- Has to be served through https
- Path to policy https://mta-sts.example.com/.well-known/mta-sts.txt
- _mta-sts TXT dns record

Read more from this [mailhardener](https://mta-sts.[domain]/.well-known/mta-sts.txt) post for example.

With traefik you'd make a container with some small server that serves your mta-sts.txt file and label that container to traefik, enable tls for it and add rule to host mta-sts.example.com

**Comment by wernerfred** [comment]
> With traefik you'd make a container with some small server that serves your mta-sts.txt file and label that container to traefik, enable tls for it and add rule to host mta-sts.example.com

I have exactly the described setup with traefik using proxy protocol but i never created a container to serve this file. If that behaviour is needed i think traefik will handle this by itself without interaction needed
