### ISSUE TITLE
Cant login to managesieve with Rainloop webmail client

### ISSUE THREAD

**Issue by fdisamuel** [docker-mailserver/docker-mailserver#1857]
# Bug Report

## Context

I can not reach managesieve installed on my mailserver from RainLoop webmail client (Hosted from the same machine) .

(I am not sure this is related to docker-mailserver.)

Similar issue on Rainloop's fithub page:  https://github.com/RainLoop/rainloop-webmail/issues/2074

### What is affected by this bug?

Rainloop 1.15.0 webmail client; mangesieve plugin, maybe Dovecot too
### When does this occur?
When I try configure Sieve integration in Rainloop webmail 
### How do we replicate the issue?

At Rainloop webmail admin panel
1. open domain configuration to edit it
2. click on "Sieve configuration"
3. Fill Sieve server
4. Click on "Test" button to ensure the configuration is working

### Actual Behavior

The interface switch back to the previous panel and IMAP and SMTP are displayed in red.
In the user webmail interface, adding new filter is not possible.  Error message: " Can't get filters"
![image](https://user-images.githubusercontent.com/62856267/111762798-b4d67d80-88a1-11eb-9287-e608776e1f4a.png)
![image](https://user-images.githubusercontent.com/62856267/111762890-cf105b80-88a1-11eb-8912-3b5d933fe42b.png)

### Expected Behavior

After configure Sieve in the admin panel, Rainloop can communicate with managesieve on port 4190.

## Your Environment

I run docker-mailserver and Rainloop-docker in two separate containers, beeing on the same docker network.

- version: `latest`
- available RAM: ` 2 GB`
- Docker version: `latest`

### Whats not working: 

- managesieve plugin at Rainloop-docker (cant connect to `mailserver` container)
### Whats working: 

- Sieve at mailserver-docker (I can manually specify sieve configs for user profiles)
- managesieve server listen on `mailserver:4190` I tested it from outside the docker network and it is reachable.

### Environment Variables
mailserver docker-compose.yml
```CFG
version: '3.8'

services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    container_name: ${CONTAINER_NAME}
    env_file: mailserver.env    #ENABLE_MANAGESIEVE=1  #SUPERVISOR_LOGLEVEL=info
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
      - "4190:4190" 
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - maillogs:/var/log/mail
      - /etc/localtime:/etc/localtime:ro
      - ./config/:/tmp/docker-mailserver/${SELINUX_LABEL}
      - /home/user/appdata/NginxProxyManager/config/letsencrypt/archive/npm-5/:/tmp/ssl
    restart: always
    cap_add: [ "NET_ADMIN", "SYS_PTRACE" ]

volumes:
  maildata:
  mailstate:
  maillogs:

networks:
  default:
    external:
      name: mailserver_default
```
Rainloop docker.compose.yml

```CFG
version: "3"

services:
  rainloop:
    image: youtous/rainloop:latest
    container_name: rainloop
    volumes:
       - /home/user/appdata/Rainloop:/rainloop/data
    networks:
       - mailserver_default
       - nginxproxymanager_default #deployed behind nginx revrese proxy

networks:
  mailserver_default:
    external: true
  nginxproxymanager_default: #deployed behind nginx revrese proxy
    external: true
```
### Relevant Logs

mailserver-docker log:
```CFG
user@vm:~/appdata/Mailserver$ sudo docker logs Mailserver | grep sieve
#These are created maybe because I tried to reach managesieve from outside the containers.
Mar 18 22:38:56 mail dovecot: managesieve-login: Disconnected: Too many invalid commands. (no auth attempts in 0 secs): user=<>, rip=myip, lip=172.19.0.2, session=<Bx81bda9B9uG/1hm>
Mar 18 22:38:57 mail dovecot: managesieve-login: Disconnected: Too many invalid commands. (no auth attempts in 1 secs): user=<>, rip=myip, lip=172.19.0.2, session=<7xNGbda9CNuG/1hm>
Mar 18 22:39:02 mail dovecot: managesieve-login: Disconnected: Too many invalid commands. (no auth attempts in 5 secs): user=<>, rip=myip, lip=172.19.0.2, session=<0Y6Sbda9C9uG/1hm>
Mar 18 22:40:08 mail dovecot: managesieve-login: Disconnected (no auth attempts in 66 secs): user=<>, rip=myipaddress, lip=172.19.0.2, session=<HE1+cda9DtuG/1hm>
Mar 18 23:10:24 mail dovecot: managesieve-login: Disconnected: Inactivity (no auth attempts in 180 secs): user=<>, rip=myipaddress, lip=172.19.0.2, session=<fQnE3da9/taG/1hm>
Mar 18 23:36:27 mail dovecot: managesieve-login: Disconnected: Inactivity (no auth attempts in 180 secs): user=<>, rip=myipaddress, lip=172.19.0.2, session=<xITuOte9jtyG/1hm>
```
EDIT: okay maybe this log is not related to my issue, since it shows up every time i use the  `sudo nc mail.mydomain.tld 4190` command to initialize connecton from outside

Rainloop log:
```CFG
sudo docker logs rainloop | grep sieve
[19-Mar-2021 10:09:11] WARNING: [pool default] child 279 said into stderr: "[19-Mar-2021 10:09:11 UTC] PHP Fatal error:  Declaration of MailSo\Sieve\ManageSieveClient::Connect($sServerName, $iPort, $iSecurityType = MailSo\Net\Enumerations\ConnectionSecurityType::AUTO_DETECT, $bVerifySsl = false, $bAllowSelfSigned = true) must be compatible with MailSo\Net\NetClient::Connect($sServerName, $iPort, $iSecurityType = MailSo\Net\Enumerations\ConnectionSecurityType::AUTO_DETECT, $bVerifySsl = false, $bAllowSelfSigned = true, $sClientCert = '') in /rainloop/rainloop/v/1.15.0/app/libraries/MailSo/Sieve/ManageSieveClient.php on line 114"
```
and
```CFG
[18-Mar-2021 22:37:33] WARNING: [pool default] child 129 said into stderr: "[18-Mar-2021 22:37:33 UTC] PHP Warning:  RainLoop\Config\AbstractConfig::RainLoop\Config\{closure}(): Argument #1 ($sLine) must be passed by reference, value given in /rainloop/rainloop/v/1.15.0/app/libraries/RainLoop/Config/AbstractConfig.php on line 306"
```

Any help is appreciated!

**Comment by fdisamuel** [comment]
UPDATE: 
I am now certainly sure this problem is related to Rainloop itself. To test this I installed previous version of Rainloop (1.14.0) with PHP 7 and everything is working as expected. There is definitely a bug in Rainloop when using with PHP 8 and managesieve.

**Comment by casperklein** [comment]
Thank you for the update. Then we can close this issue as it's not related to this project.
