### ISSUE TITLE
[BUG] sieve not getting the alias for evaluation

### ISSUE THREAD

**Issue by mcarleio** [docker-mailserver/docker-mailserver#1861]
# Bug Report

## Context

My sieve filters do not get the original mail address, only the postfix mapped one: If you have defined an alias and receive a mail to that alias, the alias will not be present in any sieve parameters, only the email address for which the alias was created.

### What is affected by this bug?
All my sieve filters do not work anymore when I use the docker-mailserver. Everything else is looking awesome!

### When does this occur?
For every mail account with at least one alias.

### How do we replicate the issue?

1. Create an email account `user1@domain.tld` with an alias:
```bash
./setup.sh email add user1@domain.tld pwd123
./setup.sh alias add notifications@domain.tld user1@domain.tld
```
2. Create a simple sieve for the created email account `user1`:
```bash
cat << 'EOF' >./config/user1@domain.tld.dovecot.sieve
require ["envelope", "fileinto", "mailbox"];
if anyof(envelope :is "to" "notifications@domain.tld") {
    fileinto :create "notifications";
    stop;
}
EOF
```
3. Boot everything up, send a mail to `notifications@domain.tld`

### Actual Behavior

The mail does not end up in the directory `notifications` of `user1@domain.tld`. Instead the mail ends up in the INBOX.

### Expected Behavior

The mail should end up in the directory `notifications` of `user1@domain.tld`, as the sieve should have moved it to that directory.

**Comment by mcarleio** [comment]
I seem to have found a workaround, but am not sure what this might have for side effects. I played around with other variants to check for the receiver and found these: 

```
if address :is "to" "notifications@domain.tld"
/* or */
if header :is "to" "notifications@domain.tld"
```

Both seem to work. Any idea why this was no solution for https://github.com/docker-mailserver/docker-mailserver/issues/504 ?

**Comment by wernerfred** [comment]
I am using [rainloop](https://github.com/wernerfred/docker-rainloop) to modify my sieve filters. If I add a filter that you described rainloop produces:
```
if header :contains ["To", "CC"] "notifications@domain.tld"
{
    fileinto "Notifications";
    stop;
}
```

So imho your solutions should not have any drawback.

If your problem is solved pls close the Issue then. Feel free to open another one (or reopen this one) if the problem/any side effects (re)appears.

**Comment by Bluejanis** [comment]
The drawback is, that it won't work for bcc. It wont be in the header either, so you need the envelope :is "to". But I am not sure how to configure docker-mailserver so that info will be passed to sieve.
