### ISSUE TITLE
Kubernetes docker-mailserver default username|password

### ISSUE THREAD

**Issue by rajsenthil** [docker-mailserver/docker-mailserver#1863]
# Looking for default username password to connect after installation.

I would like to configure a not documented mail server use case
Other I have questions about authenticating mail user with LDAP 

## Description
I am following the steps documented [here](https://github.com/docker-mailserver/docker-mailserver/blob/55daef4820bc6566c7c8b78783223b4a92ff0b46/docs/content/advanced/kubernetes.md) to deploy docker-mailserver with kubenetes. The server is started and I have set the port to be accessible outside the cluster by using **NodePort**. I see in the yaml file the line
```
postfix-accounts.cf: |
    user1@example.com|{SHA512-CRYPT}$6$2YpW1nYtPBs2yLYS$z.5PGH1OEzsHHNhl3gJrc3D.YMZkvKw/vp.r5WIiwya6z7P/CQ9GDEJDr2G2V0cAfjDFeAQPUoopsuWPXLk3u1
```

Is **user1@example.com** a default user? What is the password? I tried with different password using [thunderbird mail client](https://thunderblrd.com/) but none of them seems working. I also used my my own sha-512 hashed string for **mailserver** as password encoded as
`3e6c798a90032fbc1cc4ff98a55c19611a9d4e3884b73fe76b932e095b10b275d7d45f6b37c329e7b1306c308a2174298bdcb146928f087a78600017da3fdbdd`

but that also did not make the connection.
All the services, pods are up and running and only looking for proper way to connect. 

Also I read somewhere about connecting to LDAP server for authenticating. How to do that using Kubernetes? Please let me know.

Regards

```

**Comment by rajsenthil** [comment]
On logging into the docker container there are few files and folder are created under **/tmp/docker-mailserver/**

But it is strange that **postfix-accounts.cf** show as folder. Shouldn't this be a file as well?
```

-rw-r--r-- 1 root root   37 Mar 24 15:07 postfix-virtual.cf
**drwxrwxrwx 2 root root 4096 Mar 24 15:07 postfix-accounts.cf**
drwxrwxrwx 2 root root 4096 Mar 24 15:07 fetchmail.cf
drwxrwxrwx 2 root root 4096 Mar 24 15:07 dovecot.cf
drwxr-xr-x 3 root root 4096 Mar 24 15:07 opendkim
-rw-r--r-- 1 root root    0 Mar 24 15:07 dovecot-quotas.cf

```

The folder /tmp/docker-mailserver/postfix-accounts.cf is empty though.

**Comment by casperklein** [comment]
As the domain suggests, `user1@example.com` is only an example :-)

It's just the content of your postfix-accounts.cf which you had, if you wouldn't use Kubernetes. Accounts are generated via `setup.sh`. Take a look there, if you want to know, how the hash is generated exactly.

**Comment by rajsenthil** [comment]
> As the domain suggests, `user1@example.com` is only an example :-)
> 
> It's just the content of your postfix-accounts.cf which you had, if you wouldn't use Kubernetes. Accounts are generated via `setup.sh`. Take a look there, if you want to know, how the hash is generated exactly.

Thanks for your reply @casperklein . 
I am a newbie to mailserver configurations and if there is any question that does not make sense, sorry about that.

I copied the setup.sh to kubernetes pod and when ran got the error message 
`No supported Container Runtime Interface detected.`
I tried by editing the file postfix-accounts.cf with content as
```
user1@example.com|test123
user2@example.com|test123

```
Is that allowed? When tried to login with user1@example.com
  ```
Mar 24 20:52:36 mailserver-655c8bb445-zbq5x dovecot: auth: passwd-file(user1@example.com,172.17.0.1): Password mismatch (SHA1 of given password: 7288ed)
  Mar 24 20:52:38 mailserver-655c8bb445-zbq5x postfix/submission/smtpd[89598]: warning: unknown[172.17.0.1]: SASL PLAIN authentication failed: 
  Mar 24 20:52:42 mailserver-655c8bb445-zbq5x dovecot: auth: passwd-file(user1@example.com,172.17.0.1): Password mismatch (SHA1 of given password: 7288ed)
  Mar 24 20:52:44 mailserver-655c8bb445-zbq5x postfix/submission/smtpd[89598]: warning: unknown[172.17.0.1]: SASL LOGIN authentication failed: UGFzc3dvcmQ6

```

**Comment by casperklein** [comment]
> Then, I tried by editing the file postfix-accounts.cf with content as

I don't think this is going to work. The password must be hashed. Unfortunately, I've no experience with kubernetes.

A pragmatic solution I can think of:

Use some debian/ubuntu machine and run:

```
git clone https://github.com/docker-mailserver/docker-mailserver
cd docker-mailserver/
./setup.sh email add foo@example.com mysecretpassword
cat config/postfix-accounts.cf
```

This should give you the hash you are looking for.

**Comment by rajsenthil** [comment]
> > Then, I tried by editing the file postfix-accounts.cf with content as
> 
> I don't think this is going to work. The password must be hashed. Unfortunately, I've no experience with kubernetes.
> 
> A pragmatic solution I can think of:
> 
> Use some debian/ubuntu machine and run:
> 
> ```
> git clone https://github.com/docker-mailserver/docker-mailserver
> cd docker-mailserver/
> ./setup.sh email add foo@example.com mysecretpassword
> cat config/postfix-accounts.cf
> ```
> 
> This should give you the hash you are looking for.

Yes, thank you. That solved the auth issue. 

Using `setup.sh` was is quite easy. Only thing to remember is that I need to shutdown the running **mailserver container** before running the `setup.sh` script

As a next step, using setup.sh, I generated dkim config as 
`setup.sh config dkim domain example.com`
which generated the files
```
TrustedHosts
SigningTable
KeyTable
keys/..2021_03_25_01_15_30.332173794/example.com-mail.key

```
under /tmp/docker-mailserver folder
All these files are empty though. I am getting the same issue as [this](https://github.com/docker-mailserver/docker-mailserver/issues/1566)

in the log, the error is 
```
Mar 25 01:31:44 mailserver-655c8bb445-t2tn5 postfix/pickup[904]: 2F6A472CAA3: uid=112 from=<amavis>
Mar 25 01:31:44 mailserver-655c8bb445-t2tn5 postfix/cleanup[3125]: 2F6A472CAA3: message-id=<20210325013144.2F6A472CAA3@example.com>
Mar 25 01:31:44 mailserver-655c8bb445-t2tn5 opendkim[197]: 2F6A472CAA3: SSL error:0D06B08E:asn1 encoding routines:asn1_d2i_read_bio:not enough data
Mar 25 01:31:44 mailserver-655c8bb445-t2tn5 opendkim[197]: 2F6A472CAA3: dkim_eom(): resource unavailable: d2i_PrivateKey_bio() failed
Mar 25 01:31:44 mailserver-655c8bb445-t2tn5 postfix/cleanup[3125]: 2F6A472CAA3: milter-reject: END-OF-MESSAGE from localhost[127.0.0.1]: 4.7.0 resource unavailable; from=<amavis@example.com> to=<amavis@example.com>

```

**Comment by rajsenthil** [comment]
I confirmed that login is working. After login from the email client (Thunderbird), I see the log 
`Mar 25 03:19:52 mailserver-5f4494fb94-tjgtr dovecot: imap-login: Login: user=<user1@example.com>, method=PLAIN, rip=172.17.0.1, lip=172.17.0.34, mpid=7375, TLS, session=<N7iF41O+SzSsEQAB>`

and the below dkim error is keep showing up after that at regular intervals
```
Mar 25 03:22:17 mailserver-5f4494fb94-tjgtr postfix/cleanup[6896]: 83A1772CAB6: message-id=<20210325032217.83A1772CAB6@example.com>
Mar 25 03:22:17 mailserver-5f4494fb94-tjgtr opendkim[196]: 83A1772CAB6: SSL error:0D06B08E:asn1 encoding routines:asn1_d2i_read_bio:not enough data
Mar 25 03:22:17 mailserver-5f4494fb94-tjgtr opendkim[196]: 83A1772CAB6: dkim_eom(): resource unavailable: d2i_PrivateKey_bio() failed

```

Using setup.sh I generated the dkim config with command 
`./setup.sh config dkim domain example.com`
and it generated private keys
`/tmp/docker-mailserver/opendkim/keys/example.com/mail.private`
and 
`/tmp/docker-mailserver/opendkim/keys/example.com/mail.txt`

Not suree what to do next though.

**Comment by casperklein** [comment]
To keep things organized, please open a new issue for this problem.

As your initial issue is fixed, we can close this one?

**Comment by rajsenthil** [comment]
Opened a new [issue](https://github.com/docker-mailserver/docker-mailserver/issues/1867) and closing this one

**Comment by rajsenthil** [comment]
> To keep things organized, please open a new issue for this problem.
> 
> As your initial issue is fixed, we can close this one?

Sure, I closed this one and opened [another](https://github.com/docker-mailserver/docker-mailserver/issues/1867) one for dkim issue
