### ISSUE TITLE
[Q] [ WARNING ]  Using self-generated dhparams is considered insecure.

### ISSUE THREAD

**Issue by tdeseez** [docker-mailserver/docker-mailserver#1865]
Hi

When _docker-compose up -d mailserver_ command is started, I have this warning messages in my logs about **Using self-generated dhparams** : 
```
mail          | [ TASKLOG ]  Initializing setup
mail          | [ TASKLOG ]  Checking configuration
mail          | [ TASKLOG ]  Configuring mail server
mail          | [ WARNING ]  Using self-generated dhparams is considered as insecure.
mail          | [ WARNING ]  Unless you known what you are doing, please remove /etc/dovecot/dh.pem.
mail          | Nameservers 127.0.0.11
mail          | [ WARNING ]  Clamav is disabled. You can enable it with 'ENABLE_CLAMAV=1'
mail          | [ WARNING ]  Using self-generated dhparams is considered insecure.
mail          | [ WARNING ]  Unless you known what you are doing, please remove /etc/postfix/dhparams.pem.
```
I could easily rename files  _/etc/postfix/dhparams.pem_ and _/etc/dovecot/dh.pem_ and restart mailserver without any issue via using _docker exec -ti mail /bin/bash_.

Are those warning a bug that need to be fixed ?
Did I miss a step in my installation process ?
Is it a security flaw to host _docker-mailserver_ regardless of this warnings ? 

Thanks for your answer.

Keep up great work.

thierry

# Bug Report

### What is affected by this bug?
Warnings in logs.

### When does this occur?
When docker-mailserver is started.

### How do we replicate the issue?
When docker-mailserver is started.

1.
2.
3.
4.

## Behavior
only warnings, no effects on usability.

## Your Environment
Ubuntu Server 20.04.2 LTS 

- version: `v`
- available RAM: `4 GB`
- Docker version: `Docker version 20.10.5, build 55c4c88`
- docker-compose version: `docker-compose version 1.28.5, build c4eb3a1f`

### Environment Variables

```CFG

```

### Relevant Stack Traces

```BASH
# BEGIN
mail          | [ TASKLOG ]  Initializing setup
mail          | [ TASKLOG ]  Checking configuration
mail          | [ TASKLOG ]  Configuring mail server
mail          | [ WARNING ]  Using self-generated dhparams is considered as insecure.
mail          | [ WARNING ]  Unless you known what you are doing, please remove /etc/dovecot/dh.pem.
mail          | Nameservers 127.0.0.11
mail          | [ WARNING ]  Clamav is disabled. You can enable it with 'ENABLE_CLAMAV=1'
mail          | [ WARNING ]  Using self-generated dhparams is considered insecure.
mail          | [ WARNING ]  Unless you known what you are doing, please remove /etc/postfix/dhparams.pem.
# END
```

**Comment by aendeavor** [comment]
> Are those warning a bug that need to be fixed ?

No, this isn't a bug. We're just making sure that you know what you're doing. It's just a warning, not an error, so nothing you need to worry about.

>  Did I miss a step in my installation process ?

Probably not - we cannot really say. But the warning about the self-generated DH parameters has nothing to do with that:)

>  Is it a security flaw to host docker-mailserver regardless of this warnings ?

Technically no, you just need to know what you're doing. If you feel like you do not _really_ know, this warning makes sure to inform you.

**Comment by tdeseez** [comment]
Hi

thanks for your answer. This is kind of a biblical one : _' forgive them for they know not what they do'_.

I really don't. I just stand by by instructions I find usually.

So I guess life still goes on _'with or without'_ dhparams self signed (this one is more like a U2 quote !).

regards/

**Comment by casperklein** [comment]
If you are unsure, delete the self generated dhparams file, as the warning says.

More information:

- https://github.com/internetstandards/dhe_groups
- https://tools.ietf.org/html/rfc7919

**Comment by tdeseez** [comment]
Thanks for your tip.

Shouldn't the _self generated dhparams files_ be removed by default when mailserver is installed for the first time ? And let those who know activate those files by themselves ?
Or maybe this matter needs extra documentation in the installation guide ? 

The problem with _warnings_ in logs being you don't really know how concerning they are.

regards/

**Comment by aendeavor** [comment]
> Shouldn't the self generated dhparams files be removed by default when mailserver is installed for the first time ?

Not sure what you did exactly, but I don't see these warning in my logs when the server starts. This is the very reason these warning pop up. It's **not default behaior**.

**Comment by tdeseez** [comment]
> Not sure what you did exactly, but I don't see these warning in my logs when the server starts. This is the very reason these warning pop up. It's not default behaior.

I don't think I did something unusual. Except for one thing : I started docker **as a user**, not as root (not with sudo either).
```
sudo usermod -aG docker $USER
cd ~/docker-mailserver/
docker-compose up -d
```
This is the first time I did this way. Do you think this could be related ? 
Anyway, what's the best practice : run docker as root or as a user ?

**Comment by aendeavor** [comment]
> I don't think I did something unusual. Except for one thing : I started docker **as a user**, not as root (not with sudo either).
> 
> ``` bash
> 
> sudo usermod -aG docker $USER
> 
> cd ~/docker-mailserver/
> 
> docker-compose up -d
> 
> ```
> 
> This is the first time I did this way. Do you think this could be related ? 

Absolutely not:) The `usermod` command adds the current user to the Docker group. In this group, you're able to execute the `docker` command without superuser privileges.

> Anyway, what's the best practice : run docker as root or as a user ?

I executed the `usermod` too and I'm finewith it. But I'm working in a somewhat hardened security environment too. If you want maximal security, don't use the `usermod` command, if you want comfort, use it.

Can you just the delete this files - @casperklein are these located in the `config/` directory?

**Comment by casperklein** [comment]
No. AFAIK, the file is located somewhere in the mounted `mail-state` directory.

**Comment by daitangio** [comment]
I have the same warning when upgrading from a very old version (7.x) to the 10.x.
Deleting the file seems to right thing to do.
