### ISSUE TITLE
Dovecot running postlogin script for tracking users

### ISSUE THREAD

**Issue by chongma** [docker-mailserver/docker-mailserver#1880]
# Subject

I would like some feedback concerning a use case

## Description

Currently I am using postfix / dovecot and am planning to switch to docker-mailserver. I have a script setup in dovecot which monitors user logins.

The dovecot.conf part is like this:
``` bash
service imap-postlogin {
  # all post-login scripts are executed via script-login binary
  executable = script-login /etc/dovecot/postlogin.sh

  # the script process runs as the user specified here (v2.0.14+):
  user = $default_internal_user

  # this UNIX socket listener must use the same name as given to imap executable
  unix_listener imap-postlogin {
  }
}
```

And the postlogin.sh part is something like this:
```bash
#!/bin/sh
#USER: Username
#IP: Remote IP address
#LOCAL_IP: Local IP address
URL="https://api.example.com/logAccess?source=dovecot&entityId=0&username=$USER&ip=$IP&ipLocal=$LOCAL_IP&userAgent=unknown"
curl  --max-time 5 $URL
exec "$@"
```

Is there a way I can integrate this code?  Would I have to write a Dockerfile?  Is there an example of adding custom config to Dovecot?

**Comment by casperklein** [comment]
> Is there an example of adding custom config to Dovecot?

For sure, you just have to look in the documentation.. https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/override-defaults/dovecot/

**Comment by chongma** [comment]
@casperklein Thanks.  I looked through the FAQ but I didn't find that configuration.  It explains it really well

This page https://wiki.dovecot.org/PostLoginScripting says I need to override the 10-master.conf. The page you pointed me to has an example of how to do that.  

10-master.conf looks quite long and complicated so I will need to take a copy of it.  It seems unsatisfactory because other parts of 10-master.conf might change over time and I will keep overwriting them with my edited version.

Would have been better if post login scripting could have used local.cf

**Comment by casperklein** [comment]
I think it does exactly what you are looking for. `config/dovecot.cf` will be `local.cf` in the container:

https://github.com/docker-mailserver/docker-mailserver/blob/44bee0f935c722f5dd97d5f5333bb37b0bd34fe8/target/scripts/startup/daemons-stack.sh#L79-L82

**Comment by chongma** [comment]
After many attempts I still cannot get a postlogin script working.  My best effort so far is to get a copy of the config
```sh
docker cp mail:/etc/dovecot/conf.d/10-master.conf ./config/dovecot/10-master.conf
```
edit ./config/dovecot/10-master.conf to read
```
...
service imap {  # edited this section
  executable = imap imap-postlogin
}
service imap-postlogin { # added this part
  executable = script-login /tmp/docker-mailserver/dovecot/postlogin.sh
  user = $default_internal_user
  unix_listener imap-postlogin {
  }
}
```
add ./config/dovecot/10-master.conf to docker-compose.yml using
```yaml
volumes:
  - ./config/dovecot/10-master.conf:/etc/dovecot/conf.d/10-master.conf
```
added a test file ./config/dovecot/postlogin.sh
```bash
#!/bin/sh
#USER: Username
#IP: Remote IP address
#LOCAL_IP: Local IP address
echo "username: $USER";
echo "ip address: $IP";
echo "local ip: $LOCAL_IP";
exec "$@"
```
restarted the container but it doesn't log anything.  it doesn't let me login and logs show
```
Apr 29 07:40:01 localhost dovecot: imap-login: Login: user=<matthew.broadhead@domain.tld>, method=PLAIN, rip=<ipaddress>, lip=192.168.96.2, mpid=3863, TLS, session=<WuPGwxbBqoZRIGzp>
Apr 29 07:40:01 localhost dovecot: imap(matthew.broadhead@domain.tld)<2570><h8gAshbBfOtRIGzp>: Logged out in=533 out=3073 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
Apr 29 07:40:01 localhost dovecot: imap(matthew.broadhead@domain.tld)<2577><rXoTshbBhutRIGzp>: Logged out in=3945 out=199225 deleted=0 expunged=0 trashed=8 hdr_count=9 hdr_bytes=3443 body_count=9 body_bytes=184246
Apr 29 07:40:01 localhost dovecot: imap(matthew.broadhead@domain.tld)<3863><WuPGwxbBqoZRIGzp>: Connection closed (login finished 0.232 secs ago) in=77 out=534 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
```

**Comment by casperklein** [comment]
You can increase the log level in `/etc/dovecot/conf.d/10-logging.conf`. Maybe that helps to identify the problem.

**Comment by chongma** [comment]
when it was running it did successfully log some users, but did not allow the person logging in to list any folders or anything.  it is almost as if the 
```sh
exec "$@"
```
at the end is failing to allow execution to continue
