### ISSUE TITLE
Forward email from another mailbox

### ISSUE THREAD

**Issue by chongma** [docker-mailserver/docker-mailserver#1881]
# Subject
I would like some feedback concerning a use case

## Description

In my previous setup all email from an existing mailbox could be forwarded to another.  There was the choice whether to keep the email in the existing mailbox or to forward it without storing.  Is this possible with the stock version of docker-mailserver?

**Comment by aspettl** [comment]
Hi

I think you can just add two aliases to the mailbox:
* one is the other mailbox
* one is the same one (i.e., target address identical to the alias address, which is a real mailbox at the same time)

In the end, this means you have one line in `config/postfix-accounts.cf` (e.g. `yourmailbox@domain.xy|...`, as usual) and one line in `config/postfix-virtual.cf` (e.g. `yourmailbox@domain.xy othermailbox@domain.xy,yourmailbox@domain.xy`).

Seems to work for me.

**Comment by wernerfred** [comment]
@chongma did this solve your problem?

**Comment by chongma** [comment]
@wernerfred i haven't had time to check it yet.  it seems like it will work fine.  i will close the issue and reopen if i have any problems
