### ISSUE TITLE
[BUG] error: open database /etc/postfix/vmailbox

### ISSUE THREAD

**Issue by diveyez** [docker-mailserver/docker-mailserver#1890]
# Bug Report
 Apr  9 01:21:09 mailsrv postfix/submission/smtpd[1223]: error: open database /etc/postfix/vmailbox: No such file or directory
### What is affected by this bug?
Logins, Send, Receive
### When does this occur?
During Setup and Operation
### How do we replicate the issue?

1.
2.
3.
4.

## Your Environment

- version: `v`
- available RAM: `GB`
- Docker version: `v`
- docker-compose version: `v`

### Environment Variables

```CFG

```

### Relevant Stack Traces

```BASH
# BEGIN

# END
```

**Comment by casperklein** [comment]
You have given very little information..

Make sure you have created a mailbox. See [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md), especially the _Get up and running_ part.

**Comment by diveyez** [comment]
I did create a mailbox, it is failing the same, even with a fresh build.

I did circumvent this with `docker exec -it mailserver bash` followed by a `touch /etc/postfix/vmailbox`
However, without making the container persistent, it fails with same error

**Comment by casperklein** [comment]
Please provide your docker-compose configuration and environment variables.

**Comment by diveyez** [comment]
This issue is resolved. Using non persistent docker volumes created this problem. I advise that all users use persistent volumes to avoid this.

**Comment by srad** [comment]
I got the exact same error when I just spin up the example "error: open database /etc/postfix/vmailbox: No such file or directory"
