### ISSUE TITLE
[BUG] mailserver    | Apr  9 17:32:26 mailsrv postfix/smtp[3494]: connect to alt4.gmail-smtp-in.l.google.com[64.233.177.27]:25: Connection timed out

### ISSUE THREAD

**Issue by diveyez** [docker-mailserver/docker-mailserver#1891]
# Bug Report

### How do we replicate the issue?

1. Setup fresh docker-mailserver with required records, etc
2. Attempt to send an email to a gmail account
3.
4.

## Behavior
mailserver    | Apr  9 17:32:26 mailsrv postfix/smtp[3494]: connect to alt4.gmail-smtp-in.l.google.com[64.233.177.27]:25: Connection timed out
### Expected Behavior
Expected email to send
## Your Environment

- version: ``
- available RAM: `4GB`
- Docker version: `latest`
- docker-compose version: `latest`

### Environment Variables

```CFG

```

### Relevant Stack Traces

```BASH
# BEGIN

# END
```

**Comment by casperklein** [comment]
What happens if you try to connect manually from the host: `nc 64.233.177.27 25`

**Comment by diveyez** [comment]
No knock report

Any idea why that could be happening?

**Comment by diveyez** [comment]
I confirm, it can receive from gmail but it cannot send to it

**Comment by diveyez** [comment]
Is there anyway to send the email with another protocol because everything on port 25 is timing out, I have tried this locally, and on 3 different hosts now.

**Comment by diveyez** [comment]
I can confirm, the host is blocking all outgoing email ports. This is now resolved and can be closed.
