### ISSUE TITLE
[FR] Enhanced all-in-one ./setup.sh email list (with quotas, disk usage and aliases)

### ISSUE THREAD

**Issue by tdeseez** [docker-mailserver/docker-mailserver#1892]
# Feature Request

Display a enhanced all-in-one **_./setup.sh email list_** with quotas, disk usage and aliases for each user with one single command.

## Context

Common usage. The aim is to have more info with one glimpse. 

### Is your Feature Request related to a Problem?

No. Simply an enhancement proposal.

### Describe the Solution you'd like

The  **_./setup.sh email list_** command could display users info like this : 

```
* bobby.bob@mydomain.com ( 1,9M / ~ )
    [ aliases -> postmaster@mydomain.com, bob@mydomain.com ]

* johnny_john@mydomain.com ( 24K / 3G )
    [ aliases -> admin@mydomain.com, johnny@mydomain.com ]
```

### Are you going to implement it?

Yes, because I know the probability of someone else doing it is low and I can learn from it.

### What are you going to contribute??

Here is sample bash script which runs fine from my docker-compose working directory ; 

```
#! /bin/bash

# shellcheck source=../scripts/helper-functions.sh
#. /usr/local/bin/helper-functions.sh

#DATABASE=${DATABASE:-/tmp/docker-mailserver/postfix-virtual.cf}
DATABASE="config/postfix-accounts.cf"
ALIASES="config/postfix-virtual.cf"
QUOTAS="config/dovecot-quotas.cf"
DOCKER_MAILDATA="/var/lib/docker/volumes/docker-mailserver_maildata/_data/"
set user_found, user_data_dir, user_quota

#[[ -f ${DATABASE} ]] || errex "Error: No postfix-virtual.cf file"
#[[ -s ${DATABASE} ]] || errex "Error: Empty postfix-virtual.cf - no aliases have been added"

#grep -v "^\s*$\|^\s*\#" "${DATABASE}"
#{ grep -v "^\s*$\|^\s*\#" "${DATABASE}" || true ; } | awk -F '|' '{ print $1; }'

while read line
do
    user_found=$(echo "${line}" | awk -F '|' '{ print $1; }')
    user_data_dir=`echo "${DOCKER_MAILDATA}"$(echo "${user_found}" | awk -F '@' '{ print $2; }')/$(echo "${user_found}" | awk -F '@' '{ print $1; }')/cur`
    user_quota="~"

    # Display disk usage and quotas for specific mailbox user
    if grep -q "${user_found}" "${QUOTAS}"
    then
       user_quota=$(grep "${user_found}" "${QUOTAS}" | awk -F ':' '{ print $2; }') ;
    fi

    echo "* ${user_found} (" $(du -sh "${user_data_dir}" | awk '{ print $1; }') / "${user_quota} )"

    # Display available aliases for specific mailbox user
    echo -e "    [ aliases ->" $(grep "${user_found}" "${ALIASES}" | awk '{print $1;}' | sed ':a;N;$!ba;s/\n/, /g') "]\n"
done < "${DATABASE}"

exit 0

``` 

## Additional context

Not sure i want/have skill to "commit" directly in the project, but I think this script can be helpful (though it's certainly not perfect as it is).

### Who will that Feature be useful to?

Everyone running and managing docker-mailserver.

### What have you done already?

a sample bash script !

**Comment by aendeavor** [comment]
I like it. Here's what you have to do to open a PR (don't worry about skill, we will make sure everything is how it should be in the end):

1. Read `CONTRIBUTING.md` on how to open a PR
2. You'll find the scrits that actually do the work inside the container under `target/bin/`
3. Make your changes to the corresponding script there (I will look up its name)
4. Run linting locally (found in `CONTRIBUTING.md`)
5. Submit the PR and we will see wha CI says

**Comment by tdeseez** [comment]
Hi,
I refined my script and could successfully test it in _mailserver_ container (via  _docker-compose exec mailserver bash_ command ). 

From now on I retrieve quotas info for users with the _doveadm quota get -u_ command.
Here is what it looks like now : 

```
#! /bin/bash

# shellcheck source=../scripts/helper-functions.sh
. /usr/local/bin/helper-functions.sh

function dove_stat_to_hr()
{
  #if [ "$1" == "-" ]
  if ! [[ "$1" =~ ^[0-9]+$ ]]
  then
      echo "~" ;
  else
      echo $(( 1024*$1 )) | numfmt --to=iec ;
  fi
}

DATABASE=${DATABASE:-/tmp/docker-mailserver/postfix-accounts.cf}
ALIASES=${ALIASES:-/tmp/docker-mailserver/postfix-virtual.cf}
set user_found, dove_stat

[[ -f ${DATABASE} ]] || errex "Error: No postfix-virtual.cf file"
[[ -s ${DATABASE} ]] || errex "Error: Empty postfix-virtual.cf - no aliases have been added"

while read line
do
    user_found=$(echo "${line}" | awk -F '|' '{ print $1; }')
    dove_stat=($(doveadm quota get -u "${user_found}" | grep "STORAGE" | awk '{print $4 ; print $5 ; print $6}'))

    echo "* ${user_found} ( $(dove_stat_to_hr "${dove_stat[0]}") / $(dove_stat_to_hr "${dove_stat[1]}") ) [${dove_stat[2]}%]"
    echo -e "    [ aliases ->" $(grep "${user_found}" "${ALIASES}" | awk '{print $1;}' | sed ':a;N;$!ba;s/\n/, /g') "]\n"
done < "${DATABASE}"

exit 0
```
I'll have a look at CONTRIBUTING.md.

cheers/

**Comment by casperklein** [comment]
I haven't test your script, but that seems wrong to me:

`[[ -s ${DATABASE} ]] || errex "Error: Empty postfix-virtual.cf - no aliases have been added"`

`{$DATABASE}` should probably be `${ALIASES}`

Styling: There are some lowercase variables in your code, that should be uppercase.

**Comment by casperklein** [comment]
What is this line for? `set user_found, dove_stat`

**Comment by tdeseez** [comment]
New version of the script according to your remarks :

```
#! /bin/bash

# shellcheck source=../scripts/helper-functions.sh
. /usr/local/bin/helper-functions.sh

function dove_stat_to_hr()
{
  #if [ "$1" == "-" ]
  if ! [[ "$1" =~ ^[0-9]+$ ]]
  then
      echo "~" ;
  else
      echo $(( 1024*$1 )) | numfmt --to=iec ;
  fi
}

DATABASE=${DATABASE:-/tmp/docker-mailserver/postfix-accounts.cf}
ALIASES=${ALIASES:-/tmp/docker-mailserver/postfix-virtual.cf}

[[ -f ${DATABASE} ]] || errex "Error: No postfix-accounts.cf file"
[[ -s ${DATABASE} ]] || errex "Error: Empty postfix-accounts.cf - no accounts have been added"

while read LINE
do
    USER_FOUND=$(echo "${LINE}" | awk -F '|' '{ print $1; }')
    DOVE_STAT=($(doveadm quota get -u "${USER_FOUND}" | grep "STORAGE" | awk '{print $4 ; print $5 ; print $6}'))

    echo "* ${USER_FOUND} ( $(dove_stat_to_hr "${DOVE_STAT[0]}") / $(dove_stat_to_hr "${DOVE_STAT[1]}") ) [${DOVE_STAT[2]}%]"

    if [[ -f ${ALIASES} ]]
    then
      echo -e "    [ aliases ->" $(grep "${USER_FOUND}" "${ALIASES}" | awk '{print $1;}' | sed ':a;N;$!ba;s/\n/, /g') "]\n" ;
    fi
done < "${DATABASE}"

exit 0
```

**Comment by casperklein** [comment]
Would you like to create a PR? That way, it's easier to improve your script and you don't have to re-post it every time.

Few more things to improve:

`DATABASE=${DATABASE:-/tmp/docker-mailserver/postfix-accounts.cf}`

`DATABASE` is always empty. So this is enough: `DATABASE="/tmp/docker-mailserver/postfix-accounts.cf"`.
The same goes for the `ALIASES` line.

The other existing scripts are also wrong in this manner. @aendeavor Or do I overlook something here?

Styling: Two spaces for indentation, not four. If you are in doubt, just look at the existing scripts, that's what I regularly do 😉

**Comment by casperklein** [comment]
@tdeseez What do you think about this:

```bash
#! /bin/bash

# shellcheck source=../scripts/helper-functions.sh
. /usr/local/bin/helper-functions.sh

function dovecot_quota_to_hr()
{
  if [ "${1}" == "-" ]
  then
    echo "~"
  else
    echo $(( 1024 * ${1} )) | numfmt --to=iec
  fi
}

DATABASE="/tmp/docker-mailserver/postfix-accounts.cf"
ALIASES="/tmp/docker-mailserver/postfix-virtual.cf"

[[ -f "${DATABASE}" ]] || errex "Error: No postfix-accounts.cf file"
[[ -s "${DATABASE}" ]] || errex "Error: Empty postfix-accounts.cf - no accounts have been added"

while read LINE
do
  USER=$(echo "${LINE}" | cut -d'|' -f1)
  
  # ${QUOTA[0]} => current size
  # ${QUOTA[1]} => configured size limit
  # ${QUOTA[2]} => usage in percent
  QUOTA=($(doveadm quota get -u "${USER}" | tail -n +2 | awk '{ if ($3 == "STORAGE") { print $4" "$5" "$6 } }'))

  echo "* ${USER} ( $(dovecot_quota_to_hr "${QUOTA[0]}") / $(dovecot_quota_to_hr "${QUOTA[1]}") ) [${QUOTA[2]}%]"

  if [[ -f ${ALIASES} ]]
  then
    echo -e "    [ aliases -> "$(grep "${USER}" "${ALIASES}" | awk '{print $1;}')"]\n"
  fi
done < "${DATABASE}"

exit 0
```

**Comment by aendeavor** [comment]
What @casperklein wrote seems very good. @tdeseez shall he open a PR of will you do this on your own?

@casperklein will you or shall I open a PR about this?

**Comment by tdeseez** [comment]
I'm still not familiar with PR so I'm happy if you open the PR. Script looks great !

**Comment by casperklein** [comment]
Alright. I'll do so :+1:
