### ISSUE TITLE
dovecot: imap-login: Fatal: master: service(imap-login): child xxx killed with signal 9

### ISSUE THREAD

**Issue by cottonthread** [docker-mailserver/docker-mailserver#1893]
# Subject

Other

## Description

Thank you very much for the great container to all contributors and the excellent community. Lately my container is giving the following errors randomly, it may happen every three weeks or so.

I am on the latest stable version 9.1.0 and I am coming from an old version 7.2.0. I don't know if this would have anything to do with it as I am totally clueless as to what could be causing it:

```
    Apr  9 22:54:59 mail postfix/postscreen[20338]: fatal: watchdog timeout
    Apr  9 22:57:38 mail dovecot: master: Error: service(imap-login): Initial status notification not received in 30 seconds, killing the process
    Apr  9 22:57:40 mail dovecot: imap-login: Fatal: master: service(imap-login): child 21701 killed with signal 9
    Apr  9 22:58:06 mail dovecot: master: Error: service(pop3-login): Initial status notification not received in 30 seconds, killing the process
    Apr  9 22:58:07 mail dovecot: pop3-login: Fatal: master: service(pop3-login): child 21723 killed with signal 9
    Apr  9 22:58:10 mail dovecot: master: Error: service(imap-login): Initial status notification not received in 30 seconds, killing the process
    Apr  9 22:58:12 mail dovecot: imap-login: Fatal: master: service(imap-login): child 21727 killed with signal 9
    Apr  9 22:58:37 mail dovecot: master: Error: service(pop3-login): Initial status notification not received in 30 seconds, killing the process
    Apr  9 22:58:37 mail dovecot: pop3-login: Fatal: master: service(pop3-login): child 21749 killed with signal 9
    Apr  9 22:58:43 mail dovecot: master: Error: service(imap-login): Initial status notification not received in 30 seconds, killing the process
    Apr  9 22:58:43 mail dovecot: imap-login: Fatal: master: service(imap-login): child 21751 killed with signal 9
    Apr  9 22:59:09 mail dovecot: master: Error: service(pop3-login): Initial status notification not received in 30 seconds, killing the process
    Apr  9 22:59:09 mail dovecot: pop3-login: Fatal: master: service(pop3-login): child 21773 killed with signal 9
    Apr  9 22:59:14 mail dovecot: master: Error: service(imap-login): Initial status notification not received in 30 seconds, killing the process
    Apr  9 22:59:14 mail dovecot: imap-login: Fatal: master: service(imap-login): child 21781 killed with signal 9
    Apr  9 23:00:05 mail dovecot: master: Error: service(imap-login): Initial status notification not received in 30 seconds, killing the process
    Apr  9 23:00:06 mail dovecot: imap-login: Fatal: master: service(imap-login): child 21831 killed with signal 9
    Apr  9 23:02:00 mail dovecot: master: Error: service(pop3-login): Initial status notification not received in 30 seconds, killing the process
    Apr  9 23:02:00 mail dovecot: pop3-login: Fatal: master: service(pop3-login): child 21963 killed with signal 9
    Apr  9 23:02:30 mail dovecot: master: Error: service(pop3-login): Initial status notification not received in 30 seconds, killing the process
    Apr  9 23:02:30 mail dovecot: pop3-login: Fatal: master: service(pop3-login): child 21996 killed with signal 9
    Apr  9 23:03:01 mail dovecot: master: Error: service(pop3-login): Initial status notification not received in 30 seconds, killing the process
    Apr  9 23:03:02 mail dovecot: pop3-login: Fatal: master: service(pop3-login): child 22025 killed with signal 9
    Apr  9 23:03:32 mail dovecot: master: Error: service(pop3-login): Initial status notification not received in 30 seconds, killing the process
    Apr  9 23:03:32 mail dovecot: pop3-login: Fatal: master: service(pop3-login): child 22054 killed with signal 9
    Apr  9 23:04:03 mail dovecot: master: Error: service(pop3-login): Initial status notification not received in 30 seconds, killing the process
    Apr  9 23:04:03 mail dovecot: pop3-login: Fatal: master: service(pop3-login): child 22082 killed with signal 9
    Apr  9 23:04:36 mail dovecot: pop3-login: Fatal: master: service(pop3-login): child 22115 killed with signal 9
    Apr  9 23:05:05 mail dovecot: master: Error: service(pop3-login): Initial status notification not received in 30 seconds, killing the process
    Apr  9 23:05:05 mail dovecot: pop3-login: Fatal: master: service(pop3-login): child 22143 killed with signal 9
    Apr  9 23:05:36 mail dovecot: master: Error: service(pop3-login): Initial status notification not received in 30 seconds, killing the process
    Apr  9 23:05:36 mail dovecot: pop3-login: Fatal: master: service(pop3-login): child 22180 killed with signal 9
    Apr  9 23:06:07 mail dovecot: master: Error: service(pop3-login): Initial status notification not received in 30 seconds, killing the process
    Apr  9 23:06:07 mail dovecot: master: Error: service(pop3-login): Initial status notification not received in 30 seconds, killing the process
    Apr  9 23:06:08 mail dovecot: pop3-login: Fatal: master: service(pop3-login): child 22202 killed with signal 9
    Apr  9 23:06:38 mail dovecot: master: Error: service(pop3-login): Initial status notification not received in 30 seconds, killing the process
    Apr  9 23:06:38 mail dovecot: pop3-login: Fatal: master: service(pop3-login): child 22228 killed with signal 9
    Apr  9 23:07:09 mail dovecot: master: Error: service(pop3-login): Initial status notification not received in 30 seconds, killing the process
    Apr  9 23:07:11 mail dovecot: pop3-login: Fatal: master: service(pop3-login): child 22253 killed with signal 9
    Apr  9 23:07:43 mail dovecot: master: Error: service(pop3-login): Initial status notification not received in 30 seconds, killing the process
    Apr  9 23:07:44 mail dovecot: pop3-login: Fatal: master: service(pop3-login): child 22278 killed with signal 9
    Apr  9 23:08:14 mail dovecot: master: Error: service(pop3-login): Initial status notification not received in 30 seconds, killing the process
    Apr  9 23:08:14 mail dovecot: pop3-login: Fatal: master: service(pop3-login): child 22298 killed with signal 9
    Apr  9 23:08:45 mail dovecot: master: Error: service(pop3-login): Initial status notification not received in 30 seconds, killing the process
    Apr  9 23:08:47 mail dovecot: pop3-login: Fatal: master: service(pop3-login): child 22326 killed with signal 9
    Apr  9 23:09:17 mail dovecot: master: Error: service(pop3-login): Initial status notification not received in 30 seconds, killing the process
    Apr  9 23:09:17 mail dovecot: pop3-login: Fatal: master: service(pop3-login): child 22348 killed with signal 9
    Apr  9 23:09:48 mail dovecot: master: Error: service(pop3-login): Initial status notification not received in 30 seconds, killing the process
	Apr  9 23:09:49 mail dovecot: pop3-login: Fatal: master: service(pop3-login): child 22374 killed with signal 9
    Apr  9 23:10:20 mail dovecot: master: Error: service(pop3-login): Initial status notification not received in 30 seconds, killing the process
    Apr  9 23:10:20 mail dovecot: pop3-login: Fatal: master: service(pop3-login): child 22401 killed with signal 9
    Apr  9 23:10:55 mail dovecot: master: Error: service(pop3-login): Initial status notification not received in 30 seconds, killing the process
    Apr  9 23:11:06 mail dovecot: pop3-login: Fatal: master: service(pop3-login): child 22429 killed with signal 9
    Apr  9 23:11:37 mail dovecot: master: Error: service(pop3-login): Initial status notification not received in 30 seconds, killing the process
    Apr  9 23:11:40 mail dovecot: pop3-login: Fatal: master: service(pop3-login): child 22460 killed with signal 9
    Apr  9 23:12:10 mail dovecot: master: Error: service(pop3-login): Initial status notification not received in 30 seconds, killing the process
    Apr  9 23:12:11 mail dovecot: pop3-login: Fatal: master: service(pop3-login): child 22470 killed with signal 9
    Apr  9 23:12:42 mail dovecot: master: Error: service(pop3-login): Initial status notification not received in 30 seconds, killing the process
    Apr  9 23:12:43 mail dovecot: pop3-login: Fatal: master: service(pop3-login): child 22476 killed with signal 9
    Apr  9 23:13:16 mail dovecot: master: Error: service(pop3-login): Initial status notification not received in 30 seconds, killing the process
    Apr  9 23:13:17 mail dovecot: pop3-login: Fatal: master: service(pop3-login): child 22482 killed with signal 9
    Apr  9 23:13:50 mail dovecot: master: Error: service(pop3-login): Initial status notification not received in 30 seconds, killing the process
    Apr  9 23:13:55 mail dovecot: pop3-login: Fatal: master: service(pop3-login): child 22490 killed with signal 9
    Apr  9 23:13:59 mail dovecot: master: Error: service(imap-login): Initial status notification not received in 30 seconds, killing the process
    Apr  9 23:14:10 mail dovecot: imap-login: Fatal: master: service(imap-login): child 22491 killed with signal 9
    Apr  9 23:14:35 mail dovecot: master: Error: service(pop3-login): Initial status notification not received in 30 seconds, killing the process
    Apr  9 23:14:54 mail dovecot: master: Error: service(imap-login): Initial status notification not received in 30 seconds, killing the process
    Apr  9 23:14:54 mail dovecot: pop3-login: Fatal: master: service(pop3-login): child 22497 killed with signal 9
    Apr  9 23:14:54 mail dovecot: imap-login: Fatal: master: service(imap-login): child 22500 killed with signal 9
    Apr  9 23:15:05 mail postfix/smtpd[22553]: fatal: no SASL authentication mechanisms
    Apr  9 23:15:05 mail postfix/smtpd[22554]: fatal: no SASL authentication mechanisms
    Apr  9 23:15:05 mail dovecot: pop3-login: Error: master(pop3): net_connect_unix(pop3) failed: Connection refused (client-pid=22507, client-id=1, rip=79.150.179.192, created 0 msecs ago, received 0/4 bytes)
    Apr  9 23:15:05 mail postfix/smtpd[22555]: fatal: no SASL authentication mechanisms
    Apr  9 23:15:05 mail postfix/smtpd[22556]: fatal: no SASL authentication mechanisms
    Apr  9 23:15:05 mail postfix/smtpd[22557]: fatal: no SASL authentication mechanisms
```
I am attaching my docker-compose.yml configuration as well:

```
version: '3'
services:
  mail:
    image: mailserver/docker-mailserver:stable
    hostname: mail
    domainname: xxx
    container_name: mail
    ports:
    -   "25:25"
    -   "110:110"
    -   "143:143"
    -   "587:587"
    -   "993:993"
    -   "995:995"
    -   "465:465"
    volumes:
    - $HOME/mailserver/mail/:/var/mail/
    - $HOME/mailserver/mail-state/:/var/mail-state/
    - $HOME/mailserver/logs/:/var/log/mail/
    - $HOME/mailserver/config/:/tmp/docker-mailserver/
    - $HOME/www/Certfications/acme/acme-v02.api.letsencrypt.org/sites/mail.disframed.tk/mail.disframed.tk.crt:/tmp/ssl/cert/public.crt
    - $HOME/www/Certfications/acme/acme-v02.api.letsencrypt.org/sites/mail.disframed.tk/mail.disframed.tk.key:/tmp/ssl/private/private.key
    environment:
    -   "TZ=Europe/Madrid"
    -   "OVERRIDE_HOSTNAME=mail.xxx"
    -   "DMS_DEBUG=1"
    -   "ONE_DIR=1"
    -   "POSTMASTER_ADDRESS=master@xxx"
    -   "PERMIT_DOCKER=connected-networks"
    -   "TLS_LEVEL=intermediate"
    -   "SPOOF_PROTECTION="
    -   "ENABLE_SRS=0"
    -   "ENABLE_POP3=1"
    -   "ENABLE_CLAMAV=0"
    -   "ENABLE_FAIL2BAN=1"
    -   "ENABLE_MANAGESIEVE="
    -   "POSTSCREEN_ACTION=enforce"
    -   "SMTP_ONLY="
    -   "SSL_TYPE=manual"
    -   "SSL_CERT_PATH=/tmp/ssl/cert/public.crt"
    -   "SSL_KEY_PATH=/tmp/ssl/private/private.key"
    -   "VIRUSMAILS_DELETE_DELAY="
    -   "ENABLE_POSTFIX_VIRTUAL_TRANSPORT="
    -   "POSTFIX_DAGENT="
    -   "POSTFIX_MAILBOX_SIZE_LIMIT=5368706371" 
    -   "POSTFIX_MESSAGE_SIZE_LIMIT=26214400"
    -   "PFLOGSUMM_TRIGGER=daily_cron"
    -   "PFLOGSUMM_RECIPIENT="
    -   "PFLOGSUMM_SENDER="
    -   "LOGWATCH_INTERVAL=weekly"
    -   "LOGWATCH_RECIPIENT="
    -   "REPORT_RECIPIENT=0"
    -   "REPORT_SENDER="
    -   "REPORT_INTERVAL=weekly"
    -   "POSTFIX_INET_PROTOCOLS=ipv4"
    -   "ENABLE_SPAMASSASSIN=1"
    -   "SPAMASSASSIN_SPAM_TO_INBOX=1"
    -   "MOVE_SPAM_TO_JUNK=1"
    -   "SA_TAG=2.0"
    -   "SA_TAG2=6.31"
    -   "SA_KILL=6.31"
    -   "SA_SPAM_SUBJECT=***SPAM*****"
    -   "ENABLE_FETCHMAIL=0"
    -   "FETCHMAIL_POLL=300"
    -   "ENABLE_LDAP="
    -   "LDAP_START_TLS="
    -   "LDAP_SERVER_HOST="
    -   "LDAP_SEARCH_BASE="
    -   "LDAP_BIND_DN="
    -   "LDAP_BIND_PW="
    -   "LDAP_QUERY_FILTER_USER="
    -   "LDAP_QUERY_FILTER_GROUP="
    -   "LDAP_QUERY_FILTER_ALIAS="
    -   "LDAP_QUERY_FILTER_DOMAIN="
    -   "DOVECOT_TLS="
    -   "DOVECOT_USER_FILTER="
    -   "DOVECOT_PASS_FILTER="
    -   "DOVECOT_MAILBOX_FORMAT=maildir"
    -   "DOVECOT_AUTH_BIND="
    -   "ENABLE_POSTGREY=0"
    -   "POSTGREY_DELAY=300"
    -   "POSTGREY_MAX_AGE=35"
    -   "POSTGREY_TEXT=Delayed by postgrey"
    -   "POSTGREY_AUTO_WHITELIST_CLIENTS=5"
    -   "ENABLE_SASLAUTHD=0"
    -   "SASLAUTHD_MECHANISMS="
    -   "SASLAUTHD_MECH_OPTIONS="
    -   "SASLAUTHD_LDAP_SERVER="
    -   "SASLAUTHD_LDAP_SSL="
    -   "SASLAUTHD_LDAP_BIND_DN="
    -   "SASLAUTHD_LDAP_PASSWORD="
    -   "SASLAUTHD_LDAP_SEARCH_BASE="
    -   "SASLAUTHD_LDAP_FILTER="
    -   "SASLAUTHD_LDAP_START_TLS="
    -   "SASLAUTHD_LDAP_TLS_CHECK_PEER="
    -   "SASL_PASSWD="
    -   "SRS_SENDER_CLASSES=envelope_sender"
    -   "SRS_EXCLUDE_DOMAINS="
    -   "SRS_SECRET="
    -   "DEFAULT_RELAY_HOST="
    -   "RELAY_HOST="
    -   "RELAY_PORT="
    -   "RELAY_USER="
    -   "RELAY_PASSWORD="
    -   "ENABLE_QUOTAS=1"
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE
    restart: always
    stop_grace_period: 1m30s
```

Thank you!

**Comment by casperklein** [comment]
> I don't know if this would have anything to do with it

You can easily test this by switching back to the old version and see if the errors are gone.

Are you sure you are on 9.1.0? You are probably not using the _latest_ image. We migrated the images to a new location. Please use `image: docker.io/mailserver/docker-mailserver:latest` instead of `image: tvial/docker-mailserver:latest` in your `docker-compose.yml`. Or even better, use versioned tags like `docker-mailserver:9`. That way, you won't hit by breaking changes.

Make also sure to read the [CHANGELOG](https://github.com/docker-mailserver/docker-mailserver/blob/master/CHANGELOG.md), especially the parts about breaking changes.

**Comment by cottonthread** [comment]
> > I don't know if this would have anything to do with it
> 
> You can easily test this by switching back to the old version and see if the errors are gone.
> 
> Are you sure you are on 9.1.0? You are probably not using the _latest_ image. We migrated the images to a new location. Please use `image: docker.io/mailserver/docker-mailserver:latest` instead of `image: tvial/docker-mailserver:latest` in your `docker-compose.yml`. Or even better, use versioned tags like `docker-mailserver:9`. That way, you won't hit by breaking changes.
> 
> Make also sure to read the [CHANGELOG](https://github.com/docker-mailserver/docker-mailserver/blob/master/CHANGELOG.md), especially the parts about breaking changes.

Hello, thank you very much for your answer. It is true that the docker data that I pasted were wrong, because I copied in a place where the data that did not correspond to reality. I have already corrected it.

And to ensure that I have the latest version of Mail-Server, I just performed: 
```docker-compose pull mail && docker-compose down mail && docker-compose up -d mail```
I understand that with this command and image: mailserver/docker-mailserver:stable, I should download version 9.10 as it is now.

Looking at the Breaking-changes, I think I understand that there is a part could affect my configuration:

```
[security] TLS: TLS_LEVEL=intermediate has removed support for cipher suites using RSA for key exchange (only available with an RSA certificate) (#1802).
NOTE: This only affects Dovecot which supported 5 extra cipher suites using AES-CBC and AES-GCM. Your users MUA clients should be unaffected, preferring ECDHE or DHE for key exchange.
```

I don't know how it would actually affects me. Since I use the method of obtaining the certificate via Caddy 1 and the certification type is RSA 2048:

```
        tls register@xxx {
                key_type rsa2048
        }

```

Could you explain me what dose *has removed support for cipher suites using RSA for key exchange (only available with an RSA certificate)* means to me? Thank you very much!

**Comment by aendeavor** [comment]
Please note `stable` does not correspond to `9.1.0`. `latest` is `9.1.0`.

**Comment by cottonthread** [comment]
> Please note `stable` does not correspond to `9.1.0`. `latest` is `9.1.0`.

Oops, I have always thought that the stable tag corresponds to the latest Release, in this case 9.1.0. 

So what version did I put?

**Comment by aendeavor** [comment]
Should be the latest `8.x.x`. The stable tag is about to be deleted, since it causes confusion. You should use the explicit version number to pin the version:)

**Comment by cottonthread** [comment]
> Should be the latest `8.x.x`. The stable tag is about to be deleted, since it causes confusion. You should use the explicit version number to pin the version:)

Ok, so what I thought I updated is not what was actually done. I get it now. Thank you very much.
And just to get out of doubt, I am now with the RSA2048 key provided by Caddy 1, by upgrading to version 9.1.0 really, could it cause any problems? I am referring specifically to this section:
```
[security] TLS: TLS_LEVEL=intermediate has removed support for cipher suites using RSA for key exchange (only available with an RSA certificate) (#1802).
NOTE: This only affects Dovecot which supported 5 extra cipher suites using AES-CBC and AES-GCM. Your users MUA clients should be unaffected, preferring ECDHE or DHE for key exchange.```

**Comment by aendeavor** [comment]
@polarathene Can you help?:)

**Comment by polarathene** [comment]
That change is about RSA key exchange, as the note says it only affects users mail clients connecting to the server over cipher suites via RSA key exchange.

This shouldn't be an issue with any modern client that can use more secure cipher suites using the ECDHE or DHE key exchanges, certificate type should not affect their availability. Postfix always excluded these for receiving/sending mail, so I highly doubt it'd cause any problems.

If your users are unable to connect to IMAP/POP3 securely, let us know and you can use a custom config to enable the old cipher suites again. Or your users can update their mail client software if possible instead, IIRC mail clients from the past decade should have no problem supporting ECDHE or DHE.

**Comment by cottonthread** [comment]
> That change is about RSA key exchange, as the note says it only affects users mail clients connecting to the server over cipher suites via RSA key exchange.
> 
> If you use an RSA certificate, RSA key exchange is one of the available key exchange options, but we have removed that, you should be ok with the more modern key exchange alternatives instead. No change is required on your end, the mail software should negotiate this when connecting to the mail server, it has probably not been using RSA key exchange if it can use the modern alternatives.
> 
> This shouldn't be an issue with any modern client that can use more secure cipher suites using the ECDHE or DHE key exchanges, certificate type should not affect their availability. Postfix always excluded these for receiving/sending mail, so I highly doubt it'd cause any problems.
> 
> If your users are unable to connect with IMAP/POP3 securely, let us know and you can use a custom config to enable the old cipher suites again. Or your users can update their mail client software if possible instead, IIRC mail clients from the past decade should have no problem supporting ECDHE or DHE.

Roger that, thank you very much for your answer. I just updated to the latest container yesterday via the **docker-mailserver:9.1.0** tag and so far it looks like all mail clients are not having problems receiving or sending. (Outlook, Thunderbird, Gmail, K-9 Mail)

Going back to my original intention of asking this question, the night my container log reported the following error:
```
Apr 9 22:57:38 mail dovecot: master: Error: service(imap-login): Initial status notification not received in 30 seconds, killing the process
Apr 9 22:57:40 mail dovecot: imap-login: Fatal: master: service(imap-login): child 21701 killed with signal 9
```
I understand that there is some kind of problem with the **dovecot** program in the original **stable** tag container, but I can't understand what the problem is through the logs. Can you tell anything from it?

Because this error is causing my entire docker service to go down and deny all other containers external connections and cause a high CPU load on the server. I'd love to get some help from you on how to troubleshoot this.

Thanks again for your kind help!

**Comment by polarathene** [comment]
I mostly only have knowledge on the security related parts I've contributed to the project as well as documentation.

It would be helpful if you can reproduce the error reliably and relay those instructions along with a docker-compose config.

---

There are some google results on the error, but nothing particularly helpful. It could be a variety of things as we have very little context. The size / resources of the server, how many connections / users it's supporting, if AppArmor or SE_Linux or Firewalls and such are at play and potentially interfering, if you use ClamAV or other services in the container that may contribute towards the issue. Config changes that differ from the image defaults could be another, possibly issues with migration too? (ssince persisted state is carried across)

None of which I can provide any better advice to you beyond considering all that for debugging/troubleshooting on your end unfortunately :cry:

**Comment by cottonthread** [comment]
> I mostly only have knowledge on the security related parts I've contributed to the project as well as documentation.
> 
> It would be helpful if you can reproduce the error reliably and relay those instructions along with a docker-compose config.
> 
> There are some google results on the error, but nothing particularly helpful. It could be a variety of things as we have very little context. The size / resources of the server, how many connections / users it's supporting, if AppArmor or SE_Linux or Firewalls and such are at play and potentially interfering, if you use ClamAV or other services in the container that may contribute towards the issue. Config changes that differ from the image defaults could be another, possibly issues with migration too? (ssince persisted state is carried across)
> 
> None of which I can provide any better advice to you beyond considering all that for debugging/troubleshooting on your end unfortunately 😢

Ok, you guys have helped me a lot. Unfortunately I wasn't able to get the original problem back, I'll try using version 9.1.0 now to see if the above problem still occurs. (I hope not)
I'll close the issue now and I'll open it again if something new happens. I also hope that other people who see this problem can re-open the problem and study it together. Thank you!

**Comment by cottonthread** [comment]
Hello again, the problem has appeared again and I am certainly not able to reproduce it. Although now with the new search, I think the problem could be in 'login_process_size', I found this post talking about how to fix it: https://serverfault.com/questions/707836/dovecot-is-not-working/707837#707837 now, I am not able to find this parameter in the container and I don't know how I could execute it. Could you help me again please? Thank you very much!

@polarathene @aendeavor @casperklein

**Comment by polarathene** [comment]
The [old dovecot wiki for `LoginProcess`](https://wiki1.dovecot.org/LoginProcess) details `login_process_size`. However, this setting **is not mentioned** in the [active wiki docs for `LoginProcess`](https://wiki.dovecot.org/LoginProcess). That setting [was **deprecated a decade ago** and replaced with `vsz_limit`](https://dovecot.dovecot.narkive.com/CdqRj4Nr/upgrade-to-v2-0-conf-file-fails).

Here is relevant config file and it's snippets:

https://github.com/docker-mailserver/docker-mailserver/blob/04e98dc49f54bf385edb5f02dd15fdad8afc7217/target/dovecot/10-master.conf#L4-L7

https://github.com/docker-mailserver/docker-mailserver/blob/04e98dc49f54bf385edb5f02dd15fdad8afc7217/target/dovecot/10-master.conf#L17-L36

https://github.com/docker-mailserver/docker-mailserver/blob/04e98dc49f54bf385edb5f02dd15fdad8afc7217/target/dovecot/10-master.conf#L62-L69

Our docs advise for larger or temporary config changes to [modify and replace the equivalent config file](https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/override-defaults/dovecot/#override-configuration). That may be suitable for you to test with.

If you're more comfortable with shell scripts, a more correct approach for production use is to apply your own modifications on top of the ones we provide, thus your config will remain in sync with any changes/fixes we push out in future releases. Documentation for this is explained [here](https://docker-mailserver.github.io/docker-mailserver/edge/faq/#how-to-adjust-settings-with-the-user-patchessh-script) via `user-patches.sh`.

Your script might be something like (untested):

```bash
#!/bin/bash

# Default is 256M? Replace with your own value here
DOVECOT_VSZ_LIMIT='1G'

# `sed` will check for config line starting with `#default_vsz_limit`, the `#` ensures it's only updating the expected default config.
sed -i "s|^#default_vsz_limit.*|default_vsz_limit = ${DOVECOT_VSZ_LIMIT}|" '/etc/dovecot/conf.d/10-master.conf'
```

---

If we look at the current Dovecot docs, `vsz_limit` is advised at 64M size, or 1G for the high-performance (but bad security) config. Our config seems to imply the default is 256M though. The docs do mention this however:

> `vsz_limit` should be increased to avoid out of memory errors, especially if you're using SSL/TLS.

You have not shared details about your deployment environment. What sort of RAM capacity does it have? Do you have plenty of memory available? Or is it possible at some point that becomes limited and potentially the cause of the Dovecot breaking?

If you have sufficient memory, perhaps the default really is not enough and `vsz_limit` needs to be increased. I am only relaying this information I came across and do not know the functionality well enough to advise further.

---

During quick google queries, I did come across [this old answer](https://serverfault.com/questions/588391/how-to-get-doveconf-to-reload-its-config-or-read-from-etc-dovecot), they may have had a similar issue you experience and talk about other config options that might be relevant for you to look into and try (consult the official Dovecot docs to ensure they're still the same setting names and you understand what they actually do).

**Comment by cottonthread** [comment]
> The [old dovecot wiki for `LoginProcess`](https://wiki1.dovecot.org/LoginProcess) details `login_process_size`. However, this setting **is not mentioned** in the [active wiki docs for `LoginProcess`](https://wiki.dovecot.org/LoginProcess). That setting [was **deprecated a decade ago** and replaced with `vsz_limit`](https://dovecot.dovecot.narkive.com/CdqRj4Nr/upgrade-to-v2-0-conf-file-fails).
> 
> Here is relevant config file and it's snippets:
> 
> https://github.com/docker-mailserver/docker-mailserver/blob/04e98dc49f54bf385edb5f02dd15fdad8afc7217/target/dovecot/10-master.conf#L4-L7
> 
> https://github.com/docker-mailserver/docker-mailserver/blob/04e98dc49f54bf385edb5f02dd15fdad8afc7217/target/dovecot/10-master.conf#L17-L36
> 
> https://github.com/docker-mailserver/docker-mailserver/blob/04e98dc49f54bf385edb5f02dd15fdad8afc7217/target/dovecot/10-master.conf#L62-L69
> 
> Our docs advise for larger or temporary config changes to [modify and replace the equivalent config file](https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/override-defaults/dovecot/#override-configuration). That may be suitable for you to test with.
> 
> If you're more comfortable with shell scripts, a more correct approach for production use is to apply your own modifications on top of the ones we provide, thus your config will remain in sync with any changes/fixes we push out in future releases. Documentation for this is explained [here](https://docker-mailserver.github.io/docker-mailserver/edge/faq/#how-to-adjust-settings-with-the-user-patchessh-script) via `user-patches.sh`.
> 
> Your script might be something like (untested):
> 
> ```shell
> #!/bin/bash
> 
> # Default is 256M? Replace with your own value here
> DOVECOT_VSZ_LIMIT='1G'
> 
> # `sed` will check for config line starting with `#default_vsz_limit`, the `#` ensures it's only updating the expected default config.
> sed -i "s|^#default_vsz_limit.*|default_vsz_limit = ${DOVECOT_VSZ_LIMIT}|" '/etc/dovecot/conf.d/10-master.conf'
> ```
> 
> If we look at the current Dovecot docs, `vsz_limit` is advised at 64M size, or 1G for the high-performance (but bad security) config. Our config seems to imply the default is 256M though. The docs do mention this however:
> 
> > `vsz_limit` should be increased to avoid out of memory errors, especially if you're using SSL/TLS.
> 
> You have not shared details about your deployment environment. What sort of RAM capacity does it have? Do you have plenty of memory available? Or is it possible at some point that becomes limited and potentially the cause of the Dovecot breaking?
> 
> If you have sufficient memory, perhaps the default really is not enough and `vsz_limit` needs to be increased. I am only relaying this information I came across and do not know the functionality well enough to advise further.
> 
> During quick google queries, I did come across [this old answer](https://serverfault.com/questions/588391/how-to-get-doveconf-to-reload-its-config-or-read-from-etc-dovecot), they may have had a similar issue you experience and talk about other config options that might be relevant for you to look into and try (consult the official Dovecot docs to ensure they're still the same setting names and you understand what they actually do).

Hello, thank you very much for your help, my server has 1 vCPU and 2GB of RAM, according to what I understood from your theory, it could be that it is lacking RAM, so I have decided to increase it to 4GB to see if that could fix the problem. In case of further failure, I will come back to this post. Thank you very much!
