### ISSUE TITLE
[BUG] Postfix acts as open relay by default when deploying a stack in docker swarm mode

### ISSUE THREAD

**Issue by dfyx** [docker-mailserver/docker-mailserver#1903]
# Bug Report

## Context

When the recommended docker-compose.yml gets deployed into docker swarm mode, all ports get published through the ingress network by default which makes all incoming connections look like they come from within `10.0.0.0/24` which is in `mynetworks`.

### What is affected by this bug?

Postfix

### When does this occur?

When docker-mailserver is deployed as a stack or service in docker swarm mode without explicitly setting the port publish mode to host.

### How do we replicate the issue?

1. Configure docker-mailserver as described in the documentation
2. Deploy with `docker stack deploy` instead of `docker-compose up`.
3. Connect with `telnet`/`netcat` or wait for the usual spam to arrive.

### Actual Behavior

**telnet:**
```smtp
220 mail.mydomain.de ESMTP
HELO mydomain.de
250 mail.mydomain.de
MAIL FROM: <test@example.com>
250 2.1.0 Ok
RCPT TO: <test@gmail.com>
250 2.1.5 Ok
```

**log:**
```
Apr 13 18:37:05 77daf529c864 postfix/postscreen[2129]: cache btree:/var/lib/postfix/postscreen_cache full cleanup: retained=0 dropped=0 entries
Apr 13 18:37:05 77daf529c864 postfix/postscreen[2129]: CONNECT from [10.0.0.2]:60456 to [10.0.0.8]:25
Apr 13 18:37:05 77daf529c864 postfix/postscreen[2129]: WHITELISTED [10.0.0.2]:60456
Apr 13 18:37:05 77daf529c864 postfix/smtpd[2130]: connect from unknown[10.0.0.2]
Apr 13 18:37:05 77daf529c864 opendmarc[1135]: ignoring connection from [10.0.0.2]
Apr 13 18:38:15 77daf529c864 postfix/smtpd[2130]: 453B6201E96: client=unknown[10.0.0.2]
```

### Expected Behavior

**telnet:**
```smtp
220-mail.mydomain.de ESMTP
HELO mydomain.de
250 mail.mydomain.de
MAIL FROM: <test@example.com>
250 2.1.0 Ok
RCPT TO: <test@gmail.com>
550 5.5.1 Protocol error
```

**log:**
```
Apr 13 18:42:41 62de164fa2ea postfix/postscreen[1877]: cache btree:/var/lib/postfix/postscreen_cache full cleanup: retained=0 dropped=0 entries
Apr 13 18:42:41 62de164fa2ea postfix/postscreen[1877]: CONNECT from [x.x.52.104]:33428 to [172.18.0.14]:25
Apr 13 18:42:41 62de164fa2ea postfix/dnsblog[1881]: warning: dnsblog_query: lookup error for DNS query 104.52.x.x.list.dnswl.org: Host or domain name not found. Name service error for name=104.52.x.x.list.dnswl.org type=A: Host not found, try again
Apr 13 18:42:41 62de164fa2ea postfix/dnsblog[1881]: warning: dnsblog_query: lookup error for DNS query 104.52.x.x.zen.spamhaus.org: Host or domain name not found. Name service error for name=104.52.x.x.zen.spamhaus.org type=A: Host not found, try again
Apr 13 18:42:45 62de164fa2ea postfix/postscreen[1877]: PREGREET 17 after 3.8 from [x.x.52.104]:33428: HELO mydomain.de
Apr 13 18:43:08 62de164fa2ea postfix/postscreen[1877]: NOQUEUE: reject: RCPT from [x.x.52.104]:33428: 550 5.5.1 Protocol error; from=<test@example.com>, to=<test@gmail.com>, proto=SMTP, helo=<mydomain.de>
```

## How this should be fixed

To be fair, there's probably no catch-all solution to this. But there should at least be a warning in the documentation since this leads to instances of docker-mailserver to become unsecured spam relays. In the 15 minutes I needed to notice and fix this, I got a total of 9 abuse reports from my datacenter.

Possible solutions:
* Remove `10.0.0.0/24` from `mynetworks` when running in swarm mode. Direct linking of containers is deprecated, so other containers will probably contact the mail server through a different overlay network (subnet `10.0.11.0/24` in my case) anyway.
* Define ports in long format and mark them as `mode: host`. This would be prefered so the server can see the actual IP address but might not be possible in multi-node swarms.
  ```yaml
  ports:
  - target: 25
    published: 25
    protocol: tcp
    mode: host
  ```

**Comment by aendeavor** [comment]
I'm running Swarm as well, this is my ports section:

``` YAML
ports:
      - target:    25
        published: 25
        protocol:  tcp
        mode:      host
      # ESMTP with explicit TLS (STARTTLS)
      - target:    587
        published: 587
        protocol:  tcp
        mode:      host
      # ESMTP with implicit TLS
      - target:    465
        published: 465
        protocol:  tcp
        mode:      host
      # IMAPS with implicit TLS
      - target:    993
        published: 993
        protocol:  tcp
        mode:      host
```

I think that the name of the file `docker-compose.yml` actually makes clear that this is intended to be used with Compose, not Swarm. However, an easy fix would be to use the long syntax for the ports section in the Compose file as well. I will provide a PR.

**Comment by aendeavor** [comment]
We can close this, as we have seen that in #1907, Swarm is not officially supported - we therefore assume users who use Swarm are aware of networking in Swarm.

Nevertheless, thanks for this report!
