### ISSUE TITLE
Refiltering emails with sieve-filter?

### ISSUE THREAD

**Issue by dugite-code** [docker-mailserver/docker-mailserver#1905]
# Subject

I would like to configure a not documented mail server use case

## Description

I want to trigger the sieve-filter manually to Refilter a mailbox. Ultimately I plan on doing this regularly to a specific folder in order to have it automatically archive emails based on the date.

I've tried to test this manually with several users in the docker container (mail, dovecot, docker, root, amavis) `sudo docker exec -it -u mail 94545520465a bash`

This is always the output:

``` BASH
sieve-filter -v -C -u dugite-code /var/mail/example.tld/dugite-code/sieve/Filter.sieve INBOX
sieve-filter: Fatal: Unknown user
```

I've also tried to determine my username using `doveadm user dugite-code@example.tld` and it works on root but no other user

I realize this probably isn't the correct way to go about this but I haven't been able to figure out a starting point.

**Comment by dugite-code** [comment]
The stale bot reminded me to try one action I hadn't thought of. As I use docker-compose:

```
sudo docker-compose exec mail sh -c "sieve-filter -v -C -u dugite-code /var/mail/example.tld/dugite-code/sieve/Filter.sieve INBOX"
```

I'm still not sure why this works and `sudo docker exec -it` doesn't as `sudo docker-compose exec mail sh -c "whoami"` returns `root`

**Comment by casperklein** [comment]
`sudo docker-compose exec mail sh -c "sieve-filter -v -C -u dugite-code /var/mail/example.tld/dugite-code/sieve/Filter.sieve INBOX"`

should be the same as:
`sudo docker exec exec mail sh -c "sieve-filter -v -C -u dugite-code /var/mail/example.tld/dugite-code/sieve/Filter.sieve INBOX"`

The only difference I see to your first post is the usage of the `-u` switch in the docker command which in the latest docker version (20.10.6) doesn't even exist.
