### ISSUE TITLE
The best way to backup my configuration, accounts and emails

### ISSUE THREAD

**Issue by e-fo** [docker-mailserver/docker-mailserver#1906]
# Subject
I have  questions about the best backup method for docker-mailserver

## Description
I searched your documents and I couldn't find anything about backup. I looking for a method that able me to backup my configs, accounts and their emails.

I appreciate you if can help me about that.

**Comment by casperklein** [comment]
There is https://docker-mailserver.github.io/docker-mailserver/edge/faq/#what-about-backups. However, it's not complete.

Backup your volumes (maildata, mailstate, maillogs) and `config` directory should all you need to do.

**Comment by aendeavor** [comment]
Just Backup the (bind-)mounted volumes, i.e. these directories on your drive, in a regular backup, nothing special:)

**Comment by zzwxrchi** [comment]
https://docker-mailserver.github.io/docker-mailserver/edge/faq/#what-about-backups
Only backup config files, others folders are empty.

**Comment by zzwxrchi** [comment]
Run for me with little change the command:

docker run --rm -ti --volumes-from ${ContainerName}\
  -v "${DOCKER-COMPOSE_ROOT_DIR}/config":/tmp/docker-mailserver \
  -v ${DIR_BACKUP}:/backup \
  alpine:latest \
  tar -czf "/backup/${FILE_NAME}_${DATESTAMP}.tar.gz" /var/mail /var/mail-state /var/log/mail /tmp/docker-mailserver

**Comment by casperklein** [comment]
Check which sub directory makes it big.

**Comment by zzwxrchi** [comment]
var/mail-state/lib-clamav folder, 440MB for a new installation with 2 email added.
With files: daily.cld 322.5MB and main.cvd 117.9 MB

**Comment by casperklein** [comment]
You can exclude that directory, but then when you recreate the container, you'll not have the latest anti virus patterns. It will however update via cron job every 6 hours.

**Comment by zzwxrchi** [comment]
Thanks @casperklein !!

**Comment by Bluejanis** [comment]
The [solution in the FAQ](https://docker-mailserver.github.io/docker-mailserver/edge/faq/#what-about-backups) didnt work! It produced empty folders in the archive backup. 

Thanks @zzwxrchi for your snippet. That helped me to backup the whole mailserver successfully!

The documentation should be updated in this regard, so you can actually create complete backups with the available info. But for the most part the docker-mailserver documentation is extremely helpful!

**Comment by casperklein** [comment]
@Bluejanis / @zzwxrchi  What exactly was the problem? Could it be, that you don't use named volumes?

**Comment by zzwxrchi** [comment]
This is my docker-compose.yml

version: '3.8'

services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:edge
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    container_name: ${CONTAINER_NAME}
    env_file: mailserver.env
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)    
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - maillogs:/var/log/mail
      - /etc/localtime:/etc/localtime:ro
      - ./config/:/tmp/docker-mailserver/${SELINUX_LABEL}
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always 
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE

volumes:
  maildata:
  mailstate:
  maillogs:

**Comment by casperklein** [comment]
Thx. Did you execute the command in the directory, where your config directory is?

**Comment by zzwxrchi** [comment]
> Thx. Looks good. Did you execute the command in the directory, where your config directory is?

The modified command can execute in other directory too.

**Comment by casperklein** [comment]
Yes, but I was trying to figure out, what's wrong the documented example.

**Comment by zzwxrchi** [comment]
If execute the document example:
https://docker-mailserver.github.io/docker-mailserver/edge/faq/#what-about-backups

# create backup
docker run --rm -ti \
  -v maildata:/var/mail \
  -v mailstate:/var/mail-state \
  -v maillogs:/var/logs/mail \
  -v "$PWD/config":/tmp/docker-mailserver \
  -v /backup/mail:/backup \
  alpine:latest \
  tar czf "/backup/mail-$(date +%F).tar.gz" /var/mail /var/mail-state /var/logs/mail /tmp/docker-mailserver

# delete backups older than 30 days
find /backup/mail -type f -mtime +30 -delete

Only backup config files, others folders are empty. 
I imagine that the 3 -v mail volumens (maildata, mailstate, maillogs) is not necessary, since it is already included in the tar command tar czf ...

**Comment by casperklein** [comment]
The `tar` command runs inside a new (alpine) container, so the 3 mail volumes are necessary.

**Comment by zzwxrchi** [comment]
Then "docker run --rm -ti --volumes-from ${ContainerName}" is the key to solution, and can avoid 3 mail volumens declaración.

**Comment by casperklein** [comment]
This will be added to the documentation with #2035.
