### ISSUE TITLE
Mutiple hostnames with TLS

### ISSUE THREAD

**Issue by perry-amsterdam** [docker-mailserver/docker-mailserver#1911]
# Subject

I have questions about TLS/SSL/STARTTLS/OpenSSL

Is het possible to use multiple domain names with mail.domain1, mail.domain2, mail.domain3
Each with a letsencrypt certificate ?

This for postfix and dovecot ?

Perry

**Comment by casperklein** [comment]
I don't know if multiple certificates are possible. However a SAN certificate (with multiple domain names) should work. Just give it a try 😉

**Comment by reneploetz** [comment]
It should be possible to do this, tough you need to add your own configuration to either user-patches.sh for that or create a custom image:
- postfix: tls_server_sni_maps - http://www.postfix.org/postconf.5.html#tls_server_sni_maps
- dovecot: https://doc.dovecot.org/configuration_manual/dovecot_ssl_configuration/#with-client-tls-sni-server-name-indication-support

**Comment by yash-ahir** [comment]
> I don't know if multiple certificates are possible. However a SAN certificate (with multiple domain names) should work. Just give it a try wink

Hello, sorry to re-open this issue but I'm currently in the same position. I've issued a certificate with 

```
docker run --rm -it -v $PWD/log/:/var/log/letsencrypt/ -v $PWD/etc/:/etc/letsencrypt/ -p 80:80 certbot/certbot certonly --standalone -d mail.yashahir.tech -d mail.syntx.dev
```

This is a SAN certificate yet it does not work as you mentioned.

Hostname is `mail`, the domainname is `yashahir.tech` in `docker-compose.yml`

---

> It should be possible to do this, tough you need to add your own configuration to either user-patches.sh for that or create a custom image:
> 
>     * postfix: tls_server_sni_maps - http://www.postfix.org/postconf.5.html#tls_server_sni_maps
> 
>     * dovecot: https://doc.dovecot.org/configuration_manual/dovecot_ssl_configuration/#with-client-tls-sni-server-name-indication-support
> 
> 
> See also: https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/override-defaults/user-patches/
> 
> An alternative would be to use a proxy in front of your mailserver / dovecot which terminates TLS, e.g. traefik.

So from what I understand here (and if this is applicable, hopefully to others with the same problem),

After putting the certificate and TLD information in both the `sni` file for postfix and `conf.d/10-ssl.conf`(?) for dovecot and restarting the container stack should work correctly?

I'm not sure how https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/override-defaults/user-patches/ can be applied here, but do we need to use it ***after*** the previous step?

Apologies for the rookie question,
and thank you.

**Comment by mrkpatchaa** [comment]
I just made it work, using [this script](https://forum.howtoforge.com/threads/postfix-dovecot-sni-for-letsencrypt-certificates-via-cron-script-auto.86878/) and adapting it a little bit. I removed the system reload of services because **user patches script runs right before starting daemons**

So my user-patches.sh script looks like this
```bash
#!/bin/bash


##
# Adapted from https://forum.howtoforge.com/threads/postfix-dovecot-sni-for-letsencrypt-certificates-via-cron-script-auto.86878/
##

if [ $(grep -E "^indexed = " /etc/postfix/main.cf | wc -l) -eq 0 ]; then
       echo 'indexed = ${default_database_type}:${config_directory}/' >> /etc/postfix/main.cf
fi
if [ $(grep -E "^tls_server_sni_maps = " /etc/postfix/main.cf | wc -l) -eq 0 ]; then
       echo 'tls_server_sni_maps = ${indexed}sni' >> /etc/postfix/main.cf
fi
[[ ! -f /etc/dovecot/conf.d/99-ispconfig-custom-config.conf ]] && touch /etc/dovecot/conf.d/99-ispconfig-custom-config.conf

if [ $(grep -E "^\!include_try /etc/dovecot/sni.conf" /etc/dovecot/conf.d/99-ispconfig-custom-config.conf | wc -l) -eq 0 ] \
&& [ $(grep -E "^\!include_try /etc/dovecot/sni.conf" /etc/dovecot/dovecot.conf | wc -l) -eq 0 ]
then
       echo '!include_try /etc/dovecot/sni.conf' >> /etc/dovecot/conf.d/99-ispconfig-custom-config.conf
fi

letsencrypt="/etc/letsencrypt/live"
dovecotsni="/etc/dovecot/sni.conf"
postfixchains="/etc/postfix/sni-chains"
postfixsni="/etc/postfix/sni"
reload="false"

[ ! -d "${postfixchains}" ] && mkdir ${postfixchains}
[ ! -f "${dovecotsni}" ] && touch ${dovecotsni}
[ ! -f "${postfixsni}" ] && touch ${postfixsni}
[ -f "${dovecotsni}.new" ] && rm -f "${dovecotsni}.new"
[ -f "${postfixsni}.new" ] && rm -f "${postfixsni}.new"

echo "# Generated automatically by /root/scripts/sni-dovecot-postfix.sh" >> ${dovecotsni}.new

for domain in $(echo -e "$(find /var/www/ -maxdepth 1 -mindepth 1 -type l | awk -F"/var/www/" '{print $2}')\n$(find ${letsencrypt}/ -maxdepth 1 -mindepth 1 -type d -exec basename {} \; | sort)" | sort | uniq)
do

       # Check for LE certificate
       if [ -e ${letsencrypt}/${domain}/fullchain.pem ]; then
               cert="${letsencrypt}/${domain}/fullchain.pem"
               key="${letsencrypt}/${domain}/privkey.pem"
               generate="Letsencrypt"
       # Check for ISPCONFIG installed certificate
       elif [ -e /var/www/${domain}/ssl/${domain}.crt ]; then
               cert="/var/www/${domain}/ssl/${domain}.crt"
               key="/var/www/${domain}/ssl/${domain}.key"
               generate="Ispconfig"
       # There is no certificate anywhere for this domain
       else
               generate="false"
       fi

       if [ "${generate}" == "Letsencrypt" ] || [ "${generate}" == "Ispconfig" ]; then

               echo "Processing ${domain} SNI (detected ${generate} certificate)"

               # Dovecot SNI
               echo "local_name \"*.${domain} ${domain}\" {" >> ${dovecotsni}.new
               echo "    ssl_cert = <${cert}"  >> ${dovecotsni}.new
               echo "    ssl_key = <${key}"  >> ${dovecotsni}.new
               echo "}"  >> ${dovecotsni}.new


               # Postfix SNI Chains
               if [ -e ${postfixchains}/${domain}.pem ]; then
                       awk '{print $0}' ${key} ${cert} > ${postfixchains}/${domain}.pem.new
                       if [ $(diff ${postfixchains}/${domain}.pem.new ${postfixchains}/${domain}.pem | wc -l) -eq 0 ]; then
                               rm -f ${postfixchains}/${domain}.pem.new
                       else
                               mv ${postfixchains}/${domain}.pem.new ${postfixchains}/${domain}.pem
                               echo "(${domain} certificate has been modified)"
                               reload="true"
                       fi
               else
                       # Need to do it in two lines because ispconfig key file does not end with \r\n
                       awk '{print $0}' ${key} ${cert} > ${postfixchains}/${domain}.pem
                       reload="true"
               fi
               chmod 600 ${postfixchains}/${domain}.pem
               echo "${domain} ${postfixchains}/${domain}.pem" >> ${postfixsni}.new
               echo ".${domain} ${postfixchains}/${domain}.pem" >> ${postfixsni}.new

       fi

done


if [ $(diff ${dovecotsni}.new ${dovecotsni} | wc -l) -gt 0 ] || [ ${reload} == "true" ]; then
       echo ""
       echo "Detected changes in Dovecot SNI: executing reload"
       cat ${dovecotsni}.new > ${dovecotsni}
       # systemctl reload dovecot.service
fi

if [ $(diff ${postfixsni}.new ${postfixsni} | wc -l) -gt 0 ] || [ ${reload} == "true" ]; then
       echo ""
       echo "Detected changes in Postfix SNI: executing postmap and reload"
       cat ${postfixsni}.new > ${postfixsni}
       /usr/sbin/postmap -F /etc/postfix/sni
       # systemctl reload postfix
fi

[ -f "${dovecotsni}.new" ] && rm -f "${dovecotsni}.new"
[ -f "${postfixsni}.new" ] && rm -f "${postfixsni}.new"
```

**Comment by casperklein** [comment]
Very strange. I am still using a SAN certificate without any issues. It's using the following DNS names:

`example.com` and `*.example.com`

**Comment by mrkpatchaa** [comment]
@casperklein I think the issue is with when you have mail.example.com and mail.anothersite.com. 
In this case you will have a certificate issue.

**Comment by GAS85** [comment]
> I just made it work, using [this script](https://forum.howtoforge.com/threads/postfix-dovecot-sni-for-letsencrypt-certificates-via-cron-script-auto.86878/) and adapting it a little bit. I removed the system reload of services because **user patches script runs right before starting daemons**

Very nice solution! Just to add that you can test it with different domains:

```shell
docker exec mailserver openssl s_client -connect 0.0.0.0:25 \
-starttls smtp \
-CApath /etc/ssl/certs/ \
-servername <DOMAIN>
```
