### ISSUE TITLE
[FR] Link to wsproxy pointing to an archived unsupported version of it

### ISSUE THREAD

**Issue by vinicius03** [docker-mailserver/docker-mailserver#1923]
# Feature Request

The wsproxy link is pointing to https://github.com/docker-scripts/wsproxy at documentation page https://docker-mailserver.github.io/docker-mailserver/edge/examples/tutorials/basic-installation/ 

Please update to https://gitlab.com/docker-scripts/wsproxy

It might induct to errors (I felt at this trap). Thanks!

**Comment by casperklein** [comment]
Thanks!
