### ISSUE TITLE
strange situation on windows10 mail client

### ISSUE THREAD

**Issue by vaskovasilev** [docker-mailserver/docker-mailserver#1926]
Hello dear all,

yesterday i have installed the mailserver, configured one email account and setup dkim.
I have added the account to windows mail client , logged in successfull and had to accept the certificate that was not correct. 
Then tried to send one email and the emails stay in Outbox. I dont see some logs in /var/log/mail related with these new mails.
On smartphone - all is fine with sending and i see logs. 
Incoming emails - are not working. I dont receive an email to this new account. 
Is there any way to understand why this is happening?

some part of the log

```Apr 21 04:16:58 domain postfix/smtps/smtpd[104539]: warning: hostname zg-0416b-26.stretchoid.com does not resolve to address 192.*.*.*: No address associated with hostname
Apr 21 05:58:33 domain postfix/smtps/smtpd[131095]: warning: TLS library problem: error:14209102:SSL routines:tls_early_post_process_client_hello:unsupported protocol:../ssl/statem/statem_srvr.c:1661:
Apr 21 05:58:34 domain postfix/smtps/smtpd[131149]: warning: TLS library problem: error:142090C1:SSL routines:tls_early_post_process_client_hello:no shared cipher:../ssl/statem/statem_srvr.c:1756:
Apr 21 05:58:34 domain postfix/smtps/smtpd[131095]: warning: TLS library problem: error:141CF06C:SSL routines:tls_parse_ctos_key_share:bad key share:../ssl/statem/extensions_srvr.c:693:
Apr 21 07:45:28 domain postfix/smtps/smtpd[159300]: warning: TLS library problem: error:1408F09C:SSL routines:ssl3_get_record:http request:../ssl/record/ssl3_record.c:322:
Apr 21 08:27:02 domain postfix/submission/smtpd[170196]: warning: hostname zg-0416a-280.stretchoid.com does not resolve to address 192.*.*.*: No address associated with hostname
Apr 21 11:17:17 domain dovecot: master: Warning: Killed with signal 15 (by pid=8 uid=0 code=kill)
Apr 21 12:18:08 domain postfix/trivial-rewrite[14800]: warning: do not list domain domain.info in BOTH mydestination and virtual_mailbox_domains
Apr 21 12:18:08 domain postfix/trivial-rewrite[14800]: warning: do not list domain domain.info in BOTH mydestination and virtual_mailbox_domains```

thanks !

**Comment by reneploetz** [comment]
You likely have configured the container hostname to be identical to your mail domains. See this FAQ entry: https://docker-mailserver.github.io/docker-mailserver/edge/faq/#can-i-use-nakedbare-domains-no-host-name

**Comment by vaskovasilev** [comment]
thanks for the reply. 

`mydestination = localhost.$mydomain, localhost
local_recipient_maps = # also added (saw in some post)`

yesterday i have moved the dns entries to this new server. now i cannot send from some external (not on this server) email.

`User unknown in local recipient table;`

I have tried from the email to send to itself - same , mails are in outbox and i dont see some logs when i click send.

DNS entries:


mail.domain.com | 86400 | CNAME | 0 | domain.com
domain.com | 86400 | MX | 10 | domain.com

same as before from the shared hosting.

**Comment by reneploetz** [comment]
---
As a sidenote:
That's an unusual DNS configuration as you have configured your MX on a bare-bones domain and a CNAME on the mail-like "mail.domain.com". Usually, you want the MX on "mail.domain.com" and an A record for both "domain.com" and "mail.domain.com" (CNAMEs do not play well with MX). Your DNS configuration is probably be fine tough, the CNAME-"mail.domain.com" will just not used at all. You have - together with HOSTNAME / DOMAINNAME - configured a bare domain mail server. 
Note that DNS changes can take a while to propagate - your have configured 1 day of lifetime for them on your domain.
---

Why did you configure "local_recipient_maps = (empty)" ?
Setting this to empty will result in postfix not discarding mails to unknown (local) recipients but instead send notification to the (potentially forged) sender address. Doing this is a really bad idea as you basically create an open backscatter relay server, e.g. if someone sending a mail to "does-not-exist@domain.com" with sender "foo@bar.com", then "foo@bar.com" will receive a notification with the mail content. This will also get your server on a backscatter blocklist. 

---

That your phone is moving mails to the sent folder might not indicate that you are successfully sending emails, as this is a client operation. Can you check that outgoing mails are in fact received by the recipient?
Also, it would be helpful to post your docker configuration and/or the messages you get when sending mails.

**Comment by vaskovasilev** [comment]
Ok, all is fine :)
Seems the dns was not refreshed and have to wait a little bit.

local_recipient_maps - i have found in some article on github . Removed now.

Thanks !
