### ISSUE TITLE
550 5.7.1 Service unavailable; client [xxx.xxx.xxx.xxx] blocked using zen.spamhaus.org

### ISSUE THREAD

**Issue by ghnp5** [docker-mailserver/docker-mailserver#1927]
Today I got an absolutely ridiculous problem, after noticing that I've not been receiving emails at all, since the morning...

I decided to do a test, by sending an email to my mailbox, from an external address, and here is the result:

> 550 5.7.1 Service unavailable; client [xxx.xxx.xxx.xxx] blocked using zen.spamhaus.org

After investigating, I see the problem is similar to #1781

And gladly, someone's comment drove me to the solution, which is to overwrite the following configs in "postfix-main.cf":

`postscreen_dnsbl_sites`
`smtpd_recipient_restrictions`

Removing the offender instructions for `zen.spamhaus.org`.

Now, I have a few questions:

1) What does it mean that emails are "blocked using zen.spamhaus.org" ?
Does this mean my domain/IP was blocked somehow?
Is this something that only affects me, or nothing to do with "me" ("my domain") ?

2) Why are these "sites" in my configurations? Who decides to put these sites as default?

I'm just **very concerned** with the fact that these 3rd party sites, that I never heard about before, can so easily "break" the receiving of emails on my server...

3) Is there a way to recover all the emails that were lost during the day?

This is just absolutely ridiculous...

I'm not blaming you at all. I understand you don't control "zen.spamhaus.org".
But I definitely want to prevent this from happening in the future.

I'm on the latest 7.x version.

Thank you.

**Comment by casperklein** [comment]
> What does it mean that emails are "blocked using zen.spamhaus.org" ?  Does this mean my domain/IP was blocked somehow?

The sending system is on a block list.

> Why are these "sites" in my configurations? Who decides to put these sites as default?

They were added by this project in the past and are not part of the postfix default configuration.

> I'm just very concerned with the fact that these 3rd party sites, that I never heard about before, can so easily "break" the receiving of emails on my server...

I have the same opinion. I don't like the fact, that mails are silently blocked/discard. I want to receive all mails, but marked as spam. Thats why I also disabled all DNS block lists and use Spamassassin only.

fyi: The same goes for Antivirus (clamav). If an email is considered harmful (e.g. containing "dangerous" attachments), it will be discarded.

**Comment by ghnp5** [comment]
Thank you very much.

> The sending system is on a block list.

What sending system exactly? I was receiving absolutely no emails from anyone. My own internal servers, Yahoo, Gmail, Hotmail, AWS... everything was being rejected.

> Probably not.

I did receive a few emails from those ISP who keep trying to resend for some time, but I also lost a good amount of them, unfortunately :(
I received some Gmail emails, and some internal emails,
but seems all emails from Yahoo and AWS were lost... (who knows what else...)

Looking at the mail.log rejections, it seems ~235 emails were rejected during this period. I only received a few from that period, after the issue was resolved.

> The same goes for Antivirus (clamav)

I have `ENABLE_CLAMAV=0`
So I think I'm good there?

> Thats why I also disabled all DNS block lists and use Spamassassin only.

Thank you. That's very good advice - really appreciate.

Would you please let me know what do you do to disable all DNS blocks, please?
Just want to make sure I do the right thing, and don't be experiment and risk "messing up / losing even more emails"...

Thank you very much again!

**Comment by casperklein** [comment]
> Would you let me know what do you do to disable all DNS blocks, please? Just want to make sure I do the right thing,

Sure, but without guarantee for completeness. That's what I found out so far.

These are my "deliver all mails" hacks:

`config/postfix-main.cf`:

```
postscreen_dnsbl_sites =

# DNS blacklists removed
smtpd_recipient_restrictions = permit_sasl_authenticated, permit_mynetworks, reject_unauth_destination, check_policy_service unix:private/policyd-spf, reject_unauth_pipelining, reject_invalid_helo_hostname, reject_non_fqdn_helo_hostname, reject_unknown_recipient_domain
```

`config/user-patches.sh`:

```
sed -i '/^\$final_virus_destiny/ s|D_DISCARD|D_PASS|' /etc/amavis/conf.d/20-debian_defaults
sed -i '/^\$final_banned_destiny/ s|D_DISCARD|D_PASS|' /etc/amavis/conf.d/20-debian_defaults

# verify with:
# grep -P final_.+_destiny /etc/amavis/conf.d/*
#    /etc/amavis/conf.d/20-debian_defaults:$final_virus_destiny      = D_PASS;  # (data not lost, see virus quarantine)
#    /etc/amavis/conf.d/20-debian_defaults:$final_banned_destiny     = D_PASS;
#    /etc/amavis/conf.d/20-debian_defaults:$final_spam_destiny       = D_PASS;
#    /etc/amavis/conf.d/20-debian_defaults:$final_bad_header_destiny = D_PASS;     # False-positive prone (for spam)

```

**Comment by ghnp5** [comment]
Thank you VERY much for this!
That's great. I'm copying your changes.

I see that for `smtpd_recipient_restrictions`, you don't have this:

`check_policy_service inet:localhost:65265`  (which I have in my container)

But you kept this:

`check_policy_service unix:private/policyd-spf`

What is on `localhost:65265` anyway, do you know?

Have a very great day.

**Comment by casperklein** [comment]
I just removed the DNS blacklists from the original string some time ago. `check_policy_service inet:localhost:65265` must have been added later. However I checked my setup and there is no service listening on port 65265.

It's seems to be related to postfix quotas:

https://github.com/docker-mailserver/docker-mailserver/blob/69402b0bfade5366bd0bd81cdc710e191110efa0/target/scripts/startup/setup-stack.sh#L290-L291

PS: You might also the check the env variable `POSTSCREEN_ACTION` and set it to `ignore`.

**Comment by ghnp5** [comment]
Very good! Thank you for that.

I also don't use quotas, so I went ahead and put `ENABLE_QUOTAS=0` in the env file.

Really appreciate your help here. Yeah, since the "main.cf" configs may change, it's probably better to use patches instead.
I'll look into that too.


As this issue is now resolved, I'll go ahead and close this ticket, just so it doesn't remain unnecessarily open!

Have a great day!

**Comment by 17Halbe** [comment]
The easiest solution would be to add a dns server which supports ECS. Spamhaus changed their policy in 2020 of accepting any query towards denying queries send via open resolvers due to misuse of their service. If you still identify yourself with your own IP they are still happy to serve you. And you'll keep their pretty good filter working.

If you are using docker-compose just add the line    
```
dns:
  - 9.9.9.11 #QUAD9 DNS Server with ECS enabled see: https://www.quad9.net/service/service-addresses-and-features/#ecssec
```
(Quad9 is a not-for-profit organization, relying on grants and partnerships with commercial and non-commercial sources and from individuals.)

I could provide a pull request if desired.

**Comment by ghnp5** [comment]
Thanks, but I'm no longer using it at all. I don't want to use something that can easily break my server whenever they want.

**Comment by 17Halbe** [comment]
True, and rightfully so. It's debatable if one should rely on 3rd party ressources and especially services. 
Anyways, now that you mention it; the mail delivery shouldn't fail anyway. I just realized, that we should consider valid responses anyways. I would say this is the real bug:
So instead of 
`postscreen_dnsbl_sites = zen.spamhaus.org*3` we should use
`postscreen_dnsbl_sites = zen.spamhaus.org=127.0.0.[2..11]*3`

**Comment by casperklein** [comment]
With v11 we wanted to remove dns blocking completely and making it opt-in.

**Comment by casperklein** [comment]
@georglauterbach Why did you unpin this issue? It might help people having similar issues like https://github.com/docker-mailserver/docker-mailserver/issues/2288

**Comment by georglauterbach** [comment]
I saw two closed issues still pinned. I thought they could safely be removed.

I will pin this back up.

**Comment by casperklein** [comment]
Until fixed (in v11 in that case), we should let the issues pinned, even when closed, to avoid further issues opened.

**Comment by yoyecros** [comment]
Hi,

Same issue with latest image, using dns param (https://github.com/docker-mailserver/docker-mailserver/issues/1927#issuecomment-955713448) resolves the issue for zen.spamhaus.org but another domain is also blocked.
I have set ENABLE_QUOTAS=0 and POSTSCREEN_ACTION=ignore.
If I update config/postfix-main.cf or other config file, it will be overwrited with new releases

Is there any config to disable DNS blocks ?

Thanks!

**Comment by georglauterbach** [comment]
> Hi,
> 
> 
> 
> Same issue with latest image, using dns param (https://github.com/docker-mailserver/docker-mailserver/issues/1927#issuecomment-955713448) resolves the issue for zen.spamhaus.org but another domain is also blocked.
> 
> I have set ENABLE_QUOTAS=0 and POSTSCREEN_ACTION=ignore.
> 
> If I update config/postfix-main.cf or other config file, it will be overwrited with new releases
> 
> 
> 
> Is there any config to disable DNS blocks ?
> 
> 
> 
> Thanks!

https://github.com/docker-mailserver/docker-mailserver/issues/1927#issuecomment-824940913

Did you even bother reading this thread?

**Comment by yoyecros** [comment]
Sorry, because config/postfix-main.cf didn't exists, I though that this file has to be inside the container, but create it in my config folder worked... So I can confirm that the solution is working 😅
Thanks and sorry for my mistake!

**Comment by vaskozl** [comment]
I've also been loosing mails due this. Honestly it's crazy to me that spamhaus choosing to block public resolvers leads to basically all emails being rejected. 

While this has traditionally been quite a popular postfix configuration, it's absolutely silly, an rbl failure like this should at the very least deliver to spam.

I vote in favour of getting rid of DNSBL as soon as possible.

**Comment by georglauterbach** [comment]
@casperklein one questions: why is removing the DNSBLs like Spamhaus scheduled for `v11`? It's not a breaking change AFAIK.

**Comment by casperklein** [comment]
It's how you define a breaking change. Someone relying on DNSBLs, will have to act after removal from our default config, to keep the functionality.

**Comment by georglauterbach** [comment]
I would define a breaking change to be one after which one would (possibly) not be able to use the mail server anymore without taking action. This is not the case here, right? I'm just curious because I have nothing against this going into `v10.4`.
