### ISSUE TITLE
docker-mailserver without changing the server hostname to mail?

### ISSUE THREAD

**Issue by Itzdlg** [docker-mailserver/docker-mailserver#1930]
**I would like some feedback concerning a use case**

I understand that this specific "application" has something called a hostname-override. I am quite confused by the comments left. How can I setup docker-mailserver to not require a change in hostname, or if that's even possible? Please let me know exactly what needs to be done.

**Comment by reneploetz** [comment]
I'm somewhat unsure what you want to achieve here, so this is more of a general answer.

You can technically define any hostname you like for your docker container. 

If you are using docker-compose you are able to use the configuration like so:
```
services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    hostname: bar
    domainname: foo.com
```
There is no specific requirement to use ```mail``` as the hostname, but the FQDN hostname ``hostname -f``` (inside your container) must be present in A/MX records for that domain, e.g. "bar.foo.com" in this example. The reason for that is that incoming connections to your server and the server configuration have to match, so when clients connect to "bar.foo.com", they have to be presented a mail server banner for "bar.foo.com".

---

When booting up, the container will use the Linux ```hostname -d``` command to fetch the hostname. Some container deployments (kubernetes, ..) do not allow you to easily configure the hostname. Therefore, you need to use ```OVERRIDE_HOSTNAME```. In this case, you must include the domain name in the hostname variable, e.g. "bar.foo.com" as the example above. The container will extract the domain name from this variable (taking everything after the first dot) and using the full variable as the hostname.
