### ISSUE TITLE
[FR] [Security] Implement Docker Content Trust, sign Docker images

### ISSUE THREAD

**Issue by williamdes** [docker-mailserver/docker-mailserver#1939]
# Feature Request

## Context

```
docker pull docker.io/mailserver/docker-mailserver:latest --disable-content-trust=false
```

```
Error: remote trust data does not exist for docker.io/mailserver/docker-mailserver: notary.docker.io does not have trust data for docker.io/mailserver/docker-mailserver
```

### Describe the Solution you'd like

Sign the images

(Did not test on GitHub Content Registry, Docker hub supports the notary)

### Are you going to implement it?

No, I am not the one that will own the secrets

### What are you going to contribute??

Nope, but I can help and here is my GitHub action to do the work: https://github.com/sudo-bot/action-docker-sign#readme

## Additional context

https://github.com/sudo-bot/action-docker-sign#inspect-trust

Same issue as for https://github.com/dani-garcia/vaultwarden/issues/1651

I can provide help for the setup if needed

### Who will that Feature be useful to?

All users, we need security for our emails

### What have you done already?

Build a GitHub action and document it

See: https://github.com/sudo-bot/action-docker-sign

All the needed commands can be copied from https://github.com/sudo-bot/action-docker-sign/blob/main/action.yml

Is it easy to implement: Yes
Do you have to backup in a very safe place the repository and root keys, YES !!

**Comment by williamdes** [comment]
I am trying to make the signing work when using multi platform builds (with build for example)
Docker cli has upstream issues open since ages, will try to make the signing work

**Comment by williamdes** [comment]
Nope

**Comment by casperklein** [comment]
Maybe close the issues/PRs and just reopen them when you are ready? 😉

**Comment by williamdes** [comment]
> Maybe close the issues/PRs and just reopen them when you are ready? wink

Hmm, seems like an idea 🤔. Kind of dislike it but it's not worth my morning notifications review to fight with a stale bot ^^
