### ISSUE TITLE
[FR] Include env variable or file containing the image version

### ISSUE THREAD

**Issue by casperklein** [docker-mailserver/docker-mailserver#1946]
# Feature Request

## Context

We should introduce an env variable or file that includes the image version. I see two main benefits from that:

- We could include the version information in the startup script, which makes it easier to identify the used version (e.g. when helping with issues).
- It should be easy to implement a cron based update check to see, if there is a new release available.

"Disadvantage":

- Each time we release a new version, this env variable/file must be updated.

### Describe the Solution you'd like

Env variable or file containing the image version. I prefer the file solution. **What are your thoughts?**

### Are you going to implement it?

Yes, because I know the probability of someone else doing it is low and I can learn from it.

### What are you going to contribute??

The necessary adjustments.

**Comment by aendeavor** [comment]
I like this idea. As long as the implementation has a small footprint, I'm fine with it. Could we automate the process of adding this environment variable when releasing in CI?

And we already do something similar in the make file:

``` MAKEFILE
VCS_REF = $(shell git rev-parse --short HEAD)
VCS_VER = $(shell git describe --tags --contains --always)
```

**Comment by casperklein** [comment]
Something like this in the `Dockerfile` should work:

ENV VERSION=${VCS_VER}

However, there are cases, where this variable doesn't contain the version, but instead something like `refs/heads/master`.

For a semantic version check I have in mind, that would't work:

1. `LATEST_VERSION=$(wget https://raw.githubusercontent.com/docker-mailserver/docker-mailserver/master/VERSION)`
2. `MY_VERSION=$(cat /VERSION)`
3. `if $MY_VERSION < $LATEST_VERSION; then send update notification mail to $POSTMASTER_ADDRESS`

**Comment by aendeavor** [comment]
We should somehow enable users to turn this update notification off - I'm just saying this now so we can keep this in mind.

I like the idea, and the method you proposed seems sufficient to me.

**Comment by casperklein** [comment]
Yes, I've already considered this. I will implement something like $ENABLE_UPDATE_CHECK and maybe $UPDATE_CHECK_INTERVAL

**Comment by lorena1976** [comment]
> Yes, I've already considered this. I will implement something like `$ENABLE_UPDATE_CHECK` and maybe `$UPDATE_CHECK_INTERVAL`

**Comment by polarathene** [comment]
> However, there are cases, where this variable doesn't contain the version, but instead something like `refs/heads/master`.

What cases are those? If it's used with official releases, we should have the version baked into an ENV during the automated image build process? Thus it should be stable to rely on (at least for tagged version releases where it matters), and can just query Github for latest release tag? (potentially not reliable if we have alternative tags like beta/rc versions that could accidentally be picked up)

**Comment by casperklein** [comment]
>  (potentially not reliable if we have alternative tags like beta/rc versions that could accidentally be picked up)

Yes. I referred to this tag in my example: `mailserver/docker-mailserver:edge`

I don't like [features](https://github.com/docker-mailserver/docker-mailserver/pull/1951), that would only work with some image tags, but always fail with other like `:edge`.

For now it seems, that I am the only one that likes the simple and flat VERSION file approach that would always work. :confused:

I am happy to change my [PR](https://github.com/docker-mailserver/docker-mailserver/pull/1951), if some comes up with a reliable env variable solution providing the current version in semver format.

**Comment by polarathene** [comment]
> Yes. I referred to this tag in my example: `mailserver/docker-mailserver:edge`
> I don't like features, that would only work with some image tags, but always fail with other like `:edge`.

Is `edge` intended to use and benefit from this feature as well? I don't think `edge` would be getting a release tag so I don't see that  appearing as a result from the curl query?

---

> For now it seems, that I am the only one that likes the simple and flat VERSION file approach that would always work.

I don't mind it personally. I just don't see a reason or need for a file when the version can be built-in to the image as ENV and queried via curl.

If we have a new version and an rc/beta suffix was added and a release published that would actually be returned via the curl query, those can be filtered out or detected.

Your file approach I assume would not update the version accordingly to avoid triggering an update? It must be documented that the file included in git does not necessarily match it's actual version then? (as builds are potentially overriding it with a different version)

---

Personally I'm all for providing data for a container to know internally what version it is running. But monitoring for updates and notifying a user to get a new container isn't the responsibility of this project, there are specific generic solutions for catering to that need and our documentation can advise about that if necessary for those that want it.

**Comment by polarathene** [comment]
@fbartels responding to your comment on the [related PR](https://github.com/docker-mailserver/docker-mailserver/pull/1951#issuecomment-835829418):

> the comparison should instead be done either against the tags available on Docker Hub, or a git tag.

I looked at DockerHub and Github/GHCR API for querying the tags/versions, both of these seem to require auth headers. So querying Github like the curl example provided earlier seems to be the only viable option for that approach. Unless we do whatever tools like Watchtower already do to check (assuming that's different).

**Comment by fbartels** [comment]
Get Docker tags without auth: `curl -L -s 'https://registry.hub.docker.com/v2/repositories/mailserver/docker-mailserver/tags?page_size=1024'\|jq '."results"[]["name"]' | jq .`

Get Git tags without auth: `git ls-remote --refs --tags https://github.com/docker-mailserver/docker-mailserver`

**Comment by polarathene** [comment]
> Get Docker tags without auth

Ah that's cool, thanks for sharing that :)

When I tried it, I didn't receive any tags, just pretty json response, I get a list of tags this way though:

```bash
$ curl -L -s 'https://registry.hub.docker.com/v2/repositories/mailserver/docker-mailserver/tags?page_size=1024' | jq -r ".results[].name"

latest
stable
edge
9.1.0
9.1
9
9.0.1
9.0
9.0.0
8.0.1
8.0
8
8.0.0
```

Probably needs more logic to sort that out for latest tag that is semver.

---

> Get Git tags without auth

That isn't an issue, I was referring to GHCR (technically referred to as "container" type in Github Packages product). That API appears to require authorization.

To query the latest tag released via Github (not tagged via git):

```bash
curl -sL https://api.github.com/repos/docker-mailserver/docker-mailserver/releases/latest | jq -r ".tag_name"
```
