### ISSUE TITLE
Does a letsencrypt wildcard cert work with docker-mailserver?

### ISSUE THREAD

**Issue by Dubbeldrank** [docker-mailserver/docker-mailserver#1950]
There are some issue in the backlog about letsencrypt wildcard certs but that's mainly old and not really conclusive. So my question is wil this work out of the box when i generate a wildcard certificate? Currently it's all working fine, but i want to simplify. So i'm asking first before i mess up my current setup.

**Comment by casperklein** [comment]
No problem here, using a LE wildcard certificate (since two years).

**Comment by Dubbeldrank** [comment]
> 
> 
> No problem here, using a LE wildcard certificate (since two years).

Does it work out of the box, or is there some work on it?

**Comment by Dubbeldrank** [comment]
> 
> 
> Hey 👋🏻
> 
> did you look at #1338 #1341 or #1915 (20 days old) already if they solve your problem?

I did, that's why i made this post. The most recent one is in combination with Traefik which i don't use, the other ones are old as i mentioned.

**Comment by casperklein** [comment]
> Does it work out of the box, or is there some work on it?

Out of the box, using `$SSL_TYPE=manual` 👍

**Comment by wernerfred** [comment]
Thanks @casperklein for your answer. I will close this then. @Dubbeldrank please keep the [contributing guides](https://github.com/docker-mailserver/docker-mailserver/blob/master/CONTRIBUTING.md#opening-an-issue) in mind before opening an issue that strictly speaking isn't one.
We are always happy to help if there is a problem (technically or in understanding) but Issues that ask about eventualities (especially bc many hits are found looking for wildcard certs) without a real problem are a waste of time for us maintainers doing this in their spare time.

@aendeavor maybe we should think of enabling the discussions feature for such cases.

Other than that, feel free to reach back to us or this Issue in particular if you encounter any errors during your wildcard enablement. Good Luck 🤞🏻
