### ISSUE TITLE
[FR] Reduce unnecessary disk IO

### ISSUE THREAD

**Issue by nukedupe** [docker-mailserver/docker-mailserver#1958]
# Feature Request

## Context
```check-for-changes.sh``` script is constantly (every second) hashing and writing unnecessary to host filesystem.

### Is your Feature Request related to a Problem?
Reduce unnecessary disk IO.

### Describe the Solution you'd like
Wait and hash only if change was detected.

### Are you going to implement it?
I have just a quick hack but it depends on package ```inotify-tools```.
I have added in ```check-for-changes.sh``` before line 46:
```
  inotifywait -r \
          /tmp/docker-mailserver \
          /etc/letsencrypt/acme.json \
          "/etc/letsencrypt/live"
```

But this snippet is not heavily. Have just add it to my container.

**Comment by aendeavor** [comment]
A good idea, I think the one-second hash and write may not benecessary. The package you added, is it lightweight? How fast can the new version of the script adjust for changes?

**Comment by nukedupe** [comment]
Package is < 100kb. In terms of speed, it should be the same or maybe even faster.

**Comment by aendeavor** [comment]
> Package is < 100kb. In terms of speed, it should be the same or maybe even faster.

Alright. I will open a PR and link to this issue. We can then discuss changes to the topic in this issue and changes to the PR in the PR itself.

**Comment by aendeavor** [comment]
Reach back here when a PR is ready. I will close this in the meantime, and re-open when the PR is ready.
