### ISSUE TITLE
[BUG] DKIM error on kubernetes node

### ISSUE THREAD

**Issue by mamiapatrick** [docker-mailserver/docker-mailserver#1977]
# Bug Report

## Context

I install mailserver on kubernetes cluster and use LDAP as the authentication system but when i try to use the setup.sh to generate the DKIM i got an error and even if i log in, i cannot sent any email.

### What is affected by this bug?

I cannot generate DKIM with setup.sh on the node (kubernetes node)
I cannot sent any mail with a manual DKIM (generated by my own on a dkim generator)

### When does this occur?

When i try to create DKIM with setup.sh
When i try to sent email

### How do we replicate the issue?

1. ./setup.sh config dkim domain example.com (failed)
2. generate DKIM manually with online DKIM generator
3. mount /tmp/docker-mailserver/opendkim/keys/mail.example.com.com-mail.key 
4.

### Actual Behavior

For the DKIM

`````
––– UNCHECKED ERROR
  – script    = setup.sh
  – function  = _update_config_path / grep "/tmp/docker-mailserver$" 2> /dev/null
  – line      = 76
  – exit code = 1

Make sure you use a version of this script that matches
the version / tag of docker-mailserver. Please read the
'Get the tools' section in the README on GitHub careful-
ly and use ./setup.sh help and read the VERSION section.

––– UNCHECKED ERROR
  – script    = setup.sh
  – function  = _update_config_path / VOLUME=$(${CRI} inspect "${CONTAINER_NAME}"       --format="{{range .Mounts}}{{ println .Source .Destination}}{{end}}" |       grep "/tmp/docker-mailserver$" 2>/dev/null)
  – line      = 76
  – exit code = 1

Make sure you use a version of this script that matches
the version / tag of docker-mailserver. Please read the
'Get the tools' section in the README on GitHub careful-
ly and use ./setup.sh help and read the VERSION section.
`````

For the mail to send

```
mailserver-5f4494fb94-tjgtr postfix/cleanup[6896]: 83A1772CAB6: message-id=<20210325032217.83A1772CAB6@example.com>
 mailserver-5f4494fb94-tjgtr opendkim[196]: 83A1772CAB6: SSL error:0D06B08E:asn1 encoding routines:asn1_d2i_read_bio:not enough data
 mailserver-5f4494fb94-tjgtr opendkim[196]: 83A1772CAB6: dkim_eom(): resource unavailable: d2i_PrivateKey_bio() failed
```

### Expected Behavior

DKIM key is generated with setup.sh
Mail can be sent

## Your Environment

- version: `v9.1.0`
- available RAM: `12GB`
- Docker version (on node): `v19.03.7`
- Kubernetes version: `v1.18.3`

### Environment Variables

```CFG

  DMS_DEBUG: "0"
  DOMAINNAME: mail.example.com
  DOVECOT_AUTH_BIND: "yes"
  DOVECOT_PASS_ATTRS: mail=user,userPassword=password
  DOVECOT_PASS_FILTER: (&(objectClass=gosaMailAccount)(mail=%u))
  DOVECOT_USER_ATTRS: =home=/var/mail,=uid=5000,=gid=5000
  DOVECOT_USER_FILTER: (&(objectClass=gosaMailAccount)(mail=%u))
  ENABLE_CLAMAV: "1"
  ENABLE_FAIL2BAN: "1"
  ENABLE_LDAP: "1"
  ENABLE_POSTGREY: "1"
  ENABLE_SASLAUTHD: "0"
  ENABLE_SPAMASSASSIN: "1"
  HOSTNAME: mail
  LDAP_BIND_DN: cn=admin,dc=mail,dc=example,dc=com
  LDAP_BIND_PW: xxxxxxxxx
  LDAP_QUERY_FILTER_ALIAS: (&(objectClass=gosaMailAccount)(mail=%u))
  LDAP_QUERY_FILTER_DOMAIN: (|(mail=*@%s)(mailalias=*@%s)(mailGroupMember=*@%s))
  LDAP_QUERY_FILTER_GROUP: (&(|(memberof=group1,ou=groups,dc=mail,dc=example,dc=com))
  LDAP_QUERY_FILTER_USER: (&(objectClass=gosaMailAccount)(mail=%u))
  LDAP_SEARCH_BASE: dc=sie,dc=gov,dc=cm
  LDAP_SERVER_HOST: oldap.default
  ONE_DIR: "1"
  OVERRIDE_HOSTNAME: mail.mail.example.com
  PERMIT_DOCKER: connected-networks
  POSTFIX_MESSAGE_SIZE_LIMIT: "100000000"
  POSTMASTER_ADDRESS: postmaster@mail.example.com
  SASLAUTHD_LDAP_BIND_DN: cn=admin,dc=sie,dc=gov,dc=cm
  SASLAUTHD_LDAP_FILTER: (&(objectClass=gosaMailAccount)(mail=%u))
  SASLAUTHD_LDAP_PASSWORD: xxxxxxxx
  SASLAUTHD_LDAP_SEARCH_BASE: dc=mail,dc=example,dc=com
  SASLAUTHD_LDAP_SERVER: oldap.default
  SASLAUTHD_MECHANISMS: ldap
  SPAMASSASSIN_SPAM_TO_INBOX: "1"

```

### Relevant Stack Traces

```BASH
# BEGIN
`––– UNCHECKED ERROR
  – script    = setup.sh
  – function  = _update_config_path / grep "/tmp/docker-mailserver$" 2> /dev/null
  – line      = 76
  – exit code = 1

Make sure you use a version of this script that matches
the version / tag of docker-mailserver. Please read the
'Get the tools' section in the README on GitHub careful-
ly and use ./setup.sh help and read the VERSION section.

––– UNCHECKED ERROR
  – script    = setup.sh
  – function  = _update_config_path / VOLUME=$(${CRI} inspect "${CONTAINER_NAME}"       --format="{{range .Mounts}}{{ println .Source .Destination}}{{end}}" |       grep "/tmp/docker-mailserver$" 2>/dev/null)
  – line      = 76
  – exit code = 1

Make sure you use a version of this script that matches
the version / tag of docker-mailserver. Please read the
'Get the tools' section in the README on GitHub careful-
ly and use ./setup.sh help and read the VERSION section.`
# END
```

**Comment by aendeavor** [comment]
Seems like `setup.sh` cannot find the configuration volume path (obviously, as volumes work differently in Kubernetes).

Please note that we do not officially support Kubernetes. But maybe @radicand can help here.

@mamiapatrick note that @radicand msy be slow to respond as he's a retired maintainer. He may not respond at all, since he's very low on time.

**Comment by mamiapatrick** [comment]
@aendeavor Thanks, me too i believed that this could be an issue because how symfony rename pods and volume. Do you think there is another way to generate a valid DKIM without setup.sh.
Hoping that @radicand may have better solutions later

**Comment by aendeavor** [comment]
> @aendeavor Thanks, me too i believed that this could be an issue because how symfony rename pods and volume. Do you think there is another way to generate a valid DKIM without setup.sh.
> 
> Hoping that @radicand may have better solutions later

Setup just wraps a script located in the container, which is in PATH. You could try to execute the script (which is called `opendkim`) directly from within the container to create the keys.

**Comment by radicand** [comment]
What @aendeavor notes is how I accomplish this in kubernetes - I look for what the script does and then execute them manually in container /edit my configmap accordingly

**Comment by mamiapatrick** [comment]
Hello @radicand,
setup.sh script as many functions and parameters. could you please share with me the list of command to execute to generate DKIM key directly into the container?

**Comment by aendeavor** [comment]
> Hello @radicand,
> 
> setup.sh script as many functions and parameters. could you please share with me the list of command to execute to generate DKIM key directly into the container? 

Exec into the container and run `open-dkim -h` or `open-dkim help`, viòla.
