### ISSUE TITLE
[FR] Remove private IPs from email header

### ISSUE THREAD

**Issue by jbaumg93** [docker-mailserver/docker-mailserver#1981]
# Feature Request

Private IPs are not fully removed from the mail header. The commit https://github.com/docker-mailserver/docker-mailserver/commit/4cb8f4d4ae8bd80a65ad2e1d01c12e63f138bc7e helps for mail clients but does not remove the header from container to container emails (see below).

I am aware that this is a minor problem. **I would like to hear your opinion on this before I create a PR.**

## Context

When using the container to send emails for another container, the following "Received" header will be added:

```
Received: from edc10e7db01f (app_1.app_mail [172.17.5.3])
	by mail.someproject.com (Postfix) with ESMTPA id XXXXXXXXXX
	for <test@example.com>; Tue, 18 May 2021 09:00:00 +0000 (UTC)
```

It contains the Container ID, application name, container name and private IP address.

### Describe the Solution you'd like

Replace the line `/^\s*Received: from.*127.0.0.1/     IGNORE` of target/postfix/sender_header_filter.pcre with the following:

```
/^\s*Received: from.*\b(127\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)|0?10\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)|172\.0?1[6-9]\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)|172\.0?2[0-9]\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)|172\.0?3[0-2]\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)|192\.168\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)|169\.254\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)|::1|[fF][cCdD][0-9a-fA-F]{2}(?:[:][0-9a-fA-F]{0,4}){0,7}|[fF][eE][89aAbB][0-9a-fA-F](?:[:][0-9a-fA-F]{0,4}){0,7})(?:\/([789]|1?[0-9]{2}))?\b/    IGNORE
```

Regex source: https://stackoverflow.com/a/62925185

The regex matches all complete private IPv4 addresses, localhost and IPv6 addresses start with "FE".

### Are you going to implement it?

Yes, because I know the probability of someone else doing it is low and I can learn from it.

### What are you going to contribute??

Creating a PR with the line above.

### Alternatives you've considered

Reconfiguring Postfix after the container has started. It will work but it is not pretty.

### Who will that Feature be useful to?

In situations when another container uses this container. Probably other server to server communication on a private network.

### What have you done already?

Provide the line above.

**Comment by casperklein** [comment]
Your fix includes a quite heavy regex. Is it possible to split this up like:

```bash
# 127.0.0.0/8
/^\s*Received: from.*....
# 192.168.0.0/24
/^\s*Received: from.*....
# 172.16.0.0/12
/^\s*Received: from.*....

etc.
```

**Comment by jbaumg93** [comment]
Done, splitting it up makes it much cleaner!

**Comment by casperklein** [comment]
Further simplified:

```
/^\s*Received: from.*127\./                                        IGNORE
/^\s*Received: from.*10\./                                         IGNORE
/^\s*Received: from.*(172\.1[6-9]\.|172\.2[0-9]\.|172\.3[0-1]\.)/  IGNORE
/^\s*Received: from.*192\.168\./                                   IGNORE
/^\s*Received: from.*169\.254\./                                   IGNORE
```

Keep in mind, that this will also strip out private IP addresses from mails you receive and not only the ones you send out.

**Comment by jbaumg93** [comment]
This will also match addresses like `8.9.10.11`, which I wanted to avoid. Is there any other way to avoid sending private IPs and container names when another container (or someone on the private network) is sending the email?

**Comment by jbaumg93** [comment]
Hi! If I would create a PR is there any chance you would merge it?

**Comment by casperklein** [comment]
> Keep in mind, that this will also strip out private IP addresses from mails you receive

Because of this, I am no big fan of it. I like my mails unchanged. Instead of extending, I would completely remove the 127.0.0.1 line.

However, our documention would be a good place for the example you provided. So everyone that likes private IP addresses to be stripped out, could do it easily via [user-patches.sh](https://github.com/docker-mailserver/docker-mailserver/blob/master/config/user-patches.sh.dist)

Do you know if it's possible to apply those rules only to outgoing mails?

@docker-mailserver/maintainers What's your opinion on that?

**Comment by wernerfred** [comment]
> @docker-mailserver/maintainers What's your opinion on that?
 
This:

> However, our documentation would be a good place for the example you provided. So everyone that likes private IP addresses to be stripped out, could do it easily via user-patches.sh

**Comment by casperklein** [comment]
@jbaumg93 Would you like to provide a PR for our docs?
