### ISSUE TITLE
[BUG] SASLAUTHD_LDAP_SSL=1 does not set ldaps://

### ISSUE THREAD

**Issue by kevin-leong** [docker-mailserver/docker-mailserver#1983]
# Bug Report

### What is affected by this bug?

Setting the environmental variable SASLAUTHD_LDAP_SSL to "1" does not set "ldaps://" in /etc/saslauthd.conf.  This is breaking saslauthd from working as the parameter "ldap_servers" is not set to a proper URI.

### When does this occur?

When setting the environmental variable SASLAUTHD_LDAP_SSL to "1" 

### How do we replicate the issue?

Set the environmental variable SASLAUTHD_LDAP_SSL to "1".

### Actual Behavior

The parameter "ldap_servers" in the file /etc/saslauthd.conf is being set like the below when setting the environmental variable SASLAUTHD_LDAP_SSL to "1". 

```
ldap_servers: 10.10.10.10
```

I think the problem seems to be with the logic in https://github.com/docker-mailserver/docker-mailserver/blob/master/target/scripts/startup/setup-stack.sh:

```
if [[ -z ${SASLAUTHD_LDAP_SSL} ]] || [[ ${SASLAUTHD_LDAP_SSL} -eq 0 ]]
then
    SASLAUTHD_LDAP_PROTO='ldap://' || SASLAUTHD_LDAP_PROTO='ldaps://'
fi
```

When the environmental variable SASLAUTHD_LDAP_SSL to "1", the logic above will set SASLAUTHD_LDAP_PROTO to "" (i.e empty).  Later in the code when SASLAUTHD_LDAP_PROTO is used, this parameter will be "" (i.e empty) and so SASLAUTHD_LDAP_SERVER will only be printed.

```
if [[ ! -f /etc/saslauthd.conf ]]  then
    _notify 'inf' 'Creating /etc/saslauthd.conf'
    cat &gt; /etc/saslauthd.conf &lt;&lt; EOF
ldap_servers: ${SASLAUTHD_LDAP_PROTO}${SASLAUTHD_LDAP_SERVER}
```

If I am not mistaken, I think this logic needs to be updated so that it properly sets SASLAUTHD_LDAP_PROTO='ldaps://' when the environmental variable SASLAUTHD_LDAP_SSL to "1". 

### Expected Behavior

The parameter "ldap_servers" in the file /etc/saslauthd.conf should be set like the below when setting the environmental variable SASLAUTHD_LDAP_SSL to "1".

ldap_servers: ldaps://10.10.10.10

## Your Environment

- version: `v`
- available RAM: `GB`
- Docker version: `v`
- docker-compose version: `v`

### Environment Variables

```CFG
SASLAUTHD_LDAP_SSL=1 
```

### Relevant Stack Traces

```BASH
# BEGIN

# END
```

**Comment by kevin-leong** [comment]
Here a simple test showing that the logic seems incorrect for setting SASLAUTHD_LDAP_PROTO.

```
[test@docker test]$ cat test 
#!/usr/bin/env bash

if [[ -z ${SASLAUTHD_LDAP_SSL} ]] || [[ ${SASLAUTHD_LDAP_SSL} -eq 0 ]]
then
    SASLAUTHD_LDAP_PROTO='ldap://' || SASLAUTHD_LDAP_PROTO='ldaps://'
fi

echo $SASLAUTHD_LDAP_PROTO

[test@docker test]$ SASLAUTHD_LDAP_SSL=0 ./test
ldap://
[test@docker test]$ SASLAUTHD_LDAP_SSL=1 ./test

[test@docker test]$ ./test
ldap://
```

**Comment by casperklein** [comment]
` SASLAUTHD_LDAP_PROTO='ldap://' || SASLAUTHD_LDAP_PROTO='ldaps://'`

This makes no sense. `SASLAUTHD_LDAP_PROTO='ldaps://'` will never get triggered 😳

**Comment by wernerfred** [comment]
Tagging @moqmar here to throw in his experience as he worked on a related topic in #1901. Did you run in the same problem?

**Comment by aendeavor** [comment]
This

``` BASH
if [[ -z ${SASLAUTHD_LDAP_SSL} ]] || [[ ${SASLAUTHD_LDAP_SSL} -eq 0 ]]
then
    SASLAUTHD_LDAP_PROTO='ldap://' || SASLAUTHD_LDAP_PROTO='ldaps://'
fi
```

does not make any sense :D

I think the author wanted to do something like this:

``` BASH
if [[ -z ${SASLAUTHD_LDAP_SSL} ]] || [[ ${SASLAUTHD_LDAP_SSL} -eq 0 ]]
then
    SASLAUTHD_LDAP_PROTO='ldap://'
elif
    SASLAUTHD_LDAP_PROTO='ldaps://'
fi
```

**Comment by moqmar** [comment]
I'm using the following configuration:

```
SASLAUTHD_LDAP_SERVER=ldaps://example.org:636
SASLAUTHD_LDAP_SSL=1
```

This works, but I guess the logic is indeed broken. The suggested change would definitely be a breaking change for my configuration though, as the configuration file would then read `ldaps://ldaps://...`.

**Comment by wernerfred** [comment]
@casperklein @aendeavor we should include this fix as the last PR for `v10.0.0` as it is indeed a breaking change.
Who will create a PR?

**Comment by aendeavor** [comment]
> @casperklein @aendeavor we should include this fix as the last PR for `v10.0.0` as it is indeed a breaking change.
> 
> Who will create a PR?

Is the change I suggested above everything that needs to be done?

**Comment by aendeavor** [comment]
@moqmar 

> I'm using the following configuration:
> 
> ```
> SASLAUTHD_LDAP_SERVER=ldaps://example.org:636
> SASLAUTHD_LDAP_SSL=1
> ```
> 
> This works, but I guess the logic is indeed broken. The suggested change would definitely be a breaking change for my configuration though, as the configuration file would then read `ldaps://ldaps://...`.

`SASLAUTHD_LDAP_SERVER` should be mentioned in the documentation to not include the protocol after this change. Your PR on doc improvement for LDAP should mention this and should be merged before `v10` too.

**Comment by moqmar** [comment]
I think that it would be great to still optionally allow the protocol to be specified in SASLAUTHD_LDAP_SERVER, as that would allow the empty value to fall back to LDAP_SERVER_HOST, just as for DOVECOT_URIS - this would be much more consistent IMO.

**Comment by aendeavor** [comment]
> I think that it would be great to still optionally allow the protocol to be specified in SASLAUTHD_LDAP_SERVER, as that would allow the empty value to fall back to LDAP_SERVER_HOST, just as for DOVECOT_URIS - this would be much more consistent IMO, the current default value of "localhost" doesn't really make sense in my opinion.

Not using LDAP myself, but this makes sense to me. Can you or someone with a little bit of LDAP experience provide a PR?

**Comment by casperklein** [comment]
>  Who will create a PR?

> Not using LDAP myself

Same here. The PR should be done & tested by someone actually using LDAP.

**Comment by moqmar** [comment]
I can do that in the next couple of days, probably on Thursday. :+1:

Main tasks:
- [ ] Incorporate logic, but make sure the protocol isn't duplicated for better backwards compatibility
- [ ] Use LDAP_SERVER_HOST as a default value instead of "localhost"
- [ ] Update documentation
- [ ] Check which tests are affected & if they still work (and everything else from the PR guidelines)

**Comment by moqmar** [comment]
When adding the fallback, I noticed that `SASLAUTHD_LDAP_SEARCH_BASE` has a really weird default where it falls back to `SASLAUTHD_MECHANISMS=pam`, I'd suggest to use `LDAP_SEARCH_BASE` instead?

 `SASLAUTHD_LDAP_BIND_DN` & `SASLAUTHD_LDAP_PASSWORD` are using anonymous binding as a default, while `DOVECOT_DN` and `DOVECOT_DNPASS` fall back to `LDAP_BIND_DN` and `LDAP_BIND_PW`. This means that it's currently not possible to use Postfix with authenticated bind, but Dovecot with an anonymous one. Shall I use the same defaults as for Dovecot for Saslauthd as well?

Anonymous binds for only some of the services are a quite special use case I guess, probably it makes sense then to add a special value like `DOVECOT_DN=anonymous` (with `anonymous` not being a valid LDAP DN anyways)? This requires lots of testing though, so I wouldn't add it to this PR right now, and I guess we need to talk about it only if someone needs it.
