### ISSUE TITLE
Relay Settings Not Having Effect on Traffic

### ISSUE THREAD

**Issue by rcollinsef** [docker-mailserver/docker-mailserver#1984]
Hi All,

Trying to get mailserver answering on the front end and based on the sender domain, relay the traffic on to another internal mail host for processing. Followed the steps in ./setup.sh to add the sender domain. However, continue to see relay=none and PostFix trying to look for a public MX record. If there is a better forum for this please let me know and I will be happy to move it there.

postfix-relaymap.cf:
`@fax.domain.com        [172.17.0.3]:25`

[mailserver_relay_logging.txt](https://github.com/docker-mailserver/docker-mailserver/files/6504501/mailserver_relay_logging.txt)
[mailserver.env.txt](https://github.com/docker-mailserver/docker-mailserver/files/6504563/mailserver.env.txt)

**Comment by wernerfred** [comment]
@rcollinsef how did you manage to open an issue without using one of the mandatory predefined issue-templates? Serious questions as this seems to happen more frequently in the past time. Are you using GitHub Desktop or Web?

____

Regarding your Issue: Please use the templates! Fill in all the information that is asked even if it seems not neccessary for you. Use code blocks and block wraps for log/console output and do not upload files. Thank you!
