### ISSUE TITLE
Latest Docker won't install

### ISSUE THREAD

**Issue by cybrpimp** [docker-mailserver/docker-mailserver#1987]
We have follow the directions to the best of our ability and got the following error.

Any ideas?

![image](https://user-images.githubusercontent.com/61793417/118910204-f0f58100-b8d8-11eb-930e-2a650807adb3.png)

**Comment by aendeavor** [comment]
1. This error is not related to Docker-Mailserver but to Docker Compose
2. You're using Windows which is not supported

This issue is out of scope of this project and does not adhere to the issue guidelines set by this project. I'm closing this.
