### ISSUE TITLE
How to start mailserver?

### ISSUE THREAD

**Issue by YexuanXiao** [docker-mailserver/docker-mailserver#1991]
I have successfully installed docker, configured the domain in docker-compose.yml, added the mail account using setup.sh, configured dkim, and added the DNS Record for dkim.
I would like to configure a mail server use case and I want to know what I need to do next.😊

**Comment by polarathene** [comment]
Have you looked through our [online documentation](https://docker-mailserver.github.io/docker-mailserver/edge/)?

We have some [examples](https://docker-mailserver.github.io/docker-mailserver/edge/examples/tutorials/basic-installation/) for setting up your server. If anything there is confusing or doesn't explain how to do something you'd like, please let us know so we can improve the documentation.

**Comment by YexuanXiao** [comment]
Thank you! It is useful.

**Comment by YexuanXiao** [comment]
> Have you looked through our [online documentation](https://docker-mailserver.github.io/docker-mailserver/edge/)?
> 
> We have some [examples](https://docker-mailserver.github.io/docker-mailserver/edge/examples/tutorials/basic-installation/) for setting up your mail server. If anything there is confusing or doesn't explain how to do something you'd like, please let us know so we can improve the documentation.

Thank you! It is useful.😄

**Comment by aendeavor** [comment]
> > Have you looked through our [online documentation](https://docker-mailserver.github.io/docker-mailserver/edge/)?
> > We have some [examples](https://docker-mailserver.github.io/docker-mailserver/edge/examples/tutorials/basic-installation/) for setting up your mail server. If anything there is confusing or doesn't explain how to do something you'd like, please let us know so we can improve the documentation.
> 
> Thank you! It is useful.😄

Issue seems to be solved:)
