### ISSUE TITLE
Send mail from .Net core client

### ISSUE THREAD

**Issue by eyadek** [docker-mailserver/docker-mailserver#2004]
# Subject

Sending mail from .Net Core client Using docker mail-server

## Description

##PLEASE HELP!##

Hi, I have installed mail-server and run it using docker-compose. I have a .Net Core client which needs to integrate with the container to auto send emails to users but when sending, it gives me this error "InnerException = {"Smtp server returned an invalid response."}"

My code: 

public static void CreateTestMessage()
        {

            string to = "akkad.eyad@gmail.com";
            string from = "noreply@reef-up.com";
            string subject = "Using the new SMTP client.";
            string body = @"test body";
            MailMessage message = new MailMessage(from, to, subject, body);
            SmtpClient mailer = new SmtpClient();
            mailer.Host = "mail.reef-up.com";
            mailer.Port = 143;
            mailer.Credentials = new System.Net.NetworkCredential("noreply@reef-up.com", "mypassword");
            try
            {
                mailer.Send(message);
            }
            catch (Exception ex)
            {
                Console.WriteLine("Exception caught in CreateTestMessage1(): {0}", ex.ToString());
            }
        }

What might be the problem?

**Comment by casperklein** [comment]
>        mailer.Port = 143;

143 is IMAP. For sending mails, you usually want port 25 or 465 (encrypted)

**Comment by eyadek** [comment]
@casperklein I've changed it to port 25, it still gives me this message "_Service not available, closing transmission channel. The server response was: Cannot connect to SMTP server ::ffff:51.38.133.14 (::ffff:51.38.133.14:25), connect error 10060_"

**Comment by casperklein** [comment]
This looks odd. You want to connect to `51.38.133.14`. No idea, where that `::ffff:` comes from. Looks like a kind of IPv6!?
