### ISSUE TITLE
[BUG] The mailserver is not running!

### ISSUE THREAD

**Issue by waterdrop01** [docker-mailserver/docker-mailserver#2008]
Hello,

When running `./setup.sh email list` I get the error `The mailserver is not running!`.

The mailserver IS running, as shown by the output of `docker ps`: `ab866e57a7d1        tvial/docker-mailserver:stable   "supervisord -c /etc…"   5 months ago        Up 3 weeks          0.0.0.0:25->25/tcp, 110/tcp, 0.0.0.0:143->143/tcp, 0.0.0.0:587->587/tcp, 465/tcp, 995/tcp, 0.0.0.0:993->993/tcp, 4190/tcp   mail`

And I downloaded the `.setup.sh` client based on the README.md instructions:
![Screenshot from 2021-05-27 12-07-02](https://user-images.githubusercontent.com/47316824/119808456-6b7b5d80-bee4-11eb-9241-9a4e16e2691e.png)

I am using the `stable` tag from dockerhub. But it seems `.setup.sh` only supports `latest` tag.

Any idea? Thanks a lot!!

**Comment by waterdrop01** [comment]
Also, directly running the docker command to create the user account doesn't work. I followed [this](https://docker-mailserver.github.io/docker-mailserver/edge/config/user-management/accounts/):
![Screenshot from 2021-05-27 12-12-43](https://user-images.githubusercontent.com/47316824/119808978-ef354a00-bee4-11eb-8341-7b7fa0d95178.png)
And I get this:
```bash: !957: event not found```

**Comment by waterdrop01** [comment]
I'm a long time user of mailserver (over 3 years I'd say) and I deeply appreciate the hard work of the maintainers.

Didn't mean to bother. I genuinely didn't notice the docker repo changed (not even noticed the github repo changed).

Would you recommend me to upgrade from `tvial/docker-mailserver:stable` to `mailserver/docker-mailserver:stable`?

Thanks for your time

**Comment by aendeavor** [comment]
> Would you recommend me to upgrade from `tvial/docker-mailserver:stable` to `mailserver/docker-mailserver:stable`?

Yes. There are numerous improvements (refer to the CHANGELOG.md if you want to know the details). In a few days, major version 10.0.0 should be available (if no bugs appear in the meantime). I‘d advise to update to v10 when it is available :)

**Comment by waterdrop01** [comment]
Got it, thanks @aendeavor  for the feedback! That's very clear. I'll update to latest as soon as v10 is out :)
