### ISSUE TITLE
ONE_DIR information

### ISSUE THREAD

**Issue by Yamakasi** [docker-mailserver/docker-mailserver#2009]
# Subject
I would like some feedback concerning a use case

## Description

I would like to know some more about the ONE_DIR option. Is it only Amavisd what you want to tear out that way from /var/mail?

What about /var/spool/mail, etc ?

I also wonder why the config is outside the docker container, this because I like to do some HA stuff which is possble :)

**Comment by aendeavor** [comment]
This file: <https://github.com/docker-mailserver/docker-mailserver/blob/master/target/scripts/startup/misc-stack.sh> does most of the `ONE_DIR` related stuff. Searching through the scripts, there are some more locations, but the link above provides a good starting point.

**Comment by Yamakasi** [comment]
@aendeavor Thanks, I was looking for that!

What is the reason for ONE_DIR ? As I normally separate those directories myself I wonder why you would put them in one folder, pure backup or some HA related thing for shared storage ?

Maybe this is not the right topic, but why do you expose the config files from the host to he container like:

`- ./config/:/tmp/docker-mailserver/`

I have a feeling and it's maybe better then a lot of ENV's but still... you don't need that much ENV's I think in that case.

I hope to hear some more about the HA part when I want to place it in a SWARM with shared storage. (which I'm actually doing)

**Comment by aendeavor** [comment]
This way, you are able to back up this directory and make it persistent via bind-mounts. Note that we support Docker-compose, not Swarm. For Compose, this way of mounting makes a lot of sense.

**Comment by Yamakasi** [comment]
Sure, agreed. But what do you see different between Swarm and Compose? Compose is a way to start a container/service in Swarm as well... containers just connect  and live in HA/redundancy modus.

Volumes are persistent as well, your next thing is just: Where to store them.

At least you seem to know better what you are doing then MailCow.. which I tried and didn't satisfy me at all (because of their complexity)

**Comment by aendeavor** [comment]
With orchestrators like Swarm, redundancy comes into play. Swarm isn‘t very well thought-through when it comes to the storage (drivers). Hence Kubernetes does it better. Swarm does not decouple these concerns - that’s why it is so close to Compose. And that’s why we bother only with bind mounts and a simple backup solution in one directory. If you want geo-redundant storage with another storage concept and other directories, use Kubernetes.

**Comment by Yamakasi** [comment]
OK, Kubernetes is just another type of thing, I'm more a Rancher guy but bound to Docker atm.

As you say Swarm is not very well thought-through, this is more on where you want/need it for. My concern is more in that case; Did you overthought the binds very well as they come with lots of permission issues from the host by default. Volumes are advised at any time.

Curious.

**Comment by aendeavor** [comment]
> Volumes are advised at any time.

Who says that? I‘m almost exclusively using bind mounts and never had any problems. And we haven‘t even touched backups yet. How would you go about mounting configuration files - one by one?

Bind mounts are not perfect, right, and they have issues, true, but so do volumes.

> Did you overthought the binds very well as they come with lots of permission issues from the host by default

Someone decided this a long while back, and it works very well. You‘re the first to argue about them on my watch. I think this is the easiest solution for the great majority of users, as you either use it, or you go with another concept entirely, which is then not our case.

So, yes. _We thought this through very well_, as we try to do with everything we do in this project:)

**Comment by Yamakasi** [comment]
> > Volumes are advised at any time.
> 
> Who says that? I‘m almost exclusively using bind mounts and never had any problems. And we haven‘t even touched backups yet. How would you go about mounting configuration files - one by one?
> 

Don't mount them at all and just use ENV's ? Both can work but as you don't support HA ENV's are more sticky and the image is easier to maintain.

> Bind mounts are not perfect, right, and they have issues, true, but so do volumes.
 
Volumes don't have issues, binds do; rights.

> > Did you overthought the binds very well as they come with lots of permission issues from the host by default
> 
> Someone decided this a long while back, and it works very well. You‘re the first to argue about them on my watch. I think this is the easiest solution for the great majority of users, as you either use it, or you go with another concept entirely, which is then not our concern anymore.
> 
> So, yes. _We thought this through very well_, as we try to do with everything we do in this project:)

I assume you do things in this project in a way you thought about but easy isn't always good which seems to happen with binds. Just try to take a deep dive into it, it's a known issue; Host rights apply to the docker container binds so you are much faster in problems. Volume's don't have that problem at all.

When you say "it's not our concern anymore" then I assume there is not much invention here or is it just easier as well ? No offence ;)

**Comment by aendeavor** [comment]
> > How would you go about mounting configuration files - one by one?
>
> Don't mount them at all and just use ENV's ? Both can work [...]

How do convert configuration files, like `fail2ban-jail.cf`, as described in the docs [here](https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/optional-config/), to ENV variables to be used in the container? And why is this easier?

---

> Volumes don't have issues, binds do; rights.

Example: Docker and Docker Swarm do not offer a native volume driver for S3. This is just an illustration of why Docker is not well thought-through when it comes to HA. You want HA, use Kubernetes, not Swarm.

---

> Host rights apply to the docker container binds so you are much faster in trouble. Volume's don't have that problem at all.

If I'm not mistaken, the default `docker-compose.yml` even uses volumes. You are free to choose whatever you like.

---

> When you say "it's not our concern anymore" then I assume there is not much invention here

You took this out of context. Let me explain: If you use an orchestrator that is not Compose, we do **not** offer official support. We provide adequate storage concepts for Compose, but **not** for Swarm or other orchestrators, and they are not our concern.

>  I assume there is not much invention here

What is this assumption based upon? The maintainers of this team are one of the best programmers and Dev/CI/SecOps folks I know of and I take **what you just said as an insult**. Not against me, I don't care, but against all the maintainers and contributors of this project.

---

Let's get this straight now: This project is open source, and anyone can contribute. You asked a question, then complained that volumes are better than bind mounts without showing what such a setup would look like.

If you are dissatisfied with the current state, **do not complain, offer solutions and implement them**. As of now, **I don't even know what exactly it is that you want to have changed**. Open a new issue, use the Feature Request template and we will see. I'm especially interested in the "Are you going to implement it?" section. Then we can go ahead and compare your changes to some of the best PR's this project has seen, like #1988, or #1802, or #1826.

**Comment by Yamakasi** [comment]
> > > How would you go about mounting configuration files - one by one?
> > 
> > 
> > Don't mount them at all and just use ENV's ? Both can work [...]
> 
> How do convert configuration files, like `fail2ban-jail.cf`, as described in the docs [here](https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/optional-config/), to ENV variables to be used in the container? And why is this easier?
> 

Erm ? This is how ENV's work ? Can't comment further on it at that part because it is as it is/works. What is easier to start with ; people won't messup that easy by missing config pieces.

> > Volumes don't have issues, binds do; rights.
> 
> Example: Docker and Docker Swarm do not offer a native volume driver for S3. This is just an illustration of why Docker is not well thought-through when it comes to HA. You want HA, use Kubernetes, not Swarm.

S3 is just your problem in that case, who says S3 is "the" solution, it's not; it's just another "holy grail" for people that "need (simple) storage" these days. Kubernetes is also a way, not the only way. K8s so to say is not easy to manage at all by itself, even Google advises not to do so in production.
 
> > Host rights apply to the docker container binds so you are much faster in trouble. Volume's don't have that problem at all.
> 
> If I'm not mistaken, the default `docker-compose.yml` even uses volumes. You are free to choose whatever you like.

Yes you are right there, I saw some example writings/comments here about binds so I was confused why this was said (by maintainers)
 
> > When you say "it's not our concern anymore" then I assume there is not much invention here
> 
> You took this out of context. Let me explain: If you use an orchestrator that is not Compose, we do **not** offer official support. We provide adequate storage concepts for Compose, but **not** for Swarm or other orchestrators, and they are not our concern.
>

No I just took it as you said, I understood in some way but it's just a thing that happens often with projects when people are trying to find better ways that are not directly pushed back to the community. Blogs are great examples for for it, they just say... swarm your docker-mailserver, you can! Better positive sound if you ask me, that's all!

> > I assume there is not much invention here
> 
> What is this assumption based upon? The maintainers of this team are one of the best programmers and Dev/CI/SecOps folks I know of.
> 

It's a nice project but to be honest, this is not rocket science, it's just another way of running a mailserver in a container. Everyone has different thoughts with reasons about such implementations. If they were the best, Rspamd would be in in no-time. But I won't start that discussion again as it has been asked here a lot and it seems to be "difficult" ;)

> This project is open source, and anyone can contribute. This issue was originally just a question. I'd say, if you are dissatisfied with the current state, do not complain, offer solutions and implement them. As of now, I don't really know what exactly it is that you want to have changed. You may open a new issue and use the Feature Request template.

I will see what I can do, but this would change quite some things as the design of ONE_DIR could be done really better if you ask me. Maybe I come up with something when I manage it in a different way, I can PR then :)

Have a good weekend!
