### ISSUE TITLE
[FR] SA_SPAM_SUBJECT per account

### ISSUE THREAD

**Issue by ghnp5** [docker-mailserver/docker-mailserver#2011]
# Feature Request

## Context

Would it be possible to allow setting a Spam Subject prefix per account?

So, for example, for the accounts under @domain1.com, I want to prefix Subjects with "SPAM",
while for accounts under @domain2.com I want nothing at all.

### Is your Feature Request related to a Problem?

No.

### Describe the Solution you'd like

A way to configure or override Spam subjects per account.

Thank you!

**Comment by reneploetz** [comment]
Using Spamassassin and SA_SPAM_SUBJECT to set a per-user spam subject is not possible.
There are two options:
- You can configure spamassassins sql_select_policy to get a per-user configuration - this will require to use an SQL database and therefore is not covered by this project
- You can use a per-user sieve filter or allow users to create one, or you can create a global one that contains all the rules

Some untested examples:
```
require ["editheader", "variables"];

if header :matches "Subject" "*" {
    set "subject" "${1}";
}

if header :contains "X-Spam-Flag" "YES" {
    deleteheader "Subject";
    addheader :last "Subject" "[SPAM] ${subject}";
}
```
```
require ["editheader", "variables"];

if header :matches "Subject" "*" {
    set "subject" "${1}";
}

if header :contains "X-Spam-Flag" "YES" {
   if address :domain "From" "domain1.com" {
        deleteheader "Subject";
        addheader :last "Subject" "[SPAM] ${subject}";
   }
}
```

See also: https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/mail-sieve/
