### ISSUE TITLE
Can this mail server support oauth2 authentication?[FR]

### ISSUE THREAD

**Issue by xueyuancoming** [docker-mailserver/docker-mailserver#2029]

**Comment by aendeavor** [comment]
No, it cannot :)

**Comment by casperklein** [comment]
Not out of the box. However, Dovecot does [support it](https://doc.dovecot.org/configuration_manual/authentication/oauth2/). So it should be possible to implement this via our [user-patches.sh script](https://docker-mailserver.github.io/docker-mailserver/edge/faq/#how-to-adjust-settings-with-the-user-patchessh-script).
