### ISSUE TITLE
external IP adress not shown

### ISSUE THREAD

**Issue by yo34** [docker-mailserver/docker-mailserver#2032]
Hi,

the log of the mail server show the internal docker IP adress (172.18.0.x) , not the IP of the sender. 

I try to put this in :

ports:
      - **192.168.0.65**:25:25    # SMTP  (explicit TLS => STARTTLS)
      - **192.168.0.65**:465:465  # ESMTP (implicit TLS)
      - **192.168.0.65**:587:587  # ESMTP (explicit TLS => STARTTLS)
      - **192.168.0.65**:993:993  # IMAP4 (implicit TLS)

I try **PERMIT_DOCKER=host** in mailserver.env  conf file. 

But it still get internal docker IP : 

....
Jun 10 23:30:21 mail dovecot: imap-login: Login: user=<user@domain.com>, method=PLAIN, rip=172.18.0.1, lip=172.18.0.2, mpid=8076,  TLS, session=<xxxx>
....

Same for postfix daemon log

Thank you

**Comment by casperklein** [comment]
It's hard to help, not knowing the exact setup.. Why did you not use the issue template?

Also describe in detail:

1. Who (which system --> internal or external) is sending the mail?
2. What is the mail-flow: are there any (NAT) systems in between?
3. What is the expected IP address?
