### ISSUE TITLE
create new folder in the user mailbox

### ISSUE THREAD

**Issue by vaskovasilev** [docker-mailserver/docker-mailserver#2036]
Hello dear all,
I want to create one folder - let's say Important like Inbox , Send and so on.
Can you tell me if this is possible and how?

Thank you !

**Comment by wernerfred** [comment]
Basic folders that are mandatory for functionality are already included. I would advise you to quickly spin up the image and test if the behavior fits your needs. If not pretty much anything can be addressed and changed/added afterwards. See [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) for further details or report back with more specific questions.

**Comment by NorseGaud** [comment]
I thought using IMAP allows users to create server-side folders through their email client.

@vaskovasilev , do you mean that you want these folders to be included by default and when a user is first created by the admin? If so, check out https://github.com/docker-mailserver/docker-mailserver/pull/2031/files for an example of doing this for the Archive directory.

**Comment by polarathene** [comment]
There is now [documentation available for this](https://docker-mailserver.github.io/docker-mailserver/edge/examples/uses-cases/imap-folders/), if it is missing anything please let us know :)
