### ISSUE TITLE
Since last updats (docker-compose,..) all folders are empty

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [docker-mailserver/docker-mailserver#2039]
All sent, received,... e-mails where whiped after update from yesterday.
Can you tell me how to fix it?

**Comment by MrLoverLoverMMMM** [comment]
you can close it, i fixed it on my server :)

**Comment by reneploetz** [comment]
For reference purposes and potential later questions:

This commit yesterday changed volumes to bind mounts: https://github.com/docker-mailserver/docker-mailserver/commit/b6b0948095a9e98b4eb5dd3ae7425acdd825fa9b
