### ISSUE TITLE
[BUG] Postgrey whitelist horribly outdated

### ISSUE THREAD

**Issue by dfyx** [docker-mailserver/docker-mailserver#2040]
# Bug Report

## Context

Similar to the [problem that mail in a box](https://github.com/mail-in-a-box/mailinabox/issues/1587) had, the included `/etc/postgrey/whitelist_clients` is outdated by years, the last entry is from 2015. The official current version can be found at http://postgrey.schweikert.ch/pub/postgrey_whitelist_clients

### What is affected by this bug?

Many websites use mass-mailing services like MailChimp for their confirmation mails. Those services use a large pool of servers that all get greylisted individually. Also, they use very conservative intervals when reacting to being greylisted so confirmation tokens are often already invalid when the mail eventually goes through.

### How do we replicate the issue?

1. Sign up for a new account with something that uses MailChimp / Mandrill (I found it while making an account for the game Alchemy Star but I think Twitch is also affected)
2. Wait
3. Request another confirmation mail
3. Wait some more
4. See that the mails take 20 minutes or more

### Actual Behavior

Every mail gets greylisted individually

### Expected Behavior

MailChimp (along with some others) has been on postgrey's whitelist since 2018 so it should not be greylisted.

### Workaround
I added the following to my `config/user-patches.sh`:

```bash
#!/bin/bash
curl http://postgrey.schweikert.ch/pub/postgrey_whitelist_clients -o /etc/postgrey/whitelist_clients
service postgrey reload
```

**Comment by dfyx** [comment]
Oh, tiny addendum: it's okay to whitelist those services since we know that every server in their pool would *eventually* pass greylisting.

**Comment by casperklein** [comment]
You can remove your user-patch in the next DMS version 👍
