### ISSUE TITLE
Network Issue : open file /32: No such file or directory

### ISSUE THREAD

**Issue by Anthony-Jhoiro** [docker-mailserver/docker-mailserver#2042]
# Subject
Other

## Description
Hello ! I am just a beginner, I want to deploy a mail server on a VM running docker, I followed the documentation but I can not connect to the mail server. I found some errors in the logs : 
```
Jun 17 20:47:43 mail postfix/postscreen[3170]: error: open file /32: No such file or directory
Jun 17 20:47:43 mail postfix/postscreen[3170]: warning: non-existent:/32 is unavailable. open file /32: No such file or directory
Jun 17 20:47:43 mail postfix/postscreen[3170]: warning: postscreen_access_list: non-existent:/32: table lookup problem
Jun 17 20:47:43 mail postfix/postscreen[3170]: warning: postscreen_access_list: permit_mynetworks: mynetworks lookup error -- ignoring the remainder of this access list
```

The problem seems to come from my network interface, I am not using eth0 but ens18. so I set this : 
```bash
NETWORK_INTERFACE=ens18
```
If you need more information feel free to ask.

Thank you !

**Comment by georglauterbach** [comment]
> I am just a beginner

You altered the network setup - not a good idea as a beginner :)

What does `PERMIT_DOCKER` look like? When using plain Docker, why do you have to alter the network interface at all?

**Comment by casperklein** [comment]
It doesn't matter what your **host** network interface is. Unless you have a good reason (e.g. HostNetworking in Kubernetes), just leave `NETWORK_INTERFACE` empty.

The errors you see indicates, that the container was unable to determine his IP address, due a wrong `NETWORK_INTERFACE` value.

**Comment by Anthony-Jhoiro** [comment]
Ok thank you I completely misunderstood, I thought that the value of `NETWORK_INTERFACE` should be modified if the network interface didn't have the same name. I have another error now but it seems like an unrelated SSL issue.

FYI, I had to `docker-compose rm` to apply the changes, `docker-compose restart` wasn't enough !

**Comment by casperklein** [comment]
Use `docker-compose down / up` instead.
