### ISSUE TITLE
[FR] Web Admin possible?

### ISSUE THREAD

**Issue by plittlefield** [docker-mailserver/docker-mailserver#2049]
# Feature Request

## Context

As the system administrator for my customer's email server, I have no problem with handling the CLI based setup of this stack with adding email accounts and changing passwords etc.

### Is your Feature Request related to a Problem?

No.

### Describe the Solution you'd like

Is there a way to add some web admin page for adding and editing email accounts so that my customer can do the day-to-day tasks themselves.

I appreciate the fact that this docker stack does not use any database method (which is marvellous!) but wondered of anyone has been able to use a well known script, or perhaps another docker image, to admin the email accounts.

Thanks,

Paully

**Comment by georglauterbach** [comment]
#1800 is about password. But there is no panel to my knowledge.

**Comment by NorseGaud** [comment]
I imagine this coming after we add the API for changing passwords.

**Comment by georglauterbach** [comment]
I will close This here as This is now a thing with docker-mailserver/docker-mailserver-admin
