### ISSUE TITLE
file fetchmail-UIDL-cache not found

### ISSUE THREAD

**Issue by bylli79** [docker-mailserver/docker-mailserver#2052]
# Subject

Other

## Description

Hello,
setting ONE_DIR = 1 and accessing the docker in bash, the file /var/lib/fetchmail/.fetchmail-UIDL-cache is not created.

My problem is that when I restart docker compose, fetchmail resumes downloading all mail.
I don't understand if it's my configuration problem or something.

``` BASH
  ps ax | grep fetch
   363? S 1:30 / usr / bin / fetchmail -f / etc / fetchmailrc -v --nodetach --daemon 300 -i /var/lib/fetchmail/.fetchmail-UIDL-cache --pidfile / var / run / fetchmail / fetchmail.pid
  6685 pts / 0 S + 0:00 grep fetch
root @ mail: / # tail /var/lib/fetchmail/.fetchmail-UIDL-cache
tail: cannot open '/var/lib/fetchmail/.fetchmail-UIDL-cache' for reading: No such file or directory

```

**Comment by casperklein** [comment]
If `/var/lib/fetchmail/.fetchmail-UIDL-cache` can't be created, it's probably a permission issue..
