### ISSUE TITLE
Manually approve an ip banned by postfix/postscreen

### ISSUE THREAD

**Issue by ducky710** [docker-mailserver/docker-mailserver#2055]
Hello I have a question/issue that I'm having trouble finding a concrete answer to. This is the first time i'm aware this has happened but I've needed to receive an email from an older more outdated mailserver using old cyphers and TLS setup (TLSv1) and it seems they're even blocked on spamhaus. I'd like to know how I can manually tell docker-mailserver that it's okay to receive mails for this ip/domain. Logs below

```

Jun 24 12:02:23 mail postfix/tlsproxy[3518]: Anonymous TLS connection established from [188.*********]:34674: TLSv1 with cipher DHE-RSA-AES256-SHA (256/256 bits)



Jun 24 12:02:23 mail postfix/postscreen[3508]: NOQUEUE: reject: RCPT from [188.********]:34674: 550 5.7.1 Service unavailable; client [188.165.1.233] blocked using zen.spamhaus.org; from=<www-data@domain.org>, to=<user@domain.tld>, proto=ESMTP, helo=<domain.org>


2021-06-24 12:02:23,859 DEBG 'mailserver' stdout output:


Jun 24 12:02:23 mail postfix/postscreen[3508]: NOQUEUE: reject: RCPT from [188.********]:34674: 550 5.7.1 Service unavailable; client [188.*******] blocked using zen.spamhaus.org; from=<www-data@domain.org>, to=<user@domain.tld>, proto=ESMTP, helo=<domain.org>



Jun 24 12:02:23 mail postfix/postscreen[3508]: DATA without valid RCPT from [188.*******]:34674


Jun 24 12:02:23 mail postfix/postscreen[3508]: DISCONNECT [188.*******]:34674
```
IP and Domain censored for privacy

**Comment by casperklein** [comment]
That's not possible out of the box. You can however hack something together.

Take a look [here](http://www.postfix.org/POSTSCREEN_README.html), look for the "Permanent allow/denylist test" section.

To modify main.cf: https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/override-defaults/postfix/
To create a whitelist file: https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/override-defaults/user-patches/

**Comment by ducky710** [comment]
Aw that's a shame, However I appreciate the links, I'll give it a shot. Thanks. Maybe this could become a feature request? A quick way to do something like this with setup.sh would be incredible.

**Comment by georglauterbach** [comment]
> Maybe this could become a feature request? A quick way to do something like this with setup.sh would be incredible.

I don‘t think quick hacks belong in the setup script, and this use-case is not very common :)
