### ISSUE TITLE
[FR] support fts-xapian as an alternative to fts-solr

### ISSUE THREAD

**Issue by eleith** [docker-mailserver/docker-mailserver#2061]
# Feature Request

support fts-xapian as an alternative to fts-solr

## Context

fts-xapian is an alternative full text search engine for dovecot that can be easier to tune for mailservers with limited RAM.

the tradeoff is that the indexes takes up much more disk space.

### Is your Feature Request related to a Problem?

currently, [dovecot-solr](https://github.com/docker-mailserver/docker-mailserver/blob/master/Dockerfile#L52) bindings are installed on docker-mailserver (which can be integrated with solr using a [separate container](https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/full-text-search/) ).

however, solr runs on the JVM, requires running an extra container, needs an additional volume and consumes a lot of memory (even when not indexing).

fts-xapian is an alternative that can be easily tuned for low memory environments. it does not need another container, it does not need an additional volume, and it can be easily tuned in the dovecot plugin itself.

### Describe the Solution you'd like

for a fully integrated solution, [dovecot-fts-xapian](https://packages.debian.org/buster-backports/dovecot-fts-xapian) needs to be added to the Dockerfile. however, this package is only available in buster-backports, so that repo will need to be added to the apt list before installing.

### What have you done so far?

currently, users can customize their existing docker-mailserver to use this plugin by [adding a layer to the docker-mailserver container and then adding one dovecot plugin config file](https://gist.github.com/eleith/6bc94d128be049d0eaea234949801992).

### What are you going to contribute?

if desired, i could add the [additional layer as described in this gist](https://gist.github.com/eleith/6bc94d128be049d0eaea234949801992) into the existing docker-mailserver container.  

also, the existing FTS documentation could be appended with instructions on how to configure and turn on fts-xapian.

**Comment by casperklein** [comment]
> is only available in buster-backports

Debian 11 is currently planned to be released on  31. July. Then the backport repo will not be needed.

If there is no downside, beside having one additional package in the image, I see no problem with this. The old package `dovecot-solr` will remain, so that no existing setups will break?

**Comment by eleith** [comment]
> The old package dovecot-solr will remain, so that no existing setups will break?

correct. you can have both bindings installed and just enable one plugin with a dovecot config file.

**Comment by casperklein** [comment]
> i could add the additional layer as described in this gist into the existing docker-mailserver container. also, the existing FTS documentation could be appended with instructions on how to configure and turn on fts-xapian.

Feel free to provide a PR for that 👍
