### ISSUE TITLE
Unable to set NETWORK_INTERFACE on ip failover

### ISSUE THREAD

**Issue by jf-gl** [docker-mailserver/docker-mailserver#2062]
# Subject

I would like to configure a not documented mail server use case

## Description

I have a network interface eth0 with an alias eth0:0 for ip failover.
When I set NETWORK_INTERFACE=eth0:0 the mail server use the eth0 ip.
Is there a way to use eth0:0 ip instead ?

Best regards.

**Comment by jf-gl** [comment]
Regarding setup-stack.sh file this is the set of CONTAINER_IP whose problem.

CONTAINER_IP=$(ip addr show "${NETWORK_INTERFACE}" | \
grep 'inet ' | sed 's|[^0-9\.\/]*||g' | cut -d '/' -f 1)

ip addr show eth0 or ip addr show eth0:0 return the same thing two ip : 
149.202.x.x <- the ip public
151.80.x.x <- the ip failover i need to use

After the first command on top CONTAINER_IP = 149.202.x.x 151.80.x.x, so only 149.202.x.x can be used.

**Comment by georglauterbach** [comment]
Not an easy fix, and because this functionality is critical, touching it is even more unpleasing. Is there maybe a way with the `ip addr show ...` command to only get the IP bound to `eth0:0`?

**Comment by casperklein** [comment]
> Is there maybe a way with the ip addr show ... command to only get the IP bound to eth0:0? 

Not tested:

```bash
ip -4 addr show eth0:0
ip -4 addr list eth0:0
ip -4 addr show dev eth0:0
```

**Comment by casperklein** [comment]
I've just assigned my dev machine a second IP address. Within the mailserver container, there is only `eth0` with it's internal Docker IP address as expected.

@jf-gl Do you run your container with network in host mode or why do you expect there should be `eth0:0`?

**Comment by jf-gl** [comment]
> 
> 
> > Is there maybe a way with the ip addr show ... command to only get the IP bound to eth0:0?
> 
> Not tested:
> 
> ```shell
> ip -4 addr show eth0:0
> ip -4 addr list eth0:0
> ip -4 addr show dev eth0:0
> ```

No, all command above return the two ip.
The container not runs with network in host mode.

**Comment by casperklein** [comment]
Did you run these commands **inside** the container?

**Comment by jf-gl** [comment]
Yes, I do.

**Comment by casperklein** [comment]
>  The container not runs with network in host mode.

If you see your host IP addresses assigned to eth0 inside the container, then something is wrong.

**Comment by jf-gl** [comment]
I ran the commands on host and inside the container.
Inside the container the ip address differs from the eth0.
The problem is that the CONTAINER_IP variable can't bind ip alias on eth0 interface.

Thanks for your reply, finally i work without ip alias.

**Comment by casperklein** [comment]
>  The problem is that the CONTAINER_IP variable can't bind ip alias on eth0 interface.

I don't understand this. The container should only have one IP address, regardless how many (alias) IP addresses the host has.

But glad you worked it out otherwise. So this issue can be closed?
