### ISSUE TITLE
Question: Clients have to use VPN / IP allow list

### ISSUE THREAD

**Issue by billy-mar** [docker-mailserver/docker-mailserver#2063]
Hi Everybody,

I'd like to configure Docker to listen on 127.0.0.1 and HAProxy to allow clients only with specific IP / via VPN. It's clear to me that port 25 is for SMTP fort servers to communicate with each other so I can't lock down that port.

Could you please tell me, is it OK to block (limit to specific IPs) all other ports (143, 587, 993)? Or will I break something by limiting these ports?

Thank you.

Kind regards,

Billy

**Comment by casperklein** [comment]
There should be no problems, limiting access to the ports other than 25.

**Comment by billy-mar** [comment]
Thank you very much @casperklein , I've just closed all ports except 25 and it is still working ;-).
