### ISSUE TITLE
[Q] Configuration of policyd-spf.conf to receive emails from AWS SES

### ISSUE THREAD

**Issue by hanamala** [docker-mailserver/docker-mailserver#2066]
Hi All,

I started using docker-mailserver yesterday and everything works great, thank you for this fantastic project ;-).

The only problem I have is that I'm not getting emails that are sent from a different domain via AWS Simple Email Service (SES).

I read documentation about configuring SPF policy:

https://docker-mailserver.github.io/docker-mailserver/edge/config/best-practices/spf/#backup-mx-secondary-mx

And I realized that SPF Policy is the only way I can solve this problem since as discussed in:

https://github.com/docker-mailserver/docker-mailserver/issues/1751

this is normal and proper behavior.

The error I get is:

~~~
Jul  3 16:38:22 myserver1 policyd-spf[32790]: 550 5.7.23 Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=mfrom;id=<GUID>@eu-central-1.amazonses.com;ip=172.18.0.1;r=<UNKNOWN>
Jul  3 16:38:22 myserver1 postfix/smtpd[32785]: NOQUEUE: reject: RCPT from unknown[172.18.0.1]: 550 5.7.23 <me@mydomain.com>: Recipient address rejected: Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=mfrom;id=<GUID>@eu-central-1.amazonses.com;ip=172.18.0.1;r=<UNKNOWN>; from=<0<GUID>@eu-central-1.amazonses.com> to=<me@mydomain.com> proto=ESMTP helo=<b224-5.smtp-out.eu-central-1.amazonses.com>
~~~

The e-mails are notifications sent by an application that has AWS SES IMAP credentials. Emails are sent from `noreply@email.mydomain.com`. Domain `email.mydomain.com` is configured in AWS SES with all bells and whistles (SPF, DKIM, DMARC) and SES shows that everything is OK. Emails are sent to `me@mydomain.com` (same domain without `email` subdomain) that is configured in docker-mailserver. I used this address with protonmail before I switched to docker-mailserver and e-mails from SES were coming through...

So I copied unmodified `policyd-spf.conf` from a container, modified it and mounted it over: `./config/postfix-policyd-spf.conf:/etc/postfix-policyd-spf-python/policyd-spf.conf`

In the file I tried to whitelist domains like this:

```
Domain_Whitelist = amazonses.com,ap-northeast-1.amazonses.com,ap-northeast-2.amazonses.com,ap-south-1.amazonses.com,ap-southeast-1.amazonses.com,ap-southeast-2.amazonses.com,ca-central-1.amazonses.com,eu-central-1.amazonses.com,eu-west-1.amazonses.com,eu-west-2.amazonses.com,eu-west-3.amazonses.com,us-east-1.amazonses.com,us-east-2.amazonses.com,us-west-1.amazonses.com,us-west-2.amazonses.com
```
and I tried
```
Domain_Whitelist = email.mydomain.com
```
and I tried
```
Domain_Whitelist = mydomain.com
```

and none of those settings worked.

So I tried (full content of the file):

```
debugLevel = 1
TestOnly = 1

HELO_reject = Fail
Mail_From_reject = Fail

PermError_reject = False
TempError_Defer = False

skip_addresses = 127.0.0.0/8,::ffff:127.0.0.0/104,::1

Whitelist = 0.0.0.0/0
```

and that works!

But it's really bad - I understand that I shouldn't whitelist whole internet using `0.0.0.0/0`.

Can anyone please tell me what other less crazy settings should I try?

Thank you.

Hana

**Comment by wernerfred** [comment]
Hey, thanks for the nice words. Short on time right now, will read your question later again (hopefully with more time).. But in the meantime: there is a wiki page for SES and relaying. Maybe this helps solving your problem?

https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/mail-forwarding/relay-hosts/

**Comment by wernerfred** [comment]
Hey, just found time to read your question again now. How does your SPF record look like?
Does it look like this? `v=spf1 mx mx:email.mydomain.com -all`

**Comment by hanamala** [comment]
Hi @wernerfred ,

Thank you very much for reading and replying ;-).

The SPF is
```
email.mydomain.com
3600
TXT
v=spf1 include:amazonses.com ~all
```

It does not have `mx` like in your example since there are MX records on email.mydomain.com since it is used only by SES and only for sending.

To make sure I've just tested it with https://mailgenious.com/ and

<img width="552" alt="spf_dkim" src="https://user-images.githubusercontent.com/86894455/124951723-237f4880-e003-11eb-9701-264972c06eec.png">

Which is not a surprise since I had no issues on protonmail.com with receiving emails sent from the same address `noreply@email.mydomain.com` and from the same application. I would assume Proton wouldn't accept e-mails with wrong SPF. I started to having problems after I switched to self-hosted docker-mailserver and as I mentioned I resolved it by hacking SPF policy.

Thank you.

Kind regards,

Hana

**Comment by wernerfred** [comment]
Can you provide more log lines before and after this entry:

> 

> ```
> Jul  3 16:38:22 myserver1 policyd-spf[32790]: 550 5.7.23 Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=mfrom;id=<GUID>@eu-central-1.amazonses.com;ip=172.18.0.1;r=<UNKNOWN>
> Jul  3 16:38:22 myserver1 postfix/smtpd[32785]: NOQUEUE: reject: RCPT from unknown[172.18.0.1]: 550 5.7.23 <me@mydomain.com>: Recipient address rejected: Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=mfrom;id=<GUID>@eu-central-1.amazonses.com;ip=172.18.0.1;r=<UNKNOWN>; from=<0<GUID>@eu-central-1.amazonses.com> to=<me@mydomain.com> proto=ESMTP helo=<b224-5.smtp-out.eu-central-1.amazonses.com>
> ```

And tell us which spf policy/record is set for the domain docker-mailserver is responsible for (mydomain.com)

My guess is that some kind of filtering is happening on docker-mailserver side which processes the mail and then tries to deliver it to inbox. And then the origin of the mail is docker-mailserver which then will result in a reject bc origin (docker-mailserver) does not match the spf record origin/allowed servers (aws ses).

**Comment by hanamala** [comment]
These are lines I noted a couple of days ago:
~~~
Jul  3 16:38:22 myserver1 postfix/smtpd[32785]: warning: hostname containerhost does not resolve to address 172.18.0.1
Jul  3 16:38:22 myserver1 postfix/smtpd[32785]: connect from unknown[172.18.0.1]
Jul  3 16:38:22 myserver1 postfix/smtpd[32785]: Anonymous TLS connection established from unknown[172.18.0.1]: TLSv1.2 with cipher ECDHE-RSA-AES256-SHA384 (256/256 bits)
Jul  3 16:38:22 myserver1 policyd-spf[32790]: 550 5.7.23 Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=mfrom;id=<GUID>@eu-central-1.amazonses.com;ip=172.18.0.1;r=<UNKNOWN>
Jul  3 16:38:22 myserver1 postfix/smtpd[32785]: NOQUEUE: reject: RCPT from unknown[172.18.0.1]: 550 5.7.23 <me@mydomain.com>: Recipient address rejected: Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=mfrom;id=<GUID>@eu-central-1.amazonses.com;ip=172.18.0.1;r=<UNKNOWN>; from=<0<GUID>@eu-central-1.amazonses.com> to=<me@mydomain.com> proto=ESMTP helo=<b224-5.smtp-out.eu-central-1.amazonses.com>
Jul  3 16:38:43 myserver1 postfix/smtpd[32785]: disconnect from unknown[172.18.0.1] ehlo=2 starttls=1 mail=1 rcpt=0/1 rset=1 quit=1 commands=6/7
~~~

I'll answer the other questions and get some current logs later today. Thank you Frederic.

**Comment by hanamala** [comment]
Hi again @wernerfred ;-)

> And tell us which spf policy/record is set for the domain docker-mailserver is responsible for (mydomain.com)

* The subdomain is
```
email.mydomain.com
3600
TXT
v=spf1 include:amazonses.com -all
```
* The parent domain is
```
mydomain.com
3600
TXT
"v=spf1 mx -all
```

The subdomain is supposed to be used only by SES and has no MX records, the parent domain is supposed to be used only by docker-mailserver and therefore does not have `include:amazonses.com`. This should work just fine since SPF records should not affect other domains (should not affect the domain subdomain or the domain parent domain). I can test changing parent domain SPF to `v=spf1 mx include:amazonses.com -all` and see if that works but if it does then that would be most likely a bug in `policyd-spf` that you use inside docker-mailserver.

* __logs I promised when `/etc/postfix-policyd-spf-python/policyd-spf.conf` is NOT modified:__

``` sh
docker logs mymailsrv --follow
```
~~~
[ TASKLOG ]  Welcome to docker-mailserver 10.0.0
[ TASKLOG ]  Initializing setup
[ TASKLOG ]  Checking configuration
[ TASKLOG ]  Configuring mail server
[ TASKLOG ]  Post-configuration checks
[ TASKLOG ]  Starting daemons & mail server
cron: started
rsyslog: started
dovecot: started
update-check: started
opendkim: started
opendmarc: started
postfix: started
fail2ban: started
clamav: started
changedetector: started
amavis: started
[ TASKLOG ]  mymailsrv1.something.mailsrvdomain.com is up and running
Jul 12 11:53:07 mymailsrv1 amavis[352]: starting. /usr/sbin/amavisd-new at mymailsrv1.something.mailsrvdomain.com amavisd-new-2.11.0 (20160426), Unicode aware
Jul 12 11:53:08 mymailsrv1 amavis[352]: Net::Server: Group Not Defined.  Defaulting to EGID '114 114'
Jul 12 11:53:08 mymailsrv1 amavis[352]: Net::Server: User Not Defined.  Defaulting to EUID '112'
Jul 12 11:53:08 mymailsrv1 amavis[352]: No ext program for   .zoo, tried: zoo
Jul 12 11:53:08 mymailsrv1 amavis[352]: No ext program for   .doc, tried: ripole
Jul 12 11:53:08 mymailsrv1 amavis[352]: No decoder for       .F
Jul 12 11:53:08 mymailsrv1 amavis[352]: No decoder for       .doc
Jul 12 11:53:08 mymailsrv1 amavis[352]: No decoder for       .zoo
Jul 12 11:53:08 mymailsrv1 amavis[352]: Using primary internal av scanner code for ClamAV-clamd
Jul 12 11:53:08 mymailsrv1 amavis[352]: Found secondary av scanner ClamAV-clamscan at /usr/bin/clamscan
Jul 12 11:53:14 mymailsrv1 postfix/master[928]: daemon started -- version 3.4.14, configuration /etc/postfix
Jul 12 11:53:19 mymailsrv1 postfix/master[928]: terminating on signal 15
Jul 12 11:53:19 mymailsrv1 dovecot: master: Warning: Killed with signal 15 (by pid=7 uid=0 code=kill)
Jul 12 11:53:20 mymailsrv1 dovecot: master: Dovecot v2.3.4.1 (f79e8e7e4) starting up for imap, lmtp, sieve
Jul 12 11:53:26 mymailsrv1 postfix/master[1712]: daemon started -- version 3.4.14, configuration /etc/postfix
~~~
* this is me executing `telnet 127.0.0.1 <postfix and dovecot port>` to test that services are up and running:
~~~
Jul 12 11:54:52 mymailsrv1 dovecot: imap-login: Disconnected (no auth attempts in 6 secs): user=<>, rip=172.21.0.1, lip=172.21.0.2, session=<l9cGyuvGYKmsFQAB>
Jul 12 11:55:04 mymailsrv1 postfix/postscreen[2186]: CONNECT from [172.21.0.1]:44726 to [172.21.0.2]:25
Jul 12 11:55:04 mymailsrv1 postfix/dnsblog[2190]: addr 172.21.0.1 listed by domain list.dnswl.org as 127.0.10.3
Jul 12 11:55:09 mymailsrv1 postfix/postscreen[2186]: PASS NEW [172.21.0.1]:44726
Jul 12 11:55:09 mymailsrv1 postfix/smtpd[2217]: warning: hostname containerhost1 does not resolve to address 172.21.0.1
Jul 12 11:55:09 mymailsrv1 postfix/smtpd[2217]: connect from unknown[172.21.0.1]
Jul 12 11:55:17 mymailsrv1 postfix/smtpd[2217]: lost connection after CONNECT from unknown[172.21.0.1]
Jul 12 11:55:17 mymailsrv1 postfix/smtpd[2217]: disconnect from unknown[172.21.0.1] commands=0/0
~~~
* this is me sending e-mail via SES:
~~~
Jul 12 11:55:36 mymailsrv1 postfix/postscreen[2186]: CONNECT from [172.21.0.1]:44768 to [172.21.0.2]:25
Jul 12 11:55:36 mymailsrv1 postfix/postscreen[2186]: PASS OLD [172.21.0.1]:44768
Jul 12 11:55:36 mymailsrv1 postfix/smtpd[2217]: warning: hostname containerhost1 does not resolve to address 172.21.0.1
Jul 12 11:55:36 mymailsrv1 postfix/smtpd[2217]: connect from unknown[172.21.0.1]
Jul 12 11:55:36 mymailsrv1 postfix/smtpd[2217]: Anonymous TLS connection established from unknown[172.21.0.1]: TLSv1.2 with cipher ECDHE-RSA-AES256-SHA384 (256/256 bits)
Jul 12 11:55:36 mymailsrv1 policyd-spf[2353]: 550 5.7.23 Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=mfrom;id=0107017a9a92974c-6f6e62e4-f473-43f6-b652-19dff1b7cdfd-000000@eu-central-1.amazonses.com;ip=172.21.0.1;r=<UNKNOWN>
Jul 12 11:55:36 mymailsrv1 postfix/smtpd[2217]: NOQUEUE: reject: RCPT from unknown[172.21.0.1]: 550 5.7.23 <log@mydomain.com>: Recipient address rejected: Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=mfrom;id=0107017a9a92974c-6f6e62e4-f473-43f6-b652-19dff1b7cdfd-000000@eu-central-1.amazonses.com;ip=172.21.0.1;r=<UNKNOWN>; from=<0107017a9a92974c-6f6e62e4-f473-43f6-b652-19dff1b7cdfd-000000@eu-central-1.amazonses.com> to=<log@mydomain.com> proto=ESMTP helo=<b224-6.smtp-out.eu-central-1.amazonses.com>
Jul 12 11:55:57 mymailsrv1 postfix/smtpd[2217]: disconnect from unknown[172.21.0.1] ehlo=2 starttls=1 mail=1 rcpt=0/1 rset=1 quit=1 commands=6/7
~~~

* __again with hacked `/etc/postfix-policyd-spf-python/policyd-spf.conf`__

``` sh
docker logs mymailsrv --follow
```
~~~
[ TASKLOG ]  Welcome to docker-mailserver 10.0.0
[ TASKLOG ]  Initializing setup
[ TASKLOG ]  Checking configuration
[ TASKLOG ]  Configuring mail server
[ TASKLOG ]  Post-configuration checks
[ TASKLOG ]  Starting daemons & mail server
cron: started
rsyslog: started
dovecot: started
update-check: started
opendkim: started
opendmarc: started
postfix: started
fail2ban: started
clamav: started
changedetector: started
amavis: started
[ TASKLOG ]  mymailsrv1.something.mailsrvdomain.com is up and running
Jul 12 11:58:22 mymailsrv1 amavis[338]: starting. /usr/sbin/amavisd-new at mymailsrv1.something.mailsrvdomain.com amavisd-new-2.11.0 (20160426), Unicode aware
Jul 12 11:58:23 mymailsrv1 amavis[338]: Net::Server: Group Not Defined.  Defaulting to EGID '114 114'
Jul 12 11:58:23 mymailsrv1 amavis[338]: Net::Server: User Not Defined.  Defaulting to EUID '112'
Jul 12 11:58:23 mymailsrv1 amavis[338]: No ext program for   .zoo, tried: zoo
Jul 12 11:58:23 mymailsrv1 amavis[338]: No ext program for   .doc, tried: ripole
Jul 12 11:58:23 mymailsrv1 amavis[338]: No decoder for       .F
Jul 12 11:58:23 mymailsrv1 amavis[338]: No decoder for       .doc
Jul 12 11:58:23 mymailsrv1 amavis[338]: No decoder for       .zoo
Jul 12 11:58:23 mymailsrv1 amavis[338]: Using primary internal av scanner code for ClamAV-clamd
Jul 12 11:58:23 mymailsrv1 amavis[338]: Found secondary av scanner ClamAV-clamscan at /usr/bin/clamscan
Jul 12 11:58:28 mymailsrv1 postfix/master[929]: daemon started -- version 3.4.14, configuration /etc/postfix
Jul 12 11:58:34 mymailsrv1 postfix/master[929]: terminating on signal 15
Jul 12 11:58:34 mymailsrv1 dovecot: master: Warning: Killed with signal 15 (by pid=8 uid=0 code=kill)
Jul 12 11:58:35 mymailsrv1 dovecot: master: Dovecot v2.3.4.1 (f79e8e7e4) starting up for imap, lmtp, sieve
Jul 12 11:58:40 mymailsrv1 postfix/master[1709]: daemon started -- version 3.4.14, configuration /etc/postfix
~~~
* this is me executing `telnet 127.0.0.1 <postfix and dovecot port>` to test that services are up and running:
~~~
Jul 12 12:01:07 mymailsrv1 postfix/postscreen[2418]: CONNECT from [172.22.0.1]:38688 to [172.22.0.3]:25
Jul 12 12:01:07 mymailsrv1 postfix/dnsblog[2422]: addr 172.22.0.1 listed by domain list.dnswl.org as 127.0.10.3
Jul 12 12:01:07 mymailsrv1 postfix/postscreen[2418]: PASS NEW [172.22.0.1]:38688
Jul 12 12:01:08 mymailsrv1 postfix/smtpd[2430]: warning: hostname containerhost1 does not resolve to address 172.22.0.1
Jul 12 12:01:08 mymailsrv1 postfix/smtpd[2430]: connect from unknown[172.22.0.1]
Jul 12 12:01:13 mymailsrv1 postfix/smtpd[2430]: lost connection after CONNECT from unknown[172.22.0.1]
Jul 12 12:01:13 mymailsrv1 postfix/smtpd[2430]: disconnect from unknown[172.22.0.1] commands=0/0
Jul 12 12:01:25 mymailsrv1 dovecot: imap-login: Disconnected (no auth attempts in 6 secs): user=<>, rip=172.22.0.1, lip=172.22.0.3, session=<Tylz4evGNMmsFgAB>
~~~
* this is me sending e-mail via SES:
~~~
Jul 12 12:01:51 mymailsrv1 postfix/postscreen[2418]: CONNECT from [172.22.0.1]:38768 to [172.22.0.3]:25
Jul 12 12:01:51 mymailsrv1 postfix/postscreen[2418]: PASS OLD [172.22.0.1]:38768
Jul 12 12:01:51 mymailsrv1 postfix/smtpd[2430]: warning: hostname containerhost1 does not resolve to address 172.22.0.1
Jul 12 12:01:51 mymailsrv1 postfix/smtpd[2430]: connect from unknown[172.22.0.1]
Jul 12 12:01:51 mymailsrv1 postfix/smtpd[2430]: Anonymous TLS connection established from unknown[172.22.0.1]: TLSv1.2 with cipher ECDHE-RSA-AES256-SHA384 (256/256 bits)
Jul 12 12:01:51 mymailsrv1 policyd-spf[2645]: prepend X-Comment: SPF skipped for whitelisted relay - client-ip=172.22.0.1; helo=b224-1.smtp-out.eu-central-1.amazonses.com; envelope-from=0107017a9a984fe7-b80511c9-6223-4a11-8ae7-e84646bf3a91-000000@eu-central-1.amazonses.com; receiver=<UNKNOWN>
Jul 12 12:01:51 mymailsrv1 dovecot: auth: passwd-file(log@mydomain.com): unknown user
Jul 12 12:01:51 mymailsrv1 postfix/smtpd[2430]: E7C2010A86: client=unknown[172.22.0.1]
Jul 12 12:01:51 mymailsrv1 postfix/cleanup[2649]: E7C2010A86: message-id=<0107017a9a984fe7-b80511c9-6223-4a11-8ae7-e84646bf3a91-000000@eu-central-1.amazonses.com>
Jul 12 12:01:51 mymailsrv1 opendkim[208]: E7C2010A86: [172.22.0.1] [172.22.0.1] not internal
Jul 12 12:01:51 mymailsrv1 opendkim[208]: E7C2010A86: not authenticated
Jul 12 12:01:52 mymailsrv1 opendkim[208]: E7C2010A86: message has signatures from email.mydomain.com, amazonses.com
Jul 12 12:01:52 mymailsrv1 opendkim[208]: E7C2010A86: DKIM verification successful
Jul 12 12:01:52 mymailsrv1 opendkim[208]: E7C2010A86: s=jhdhu7ev6vcrmfgqp5xkrmlyboge5zpw d=email.mydomain.com SSL
Jul 12 12:01:52 mymailsrv1 opendmarc[215]: E7C2010A86 ignoring Authentication-Results at 1 from mymailsrv1.something.mailsrvdomain.com
Jul 12 12:01:52 mymailsrv1 opendmarc[215]: E7C2010A86: email.mydomain.com fail
Jul 12 12:01:52 mymailsrv1 postfix/qmgr[1712]: E7C2010A86: from=<0107017a9a984fe7-b80511c9-6223-4a11-8ae7-e84646bf3a91-000000@eu-central-1.amazonses.com>, size=1797, nrcpt=1 (queue active)
Jul 12 12:01:56 mymailsrv1 postfix/smtpd[2679]: connect from localhost[127.0.0.1]
Jul 12 12:01:56 mymailsrv1 postfix/smtpd[2679]: DB2AA10B09: client=localhost[127.0.0.1]
Jul 12 12:01:56 mymailsrv1 postfix/cleanup[2649]: DB2AA10B09: message-id=<0107017a9a984fe7-b80511c9-6223-4a11-8ae7-e84646bf3a91-000000@eu-central-1.amazonses.com>
Jul 12 12:01:56 mymailsrv1 postfix/qmgr[1712]: DB2AA10B09: from=<0107017a9a984fe7-b80511c9-6223-4a11-8ae7-e84646bf3a91-000000@eu-central-1.amazonses.com>, size=2382, nrcpt=1 (queue active)
Jul 12 12:01:56 mymailsrv1 amavis[961]: (00961-01) Passed CLEAN {RelayedInbound}, [172.22.0.1]:38768 <0107017a9a984fe7-b80511c9-6223-4a11-8ae7-e84646bf3a91-000000@eu-central-1.amazonses.com> -> <info@mydomain.com>, Queue-ID: E7C2010A86, Message-ID: <0107017a9a984fe7-b80511c9-6223-4a11-8ae7-e84646bf3a91-000
000@eu-central-1.amazonses.com>, mail_id: TagSUFR7Kzto, Hits: -0.951, size: 2143, queued_as: DB2AA10B09, 4718 ms
Jul 12 12:01:56 mymailsrv1 postfix/smtp[2655]: E7C2010A86: to=<info@mydomain.com>, orig_to=<log@mydomain.com>, relay=127.0.0.1[127.0.0.1]:10024, delay=5.3, delays=0.56/0.01/0.09/4.7, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as DB2AA10B09)
Jul 12 12:01:56 mymailsrv1 postfix/qmgr[1712]: E7C2010A86: removed
Jul 12 12:01:56 mymailsrv1 dovecot: lmtp(2681): Connect from local
Jul 12 12:01:56 mymailsrv1 dovecot: lmtp(info@mydomain.com)<2681><+z0HODQv7GB5CgAA8NMzjQ>: sieve: msgid=<0107017a9a984fe7-b80511c9-6223-4a11-8ae7-e84646bf3a91-000000@eu-central-1.amazonses.com>: stored mail into mailbox 'INBOX'
Jul 12 12:01:56 mymailsrv1 dovecot: lmtp(2681): Disconnect from local: Client has quit the connection (state=READY)
Jul 12 12:01:56 mymailsrv1 postfix/lmtp[2680]: DB2AA10B09: to=<info@mydomain.com>, relay=mymailsrv1.something.mailsrvdomain.com[/var/run/dovecot/lmtp], delay=0.08, delays=0.01/0.01/0.03/0.03, dsn=2.0.0, status=sent (250 2.0.0 <info@mydomain.com> +z0HODQv7GB5CgAA8NMzjQ Saved)
Jul 12 12:01:56 mymailsrv1 postfix/qmgr[1712]: DB2AA10B09: removed
Jul 12 12:02:14 mymailsrv1 postfix/smtpd[2430]: disconnect from unknown[172.22.0.1] ehlo=2 starttls=1 mail=1 rcpt=1 data=1 quit=1 commands=7
~~~

**Comment by wernerfred** [comment]
Hi @hanamala thx for your reply. I need to take a closer look.
In the meantime 
1. please provide your docker-compose.yml, especially how you published the ports (are there any further devices between internet and the server that might modify the connections?)
2. Are you able to receive mails from different providers? Like gmail etc? So is the problem only present when receiving from SES?

CC @casperklein @georglauterbach or @docker-mailserver/maintainers any further idea?

**Comment by hanamala** [comment]
> please provide your docker-compose.yml

* `docker-compose.yml` - I just replaced `hostname` and `domainname` for privacy and spam reasons

``` yml
version: '3.8'

services:
  mailsrv:
    image: docker.io/mailserver/docker-mailserver:latest
    hostname: mymailsrv1
    domainname: something.mailsrvdomain.com
    container_name: mailsrv
    ports:
      - '127.0.0.1:1201:25'
      - '127.0.0.1:1202:143'
      - '127.0.0.1:1203:587'
      - '127.0.0.1:1204:993'
      - '127.0.0.1:1205:4190'
    volumes:
      - ./config:/tmp/docker-mailserver
      - ./config-other/postfix-policyd-spf.conf:/etc/postfix-policyd-spf-python/policyd-spf.conf
      - ./cert/etc-letsencrypt:/etc/letsencrypt:ro
      - ./data/maildata:/var/mail
      - ./data/mailstate:/var/mail-state
      - ./data/maillogs:/var/log/mail
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DMS_DEBUG=0
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_MANAGESIEVE=1
      - ENABLE_POSTGREY=0
      - ENABLE_SASLAUTHD=0
      - ENABLE_SPAMASSASSIN=1
      - ONE_DIR=1
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - SSL_TYPE=letsencrypt
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always
```

It is running on up-to-date Ubuntu 20.04 in digitalocean.com.

As you can see it is not exposing ports directly - it is behind HAProxy that uses `mode tcp` which is layer 4 and therefore there should be no impact to the docker-mailserver function. I'm used to use HAProxy for all endpoints but I don't actually need it in this scenario (I would need it for mode http - layer 7) so I can expose it directly (`127.0.0.1:25:25`) but based on my experience that won't help since `mode tcp` is literally just passthrough.

I also have letsencrypt container (I need to include it in the docker-compose) that gets certs for `mymailsrv1.something.mailsrvdomain.com` and stores them in `./cert/etc-letsencrypt`. It's working great - my clients connecting Dovecot have no complaints about the certs. Amazing work @wernerfred and rest of the team on letsencrypt compatibility!!!

> Are you able to receive mails from different providers?

Yes, I received e-mails from AWS, Cloudflare, DigitalOcean, Microsoft, Protonmail. I wouldn't notice AWS SES bug unless I was sending e-mails to myself and waiting for them and they were not coming...

Thank you.

Hana

**Comment by georglauterbach** [comment]
`Domain_Whitelist` does not work while manually listing IPs does; a DNS problem?

**Comment by hanamala** [comment]
Thank you @georglauterbach ;-)

But why do I need to whitelist in the first place? SPF on the domain is correct, I shouldn't need to whitelist anything ...

**Comment by georglauterbach** [comment]
You‘re correct.

SPF was „set and forget“ for me. I fear I‘m not of great help with this matter. This was just my shot in the dark.

I would triple-check the records and the config files. My experience with such problems is that somehow I forgot a small detail or did something wrong when I was sure to be correct.

**Comment by hanamala** [comment]
Thank you @georglauterbach . You're right, it is possible to make a small mistake and mess up SPF but thx to mailgenius.com I can confirm that SPF is OK:

![image](https://user-images.githubusercontent.com/86894455/125405958-d48d3680-e3a7-11eb-8f59-1e4e086ed490.png)

**Comment by georglauterbach** [comment]
Then I‘d have a look at the configuration file `policyd-spf.conf` again 🙈

**Comment by hanamala** [comment]
That's why I opened this issue. I looked at the file, I hacked it to whitelist whole internet (0.0.0.0/0), I confirmed that the SPF policy is the problem I'm not getting e-mails from SES ... and I don't know what else to do... This is where my expertise ends.

**Comment by georglauterbach** [comment]
> This is where my expertise ends.

I'm sorry to have wasted your time, but mine end here too, or at least the time I have to look at the issue tracker ATM. Maybe @casperklein has another idea?

**Comment by wernerfred** [comment]
One thing that you could try is activating SRS (https://docker-mailserver.github.io/docker-mailserver/edge/config/environment/#srs-sender-rewriting-scheme)

I'm still wondering as both of the SPF records are valid but mailserver complains about SPF fail there is only one solution:
The mail that hits the mailserver does in fact not come from SES but contains information that it is originated from SES and therefore we have a missmatch -> SPF fail.

Could you try using SRS to preserve the envelope from with the correct origin to see if that helps AND (i'm not sure about this but we could give it a try) disable all tools that might process the mail (Sieve, Spamassasin, ...)

**Comment by hanamala** [comment]
> I'm sorry to have wasted your time

Please don't apologize @georglauterbach , I appreciate your input. Thank you.

> One thing that you could try is activating SRS

OK

> disable all tools that might process the mail (Sieve, Spamassasin, ...)

And ClamAV. I'll try it. Thank you.

**Comment by casperklein** [comment]
I think, the SPF record is wrong:

``v=spf1 include:amazonses.com -all``

Afaik this does not cover subdomains of amazonses.com. Try this:

``v=spf1 include:eu-central-1.amazonses.com -all``

**Comment by wernerfred** [comment]
Isn't spf a Chain? So If you include amazonses.com and the spf of amazonses.com includes Subdomains you inlcude/inherit Them as Well?

**Comment by casperklein** [comment]
Maybe - I don't know. That's why I wrote "afaik" 😉 

After having another look, I think the problem is the sender IP address:

```
Jul  3 16:38:22 myserver1 policyd-spf[32790]: 550 5.7.23 Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=mfrom;id=<GUID>@eu-central-1.amazonses.com;ip=172.18.0.1;r=<UNKNOWN>
Jul  3 16:38:22 myserver1 postfix/smtpd[32785]: NOQUEUE: reject: RCPT from unknown[172.18.0.1]: 550 5.7.23 <me@mydomain.com>: Recipient address rejected: Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=mfrom;id=<GUID>@eu-central-1.amazonses.com;ip=172.18.0.1;r=<UNKNOWN>; from=<0<GUID>@eu-central-1.amazonses.com> to=<me@mydomain.com> proto=ESMTP helo=<b224-5.smtp-out.eu-central-1.amazonses.com>
```

The error message states, that `172.18.0.1` is no valid sender IP address for `eu-central-1.amazonses.com`. And that is true.

**Comment by wernerfred** [comment]
> The error message states, that `172.18.0.1` is no valid sender IP address for `eu-central-1.amazonses.com`. And that is true.

That is what i meant here:

> I'm still wondering as both of the SPF records are valid but mailserver complains about SPF fail there is only one solution:
The mail that hits the mailserver does in fact not come from SES but contains information that it is originated from SES and therefore we have a missmatch -> SPF fail.

I think that the mailserver does somehow process there mails before delivering them to inbox. I had a similar problem with my LDAP setup and SRS fixed it. But there are multiple things that could be the root cause. I think it can be nailed down by try & error
