### ISSUE TITLE
Should I backup volume mailstate?

### ISSUE THREAD

**Issue by pyy** [docker-mailserver/docker-mailserver#2070]
# Subject

Other

## Description

Hello, I would like to move my docker-mailserver container instance to another server. 
May I ask should I also backup(move) "mailstate" volume to the new server?

When I use "docker-compose up -d" in new server, will it create a new "mailstate" with all it need automatically?

Part of my `docker-compse.yml`:

``` BASH
  volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - maillogs:/var/log/mail
    - ssl:/etc/letsencrypt
    - ssllog:/var/log/letsencrypt
    - ./config/:/tmp/docker-mailserver/

```
It doesn't say in documents. see https://docker-mailserver.github.io/docker-mailserver/edge/faq/#what-about-mail-state-folder

Thank you.

**Comment by casperklein** [comment]
If you want to fully migrate to a new server, then also move the mail-state data.

> When I use "docker-compose up -d" in new server, will it create a new "mailstate" with all it need automatically?

Yes, but you will lose the data generated previously by the services listed in the linked FAQ, e.g. Fail2ban database, ClamAV patterns etc.
