### ISSUE TITLE
tvial/docker-mailserver how to update from the new repo? 

### ISSUE THREAD

**Issue by gizmohex** [docker-mailserver/docker-mailserver#2085]
Hello! Please,help me with my stuppid question! I have docker mailserver installed from the old repo tvial/docker-mailserver. How to update my current docker server without new installation? 

Before the repository move i used simple way - just only one command "docker pull tvial/docker-mailserver" :)

So how to update my current image from the new repo? 
****@docker-server:~# docker ps
CONTAINER ID   IMAGE                            COMMAND                  CREATED          STATUS          PORTS                                                                                                                       NAMES
21fffe39f3d5   tvial/docker-mailserver:latest   "supervisord -c /etc…"   40 minutes ago   Up 40 minutes   0.0.0.0:25->25/tcp, 110/tcp, 0.0.0.0:143->143/tcp, 0.0.0.0:587->587/tcp, 465/tcp, 995/tcp, 0.0.0.0:993->993/tcp, 4190/tcp   mail

**Comment by casperklein** [comment]
You have to update your `docker-compose.yml`. Make sure, to read the [CHANGELOG](https://github.com/docker-mailserver/docker-mailserver/blob/master/CHANGELOG.md) before. There were major releases since then, including breaking changes.
