### ISSUE TITLE
[FR] Add support for comment to ./setup alias add

### ISSUE THREAD

**Issue by andrewlow** [docker-mailserver/docker-mailserver#2092]
# Feature Request

## Context

I love aliases. Almost no one has my actual email address, I will create an alias for every single request for a new email. My love of aliases is only matched by my love for password managers (shout out to bitwarden). With many, many aliases (~300) - it gets difficult to know what the heck they are for.
With my old server I had adopted the practice of adding a comment # this is my discord email as the line proceeding the alias. This is very useful.

### Is your Feature Request related to a Problem?

Only that with many aliases it is difficult to know what they are for.

### Describe the Solution you'd like

I would like to have `./setup.sh alias add <email> <recipient>` support a third entry `<comment>`

Yes, this may make deletion a little trickier, but checking for a comment one line above the alias then deleting that would probably work fine. Adding comments may mean a little bit of string processing to ensure the comment doesn't break the file.

It would be super nice if ./setup.sh alias list supported showing the comments - but that appears to pull the data not from the file, so it would be more difficult.

### Are you going to implement it?

Yes, because I know the probability of someone else doing it is low and I can learn from it.

### What are you going to contribute??

Assuming there is consensus that this is useful, I will spend the time to create an appropriate PR.

### Alternatives you've considered

For now I'm just manually editing the config/postfix-virtual.cf file and restarting the container.

### Who will that Feature be useful to?

Folks who maintain a large list of aliases and want additional context as to what it is used for.

### What have you done already?

Only created the feature request - want to avoid investing if this is not in the direction of the project as a whole. 

Ideally - folks would comment that this is a useful feature, and I will be suitably motivated to create the PR.

**Comment by casperklein** [comment]
Out of interest: How does the ``config/postfix-virtual.cf`` file looks like with comments?

Changing the file structure, could break some `./setup.sh` tasks. If if remember correctly, there is some parsing of that file. Maybe `./setup.sh email list` (I haven't checked it).

If you provide a fully working PR, I don't see a reason why it shouldn't be merged 👍

**Comment by andrewlow** [comment]
The file looks fine with comments:

```
$ head config/postfix-virtual.cf 
# Common email address used for mail issues
postmaster@mydomain.com    user@mydomain.com
# Need to alias root too
root@mydomain.com  user@mydomain.com
# Aeroplan
user_aeroplan@mydomain.com user@mydomain.com, other@mydomain.com
# Ampro related email
ampro@mydomain.com user@mydomain.com
# Alias for blog stuff
userblog@mydomain.com       user@mydomain.com
```

Not all comments are super useful (that's really user error on my part) - but there is potential to make your file more useful than the alias itself. It also makes it easier to use numbered or even random aliases for things (or highly cryptic email names).

`./setup.sh email list` works fine for me.

**Comment by andrewlow** [comment]
Very interesting - the addalias function lives here: https://github.com/docker-mailserver/docker-mailserver/blob/65622c56e934459beef7fba045f23ef897a6dcda/target/bin/addalias

However, it doesn't appear to tickle postfix at all after modifying the file. It's a very simple shell script which

1. checks if the alias mapping exists and bails if it is already there
2. if the alias exists, replace it with the new one
3. otherwise append to the file

Comments which will start with the `#` character, will fail to match. Simply adding the optional comment should be no problem.

Delete is here https://github.com/docker-mailserver/docker-mailserver/blob/65622c56e934459beef7fba045f23ef897a6dcda/target/bin/delalias 

and is similarly simple, however it uses `sed` to remove the alias, and I'll need to think about this a little. The logic should be to look at the previous line to the one that matches and then optionally remove the comment.

There doesn't appear to be any testing for the alias helpers - probably a good idea to add some.

**Comment by andrewlow** [comment]
After an add or a delete - it seems like issuing 

```
postmap /etc/postfix/virtual
```

Would be a good idea. This would update the running server.
http://www.postfix.org/VIRTUAL_README.html

**Comment by casperklein** [comment]
> However, it doesn't appear to tickle postfix at all after modifying the file.

That's what [check-for-changes.sh](https://github.com/docker-mailserver/docker-mailserver/blob/master/target/scripts/check-for-changes.sh) is for.

**Comment by georglauterbach** [comment]
Why not :) Provide a PR and we’ll happily review it :)

**Comment by wernerfred** [comment]
> There doesn't appear to be any testing for the alias helpers - probably a good idea to add some.

Would really appreciate it 🚀 Please also make sure to document your changes in the documentation if possible.

> The logic should be to look at the previous line to the one that matches and then optionally remove the comment.

Make sure to take care of all corner cases. No comment, multi line comment (if possible), default comments,...

> Why not :) Provide a PR and we’ll happily review it :)

Agreed 100%. Hit me/us up if you need any further information.

**Comment by andrewlow** [comment]
Sorry - stalled on this as I work on other items #2091 #2108 

If someone has a suggestion on the right shell magic to do the delete - which involves looking at the previous line to determine if it starts with a comment, that would help. Adding is obviously trivial. Replacement/removal are going to require some thought.

**Comment by georglauterbach** [comment]
> If someone has a suggestion on the right shell magic to do the delete - which involves looking at the previous line to determine if it starts with a comment, that would help. Adding is obviously trivial. Replacement/removal are going to require some thought.

Not sure about the context in detail, but I'd try something like

``` BASH
LAST_LINE
while read -r CURRENT_LINE
do
  # here is the work

  # here is the end
  LAST_LINE="${CURRENT_LINE}"
done < <(cat "${FILE}")
```

**Comment by andrewlow** [comment]
I still intend to produce a PR for this - but have some time challenges. If others maintaining this project would like this issue to go away I will close it. Otherwise let's be a bit more patient and see if I get to it in the next 20 days :)

**Comment by andrewlow** [comment]
Ugh - I promise I'll start a PR on this - really soon. I got sidetracked by needing to replace my work laptop which had a busted key.

**Comment by andrewlow** [comment]
I've actually started sketching this out as code

**Comment by polarathene** [comment]
Just saw this, but I am not sure why go through the trouble of this when you can edit the `postfix-virtual.cf` directly instead?

You already show aliases that map to multiple addresses/aliases (_where we've already identified we can't easily support that to avoid risk of blacklisting via backscatter abuse if using Dovecot quotas_), I haven't tried with `setup alias add` but I guess you'd need to quote wrap this mapping if specifying more than one address for the alias to expand to, otherwise the last arg for a comment might not work well?

Since you're making a web app to handle alias support for your users, you could manage your own storage via DB or just JSON for example, allowing you a flexible data structure, that you manipulate and upon change generate the `postfix-virtual.cf` file, overwrite the existing one instead of the `setup alias ...` command and `check-for-changes.sh` will rebuild everything.

That seems more useful and easier imo at least :sweat_smile: The alias methods you'd be calling aren't doing anything special really.

**Comment by andrewlow** [comment]
> You already show aliases that map to multiple addresses/aliases (where we've already identified we can't easily support that to avoid risk of blacklisting via backscatter abuse if using Dovecot quotas), 

Hmm. I'm not sure I understand this 'risk', the other issue with dovecot quotas and errors in the logs happens with aliases with only one target. As I look at the existing alias support in the `setup` command, it doesn't appear to handle multiple targets for an alias, so this something to consider.

> Since you're making a web app to handle alias support for your users, 

It is done, and in 'production' but still hacky and has a number of hard coded things. I eventually plan to clean it up and share.

> you could manage your own storage via DB or just JSON for example, allowing you a flexible data structure

Ugh - no. I'm simply parsing the machine readable `postfix-virtual.cf` to figure out the existing aliases. Right now the app calls into docker to the setup command to add aliases. Sure I could write directly to the `postfix-virtual.cf` file, but I wanted to contribute back the concept of maintaining comments with aliases - it is a handy feature.

**Comment by polarathene** [comment]
> the other issue with dovecot quotas and errors in the logs happens with aliases with only one target.

We fixed that with a PR you were participating in.

Dovecot is made aware of aliases through dummy accounts that share the same mailbox for the alias target, provided it's a basic alias (_it would expand only to one recipient that is a real account, not multiple and not another alias to resolve_).

The risk with backscatter only applies if you have the quotas enabled and quota is exceeded, then a spammer forges the return/sender address which Dovecot will bounce the mail back to since Postfix did not reject it at an earlier stage (_because Dovecot says it doesn't know the account (alias) so it can't check the quota_).

---

> Ugh - no.

It's honestly simpler than messing around with shell scripts. Working with structured data format is much better IMO.

> Sure I could write directly to the `postfix-virtual.cf` file, but I wanted to contribute back the concept of maintaining comments with aliases - it is a handy feature.

You could still do so without it needing to be part of the `setup` scripts. For example someone is working on a web API to change passwords (_technically it calls the `setup` scripts under the hood, but that makes sense in that case, whereas this doesn't IMO_).

> Thus - if the setup commands support comments, it'll be more likely everyone moves that way.

I'm not fond of the approach myself, especially as an additional arg to `setup alias add`, but I don't have any real objections to a PR for it (_other than it offloads maintenance/support to us upon merge_). The other maintainers encourage it, with one having interest in the feature so don't mind me :sweat_smile:

**Comment by andrewlow** [comment]
> > Ugh - no.
> 
> It's honestly simpler than messing around with shell scripts.

I just have some python code that reads the `postfix-virtual.cf` - it's not hard, and the file is well formatted. Postfix is parsing the same file.

I will confess that your other arguments hold weight. 
- The setup scripts have basic support for managing aliases
- My changes will complicate those scripts, and only provide value for a small subet of users
- By pushing this into the base project, it is increasing the maintenance work

Could I ask that some of the maintainers comment on this? I'm happy to let this go as a "will not implement" feature.

**Comment by polarathene** [comment]
> I just have some python code that reads the `postfix-virtual.cf` - it's not hard, and the file is well formatted. Postfix is parsing the same file.

Yeah reading is not an issue.

If you want to contextually add in comments that could be about 1 or more alias lines then you're adding extra logic to parse or modify that.

If you had structured data like JSON, it's not going to be an issue for your application code to work with either, but allows you to create groups of aliases with a comment, you can add/remove aliases from those groups, you can add/remove a group before/after that one, and any other needs.

If no human needs to interact with the CLI tool we provide, you can provide that same functionality via an API that generates a complimentary `postfix-virtual.cf`, while retaining the JSON for application code to work with in a simpler manner (_it could still import `postfix-virtual.cf` to create an initial JSON for example_).

With JSON, you can clearly have the alias value and an array of addresses to expand to. Although I understand that it's a simple enough format to parse anyway, having the structured form available makes it easier to extend for other uses like tackle that quota-status plugin proxy.

---

That said, we do have some python in the project for handling Traefik `acme.json` config, but no maintainer really wants python creeping into the project beyond that AFAIK :sweat_smile:

There is a [`docker-mailserver-admin`](https://github.com/docker-mailserver/docker-mailserver-admin) as a community python project that's extending our image here as a base to offer an API to change passwords. Perhaps your feature would mesh well in that project (_operating on the `postfix-virtual.cf` directly if you prefer_), if you just need a programmatic way to manage comments for a large number of aliases, it seems a more appropriate home for the feature?

The project is still in a WIP state however, if you're comfortable with Python they could probably appreciate another contributor to push it forward to a release.

**Comment by andrewlow** [comment]
> If you want to contextually add in comments that could be about 1 or more alias lines then you're adding extra logic to parse or modify that.

Agree, this is actually where modifying the existing alias del script logic gets non-trivial. You have to make assumptions about the format of the file. It isn't perfect.

> That said, we do have some python in the project for handling Traefik acme.json config, but no maintainer really wants python creeping into the project beyond that AFAIK 😅

My alias editing webapp is in python. I wasn't intending to add any python to this project.

Similarly, I like the 'config file' centric approach of docker-mailserver. I wouldn't want to see an intermediate format introduced to manage aliases.

I hadn't seen [docker-mailserver-admin](https://github.com/docker-mailserver/docker-mailserver-admin) - I'll have to go check it out. Python is a language I like to make fun of, it's horrible - but so darn useful too.

**Comment by andrewlow** [comment]
Ok - after reviewing that sub-project, I agree that this type of feature request fits in there. It's still pretty early, but if we have general agreement I'm happy to move this over there.

**Comment by andrewlow** [comment]
I've thought this over a bunch more - I think I'll close this. Either I'll publish my alias editor .. and people can opt to use it - or the API project will get going in earnest and I'll add code there.
