### ISSUE TITLE
[BUG] fts_xapian plugin not found

### ISSUE THREAD

**Issue by alangrafu** [docker-mailserver/docker-mailserver#2115]
### What is affected by this bug?

I followed [this guide](https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/full-text-search/#further-discussion) to add FTS using xapian, but when running the docker container I get

```
sievec: Fatal: Plugin 'fts_xapian' not found from directory /usr/lib/dovecot/modules
```

I checked on the container itself and there is no plugin as far as I can tell.

### When does this occur?

When running the container

### How do we replicate the issue?

1. Follow https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/full-text-search/#further-discussion
2. Run mailserver

### Actual Behavior

A FATAL message appears in the logs

### Expected Behavior

FTS should work when the configuration is enabled.

## Your Environment

- version: `"Created": "2021-06-01T11:38:24.249197427Z",`
- available RAM: `1GB`
- Docker version: `20.10.8, build 3967b7d`
- docker-compose version: `1.29.2, build 5becea4c`

**Comment by alangrafu** [comment]
OK, I see this works on the `edge` tag, bot in the `latest`. I'm not sure if this is supposed to be like this or not, so I will leave this issue open, but feel free to closed if this is expected.

**Comment by casperklein** [comment]
This is part of the upcoming 10.1.0 version, which will be released in the next days.
