### ISSUE TITLE
Is Amavis blocking my own email

### ISSUE THREAD

**Issue by gismomtl** [docker-mailserver/docker-mailserver#2119]
Hi,
I'm using 10.1.0 version of the docker-mailserver, multiple domains set to be managed by the docker, dkim, srf, letencrypt .. done

When sending email from Outlook through SMTP port 587 to an external email, amavis always flag my own email as SPAM...
list of "local" domain is up2date..

In the log I can see "Passed SPAM {RelayedOpenRelay,Quarantined}"
I tried to adjust different parameters.. but no success...

**Comment by georglauterbach** [comment]
Please provide your logs and setup. With what you wrote, we cannot help you.
