### ISSUE TITLE
Document fail2ban mount and/or copy systems

### ISSUE THREAD

**Issue by williamdes** [docker-mailserver/docker-mailserver#2120]
Reading the online documentation I could not figure out where to put my config, etc..
I will probably document this

Sorry for the issue template, github removed it

https://github.com/docker-mailserver/docker-mailserver/blob/7293e3c9e8fed5020495f0bbfc8805e3a7fe3683/target/scripts/startup/setup-stack.sh#L1488-L1496

**Comment by casperklein** [comment]
> Reading the online documentation I could not figure out where to put my config, etc..

? https://docker-mailserver.github.io/docker-mailserver/edge/config/security/fail2ban/


> Fail2Ban is installed automatically and bans IP addresses for 3 hours after 3 failed attempts in 10 minutes by default. If you want to change this, you can easily edit config/fail2ban-jail.cf.
> You can do the same with the values from fail2ban.conf, e.g dbpurgeage. In that case you need to edit config/fail2ban-fail2ban.cf.

Examples:

https://github.com/docker-mailserver/docker-mailserver/blob/master/config/fail2ban-fail2ban.cf
https://github.com/docker-mailserver/docker-mailserver/blob/master/config/fail2ban-jail.cf

**Comment by williamdes** [comment]
My point is, where do I have to put/mount this file
Without reading the script I could not figure out
I may write a PR for that

**Comment by casperklein** [comment]
From our example docker-compose.yml
```
    volumes:
      - ./config/:/tmp/docker-mailserver/
```

Therefore: ``- /config/fail2ban-jail.cf:/tmp/docker-mailserver/fail2ban-jail.cf``

**Comment by williamdes** [comment]
I expected this one the same page ;)

**Comment by williamdes** [comment]
Also I expected to find on this page the ban and unban commands too
