### ISSUE TITLE
multi-domain 

### ISSUE THREAD

**Issue by Moimemeici** [docker-mailserver/docker-mailserver#2121]
Hello all !
Sorry for my english, i'am french.
But i have one question for the moment.
I see the docker-compose example and i see :
domainname: example.com
If i have multi-domain, what's is good :
domainname: example.com, exemple2.fr, ...

**Comment by casperklein** [comment]
Afaik it doesn't matter what you choose. Try it out and see if it's working 👍

**Comment by georglauterbach** [comment]
What @casperklein said is absolutely correct: It doesn't matter which one you choose as long as it matches your MX record :)
