### ISSUE TITLE
Avoid chmod +x when not needed

### ISSUE THREAD

**Issue by williamdes** [docker-mailserver/docker-mailserver#2122]
https://github.com/docker-mailserver/docker-mailserver/blob/7293e3c9e8fed5020495f0bbfc8805e3a7fe3683/target/scripts/startup/setup-stack.sh#L1624

I bet a check could be added to avoid the chmod +x on each run

```
chmod: changing permissions of '/tmp/docker-mailserver/user-patches.sh': Read-only file system
```

I mount as read only the script `- ${USER_PATCHES_FILE:-./user-patches.sh}:/tmp/docker-mailserver/user-patches.sh:ro`

**Comment by georglauterbach** [comment]
I thought about this too. We could just execute

``` BASH
bash /tmp/docker-mailserver/user-patches.sh
```

instead of `chmod`ing it before. Please provide a PR :)

**Comment by casperklein** [comment]
This breaks scripts using an alternative shell to BASH.

PS: TBH, I think not many or even zero people would be hit by this. I just wanted to mention it 😉

**Comment by georglauterbach** [comment]
This is a small enhancement after all, but I still like it. We only support Bash and Shell, so I think this would be justifieable:)
