### ISSUE TITLE
Question: Multiple containers and IP address blacklisting

### ISSUE THREAD

**Issue by lukos** [docker-mailserver/docker-mailserver#2131]
## How to deal with multiple IP addresses and avoiding blacklists?

When you have multiple instances of a mail server, it is common to use multiple public IP addresses, each with R-DNS setup etc. so that your mail server is trusted by receiving servers and mail not marked as spam. If an IP ever gets put onto a SPAM list, you get another IP address and assign it. 

If we were to setup, say, 5 containers running this image, is there documentation on how to setup public IP addresses so that they would work like 5 separate mail servers?

Doing this doesn't sound quite like what Docker does when you want 5 instances but also, it doesn't seem right to have 5 separate deployments of 1 instance of exactly the same image so that each of them can have its own ingress/IP address. Maybe it is?

**Comment by casperklein** [comment]
If you are afraid of getting black listed for some reason, then you can of course deploy multiple instances of DMS. There is nothing DMS specific to consider. Just setup the other 4 instances as you did with your first one (correct (r)DNS records etc.)
I don't understand exactly what your question is.

**Comment by lukos** [comment]
Sorry for the confusing question! So my scenario is this: I want to run multiple (let's say 10) individual mail servers to share the load and to reduce the chance of blacklisting servers from blocking most or all of our outgoing mail, which could happen if I only had one server.

Currently, I can only do this by building and managing each mail server on a separate VPS with its own public IP. 

Then I saw this project and thought it would be great because Docker provides automation and easier configuration. Why not just do a deployment with 10 instances and hey presto, exactly what I want?

But then I thought the pattern doesn't fit Docker/Kubernetes. Containerised workloads/services/deployments are usually designed to have a single IP address on an ingress which maps to multiple servers, therefore sharing the load and increasing resilience. This wouldn't give me 10 separately configured mail servers with their own IPs but instead 10 instances all with the same IP and configuration (rDNS, mail server name etc).

So the question is, if I wanted to have separate instances, would that require e.g. 10 separate deployments with 10 separate ingresses/IPs, all deployed independently or is there some kind of trick so that I could indeed just have a single deployment with 10 instances and common config but with separate IPs and names? For example, I don't know whether I could simply point 10 IPs all to the same service and get all instances to handle all hostnames e.g. ms1, ms2, ms3 etc.

**Comment by casperklein** [comment]
> are usually designed to have a single IP address on an ingress 

Correct. As you said, the easy way would be, to use 10 VPS where each has it's own IP address.

If you want to run it on only one machine, you'll need to ensure, that this is machine has multiple public IP addresses and you must somehow manage the correct host/docker routing.
The only benefit this would bring, would be IP address redundancy (to avoid blacklisting). But on the other hand, you'll create a single point of failure + no load sharing.
