### ISSUE TITLE
How do I update

### ISSUE THREAD

**Issue by Clemens-Dautermann** [docker-mailserver/docker-mailserver#2135]
Okay, this issue already sounds stupid as I am writing it. I don't know how to update. I received an email:
```
There is a docker-mailserver update available on your host: mail.*****

Current version: 10.0.0
Latest  version: 10.1.0
```
I am by no means a professional or experienced with docker workflow so it's probably really simple. Thank you!

**Comment by georglauterbach** [comment]
1. Check the release notes: <https://github.com/docker-mailserver/docker-mailserver/releases/tag/v10.1.0>
2. If you think all is well, stop your mail server (`docker-compose down`, don't use `docker-compose stop`)
3. Update the tag in the `docker-compose.yml` file to `10.1.0`
4. Run `docker-compose up`
5. Done
