### ISSUE TITLE
SMTP Errors in Rainloop

### ISSUE THREAD

**Issue by JacobOkanta** [docker-mailserver/docker-mailserver#2145]
# Subject
I have questions about TLS/SSL/STARTTLS/OpenSSL or I would like some feedback concerning a use case

I'm not sure which one represents my case better. I've started having this issue while configuring SSL but I'm not sure if that's where the problem is or not.

## Description
I have 3 mail domains directed to this server, I've decided to use Rainloop at mail.mydomain.com for all 3 as a mail client, and I'm using Thunderbird on some devices. I'm using Letsencrypt certificates via a bind mount from the host, I am using the same certificates for the Rainloop interface. This all seems to be working as expected, however when adding the domains to Rainloop the first domain adds perfectly fine with no errors, but the other 2 do not there is an error for the SMTP test "stream_socket_client(): SSL: Handshake timed out". Adding from all domains in Thunderbird on a pc outside the network seems to work fine, Rainloop is also hosted in Docker on the same server using the image from waldner. Further testing reveals that Thunderbird on the local network also doesn't seem to work using the same settings from the outside client that is working, there doesn't seem to be any logs relating to connecting from Thunderbird on the local network so this might be a different issue possibly with the firewall. I'll include relevant logs from the mailserver below with regards to the Rainloop error, there was nothing of importance in the Rainloop log. Thanks in advance for any asssitance!

Mailserver Logs:
```
2021-08-22 15:07:42 | Aug 22 20:07:42 mail postfix/smtps/smtpd[1113310]: disconnect from unknown[10.20.1.1] commands=0/0
-- | --
  |   | 2021-08-22 15:07:42 | Aug 22 20:07:42 mail postfix/smtps/smtpd[1113310]: lost connection after CONNECT from unknown[10.20.1.1]
  |   | 2021-08-22 15:07:42 | Aug 22 20:07:42 mail postfix/smtps/smtpd[1113310]: SSL_accept error from unknown[10.20.1.1]: Broken pipe
  |   | 2021-08-22 15:07:42 | Aug 22 20:07:42 mail postfix/smtps/smtpd[1113310]: connect from unknown[10.20.1.1]
  |   | 2021-08-22 15:07:32 | Aug 22 20:07:32 mail dovecot: imap-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=10.20.1.1, lip=172.16.2.24, TLS, session=<jO1xcyvKObMKFAEB>
```

**Comment by JacobOkanta** [comment]
Docker-compose
```   mailserver:
    container_name: mailserver
    image: docker.io/mailserver/docker-mailserver:latest
    restart: unless-stopped
    hostname: mail.jacobwmeadows.com # <-- CHANGE THIS
    domainname: jacobwmeadows.com # <-- CHANGE THIS
    env_file: mailserver.env
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
      - "4190:4190" # Sieve
    volumes:
      - ${SERVICES_ROOT}/${MAILSERVER_ROOT:-mailserver}/data/maildata:/var/mail
      - ${SERVICES_ROOT}/${MAILSERVER_ROOT:-mailserver}/data/mailstate:/var/mail-state
      - ${SERVICES_ROOT}/${MAILSERVER_ROOT:-mailserver}/data/maillogs:/var/log/mail
      - ${SERVICES_ROOT}/${MAILSERVER_ROOT:-mailserver}/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    stop_grace_period: 1m
    cap_add: [ "NET_ADMIN", "SYS_PTRACE" ]
    networks:
      - proxy
    logging:
      driver: "loki"
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
  rainloop:
    image: waldner/rainloop
    container_name: rainloop
    restart: unless-stopped
    hostname: rainloop
    volumes:
      - ${SERVICES_ROOT}/${WEBMAIL_ROOT:-rainloop}:/rainloop/data
    environment:
      - TZ
      - WEBMAIL_DATA=/rainloop/data
    networks:
      - proxy
    logging:
      driver: "loki"
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push" '''

Mailserver.env
``` 
OVERRIDE_HOSTNAME=
DMS_DEBUG=0
SUPERVISOR_LOGLEVEL=warn
ONE_DIR=1
POSTMASTER_ADDRESS=
ENABLE_UPDATE_CHECK=1
UPDATE_CHECK_INTERVAL=1d
PERMIT_DOCKER=
NETWORK_INTERFACE=
TLS_LEVEL=
SPOOF_PROTECTION=1
ENABLE_SRS=0
ENABLE_POP3=1
ENABLE_CLAMAV=1
ENABLE_AMAVIS=1
AMAVIS_LOGLEVEL=0
ENABLE_FAIL2BAN=1
FAIL2BAN_BLOCKTYPE=drop
ENABLE_MANAGESIEVE=1
POSTSCREEN_ACTION=enforce
SMTP_ONLY=
SSL_TYPE=letsencrypt
SSL_CERT_PATH=
SSL_KEY_PATH=
SSL_ALT_CERT_PATH=
SSL_ALT_KEY_PATH=
VIRUSMAILS_DELETE_DELAY=
ENABLE_POSTFIX_VIRTUAL_TRANSPORT=
POSTFIX_DAGENT=
POSTFIX_MAILBOX_SIZE_LIMIT=
ENABLE_QUOTAS=1
POSTFIX_MESSAGE_SIZE_LIMIT=
PFLOGSUMM_TRIGGER=
PFLOGSUMM_RECIPIENT=
PFLOGSUMM_SENDER=
LOGWATCH_INTERVAL=
LOGWATCH_RECIPIENT=
REPORT_RECIPIENT=0
REPORT_SENDER=
REPORT_INTERVAL=daily
POSTFIX_INET_PROTOCOLS=all
ENABLE_SPAMASSASSIN=1
SPAMASSASSIN_SPAM_TO_INBOX=1
MOVE_SPAM_TO_JUNK=1
SA_TAG=2.0
SA_TAG2=6.31
SA_KILL=6.31
SA_SPAM_SUBJECT=***SPAM*****
ENABLE_FETCHMAIL=1
FETCHMAIL_POLL=300
ENABLE_LDAP=
LDAP_START_TLS=
LDAP_SERVER_HOST=
LDAP_SEARCH_BASE=
LDAP_BIND_DN=
LDAP_BIND_PW=
LDAP_QUERY_FILTER_USER=
LDAP_QUERY_FILTER_GROUP=
LDAP_QUERY_FILTER_ALIAS=
LDAP_QUERY_FILTER_DOMAIN=
DOVECOT_TLS=
DOVECOT_USER_FILTER=
DOVECOT_PASS_FILTER=
DOVECOT_MAILBOX_FORMAT=maildir
DOVECOT_AUTH_BIND=
ENABLE_POSTGREY=1
POSTGREY_DELAY=300
POSTGREY_MAX_AGE=35
POSTGREY_TEXT=Delayed by Postgrey
POSTGREY_AUTO_WHITELIST_CLIENTS=5
ENABLE_SASLAUTHD=0
SASLAUTHD_MECHANISMS=
SASLAUTHD_LDAP_SERVER=
SASLAUTHD_LDAP_BIND_DN=
SASLAUTHD_LDAP_PASSWORD=
SASLAUTHD_LDAP_SEARCH_BASE=
SASLAUTHD_LDAP_FILTER=
SASLAUTHD_LDAP_START_TLS=
SASLAUTHD_LDAP_TLS_CACERT_FILE=
SASLAUTHD_LDAP_TLS_CACERT_DIR=
SASLAUTHD_LDAP_PASSWORD_ATTR=
SASL_PASSWD=
SASLAUTHD_LDAP_AUTH_METHOD=
SASLAUTHD_LDAP_MECH=
SRS_SENDER_CLASSES=envelope_sender
SRS_EXCLUDE_DOMAINS=
SRS_SECRET=
DEFAULT_RELAY_HOST=
RELAY_HOST=
RELAY_PORT=25
RELAY_USER=
RELAY_PASSWORD=
```
It does seem strange to me that everything appears to work fine from outside the network, but when inside the network only the original domain works.

**Comment by casperklein** [comment]
I cannot see something fundamental wrong with your configuration. As said, you could try `SSL_TYPE=manual`, just to be sure.

If it works from outside, but not within your network, then there is some kind of routing/NAT issue I think. Double check the traffic flow and compare outside vs. inside.

**Comment by JacobOkanta** [comment]
Further testing would seem to confirm that this is most likely some type of routing issue. Using "mailserver" as the hostname for SMTP works, as well as using the local IP of the server, however using my public IP or the domain name for 2nd or 3rd domains does not work. Changing to `SSL_TYPE=manual` doesn't seem to affect the issue in any way. Unfortunately I'm not really sure how to troubleshoot further as my knowledge of networking is limited. The original domain does work as expected, but others do not. Would there be a problem with using mail.domain1.com as the smtp server address, and logging in with a domain2.com address? Also it feels of note that the IMAP connection is working correctly, only SMTP is having this issue. Also I am seeing some other errors (sometimes?) when this problem happens.
```
2021-08-28 10:25:09 | Aug 28 15:25:09 mail postfix/dnsblog[95775]: warning: dnsblog_query: lookup error for DNS query 1.1.20.10.psbl.surriel.com: Host or domain name not found. Name service error for name=1.1.20.10.psbl.surriel.com type=A: Host not found, try again
-- | --
  |   | 2021-08-28 10:25:09 | Aug 28 15:25:09 mail postfix/dnsblog[95774]: warning: dnsblog_query: lookup error for DNS query 1.1.20.10.dnsbl.sorbs.net: Host or domain name not found. Name service error for name=1.1.20.10.dnsbl.sorbs.net type=A: Host not found, try again
  |   | 2021-08-28 10:25:09 | Aug 28 15:25:09 mail postfix/dnsblog[95773]: warning: dnsblog_query: lookup error for DNS query 1.1.20.10.zen.spamhaus.org: Host or domain name not found. Name service error for name=1.1.20.10.zen.spamhaus.org type=A: Host not found, try again
  |   | 2021-08-28 10:25:09 | Aug 28 15:25:09 mail postfix/dnsblog[95772]: warning: dnsblog_query: lookup error for DNS query 1.1.20.10.list.dnswl.org: Host or domain name not found. Name service error for name=1.1.20.10.list.dnswl.org type=A: Host not found, try again
  |   | 2021-08-28 10:25:09 | Aug 28 15:25:09 mail postfix/dnsblog[95771]: warning: dnsblog_query: lookup error for DNS query 1.1.20.10.bl.spameatingmonkey.net: Host or domain name not found. Name service error for name=1.1.20.10.bl.spameatingmonkey.net type=A: Host not found, try again
  |   | 2021-08-28 10:25:09 | Aug 28 15:25:09 mail postfix/dnsblog[95770]: warning: dnsblog_query: lookup error for DNS query 1.1.20.10.bl.mailspike.net: Host or domain name not found. Name service error for name=1.1.20.10.bl.mailspike.net type=A: Host not found, try again
  |   | 2021-08-28 10:25:09 | Aug 28 15:25:09 mail postfix/postscreen[95767]: warning: dnsblog reply timeout 10s for psbl.surriel.com
  |   | 2021-08-28 10:25:09 | Aug 28 15:25:09 mail postfix/postscreen[95767]: warning: dnsblog reply timeout 10s for dnsbl.sorbs.net
  |   | 2021-08-28 10:25:09 | Aug 28 15:25:09 mail postfix/postscreen[95767]: warning: dnsblog reply timeout 10s for zen.spamhaus.org
  |   | 2021-08-28 10:25:09 | Aug 28 15:25:09 mail postfix/postscreen[95767]: warning: dnsblog reply timeout 10s for list.dnswl.org
  |   | 2021-08-28 10:25:09 | Aug 28 15:25:09 mail postfix/postscreen[95767]: warning: dnsblog reply timeout 10s for bl.spameatingmonkey.net
  |   | 2021-08-28 10:25:09 | Aug 28 15:25:09 mail postfix/postscreen[95767]: warning: dnsblog reply timeout 10s for bl.mailspike.net
  |   | 2021-08-28 10:25:09 | Aug 28 15:25:09 mail postfix/postscreen[95767]: warning: dnsblog reply timeout 10s for b.barracudacentral.org
  |   | 2021-08-28 10:25:09 | Aug 28 15:25:09 mail postfix/dnsblog[95769]: warning: dnsblog_query: lookup error for DNS query 1.1.20.10.b.barracudacentral.org: Host or domain name not found. Name service error for name=1.1.20.10.b.barracudacentral.org type=A: Host not found, try again
```
I don't believe that these are related but I wanted to bring it up as I could be wrong. I believe the relevant error is still `SSL_accept error from unknown[10.20.1.1]: Broken pipe`. I'm just not sure why it is only an issue with SMTP at mail.domain2.com and mail.domain3.com and only inside the network. Is it possible that there could be a configuration option somewhere for postfix that only answers to the hostname and local IP of the server?

**Comment by JacobOkanta** [comment]
I believe I have confirmed now that this is a configuration issue somewhere. By stopping the current mailserver I was able to create another instance changing the hostname and domain name to mail.domain2.com and domain2.com, the only things copied to the new instance were postfix-accounts.cf and the opendkim folder. Testing now I have exactly the same issue except now domain2.com works while domain1.com and domain3.com do not. I'm sure that this is a config issue somewhere that will be easy to fix once I know where it is, also if I'm correct perhaps there could be a variable for other domains in mailserver.env to automatically add them to this config file?

**Comment by casperklein** [comment]
On every connect, the client IP address is checked against various DNS blacklists

`Aug 28 15:25:09 mail postfix/dnsblog[95772]: warning: dnsblog_query: lookup error for DNS query 1.1.20.10.list.dnswl.org: Host or domain name not found. Name service error for name=1.1.20.10.list.dnswl.org type=A: Host not found, try again`

Checking **local** IPs (10.20.1.1 in this case) against **public** DNS blacklists makes no sense and will fail.

You can disable DNS blocklist by adding `postscreen_dnsbl_sites =` to `config/postfix-main.cf`

> Is it possible that there could be a configuration option somewhere for postfix that only answers to the hostname and local IP of the server?

I don't think so. Make sure, that your MX records from all domains point to the same server, e.g.

Your DMS instance runs on "mail.example.com".

Domain1 would have a MX record of "mail.example.com"
Domain2 would have a MX record of "mail.example.com"
etc..

**Comment by JacobOkanta** [comment]
Oh I think I see what I have done wrong. My mx records are currently domain1=mail.domain1.com, domain2=mail.domain2.com,domain3=mail.domain3.com. All of these do point to the same IP. I have used other mail server applications that did work this way so I didn't even think about it when setting up the records. Just to clarify all domains should point to mail.domain1.com, domain1.com being what is specified in the compose file as domainname correct?

**Comment by casperklein** [comment]
I might be also working the way you did it, as long as the IP address is correct. But it's best practice, to do it like I described.

> what is specified in the compose file as domainname correct?

Yes.

**Comment by casperklein** [comment]
Also best practice (if possible with your hoster),  set the correct PTR record (Reverse DNS):

```
mail.jacobwmeadows.com       IN     A     63.135.188.11
11.188.135.63.in-addr.arpa     IN     PTR     host-63-135-188-11.twlakes.net
```

`11.188.135.63.in-addr.arpa` should point to `mail.jacobwmeadows.com`

You can test it with:

```bash
# dig mail.jacobwmeadows.com +short
63.135.188.11

# dig -x 63.135.188.11 +short
host-63-135-188-11.twlakes.net.
```

**Comment by JacobOkanta** [comment]
All of the mail domains do point to the same public IP address, and changing the records doesn't seem to have had an effect but there might not have been enough time for the records to propagate yet. As for the PTR record that is unfortunately not something that I can do. Though I do intend to use a relay for outgoing mail once the server is working properly so I think that won't be necessary? It's also possible that I move the mailserver to Digital Ocean once I've gotten the setup all figured out and working as expected.

**Comment by casperklein** [comment]
> Though I do intend to use a relay for outgoing mail once the server is working properly so I think that won't be necessary?

Take a look here: https://mailtrap.io/blog/ptr-record/

**Comment by JacobOkanta** [comment]
Thanks, I think I understand why it is important now, however that didn't quite answer all my questions. I had read that only the sending server would need to have a PTR record. So if using an SMTP relay for sending mail, then it wouldn't be an issue. Did I misunderstand or get some bad information?

**Comment by casperklein** [comment]
> So if using an SMTP relay for sending mail, then it wouldn't be an issue

I've never used a relay for sending emails, but yes, I think so. Just give it a try and see if it works 😉
