### ISSUE TITLE
[BUG] [10.1.1] High CPU usage caused by check-for-changes.sh

### ISSUE THREAD

**Issue by KowalskiPiotr98** [docker-mailserver/docker-mailserver#2154]
# Bug Report

After updating to v10.1.1 I'm seeing heavy CPU usage caused by `check-for-changes.sh`

## Context

![image](https://user-images.githubusercontent.com/56399446/131232335-87169b39-bc50-4a96-8bf2-70536d3510fa.png)

![image](https://user-images.githubusercontent.com/56399446/131232337-551d84d4-8fd4-4453-b323-d654869f4b6e.png)

This is what I'm seeing. The CPU usage graph shows a significant increase after an update to 10.1.1 and then a sudden drop once I've downgraded back to 10.1.0. Htop reported `check-for-changes.sh` as the process using the most CPU on the server at the time.

This is how `check-for-changes.sh` behaves on 10.1.0:
![image](https://user-images.githubusercontent.com/56399446/131232353-1ca20cf7-f225-4733-a420-eb5c310f0ed3.png)

There was no increase in mail traffic during that period of time so I don't believe it was caused by external factors.

### What is affected by this bug?

High CPU usage.

### When does this occur?

All the time on v10.1.1

### How do we replicate the issue?

1. Start the server on v10.1.1
2. Done

## Your Environment

- version: `v10.1.1`
- available RAM: `4GB`
- Docker version: `v20.10.8`
- docker-compose version: `v1.28.5`

### Environment Variables

```CFG
ENABLE_UPDATE_CHECK=1
UPDATE_CHECK_INTERVAL=1d
AMAVIS_LOGLEVEL=0
FAIL2BAN_BLOCKTYPE=drop
ONE_DIR=1
SPOOF_PROTECTION=1
ENABLE_CLAMAV=1
ENABLE_FAIL2BAN=1
POSTFIX_MAILBOX_SIZE_LIMIT=10737420000
PFLOGSUMM_TRIGGER=daily_cron
LOGWATCH_INTERVAL=daily
REPORT_RECIPIENT=1
ENABLE_SPAMASSASSIN=1
SPAMASSASSIN_SPAM_TO_INBOX=1
MOVE_SPAM_TO_JUNK=1
```
Above are the env variables that were not empty that I've either changed or am not sure what the default was. I haven't changed any settings before upgrading to v10.1.1 as well as before downgrading back to v10.1.0 so this isn't caused by a settings change.

### Relevant Stack Traces

I haven't noticed any abnormalities in the logs.

**Comment by NorseGaud** [comment]
Likely https://github.com/docker-mailserver/docker-mailserver/pull/2104

**Comment by mmjee** [comment]
I'm seeing this too, about 40% idle CPU usage. The container is running in a VM with 1C/2T vCPU, 2GB of RAM, the volumes are are on a HDD.

Downgrading to 10.1.0 fixes the issue.

**Comment by casperklein** [comment]
Temporary quick fix: `docker exec mailserver supervisorctl stop changedetector`

This will disable check-for-changes. Impact: You cannot add/remove mail addresses/aliases etc while DMS is running.

**Comment by NorseGaud** [comment]
I wouldn't necessarily consider this a bug -- Functionality is not broken, the new logic simply uses more resources on the host.

**Comment by KowalskiPiotr98** [comment]
> Likely #2104
> Lots of parallelism now. What are the specs for the host?

My host is 2 vCPU (2x2.4 GHz) and 4GB RAM

**Comment by mmjee** [comment]
I don't think 40% idle CPU usage can be considered reasonable for the 
change detector, especially since the previous implementation took an 
order of a magnitude less resources.

**Comment by NorseGaud** [comment]
> I don't think 40% idle CPU usage can be considered reasonable for the change detector, especially since the previous implementation took an order of a magnitude less resources.

I think we have a few things going on at the moment:

1. The change in 2104 should have been for a minor release version
2. We should have vetted and tested the changes more before merging them in.

I'll chat with the other maintainers as I think this change should be reverted until the two above conditions are met.

**Comment by NorseGaud** [comment]
@mmjee @KowalskiPiotr98 

https://github.com/docker-mailserver/docker-mailserver/releases/tag/v10.1.2

Sorry about the trouble! Thanks for the report. We'll be sure the resource usage of the eventual change to the check-for-changes is minimal once it's eventually released.
