### ISSUE TITLE
Recommended way of user changing own passwords

### ISSUE THREAD

**Issue by s0ftcorn** [docker-mailserver/docker-mailserver#2162]
# Subject
Other

## Description

What is the recommended way of letting users change their own password? There seem to be a few loose ends of issues in this repo but i couldnt find any real solution. Of course using LDAP would solve this, and im using exactly this in another instance. But for this specific use-case i would like to not use LDAP for the mailboxes.

**Comment by NorseGaud** [comment]
There is a web UI project in the works (feel free to help moving it forward in development): https://github.com/docker-mailserver/docker-mailserver-admin)

**Comment by georglauterbach** [comment]
I will close this issue because it is being worked on in another repository :)
