### ISSUE TITLE
[BUG] Docker build fails

### ISSUE THREAD

**Issue by michaeljensen** [docker-mailserver/docker-mailserver#2163]
# Bug Report

## Context

Build from Dockerfile fails with error on step 42

### How do we replicate the issue?
Using a clean checkout from git and the master branch, run `docker build --no-cache .`
The error also occurs with v10.1.2

### Actual Behavior
```
Step 42/72 : COPY   ./target/bin/*   ./target/scripts/*.sh   ./target/scripts/startup/*.sh   ./target/docker-configomat/configomat.sh   /usr/local/bin/
COPY failed: file not found in build context or excluded by .dockerignore: stat target/docker-configomat/configomat.sh: file does not exist
```
No errors or warnings are reported prior to the message above.

### Expected Behavior
Successful build

## Your Environment
Docker version 20.10.7, build f0df350

**Comment by NorseGaud** [comment]
Hi, you need to `git submodule update --init --recursive`

**Comment by casperklein** [comment]
All in one: `git clone --recurse-submodules https://github.com/docker-mailserver/docker-mailserver`

**Comment by michaeljensen** [comment]
Yup, that did it!
Is that documented anywhere for those wanting to build their own docker image?  I couldn't find it.
I also couldn't find general instructions for building your own docker image.

**Comment by casperklein** [comment]
> Is that documented anywhere for those wanting to build their own docker image? I couldn't find it.

Not that I am aware of. There is [this](https://docker-mailserver.github.io/docker-mailserver/edge/contributing/issues-and-pull-requests/#submit-a-pull-request), but that does not directly aim building DMS.

If you would like to improve our [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/), feel free to do so. That would be awesome 😃

**Comment by michaeljensen** [comment]
Definitely!  I'll get a pull request together for "Building your own Docker image"

Even though it's a pretty simple process, I think it will fit well as a new page under the tutorials section. <https://docker-mailserver.github.io/docker-mailserver/edge/examples/tutorials/basic-installation/#building-a-simple-mailserver> 
But I'm open to feedback as to where it would live, in case someone thinks it should be somewhere else.

**Comment by casperklein** [comment]
Or a page on it's own: tutorials/build-own-image

@polarathene @wernerfred Suggestions?

**Comment by michaeljensen** [comment]
Yes, I was thinking its own page, but I couldn't link to a general tutorials page :-)

**Comment by polarathene** [comment]
> @polarathene @wernerfred Suggestions?

I actually had something in the works long ago, but I'm all for someone getting something into the docs :joy: 

Most aren't likely to build their own docker image, so a separate page seems fine. I was going to have it a contributor / testing section as I didn't think users would be interested in such, under the examples/tutorials section seems fine as it's own page.
