### ISSUE TITLE
Dockerbuild fails. Also it looks like the setup app inside the image is missing in a lot of the versions on dockerhub

### ISSUE THREAD

**Issue by dinocore1** [docker-mailserver/docker-mailserver#2184]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

Docker build fails. Missing file target/docker-configomat/configomat

### What happened and when does this occur?

```Markdown
Docker build fails:


$ docker build .
...
Step 42/72 : COPY   ./target/bin/*   ./target/scripts/*.sh   ./target/scripts/startup/*.sh   ./target/docker-configomat/configomat.sh   /usr/local/bin/                                                                               COPY failed: file not found in build context or excluded by .dockerignore: stat target/docker-configomat/configomat.
sh: file does not exist
```

### What did you expect to happen?

```Markdown
Docker to successfully build image
```

### How do we replicate the issue?

```Markdown
1. git clone
2. docker build .
3. FAIL!
```

### DMS version

all versions!

### How much RAM is available to DMS explicitly?

more than 4GB

### How many CPU cores are available?

more than 4 Cores

### Is DMS running in a virtualized environment?

... a physical host (with real, physical CPU cores, i.e. bare metal)

### What operating system is DMS running on?

Linux

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### I/O - Persistent memory

its an ssd bro

### What container orchestration tool are you using?

Docker

### The output of `uname -a`

inux homedesktop 5.4.0-81-generic #91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### What level of experience do you have with Docker and mail servers?

Trust me, I'm a (computer) engineer! [expert]

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by NorseGaud** [comment]
Update the submodules

**Comment by NorseGaud** [comment]
May help: https://github.com/docker-mailserver/docker-mailserver/pull/2164
