### ISSUE TITLE
starting container process caused: exec: "setup": executable file not found in $PATH: unknown

### ISSUE THREAD

**Issue by Margular** [docker-mailserver/docker-mailserver#2185]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

setup.sh

### What happened and when does this occur?

```Markdown
☁  docker-mailserver  ./setup.sh
OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "setup": executable file not found in $PATH: unknown
```

### What did you expect to happen?

```Markdown
setup.sh works
```

### How do we replicate the issue?

```Markdown
DMS_GITHUB_URL='https://raw.githubusercontent.com/docker-mailserver/docker-mailserver/master'
wget "${DMS_GITHUB_URL}/docker-compose.yml"
wget "${DMS_GITHUB_URL}/mailserver.env"
wget "${DMS_GITHUB_URL}/setup.sh"

chmod a+x ./setup.sh
./setup.sh help
```

### DMS version

v10.1.2

### How much RAM is available to DMS explicitly?

less than 1GB (very low)

### How many CPU cores are available?

less than 1 Core

### Is DMS running in a virtualized environment?

... a virtual private server (VPS) (with virtual CPU cores)

### What operating system is DMS running on?

Linux

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### I/O - Persistent memory

Docker

### What container orchestration tool are you using?

Docker Compose

### The output of `uname -a`

Linux ecs 5.4.0-84-generic #94-Ubuntu SMP Thu Aug 26 20:27:37 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by casperklein** [comment]
We are just migrating to a new `setup.sh` approach.

Download and use this version, until the next release: https://raw.githubusercontent.com/docker-mailserver/docker-mailserver/4755b16b312d9ac7f814ef7a8b62dba5251663c1/setup.sh

@docker-mailserver/maintainers Maybe we should "bring back" the old setup.sh version, until the next release.

**Comment by georglauterbach** [comment]
Yes. We should release `v10.2.0` immediately after all PRs for this milestone are merged.

**Comment by dinocore1** [comment]
I don't understand. Its like the setup script is missing inside the container:

```
paul@web1:~$ docker run --rm -it docker-mailserver bash
root@20b3e4de5929:/# ls /usr/local/bin
addalias      addsaslpassword	    configomat.sh     delalias	   excluderelaydomain	fetchmailrc_split    listalias	    open-dkim		postsrsd-wrapper.sh	    restrict-access  setup-stack.sh	  updatemailuser
addmailuser   check-for-changes.sh  daemons-stack.sh  delmailuser  fail2ban		fixes-stack.sh	     listmailuser   postfix-summary	quota-warning.sh	    setquota	     start-mailserver.sh  virus-wiper
addrelayhost  check-stack.sh	    debug-fetchmail   delquota	   fail2ban-wrapper.sh	helper-functions.sh  misc-stack.sh  postfix-wrapper.sh	report-pflogsumm-yesterday  setup-fetchmail  update-check.sh
root@20b3e4de5929:/#
```

Note that `setup` is missing.

**Comment by dinocore1** [comment]
using this setup script seems to work: https://raw.githubusercontent.com/docker-mailserver/docker-mailserver/4755b16b312d9ac7f814ef7a8b62dba5251663c1/setup.sh

**Comment by dinocore1** [comment]
using this setup script seems to work: https://raw.githubusercontent.com/docker-mailserver/docker-mailserver/4755b16b312d9ac7f814ef7a8b62dba5251663c1/setup.sh

**Comment by polarathene** [comment]
While we did make a change to how `setup.sh` is handled, the [README does clearly inform you about the change from the upcoming v10.2 release](https://github.com/docker-mailserver/docker-mailserver#get-the-tools). However, [our `edge` docs drop the note about previous versions](https://github.com/docker-mailserver/docker-mailserver/pull/2174/files#diff-b3f580a23248c71361b2250edc63d21eb9cedc9feaeb81cae08dfcb8c5a9d662L18), but if you [viewed the versioned docs for earlier versions](https://docker-mailserver.github.io/docker-mailserver/v10.1/config/setup.sh/), such as the v10.1 that you're using, you would see the `info` note on the top of that page (_we should have made it a more noticeable warning in all fairness_), which instructs you to use the `setup.sh` from the same tagged release you're using.

Once we have v10.2 available, that confusing gotcha/hassle will no longer need to be worried about :)
