### ISSUE TITLE
[BUG] Wrong IP adrress

### ISSUE THREAD

**Issue by mforbak** [docker-mailserver/docker-mailserver#2191]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

fail2ban

### What happened and when does this occur?

When connecting to SMTP using IPv4 connection, IP address is correctly logged

**telnet mail.domain.com 25** results in

```
mail_1  | Sep 14 09:01:46 mail postfix/postscreen[1128]: CONNECT from [87.197.107.210]:46096 to [172.24.0.3]:25
mail_1  | Sep 14 09:01:46 mail postfix/postscreen[1128]: PASS OLD [87.197.107.210]:46096
mail_1  | Sep 14 09:01:46 mail postfix/smtpd[1129]: connect from unknown[87.197.107.210]
mail_1  | Sep 14 09:01:57 mail postfix/smtpd[1129]: disconnect from unknown[87.197.107.210] quit=1 commands=1
```

But when connection is made using IPv6 network, I could only see the docker virtual IP address

**telnet -6 mail.domain.com 25** results in

```
mail_1  | Sep 14 09:07:56 mail postfix/postscreen[4099]: CONNECT from [172.24.0.1]:42164 to [172.24.0.3]:25
mail_1  | Sep 14 09:07:56 mail postfix/postscreen[4099]: PASS OLD [172.24.0.1]:42164
mail_1  | Sep 14 09:07:56 mail postfix/smtpd[4112]: connect from unknown[172.24.0.1]
mail_1  | Sep 14 09:07:57 mail postfix/smtpd[4112]: disconnect from unknown[172.24.0.1] quit=1 commands=1
```

Container started with docker-compose following the example configuration https://github.com/docker-mailserver/docker-mailserver#examples

### What did you expect to happen?

```Markdown
I except to see my IPv6 address.

The container is not able to recognize address from IPv6 connection which could ends up with ban for docker private IP address (when using fail2ban).
```

### How do we replicate the issue?

```Markdown
The simplest way to replicate is using telnet and looks inside the logs.

telnet -6 mail.domain.com 25
```

### DMS version

latest

### How much RAM is available to DMS explicitly?

more than 4GB

### How many CPU cores are available?

less than 4 Cores

### Is DMS running in a virtualized environment?

... a physical host (with real, physical CPU cores, i.e. bare metal)

### What operating system is DMS running on?

Linux

### What instruction set architecture is DMS running on?

ARM v7

### I/O - Persistent memory

docker volume bind on ext4

### What container orchestration tool are you using?

Docker Compose

### Docker version

Docker version 20.10.8, build 3967b7d

### Docker Compose version

docker-compose version 1.21.0, build unknown

### The output of `uname -a`

Linux raspberrypi 5.10.52-v7l+ #1441 SMP Tue Aug 3 18:11:56 BST 2021 armv7l GNU/Linux

### Relevant log output

```shell
mail_1  | Sep 14 09:07:56 mail postfix/postscreen[4099]: CONNECT from [172.24.0.1]:42164 to [172.24.0.3]:25
mail_1  | Sep 14 09:07:56 mail postfix/postscreen[4099]: PASS OLD [172.24.0.1]:42164
mail_1  | Sep 14 09:07:56 mail postfix/smtpd[4112]: connect from unknown[172.24.0.1]
mail_1  | Sep 14 09:07:57 mail postfix/smtpd[4112]: disconnect from unknown[172.24.0.1] quit=1 commands=1
```

### Other relevant information

**network_mode: host** solved the issue, but with this option I cannot connect to DMS container from other containers...so it is not preferable solution.

### What level of experience do you have with Docker and mail servers?

I know the basics, I've used Docker before [novice]

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by georglauterbach** [comment]
As stated [in our documentation on IPv6](https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/ipv6/), this is expected behavior because Docker does an IP64NAT.
