### ISSUE TITLE
Network_mode: host, is not working in docker mailserver

### ISSUE THREAD

**Issue by zOthix** [docker-mailserver/docker-mailserver#2194]
# Subject

I would like some feedback concerning a use case

## Description

I am trying to implement docker mail server for multiple IP addresses, for that i am trying to use docker host network, 
if i use network_mode : host, i get the following error

``` 
mailserver    | hostname: Name or service not known
mailserver    | hostname: Name or service not known
mailserver    | [ TASKLOG ]  Welcome to docker-mailserver 10.1.2
mailserver    | [ TASKLOG ]  Initializing setup
mailserver    | [ TASKLOG ]  Checking configuration
mailserver    | [  ERROR  ]  Setting hostname/domainname is required
mailserver    | [  ERROR  ]  Shutting down..
mailserver    | [  FATAL  ]  Please fix your configuration. Exiting...
mailserver    | 2021-09-15 03:30:58,267 WARN received SIGTERM indicating exit request
```

it works perfectly fine if i dont use network_mode: host, as i have already defined hostname and domainname as documented

**Comment by georglauterbach** [comment]
This is a possible bug. Please use the official issue template for bugs (you can't do that with the app yet, you'll need a browser). You description lacks information needed to resolve the problem - that's what the bug template is for:)

**Comment by polarathene** [comment]
Your problem was when using network host mode, `/etc/hosts` in the container is a copy of the docker daemon hosts `/etc/hosts`, this lacks an entry for your container IP with the FQDN (`hostname` or `hostname`+`domainname`).

If you add that, you should not have the error :)
