### ISSUE TITLE
[NOT-A-BUG] setup.sh prints error

### ISSUE THREAD

**Issue by MrCapsLock** [docker-mailserver/docker-mailserver#2203]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

setup.sh don't work

### What happened and when does this occur?

```Markdown
If latest image doesn't exist, It will pull it then this message will show:
[dumb-init] setup: No such file or directory
```

### What did you expect to happen?

```Markdown
show help of setup file
```

### How do we replicate the issue?

```Markdown
1. Make sure you installed latest docker version and latest docker-compose
2. Download latest setup.sh file from github
3. Make sure delete docker-mailserver image
4. Run ./setup.sh help
```

### DMS version

latest

### How much RAM is available to DMS explicitly?

less than 2GB

### How many CPU cores are available?

less than 2 Cores

### Is DMS running in a virtualized environment?

... a virtual private server (VPS) (with virtual CPU cores)

### What operating system is DMS running on?

Linux

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### I/O - Persistent memory

Default one of docker-compose on github on ext4

### What container orchestration tool are you using?

Docker Compose

### Docker version

Docker version 20.10.8, build 3967b7d

### Docker Compose version

docker-compose version 1.29.2, build 5becea4c

### The output of `uname -a`

Linux mail 5.4.0-84-generic #94-Ubuntu SMP Thu Aug 26 20:27:37 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### What level of experience do you have with Docker and mail servers?

I have experience with mail servers, but less experience working with containers

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by jessec** [comment]
Got the same problem. Also when I have a container running setup.sh gives me "OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "setup": executable file not found in $PATH: unknown" on all commands.

**Comment by jessec** [comment]
This started this morning yesterday everything was ok.

**Comment by georglauterbach** [comment]
This is expected behavior, as the README states:

>setup.sh for Docker Mailserver version `v10.1.x` and below
>
> If you're using Docker Mailserver version `v10.1.x` or below, you will need to get setup.sh with a specific version. Substitute <VERSION> with the mail server version you're using: `wget https://raw.githubusercontent.com/docker-mailserver/docker-mailserver/<VERSION>/setup.sh`.

Ans since you're using `:latest`, which currently translates into `v10.1.2`, you're seeing this error. Either use `:edge` or use the correct version of `setup.sh`!

**Comment by MrCapsLock** [comment]
> _**This is expected behavior**_, as the README states:
> 
> > setup.sh for Docker Mailserver version `v10.1.x` and below
> > If you're using Docker Mailserver version `v10.1.x` or below, you will need to get setup.sh with a specific version. Substitute  with the mail server version you're using: `wget https://raw.githubusercontent.com/docker-mailserver/docker-mailserver/<VERSION>/setup.sh`.
> 
> And since you're using `:latest`, which currently translates into `v10.1.2`, you're seeing this error. Either use `:edge` or use the correct version of `setup.sh`!
> 
> > BTW: I couldn't use wget https://raw.githubusercontent.com/docker-mailserver/docker-mailserver/10.1.2/setup.sh
> 
> Yes, because you're missing the `v` in the version.

But I'm using the latest version of both (setup.sh and docker image), What about that?

**Comment by georglauterbach** [comment]
> > _**This is expected behavior**_, as the README states:
> > > setup.sh for Docker Mailserver version `v10.1.x` and below
> > > If you're using Docker Mailserver version `v10.1.x` or below, you will need to get setup.sh with a specific version. Substitute  with the mail server version you're using: `wget https://raw.githubusercontent.com/docker-mailserver/docker-mailserver/<VERSION>/setup.sh`.
> > 
> > 
> > And since you're using `:latest`, which currently translates into `v10.1.2`, you're seeing this error. Either use `:edge` or use the correct version of `setup.sh`!
> > > BTW: I couldn't use wget https://raw.githubusercontent.com/docker-mailserver/docker-mailserver/10.1.2/setup.sh
> > 
> > 
> > Yes, because you're missing the `v` in the version.
> 
> But I'm using the latest version of both (setup.sh and docker image), What about that?

The latest version of `setup.sh` is the one on `master` which translates into the `:edge` tag for the image, which is a mismatch. Please read the README carefully, especially the tagging convention...

**Comment by georglauterbach** [comment]
This issue will be resolved when `v10.2.0` is released. Until then, you'll need to be on the lookout:) After the new release, everything is basically "back to normal".

**Comment by polarathene** [comment]
Perhaps the docs warning about the change should give instructions with v10.1.2 release, and link to `setup.sh` from that release commit? We can say to replace `v10.1.2` with an earlier version for those that are using something older still, instead of `<VERSION>`, might be easier for users, especially new ones not as familiar with the project and docs atm?

---

For the users running into this issue, as mentioned, once we've made the 10.2 release it'll no longer be a problem. That release will remove the requirement to keep the `setup.sh` matching the release version which has often been a hassle in the past.

**Comment by polarathene** [comment]
@georglauterbach actually, I think a common mistake will be made by users attempting to follow [this guide](https://docker-mailserver.github.io/docker-mailserver/edge/examples/tutorials/basic-installation/) we have that was community contributed from the wiki before we migrated to proper docs site.

I've got heavy revisions to this via PR soon, but just in case other other reports are raised, I wouldn't be surprised if they're jumping straight to that page to get something going. I did a search for `basic-installation` over the git repo and it doesn't appear we have any other references to it. It still might be discovered browsing docs or third-party sites might link directly to it though.

**Comment by georglauterbach** [comment]
@polarathene You're right, indeed. But as you're coming up with a bigger docs-PR, I wouldn't change the status quo as of now myself but wait for you to create the PR :)

**Comment by idfxken** [comment]
Just fyi, ran into this with the github README, not the guide.

https://github.com/docker-mailserver/docker-mailserver/tree/master#usage

relevant part that caused the issue, seems to pull different versions?
```
DMS_GITHUB_URL='https://raw.githubusercontent.com/docker-mailserver/docker-mailserver/master'
wget "${DMS_GITHUB_URL}/docker-compose.yml"
wget "${DMS_GITHUB_URL}/mailserver.env"
wget "${DMS_GITHUB_URL}/setup.sh"

```
