### ISSUE TITLE
Thunderbird cannot move or delete certain folders

### ISSUE THREAD

**Issue by chongma** [docker-mailserver/docker-mailserver#2208]
# Subject

Other

## Description

When I set up docker mailserver I copied existing users IMAP mailboxes into the data directory for the domain.tld.  I have just noticed that some (not all) of the directories have the wrong permissions and cannot be moved or deleted.  I can move the messages out of the folder into a new folder.

What is the best way to reset the permissions to standard on a mailbox so that everything works again?

```
The current command did not success.  The mail server for account username@domain.tld responded: [CANNOT] Renaming not supported across conflicting directory permissions
```

**Comment by casperklein** [comment]
What is the output of

`docker exec mailserver ls -l /var/mail`
`docker exec mailserver ls -ln /var/mail`

**Comment by chongma** [comment]
@casperklein 
all folders have
docker docker
5000 5000

**Comment by casperklein** [comment]
Looks good. Also the including files?

**Comment by casperklein** [comment]
You could try, instead of copying the files on the host, to import your emails via your mail client. That way, there should hopefully no permission problems.

**Comment by chongma** [comment]
Looking at a listing of my mailbox showing hidden files some of the directories have a big 'S' and some have a little 's'.  It seems like the ones with a big 'S' cannot be moved or deleted. 

![Screenshot from 2021-09-30 12-54-23](https://user-images.githubusercontent.com/6253322/135442692-9e48e11e-6e9b-4c67-b459-de5fa8a4c6d1.png)
