### ISSUE TITLE
Multiple domains with own certificates

### ISSUE THREAD

**Issue by cschmatzler** [docker-mailserver/docker-mailserver#2219]
# Subject

I would like some feedback concerning a use case

## Description

Hi! 
I am trying to set up a container right now and would like to bring my own TLS certificates. Following the docs, I can use 

```
environment:
  - SSL_TYPE=manual
  # Values should match the file paths inside the container:
  - SSL_CERT_PATH=/tmp/dms/custom-certs/public.crt
  - SSL_KEY_PATH=/tmp/dms/custom-certs/private.key
```

... for one domain. I haven't found a way to pass multiple certificates this way. Using multiple domains, e.g. example.com and example.net with two different certificates does not seem supported. Am I missing a configuration here or do I need to hack my way around it?

Cheers

**Comment by casperklein** [comment]
For the record: A SAN certificate is what you are looking for.
