### ISSUE TITLE
Problem with logrotate / clamav

### ISSUE THREAD

**Issue by mholti** [docker-mailserver/docker-mailserver#2230]
Hi,
i've got the following problem:
my /var/log/mail (mounted from host-fs) has 777-permissions. Because of this i get following message from logrotate:
> error: skipping "/var/log/mail/clamav.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.

when i set the permissions to 700 logrotate works but clamav can't run:

>ERROR: Problem with internal logger (UpdateLogFile = /var/log/mail/freshclam.log).
>ERROR: initialize: libfreshclam init failed.
>ERROR: Initialization error!
>ERROR: Can't open /var/log/mail/freshclam.log in append mode (check permissions!).

What permissions should /var/log/mail have?
Thanks in advance
Michael

**Comment by casperklein** [comment]
```
drwxr-xr-x 2 syslog root /var/mail

-rw-r----- 1 clamav adm  /var/mail/clamav.log
-rw-r----- 1 clamav adm  /var/mail/freshclam.log
-rw-r----- 1 root   adm  /var/mail/mail.err
-rw-r----- 1 root   adm  /var/mail/mail.info
-rw-r----- 1 root   adm  /var/mail/mail.log
-rw-r----- 1 root   adm  /var/mail/mail.warn
```

However, on container start the necessary permissions should be set automatically: https://github.com/docker-mailserver/docker-mailserver/blob/e4eca00b252ce59e0e3c1e7f59ebccd11b2461c1/target/scripts/startup/setup-stack.sh#L89-L105

If this does not work for you, open a separate issue and provide all necessary information the template asks for 😉

**Comment by georglauterbach** [comment]
This is a possible bug. Please use the correct template:)

**Comment by mholti** [comment]
Thanks to casperklein and georglauterbach.
I restarted the server to give it a chance to repair permssions. I'll fill the template if one of the errors occurs again.
