### ISSUE TITLE
[NOT A BUG] Spamassassin isn't doing anything

### ISSUE THREAD

**Issue by winks** [docker-mailserver/docker-mailserver#2231]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

spamassassin

### What happened and when does this occur?

```Markdown
spam mails don't have a spamassassin rating (not even a good one), 
no useful log entries for spamassassin
```

### What did you expect to happen?

```Markdown
I expected SA to work like it did before the upgrade, at least adding SOME headers, 
and some output why it doesn't do anything.
```

### How do we replicate the issue?

```Markdown
Upgrade to 10.1.2
```

### DMS version

v10.1.2

### How much RAM is available to DMS explicitly?

more than 4GB

### How many CPU cores are available?

more than 4 Cores

### Is DMS running in a virtualized environment?

... a virtual private server (VPS) (with virtual CPU cores)

### What operating system is DMS running on?

Linux

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### I/O - Persistent memory

-

### What container orchestration tool are you using?

Docker Compose

### Docker version

Docker version 20.10.8, build 3967b7d

### Docker Compose version

Docker version 20.10.8, build 3967b7d

### The output of `uname -a`

Linux asdf 4.15.0 #1 SMP Thu Apr 22 16:18:59 MSK 2021 x86_64 x86_64 x86_64 GNU/Linux

### Important environment variables

```bash
OVERRIDE_HOSTNAME=MYHOST.EXAMPLE.ORG
ONE_DIR=1
ENABLE_SASLAUTHD=1
SASLAUTHD_MECHANISMS=rimap
SASLAUTHD_MECH_OPTIONS=MYHOST.EXAMPLE.ORG

ENABLE_MANAGESIEVE=1
DMS_DEBUG=1
ENABLE_SPAMASSASSIN=1
# deliver spam messages in the inbox (eventually tagged using SA_SPAM_SUBJECT)
SPAMASSASSIN_SPAM_TO_INBOX=1
# spam messages will be moved in the Junk folder (SPAMASSASSIN_SPAM_TO_INBOX=1 required)
MOVE_SPAM_TO_JUNK=1
SA_SPAM_SUBJECT=***SPAM*****
SA_TAG=2.0
SA_TAG2=6.31
SA_KILL=6.31


ENABLE_CLAMAV=0
# Amavis content filter (used for ClamAV & SpamAssassin)
ENABLE_AMAVIS=0
AMAVIS_LOGLEVEL=0
```

### Relevant log output

```shell
DMS_DEBUG=1
ENABLE_SPAMASSASSIN=1
SPAMASSASSIN_SPAM_TO_INBOX=1
[[  INF  ]]  Enabling and configuring spamassassin
[[  INF  ]]  Configure Spamassassin/Amavis to put SPAM inbox
-esa-update-keys [[  \e[34mINF\e[0m  ]]  Moving contents of /var/lib/spamassassin to /var/mail-state/lib-spamassassin:

===============================
daily mail report, interestingly it runs amavisd although that was disabled on OLD and NEW version of my config:

/etc/cron.daily/spamassassin:
run-parts: /etc/spamassassin/sa-update-hooks.d/amavisd-new exited with return code 3
run-parts: /etc/cron.daily/spamassassin exited with return code 1
===============================
Example anonymized spam mail:

Return-Path: <apache@cpsv01.compart.com.br>
Delivered-To: USER@EXAMPLE.ORG
Received: from MYHOST.EXAMPLE.ORG
    by MYHOST.EXAMPLE.ORG with LMTP
    id +0CMAe3WVmGfMgAAmEI3ig
    (envelope-from <apache@cpsv01.compart.com.br>)
    for <USER@EXAMPLE.ORG>; Fri, 01 Oct 2021 09:37:49 +0000
Received-SPF: Pass (mailfrom) identity=mailfrom; client-ip=179.191.121.116; helo=cpsv01.compart.com.br; envelope-from=apache@cpsv01.compart.com.br; receiver=<UNKNOWN>
Authentication-Results: 'MYHOST.EXAMPLE.ORG'; dmarc=pass (p=none dis=none) header.from=compart.com.br
Received: from cpsv01.compart.com.br (cpsv01.compart.com.br [179.191.121.116])
    by MYHOST.EXAMPLE.ORG (Postfix) with ESMTPS id A9BF6444AF0
    for <bugs@EXAMPLE.ORG>; Fri, 1 Oct 2021 09:37:47 +0000 (UTC)
Received: from apache by cpsv01.compart.com.br with local (Exim 4.88)
    (envelope-from <apache@cpsv01.compart.com.br>)
    id 1mWEz5-000Yud-03
    for bugs@EXAMPLE.ORG; Fri, 01 Oct 2021 06:37:39 -0300
To: bugs@EXAMPLE.ORG
Subject: Business Proposal
X-PHP-Originating-Script: 48:mic.php
Date: Fri, 1 Oct 2021 06:37:38 -0300
From: Simmons Mark Robert <support@compart.com.br>
Reply-To: sm.robert@sechserconsulting.org
Message-ID: <c64fae5d77cf189ccec5ab5e50d4b88a@compart.com.br>
MIME-Version: 1.0
Content-Type: multipart/alternative;
    boundary="b1_c64fae5d77cf189ccec5ab5e50d4b88a"
Content-Transfer-Encoding: 8bit
Sender: Apache <apache@cpsv01.compart.com.br>
```

### Other relevant information

```Markdown
I upgraded from an older version (I think it was an 8.x stable, but it didn't show it) 
to 10.1.2 and everything works fine, except spamassassin.

At first I used my old `docker-data/dms/mail-state/lib-spamassassin` folder 
(moved from mailstate/spamassassin or whatever it was called), when that didn't work I did this:


docker-compose down
rm -rf docker-data/dms/mail-state/lib-spamassassin
docker-compose up -d


No change at all.

I don't think this is related to #2123 because I don't have LDAP and no amavisd.
I think my only meaningful changes from the default are SASL and SIEVE.
```

### What level of experience do you have with Docker and mail servers?

I know both pretty well actually [experienced]

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

### Improvements to this form?

```Markdown
Too many mandatory fields, I don't see how my docker/docker-compose version would have anything to do if a single component inside the container doesn't work. But not a big deal.
```

**Comment by casperklein** [comment]
Have you tried sending an email containing the [GTUBE](https://de.wikipedia.org/wiki/GTUBE) string?

`XJS*C4JDBQADN1.NSBN3*2IDNEN*GTUBE-STANDARD-ANTI-UBE-TEST-EMAIL*C.34X`

This should trigger spam detection in any case.

**Comment by winks** [comment]
Sorry, forgot to mention, had tried it and just tried again from a different host. No headers addded

**Comment by georglauterbach** [comment]
@winks do you think this is a regression from `v8.x.x`?

**Comment by winks** [comment]
@georglauterbach I don't know how to answer this, I guess yes.

  * I ran the image `5553976f0dc1` which didn't echo a version, but it was ~8 months ago and it was a `stable`, so I think it was an 8.x
  * spamassassin was working perfectly
  * I first migrateted my whole mail-state, but then deleted the spamassassin folder, no change in behaviour
  * zero useful debug output and SA is not working.

So regression yes, but doesn't even look like a migration issue

**Comment by casperklein** [comment]
> spam mails don't have a spamassassin rating (not even a good one)

I can confirm the second part, good mails don't have a rating in their headers in my setup too.

When sending the GTUBE string, I see:

```
X-Spam-Flag: YES
X-Spam-Score: 998.493
X-Spam-Level: ****************************************************************
X-Spam-Status: Yes, score=998.493 tagged_above=2 required=6.31
	tests=[ALL_TRUSTED=-1, BAYES_00=-1.9, GTUBE=1000, PYZOR_CHECK=1.392,
	TVD_SPACE_RATIO=0.001] autolearn=no autolearn_force=no
```

No that you mentioned it, I haven't got any SPAM mails for a long time. Reasons I can think of:

1. Spamers have put me on a blacklist 😄
2. Spam is filtered out, due to wrong SPF records
3. Spam is silently discarded

The 3rd one would be the worst for me.

**Comment by winks** [comment]
Full GTUBE  mail:

```
Return-Path: <XXX@gmail.com>
Delivered-To: USER@EXAMPLE.ORG
Received: from MYHOST.EXAMPLE.ORG
	by MYHOST.EXAMPLE.ORG with LMTP
	id vhqiClEFV2FADgAAmEI3ig
	(envelope-from <XXX@gmail.com>)
	for <USER@EXAMPLE.ORG>; Fri, 01 Oct 2021 12:55:45 +0000
Received-SPF: Softfail (mailfrom) identity=mailfrom; client-ip=172.22.0.1; helo=mail-wm1-x330.google.com; envelope-from=XXX@gmail.com; receiver=<UNKNOWN> 
Authentication-Results: 'MYHOST.EXAMPLE.ORG'; dmarc=fail (p=none dis=none) header.from=gmail.com
Authentication-Results: MYHOST.EXAMPLE.ORG;
	dkim=pass (2048-bit key; unprotected) header.d=gmail.com header.i=@gmail.com header.b="R27ziuCU";
	dkim-atps=neutral
Received: from mail-wm1-x330.google.com (unknown [172.22.0.1])
	by MYHOST.EXAMPLE.ORG (Postfix) with ESMTPS id 02E784449E8
	for <USER@EXAMPLE.ORG>; Fri,  1 Oct 2021 12:55:44 +0000 (UTC)
Received: by mail-wm1-x330.google.com with SMTP id t16-20020a1c7710000000b003049690d882so11148849wmi.5
        for <USER@EXAMPLE.ORG>; Fri, 01 Oct 2021 05:55:44 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20210112;
        h=mime-version:from:date:message-id:subject:to;
        bh=M+QoFZgXW0bqb6bolaenPVz+Hz9OgDNrvnMgnCoirnI=;
        b=R27ziuCUb+YDmFmpTloymcGKhR9w0fDHRytLLMdBWVgx2bTxtHYg4LVAAoQ55QacD4
         144gDg1vbx1o8w/i0s7kXBegDgV/Sd2/thztTE5u1lOp6NdT4St03ZKRknn0cWPdUnHB
         hG37z5fGz6i63Z3GBsZFsa7JtN/eYuSf0a56WpZuKBZfaLpWQsqSrPjb4e0bm3Dz8Apu
         3bQChkCHdmCjZOoFCJeSV++Dt7DWO1MKHPOwWzsWucYDdD57mXQ6XubZ7lPoouWw00FB
         lXpbnOBTNlD6Q7aM9h6ghswKmndFOkgAznjwXrG4+jFW8LmRUUFJvzig4PWU3zLMDRs5
         OljA==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20210112;
        h=x-gm-message-state:mime-version:from:date:message-id:subject:to;
        bh=M+QoFZgXW0bqb6bolaenPVz+Hz9OgDNrvnMgnCoirnI=;
        b=jpX5JGH5lQwFWMEAEy+h92T6BMbExxRcw+SmXFT4lq1kdeVhrUq/4GSq9TYaD7c1+f
         BQw1zSO5HY9RxSnTqRiJZM51zjyVosJpM8V6vXV7jS8/ATjBFcdysWZbh+zQ1NW4mwaD
         TRv9wxw2ulT/B2vSfpYTuCpAJAMef1lQ7xe16caalTtE5M0UDBwwoWFn3g2yp0/akeda
         X0huuVMLUeyGmpkKRfCD04IH4H2BPXh5CizQFAXMWvcyQNokg8Fwk4JojkQtge1OCOWb
         YbJSf1tCF6c6oTLvSoeGVd0vVv97dWl45P21VNF3uROpqiFPsJFFDdC+Mb8EGs7zKpGi
         9l7A==
X-Gm-Message-State: AOAM532MSxjDc/s2rDNHWvSR0MkvJauV4wvnwfLs6gc2nAX71Zp0KJns
	EK/Sb7+B3o2rpVDQgK6RU7Ac4b1Sql4LB9GvjyMuRxkZR28=
X-Google-Smtp-Source: ABdhPJxHYNW+2GvropkhpW1HsVJIsu+W5n/tBo+YTlAL8w7k8rV4hhw64V3imTXFFNML478lyZz8pAJ0bC9FBnvKEpk=
X-Received: by 2002:a05:600c:1c9e:: with SMTP id k30mr4221435wms.74.1633092944137;
 Fri, 01 Oct 2021 05:55:44 -0700 (PDT)
MIME-Version: 1.0
From: XXX <XXX@gmail.com>
Date: Fri, 1 Oct 2021 14:55:32 +0200
Message-ID: <CABjvGgwjoYKRRfzPnfcWWoUCgqwmnutRGst1S=AVsGPxOKH03g@mail.gmail.com>
Subject: ssss
To: USER@EXAMPLE.ORG
Content-Type: multipart/alternative; boundary="000000000000d210ae05cd4a1409"

--000000000000d210ae05cd4a1409
Content-Type: text/plain; charset="UTF-8"

XJS*C4JDBQADN1.NSBN3*2IDNEN*GTUBE-STANDARD-ANTI-UBE-TEST-EMAIL*C.34X

--000000000000d210ae05cd4a1409
Content-Type: text/html; charset="UTF-8"

<div dir="ltr"><p><code>XJS*C4JDBQADN1.NSBN3*2IDNEN*GTUBE-STANDARD-ANTI-UBE-TEST-EMAIL*C.34X</code></p></div>

--000000000000d210ae05cd4a1409--

```

**Comment by georglauterbach** [comment]
You said you deleted the Spamassasin folder. Why? And you're sure this did not have any impact?

**Comment by winks** [comment]
* on a fresh install it wouldn't be there
  * it didn't work in the first place after the upgrade so I thought maybe some format had changed or something went wrong.

As I said, zero difference between "pre-upgrade mail-state/lib-spamassassin" and "no folder" in the log output and functionality

**Comment by casperklein** [comment]
Have you fully restarted the container between your tests? `docker-compose down; docker-compose up`

We had issues in the past, where a simple docker stop / start was used.

**Comment by winks** [comment]
Yes. But I can try that again.

I also found it weird that running the spamassassin cronjob manually via `docker exec` took ages and didn't give any output.

**Comment by casperklein** [comment]
Pretty fast for me:

time docker exec -it mail bash -c '/etc/cron.daily/spamassassin'

real    0m1.914s
user    0m0.018s
sys     0m0.020s

I see no output too.

**Comment by winks** [comment]
I've not configured postfix for a while, but my `/etc/postfix/master.cf` in the container doesn't contain what I would expect in some form, namely the actual call

```
-o content_filter=spamassassin
spamassassin unix -     n       n       -       -       pipe
user=spamd argv=/usr/bin/spamc -f -e  
/usr/sbin/sendmail -oi -f ${sender} ${recipient}
```

actually:

```
# grep -ri spam /etc/postfix

/etc/postfix/main.cf:# Settings to prevent SPAM early
/etc/postfix/main.cf:smtpd_recipient_restrictions = permit_sasl_authenticated, permit_mynetworks, reject_unauth_destination, check_policy_service unix:private/policyd-spf, reject_unauth_pipelining, reject_invalid_helo_hostname, reject_non_fqdn_helo_hostname, reject_unknown_recipient_domain, reject_rbl_client zen.spamhaus.org
/etc/postfix/main.cf:# Postscreen settings to drop zombies/open relays/spam early
/etc/postfix/main.cf:postscreen_dnsbl_sites = zen.spamhaus.org*3
/etc/postfix/main.cf:   bl.spameatingmonkey.net
/etc/postfix/post-install:#    # mail relay policy from the spam blocking policy.

# grep -ri spam /etc/supervisor/
#
```

I would expect it to either be running as a daemon or on demand via master.cf.

**Comment by winks** [comment]
Also as I wrote above I have amavis disabled, but reading through the repo it looks as if SA and amavis are kinda intertwined.

Is Spamassassin actually supposed to work without amavis enabled?

**Comment by casperklein** [comment]
You quoted it yourself in the first post? --> "# Amavis content filter (used for ClamAV & SpamAssassin)"

So I would guess, Amavis is necessary for SA to work.

**Comment by winks** [comment]
Gonna try that tomorrow, thanks.

But: https://github.com/docker-mailserver/docker-mailserver/blob/master/CHANGELOG.md#v910

[feat] Introduce ENABLE_AMAVIS env (#1866) 

This is not listed as a breaking change, but I still have my old 8.x config here, there was no Amavis and **before that spamassassin worked on its own**.

**Comment by casperklein** [comment]
It's not listed, because it's not a breaking change. This introduced just the ability to disable amavis (default value is enabled). Before that, you could not disable amavis and it was enabled all the time.
So unless you explicitly set `ENABLE_AVAVIS=0`, it will be enabled.

**Comment by casperklein** [comment]
To have the X-SPAM headers added, configure a lower (negative) value:

https://github.com/docker-mailserver/docker-mailserver/blob/e4eca00b252ce59e0e3c1e7f59ebccd11b2461c1/mailserver.env#L242-L243

**Comment by winks** [comment]
enabling amavis and restarting (down/up) seems to have worked,

GTUBE:

```
X-Quarantine-ID: <JIRsM2n9CsjH>
X-Spam-Flag: YES
X-Spam-Score: 1001.457
X-Spam-Level: ****************************************************************
X-Spam-Status: Yes, score=1001.457 tagged_above=2 required=6.31
	tests=[ALL_TRUSTED=-1, BAYES_00=-1.9, DKIM_SIGNED=0.1,
	DKIM_VALID=-0.1, DKIM_VALID_AU=-0.1, DKIM_VALID_EF=-0.1,
	FREEMAIL_FROM=0.001, FSL_BULK_SIG=2.497, GTUBE=1000,
	HTML_MESSAGE=0.001, PYZOR_CHECK=1.392, SPF_SOFTFAIL=0.665,
	TVD_SPACE_RATIO=0.001] autolearn=no autolearn_force=no
```

Also I can see your reasoning that it's not a breaking change from your point of view, and my bad was not properly grasping the line `Amavis content filter (used for ClamAV & SpamAssassin)` but this was kinda new and if you know amavis only for the antivirus stuff and had never used it for anything related to spamassassin, it's kinda easy to miss. Sorry for the noise.

My suggestion would be add a single sentence to the CHANGELOG at 9.1: "Attention: For Spamassassin to continue to work, you need to enable amavis (defaults to on).

**Comment by casperklein** [comment]
I don't get your point "to continue to work". If you change nothing, nothing will break. When you, for whatever reason decide to pro-actively disable amavis, then you should be aware of the impact.

I will provide a patch to display a warning, when amavis is disabled and clamav/spamassassin is enabled.

**Comment by winks** [comment]
"continue to work" as in: I was using 8.x, which did not have amavis, only a working spamassassin.
Now a new component is added, which interacts with Spamassassin and is suddenly a prereq.

As I said, you can see this from both sides. It's definitely not a bug, but a caveat maybe?

Thanks for your work on dms in any case and sorry again for failing to read the instructions properly.

**Comment by casperklein** [comment]
> I was using 8.x, which did not have amavis

That is wrong! As I already said, amavis was there all the time. It just haven't an ENV to disable it.

Proof:

```
docker run --rm -it mailserver/docker-mailserver:8.0.0 dpkg -l amavisd-new

Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=======================================================
ii  amavisd-new    1:2.11.0-6.1 all          Interface between MTA and virus scanner/content filters

```

**Comment by winks** [comment]
Ok, apologies. It was **not exposed to the user** as a thing to be enabled or disabled, or I had removed it from my config (which I doubt). So it was there, but not visible.

As I said, purely my fault for misreading the new config that it's needed for SA. Maybe no one else will make that error in the future.
