### ISSUE TITLE
[NOT A BUG] Fresh 10.2.0 container crashes while booting: Failed to remove ClamAV configuration

### ISSUE THREAD

**Issue by MohammedNoureldin** [docker-mailserver/docker-mailserver#2232]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

ClamAV

### What happened and when does this occur?

```Markdown
When running a fresh container (no old mounted folders or files), the container crashes with the error:


[[  INF  ]]  Fixing Amavis permissions
[[ TASKS ]]  Cleaning up disabled ClamAV
rm: cannot remove '/etc/logrotate.d/clamav-*': No such file or directory
rm: cannot remove '/etc/cron.d/clamav-freshclam': No such file or directory
[  FATAL  ]  Failed to remove ClamAV configuration
[  ERROR  ]  Shutting down..
```
```


### What did you expect to happen?

```Markdown
The container should start normally
```

### How do we replicate the issue?

```Markdown
Just run the container using the settings below.
```

### DMS version

v10.2.0 (edge)

### How much RAM is available to DMS explicitly?

less than 2GB

### How many CPU cores are available?

less than 1 Core

### Is DMS running in a virtualized environment?

... a virtual private server (VPS) (with virtual CPU cores)

### What operating system is DMS running on?

Linux

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### I/O - Persistent memory

-

### What container orchestration tool are you using?

Docker Compose

### Docker version

Docker version 20.10.8, build 3967b7d

### Docker Compose version

docker-compose version 1.29.2, build 5becea4c

### The output of `uname -a`

Linux srv02 5.4.0-84-generic #94-Ubuntu SMP Thu Aug 26 20:27:37 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Important environment variables

```bash
DMS_DEBUG=1

POSTMASTER_ADDRESS=postmaster@MYDOMAIN.com

SSL_TYPE=manual
SSL_CERT_PATH=/etc/ssl/pki/mail.MYDOMAIN.com.crt
SSL_KEY_PATH=/etc/ssl/pki/mail.MYDOMAIN.com.key

ENABLE_LDAP=1
LDAP_START_TLS=yes
LDAP_SERVER_HOST=dc1.internal.MYDOMAIN.com
LDAP_SEARCH_BASE=dc=internal,dc=MYDOMAIN,dc=com
LDAP_BIND_DN=cn=Administrator,cn=users,dc=internal,dc=MYDOMAIN,dc=com
LDAP_BIND_PW=Ch@ngeMe
# Specifies how ldap should be asked for users.
LDAP_QUERY_FILTER_USER=(&(objectclass=person)(mail=%s))
# Specifies how ldap should be asked for groups.
LDAP_QUERY_FILTER_GROUP=(|)
# Specifies how ldap should be asked for aliases.
LDAP_QUERY_FILTER_ALIAS=(|)
# Specifies how ldap should be asked for domains.
LDAP_QUERY_FILTER_DOMAIN=(mail=*@%s)

DOVECOT_TLS=yes
DOVECOT_USER_FILTER=(&(objectclass=person)(sAMAccountName=%n))
DOVECOT_USER_ATTRS==uid=%{ldap:uidNumber},=gid=6000,=home=/var/mail/%Ln,=mail=maildir:~/Maildir
DOVECOT_PASS_ATTRS=sAMAccountName=user,userPassword=password
DOVECOT_AUTH_BIND=yes

ENABLE_SASLAUTHD=1
SASLAUTHD_MECHANISMS=ldap
SASLAUTHD_LDAP_SERVER=dc1.internal.MYDOMAIN.com
SASLAUTHD_LDAP_BIND_DN=cn=Administrator,cn=users,dc=internal,dc=MYDOMAIN,dc=com
SASLAUTHD_LDAP_SEARCH_BASE=dc=internal,dc=MYDOMAIN,dc=com
SASLAUTHD_LDAP_FILTER=(&(sAMAccountName=%U)(objectClass=person))
SASLAUTHD_LDAP_START_TLS=yes
SASLAUTHD_LDAP_TLS_CHECK_PEER=yes
SASLAUTHD_LDAP_TLS_CACERT_FILE=/etc/ssl/self-signed-pki/pki/ca.crt
```

### Relevant log output

```shell
[[  INF  ]]  Fixing Amavis permissions
[[ TASKS ]]  Cleaning up disabled ClamAV
rm: cannot remove '/etc/logrotate.d/clamav-*': No such file or directory
rm: cannot remove '/etc/cron.d/clamav-freshclam': No such file or directory
[  FATAL  ]  Failed to remove ClamAV configuration
[  ERROR  ]  Shutting down..
```

### Other relevant information

```Markdown
**(do NOT miss number 2 below)**

1. Find the **Docker-Compose** file below:

version: '3.9'
services:
  mailserver:
    container_name: mailserver
    image: docker.io/mailserver/docker-mailserver:edge # TODO change the TAG to 10.2.0 when released.
    hostname: mail
    domainname: ${PUBLIC_DOMAIN_NAME}
    # dns: 1.1.1.1
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    # More information about the mailserver ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
    networks:
      - internal01
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - mailserver-data:/var/mail/
      - mailserver-state:/var/mail-state/
      - mailserver-logs:/var/log/mail/
      - mailserver-config:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - publicly-trusted-pki:/etc/ssl/pki/:ro
    restart: always
    stop_grace_period: 1m
    cap_add: [ "NET_ADMIN", "SYS_PTRACE" ]
    env_file:
      - mailserver/mailserver.env
    environment:
      # The following variables will be passed from the .env (if exist) to override the variables in mailserver.env.
      - DMS_DEBUG
      - POSTMASTER_ADDRESS
      - SSL_TYPE
      - SSL_CERT_PATH
      - SSL_KEY_PATH
      - ENABLE_LDAP
      - LDAP_START_TLS
      - LDAP_SERVER_HOST
      - LDAP_SEARCH_BASE
      - LDAP_BIND_DN
      - LDAP_BIND_PW
      - LDAP_QUERY_FILTER_USER
      - LDAP_QUERY_FILTER_GROUP
      - LDAP_QUERY_FILTER_ALIAS
      - LDAP_QUERY_FILTER_DOMAIN
      - DOVECOT_TLS
      - DOVECOT_USER_FILTER
      - DOVECOT_USER_ATTRS
      - DOVECOT_PASS_ATTRS
      - DOVECOT_AUTH_BIND
      - ENABLE_SASLAUTHD
      - SASLAUTHD_MECHANISMS
      - SASLAUTHD_LDAP_SERVER
      - SASLAUTHD_LDAP_BIND_DN
      - SASLAUTHD_LDAP_SEARCH_BASE
      - SASLAUTHD_LDAP_FILTER
      - SASLAUTHD_LDAP_START_TLS
      - SASLAUTHD_LDAP_TLS_CHECK_PEER
      - SASLAUTHD_LDAP_TLS_CACERT_FILE


volumes:
  mailserver-data:
  mailserver-state:
  mailserver-logs:
  mailserver-config:

internal01 network and the volume of the public key are defined in another docker-compose.yml file. But this should not be an issue.

2. Make sure the container does not validate the CA in the ldap.conf file, as is seems that there is an issue here (the certificate seems to be refused even if it is valid). In simple words, execute the following on the host and this will do the job:

    docker exec mailserver sh -c 'echo "TLS_REQCERT   never" > /etc/ldap/ldap.conf'

```

### What level of experience do you have with Docker and mail servers?

Trust me, I'm a (computer) engineer! [expert]

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by georglauterbach** [comment]
Just tried a new container, all works well, and I cannot reproduce this issue...

**Comment by MohammedNoureldin** [comment]
> Just tried a new container, all works well, and I cannot reproduce this issue...
> 
> What does the output of `docker run --rm mailserver/docker-mailserver:edge ls -lh /etc/logrotate.d` show for you @msheakoski?

Did you try it with LDAP? If not, can this be only related to LDAP?

**Comment by MohammedNoureldin** [comment]
Hi @georglauterbach, just in case you are still not able to reproduce the error (which is weird, because I am not able to use the container because of it), do you suggest any workaround or anything I can do to get rid of it on my side, just to be able to continue using the container?

If you prefer, I can provide you an SSH connection to the server where this issue appears if that can help you somehow.

**Comment by casperklein** [comment]
> Could this be that this is only reproduceable when using LDAP?

I don't think so. The error occurs in the early startup phase. At this point, no daemons are started yet.

**Comment by MohammedNoureldin** [comment]
> > Could this be that this is only reproduceable when using LDAP?
> 
> I don't think so. The error occurs in the early startup phase. At this point, no daemons are started yet.

I don't know, but as I updated, I tried again on a completely clean server, though I still get the same error. I am not sure what the cause can be.

**Comment by casperklein** [comment]
> What does the output of docker run --rm mailserver/docker-mailserver:edge ls -lh /etc/logrotate.d show for you @msheakoski?

**Comment by MohammedNoureldin** [comment]
@casperklein for me:

```
root@srv02:~# docker run --rm mailserver/docker-mailserver:edge ls -lh /etc/logrotate.d
total 44K
-rw-r--r-- 1 root root 120 Apr 19  2019 alternatives
-rw-r--r-- 1 root root 173 Apr 19 16:41 apt
-rw-r--r-- 1 root root 130 Aug 28  2018 btmp
-rw-r--r-- 1 root root 383 Sep 26 08:43 clamav-daemon
-rw-r--r-- 1 root root 140 Sep 26 08:43 clamav-freshclam
-rw-r--r-- 1 root root 107 Aug 18  2019 dbconfig-common
-rw-r--r-- 1 root root 112 Apr 19  2019 dpkg
-rw-r--r-- 1 root root 354 Nov 23  2020 fail2ban
-rw-r--r-- 1 root root  88 Nov  1  2018 razor
-rw-r--r-- 1 root root 498 Sep 26 08:43 rsyslog
-rw-r--r-- 1 root root 145 Feb 19  2018 wtmp
```

**Comment by casperklein** [comment]
Looks good (normal).

**Comment by casperklein** [comment]
Do you have any customizations? like `config/user-patches.sh` etc?

**Comment by MohammedNoureldin** [comment]
I have no *user-patches* at the moment, and yes I am not mounting any host volumes, but rather a named volumes, to stay uncoupled with the directory of docker-compose.

The content is:

```
root@srv02:~/MyServer/Docker# ll /var/lib/docker/volumes/MyServer_mailserver-config/_data/
total 8
drwxr-xr-x 2 root root 4096 Oct  1 22:30 ./
drwx-----x 3 root root 4096 Oct  1 22:30 ../
-rw-r--r-- 1 root root    0 Oct  1 22:30 postfix-aliases.cf
```
Here I uploaded the whole log output, maybe that can help more to get the whole context:

[mailserver.log](https://github.com/docker-mailserver/docker-mailserver/files/7270031/mailserver.log)

**Comment by casperklein** [comment]
`rm: cannot remove '/etc/logrotate.d/clamav-*': No such file or directory` is not included in the log?

**Comment by MohammedNoureldin** [comment]
No it isn't, I reuploaded a simplified version of the log, where I just removed the duplications because of trying to restart the container. The line you mentioned is not in it.

**Comment by casperklein** [comment]
What is the rational behind this in your docker-compose.yml:
```

environment:
      # The following variables will be passed from the .env (if exist) to override the variables in mailserver.env.
      - DMS_DEBUG
      - POSTMASTER_ADDRESS
      - SSL_TYPE
      [..]
```

It overrides all settings set in your mailserver.env?!

**Comment by casperklein** [comment]
This works for me. I've just disabled the SSL stuff in mailserver.env: https://gist.github.com/casperklein/7ad20731e71c4c1fa179f16b53ea6ecd

**Comment by polarathene** [comment]
Could you try temporarily using bind mount volumes instead of named volumes? Probably won't make a difference but IIRC they don't always behave the same. I noticed `ONE_DIR` wasn't set, so on your previous version `ONE_DIR=0` and the new version `ONE_DIR=1` is going to differ between them, but I don't know why that'd cause the errors.

---

> What is the rational behind this in your docker-compose.yml

If a `.env` file (just the extension, no filename prefix) is by your `docker-compose.yml`, it will be available to the config to pass env vars selectively. That is in addition to a env file or setting env vars explicity.

**Comment by casperklein** [comment]
> Neither the line you mentioned nor any similar appear in it.

So then it works? Problem gone?

**Comment by casperklein** [comment]
> That is in addition to a env file or setting env vars explicity.

No.

**Comment by MohammedNoureldin** [comment]
> What is the rational behind this in your docker-compose.yml:
> 
> ```
> 
> environment:
>       # The following variables will be passed from the .env (if exist) to override the variables in mailserver.env.
>       - DMS_DEBUG
>       - POSTMASTER_ADDRESS
>       - SSL_TYPE
>       [..]
> ```
> 
> It overrides all settings set in your mailserver.env?!

My *mailserver.env* is just the default file in the repository without any changes (I am not sure if I need to provide it at all if it has no changes). The `environment` variables you mentioned are here to override only the variables mentioned in that list and available in my own *.env* file, where I have some domain specific values to configure not only for the mail server, but also for other services.

> So then it works? Problem gone?

No, I am not sure where that error is gone now, but I still have this anyway:
```
[  FATAL  ]  Failed to remove ClamAV configuration
[  ERROR  ]  Shutting down..
```

**Comment by polarathene** [comment]
> Neither the line you mentioned nor any similar appear in it.

You need to confirm that you're no longer having the container crash/shutdown anymore then. The troubleshooting effort was based on this. If you're still experiencing failure somewhere we need to know what is wrong this time.

---

> No. Variables defined in a `.env` are only available in docker-compose.yml itself and not in the container.

[It's valid syntax to pass them to container](https://docs.docker.com/compose/compose-file/compose-file-v3/#environment).

**Comment by casperklein** [comment]
Stop. Variables in the file `.env` are not passed to the container. However, the vars in mailserver.env are passed to the  container.

**Comment by casperklein** [comment]
> The environment variables you mentioned are here to override only the variables

This essentially unset all listed variables, because no values are provided.

**Comment by MohammedNoureldin** [comment]
After restarting the container I get the same error (not the short form):

```
[ TASKLOG ]  Post-configuration checks
[[ TASKS ]]  Checking /var/mail permissions
[[  INF  ]]  Permissions in /var/mail look OK
[[  INF  ]]  Fixing Amavis permissions
[[ TASKS ]]  Cleaning up disabled ClamAV
rm: cannot remove '/etc/logrotate.d/clamav-*': No such file or directory
rm: cannot remove '/etc/cron.d/clamav-freshclam': No such file or directory
[  FATAL  ]  Failed to remove ClamAV configuration
[  ERROR  ]  Shutting down..
```

@casperklein according to my tests they are passed to the container when they are mentioned. Any they can override the variables mentioned in the x.env files.

**Comment by casperklein** [comment]
If you manage your variables in a file (`mailserver.env`) or directly in `docker-compose.yml` is up to you. It makes no difference. But keep in mind, if you use both, one can override the other.

If you do all customization directly in `docker-compose.yml`, then you don't need to reference `mailserver.env`.

**Comment by casperklein** [comment]
Good news: I can replicate your issue.
Bad news: You probably didn't do as adviced 😉

**Comment by polarathene** [comment]
> Stop. Variables in the file `.env` are not passed to the container. However, the vars in `mailserver.env` are passed to the container.

```env
# .env
IT_WORKS=42
```

```yml
# docker-compose.yml
version: '3'

services:
  try_it:
    image: alpine
    container_name: try_it
    environment:
      - IT_WORKS
    tty: true
```

And now it works:

```console-session
$ docker-compose up -d && docker exec -it try_it ash -c 'echo "${IT_WORKS}"'
42
```

You can add `env_file` for a custom env file, but you'll still find vars passed through `environment` override it.

**Comment by casperklein** [comment]
Okay. Sorry. I didn't know that 😞  I thought you would mistake `.env` file with `mailserver.env`

TIL that there is another crazy way to provide container variables 😄

**Comment by casperklein** [comment]
@ MohammedNoureldin 

The error occurs, when you do not fully shutdown (destroy) the container. On next start, the files are already gone because they were deleted previously.

In any case, you must run `docker-compose down`.

In doubt, check if the container is really gone with  `docker ps -a`.

If you see something like this:

```
CONTAINER ID   IMAGE                               COMMAND                  CREATED         STATUS                     PORTS     NAMES
aad9522a93e9   mailserver/docker-mailserver:edge   "/usr/bin/dumb-init …"   7 minutes ago   Exited (0) 2 minutes ago             mailserver
```

then issue `docker-compose down`. Otherwise, THIS "already used" container will be used by `docker-compose up` again.

**Comment by casperklein** [comment]
This can happen for example, if you use `docker-compose up` and then hitting CTRL-C. This will just shutdown but not delete/destroy the container.

**Comment by MohammedNoureldin** [comment]
> This can happen for example, if you use `docker-compose up` and then hitting CTRL-C. This will just shutdown but not delete/destroy the container.

I am bit confused what to do now. Actually I am stopping the container using: `docker stop mailserver`

**Comment by polarathene** [comment]
> Actually I am stopping the container using: `docker stop mailserver`

This stops the container, it does not remove it. What that means is the internal file state is kept the same. It is not "reset" to a known good state like when you start fresh.

`docker stop mailserver && docker rm mailserver` is what you want. You rely on the volumes for persisting data, anything else is meant to be thrown away. If you're not going to use the proper `docker-compose down` which does the same, you can also run `docker run --rm` which will remove the container after it stops.

**Comment by MohammedNoureldin** [comment]
Oooh ok now I understand, but why is this happning? in the older version that was not a problem to just restart the container without removing it. For me this beheviour is a bit weird that I need to recreate the whole container instead of restarting it.

**Comment by polarathene** [comment]
> but why is this happning? in the older version that was not a problem to just restart the container without removing it.

Because this was considered a bugfix/improvement I think. Previously we just removed the file but no error would be thrown if the file didn't exist. This might seem like a regression, but it actually helps identify the cause much sooner.

When using `user-patches.sh` scripts, these can suffer the same problem, I encountered them over a year ago as I would use `docker-compose up` and then exit with `ctrl+c` (instead of `docker-compose down`), then `docker-compose up` again, and wonder why my script was not working.

Now the reason will be more obvious :)

**Comment by casperklein** [comment]
> Oooh ok now I understand, but why is this happning?

Your previous workflow (docker start/stop) might work, but it's not best practice. With the new version, we introduced a stricter error checking. So these files couldn't be deleted in the old version as well, but no error was shown.

Think of containers like the were toilet papers (should only be used once 😄). As a thumb rule, containers shouldn't be stopped and started again.

**Comment by polarathene** [comment]
> For me this behavior is a bit weird and uncommon that I need to recreate the whole container instead of restarting it. Can't it be _fixed_, this is much nicer to be able to just restart the container?

You'd need a compelling case for it I think. As I explained in my last comment, it can be easy to accidentally get different behaviour that we can't workaround, so it's better to detect that early on.

If you really want to avoid this, you can override the error handling [here](https://github.com/docker-mailserver/docker-mailserver/blob/master/target/scripts/startup/fixes-stack.sh), just remove the content on each line from `||` onwards. You can either build custom Dockerfile, or volume mount over it in the container.

**Comment by MohammedNoureldin** [comment]
@polarathene @casperklein thank you for the explanation! At least I understand the whole thing now.

To be honest, I see it as a bad behavior, you don't know what can happen with your server or container, and it is always good if your container can just restart and recover itself. I know it is good that you know exactly that something went wrong, but you may have that as a very emphasized log entry, but to just crash the container for such minor error is not something I would see, imho.

Can't we have the ability to **configure this behavior as environment variable** to ignore such not-really-errors?

**Comment by casperklein** [comment]
> always good if your container can just restart and recover itself.

Fair point. We should improve this. I agree that the error handling in this case is a but harsh.

**Comment by polarathene** [comment]
I'm not sure how you're starting your containers, but here is the two ways to do this and avoid this problem:

- `docker run --rm`
- `docker-compose up --force-recreate`

And then add any extra options you normally have. The `docker` example will remove when container is stopped, while `docker-compose` will always recreate the containers.

---

> to ignore such not-really-errors?

And if you later have something that would be a silent error because you didn't create a fresh container?

I think it's fair though. If other maintainers agree that it would be better to emit a warning instead. I don't think we have a need to explicitly shut the container down for this error handling.

**Comment by MohammedNoureldin** [comment]
@polarathene sorry I did not meant ignore literally. I just meant to log them as **warnings**. This is gonna be the best.

If it is possible please try to get it in this version, because this is directly related to a change done it it.

Thank you all for this discussion!

**Comment by georglauterbach** [comment]
@casperklein shall we emit a warning now, instead of logging a fatality?

**Comment by MohammedNoureldin** [comment]
> > So removing the container should be considered only if the container for a serious reason fails. Otherwise `restart` is the clean way.
> 
> Can you expand on the doc reference? That's an area I look after, I'm going to take a guess you're referring to `restart: always` in the config example?
> 
> That's not necessary for cert renewals AFAIK, and it's for the non-`docker-mailserver` containers, which I believe use the Docker API to restart the containers if necessary regardless of the setting.
> 
> When you restart a container, ENV changes don't carry over IIRC, which can be unexpected. The clean way is re-creating a container as we advise as no state is persisted. Should the container encounter a failure and be eligible to restart itself, ideally it should be able to recover that way though, I'm not against that.

I am not sure if I understand you correctly, so please correct me if I did not get your point correctly.

Restarting the container (or at least the service that uses the certificate) is necessary in most cases (I am not sure what about postfix), but in general you would restart the services after renewing the certificates. That is what all other services (and docker containers) do. Actually I know no docker container that requires removing and recreating the container as a better solution than restarting. Of course if the container is stateless is good. I am just trying to say that nor restarting nor recreating should be better the other, they both should be good, imo.
