### ISSUE TITLE
[BUG] Let's encrypt certificate renew not recognised. mailserver uses old one and not updated one. 

### ISSUE THREAD

**Issue by zaphoodb** [docker-mailserver/docker-mailserver#2239]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

mailserver does not use renewed let's encrypt certificate

### What happened and when does this occur?

```Markdown
I'm using traefik v2 to get and renew certificates. The traefik json which holds the certificates has been mounted as volume into the mailserver docker container. When the certificate gets renewed by traefik (~4 weeks before expiry), the mailserver does not recognise this certificate and keeps using the old one. 

I checked certificate with https://www.checktls.com/TestReceiver and it still shows the old one. Opening the Website that uses the same hostname and certificate, it shows the renewed one. 

When I do a restart of the docker container, the new certificate is recognized and from there on used.
```

### What did you expect to happen?

```Markdown
docker mailserver should recognise the updated / renewed certificate (by traefik2) without restarting the container.
```

### How do we replicate the issue?

```Markdown
1. Setup traefik2, nginx webserver and docker mailserver as described in the docu
2. wait until let's encrypt certificate get's renewed by traefik2
3. check that mailserver does not pick renewed certificate
...
```

### DMS version

v10.1.2

### How much RAM is available to DMS explicitly?

more than 4GB

### How many CPU cores are available?

less than 4 Cores

### Is DMS running in a virtualized environment?

... a virtual private server (VPS) (with virtual CPU cores)

### What operating system is DMS running on?

Linux

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### I/O - Persistent memory

docker volume mount ext4

### What container orchestration tool are you using?

Docker Compose

### Docker Compose version

docker-compose version 1.28.5

### The output of `uname -a`

Linux 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux

### Important environment variables

```bash
Mount point within my docker-compose file: 

      - /data/acme/:/etc/letsencrypt/

I tried 

      - /data/acme/acme.json:/etc/letsencrypt/acme.json:ro

last time but same result.
```

### What level of experience do you have with Docker and mail servers?

Trust me, I'm a (computer) engineer! [expert]

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by georglauterbach** [comment]
@docker-mailserver/maintainers doesn't check for changes automatically recognize this? Is there a regression here?

**Comment by casperklein** [comment]
It does:

https://github.com/docker-mailserver/docker-mailserver/blob/cd7677b6f020099a85ae35739cdd7a485491bc92/target/scripts/helper-functions.sh#L278-L281

**Comment by polarathene** [comment]
I don't see anything that stands out to me with this script logic:

https://github.com/docker-mailserver/docker-mailserver/blob/cd7677b6f020099a85ae35739cdd7a485491bc92/target/scripts/check-for-changes.sh#L64-L79

https://github.com/docker-mailserver/docker-mailserver/blob/cd7677b6f020099a85ae35739cdd7a485491bc92/target/scripts/helper-functions.sh#L151-L195

---

The report is not clear if this is a regression. Version cited is `10.1.2`, so presumably this has always been the behavior shipped.

I'm not sure why it would be failing though, looks like the check script would restart postfix afterwards. I would need to try reproduce it.

How long did the time between renewal and the user noticing it wasn't switched to take? How often do we have `check-for-changes.sh` run?

**Comment by georglauterbach** [comment]
@zaphoodb can you re-check you mounted the ACME file to `/etc/letsencrypt/acme.json`?

**Comment by zaphoodb** [comment]
Yes it is mounted to that location. I just verified with my docker-compose.yml: 
`      - /data/acme/acme.json:/etc/letsencrypt/acme.json:ro` is the exact mount. 

Tomorrow morning GMT will be another renew. Will check afterwards but do not restart the docker container. 

I don't recall how long I waited last time to see if the renewed certificate gets noticed. But at least a few hours or up to one / two days I would say.

**Comment by polarathene** [comment]
> I don't recall how long I waited last time to see if the renewed certificate gets noticed.

Did the functionality ever work as desired? Or are you new to `docker-mailserver` and you expected it to update to renewed certs? (_it should, but I'm just curious if it ever worked this way for `acme.json`_)

**Comment by zaphoodb** [comment]
I'm very familiar with docker and running traefik as a reverse proxy (and using it to get letsencrypt certificates). I am using docker-mailserver since beginning of this year. So far everything worked. But I newer saw that docker-mailserver was picking up the changes to the acme.json (made by traefik) automatically. Only on a restart or re-create of the docker container, the updated certificate was used. Therefore I think it's an option that this never worked as designed. 

[docker-mailserver docu about traefik](https://docker-mailserver.github.io/docker-mailserver/edge/config/security/ssl/#traefik-v2): `The file is also monitored for changes and will trigger a reload of the mail services (Postfix and Dovecot).` This is newer saw happening.

**Comment by georglauterbach** [comment]
I have used DMS & Traefik this way and it worked fine this way. But I'm not using this setup for 5 or 6 months anymore as I moved to K8s.

But I'm certain it worked fine. I'll have a look later.

**Comment by georglauterbach** [comment]
What hostname / domainname / `OVERRIDE_HOSTNAME` is set for you setup @zaphoodb ? For which domain is the certificate issued?

**Comment by zaphoodb** [comment]
@georglauterbach: 
`hostname: mail`
`domainname: somedomain.com`

Do you need the real values? 

Other (relevant) environment variables:
`environment:`
`      - SSL_TYPE=letsencrypt`
`      - SSL_DOMAIN=mail.somedomain.com`

`OVERRIDE_HOSTNAME` is not set in my docker-compose.yml

The renew has not yet taken place (it might be tomorrow or the day after - traefik does not renew the certificate right away if the remaining time is less than 4 weeks). I switched `DMS_DEBUG=1` on. I will give you an update once I see something. 


I just realized that in my config folder there is this file: 
`-rw-r--r-- 1 root root    0 Aug 20 08:43 check-for-changes.sh.lock` 

I did restart the docker-container since Aug 20... might this file be the reason why I have this strange behavior?

**Comment by georglauterbach** [comment]
The real values are not needed:) Please remove the lock file and see whether this solves your problem.

**Comment by casperklein** [comment]
What is the output of:

`docker exec mailserver bash -c 'openssl x509 -noout -text -in /etc/letsencrypt/live/"${HOSTNAME}"/fullchain.pem'`

**Comment by zaphoodb** [comment]
Executing `docker exec mailserver bash -c 'openssl x509 -noout -text -in /etc/letsencrypt/live/"${HOSTNAME}"/fullchain.pem'` (HOSTNAME is "mail"), I get this (just an extract): 

```
        Validity
            Not Before: Oct  6 07:20:34 2021 GMT
            Not After : Jan  4 07:20:33 2022 GMT
        Subject: CN = mail.somedomain.com
```
Executing `docker exec mailserver bash -c 'openssl x509 -noout -text -in /etc/letsencrypt/live/mail.somedomain.com/fullchain.pem'`, I get this (just an extract): 

```
        Validity
            Not Before: Aug  6 15:49:07 2021 GMT
            Not After : Nov  4 15:49:05 2021 GMT
        Subject: CN = mail.somedomain.com
```

**Comment by zaphoodb** [comment]
I can't say which certificate is picked. I executed it on the host VM (not within the docker container): 
```
CONNECTED(00000003)
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = mail.somedomain.com
verify return:1
---
Certificate chain
 0 s:CN = mail.somedomain.com
   i:C = US, O = Let's Encrypt, CN = R3
 1 s:C = US, O = Let's Encrypt, CN = R3
   i:C = US, O = Internet Security Research Group, CN = ISRG Root X1
 2 s:C = US, O = Internet Security Research Group, CN = ISRG Root X1
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
---
Server certificate
-----BEGIN CERTIFICATE-----
<REMOVED>
-----END CERTIFICATE-----
subject=CN = mail.somedomain.com

issuer=C = US, O = Let's Encrypt, CN = R3

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 5334 bytes and written 422 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 4096 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
250 CHUNKING
DONE
```

**Comment by zaphoodb** [comment]
This still looks like the old certificate: 
```
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = mail.somedomain.com
verify return:1
250 CHUNKING
DONE
notAfter=Nov  4 15:49:05 2021 GMT
```

**Comment by NorseGaud** [comment]
1. The orphaned lock file was definitely a problem. So it's good you cleared that up.

2. There is definitely something wrong with the HOSTNAME, DOMAIN, DOMAINNAME, and override + watching SSL changes/renewals on the container: I had experienced and attempted a fix in the https://github.com/docker-mailserver/docker-mailserver/pull/2157 branch. I'll pull out those changes from that PR as I need a bit more time on the changes watcher improvements.

I'm a little confused though. Is the problem with acme renewing, or a domain's SSL renewing?

**Comment by zaphoodb** [comment]
> I'm a little confused though. Is the problem with acme renewing, or a domain's SSL renewing?
ACME renewing works perfectly (traefik2 does the job) and saves it to acme.json. Then the mailserver should pick up the changed certificate (instantly) which does not work  on-the-fly. Only when the docker container is restarted (or re-created) the updated certificate gets picked up and used from then on.

Does that clarify your question?

**Comment by NorseGaud** [comment]
I'm 99% certain you're experiencing the bug I mentioned. It looks like it may have expanded the certs into `mail` instead. Why it works after a reboot of the container though is a different problem. If you moved the contents of `mail` into `mail.somedomain.com` it would probably work after manually restarting postfix/dovecot. Do you have the ability to test that?

**Comment by NorseGaud** [comment]
Also, you could build [my fix branch's](https://github.com/docker-mailserver/docker-mailserver/pull/2245) tag and use that to test.

**Comment by zaphoodb** [comment]
> I'm 99% certain you're experiencing the bug I mentioned. It looks like it may have expanded the certs into `mail` instead. Why it works after a reboot of the container though is a different problem. If you moved the contents of `mail` into `mail.somedomain.com` it would probably work after manually restarting postfix/dovecot. Do you have the ability to test that?

I copied the files from mail to mail.somedomain.com and restarted postfix/dovecot via ``supervisorctl restart dovecot / postfix``. The renewed certificate is in use now: 

```
Not Valid Before: Oct  6 07:20:34 2021 GMT
Not Valid After: Jan  4 07:20:33 2022 GMT
```

**Comment by dumblob** [comment]
Is there anything to improve on?

**Comment by polarathene** [comment]
@dumblob there is still some related PRs to merge before a 10.3 release. Most of them are in `:edge` right now and should fix the problem AFAIK.

**Comment by polarathene** [comment]
[`v10.3.0` has been released](https://github.com/docker-mailserver/docker-mailserver/releases/tag/v10.3.0), it contains fixes around `SSL_DOMAIN` and `SSL_TYPE=letsencrypt` handling/renewals.

Please let us know if it resolves this issue.

**Comment by dumblob** [comment]
> [`v10.3.0` has been released](https://github.com/docker-mailserver/docker-mailserver/releases/tag/v10.3.0), it contains fixes around `SSL_DOMAIN` and `SSL_TYPE=letsencrypt` handling/renewals.

Do these changes apply also to other providers using a similar issuing policy as Let's Encrypt - e.g. Buypass, ZeroSSL, SSL.com etc.?

(sorry, I didn't find the time to read through all the commits' patches)

**Comment by polarathene** [comment]
> Do these changes apply also to other providers using a similar issuing policy as Let's Encrypt - e.g. Buypass, ZeroSSL, SSL.com etc.?

If you use the `SSL_TYPE=letsencrypt` mode and you externally renew your certs that are provided via a bind mount volume, the file change will be detected and certs updated (unless using LDAP).

This issue is about a case where that feature did not work reliably (_the cert internally was copied to the wrong location_), it should no longer happen.

**Comment by zaphoodb** [comment]
I updated to 10.3.0. Next auto-renew is around 4th of December. Therefore perfect timing from your end to release this! :) 

Will give you an update afterwards.

**Comment by polarathene** [comment]
@zaphoodb how did it  go? Renewal went smoothly this time? :)

**Comment by zaphoodb** [comment]
Renewal was successful! :) No manual restar required this time. Thanks a lot!!

``````
Not Valid Before: Dec  5 22:42:21 2021 GMT
Not Valid After: Mar  5 22:42:20 2022 GMT

root@mail:/# ls -al /etc/letsencrypt/acme.json
-rw------- 1 root root 202986 Dec  7 00:42 /etc/letsencrypt/acme.json

root@mail:/# ls -al /etc/letsencrypt/live/
total 20
drwxr-xr-x 2 root root 4096 Nov 29 09:30 .
drwxr-xr-x 3 root root 4096 Nov 29 09:30 ..
-rw-r--r-- 1 root root 5946 Dec  7 00:42 fullchain.pem
-rw-r--r-- 1 root root 3243 Dec  7 00:42 key.pem
``````
