### ISSUE TITLE
[BUG] Problems with log-file-permissions

### ISSUE THREAD

**Issue by mholti** [docker-mailserver/docker-mailserver#2240]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

logrotate complains about too open permissions

### What happened and when does this occur?

```Markdown
I create my folders to mount via script and give them 777-permissions.
now logrotate complains:


error: skipping "/var/log/mail/clamav.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
error: skipping "/var/log/mail/freshclam.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
error: skipping "/var/log/mail/mail.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
error: skipping "/var/log/mail/mail.info" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
error: skipping "/var/log/mail/mail.warn" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
error: skipping "/var/log/mail/mail.err" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
run-parts: /etc/cron.daily/logrotate exited with return code 1
```
when i change permissions to 700, frehclam isn't able to access the log and wont run.
```


### What did you expect to happen?

```Markdown
I expect to run logrotate and freshclam without problems
```

### How do we replicate the issue?

```Markdown
1. Create folders for bind-mount with 777-permissions
2. start container
3. wait for logrotate and freshclam to start
4. read error-mails ;-) 
...
```

### DMS version

latest

### How much RAM is available to DMS explicitly?

more than 4GB

### How many CPU cores are available?

less than 4 Cores

### Is DMS running in a virtualized environment?

... a physical host (with real, physical CPU cores, i.e. bare metal)

### What operating system is DMS running on?

Linux

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### I/O - Persistent memory

Docker bind-mount from local btrfs

### What container orchestration tool are you using?

Docker Compose

### Docker version

Docker version 20.10.3, build b455053

### Docker Compose version

docker-compose version 1.28.5, build 324b023a

### The output of `uname -a`

Linux NASiX 4.4.180+ #41890 SMP Fri Jun 25 02:40:02 CST 2021 x86_64 GNU/Linux synology_v1000_1621+

### Important environment variables

```bash
environment:
      - DEFAULT_RELAY_HOST=[xxxx]:25
      - DMS_DEBUG=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=0
      - ENABLE_FETCHMAIL=1
      - ENABLE_MANAGESIEVE=1
      - ENABLE_POP3=0
      - ENABLE_POSTGREY=0
      - ENABLE_QUOTAS=1
      - ENABLE_SPAMASSASSIN=1
      - FETCHMAIL_POLL=300
      - ONE_DIR=1
      - PERMIT_DOCKER=192.168.0.0/16
      - PFLOGSUMM_RECIPIENT=xxxx
      - PFLOGSUMM_TRIGGER=daily_cron
      - POSTMASTER_ADDRESS=xxxx
      - RELAY_HOST=xxxx
      - RELAY_PASSWORD=xxxxxx
      - RELAY_PORT=25
      - RELAY_USER=xxxxx
      - SA_SPAM_SUBJECT=***SPAM(_SCORE_)***
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - SPOOF_PROTECTION=0
      - SSL_TYPE=letsencrypt
```

### Relevant log output

```shell
nothing in log, error-mails
```

### Other relevant information

```Markdown
My volumes:

    volumes:
      - ${BASEDIR}/${MAIL_DIRNAME}/data:/var/mail
      - ${BASEDIR}/${MAIL_DIRNAME}/state:/var/mail-state
      - ${BASEDIR}/${MAIL_DIRNAME}/config/:/tmp/docker-mailserver/
      - ${BASEDIR}/${MAIL_DIRNAME}/log:/var/log/mail
      - ${CERTDIR}:/etc/letsencrypt:ro
      - ${TIMEZONE_PATH}:/etc/timezone:ro
      - ${LOCALTIME}:/etc/localtime:ro

all "${*DIR*}-variables are set in .env
```

### What level of experience do you have with Docker and mail servers?

I know both pretty well actually [experienced]

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by georglauterbach** [comment]
You said

> I create my folders to mount via script and give them 777-permissions.

why would you provide `777` for these folders as permissions? Isn't that a bit too open as a default? `logrotate` is right to complain here, as permissions are too open which is a security issue (anyone could change logs at will). Maybe `btrfs` is onvolved too.

I'm running K8s and because of my volume setup, I use

``` BASH
# logs
chmod 755 /var/log/mail
chmod 755 /var/log/mail.log
chown root:root /var/log/mail/mail.*
chmod 644 /var/log/mail/mail.log*
```

in my `user-patches.sh` script to adjust permissions.

**Comment by mholti** [comment]
Hi,
sure it's to open... I use this script to setup a lot of containers and not all images allow to set user- and group-id via env. So my solution was to give all folders 777...
I'll try your user-patches.sh
Thanks for the hint.
