### ISSUE TITLE
dovecot: master: Error: bind(/var/spool/postfix/private/auth) failed: Operation not supported

### ISSUE THREAD

**Issue by ekalchev** [docker-mailserver/docker-mailserver#2242]
# Subject

I would like to configure a not documented mail server use case

## Description
I am using docker-mailserver 10.2.0

I am trying to run the container on WSL2-Ubuntu. When I execute "docker-compose up" I am getting these errors from dovecot.
I tried to enable all debug logs of dovecot but I am not getting any additional information.

```
mailserver    | Oct  6 20:02:45 mail dovecot: master: Error: bind(/var/spool/postfix/private/auth) failed: Operation not supported
mailserver    | Oct  6 20:02:45 mail dovecot: master: Error: service(auth): net_listen_unix(/var/spool/postfix/private/auth) failed: Operation not supported
mailserver    | Oct  6 20:02:45 mail dovecot: master: Fatal: Failed to start listeners
```
my docker-compose.yml
```version: '3.8'

services:
  mailserver:
    build: ./
    container_name: mailserver
    hostname: mail
    # Change this to your domain, it is used for your email accounts (eg: user@example.com):
    domainname: example.com
    env_file: mailserver.env
    ports:
      - "25:25"
      - "110:110"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE```

**Comment by georglauterbach** [comment]
> @georglauterbach It is running on pure Ubuntu with no issues. both WSL2 and pure linux are Ubuntu 20.04

Then this is a WSL issue. We don't support WSL. I cannot afford to look into this further, I'm sorry.

---

> Another issue I noticed while was doing my tests. If I use docker-compose file as it is in git and build from image i am getting errors when I tried to create user like this
> 
> ```
> docker run --rm -v "${PWD}/docker-data/dms/config/:/tmp/docker-mailserver/" docker-mailserver_mailserver setup email add testmail1@example.com 11111
> ```
> 
> if I build the image locally with modifying .yml file and adding build: ./ it is working fine.

Not sure I get what you're asking. You container is running and is called `docker-mailserver_mailserver`, right? Which version of DMS are you using?
