### ISSUE TITLE
Mailserver behind Traefik

### ISSUE THREAD

**Issue by dimitrimestdag** [docker-mailserver/docker-mailserver#2263]
# Subject

I would like to configure a not documented mail server use case

## Description

Hello,

I have configured your mail server with rainloop.
I receive emails well and when I configure an alias to an external address and I receive an email on my address, the email is transferred to the external address.
The concern is that when I try to send an email from rainloop I get the message "Authentication failed":
![image](https://user-images.githubusercontent.com/18188598/139282284-d528ab19-8ccf-40f7-9b7a-3358cd846b98.png)

Here are the container logs regarding this error : 

``` BASH
Oct 28 16:09:23 mail dovecot: imap(user@domain.fr)<18024><BXryQWrPUMtVqGs9>: Logged out in=90 out=982 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0,
Oct 28 16:13:38 mail dovecot: imap(user@domain.fr)<19420><UynoUGrPAs9VqGs9>: Logged out in=90 out=982 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0,
Oct 28 16:13:38 mail dovecot: imap-login: Login: user=<user@domain.fr>, method=PLAIN, rip=my.ip, lip=traefik ip, mpid=19420, TLS, session=<UynoUGrPAs9VqGs9>,
Oct 28 16:13:34 mail dovecot: imap(user@domain.fr)<19384><wkHLUGrP7s5VqGs9>: Logged out in=11 out=449 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0,
Oct 28 16:13:34 mail postfix/smtps/smtpd[19385]: disconnect from my-ip.rev.numericable.fr[my.ip] ehlo=1 auth=0/1 quit=1 commands=2/3,
Oct 28 16:13:34 mail postfix/smtps/smtpd[19385]: warning: my-ip.rev.numericable.fr[my.ip]: SASL PLAIN authentication failed: ,
Oct 28 16:13:32 mail dovecot: auth: passwd-file(user,my.ip): unknown user (SHA1 of given password: ca7fbf),
Oct 28 16:13:32 mail postfix/smtps/smtpd[19385]: Anonymous TLS connection established from my-ip.rev.numericable.fr[my.ip]: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits),
Oct 28 16:13:32 mail postfix/smtps/smtpd[19385]: connect from my-ip.rev.numericable.fr[my.ip],
Oct 28 16:13:32 mail dovecot: imap-login: Login: user=<user@domain.fr>, method=PLAIN, rip=my.ip, lip=traefik ip, mpid=19384, TLS, session=<wkHLUGrP7s5VqGs9>

```

I think the most important in these logs is "SASL PLAIN authentication failed" but I can't seem to find where it came from.

my mail server is behind Traefik which is in another container, here is my docker compose file :

``` BASH
traefik:
        restart: always
        image: traefik
        container_name: traefik
        hostname: traefik
        command:
          - "--entryPoints.smtp.address=:25"
          - "--entryPoints.smtp-ssl.address=:465"
          - "--entryPoints.imap-ssl.address=:993"
          - "--entryPoints.sieve.address=:4190"
          - --certificatesresolvers.myresolver.acme.email=user@hotmail.fr
          - --certificatesresolvers.myresolver.acme.storage=/certs/acme.json
        ports:
          - "25:25"
          - "465:465"
          - "993:993"
          - "4190:4190"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - ./traefik/certs:/certs
        networks:
          - backend
          - frontend
mailserver:
        image: docker.io/mailserver/docker-mailserver:latest
        container_name: mailserver
        hostname: mail
        domainname: domain.fr
        env_file: mail/mailserver.env
        labels:
          - "traefik.enable=true"
          - "traefik.tcp.routers.smtp.rule=HostSNI(`*`)"
          - "traefik.tcp.routers.smtp.entrypoints=smtp"
          - "traefik.tcp.routers.smtp.service=smtp"
          - "traefik.tcp.services.smtp.loadbalancer.server.port=25"
          - "traefik.tcp.services.smtp.loadbalancer.proxyProtocol.version=1"
          - "traefik.tcp.routers.smtp-ssl.rule=HostSNI(`*`)"
          - "traefik.tcp.routers.smtp-ssl.tls=false"
          - "traefik.tcp.routers.smtp-ssl.entrypoints=smtp-ssl"
          - "traefik.tcp.routers.smtp-ssl.service=smtp-ssl"
          - "traefik.tcp.services.smtp-ssl.loadbalancer.server.port=465"
          - "traefik.tcp.services.smtp-ssl.loadbalancer.proxyProtocol.version=1"
          - "traefik.tcp.routers.imap-ssl.rule=HostSNI(`*`)"
          - "traefik.tcp.routers.imap-ssl.entrypoints=imap-ssl"
          - "traefik.tcp.routers.imap-ssl.service=imap-ssl"
          - "traefik.tcp.services.imap-ssl.loadbalancer.server.port=10993"
          - "traefik.tcp.services.imap-ssl.loadbalancer.proxyProtocol.version=2"
          - "traefik.tcp.routers.sieve.rule=HostSNI(`*`)"
          - "traefik.tcp.routers.sieve.entrypoints=sieve"
          - "traefik.tcp.routers.sieve.service=sieve"
          - "traefik.tcp.services.sieve.loadbalancer.server.port=4190"
        volumes:
          - ./mail/dms/mail-data/:/var/mail/
          - ./mail/dms/mail-state/:/var/mail-state/
          - ./mail/dms/mail-logs/:/var/log/mail/
          - ./mail/dms/config/:/tmp/docker-mailserver/
          - ./traefik/certs/acme.json:/etc/letsencrypt/acme.json:ro
          - /etc/localtime:/etc/localtime:ro
        restart: always
        stop_grace_period: 1m
        cap_add:
          - NET_ADMIN
          - SYS_PTRACE
        networks:
          - backend
```
and the dovecot and postfix conf are the same as here: https://docker-mailserver.github.io/docker-mailserver/edge/examples/tutorials/mailserver-behind-proxy/

It should not be a problem coming from Rainloop like here: https://github.com/RainLoop/rainloop-webmail/issues/1629 since I also cannot send mail from my Outlook client

Do you have any idea where the problem could come from?

thanks in advance,

Dimo

**Comment by wernerfred** [comment]
> The example was contributed by @wernerfred

Not much time right now but i did a quick comparison with my setup (also using rainloop in this combination) and the only difference is that i do not have this line `- "traefik.tcp.routers.smtp-ssl.tls=false"` in my config right now.

What does rainloop show in the test connection section (status green?):
![image](https://user-images.githubusercontent.com/20406381/139483829-0d2b8e96-dc72-4fc9-91c7-66fdd906974f.png)

**Comment by polarathene** [comment]
> Unfortunately I don't see how not to use rainloop without traefik: it manages port 443, I have other services that use it ...
> I should be able to dock an ubuntu for internal testing.

I was suggesting that you try focus on only `docker-mailserver`, either with your existing setup or via a separate test instance. Just ignore rainloop and traefik being involved first and get `docker-mailserver` to not fail first.

Then you can add back traefik, followed by rainloop to see if either of those cause the problem or if their involvement had nothing to do with it.

> `SSL_DOMAIN=mail.domain.fr`

I don't think you need this, or at least in an upcoming release there should be no reason to. Not likely to matter with this issue though.

---

> Rainloop or outlook tries to send on port 465, that's it.
> I have no problem sending mail from an external address (gmail or outlook) to my `docker-mailserver` address.

> I use aliases because my `SPOOF_PROTECTION` variable is enabled

Please try just send from rainloop between two email accounts in `docker-mailserver`. So `userA@domain.fr` to `userB@domain.fr`.

- Try with real accounts `setup email add` first.
- If that works, make an alias for each with `setup alias add`, then do email test again with rainloop `aliasA@domain.fr` to `aliasB@domain.fr`.

We can look at send to external email afterwards. But first check that it works properly internally.

**Comment by dimitrimestdag** [comment]
@wernerfred I was the one who added this line ```- "traefik.tcp.routers.smtp-ssl.tls=false" ``` thinking that the problem came from the certificate that traefik did not recognize.
The connection section displays green on IMAP and SMTP.

@polarathene Here are the initial mailserver logs that I perform the test mails from Rainloop (none works):

Here is the result of ./setup.sh email list:
```
* myuser.gmail@domain.fr ( 246K / ~ ) [0%]
    [ aliases -> myuser@domain.fr, myuser.gmail@domain.fr]

* postmaster.mail@domain.fr ( 1.0K / ~ ) [0%]
    [ aliases -> postmaster@domain.fr]
```
postmaster.mail@domain.fr > myuser.gmail@domain.fr
```
Oct 30 18:21:51 mail dovecot: imap-login: Login: user=<postmaster.mail@domain.fr>, method=PLAIN, rip=my.ip, lip=traefik.ip, mpid=11580, TLS, session=<ygdZV5TPasRVqGs9>,
Oct 30 18:21:51 mail postfix/smtps/smtpd[11581]: connect from my-ip.rev.numericable.fr[my.ip],
Oct 30 18:21:51 mail postfix/smtps/smtpd[11581]: Anonymous TLS connection established from my-ip.rev.numericable.fr[my.ip]: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits),
Oct 30 18:21:51 mail dovecot: auth: passwd-file(postmaster.mail,my.ip): unknown user (SHA1 of given password: ca7fbf),
Oct 30 18:21:53 mail postfix/smtps/smtpd[11581]: warning: my-ip.rev.numericable.fr[my.ip]: SASL PLAIN authentication failed: ,
Oct 30 18:21:53 mail postfix/smtps/smtpd[11581]: disconnect from my-ip.rev.numericable.fr[my.ip] ehlo=1 auth=0/1 quit=1 commands=2/3,
Oct 30 18:21:53 mail dovecot: imap(postmaster.mail@domain.fr)<11580><ygdZV5TPasRVqGs9>: Logged out in=11 out=449 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
```


postmaster.mail@domain.fr > myuser@domain.fr
```
Oct 30 18:26:15 mail dovecot: imap-login: Login: user=<postmaster.mail@domain.fr>, method=PLAIN, rip=my.ip, lip=traefik.ip, mpid=13021, TLS, session=<mEgVZ5TPHMhVqGs9>,
Oct 30 18:26:15 mail postfix/smtps/smtpd[13023]: connect from my-ip.rev.numericable.fr[my.ip],
Oct 30 18:26:15 mail postfix/smtps/smtpd[13023]: Anonymous TLS connection established from my-ip.rev.numericable.fr[my.ip]: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits),
Oct 30 18:26:15 mail dovecot: auth: passwd-file(postmaster.mail,my.ip): unknown user (SHA1 of given password: ca7fbf),
Oct 30 18:26:17 mail postfix/smtps/smtpd[13023]: warning: my-ip.rev.numericable.fr[my.ip]: SASL PLAIN authentication failed: ,
Oct 30 18:26:17 mail postfix/smtps/smtpd[13023]: disconnect from my-ip.rev.numericable.fr[my.ip] ehlo=1 auth=0/1 quit=1 commands=2/3,
Oct 30 18:26:17 mail dovecot: imap(postmaster.mail@domain.fr)<13021><mEgVZ5TPHMhVqGs9>: Logged out in=11 out=449 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
```

postmaster@domain.fr > myuser@domain.fr
```
Oct 30 18:33:50 mail dovecot: imap-login: Login: user=<postmaster.mail@domain.fr>, method=PLAIN, rip=my.ip, lip=traefik.ip, mpid=16320, TLS, session=<NVI/gpTPus5VqGs9>,
Oct 30 18:33:51 mail postfix/smtps/smtpd[16321]: connect from my-ip.rev.numericable.fr[my.ip],
Oct 30 18:33:51 mail postfix/smtps/smtpd[16321]: Anonymous TLS connection established from my-ip.rev.numericable.fr[my.ip]: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits),
Oct 30 18:33:51 mail dovecot: auth: passwd-file(postmaster.mail,my.ip): unknown user (SHA1 of given password: ca7fbf),
Oct 30 18:33:53 mail postfix/smtps/smtpd[16321]: warning: my-ip.rev.numericable.fr[my.ip]: SASL PLAIN authentication failed: ,
Oct 30 18:33:53 mail postfix/smtps/smtpd[16321]: disconnect from my-ip.rev.numericable.fr[my.ip] ehlo=1 auth=0/1 quit=1 commands=2/3,
Oct 30 18:33:53 mail dovecot: imap(postmaster.mail@domain.fr)<16320><NVI/gpTPus5VqGs9>: Logged out in=11 out=449 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0,
Oct 30 18:33:57 mail dovecot: imap-login: Login: user=<postmaster.mail@domain.fr>, method=PLAIN, rip=my.ip, lip=traefik.ip, mpid=16363, TLS, session=<WxxqgpTPzM5VqGs9>,
Oct 30 18:33:57 mail dovecot: imap(postmaster.mail@domain.fr)<16363><WxxqgpTPzM5VqGs9>: Logged out in=90 out=988 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
```
I will try to do some tests on a virtual machine without traefik, I will keep you posted

**Comment by polarathene** [comment]
@dimitrimestdag that doesn't look like you were testing with two internal email accounts, but one internal and one external?

I'm thinking that when I see `dovecot: auth: passwd-file(postmaster.mail,my.ip)` that you are logging in with user `postmaster.mail` without the rest of `@domain.fr`. Can you try that? AFAIK the Dovecot accounts are being made with the full address as the user.

**Comment by dimitrimestdag** [comment]
Hello, 
I'm confused: I was actually using the short id on Rainloop and Outlook, I changed that and it works. Thank you very much for the time you spent on my case!

**Comment by casperklein** [comment]
The issue was accidentally closed, by fixing a minor issue in `listmailuser`. If you feel your issue is resolved, feel free to close it again.

**Comment by dimitrimestdag** [comment]
Thanks again for your time

**Comment by polarathene** [comment]
> I was actually using the short id on Rainloop and Outlook, I changed that and it works. 

Ah great, so I was right then :grinning: 

To use the local part only (nothing from `@` after), we'd have to create the Dovecot accounts differently with `%n` for the username I think. Not sure how that works though if you have `contact@example.com` and `contact@not-example.com` setup :man_shrugging: 

> Thank you very much for the time you spent on my case!

Welcome!
