### ISSUE TITLE
Q: Accept eMails from Proxmox-Mail-Gateway

### ISSUE THREAD

**Issue by white-rabbit07** [docker-mailserver/docker-mailserver#2288]
Hi.
I installed the Proxmox-Mail-Gateway [like this](https://pmg.proxmox.com/pmg-docs/pmg-admin-guide.html#chapter_deployment). When I send an email from outside now, it will be accepted by the Proxmox-Mail-Gateway (PMG) and then passed to the docker-mailserver. This step fails and the eMail comes back with this error message:

`host 172.17.17.201[172.17.17.201 (this is the docker-Mailserver)] said: 550
5.7.1 Service unavailable; client [172.17.17.172 (this is the PMG)] blocked using
zen.spamhaus.org (in reply to RCPT TO command)
`
I don't know where or how to whitelist the PMG in the docker-compose.yml and I'm sure that the docker-Container doesn't use a Spamfilter at the moment ... that's why I don't know why I get this error:
`    environment:
    - ENABLE_SPAMASSASSIN=0
    - ENABLE_CLAMAV=0
    - ENABLE_FAIL2BAN=0
    - ENABLE_POSTGREY=0
[...]
`
Any hints? Thanks!

**Comment by casperklein** [comment]
To disable DNS blocking, see the the [linked issue above](https://github.com/docker-mailserver/docker-mailserver/issues/1927).

To whitelist PMG, you could also put something like this in your [user-patches.sh](https://docker-mailserver.github.io/docker-mailserver/edge/faq/#how-to-adjust-settings-with-the-user-patchessh-script):

`postconf -e "$(postconf | grep '^mynetworks =') 172.17.17.172/32"`
