### ISSUE TITLE
Upgrading to 10.2.0 - "The certificates are now stored under /etc/dms/tls/"

### ISSUE THREAD

**Issue by ghnp5** [docker-mailserver/docker-mailserver#2289]
Hello,

I use LetsEncrypt:

`SSL_TYPE=letsencrypt`

And I see that the Release Notes for 10.2.0 say:

> With this release, internal TLS functionality was revised. If you run a special or custom setup, make sure to adjust it accordingly. If you're running a normal setup, you will not have to change anything for SSL. **The certificates are now stored under /etc/dms/tls/**.

When I generate new certificates on the host, I run:

```
cp -R -L /etc/letsencrypt/live/mail.mydomain.com/* /docker/mailserver/letsencrypt/live/mail.mydomain.com/
docker exec mailserver bash -c 'dovecot reload'
docker exec mailserver bash -c 'postfix reload'
docker exec mailserver openssl s_client -connect 0.0.0.0:25 -starttls smtp -CApath /etc/ssl/certs/
docker exec mailserver openssl s_client -connect 0.0.0.0:143 -starttls imap -CApath /etc/ssl/certs/
```

Do I need to change anything in this process?
Perhaps changing `/etc/ssl/certs/` to `/etc/dms/tls/` ?

Thank you

**Comment by georglauterbach** [comment]
I guess you'd need to change:

``` DIFF
- docker exec mailserver openssl s_client -connect 0.0.0.0:25 -starttls smtp -CApath /etc/ssl/certs/
- docker exec mailserver openssl s_client -connect 0.0.0.0:143 -starttls imap -CApath /etc/ssl/certs/
+ docker exec mailserver openssl s_client -connect 0.0.0.0:25 -starttls smtp -CApath /etc/dms/tls/
+ docker exec mailserver openssl s_client -connect 0.0.0.0:143 -starttls imap -CApath /etc/dms/tls/
```

CC @polarathene

**Comment by polarathene** [comment]
> Do I need to change anything in this process?
> Perhaps changing `/etc/ssl/certs/` to `/etc/dms/tls/` ?

No, the previous location was `/etc/postfix/` IIRC, this was only intended for internal use (we copy it at container startup).

`/etc/ssl/certs` is still the correct path for your `-CApath` value and your test should show that still works fine.

**Comment by ghnp5** [comment]
Thank you very much!
I assume all I need to do is upgrade the image, then! 👍
