### ISSUE TITLE
Replacement drive/filesystem after rsync copy results in duplicated recent deleted emails?

### ISSUE THREAD

**Issue by andrewlow** [docker-mailserver/docker-mailserver#2290]
# Subject

I would like some feedback concerning a use case

## Description

Version 10.2.0

I recently was changing the drive configuration of my setup - moving from a regular ext4 filesystem, to a RAID1 setup with ext4.

This means that /storage/email remained the same path - but the storage underneath it changed from being a drive mounted on /storage - to a RAID1 array mounted on /storage.

I replicated the data using `sudo rsync -avxHAX --progress /storage/. /mnt/.` - I checked that the filesystem seemed to be a perfect duplicate. I shutdown the mailserver and all other containers/processes touching the /storage filesystem. The rsync reported zero changes after repeated runs.

When I remounted the new array from `/mnt` to be `/storage` - everything appears to have restarted just fine. However, I received in my mail client new copies of some emails I'd received in the last 12hrs. These are all emails that I'd received, and deleted. However, it seems I have new copies - so after re-deleting them - I have 2 copies in my trash.

Any ideas here? Does dovecot use the inode or something to decide that something is new or not? Why only a few messages and not all of them?

**Comment by maietta** [comment]
This seems more of a file-system issue and not related to docker-mailserver.

**Comment by casperklein** [comment]
Your rsync command looks good. As long as ownership and permissions are the same, there should be no issues. DMS doesn't know/care if you use a RAID setup or not.

**Comment by andrewlow** [comment]
> As long as ownership and permissions are the same, there should be no issues. 

That's why I wanted to report it. It didn't make sense that there would be anything, but clearly I have some evidence that the switch to the new filesystem (but on the same paths) had some change.

I'm happy to just close this as 'unknown' - I'm not likely to change the underlying filesystem again, and this is a rare case if it was indeed a software bug vs. user error (but I'm pretty sure I didn't do anything random)

**Comment by georglauterbach** [comment]
Like @maietta I too do not think this is actually related to DMS. But yes, this is interesting, as I see no reason why...

**Comment by andrewlow** [comment]
Agree - we should close this - it'll be in the closed issues if someone searches for the same type of problem.
