### ISSUE TITLE
Upgrade base image to Debian 11

### ISSUE THREAD

**Issue by srt** [docker-mailserver/docker-mailserver#2312]
I would love to see the base image upgraded to Debian 11 so we get an up to date version of Dovecot. Recent versions of Dovecot have better [support for XOAUTH2](https://doc.dovecot.org/configuration_manual/authentication/oauth2/) that should help implementing SSO with webmail clients like Roundcube and OIDC providers like Keycloak.

**Comment by georglauterbach** [comment]
https://github.com/docker-mailserver/docker-mailserver/pull/2116

**Comment by polarathene** [comment]
> Debian 11 so we get an up to date version of Dovecot. Recent versions of Dovecot have better [support for XOAUTH2](https://doc.dovecot.org/configuration_manual/authentication/oauth2/)

From that link it states: _"New in version v2.3.16."_ (for OpenID Discovery)

[Debian 11 ships Dovecot 2.3.13](https://github.com/docker-mailserver/docker-mailserver/pull/2116#issuecomment-955615529) which will enable support for features "Proxy with Password Grant" and "Local Validation". Is it one of those? Or did you want the OpenID Discovery? (_it seems like it'd be useful for Keycloak, but too new unfortunately_)

---

As stated, I'm waiting on hearing back that changes in two active issues were resolved with `v10.3.0` release, then we'll update the image for `edge` tag. I'm a bit pressed for time this month, and would like to get some changes in for `v11`, thus I am not sure if we'll see that as a tagged release until some time in Jan.

**Comment by srt** [comment]
Thanks for having a look at this and pointing me to the merge request. I will try out the new version as soon as a docker image becomes available.
The most important feature ist "Local validation" (New in version 2.3.11) which allows dovecot to validate the token without an additional round trip to the idp. OpenID Discovery would be nice too, as it would make configuration much easier, but it is not as crucial as local validation.

**Comment by vx3r** [comment]
hello @srt im also trying to setup oidc for docker-mailserver using authelia as idp, can you please elaborate you config ? Which mail client are you using ? Im struggling to understand how dovecot is getting the oauth token or client credentials from email client to validate them against idp. 
thanks for you help

**Comment by srt** [comment]
@vx3r I am about to configure Roundcube as mail client with oidc, see https://github.com/roundcube/roundcubemail/wiki/Configuration%3A-OAuth2
I will provide an update once I have more information on how it works.

**Comment by louistrapadoux** [comment]
hi, I managed to configure OAUTH/SSO for my setup in my case: Roundcubemail, docker-mailserver with [Authentik](https://goauthentik.io/)


the idea is that roundcube seems to pass on the bearer token to dovecot/postfix to authenticate the use to retrieve and send the emails

**Roundcubemail config:**
follow the config steps it's pretty straight forward
https://github.com/roundcube/roundcubemail/wiki/Configuration:-OAuth2

**Dovecot**
need to configure Dovecot as Roundcube will pass on the auth token
https://doc.dovecot.org/configuration_manual/authentication/oauth2/

in user-patches.sh

```
CONF_DIR=/tmp/docker-mailserver
cp ${CONF_DIR}/11-xoauth2.conf /etc/dovecot/conf.d/
cp ${CONF_DIR}/dovecot-oauth2.conf.ext /etc/dovecot/
cp ${CONF_DIR}/auth-ldap.conf.ext /etc/dovecot/conf.d/

```

in 11-xoauth2.conf

```
auth_mechanisms = oauthbearer xoauth2 plain login

passdb {

  driver = oauth2
  mechanisms = xoauth2 oauthbearer
  args = /etc/dovecot/dovecot-oauth2.conf.ext
}
```

in dovecot-oauth2.conf.ext

```
tls_ca_cert_file = /etc/ssl/certs/ca-certificates.crt

tokeninfo_url = https://<authentik.domain>/application/o/userinfo/?access_token=
introspection_url = https://<client_id>:<client_secret>@<authentik.domain>/application/o/introspect/
introspection_mode = post
force_introspection = yes
active_attribute = active
active_value = true
```

I followed the detail explained in the following issue:

https://github.com/goauthentik/authentik/issues/1234

**POSTFIX/SMTPD**
to send emails, moved smtpd authentication from SASLAUTHD to dovecot auth (default in docker-mailserver)
https://documentation.open-xchange.com/7.10.2/middleware/mail/dovecot/oauth_2.0_with_postfix_and_dovecot.html

what is needed:

```
smtpd_relay_restrictions = permit_sasl_authenticated, reject
smtpd_sasl_type = dovecot
smtpd_sasl_path = private/auth
smtpd_sasl_auth_enable = yes
```

it's the default in docker-mailserver unless SASLAUTHD is enabled which was the case for my setup so I changed:

```
ENABLE_SASLAUTHD=0
```

I got stuck for a while on an smtpd authentication issue:
I had to set in postfix main.cf to allow roundcube to pass the full token encrypted with base64
https://groups.google.com/g/mailing.postfix.users/c/-NVDJKHIZy8
line_length_limit = 4096

maybe can be fixed differently: https://github.com/roundcube/roundcubemail/issues/8178

**Fail2Ban**
issue with Fail2Ban was catching the message in /var/log/mail.log
Jan 17 21:53:54 mail dovecot: auth: ldap(<user>@<domain>,172.22.0.1,<xxxxXXXXxxxxXXXX>): Password mismatch (SHA1 of given password: da4545) - trying the next passdb

==> override the ldap passdb config for dovecot telling not to go through the ldap auth for auth mechanism other than PLAIN and LOGIN to avoid the warning message in log
https://doc.dovecot.org/configuration_manual/authentication/password_databases_passdb/

in auth-ldap.conf.ext

```
passdb {
  driver = ldap

  # Path for LDAP configuration file, see example-config/dovecot-ldap.conf.ext
  args = /etc/dovecot/dovecot-ldap.conf.ext

  skip = authenticated
  mechanisms = PLAIN LOGIN
}
```




there might be some more elegant way to configure it but for now this has been working well for me.

**Comment by polarathene** [comment]
Hey @louistrapadoux thanks for that detailed guide!

That looks like it could be a useful resource to other users and not obvious to stumble upon here due to the issue title.

We're fairly lax with user contributed guides in our [Examples](https://docker-mailserver.github.io/docker-mailserver/edge/examples/tutorials/basic-installation/) section of docs, for the most part, you'd just contribute a markdown document [here](https://github.com/docker-mailserver/docker-mailserver/tree/master/docs/content/examples/tutorials) to the project via a Pull Request.

If you'd like to get more visibility to that advice that'd be a great place to contribute it to :)
