### ISSUE TITLE
DANE/TLSA support available?

### ISSUE THREAD

**Issue by theRealBaccata** [docker-mailserver/docker-mailserver#2313]
# Subject

I have questions about TLS/SSL/STARTTLS/OpenSSL

## Description

Hello,

I’m a happy docker-mailserver user and I just got a short question.

I enabled DNSSEC for my domain and would like to use **DANE/TLSA** in the next step. I haven’t seen any documentation about this topic around here so I raised this issue.

Does docker-mailserver supports it?

**Comment by casperklein** [comment]
Out of the box, I don't think so.

fyi: From my quick web research, DANE doesn't be wildly adopted. The majority seems to go with SPF/DKIM & DMARC.

**Comment by theRealBaccata** [comment]
Thanks for the response. I already implemented DKIM & DMARC. Everything works fine, however it can't hurt adding more trust while operating a mail server.

**Comment by georglauterbach** [comment]
> however it can't hurt adding more trust while operating a mail server.

While I agree with keeping very high standards, one should carefully weigh the gained benefits of using DANE versus the additional time / potential issues introduced into an already complex system. DANE is sadly not widely used, so the benefit is marginal.

I'd personally (well, I do) go with well-known DNS providers that support ECS, like Quad9: <https://support.quad9.net/hc/en-us/articles/360056850672-Secure-with-ECS-Support-Service>. If you can, you may as well use a local, recursive DBS resolver that does DNSSEC for you, like [this containerised one](https://support.quad9.net/hc/en-us/articles/360056850672-Secure-with-ECS-Support-Service).

**Comment by paschun** [comment]
Here is a way to track DANE/TLSA usage
https://stats.dnssec-tools.org
