### ISSUE TITLE
Simple forward only setup

### ISSUE THREAD

**Issue by Tezzlicious** [docker-mailserver/docker-mailserver#2317]
Hi all, I would like to simply forward emails from @mydomain1.com @mydomain2.com to i.e. my@gmail.com. I've setup most of it by following [this guide](https://docker-mailserver.github.io/docker-mailserver/edge/examples/uses-cases/forward-only-mailserver-with-ldap-authentication/), but I end up with:

```
Dec  7 22:36:10 mail postfix/smtp[1245]: 9A1B9E2001C0: to=<my@gmail.com>, orig_to=<my@mydomain1.com>, relay=127.0.0.1[127.0.0.1]:10024, delay=0.42, delays=0.19/0.02/0.01/0.21, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as E7D7BE2001E9)'

Dec  7 22:36:10 mail postfix/lmtp[1248]: E7D7BE2001E9: to=<my@gmail.com>, relay=none, delay=0.08, delays=0.07/0.01/0/0, dsn=4.4.1, status=deferred (connect to mail.mymailserverdomain.com[/var/run/dovecot/lmtp]: No such file or directory)
```

Don't know if I understand correctly, but with SMTP_ONLY=1 it shouldn't try something with dovecot?

No clue how to proceed or what I'm missing. Help is appriciated.

**Comment by casperklein** [comment]
Did you find the cause?
