### ISSUE TITLE
alpine version?

### ISSUE THREAD

**Issue by djbrown78** [docker-mailserver/docker-mailserver#232]
Hi, did you give up on the Alpine version?

**Comment by tomav** [comment]
Currently yes. But feel free to let us know if you have inputs on that part.

**Comment by tomav** [comment]
I close the issue. Let's reopen if someone starts working on this.
On my side, the only value is a smaller image size. I'm not sure that maintenance will be that easy.
We can talk about that, I'm open to suggestions.

**Comment by williamdes** [comment]
I am interested in implementing this

**Comment by polarathene** [comment]
If you implement alpine support, for that to be upstreamed as official how is maintenance intended going forward?

Does CI and tests need to additionally take that into account and what is the impact?
- Does it complicate the CI workflows much to support / maintain in addition to the Debian image?
- How important is test coverage on Alpine builds, will it double the time to run tests or is less testing required?

This adds an additional Dockerfile to maintain with different syntax and package versions, does that pose any concerns?

I'm not opposed to it, I'd personally like an Alpine image (but then again I'd also like a more modular approach too but that doesn't align with the goals of this project AFAIK, eg splitting services across multiple images or multi-stage build variants).

---

I imagine you'd possibly want to use Bash over Ash, and that certain packages might have different locations for files? At least I think the shell scripts make assumptions based on the Debian image setup.

**Comment by georglauterbach** [comment]
@williamdes I don't think we need an alpine version. The benefit of saving 20-30MB is not worth it in my opinion. Having a complete `glibc` is more important. And you also said you already have too much to do :)

**Comment by williamdes** [comment]
> @williamdes I don't think we need an alpine version. The benefit of saving 20-30MB is not worth it in my opinion. Having a complete `glibc` is more important. And you also said you already have too much to do :)

I agree, it's a bit frustrating because it's more about not having useless code in the image than about the image size

But it's not worth the time maintaining this variant seeing the complex config overrides we have to do everywhere
