### ISSUE TITLE
550 5.1.1 User doesn't exist:  (in reply to RCPT TO command)

### ISSUE THREAD

**Issue by maietta** [docker-mailserver/docker-mailserver#2323]
I don't want to rule this a bug just yet, but it sure seems like it: If it's a bug, we can change the tags/issue type.

After running ./setup.sh email add user@example.com, I have successfully created a new user.

However, when attempting to access the email account, it doesn't exist. When I sent an email to the user, i get this response immediately.

<test@example.com>: host mail.example.com[/var/run/dovecot/lmtp] said: 550
    5.1.1 <test@example.com> User doesn't exist: test@example.com (in reply
    to RCPT TO command)

I noticed on the Docker host machine, permissions for the data directory get changed to root:5000.

I've attempted an upgrade as well, to no avail.

I have no obvious errors in the logs.

Any guidance would be greatly appreciated here.

**Comment by polarathene** [comment]
> I noticed on the Docker host machine, permissions for the data directory get changed to root:5000.

There's nothing in the [version release diff](https://github.com/docker-mailserver/docker-mailserver/compare/v10.2.0...v10.3.0) that stands out related to that. There was a fair bit of shuffling/refactoring going on which makes that diff a bit less useful, might be easier going through the list of individual commits :sweat_smile: 

The only possible change that might be related to that is in `setup.sh` with the [default config/data directory path being changed](https://github.com/docker-mailserver/docker-mailserver/commit/50e629abd0269cee0b7a86b60a6262bd6fb73967#diff-4209d788ad32c40cbda3c66b3de47eefb929308ca703bb77a6382625986add17). This still currently supports detecting an existing `config/` local directory if it exists.

---

> However, when attempting to access the email account, it doesn't exist. When I sent an email to the user, i get this response immediately.

You show an example adding an email account `user@example.com`, but then your output is for `test@example.com`? Why is that different?

Is an alias involved here?

---

I believe we also refactored `hostname`/`domainname` handling to resolve an edge case bug with TLS cert renewals. We may have accidentally introduced a bug here.

Can you provide a reproduction `docker-compose.yml` config with any commands to reproduce?

Try `hostname: mail.example.com`, with no `domainname` option. Although `hostname: mail` with `domainname: example.com` should work too AFAIK, a bare domain `hostname: example.com` would have an issue that should appear in logs.

Have you run with `DMS_DEBUG=1` to check logs? Everything ok with a fresh container start? (`docker-compose down && docker-compose up`)

**Comment by maietta** [comment]
Dammit, just now realized I was working on wrong server all day trying to solve this.

I migrated email from old server to new server last month, keeping old files in place. No wonder the setup script wasn't creating email on the new server!

I'm sorry I wasted your time but perhaps someone else will run into this particular issue and be reminded about a migration they might have forgotten about. :/
