### ISSUE TITLE
fail2ban not working

### ISSUE THREAD

**Issue by jlim0930** [docker-mailserver/docker-mailserver#2327]
# Subject

Other - fail2ban

## Description

I've just deployed docker-mailserver - Super nice!

I see that fail2ban is not working.  I currently have set in `docker-compose.yml`

```
     cap_add:
       - NET_ADMIN
       - NET_RAW
       - SYS_PTRACE
```

however when I run `docker exec mailserver iptables -L` I get 
```
iptables v1.8.2 (legacy): can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
```

I saw on https://github.com/docker-mailserver/docker-mailserver/issues/2169 that many are running fail2ban on their host instead.  Are there any instructions for that?

**Comment by georglauterbach** [comment]
This might very well be related to the host you are using. F2B runs flawlessly for me with `:v10.3.0`. What's the output of `iptables -nL` when you execute it on your host (with `sudo` or as root if necessary)?

**Comment by jlim0930** [comment]
I'm on Rocky 8.5 using docker-ce

iptables -nL shows
```
# iptables -nL
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
f2b-sshd   tcp  --  0.0.0.0/0            0.0.0.0/0            multiport dports 22

Chain FORWARD (policy DROP)
target     prot opt source               destination
DOCKER-USER  all  --  0.0.0.0/0            0.0.0.0/0
DOCKER-ISOLATION-STAGE-1  all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
DOCKER     all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
f2b-wplogin  tcp  --  0.0.0.0/0            0.0.0.0/0            multiport dports 80
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
DOCKER     all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
DOCKER     all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
DOCKER     all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain DOCKER (4 references)
target     prot opt source               destination
ACCEPT     tcp  --  0.0.0.0/0            172.20.0.3           tcp dpt:80
ACCEPT     tcp  --  0.0.0.0/0            172.22.0.2           tcp dpt:993
ACCEPT     tcp  --  0.0.0.0/0            172.22.0.2           tcp dpt:587
ACCEPT     tcp  --  0.0.0.0/0            172.22.0.2           tcp dpt:465
ACCEPT     tcp  --  0.0.0.0/0            172.22.0.2           tcp dpt:143
ACCEPT     tcp  --  0.0.0.0/0            172.22.0.2           tcp dpt:25
ACCEPT     tcp  --  0.0.0.0/0            172.20.0.4           tcp dpt:443
ACCEPT     tcp  --  0.0.0.0/0            172.20.0.4           tcp dpt:80

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
target     prot opt source               destination
DOCKER-ISOLATION-STAGE-2  all  --  0.0.0.0/0            0.0.0.0/0
DOCKER-ISOLATION-STAGE-2  all  --  0.0.0.0/0            0.0.0.0/0
DOCKER-ISOLATION-STAGE-2  all  --  0.0.0.0/0            0.0.0.0/0
DOCKER-ISOLATION-STAGE-2  all  --  0.0.0.0/0            0.0.0.0/0
RETURN     all  --  0.0.0.0/0            0.0.0.0/0

Chain DOCKER-ISOLATION-STAGE-2 (4 references)
target     prot opt source               destination
DROP       all  --  0.0.0.0/0            0.0.0.0/0
DROP       all  --  0.0.0.0/0            0.0.0.0/0
DROP       all  --  0.0.0.0/0            0.0.0.0/0
DROP       all  --  0.0.0.0/0            0.0.0.0/0
RETURN     all  --  0.0.0.0/0            0.0.0.0/0

Chain DOCKER-USER (1 references)
target     prot opt source               destination
RETURN     all  --  0.0.0.0/0            0.0.0.0/0
```

**Comment by georglauterbach** [comment]
Got to be honest with you, exactly as in #2169, I don't really know whether to dig next about this, sorry. But we'll keep it open and see if someone else comes along.

**Comment by casperklein** [comment]
I just fired up a test Rocky VM.

This works (iptables-nft):

`docker run -it --cap-add NET_ADMIN debian:11-slim bash -c 'apt update && apt -y install iptables && iptables -L'`

This doesn't work (iptables-legacy, which DMS is using):

`docker run -it --cap-add NET_ADMIN debian:11-slim bash -c 'apt update && apt -y install iptables && update-alternatives --set iptables /usr/sbin/iptables-legacy && iptables -L'`

However, on a Debian host both examples are working.

**Comment by joeknock90** [comment]
I was experiencing the same issue on Rocky Linux. Here's what I did as a work around:

Using from the documentation here: https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/override-defaults/user-patches/

Used @casperklein 's find to update alternatives for iptables to point to iptables-nft

Seems to be working just fine now even after downing and upping (Is that the best way to say that? Whatever) the container.

**Comment by duckpuppy** [comment]
Just ran across this myself - I have exactly the same problem on Debian 11 as the Rocky Linux users. Creating a `user-patches.sh` file in my config directory with the following contents works:

```
#! /bin/bash

update-alternatives --set iptables /usr/sbin/iptables-nft
update-alternatives --set ip6tables /usr/sbin/ip6tables-nft
```

**Comment by georglauterbach** [comment]
@casperklein we're currently setting iptables to legacy iptables in the Dockerfile instead of iptables-nft. What do you think is required for the change to nft? Debian 11 brings all this by default, right?

**Comment by georglauterbach** [comment]
> I don't know, if fail2ban is already compatible with iptabels-nft. If so, there should be no reason to use legacy anymore.

If I'm not mistaken, F2B already supports nftables for a decent amount of time, so we should be able to change after slightly adjusting the F2B configuration.

**Comment by georglauterbach** [comment]
When #2505 is merged, @jlim0930 @duckpuppy you needn't run the `update-alternatives` command anymore, because `nftables` will be the default :)

**Comment by georglauterbach** [comment]
#2505 is now merged and should be available on `:edge`. It will be included in the upcoming release of major version 11.
