### ISSUE TITLE
How to disable POP3 & IMAP for specific domain?

### ISSUE THREAD

**Issue by siavashfazli** [docker-mailserver/docker-mailserver#2331]
Hi dear!
We use docker mailserver with 3 Emails.
Now we need to disable POP3 & IMAP  in one of these Emails.
I read the documentation but I can't find my problem solution.
is it possible at all?

`
root@************:/opt/mailservice-docker-configs#    ./setup.sh email list
* no-reply@***.** ( 2.5M / ~ ) [0%]

* no-reply@*****.** ( 56K / ~ ) [0%]

* support@*******.**** ( 8.0K / ~ ) [0%]

root@*************:/opt/mailservice-docker-configs# 
`
I need to disable POP3 & IMAP for the first Email.
How can I do this?

**Comment by polarathene** [comment]
It might be possible to wrap the [IMAP and POP services (our dovecot config)](https://github.com/docker-mailserver/docker-mailserver/blob/99cc9fec2a01e078fda6ce439def681e31a4e8f9/target/dovecot/10-master.conf#L17-L46) via FQDN (SNI in this case) [like shown here in Dovecot docs](https://doc.dovecot.org/configuration_manual/ssl_configuration/) (`local imap.example.com { }`). I don't know if that will actually work, and it's not something we officially support AFAIK.

Another option that might be better is to use a reverse proxy capable of handling TCP routing, such as Traefik. You'd configure that to only proxy the FQDNs (domains) to the service ports you want them to support. Then the single `docker-mailserver` container can have each port exposed (not published), and services running IMAP + POP3, but if Traefik does not make those ports reachable for some of your domains, then it should be similar to disabling them selectively.
