### ISSUE TITLE
How to configure newly created account to forward mail to another account?

### ISSUE THREAD

**Issue by blastbeng** [docker-mailserver/docker-mailserver#2334]
Hello,
I have a simple question, I'd like to have newly created accounts to forward emails to my main Email, how to do this? With an Alias?

I am a newbie in postfix\dovecot and I've not found yet a way to do this

Thanks in advance

**Comment by casperklein** [comment]
Did you bother looking in our [documentation ](https://docker-mailserver.github.io/docker-mailserver/edge/config/user-management/aliases/) for this "alias" thing?

**Comment by blastbeng** [comment]
Yes, was just wondering.. is creating an alias for every email on my main mail the best solution? Or are there other better ways of doing it?

**Comment by casperklein** [comment]
I don't exactly know your setup, but using aliases seems fine to me.

**Comment by blastbeng** [comment]
Ok sounds good then
