### ISSUE TITLE
[Question] postfix/smtpd[****]: lost connection after UNKNOWN

### ISSUE THREAD

**Issue by JivinDotL** [docker-mailserver/docker-mailserver#2338]
# Subject
I have a question about IMAP about postfix/smtpd[****]: lost connection after UNKNOWN.

## Description
I setuped a imap mailserver by using docker and installed by using demo docker-compose.yml and add - ENABLE_SRS=1
I used nginx server forward ports(25,143,587,993) to this docker mailserver and I get the 'lost connection after UNKNOWN from' the message.

'''
version: '3.8'

services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail
    domainname: yjxapi.top
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_SPAMASSASSIN=1
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ENABLE_SASLAUTHD=0
      - ONE_DIR=1
      - DMS_DEBUG=0
      - ENABLE_SRS=1
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always

''''

## LOG
Dec 24 02:05:19 mail postfix/postscreen[1602]: CONNECT from [46.213.128.57]:35840 to [172.19.0.2]:25
Dec 24 02:05:19 mail postfix/postscreen[1602]: cache btree:/var/lib/postfix/postscreen_cache full cleanup: retained=1 dropped=0 entries
Dec 24 02:05:21 mail postfix/postscreen[1602]: PASS OLD [46.213.128.57]:35840
Dec 24 02:05:21 mail postfix/smtpd[1623]: connect from 46.213.128.57.16clouds.com[46.213.128.57]
Dec 24 02:05:23 mail postfix/smtpd[1623]: lost connection after UNKNOWN from 46.213.128.57.16clouds.com[46.213.128.57]
Dec 24 02:05:23 mail postfix/smtpd[1623]: disconnect from 46.213.128.57.16clouds.com[46.213.128.57] ehlo=1 starttls=0/1 unknown=0/3 commands=1/5

**Comment by casperklein** [comment]
If that does not occurs on all incoming mail, I bet it's kind of spam and can be ignored.

**Comment by georglauterbach** [comment]
As @casperklein said, this is fine. Only suspicious IP will show such a behavior, and I see them too.
