### ISSUE TITLE
[BUG] listmailuser: line 15: 1024 *  : syntax error: operand expected (error token is "*  ")

### ISSUE THREAD

**Issue by christinloehner** [docker-mailserver/docker-mailserver#2339]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

doveadm and /usr/local/bin/listmailuser

### What happened and when does this occur?

```Markdown
After upgrading docker-mailserver from 10.3.0 to 10.4.0 and then using ./setup.sh to list all mailboxes, this error occurs:

 [08:18:16] christin@christin-loehner:/server/mail $ docker-compose pull
 Pulling mailserver ... done
 [08:20:52] christin@christin-loehner:/server/mail $ docker-compose down
 Stopping mailserver ... done
 Removing mailserver ... done
 [08:21:20] christin@christin-loehner:/server/mail $ docker-compose up -d mailserver
 Creating mailserver ... done
 [08:21:28] christin@christin-loehner:/server/mail $ 

 [08:21:32] christin@christin-loehner:/server/mail $ ./setup.sh email list
 doveadm(info@christin-loehner.de)<1172><>: Error: auth-master: userdb lookup(info@christin-loehner.de): connect(/run/dovecot/auth-userdb) failed: No such file or directory
 doveadm(info@christin-loehner.de): Error: User lookup failed: Internal error occurred. Refer to server log for more information.
 /usr/local/bin/listmailuser: line 15: 1024 *  : syntax error: operand expected (error token is "*  ")
 /usr/local/bin/listmailuser: line 15: 1024 *  : syntax error: operand expected (error token is "*  ")
 * info@christin-loehner.de (  /  ) [%]
    [ aliases -> info@christin-loehner.de, @christin-loehner.de]

But I still can send and receive emails
```

### What did you expect to happen?

```Markdown
I expected to see no errors. :-)
```

### How do we replicate the issue?

```Markdown
Run docker-mailserver 10.3.0 then do
1. docker-compose pull
2. docker-compose down
3. docker-compose up -d mailserver
4. ./setup.sh email list
```

### DMS version

v10.4.0

### What operating system is DMS running on?

Linux

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### What container orchestration tool are you using?

Docker Compose

### docker-compose.yml

```yaml
services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail.christin-loehner.de
    domainname: mail.christin-loehner.de
    env_file: mailserver.env
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./maildata/:/var/mail/
      - ./mailstate/:/var/mail-state/
      - ./maillogs/:/var/log/mail/
      - ./config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    network_mode: bridge
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
```

### Relevant log output

```shell
No log, no error in the log
```

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [ ] I am inexperienced with mail servers
- [ ] I am uncomfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by christinloehner** [comment]
Strange.... 15 minutes later, without doing anything, just calling ./setup.sh again, the errors are gone....

**Comment by casperklein** [comment]
It could be, that Dovecot was not fully started yet.

PS: In case this was unwanted, you might remove your private information like your email address from the config/logs you posted 😉

**Comment by christinloehner** [comment]
Don't worry... since I'm a very public person in germany, my email (and telephone and everything else) is public and can be found everywhere. I have very good filters for spam... :-P
