### ISSUE TITLE
Problems while looking for upgrading...

### ISSUE THREAD

**Issue by 00angus** [docker-mailserver/docker-mailserver#2347]
How and where can I found what mailserver version I am running from my old image (v 9.x or v10.x.y) ? Because I'd like to check for anything that can get broken while upgrading.

In the docs it's written: <<...you will need to get setup.sh with a specific version.>> but I cannot find what the current version is my image running from.

In the logs I cannot find any reference to my current mailserver version number (no results while searching for TASKLOG or any other reference mentioned in the docs).

Any help welcome, because I'd like not to break anything from my current setup :)
Thanks.

== EDIT ==
Maybe I should point out that I'm still running tvial/docker-mailserver version (from @tomav docker-hub image)? What could go wrong if I jump to the new version?
Thanks!

--- Marco

**Comment by casperklein** [comment]
> What could go wrong

Depends on your setup. I advice to carefully read the [CHANGELOG](https://github.com/docker-mailserver/docker-mailserver/blob/master/CHANGELOG.md), especially the "breaking changes" section.

`tvial/docker-mailserver` is pretty old. If you are using `tvial/docker-mailserver` without a pinned version, then you are using "latest". The last latest version was 7.0.2.

**Comment by 00angus** [comment]
> The last latest version is 7.0.2.
Okay - that is the starting point I was looking for, thank you. I'll check for sure the changelog.

I really appreciate the level and overall quality that this project has reached :) Keep going on :)
Thanks.
--- Marco
