### ISSUE TITLE
how to set listen=* to disable ipv6 for dovecot

### ISSUE THREAD

**Issue by a7711555** [docker-mailserver/docker-mailserver#2356]
# Subject

I have questions about configuration of covecot in container

## Description

The conatiner keeps produce the error while running

I found the default configuration of dovecot is listen = *, :: 

and should be set to listen=* to disable ipv6 but I found no way to replace it.

I tried set POSTFIX_INET_PROTOCOLS=ipv4 in environment variable but it's only for profix. 

am I missing somthing? Thanks very much.

``` BASH
mailserver    | Jan  4 10:49:17 mail dovecot: master: Error: socket() failed: Address family not supported by protocol
mailserver    | Jan  4 10:49:17 mail dovecot: master: Error: service(imap-login): listen(::, 143) failed: Address family not supported by protocol
mailserver    | Jan  4 10:49:17 mail dovecot: master: Error: socket() failed: Address family not supported by protocol
mailserver    | Jan  4 10:49:17 mail dovecot: master: Error: service(quota-status): listen(::, 65265) failed: Address family not supported by protocol
mailserver    | Jan  4 10:49:17 mail dovecot: master: Fatal: Failed to start listeners
```

**Comment by georglauterbach** [comment]
You can use [`user-patches.sh`](https://docker-mailserver.github.io/docker-mailserver/edge/faq/#how-to-adjust-settings-with-the-user-patchessh-script) to either:

1. disable IPv6 in the container
2. adjust the Dovecot configuration (with `sed` for example)

or both. **But** I'm not sure where you are getting

> I found the default configuration of dovecot is `listen = *, ::`

from. I can find this only for a integration test configuration, this is, AFAIK not the default configuration. My containers is running IPv6 (although not using it), and I do not have problems with IPv6... This leads me to belief your problems come from somewhere else. Does IPv4 properly work in your container?

**Comment by casperklein** [comment]
@georglauterbach Take a look at '/etc/dovecot/dovecot.conf'. There you'll find the `listen` statement.


@a7711555 Putting this in your [`user-patches.sh`](https://docker-mailserver.github.io/docker-mailserver/edge/faq/#how-to-adjust-settings-with-the-user-patchessh-script) will solve it:

`sed -i 's|^#listen =.*|listen = *|g' /etc/dovecot/dovecot.conf # IPv4 only`

**Comment by georglauterbach** [comment]
> @georglauterbach Take a look at '/etc/dovecot/dovecot.conf'. There you'll find the `listen` statement.

Yes, I know, but it is commented, so it does not apply - or is this the default?
 
> @a7711555 Putting this in your [`user-patches.sh`](https://docker-mailserver.github.io/docker-mailserver/edge/faq/#how-to-adjust-settings-with-the-user-patchessh-script) will solve it:
> 
> `sed -i 's|^#listen =.*|listen = *|g' /etc/dovecot/dovecot.conf # IPv4 only`

👍🏼

**Comment by casperklein** [comment]
I think so. Typically defaults in configuration files are commented out.

**Comment by a7711555** [comment]
> @georglauterbach Take a look at '/etc/dovecot/dovecot.conf'. There you'll find the `listen` statement.
> 
> @a7711555 Putting this in your [`user-patches.sh`](https://docker-mailserver.github.io/docker-mailserver/edge/faq/#how-to-adjust-settings-with-the-user-patchessh-script) will solve it:
> 
> `sed -i 's|^#listen =.*|listen = *|g' /etc/dovecot/dovecot.conf # IPv4 only`

This works for me
Thank you guys, truely appreciate all your reply and supporting!

**Comment by georglauterbach** [comment]
You're welcome :) I will close this issue. If there is more, just write us and we can re-open.

**Comment by casperklein** [comment]
This is now [configurable](https://docker-mailserver.github.io/docker-mailserver/edge/config/environment/#dovecot_inet_protocols) in the `:edge` image and later in the next regular release.
