### ISSUE TITLE
How to set Logwatch sender address?

### ISSUE THREAD

**Issue by craue** [docker-mailserver/docker-mailserver#2360]
# Subject

I would like some feedback concerning a use case.

## Description

By default, when enabling logwatch and pflogsumm reports, pflogsumm sender address is "mailserver-report@`hostname`.`domainname`" and logwatch sender address is "root@`hostname`.`domainname`". Now I'd like to change both to be sent from "whatever@`domainname`" but couldn't find out how.

I tried various environment variables, but none actually changes the sender e-mail address for the logwatch report ...

- `REPORT_SENDER`: sets sender for pflogsumm only, not logwatch
- `POSTMASTER_ADDRESS`: sets recipient addresses (for pflogsumm and logwatch) only, not sender
- `PFLOGSUMM_SENDER`: sets sender for pflogsumm only, as documented (and expected)
- `LOGWATCH_SENDER`: undocumented and obviously not working (but I wanted to be sure)

So is there a way to set the sender address for logwatch as well?

**Comment by casperklein** [comment]
You can try putting something like this in your [`user-patches.sh`](https://docker-mailserver.github.io/docker-mailserver/edge/faq/#how-to-adjust-settings-with-the-user-patchessh-script) (not tested):

`echo "MailFrom = foo@example.com" >> /etc/logwatch/conf/logfiles/maillog.conf`

**Comment by craue** [comment]
Thank you for the quick response. This led me in the right direction.

`echo "MailFrom = foo@example.com" >> /etc/logwatch/conf/logfiles/maillog.conf` indeed doesn't make a difference.

Taking a look at `/usr/share/logwatch/dist.conf/logwatch.conf` revealed the entry `MailFrom = root`, so I changed this instead and it's working: `sed -i 's|^MailFrom = root$|MailFrom = foo@example.com|' /usr/share/logwatch/dist.conf/logwatch.conf`

Interestingly, other directives put into `/etc/logwatch/conf/logfiles/maillog.conf` are ignored as well, like `Detail = High`. I also needed to add it in `/usr/share/logwatch/dist.conf/logwatch.conf`.

Having an env var at least for the sender address would be much more convenient, though. 😏

**Comment by georglauterbach** [comment]
@craue If you'd like to give it a try, you may regret to #2358 which provided a bit of structure for someone new to the project.
