### ISSUE TITLE
High Availability Options/Thoughts

### ISSUE THREAD

**Issue by TimothyGaray** [docker-mailserver/docker-mailserver#2370]
# Subject

I would like some feedback concerning a use case

## Description

I am running my own private mailserver as a docker image on an IntelNUC.  It has been working great for almost a year now.  Thank you so much for this!

Over New Years something happened and the container was not working or receiving emails.  It took me a few days to finally realize I was no longer receiving emails.  I tried sending some test emails and didn't receive them so I stopped and restarted the container and then emails worked again.  I didn't do any in-depth testing so I don't know if the whole container crashed or just the SMTP service or what the issue was.

What I found out afterwards was that some services (such as banking) tried to send me an email during that period and got the bounce notice so flagged my account until I logged in and verified my email again.  Since then I've been trying to think of options to prevent this from happening again.  I have had cases where my ISP drops and it takes them days to fix (cable company issue) or perhaps have a hardware issue.

I am curious if anyone else has done anything to keep their service running and how they did it?

I read through [#2048](https://github.com/docker-mailserver/docker-mailserver/issues/2048) and that seems promising.

I read through [#254](https://github.com/docker-mailserver/docker-mailserver/issues/254) as well.

I have a second IntelNUC also loaded with Ubuntu that I could setup a secondary mailserver on but I only have one public (dynamic) IP coming to my home so that would not help me much for Internet down.

I was looking into a store-and-forward email option.  Cheapest I found was $10/yr which isn't bad.  There are free options but I don't know how long they will hold your email before bouncing it (if at all).

I also thought about setting up a docker container in Azure or AWS as a backup only used if the primary was unavailable but don't know how much that could end up costing.  Or maybe just setup an SMTP server in the public cloud but I've seen that Azure at least blocks email sending.  Could try and setup an alternate port for that.

Since this has only happened once in the past year of running, most Internet outages are only seconds or at most few hours (I now have fiber to the house and battery backup and a generator) - maybe the easiest and cheapest thing is to setup something like Zabbix on the second IntelNUC and just monitor the service availability (primarily SMTP).  If something happens to the running container (again) or the entire docker host (hardware failure) then Zabbix could alert my phone.  Maybe even set some sort of monitoring up in the public cloud to monitor the SMTP availability (as long as it would not end up costing an arm-and-a-leg).

I also do nightly file backups of the docker host to my OneDrive so my emails are backed up.  A replicated copy would be nice but would only be needed in the event of an SSD/filesystem failure.

``` BASH
# CODE GOES HERE

```

**Comment by TimothyGaray** [comment]
I did write a PowerShell 7 script to run as an Azure Function App.  Even at every 5 minutes, it should be free every month.

I still need to add code for managing and sending alerts via PushOver based on responses/connections received or not.

`


# https://livebook.manning.com/book/powershell-deep-dives/chapter-4/29

$tcpClient = New-Object System.Net.Sockets.TcpClient
$tcpClient.Connect("mailserver.com",25)
$clientStream = $tcpClient.GetStream()
$clientStream.ReadTimeout = 10
$clientStream.WriteTimeout = 10

IF($tcpClient.Connected -eq $True) { Write-Host "Connected to mailserver" }

Start-Sleep -seconds 1
IF($clientStream.DataAvailable -eq $True)
{
	[byte[]]$inStream = New-Object byte[] $tcpClient.Available
	[Int]$response = $clientStream.Read($inStream, 0, $inStream.count)
	$ResponseString = [System.Text.Encoding]::ASCII.GetString($inStream[0..($response - 1)])
	Write-Host ("<< " + $ResponseString)
}	

$Text = "helo smtp.server.com`r`n"
[byte[]]$bytes  = [text.Encoding]::Ascii.GetBytes($Text)
$clientStream.Write($bytes,0,$bytes.length)
Write-Host (">> " + $Text)

Start-Sleep -seconds 1
IF($clientStream.DataAvailable -eq $True)
{
	[byte[]]$inStream = New-Object byte[] $tcpClient.Available
	[Int]$response = $clientStream.Read($inStream, 0, $inStream.count)
	$ResponseString = [System.Text.Encoding]::ASCII.GetString($inStream[0..($response - 1)])
	Write-Host ("<< " + $ResponseString)
}	



$Text = "quit`r`n"
[byte[]]$bytes  = [text.Encoding]::Ascii.GetBytes($Text)
$clientStream.Write($bytes,0,$bytes.length)
Write-Host (">> " + $Text)

Start-Sleep -seconds 1
IF($clientStream.DataAvailable -eq $True)
{
	[byte[]]$inStream = New-Object byte[] $tcpClient.Available
	[Int]$response = $clientStream.Read($inStream, 0, $inStream.count)
	$ResponseString = [System.Text.Encoding]::ASCII.GetString($inStream[0..($response - 1)])
	Write-Host ("<< " + $ResponseString)
}	

$tcpClient.Dispose()
$clientStream.Dispose()
`

**Comment by georglauterbach** [comment]
Achieving HA with a container like this that carries a lot of state is difficult. I got a K8s (non-HA yet) setup, and I can  recommend K8s for several reasons:

1. It's native to the container infrastructure
2. Learning K8s concepts helps in understanding how HA works best (e.g. non-imperative but declarative API)
3. It's setup has become easier

If course, downsides include

1. increased complexity (to a varying degree, but for a common setup, it's definitely more complicated)

---

For your setup, K8s is fine: you have two nodes (the Intel NUCs) in the same network that you can use for simple failover. Make both master-nodes on which you can schedule pods and you should have a failover setup. I wrote the docs for K8s myself, they should be fine unless you're an absolute beginner (because this is a complex pod). For persistent memory, you could to look into Longhorn (by Ranger).

---

I'd however go with a Linux vServer / Root Server in a Data Center as you have a SLA on uptime. I can recommend Contabo and NetCup, and you have a bit more money to spare, Hetzner. I'd not go to AWS, Azure or GKE, AKS, etc.

**Comment by jayknyn** [comment]
Tim, I was also hosting my mail server at home but after a few power failures (that out-lasted my UPS) and internet outages, I realized to reliably self-host an email server, it should run in the cloud as Georg says for the uptime SLA they provide. The cloud move happened also after I realized my ISP wouldn't create a Reverse DNS for my IP (being dynamic, they create it for static IPs) and cloud proivders give you a static IP on which you can build a good reputation for your mail server. As mentioned above, cloud doesn't just mean the big players. I ended up going with a small cloud provider whose IP range is not on any blacklists. I used [this site](https://www.vpsbenchmarks.com/screener) to find a good (and affordable) cloud provider.

For HA for an email setup, I think the best route is to actually standup at least 1 or 2 backup mailservers and create these additional MX records with a lower priority than your primary mail server. Again, these backup mailservers should probably run in the cloud, or maybe the 3rd backup could run at home. And this increases the cost of running a truly reliable (always able to receive, always able to send) email service (service being comprised of your mail servers, DNS records, clean IP address, etc.).

**Comment by TimothyGaray** [comment]
> Achieving HA with a container like this that carries a lot of state is difficult. I got a K8s (non-HA yet) setup, and I can recommend K8s for several reasons:
> 
> 1. It's native to the container infrastructure
> 2. Learning K8s concepts helps in understanding how HA works best (e.g. non-imperative but declarative API)
> 3. It's setup has become easier
> 
> If course, downsides include
> 
> 1. increased complexity (to a varying degree, but for a common setup, it's definitely more complicated)
> 
> For your setup, K8s is fine: you have two nodes (the Intel NUCs) in the same network that you can use for simple failover. Make both master-nodes on which you can schedule pods and you should have a failover setup. I wrote the docs for K8s myself, they should be fine unless you're an absolute beginner (because this is a complex pod). For persistent memory, you could to look into Longhorn (by Ranger).
> 
> I'd however go with a Linux vServer / Root Server in a Data Center as you have a SLA on uptime. I can recommend Contabo and NetCup, and if you have a bit more money to spare, Hetzner. I'd not go to AWS, Azure or GKE, AKS, etc.


I may look at K8s on down the road.  I've had some exposure to it so would be more learning experience (like Docker on Ubuntu was).

**Comment by TimothyGaray** [comment]
> Tim, I was also hosting my mail server at home but after a few power failures (that out-lasted my UPS) and internet outages, I realized to reliably self-host an email server, it should run in the cloud as Georg says for the uptime SLA they provide. The cloud move happened also after I realized my ISP wouldn't create a Reverse DNS for my IP (being dynamic, they create it for static IPs) and cloud proivders give you a static IP on which you can build a good reputation for your mail server. As mentioned above, cloud doesn't just mean the big players. I ended up going with a small cloud provider whose IP range is not on any blacklists. I used [this site](https://www.vpsbenchmarks.com/screener) to find a good (and affordable) cloud provider.
> 
> For HA for an email setup, I think the best route is to actually standup at least 1 or 2 backup mailservers and create these additional MX records with a lower priority than your primary mail server. Again, these backup mailservers should probably run in the cloud, or maybe the 3rd backup could run at home. And this increases the cost of running a truly reliable (always able to receive, always able to send) email service (service being comprised of your mail servers, DNS records, clean IP address, etc.).

I've had good luck over the past year.  I think you are good for small things like the occasional power outage (<4 hours) or Internet outage.  I did move my Internet from my cable provider where outages were more common because they coincided with power and they didn't have backups.  The new fiber provider assured me they have plenty of backup and generator to keep the light on.  SMTP standards allow for holding emails for several hours or more (don't know the details off-hand).

I am having good luck with my Azure Function App monitoring.  I am still tweaking it and will post it when I am satisfied with it.  I was actually surprised they allow TCP on port 25 from there but maybe the Function App servers haven't been hit by those firewall rules yet.  Being alerted that the SMTP server is down (and later on maybe add monitoring for other services on there as well) is probably the best thing for me for now.  If it gets bad enough then I can always move my email domain to a hosting service.  So far I'm still free and learning so those are good things.  I also have options for backup Internet (cell) although I don't know how well that would work and if they block ports as well.

**Comment by wernerfred** [comment]
Just wanted to throw in the HA discussion thread here as we now have Discussions activated: https://github.com/docker-mailserver/docker-mailserver/discussions/2391

**Comment by georglauterbach** [comment]
@wernerfred I'd even go as far as to close this issue in favor of the discussion. What's your take?

**Comment by TimothyGaray** [comment]
I'm good with it.
