### ISSUE TITLE
How are we supposed to work with multiple domains?

### ISSUE THREAD

**Issue by Akronae** [docker-mailserver/docker-mailserver#2373]
# Subject

I have questions about TLS/SSL/STARTTLS/OpenSSL

## Description

Hi,

I know we can add multiple domains mail addresses with `setup.sh`, though how are we supposed to handle SSL for these different domains?

I have several certs in `/etc/letsencrypt` but the mail server would only use the cert associated with  `domainname` in `docker-compose.yml`  

It is said that multiple domains works out of the box, but is that only true for unencrypted use?

Thanks!

![image](https://user-images.githubusercontent.com/17302866/149773863-807e7c25-cfad-401f-8adb-a88cfddc05c5.png)

**Comment by casperklein** [comment]
Generell: Your mail server can only handle one domain/hostname for TLS encryption. So all domain MX records must be pointing to this hostname.

The DNS MX record for `sushisenon.com` must be pointing `mail.appmaville.com`.

On the client site, to send/receive emails for `sushisenmon.com`, you'll also have to configure `mail.appmavile.com` as mail server.

**Comment by Akronae** [comment]
I just added the MX record and it works perfectly.
Thank you.
