### ISSUE TITLE
allow users to change their password

### ISSUE THREAD

**Issue by pn2** [docker-mailserver/docker-mailserver#2375]
I did not find a way to change a user's password except as root through the `setup` function.
When setting up an account for somebody else, it would be great if the owners could choose/change their password themselves. 
Is there some standard way to do so or implement this?

**Comment by frugan-it** [comment]
[https://github.com/docker-mailserver/docker-mailserver/issues/1800](https://github.com/docker-mailserver/docker-mailserver/issues/1800)

**Comment by georglauterbach** [comment]
Closing this, but pinning it, so that it can still be seen by everyone.

**Comment by pbies** [comment]
I have written about that here: https://serverfault.com/questions/1094908/roundcube-does-not-take-password-for-user-at-login

When you turn on password plugin it does make password change possible, but at login (for example in Roundcube) the password is taken from file. At this link I've managed to make login possible with password from database.
