### ISSUE TITLE
Security concerns using podman in rootless mode

### ISSUE THREAD

**Issue by p-fruck** [docker-mailserver/docker-mailserver#2377]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

Podman creates open postfix relay

### What happened and when does this occur?

```Markdown
As you state in your [mailserver.env](https://github.com/docker-mailserver/docker-mailserver/blob/b2b701a4786f91fe266cca4d077a088345fdff5d/mailserver.env#L53), the `network` option might open up an open relay when specifying the wrong network. The default is `localhost`.

When running Podman in rootless mode, all source IP's get translated to localhost by default, so the relay is publicly accessible to the whole WAN side and there is no mention/warning about this anywhere in the wiki.
```

### What did you expect to happen?

```Markdown
I expected this to be an `out-of-the-box secure` solution. I did not know about Podmans behaviour earlier and I think users should be warned or ideally the default config should be updated to secure Podman in rootless mode.
```

### How do we replicate the issue?

```Markdown
1. Launch DMS with Podman in rootless mode
2. Expose port 25
3. The gateway is now open to the public -> Watch your mailserver get used as a spam-distributor :)
```

### DMS version

v10.4.0

### What operating system is DMS running on?

Linux

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### What container orchestration tool are you using?

Podman (not officially supported)

### docker-compose.yml

```yaml
It's the default config provided by the master branch
```

### Other relevant information

```Markdown
This was tested on AlmaLinux 8.5 using Podman 3.3.1 in rootless mode with podman-compose v1.0.2.
Unprivileged port bindings start at 25, I have not configured firewalld redirects to unprivileged ports (but I guess this has no impact on the issue?)
```

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [X] I am inexperienced with mail servers
- [ ] I am uncomfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by georglauterbach** [comment]
> I did not know about Podmans behaviour

We certainly did not too :)

> users should be warned or ideally the default config should be updated to secure Podman in rootless mode

Yes. Can you provide a PR that updates the documentation on this? I do not use Podman and I do not know how to resolve this matter, but maybe you do? A PR would certainly be welcome!

**Comment by polarathene** [comment]
I get the impression that we should have a disclaimer for rootless, LDAP and other support that is largely reliant upon third-party contributions, rather than any official support from core maintainers that don't use any of this to be aware of such risks or breakage issues experienced by others.

---

Curious, how did your experience go with getting to this point with your setup and usage of our docs?

- We have a [Podman section here](https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/podman/), this seems to specifically mention limitations in rootless with port binding, advocating you bind to ports above 1024 (eg, host port 10025 to container port 25), and at the end mentions setup with `firewalld` which you've also mentioned you did not tackle? Is there something missing in our docs there that could have helped you?
- There is a related section about rootless podman/docker in the [Fail2Ban docs page](https://docker-mailserver.github.io/docker-mailserver/edge/config/security/fail2ban/#running-fail2ban-in-a-rootless-container), both of these docs could probably link to one another as that information is probably relevant, addressing the awareness concern you've raised about source IP propogation? (did you configure the `slirp4netns` port driver for podman?)

**Comment by p-fruck** [comment]
@georglauterbach I am still trying to figure out how to get podman to securely run docker-mailserver in rootless-mode, but I haven't managed to do so successfully yet :(

@polarathene I strongly agree with the idea of adding a disclaimer.
To be honest I did not read all the way through the docs to the podman section before setting up the environment and only found it later on because it was the very last entry, but this definitely is my fault :laughing: 
After having discovered the podman section I would do a bunch of things differently. However, I do not think there is a huge difference between exposing port 25 directly or using a firewalld redirect, the behavior of podmans ip-binding should stay the same. The fail2ban section looks really promising though. I did not configure `slirp4netns` as I thought that it is the default podman network driver nowadays, but it seems like I was wrong about that too.

I'll setup a new testing environment following your instructions, try to mitigate the issue and report the results during next week.

**Comment by polarathene** [comment]
> To be honest I did not read all the way through the docs to the podman section before setting up the environment and only found it later on because it was the very last entry, but this definitely is my fault

That's ok, new users can be quite helpful by sharing experiences like this to help identify where the docs could be improved. It's understandable that there's quite a lot to scan through there.

If you have suggestions of where we could better communicate the disclaimer and awareness of specific docs for setups like rootless/podman, that could be helpful too :+1: 

> the behavior of podmans ip-binding should stay the same. The fail2ban section looks really promising though.

Good to know, we should probably add to the podman rootless section a reference to the Fail2Ban page then, or move that sub-section for rootless IP propagation elsewhere (not Podman specific).

**Comment by p-fruck** [comment]
After setting up the debug system, I discovered that the instruction of the fail2ban do prevent this behavior indeed, but unfortunately the are incompatible with `podman-compose` (I might open an issue over there too). Before creating a PR, I wanted to suggest configuring postfix directly instead of letting the user take care of the security.

As described in the [postfix docs ](http://www.postfix.org/BASIC_CONFIGURATION_README.html#relay_from), the `mynetworks` variable can be set to an empty string, to require authentication even from localhost. If you are ok with this soulution, I'd be happy to implement in a PR, otherwise I will only document the required steps that a user must perform to secure an existing installation. Please tell me which of these two options you like best :)

**Comment by georglauterbach** [comment]
I'd only go for a documentation update.

**Comment by p-fruck** [comment]
Is there a specific reason you do not want to change the postfix config?

**Comment by casperklein** [comment]
If I understand correctly, this would break `PERMIT_DOCKER=host` and therefor setups relying on that?

**Comment by p-fruck** [comment]
Good point! How about adding a new keyword like `PERMIT_DOCKER=none` to disable local authentication?

**Comment by p-fruck** [comment]
> Did you try `PERMIT_DOCKER=`? Then only the container IP should be allowed to send unauthenticated mails:

This is exactly the issue with podman, since in the default compose network setup (without `slirp4netns`) every ip looks like it originates from localhost. 

> I think there's no reason not to implement something like that.

Will be implemented soon :)
