### ISSUE TITLE
[FR] Support crictl in setup.sh

### ISSUE THREAD

**Issue by dfoxg** [docker-mailserver/docker-mailserver#2378]
# Feature Request

At the moment, [only docker and podman are support](https://github.com/docker-mailserver/docker-mailserver/blob/master/setup.sh#L197) for interacting with a running mailserver-container. Since [docker as runtime is deprecated in Kubernetes](https://kubernetes.io/blog/2020/12/02/dockershim-faq/), the script may not longer work when docker is phased out.

### Is your Feature Request related to a Problem?

Yes, I´m unable to use the setup-script in my k3s-cluster.

### Describe the Solution you'd like

It would be great, if the script would also support [crictl](https://github.com/kubernetes-sigs/cri-tools/blob/master/docs/crictl.md) which has a symilar syntax.

### Are you going to implement it?

Yes, because I know the probability of someone else doing it is low and I can learn from it.

### Who will that Feature be useful to?

Every user of docker-mailserver in a k8s environment.

### What have you done already?

nothing

**Comment by georglauterbach** [comment]
The bad news: while this is a good idea, it would introduce maintenance overhead to `setup.sh` which is there for Docker and Podman more or less esclusively.

The good news: with #2174 and #2189 the `setup.sh` **functionality is included in the container** itself. You should therefore be able to use this functionality:

``` CONSOLE
$ kubectl exec -ti mail_server_pod -- setup help
SETUP(1)

NAME
    setup - 'docker-mailserver' Administration & Configuration script
...
```

This is stated in the README as well in the [Get the Tools](https://github.com/docker-mailserver/docker-mailserver#get-the-tools) section right in the beginning.

**Comment by dfoxg** [comment]
Okay, fine for me. Thanks for the reply!
