### ISSUE TITLE
SSL documentation contains a small bug

### ISSUE THREAD

**Issue by Twist235** [docker-mailserver/docker-mailserver#2381]
# Subject

I would like to contribute to the project

## Description
I propose to perform a documentation update:

Section: 
Let's Encrypt (Recommended)
Subsection:
Example

Add these additions to the mailserver service in your docker-compose.yml:

services:
  mailserver:
    # For the FQDN 'mail.example.com':
    hostname: mail
    domainname: example.com
    environment:
      - SSL_TYPE=letsencrypt
    volumes:
      **- /etc/letsencrypt:/etc/letsencrypt**

Change bold part to 
      **- ./docker-data/certbot/certs/:/etc/letsencrypt**

Description of problem:
In this example, a different path is used than in the following Example "using Docker for Let's Encrypt". I propose to use the same path both times. This cost me some time to find, when I follow the examples the docker restarts and I did not understand why.

I would be happy to update it myself (and maybe add some sentences for DNS cert which I used) but I do not have the rights (new to github).

**Comment by georglauterbach** [comment]
Thank you for reporting this.

> I would be happy to update it myself (and maybe add some sentences for DNS cert which I used) but I do not have the rights (new to github).

Please just have a look at [our documentation on how to contribute to this project](https://docker-mailserver.github.io/docker-mailserver/edge/contributing/issues-and-pull-requests/#pull-requests). Quick read and you should be able to open a PR (pull request) which we can then review and merge if appropriate.
