### ISSUE TITLE
How to reject spam that uses my domain as from address

### ISSUE THREAD

**Issue by tve** [docker-mailserver/docker-mailserver#2386]
I'm regularly getting spam and threats whose FROM is in my own domain. E.g. `FROM: me@example.com` `TO: me@example,com`, typically it starts with something like "Hey, sorry to tell you but as you can see I hacked into your account..."
I have a slightly older set-up of docker-mailserver, but looking at master it does not seem that there is any protection against this? If not, I believe that the solution includes:
```
smtpd_sender_restrictions = permit_sasl_authenticated,
        check_sender_access hash:/etc/postfix/access
```
from: https://superuser.com/a/1148938/374292

I do not believe this is supported by docker-mailserver. Am I missing anything?

**Comment by casperklein** [comment]
You should setup a SPF DNS record for your domain if possible. This will not only prevent you from getting spam, but also others.

**Comment by tve** [comment]
I do have an SPF record, but it ends with a soft-fail (~all), I assume you're really saying "set up a SPF DNS record with a hard fail"?

**Comment by casperklein** [comment]
Yes. You should set it to `-all`.

**Comment by georglauterbach** [comment]
> I do have an SPF record, but it ends with a soft-fail (~all), I assume you're really saying "set up a SPF DNS record with a hard fail"?

Using SPF with `~all` (soft fail) is mostly used when transitioning. You should definitely switch to `-all` (fail).

See [this post](https://serverfault.com/a/355513).

**Comment by GoliathLabs** [comment]
Hello, thank you for your nice work.

since we are talking about spam, I am currently receiving a few mails that use a faulty From-Header-Value
```
mailserver-mailserver-1  | Feb  5 10:51:25 mail opendkim[609]: 2CE32360335: can't parse From: header value ' Sofortige Zustellung'
mailserver-mailserver-1  | Feb  5 10:51:25 mail opendmarc[616]: 2CE32360335: unable to parse From header field
```
docker-mailserver rewrites these from fields to Sofortige@mail.mydomain.com and Zustellung@mail.mydomain.com.
I have set up a correct SPF record with a hard reject policy. Is there a method to reject these messages with an incorrect from header, for example?
Postgrey already delays these spam messages accordingly, yet they still end up in my junk folder.

**Comment by GoliathLabs** [comment]
It is also worth noting that the following is written in the header:
```
Received-SPF: Permerror (SPF Permanent Error: Invalid IP4 address: ip4:fe80::50c8:ff:fe5c:32d5) identity=helo; client-ip=spamserversip; helo=thespammersdomain.com, envelope-from=info@mail.windstream.syn-alias.com; receiver=<UNKNOWN> 
Authentication-Results:mail.mydomain.de; dkim=permerror (bad message/signature format)
```

**Comment by georglauterbach** [comment]
You could try to block them

1. by rejecting DKIM failures
2. with Fail2Ban
3. I guess there is a Postfix `block_` rule, that I don't know of :D (this would certainly be the best option IMO)

**Comment by GoliathLabs** [comment]
@georglauterbach also thought of this, will look for the right `reject_` rule of Postfix then. Thanks :P

**Comment by georglauterbach** [comment]
If you find it, please post it here so that when other search for it, they can find it easily. And then please also close this issue :D

**Comment by GoliathLabs** [comment]
Looks like this should be it (in conjunction with OpenDKIM ofc) https://serverfault.com/questions/587798/using-dkim-in-my-server-for-multiple-domains-websites.

Would it be a good idea to implement this directly in docker-mailserver, or is it too much of an edge case?

I'm not the one who opened this topic though. I'm just another user of docker-mailserver who is struggling with the same problem :)

**Comment by georglauterbach** [comment]
@GoliathLabs sorry, mistook you for OP. DMS is already supporting OpenDKIM. AFAIK, if you're running multiple domains, the scripts will create keys for each domain. You can get more info n that by running `docker run mailserver/docker-mailserver[:your tag] setup config dkim help`.

**Comment by GoliathLabs** [comment]
Yes, I am already using OpenDKIM and have also added the correct DKIM records to my domains. That's why I was wondering why DMS doesn't filter out these mails even though OpenDKIM is properly configured 🥲

**Comment by GoliathLabs** [comment]
Okay, what would you recommend to me? I think that the SPF fail will do the job

**Comment by georglauterbach** [comment]
> Okay, what would you recommend to me? I think that the SPF fail will do the job

I think this is the most sane default, yes. If this is not enough, you can always try enable DKIM too, etc.

**Comment by GoliathLabs** [comment]
> > Okay, what would you recommend to me? I think that the SPF fail will do the job
> 
> I think this is the most sane default, yes. If this is not enough, you can always try enabling DKIM too, etc.

Okay, thank you very much! 😄

**Comment by georglauterbach** [comment]
> > > Okay, what would you recommend to me? I think that the SPF fail will do the job
> > 
> > 
> > I think this is the most sane default, yes. If this is not enough, you can always try enabling DKIM too, etc.
> 
> Okay, thank you very much! smile

You're welcome :D

**Comment by GoliathLabs** [comment]
One question though, should I add the header_checks.pcre file to the (then newly added) `config/maps` or should I mount it manually?

**Comment by georglauterbach** [comment]
If the `config/maps` feature works, I guess it's up to you (I have not used it myself and cannot tell you whether it is appropriate). You could even use `user-patches.sh` and a heredoc to create the file. In the end, if you're fine with the solution and the solution is clean, all is well.

**Comment by GoliathLabs** [comment]
I have just manually mapped the file into the container. Let's see if that does anything about the spam. Thanks again @georglauterbach for your help and thanks to all of you for your great work on this project! Much appreciated! 😄
