### ISSUE TITLE
Not receiving transactional emails

### ISSUE THREAD

**Issue by elmaester** [docker-mailserver/docker-mailserver#2392]
# Subject

Other

## Description

I can receive emails, but it appears as if not from all sources? I promptly get emails when I send them myself from my gmail account, and several friends have successfully sent me emails from their gmail accounts too. But I can't seem to get any transactional sign-up emails. Can't create a twitter, facebook etc account, I'm not receiving verification emails. What could be the reason? Thank you.

**Comment by ontheair81** [comment]
You could check the log files to check why you don't reveive these e-mails.

My assumption is: You have checks by Spamhaus enabled. This leads - in my experience - to a lot of missed e-mails (even from Github). Have a look in the pinned threads, there are more informations about that.

**Comment by elmaester** [comment]
@ontheair81 thank you for your response!

Sorry to be ignorant, let me ask:

> You have checks by Spamhaus enabled

**Where** do I have them enabled exactly? Where can I change that configuration?

> Have a look in the pinned threads

Where are those threads pinned? Could you kindly provide a link? Again, apologies for my ignorance.

> You could have a look at the log files

Would you know off the top of your head what's the path? If not, no worries. And thank you very much!

**Comment by ontheair81** [comment]
Just do a generic log view by `docker logs [your container name] -f` and see what happens when you expect such an e-mail to arrive.

The pinned threads are on top of the issues page. [Here](https://github.com/docker-mailserver/docker-mailserver/issues/1927) is the thread about Spamhaus / DNS block and how to disable it.

Again, this is just an assumption that this could be the problem in your case. For sure the logs will tell more details.

**Comment by casperklein** [comment]
If you are using the latest version (10.4), you can disable DNS block list with: `ENABLE_DNSBL=0`.

However, this is now the default setting. So unless you explicit enabled it with `ENABLE_DNSBL=1`, DNS block lists should be disabled.

In any case, you should check your logs. Also check your MX record. Maybe there is a second MX record?

**Comment by elmaester** [comment]
```
Feb  4 19:03:57 mail postfix/postscreen[850909]: CONNECT from [5.157.254.25]:35561 to [172.26.0.2]:25
Feb  4 19:03:57 mail postfix/dnsblog[850913]: addr 5.157.254.25 listed by domain list.dnswl.org as 127.0.10.3
Feb  4 19:04:00 mail postfix/postscreen[850909]: PASS NEW [5.157.254.25]:35561
Feb  4 19:04:00 mail postfix/smtpd[850927]: connect from mx2.archfollowis.com[5.157.254.25]
Feb  4 19:04:00 mail policyd-spf[850937]: prepend Received-SPF: Pass (mailfrom) identity=mailfrom; client-ip=5.157.254.25; helo=mx2.archfollowis.com; envelope-from=meera@archfollowis.com; receiver=<UNKNOWN> 
Feb  4 19:04:00 mail dovecot: auth: passwd-file(rsbdmuhevirpgmtqdrekpbvbwjljyo@oleg.date): unknown user 
Feb  4 19:04:01 mail postfix/smtpd[850927]: NOQUEUE: reject: RCPT from mx2.archfollowis.com[5.157.254.25]: 550 5.1.1 <RSBdmuhevIrpgmTqdrekpBVbWJljYo@oleg.date>: Recipient address rejected: User unknown in virtual mailbox table; from=<meera@archfollowis.com> to=<RSBdmuhevIrpgmTqdrekpBVbWJljYo@oleg.date> proto=ESMTP helo=<mx2.archfollowis.com>
Feb  4 19:04:01 mail postfix/smtpd[850927]: disconnect from mx2.archfollowis.com[5.157.254.25] ehlo=1 mail=1 rcpt=0/1 quit=1 commands=3/4
Feb  4 19:04:01 mail postfix/postscreen[850909]: CONNECT from [77.36.98.8]:22407 to [172.26.0.2]:25
Feb  4 19:04:01 mail postfix/dnsblog[850911]: warning: dnsblog_query: lookup error for DNS query 8.98.36.77.list.dnswl.org: Host or domain name not found. Name service error for name=8.98.36.77.list.dnswl.org type=A: Host not found, try again
Feb  4 19:04:07 mail postfix/postscreen[850909]: PASS NEW [77.36.98.8]:22407
Feb  4 19:04:07 mail postfix/smtpd[850927]: connect from mx2.primeandpiper.com[77.36.98.8]
Feb  4 19:04:07 mail policyd-spf[850937]: prepend Received-SPF: Pass (mailfrom) identity=mailfrom; client-ip=77.36.98.8; helo=mx2.primeandpiper.com; envelope-from=chris@primeandpiper.com; receiver=<UNKNOWN> 
Feb  4 19:04:07 mail postfix/smtpd[850927]: EF5CF456F9: client=mx2.primeandpiper.com[77.36.98.8]
Feb  4 19:04:07 mail postfix/smtpd[850927]: disconnect from mx2.primeandpiper.com[77.36.98.8] ehlo=1 mail=1 rcpt=1 quit=1 commands=4
```

Help me make sense of this?

**Comment by casperklein** [comment]
> Feb  4 19:03:57 mail postfix/dnsblog[850913]: addr 5.157.254.25 listed by domain list.dnswl.org as 127.0.10.3

There is DNS blocking in place. So you either are using an old version of DMS or have enabled it on purpose.

Please provide some more information of your setup, at least

- What container orchestration tool are you using? `docker-compose`?
  - What does your docker-compose file looks like
- What does your MX record(s) look like. If `oleg.date` is your domain, I saw **two** MX records.

**Comment by elmaester** [comment]
Hi, @casperklein , you are right on both counts.
```
MX	oleg.date	94.103.188.50	        600	10	
MX	oleg.date	fwd2.porkbun.com	600	20
```
The second record came by default from the domain registrar, I didn't know if I should touch it. Should I remove it? Might it be the solution?
And here's the docker-compose.yml
Thank you for your help!
```
version: "3.3"

services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    # If the FQDN for your mail-server is only two labels (eg: example.com),
    # you can assign this entirely to `hostname` and remove `domainname`.
    hostname: mail
    domainname: oleg.date
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - ./docker-data/dms/custom-certs/:/tmp/dms/custom-certs/:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - SSL_TYPE=manual
      - SSL_CERT_PATH=/tmp/dms/custom-certs/domain.cert.pem
      - SSL_KEY_PATH=/tmp/dms/custom-certs/private.key.pem
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
```

**Comment by r3dey3** [comment]
Also I just noticed that the "latest" docker tag does not include the ENABLE_DNSBL setting support. (only edge does) - so if you're running into dns blacklist issues, try switching to edge

**Comment by casperklein** [comment]
That's correct, my fault. It will be in the next `10.5.0` release.

**Comment by casperklein** [comment]
If you don't want your registrar to get your emails, then remove that MX record. It has a lower priority, however MTAs might use this, if there are problems with your primary MX (for example, DNS block lists).

I would try:

1. removing the second MX record
2. disabling DNS block lists

**Comment by elmaester** [comment]
I removed the second MX record, switched to edge and set the environment variable: `ENABLE_DNSBL=0`. It helped, I am now getting those emails. Thank you for all the help! Cheers 🍻
