### ISSUE TITLE
[BUG]  virtual_alias_maps contains the regexp entry multiple times

### ISSUE THREAD

**Issue by r3dey3** [docker-mailserver/docker-mailserver#2394]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

postfix

### What happened and when does this occur?

```Markdown
virtual_alias_maps ends up with multiple `pcre:/etc/postfix/regexp` entries
```

### What did you expect to happen?

```Markdown
Only a single entry
```

### How do we replicate the issue?

```Markdown
1. Start dms
2. create data/config/postfix-regexp.cf
2. edit the alias file; wait one second
3. edit the alias file; again
```

### DMS version

edge

### What operating system is DMS running on?

Linux

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### What container orchestration tool are you using?

Docker

### Other relevant information

```Markdown
The sed line in `_handle_postfix_regexp_config` that adds the config to `virtual_alias_maps` is not guarded by a check to see if it is already present in the file. 

I think it may be possible to just always include the `pcre:/etc/postfix/regexp` as `_handle_postfix_virtual_config` always creates that file as empty.
```

### What level of experience do you have with Docker and mail servers?

- [X] I am inexperienced with docker
- [ ] I am inexperienced with mail servers
- [X] I am uncomfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by georglauterbach** [comment]
Thank you for reporting this. This indeed seems to be a bug. I will provide a PR.

**Comment by georglauterbach** [comment]
Well, the fix turned out to be a bit more subtle than your proposition :D I first of all overlooked something obvious, and now came back to see my initial mistake. We actually **have** to guard with a `grep` because the alias construction is executed with `check-for-changes.sh`. This is - thanks for this clue BTW - why you see the `/etc/postfix/regexp` being added when `check-for-changes .sh` ran after one second each. Nice catch!
