### ISSUE TITLE
"Backup MX" headline is misleading in spf docs

### ISSUE THREAD

**Issue by uncaught** [docker-mailserver/docker-mailserver#2395]
# Subject

Other

## Description

The headline ["Backup MX, Secondary MX"](https://github.com/docker-mailserver/docker-mailserver/blob/master/docs/content/config/best-practices/spf.md#backup-mx-secondary-mx) is misleading. The section is about white listing, not about secondary MX per se.

Having the headline phrased like this suggests that this white listing is something you need to do to be able to use backup MX or secondary MX. But with the ["Add a SPF Record"](https://github.com/docker-mailserver/docker-mailserver/blob/master/docs/content/config/best-practices/spf.md#add-a-spf-record)-section above, stating you should use `v=spf1 mx -all`, and the [spf-documentation](http://www.open-spf.org/SPF_Record_Syntax/) stating "Allow **domain's MXes** to send mail for the domain, prohibit all others", I would assume that white listing is in fact _not_ a best-practise. You should rather add backup and secondary servers as additional MX records and then the SPF will work fine without white listing.

To not confuse newcomers like me, please change the headline to something like "Whitelisting" or "Custom SPF Policy".

**Comment by casperklein** [comment]
Feel free to enhance our documentation. Just edit the file and provide a pull-request 👍 

I think you misunderstood SPF here. The example is for whitelisting a backup MX. Typically, a backup MX will send all mails to the primary, when it's reachable again (in case of an outage). When the backup MX receives an e-mail from an @gmail.com address, it will forward the mail to the main mail server. From the main mail server perspective, the backup MX is not allowed to send mails on behalf of gmail.com (SPF check will fail). Therefore you have to exclude the backup MX from the SPF check.

**Comment by uncaught** [comment]
Sorry, forgot to close.

Thank you for your explanation! I was wrong and confused.
