### ISSUE TITLE
[Question] Migration from OpenLDAP to authentik, dovecot issue

### ISSUE THREAD

**Issue by cybermcm** [docker-mailserver/docker-mailserver#2396]
# Migration from OpenLDAP to authentik

I would like to configure a not documented mail server use case

## Description
Currently, I try to migrate from openLDAP to authentik. I managed to get it working for other services, like portainer or nextcloud, but I'm struggling with mailserver/dovecot
Connection to authentik is working but error message is
`LDAP search returned multiple entries`

my config (the relevant part)
``` BASH
LDAP_SERVER_HOST=authentik-ldap:3389 # authentik
LDAP_SEARCH_BASE=dc=ldap,dc=goauthentik,dc=io # authentik
LDAP_BIND_DN=cn=xxx,ou=users,dc=ldap,dc=goauthentik,dc=io # authentik
LDAP_BIND_PW=xxx # authentik
LDAP_QUERY_FILTER_USER=(&(mail=%s)(mailEnabled=TRUE)) # authentik
LDAP_QUERY_FILTER_GROUP=(&(mailGroupMember=%s)(mailEnabled=TRUE)) # authentik
LDAP_QUERY_FILTER_ALIAS=(&(mailAlias=%s)(mailEnabled=TRUE)) # authentik
LDAP_QUERY_FILTER_DOMAIN=(|(&(mail=*@%s)(mailEnabled=TRUE))(&(mailalias=*@%s)(mailEnabled=TRUE))) # authentik
DOVECOT_PASS_ATTRS=mail=user,password=password # for authentik only
DOVECOT_USER_ATTRS=mailHomeDirectory=home,mailStorageDirectory=mail,uidNumber=uid # for authentik only
DOVECOT_USER_FILTER=cn=%n # for authentik only
ENABLE_SASLAUTHD=1
SASLAUTHD_MECHANISMS=rimap
SASLAUTHD_MECH_OPTIONS=127.0.0.1 # use for smtp auth same as dovecot
```
I added the following attributes for my users in authentik:
```
mailAlias: xxx
mailEnabled: true
mailHomeDirectory: xxx
mailStorageDirectory: xxx

```
I think the problem is with the DOVECOT vars, tried different things but as of now no luck...
maybe someone can point me in the right direction?

**Comment by georglauterbach** [comment]
The core maintainer's team is currently lacking LDAP developers (as documented in the `README.md`, just recently). We actually see more problems with LDAP than we'd like to... but since we (the core maintainers) are not using LDAP, we currently rely on out community. Of course, we will leave this issue open - maybe someone can help you.

**Comment by cybermcm** [comment]
@georglauterbach: thanks for the quick info, I'm no expert at all, but I like the idea of a centralized authentication system. Maybe someone has an idea, authentik is a nice tool with many capabilities...

**Comment by georglauterbach** [comment]
Although I'm not a fan of LDAP, it if common. Why do you prefer Authentik over OpenLDAP? I'm curious as I have no idea how these two differ :)

**Comment by cybermcm** [comment]
openldap is old, my main reason to switch.
authentik is often used in home environments, like my lab. Authenik is able to provide SAML2, OAuth2 and OIDC authentication and can provide LDAP auth as server as well.
Nice web interface with 2factor auth....
all in one wonder ;-)

**Comment by wernerfred** [comment]
Just read the documentation on authentik and found this sentence:

> All users and groups in authentik's database are searchable. Currently, there is limited support for filters (you can only search for objectClass), but this will be expanded in further releases.

Maybe your usecase is not supported in the current release as you can't filter properly?

**Comment by cybermcm** [comment]
@wernerfred: Thanks for the input, but as I stated in OP there are apps which already work. I'm not sure why the LDAP search returns multiple entries when searching for a cn. There is only one user with this cn....

**Comment by cybermcm** [comment]
Update from my side: After playing around, I did manage to get LDAP auth working.
The essential part (with comments):
```
- ENABLE_LDAP=1
- LDAP_SERVER_HOST=${mail_LDAP_SERVER_HOST} # authentik ldap container
- LDAP_SEARCH_BASE=${mail_LDAP_SEARCH_BASE}
- LDAP_BIND_DN=${mail_LDAP_BIND_DN} # user from auhentik admin group
- LDAP_BIND_PW=${mail_LDAP_BIND_PW}
- LDAP_QUERY_FILTER_USER=(&(cn=%s)(mailEnabled=TRUE))
- LDAP_QUERY_FILTER_GROUP=(&(member=%s)(mailEnabled=TRUE)) # NOT tested, won't work as member contains full DN, not mail addresses
- LDAP_QUERY_FILTER_ALIAS=(&(mailAlias=%s)(mailEnabled=TRUE))
- LDAP_QUERY_FILTER_DOMAIN=(|(&(mail=*@%d)(mailEnabled=TRUE))(&(mailalias=*@%d)(mailEnabled=TRUE)))
- DOVECOT_AUTH_BIND=yes # for authentik only
- DOVECOT_PASS_ATTRS=cn=user
- DOVECOT_USER_ATTRS=uidNumber=uid,gidNumber=gid,mailHomeDirectory=home,mailStorageDirectory=mail
- DOVECOT_USER_FILTER=(&(cn=%u)(objectClass=user))
```
- my users have username = primary mail address
- mailHomeDirectory and mailStorageDirectory have to be setup in authentik as attributes as well as mailEnabled and mailAlias
- If you migrate, you have to pay attention to file permissions, dovecot expects file permissions from user, e.g. 2001:2001 and standard without LDAP is 5000:5000

One caveat (major one): authentication is slow, e.g. changing from one folder into another (webmail) takes about one second (too slow for me). That didn't happen with openldap. Will have to investigate further with the authentik team.
Will close this one though...

**Comment by georglauterbach** [comment]
Thanks for keeping us posted! The permissions are a problem indeed. Feel free to chime into #2256 🙈

**Comment by NhProGamer** [comment]
hey @cybermcm i'm sorry to bother you but i have problems to make that shit work, can you send me your configs ?

**Comment by cybermcm** [comment]
@NhProGamer: I think my relevant config is here https://github.com/docker-mailserver/docker-mailserver/issues/2396#issuecomment-1033563881
I switched back to auth via local file since I couldn't work out the lag due to LDAP auth. But there was big improvement in Authentik LDAP auth since then, maybe this is solved by now

**Comment by joewashear007** [comment]
@cybermcm Thank for the direction, I was able to get the LDAP working with Authentik , here is the config I used since my username != email. I had to use the `mail` attribute for finding the users

```
LDAP_QUERY_FILTER_USER=(&(mail=%s)(mailEnabled=true))
LDAP_QUERY_FILTER_ALIAS=(&(mailAlias=%s)(mailEnabled=true))
LDAP_QUERY_FILTER_DOMAIN=(&(|(mail=*@%s)(mailalias=*@%s)(mailGroupMember=*@%s))(mailEnabled=true))


DOVECOT_AUTH_BIND=yes
DOVECOT_PASS_ATTRS=mail=user
DOVECOT_USER_ATTRS=uidNumber=uid,gidNumber=gid,mailHomeDirectory=home
DOVECOT_USER_FILTER=(&(mail=%u)(objectClass=user))
```
