### ISSUE TITLE
I must be doing something incorrectly

### ISSUE THREAD

**Issue by jdqw210** [docker-mailserver/docker-mailserver#2408]
would like some feedback concerning a use case

I cannot seem to for the life of me get this to work, I end up with this error after disabling most features just to get a bare-minimum mailserver working to go on from:

``` 
mailserver    | Feb 11 09:06:14 mailsrv postfix/submission/smtpd[1527]: warning: hostname xxxxx.xxxxx.xxxxx.starlinkisp.net does not resolve to address xxx.xxx.177.235: Name or service not known
mailserver    | Feb 11 09:06:14 mailsrv postfix/submission/smtpd[1527]: connect from unknown[xxx.xxx.177.235]
mailserver    | Feb 11 09:06:14 mailsrv postfix/submission/smtpd[1531]: improper command pipelining after EHLO from unknown[xxx.xxx.177.235]: QUIT\r\n
mailserver    | Feb 11 09:06:14 mailsrv postfix/submission/smtpd[1531]: disconnect from unknown[xxx.xxx.177.235] ehlo=1 quit=1 commands=2
mailserver    | Feb 11 09:06:14 mailsrv postfix/submission/smtpd[1527]: improper command pipelining after EHLO from unknown[129.222.177.235]: QUIT\r\n
mailserver    | Feb 11 09:06:14 mailsrv postfix/submission/smtpd[1527]: disconnect from unknown[xxx.xxx.177.235] ehlo=1 quit=1 commands=2
mailserver    | Feb 11 09:06:14 mailsrv postfix/postscreen[1504]: COMMAND PIPELINING from [xxx.xxx.177.235]:61207 after EHLO: QUIT\r\n
mailserver    | Feb 11 09:06:14 mailsrv postfix/postscreen[1504]: DISCONNECT [xxx.xxx.177.235]:61207
mailserver    | Feb 11 09:06:14 mailsrv postfix/postscreen[1504]: COMMAND PIPELINING from [xxx.xxx.177.235]:46460 after EHLO: QUIT\r\n
mailserver    | Feb 11 09:06:14 mailsrv postfix/postscreen[1504]: DISCONNECT [xxx.xxx.177.235]:46460

```

**Comment by georglauterbach** [comment]
> `warning: hostname xxxxx.xxxxx.xxxxx.starlinkisp.net does not resolve to address xxx.xxx.177.235: Name or service not known`

Seems like a DNS issue to me. You can verify or try this out by `docker exec -ti <YOUR DMS CONTAINER NAME> bash` to get a shell inside the container and try to resolve some addresses. `dig` is not installed by default, but you can run

``` CONSOLE
$ apt update
$ apt install dnsutils
$ dig google.de
```

If you see a record and an IP being shown, DNS works.

Moreover, it seems as if `xxxxx.xxxxx.xxxxx.starlinkisp.net` does not behave correctly when sending an email: a `QUIT` follows an `EHLO`. I really suggest you to [look for the cause of this in the internet](https://www.google.com/search?channel=fs&client=ubuntu&q=improper+command+pipelining+after+ehlo), as this is not `docker-mailserver` specific, but actually Postfix.
