### ISSUE TITLE
SpamAssassin - KAM channel auto-update

### ISSUE THREAD

**Issue by ghnp5** [docker-mailserver/docker-mailserver#2412]
Hey

For keeping `KAM.cf` up to date, they have a channel:
https://mcgrail.com/template/kam.cf_channel

`wget https://mcgrail.com/downloads/kam.sa-channels.mcgrail.com.key`
`sa-update --import kam.sa-channels.mcgrail.com.key`

Then in a cron:

`sa-update --gpgkey 24C063D8 --channel kam.sa-channels.mcgrail.com`

I know I can run some custom commands on start-up of the mailserver,
but,

1) Do you have already anything that makes this easy to do?

2) Would you consider making this native of the mailserver, as a setting in the env file? e.g. `SPAMASSASSIN_KAM_CHANNEL=1`

Thank you very much.

**Comment by ghnp5** [comment]
Ah, I think I got my answer. Looking at the start-mailserver.sh, it appears that SpamAssassin runs under Amavis.

Related post: https://www.howtoforge.com/community/threads/spamassassin-automated-update.72393/

`/etc/cron.daily/spamassassin` will fail to reload spamassassin,

BUT, there is this file:

```
# cat /etc/spamassassin/sa-update-hooks.d/amavisd-new 

#!/bin/sh

#This scripts restarts amavisd-new after spamassassin
#rules got updated

(...)
```

Perfect, then!

**Comment by georglauterbach** [comment]
I'd encourage you to open a PR. You can put the functionality right somewhere in between:

https://github.com/docker-mailserver/docker-mailserver/blob/ce9e86c4622947dff9e4b0ff092a9fb90fcf9dd5/target/scripts/startup/setup-stack.sh#L1316-L1376

You may want to _append_ the update to `/etc/cron.daily/spamassassin`, but not sure on that either. When you opened a PR, the other maintainers will review it, so no worries.

**Comment by ghnp5** [comment]
Hey - I'll not have the time to do that yet, but here's how I did it in `user-patches.sh`:

```
# SpamAssassin KAM - https://mcgrail.com/template/kam.cf_channel
sa-update --import /etc/spamassassin/kam-key/kam.sa-channels.mcgrail.com.key
printf '#!/bin/sh\n\nsa-update --gpgkey 24C063D8 --channel kam.sa-channels.mcgrail.com --gpghomedir /var/lib/spamassassin/sa-update-keys -v 2>&1\n' > /etc/cron.daily/aaa_spamassassin_KAM
chmod +x /etc/cron.daily/aaa_spamassassin_KAM

# Note: SpamAssassin runs under Amavis  (so there isn't a "spamd" process)
# /etc/spamassassin/sa-update-hooks.d/amavisd-new   takes care of reloading SpamAssassin after rules are updated
# So, there is no point running "/etc/init.d/spamassassin reload", because it will fail   ("/etc/cron.daily/spamassassin" runs this command, but fails)
```

I named it `aaa_****` just so it runs before `spamassassin`

**Comment by georglauterbach** [comment]
Maybe the core maintainers team will tend to it. If you have time in the future, please see whether you can tend to it :)
