### ISSUE TITLE
Limiting log size / deleting old logs

### ISSUE THREAD

**Issue by kreck90** [docker-mailserver/docker-mailserver#2413]
# Subject

/question

Limiting log size / deleting old logs.

## Description

Hi all,

I installed docker-mailserver just for me and my family and it's great. Thank you so much for your fantastic work!

Could you please recommend a way to delete logs / limit size?

I've just noticed that my mailserver is down and after some investigation I realized that log files are huuuuge and that I don't have disk space :D.

I fixed that easily by:

``` sh
sudo sh -c '> directory_with_logs/mail.log'
sudo sh -c '> directory_with_logs/mail.info'
sudo sh -c '> directory_with_logs/mail.log.1'
```

But I was thinking about some more permanent / automatic solution.

I can write Cron / systemd timer to:

``` sh
find directory_with_log -type f -size +500M -delete
```

But I was thinking that Postfix might have some configuration that for example limits log size or something like that...

Thank you.

Kind regards,

Kreckel

**Comment by casperklein** [comment]
This is the logrotate configuration:

```bash
cat /etc/logrotate.d/maillog
/var/log/mail/mail.log
{
  compress
  copytruncate
  delaycompress
  rotate 4
  monthly
}
```

Mail logs are kept for 4 months independent of their size. This can be customized to your needs, check the [manual](https://linux.die.net/man/8/logrotate).

You can customize this file on startup via [user-patches.sh](https://docker-mailserver.github.io/docker-mailserver/edge/faq/#how-to-adjust-settings-with-the-user-patchessh-script).

When you manually delete mail logs, I would stop postfix before: `supervisorctl stop postfix`.

Or the most safe variant: Stop the container (`docker-compose down`), delete the logs on the host (`./docker-data/dms/mail-logs/`) and then start the container again (`docker-compose up -d`).

> I installed docker-mailserver just for me and my family 

500+MB log files seems a lot for your use-case. Maybe you should take a look at the logs and check if everything is okay. Verify, that your server is not an open relay and abused for sending spam mails. You can use an external service like [this](https://mxtoolbox.com/diagnostic.aspx) for verification.

**Comment by georglauterbach** [comment]
500MB log is **_huge_**. As @casperklein mentioned, I'd check what's going on there. Looking at my logs, `du -sh` yields `748K` on the `logs/` directory...

**Comment by kreck90** [comment]
Yeah, it was open relay. I played with `mynetworks` thinking how clever I am and I made a mistake. So I'm not going to change the logging configuration since it was actually a good thing that it used all my disk space and stopped spamming. Apologizes for useless question and thank you very much @casperklein and @georglauterbach for helping out!

**Comment by georglauterbach** [comment]
No worries, glad you could fix it!
