### ISSUE TITLE
mail dovecot: auth: Error: passwd-file /etc/dovecot/userdb: User user@mydomain.com exists more than once

### ISSUE THREAD

**Issue by marcinkunert** [docker-mailserver/docker-mailserver#2416]
# Subject

I would like some feedback concerning a use case

## Description

I have a setup with a "catchall" solution.

I've got a few mailboxes/users defined in `config/postifx-accounts.cf`

Additionally, I've got `config/postfix-virtual.cf`

```
source@mydomain.com target@notmydomain.com
source2@mydomain.com target2@notmydomain.com

source3@mydomain.com source3@mydomain.com
source4@mydomain.com source4@mydomain.com
[...]
source9@mydomain.com source9@mydomain.com

@mydomain.com catchall@mydomain.com
```

With this config I'm getting errors reported in logs:

``` BASH
mail dovecot: auth: Error: passwd-file /etc/dovecot/userdb: User source3@mydomain.com exists more than once
mail dovecot: auth: Error: passwd-file /etc/dovecot/userdb: User source4@mydomain.com exists more than once
mail dovecot: auth: Error: passwd-file /etc/dovecot/userdb: User source5@mydomain.com exists more than once
```

The source3, source4, source5, ..., source9 in `config/postfix-virtual.cf` seem to cause the error, but if I remove them, all emails end up in catchall inbox. Is  there a solution to keep the catchall functionality and get rid of the error message?

**Comment by georglauterbach** [comment]
> The source3 ⇾ source9 in config/postfix-virtual.cf seem to cause the error, but if I remove them, all emails end up in catchall inbox. Is there a solution to keep the catchall functionality and get rid of the error message?

I don't see where `source3` is aliased to `source9` in your report. Can you clarify on that? Using `source4@mydomain.com source4@mydomain.com` in `postfix-virtual.cf` does not seem to make sense to me, I mean, this look like you're aliasing `source4@mydomain.com` to `source4@mydomain.com`?!

You could first examine and show us the contents of `/etc/dovecot/userdb`. This is where the error originates.

**Comment by georglauterbach** [comment]
Now I understand. I'm afraid #1454 is not really up-to-date anymore because we had to rework the alias logic because of issues with multiple aliases (long story..., see #2091). I will see whether we can actually solve this...

**Comment by georglauterbach** [comment]
With #2419, the issue should be resolved. Note that warning messages will be raised during startup (about not adding the aliases twice), but since you know that your setup is safe, you can ignore these messages. I've put them in place for other users to potentially spot misconfigurations.
