### ISSUE TITLE
Selective backup - only what is really needed

### ISSUE THREAD

**Issue by MatXron** [docker-mailserver/docker-mailserver#2430]
# Subject

Question / Other

## Description

THANK YOU FOR THE MAILSERVER, IS AWESOME!

I looked at: https://docker-mailserver.github.io/docker-mailserver/edge/faq/#bind-mounts-default

And the instructions for backup are crystal clear. Especially for somebody who has experience with Docker. Basically you're saying backup all bind mounts - easy and crystal clear.

I spent some time playing with Docker-Mailserver mainly to understand how it works internally and it was easy to discover that data that is needed to move to a new Linux server is only in `dms/config/` and `dms/mail-data/` since I don't need logs and data in is `dms/mail-state/` gets automatically re-generated (great work Docker Mailserver developers / maintainers!!!).

And to be even more selective, the data that really matter is only `dms/mail-data/` since if you loose `dms/config/` then you just need to recreate all accounts, aliases and DKIM and replace DKIM in DNS. Which is easy to do for a small mailserver with a few accounts.

Looking at `dms/mail-data/` (`/var/mail`) - this is a directory with multiple Maildirs generated by Dovecot. Maildirs would normally be stored in user home directories but you cleverly move them into a single bind mount. For my and other people education, could you please tell me: If I backed up only contents of `cur/` directories, is that enough to restore all e-mails?

For example I might backup only:

~~~
example.com/
└── johndoe
    ├── cur
    │   ├── 1645004028.M909374P45291.mailserver,S=1654,W=1686:2,S
    │   ├── 1645004266.M955847P46460.mailserver,S=1651,W=1683:2,S
    │   ├── 1645004292.M785778P46460.mailserver,S=1652,W=1684:2,S
    │   ├── 1645176383.M717272P255688.mailserver,S=1871,W=1906:2,S
    │   ├── 1645176450.M314605P256012.mailserver,S=1872,W=1907:2,S
    │   └── 1645450001.M332099P733717.mailserver,S=1872,W=1912:2,S
    ├── .customfolder
    │   ├── cur
    │   │   ├── 1644751920.M599049P18971.mailserver,S=32038,W=32478:2,S
    │   │   ├── 1644871672.M256152P655671.mailserver,S=16121,W=16550:2,S
    │   │   └── 1645314073.M798963P88667.mailserver,S=20206,W=20649:2,S
    ├── .Sent
    │   ├── cur
    │   │   ├── 1644808818.M439293P289661.mailserver,S=3557,W=3622:2,S
    │   │   ├── 1644895227.M551655P785789.mailserver,S=3559,W=3624:2,S
    │   │   ├── 1644981619.M352669P166263.mailserver,S=3560,W=3625:2,S
    │   │   ├── 1645068019.M673324P380907.mailserver,S=3560,W=3625:2,S
    │   │   ├── 1645154421.M104783P150821.mailserver,S=3801,W=3867:2,S
    │   │   └── 1645240818.M429972P561361.mailserver,S=3801,W=3867:2,S
~~~

And I might ignore all the other "stuff" like `dovecot.list.index`, `dovecot.list.index.log`, `dovecot.index.cache`, `dovecot.index.log`, `dovecot-uidlist`, `dovecot-uidvalidity`, `maildirfolder`.

Or is that other "stuff" needed for Dovecot to work / to restore e-mails?

THANK YOU!

Max

**Comment by georglauterbach** [comment]
I don't really know the answer to your specific question of whether _all_ the directories are necessary if you want to restore _all_ emails. My intuition says yes. Here's my short analysis:

``` CONSOLE
root@node00 /k8s-data/pvc-6170c150-2624-4e90-8fcd-40d7349af44d_mail_data/data  ➜ ls mydomain.com/acc/
Permissions  Size User Group Date Modified Name
drwxr-xr-x      - 5000 5000  21 Feb 11:37  cur
drwxr-xr-x      - 5000 5000  21 Feb 11:35  new
drwxr-xr-x      - 5000 5000  21 Feb 11:35  tmp
.rw-r--r--     27 5000 5000  18 Feb 10:43  dovecot-keywords
.rw-r--r--     53 5000 5000  21 Feb 11:43  dovecot-uidlist
.rw-r--r--      8 5000 5000   3 Jan 10:56  dovecot-uidvalidity
.r--r--r--      0 5000 5000  11 Nov  2021  dovecot-uidvalidity.6115823c
.rw-r--r--    560 5000 5000  20 Feb 09:12  dovecot.index
.rw-r--r--   17Ki 5000 5000  21 Feb 11:37  dovecot.index.cache
.rw-r--r--  4.0Ki 5000 5000  21 Feb 11:43  dovecot.index.log
.rw-r--r--   32Ki 5000 5000  20 Feb 09:12  dovecot.index.log.2
.rw-r--r--  1.2Ki 5000 5000  20 Feb 18:35  dovecot.list.index
.rw-r--r--  2.4Ki 5000 5000  21 Feb 17:16  dovecot.list.index.log
.rw-r--r--    768 5000 5000   3 Jan 10:56  dovecot.mailbox.log
.rw-r--r--     65 5000 5000   3 Jan 10:56  subscriptions
root@node00 /k8s-data/pvc-6170c150-2624-4e90-8fcd-40d7349af44d_mail_data/data  ➜ du -sh mydomain.com/acc/*
4.0K	georglauterbach.com/info/cur
4.0K	georglauterbach.com/info/dovecot.index
20K	georglauterbach.com/info/dovecot.index.cache
8.0K	georglauterbach.com/info/dovecot.index.log
40K	georglauterbach.com/info/dovecot.index.log.2
4.0K	georglauterbach.com/info/dovecot-keywords
4.0K	georglauterbach.com/info/dovecot.list.index
4.0K	georglauterbach.com/info/dovecot.list.index.log
4.0K	georglauterbach.com/info/dovecot.mailbox.log
4.0K	georglauterbach.com/info/dovecot-uidlist
4.0K	georglauterbach.com/info/dovecot-uidvalidity
0	georglauterbach.com/info/dovecot-uidvalidity.6115823c
4.0K	georglauterbach.com/info/new
4.0K	georglauterbach.com/info/subscriptions
4.0K	georglauterbach.com/info/tmp
```

shows that most of the directories `cur`, `new` and `tmp` are actually empty (only `4.0K` in size for the directory itself). The major part of the data is in the hidden files:

``` CONSOLE
root@node00 pvc-6170c150-2624-4e90-8fcd-40d7349af44d_mail_data/data/mydomain.com/acc  ➜ find . -maxdepth 1 -type d -iregex "\..*" -exec du -sh {} \;
37M	.
6.9M	./.Archives.2022
24K	./.Junk
44K	./.Drafts
4.0K	./cur
4.0K	./tmp
28K	./.Archives
26M	./.Archives.2021
3.7M	./.Sent
4.0K	./new
260K	./.Trash
```

So my conclusion is this: I'd definitely go for the hidden folders as they contain data. The other files are so small in comparison, that you may as well save them as well. There is, IMHO, no need to make the backup

1. more complex than absolutely necessary (backups should be [K.I.S.S.](https://en.wikipedia.org/wiki/KISS_principle))
2. more risky (by only saving parts, you don't know what you're likely going to miss when [Murphy](https://en.wikipedia.org/wiki/Murphy%27s_law) kicks in)

**Comment by casperklein** [comment]
`new`, `cur` is where mails are stored, if IMAP is not used.
