### ISSUE TITLE
message_size_limit does not change clamd.conf MaxFileSize

### ISSUE THREAD

**Issue by lexxxel** [docker-mailserver/docker-mailserver#2450]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

ClamAV

### What happened and when does this occur?

```Markdown
I saw that clamd.conf has a fixed MaxFileSize of 25MB. I changed message_size_limit to ~50MB, that would mean, that clamd would not scan such attachments, right? I'm unsure about this behavior, maybe one would like to increase the MaxFileSize?
```

### What did you expect to happen?

```Markdown
ClamAV scans all attachments
```

### How do we replicate the issue?

```Markdown
None
```

### DMS version

v10.4.0

### What operating system is DMS running on?

Linux

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### What container orchestration tool are you using?

Docker Compose

### Other relevant information

```Markdown
POSTFIX_MESSAGE_SIZE_LIMIT=52428800
```

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [ ] I am inexperienced with mail servers
- [ ] I am uncomfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by casperklein** [comment]
I wouldn't consider this as a bug, but maybe a lack of documentation.

You might want to receive large emails, but performance-wise you don't want clamav to scan them. So two separate values make sense.

Personally I think, sending mails larger than 10MB is crazy. There are way better protocols for file exchange 😉

If you want to modify `clamd.conf`, you can use [user-patches.sh](https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/override-defaults/user-patches/) for that.

Something like `sed -i 's/^MaxFileSize.*/MaxFileSize 50M/' /etc/clamav/clamd.conf` should work.

**Comment by lexxxel** [comment]
I agree, it's a lack of documentation or at least a surprising behaviour. 
I can't follow your performance consideration. Many people use clamav in combination with something like nextcloud or simply have no high throughput mailserver and care more about security.
However that is not the point of the discussion and I see how user patches can solve my issue with easy. Thank you for pointing that out. 

I see it as a misconfiguration, that's why I labeled this issue as a bug, but please feel free to change that.

About the craziness factor, it really depends on your usecase for mails. This 8 year old overview about some German mail providers show everything between 10MB and 100MB (https://www.email-vergleich.com/tag/e-mail-anhang-grosse/) with many being higher then 20MB.

**Comment by casperklein** [comment]
> I can't follow your performance consideration. 

It depends on the use-case and the hardware. Using old/slow hardware, a raspberry pi for example, scanning many mails with large attachments, may lock up the whole server for some time.
That is the reason, why clamav decided to set a default upper limit which mails to scan, but let people configure higher values if they are confident, their hardware can handle it.

> About the craziness factor, it really depends on your usecase for mails. 

Absolutely! That was just my personal opinion 😄

**Comment by casperklein** [comment]
In the upcoming version 11, there will be a new configuration option `CLAMAV_MESSAGE_SIZE_LIMIT`, which lets you configure the `MaxFileSize` in clamav.

fyi: While preparing the PR, I found this sources, which state/explain, why a size limit is useful:

- From the clamav man page: **Warning: disabling this limit or setting it too high may result in severe damage to the system.**
- A more detailed [explanation](https://mailing.unix.clam-users.narkive.com/nAl6A0yi/clamav-users-maxscansize-and-maxfilesize)
