### ISSUE TITLE
[BUG] The command 'debug inspect' is invalid

### ISSUE THREAD

**Issue by wolkenschieber** [docker-mailserver/docker-mailserver#2451]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

Setup script

### What happened and when does this occur?

```Markdown
Running `./setup.sh debug inspect` gives an error message. The command is not recognized. Its output is

The command 'debug inspect' is invalid.
Use `./setup.sh help` to get an overview of all commands.
```

However `/setup.sh help` lists the option as available:
```
COMMAND debug :=
        /usr/local/bin/setup debug fetchmail
        /usr/local/bin/setup debug fail2ban [unban <IP>]
        /usr/local/bin/setup debug show-mail-logs
        /usr/local/bin/setup debug inspect
```
```


### What did you expect to happen?

```Markdown
Detailed information about the running instance.
```

### How do we replicate the issue?

```Markdown
1. Run `docker exec mailserver setup debug inspect`
```

### DMS version

v10.5.0

### What operating system is DMS running on?

Linux

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### What container orchestration tool are you using?

Docker Compose

### docker-compose.yml

```yaml
Does not apply
```

### Relevant log output

```shell
Does not apply
```

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [ ] I am inexperienced with mail servers
- [ ] I am uncomfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by wolkenschieber** [comment]
So, I'd vote for dropping the command. No need wrap a docker option here.

**Comment by georglauterbach** [comment]
> So, I'd vote for dropping the command. No need to wrap a docker option here.

I agree 👍🏼
