### ISSUE TITLE
[BUG] SPF fail - openspf.net is no more

### ISSUE THREAD

**Issue by GoliathLabs** [docker-mailserver/docker-mailserver#2459]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

See below

### What happened and when does this occur?

```Markdown
Mar  4 21:56:01 mail policyd-spf[463355]: 550 5.7.23 Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=mfrom
Mar  4 21:56:01 mail postfix/smtpd[463350]: NOQUEUE: reject: RCPT from unknown[redacted]: 550 5.7.23 <myadress@mydomain.de>: Recipient address rejected: Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=mfrom;r=<UNKNOWN>; from=<info@spammer.com> to=<myadress@mydomain.de> proto=ESMTP helo=<spammerdomain.org>
```

### What did you expect to happen?

```Markdown
openspf.net is no more (https://graz4u.at/openspf-net-ist-offline/) (German)

We might want to use another service instead? (http://www.open-spf.org/Tools/)
```

### How do we replicate the issue?

```Markdown
Add header_checks.pcre

/^Received-SPF: Fail.*/ REJECT SPF failures are rejected
/^Authentication-Results:.*spf=fail .*/ REJECT SPF failures are rejected
```

and wait for some server pretending to be somebody else

### DMS version

v10.5.0

### What operating system is DMS running on?

Linux

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### What container orchestration tool are you using?

Docker Compose

### Relevant log output

```shell
Mar  4 21:56:01 mail policyd-spf[463355]: 550 5.7.23 Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=mfrom
Mar  4 21:56:01 mail postfix/smtpd[463350]: NOQUEUE: reject: RCPT from unknown[redacted]: 550 5.7.23 <myadress@mydomain.de>: Recipient address rejected: Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=mfrom;r=<UNKNOWN>; from=<info@spammer.com> to=<myadress@mydomain.de> proto=ESMTP helo=<spammerdomain.org>
```

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [ ] I am inexperienced with mail servers
- [ ] I am uncomfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by casperklein** [comment]
This must be fixed upstream.

`/usr/lib/python3/dist-packages/spf_engine/__init__.py` contains the string `http://www.openspf.net/Why?s={0};id={1};ip={2};r={3}`.

This file is part of the `python3-spf-engine` debian package we are using.

To be clear, the only issue here is a no more reachable URL that is referenced in an error message.

**Comment by casperklein** [comment]
I checked http://www.open-spf.org/Why/API/, but that service doesn't seem to work anymore too. So if we decide to fix it within DMS, we could replace the URL with a static text.
