### ISSUE TITLE
REPORT_INTERVAL => LOGROTATE_INTERVAL

### ISSUE THREAD

**Issue by ghnp5** [docker-mailserver/docker-mailserver#2462]
Hi,

I'm not sure I understand one of the changes made in https://github.com/docker-mailserver/docker-mailserver/pull/2428

> One env variable was renamed: REPORT_INTERVAL => LOGROTATE_INTERVAL

`REPORT_INTERVAL` was the frequency reports were sent.
`LOGROTATE_INTERVAL` is the frequency logs are rotated.

But the description looks confusing now:

> Changes the interval in which a report is being sent.
> **weekly** => Send a report every week
> daily => Send a daily report
> monthly => Send a report every month
>  
> Note: This Variable actually controls logrotate inside the container

Saying "Changes the interval in which a report is being sent." is wrong, right?

**Comment by georglauterbach** [comment]
`REPORT_INTERVAL` was a pretty much useless variable and did not really change anything anymore. If you think the description for `LOGROTATE_INTERVAL` could be better, we're open for proposals :)

**Comment by ghnp5** [comment]
The suggestion is simply not to say "report is being sent", but maybe "logs are being rotated" :)
