### ISSUE TITLE
Makefile job 'backup' broken

### ISSUE THREAD

**Issue by casperklein** [docker-mailserver/docker-mailserver#2465]
# Description

Since we renamed `config` to `config-examples`, this Makefile job no longer works:

https://github.com/docker-mailserver/docker-mailserver/blob/d101d0aa0a802eabf74404a8295a0148f98f9497/Makefile#L16-L20

--> `cp: cannot stat 'config': No such file or directory`

`backup` is part of the `all` job, so there is an error every time `make all` is run.

Anyway, there is no reliable way to detect the `config` directory someone might use, when no container is running. I am not sure, how useful a hard-coded config directory is at all.

Should we fix the job? How?
Or maybe remove that part of the job (Line 19)?

**Comment by polarathene** [comment]
What is the purpose of `backup` here anyway? I thought it was only for local development/testing really, not for maintaining a running deployment?

**Comment by casperklein** [comment]
I checked, if `test/config` is somehow modified while running the tests, but I couldn't find something related. At the moment, I would propose to remove the backup job completely.

**Comment by casperklein** [comment]
> I'm aware of generate-accounts job making a modification.

You are right, I've only looked at the tests and not in the Makefile.

At the moment this happens with the `test/config` directory, when running `make all`:

1. `test/config` directory is backed up
2. `generate-accounts` job adds accounts to `test/config` directory
3. `test/config` directory is duplicated for different jobs
4. `clean` job restores previously backed up `test/config`.

There is for sure room for improvements.

---

For now, I'll propose just to remove the backup/restore option of the `config` directory, to fix the current error.
