### ISSUE TITLE
spam no longer marked as such after being redirected to external address

### ISSUE THREAD

**Issue by craue** [docker-mailserver/docker-mailserver#2474]
My setup:
- docker-mailserver 10.4.0
- one alias which redirects mail to one local account and two external addresses
- ENABLE_SPAMASSASSIN=1
- SPAMASSASSIN_SPAM_TO_INBOX=1
- MOVE_SPAM_TO_JUNK=0

Problem: An incoming spam message sent to the alias is saved in the local account and marked properly as spam (most notably due to the `***SPAM***` subject prefix, and also has a lot of spam-related headers set), but the message looks legit (with the subject prefix and all spam-related headers removed) in both external accounts.

```mermaid
flowchart LR
    A[spam mail] --> C{alias}

    subgraph dms [docker-mailserver]
        C --> D[fa:fa-exclamation spam mail]
    end

    subgraph es [external server]
        C --> E[fa:fa-question legit mail]
    end
```

Is this a bug, expected behavior, or a misconfiguration on my side?

Let me know if you need further information.

**Comment by casperklein** [comment]
+1 for the mermaid chart 😄 

I think it's normal behaviour, to forward an email unmodified to the next hop (external server). How do you ensure, that `external server` is really the last hop? Imagine `external server` would also forward this mail to another mail server and so on. Now if each server adds SPAM headers/subjects, the final email would have a a pretty interesting subject line 😉

**Comment by craue** [comment]
This means SpamAssassin is invoked only for delivering mail into a local account (SA-2)? I thought it would process all incoming mail instead (SA-1).

```mermaid
flowchart LR
    A[spam mail] --> B((SA-1))

    subgraph dms [docker-mailserver]
        B --> C{alias}
        C --> D((SA-2))
        D --> E[local account]
    end
```

**Comment by casperklein** [comment]
I am not a SA/postfix expert. That was just my conclusion of your findings and my personal opinion why I think it's fine how it is 😉
