### ISSUE TITLE
Getting "tar: file changed as we read it" during backup

### ISSUE THREAD

**Issue by groupmsl** [docker-mailserver/docker-mailserver#2476]
# Getting "tar: file changed as we read it" during backup

I would like some feedback concerning a use case

## Description

I am using docker volumes with docker-mailserver, and I have another container who's job it is to backup my mailserver. It has all the volumes of docker-mailserver, plus a bind mount of my local disk - the destination of my backup. This is then backed up off site etc etc. The container runs the simple command below, based off the documentation:

```BASH
tar --gzip -cf "/destination/mailbackup-$(date +%Y%m%d%H%M%S).tar.gz" /var/mail /var/mail-state /var/log/mail /tmp/docker-mailserver
```

Which throws a few warnings:

```
tar: Removing leading `/' from member names
tar: Removing leading `/' from hard link targets
tar: /var/mail-state/lib-clamav/main.cvd: file changed as we read it
tar: /var/mail-state/lib-clamav: file changed as we read it
tar: /var/mail-state/lib-amavis/amavisd.sock: socket ignored
tar: /var/mail-state/spool-postfix/public/flush: socket ignored
tar: /var/mail-state/spool-postfix/public/cleanup: socket ignored
tar: /var/mail-state/spool-postfix/public/showq: socket ignored
tar: /var/mail-state/spool-postfix/public/qmgr: socket ignored
tar: /var/mail-state/spool-postfix/public/sender-cleanup: socket ignored
tar: /var/mail-state/spool-postfix/dev/log: socket ignored
tar: /var/mail-state/spool-postfix/private/defer: socket ignored
tar: /var/mail-state/spool-postfix/private/anvil: socket ignored
tar: /var/mail-state/spool-postfix/private/verify: socket ignored
tar: /var/mail-state/spool-postfix/private/smtp: socket ignored
tar: /var/mail-state/spool-postfix/private/tlsmgr: socket ignored
tar: /var/mail-state/spool-postfix/private/virtual: socket ignored
tar: /var/mail-state/spool-postfix/private/relay: socket ignored
tar: /var/mail-state/spool-postfix/private/local: socket ignored
tar: /var/mail-state/spool-postfix/private/proxymap: socket ignored
tar: /var/mail-state/spool-postfix/private/auth: socket ignored
tar: /var/mail-state/spool-postfix/private/policyd-spf: socket ignored
tar: /var/mail-state/spool-postfix/private/smtp-amavis: socket ignored
tar: /var/mail-state/spool-postfix/private/retry: socket ignored
tar: /var/mail-state/spool-postfix/private/tlsproxy: socket ignored
tar: /var/mail-state/spool-postfix/private/error: socket ignored
tar: /var/mail-state/spool-postfix/private/scache: socket ignored
tar: /var/mail-state/spool-postfix/private/dnsblog: socket ignored
tar: /var/mail-state/spool-postfix/private/bounce: socket ignored
tar: /var/mail-state/spool-postfix/private/rewrite: socket ignored
tar: /var/mail-state/spool-postfix/private/trace: socket ignored
tar: /var/mail-state/spool-postfix/private/discard: socket ignored
tar: /var/mail-state/spool-postfix/private/lmtp: socket ignored
tar: /var/mail-state/spool-postfix/private/proxywrite: socket ignored
tar: /var/mail-state/spool-postfix/private/smtpd: socket ignored
tar: /var/mail-state/spool-postfix/etc/ssl/certs.NEW: file changed as we read it
```

I think the socket warnings are nothing I should worry about.

What about the "file changed as we read it" lines? These files are present in the resulting archive, so I assume they are OK?

If I lost my data, would restoring this archive to new docker volumes and running up my mailserver again be enough to get be back how I was before the loss of data?

I think this is nothing to worry about, and I could suppress them with `--warning=no-file-changed`, but I'd like to be sure and know what other people do with regards to backups.

**Comment by casperklein** [comment]
> file changed as we read it

These lines may appear if you backup a running container. That is probably not an issue, but it's not 100% guaranteed.
The problem is, that the backup is running while the services are up and files may change during backup.

If you want to be 100% safe, make a "cold" backup:

1. Shutdown DMS
2. Backup the data directory on the host
3. Start DMS again

**Comment by groupmsl** [comment]
If I was to shutdown DMS during a backup am I right in thinking mail sent to that host while it is down could be delayed for quite some time, not just the downtime of DMS?

And with a few large mailboxes, the backup itself could take a few minutes.

Is this what you do?

The idea of a backup not always working doesn't sound good to me, so based on your comment I don't think I should try and backup while DMS is running.

**Comment by ontheair81** [comment]
Mails will be delayed a bit, depending on how often the sending mailserver tries to send it again. Usually this should not be a big deal (depending on the use case [personal vs. business use]).

Another option would be to define a backup MX, which will accept incoming e-mails while the main server is down, sending them to the main server when it is up again.

**Comment by ontheair81** [comment]
And to be more precise, I have a little script for doing the backups, like this:

```
cd /path/to/compose/of/DMS
docker compose down
echo "Creating Backup"
docker run -v mailserver_data:/volume -v /path/where/backup/will/be/created:/backup --rm loomchild/volume-backup backup $(date +%Y%m%d)-mailserver_data
docker inspect mailserver_data -f "{{json .Labels}}" > path/where/backup/will/be/created/$(date +%Y%m%d)-mailserver_data-labels.json
docker compose up -d
```

Not only for the data-volume, but also for state, logs and config.

The docker inspect is done to backup the labels of the volumes, as mention in loomchild/volume-backup:

> Volume labels are not backed-up or restored automatically, but they might be required for your application to work (e.g. when using docker-compose). If you need to preserve them, create a label backup file as follows: docker inspect [volume-name] -f "{{json .Labels}}" > labels.json. When restoring your data, target volume needs to be created manually with labels before launching the restore script: docker volume create --label "label1" --label "label2" [volume-name].

**Comment by groupmsl** [comment]
Thank you both for your help. I have modified my "backup" container to stop DMS before starting and start it again after (from within the container..very cool!). The container runs 24/7 and takes a backup every 12 hours.

I think I will configure a second DMS instance as a MX backup to catch mail during any downtime. I have a question about this but I'll do that in a different ticket.
