### ISSUE TITLE
[BUG] Problem receiving messages with random docker ip addresses | postfix/smtpd: NOQUEUE: reject: RCPT from unknown

### ISSUE THREAD

**Issue by swiesend** [docker-mailserver/docker-mailserver#2478]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

postfix/smtpd, opendkim, SPF

### What happened and when does this occur?

```Markdown
The mailserver received a message, but did not deliver it, as the random docker-compose ip address of the container was not permitted.

I think there is a problem with the current `postfix/main.cf`/`smtpd_relay_restrictions` setting, but I did not verify it yet.
```

### What did you expect to happen?

```Markdown
To receive the mail. Not to get a `NOQUEUE: reject: RCPT from unknown[192.168.xxx.1]: 550 5.7.23 <example@recipient.com>: Recipient address rejected: Message rejected due to: SPF fail - not authorized` message.
```

### How do we replicate the issue?

[_before_]

- `docker-compose.yml`: I had no fix docker ip address
- `config/opendkim/TrustedHosts`: did not include the real `hostname` or ip address, only the defined `hostname` from the `docker-compose.yml`
- `/etc/hosts`: no virtual domain to the `REAL_HOSTNAME` for docker ip addresses or the `REAL_IP_ADDRESS`

### DMS version

10.5.0

### What operating system is DMS running on?

Linux

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### What container orchestration tool are you using?

Docker Compose

### docker-compose.yml
[_before_]
- no volume mount for `/etc/hosts`
- no docker compose `networks`

[_after_] I added a fix ip address to the docker container:

```yaml
version: '3'

services:
  mail:
    image: mailserver/docker-mailserver:latest
    hostname: mail
    domainname: recipient.com
    ...
    volumes:
      ...
      - ./root/etc/hosts:/etc/hosts
    ...
    networks:
      mail:
        ipv4_address: 10.0.0.100

networks:
  mail:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
```
### Configuration

[_after_] I modified the `/etc/hosts` file and added some virtual domains:
```hosts
10.0.0.1	mail.recipient.com mail REAL_HOSTNAME
10.0.0.100	mail.recipient.com mail REAL_HOSTNAME
REAL_IP_ADDRESS	mail.recipient.com mail REAL_HOSTNAME
```

[_after_] `config/opendkim/TrustedHosts`:
```
127.0.0.1
localhost
::1
ip6-localhost
mail
REAL_HOSTNAME
10.0.0.1
10.0.0.100
REAL_IP_ADDRESS
```

### Relevant log output

[_before_]

```shell
Mar  5 21:56:43 mail postfix/smtpd[3396]: warning: hostname REAL_HOSTNAME does not resolve to address 192.168.xxx.1
Mar  5 21:56:43 mail postfix/smtpd[3396]: connect from unknown[192.168.xxx.1]
Mar  5 21:56:43 mail postfix/smtpd[3396]: Anonymous TLS connection established from unknown[192.168.xxx.1]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature RSA-PSS (2048 bits) server-digest SHA256
Mar  5 21:56:43 mail policyd-spf[3479]: 550 5.7.23 Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=helo;id=mail3.sender.com;ip=192.168.xxx.1;r=<UNKNOWN>
Mar  5 21:56:43 mail postfix/smtpd[3396]: NOQUEUE: reject: RCPT from unknown[192.168.xxx.1]: 550 5.7.23 <example@recipient.com>: Recipient address rejected: Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=helo;id=mail3.sender.com;ip=192.168.xxx.1;r=<UNKNOWN>; from=<example@sender.com> to=<example@recipient.com> proto=ESMTP helo=<mail3.sender.com>
Mar  5 21:56:43 mail postfix/smtpd[3396]: disconnect from unknown[192.168.xxx.1] ehlo=2 starttls=1 mail=1 rcpt=0/1 data=0/1 rset=1 quit=1 commands=6/8
```

### Other relevant information

I guess there are missing commas in the `postfix/main.cf` settings:

https://github.com/docker-mailserver/docker-mailserver/blob/65622c56e934459beef7fba045f23ef897a6dcda/target/postfix/main.cf#L50

[_after_] I modified my `postfix-main.cf`:
`smtpd_relay_restrictions = permit_mynetworks, permit_sasl_authenticated, defer_unauth_destination`

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [X] I am inexperienced with mail servers
- [ ] I am uncomfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by casperklein** [comment]
If you see local IP addresses for internet hosts, something is wrong. Do you use podman or something else not supported by DMS?

**Comment by swiesend** [comment]
For other domains than _`sender.com`_ I do see the correct external ip addresses:
```
Mar  5 17:22:28 mail policyd-spf[207735]: prepend Received-SPF: None (mailfrom) identity=mailfrom; client-ip=69.169.224.11; helo=b224-11.smtp-out.eu-central-1.amazonses.com; envelope-from=xxx@xxx.com; receiver=<UNKNOWN> 
Mar  5 18:34:25 mail policyd-spf[228055]: 550 5.7.23 Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=mfrom;id=info@alias.com;ip=194.150.235.135;r=<UNKNOWN>
Mar  5 18:34:26 mail policyd-spf[228068]: prepend Received-SPF: Pass (mailfrom) identity=mailfrom; client-ip=156.70.34.223; helo=mta-70-34-223.sparkpostmail.com; envelope-from=xxx@xxx.com; receiver=<UNKNOWN> 
Mar  5 19:47:16 mail policyd-spf[248592]: prepend Received-SPF: Pass (mailfrom) identity=mailfrom; client-ip=199.195.248.190; helo=smtp2.ageprepcare.com.au; envelope-from=xena@ageprepcare.com.au; receiver=<UNKNOWN> 
Mar  5 21:19:22 mail policyd-spf[12551]: 550 5.7.23 Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=helo;id=mail2.sender.com;ip=172.26.0.1;r=<UNKNOWN>
Mar  5 21:25:20 mail policyd-spf[2590]: 550 5.7.23 Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=helo;id=mail1.sender.com;ip=172.27.0.1;r=<UNKNOWN>
Mar  5 21:28:19 mail policyd-spf[2616]: 550 5.7.23 Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=helo;id=mail1.sender.com;ip=172.28.0.1;r=<UNKNOWN>
Mar  5 21:33:49 mail policyd-spf[2730]: 550 5.7.23 Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=helo;id=mail4.sender.com;ip=172.29.0.1;r=<UNKNOWN>
Mar  5 21:43:19 mail policyd-spf[2731]: 550 5.7.23 Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=helo;id=mail3.sender.com;ip=192.168.16.1;r=<UNKNOWN>
Mar  5 21:48:19 mail policyd-spf[2511]: 550 5.7.23 Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=helo;id=mail4.sender.com;ip=192.168.32.1;r=<UNKNOWN>
Mar  5 21:52:10 mail policyd-spf[2622]: prepend Received-SPF: Softfail (mailfrom) identity=mailfrom; client-ip=192.168.48.1; helo=mail2.sender.com; envelope-from=portal@sender.com; receiver=<UNKNOWN> 
Mar  5 21:56:43 mail policyd-spf[3479]: 550 5.7.23 Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=helo;id=mail3.sender.com;ip=192.168.48.1;r=<UNKNOWN>
Mar  5 22:28:20 mail policyd-spf[2640]: 550 5.7.23 Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=helo;id=mail2.sender.com;ip=192.168.144.1;r=<UNKNOWN>
Mar  5 22:29:43 mail policyd-spf[2640]: 550 5.7.23 Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=helo;id=mail4.sender.com;ip=192.168.144.1;r=<UNKNOWN>
Mar  5 22:32:19 mail policyd-spf[2631]: prepend Received-SPF: Pass (mailfrom) identity=mailfrom; client-ip=185.176.165.46; helo=mail3.sender.com; envelope-from=portal@sender.com; receiver=<UNKNOWN> 
Mar  5 23:31:17 mail policyd-spf[4261]: prepend Received-SPF: Softfail (mailfrom) identity=mailfrom; client-ip=10.0.0.1; helo=mail-ed1-x52d.google.com; envelope-from=xxx@gmail.com; receiver=<UNKNOWN> 
Mar  6 00:39:39 mail policyd-spf[15819]: 550 5.7.23 Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=helo;id=un.org;ip=12.91.44.110;r=<UNKNOWN>
Mar  6 03:42:07 mail policyd-spf[46549]: 550 5.7.23 Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=mfrom;id=info@alias.com;ip=185.173.176.78;r=<UNKNOWN>
Mar  6 05:08:32 mail policyd-spf[61097]: prepend Received-SPF: Pass (mailfrom) identity=mailfrom; client-ip=82.165.159.14; helo=mout-xforward.gmx.net; envelope-from=xxx@gmx.net; receiver=<UNKNOWN> 
```

The problem is I can't verify my current setup to receive a test mail from `sender.com` with that SPF policy and `policyd-spf` check enabled, as I will get banned eventually after some retries and can apply again only 14 days later with that provider. But I need the content of that mail.

How can I avoid checking the SPF policy for a certain domain? Is there any SPF whitelist mechanism?
https://github.com/docker-mailserver/docker-mailserver/blob/65622c56e934459beef7fba045f23ef897a6dcda/target/postfix/main.cf#L51

As far as I have seen I only can disable SPF entirely when removing `check_policy_service unix:private/policyd-spf`. Could that be a very hacky, but valid temporary fix?

**Comment by casperklein** [comment]
I admit, I don't fully understand your setup and what's going wrong.

The very first thing you should find out and fix is, why an internet mail host appears with a local IP address to your DMS. This is not normal and must be fixed first IMO, instead of whitelist hacks. Is there IPv6 or any kind of NAT involved?

> How can I avoid checking the SPF policy for a certain domain?

Typically you whitelist a complete server (not just a single domain) to allow them to "spoof" all sender addresses. This is necessary, e.g. for an backup MX.
There seems to be a `Domain_Whitelist` option, just take a look at the [manual](https://manpages.debian.org/testing/postfix-policyd-spf-python/policyd-spf.conf.5.en.html).

> What is the difference between skip_addresses and Whitelist for config/postfix-policyd-spf.conf?

Same here. See [manual](https://manpages.debian.org/testing/postfix-policyd-spf-python/policyd-spf.conf.5.en.html).
Make sure, you correctly mount `config/postfix-policyd-spf.conf`, otherwise this will have no effect:

```
volumes:
  - ./config/postfix-policyd-spf.conf:/etc/postfix-policyd-spf-python/policyd-spf.conf
```

> As far as I have seen could disable SPF entirely when removing check_policy_service unix:private/policyd-spf. Would that be a very hacky, but valid temporary fix?

If you want to receive a lot of SPAM, this is the route to go 😆

**Comment by swiesend** [comment]
Thank you very much @casperklein for pointing out how to mount the `policyd-spf.conf` correctly!

I'll try to find out whats going wrong with that mails and I guess its an IPv6 issue.

I'll report when I know more.
