### ISSUE TITLE
[FR] Setting up IP blacklists for Iptables

### ISSUE THREAD

**Issue by Eirikr70** [docker-mailserver/docker-mailserver#2504]
# Feature Request
The idea would be to `ipset` a line in Iptables in order to exclude well-known "bad IP's". The blacklist could be imported or just created by the user.
## Context
A "bad IP" tries to connect to my server. It gets rejected by Fail2ban but tries again once "unbanned".

### Is your Feature Request related to a Problem?
Not really. Just a suggestion for an improvement.

### Describe the Solution you'd like
-

### Are you going to implement it?

Yes, because I know the probability of someone else doing it is low and I can learn from it.

### What are you going to contribute??
I am not skilled enough to contribute, I might just configure my own container in order to manage such a blacklist.

### Who will that Feature be useful to?
I suppose all the users

### What have you done already?
-

**Comment by casperklein** [comment]
> A "bad IP" tries to connect to my server. It gets rejected by Fail2ban but tries again once "unbanned".

Even if you permanently ban this IP address, this will be an ongoing cat and mouse game. There will always be new bad actors trying malicious things. You'll probably end up, permanently banning new IPs each day.

A quick & dirty solution:

Enable a dummy fail2ban jail, e.g. `sshd` (which isn't used by DMS). [Copy](https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/optional-config/) [fail2ban-jail.cf](https://github.com/docker-mailserver/docker-mailserver/blob/master/config-examples/fail2ban-jail.cf) to your `config` directory and append the following:

```
[sshd]
enabled = true
bantime = 365d
```

Now you can ban custom IPs with: `docker exec -it mailserver fail2ban-client set sshd banip X.X.X.X`

Per our configuration, IPs are blocked on [all ports](https://github.com/docker-mailserver/docker-mailserver/blob/f22d75fa623675f5fa7dbb05316221dd1f02b07d/target/fail2ban/jail.local#L21). So this will not only block the IP address on the SSH port 22, but on all ports.

**Comment by georglauterbach** [comment]
Moreover, using `iptables` is bad timing - I just opened #2505 which replaced `iptables` with `nftables`. Your suggestion would then need to be adjusted to `nftables`.

I agree with @casperklein though too :)

**Comment by Eirikr70** [comment]
Ok. I have just adjusted the parameters of fail2ban to 3 tries in 10h for 3d exclusion.
Thanks anyway for your fast responses.

**Comment by casperklein** [comment]
In the version, you'll also be able to ban custom IPs with `./setup.sh fail2ban ban <IP>`. The default ban-time for this is 180 days.

I think we can close this issue?

**Comment by Eirikr70** [comment]
Yeap ! Thanks !
