### ISSUE TITLE
Is it possible to get passwordless IMAP access from a specific host?

### ISSUE THREAD

**Issue by groupmsl** [docker-mailserver/docker-mailserver#2529]
# Is it possible to get passwordless IMAP access from a specific host?

I would like some feedback concerning a use case

## Description

I'm considering using an IMAP backup solution, rather than my current shutdown mailserver, backup dirs, start mailserver solution. I would have a job for each user, which would connect over IMAP, do a backup and then disconnect. I don't want to have to store every users password in order to do this. Is it possible to get IMAP access from a given host without a password for all users?

**Comment by georglauterbach** [comment]
I'd personally not stop the container, but `exec` into it and stop the services with `supervisorctl`. `supervisorctl status` shows all running services:

``` CONSOLE
root@mail:/# supervisorctl status
amavis                           RUNNING   pid 41992, uptime 1 day, 3:17:49
changedetector                   RUNNING   pid 540, uptime 1 day, 17:03:51
clamav                           RUNNING   pid 56932, uptime 22:15:24
cron                             RUNNING   pid 347, uptime 1 day, 17:03:57
dovecot                          RUNNING   pid 355, uptime 1 day, 17:03:56
fail2ban                         RUNNING   pid 443, uptime 1 day, 17:03:53
fetchmail                        STOPPED   Not started
```

and you can stop a service with `supercisorctl stop <SERVICE NAME>`. Then backup the directories and start the services again. This may be easier than what you're trying to do, and it does not involve destroying the container.

**Comment by groupmsl** [comment]
I don't destroy the container when I do backups at the moment, just stop it, do my backup and start it again. This is working, but I'd sooner not have the downtime if possible. During this time I can't receive messages (I know I should receive them later) and clients can't use IMAP or send messages.

I was hoping I could get around this with IMAP backups, which I could perform while the server is still online.

**Comment by fbartels** [comment]
It is not per se "passwordless", but Dovecot has a mechanism that is called "master user", which defines a single user and password combination to open all mailboxes on a server.

https://doc.dovecot.org/configuration_manual/authentication/master_users/

I have not checked if this is already supported in docker-mailserver, but in the end its a bit of configuration work in Dovecot.

**Comment by groupmsl** [comment]
This looks exactly what I'm after, thank you. I've had a look and I don't think docker-mailserver supports it at the moment, so I'll configure it manually but then I will see if I can integrate it properly and create a pull request.

Thank you
