### ISSUE TITLE
Serving mail on subdomain of / same domain as website served over http & https

### ISSUE THREAD

**Issue by AverytheFurry** [docker-mailserver/docker-mailserver#2536]
# Subject
Serving mail on subdomain of / same domain as website served over http & https

I would like some feedback concerning a use case

## Description
I am using caddy to host a webserver and would like to set up a mail server on the same domain, or a subdomain. Is this possible with docker-mailserver? I couldn't find any info about it in the documentation, and I would assume this is a common usecase. I dont' want to create conflicting certs or anything, since caddy already has certs for my website.

**Comment by casperklein** [comment]
That's no problem. You find nothing in the documentation, because there is no relationship between both. These are two separate topics.

> I dont' want to create conflicting certs or anything, since caddy already has certs for my website.

Don't worry. You can use different certificates for Caddy and DMS.

**Comment by AverytheFurry** [comment]
> 

So a mail server running on `example.com` won't conflict with an existing website running on `example.com` through caddy?

**Comment by casperklein** [comment]
Correct.
