### ISSUE TITLE
[BUG] High CPU consumption of supervisord

### ISSUE THREAD

**Issue by Bacto** [docker-mailserver/docker-mailserver#2546]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

supervisord

### What happened and when does this occur?

```Markdown
Hi,

First I would like to thank you all for this container image that is very useful!

I noticed a high CPU consumption of my docker-mailserver container and I have dug a little bit.
Supervisord was eating a lot of CPU. In `/var/log/supervisor/changedetector.log` it complained about `/tmp/docker-mailserver` directory that didn't exist.

I do not mount a volume on `/tmp/docker-mailserver` because I don't need it.
If I create manually the directory, everything works normally.

Here is my configuration:

SMTP_ONLY: 1
ENABLE_AMAVIS: 0
SPOOF_PROTECTION: 1
PERMIT_DOCKER: connected-networks
POSTFIX_INET_PROTOCOLS: ipv4
```

I think the directory should be created automatically on container start.

Best,
Adrien
```


### What did you expect to happen?

```Markdown
-
```

### How do we replicate the issue?

```Markdown
-
```

### DMS version

v10.5.0

### What operating system is DMS running on?

Linux

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### What container orchestration tool are you using?

Docker Compose

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [ ] I am inexperienced with mail servers
- [ ] I am uncomfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

### Improvements to this form?

```Markdown
Super annoying but I understand you need that to filter ;)
```

**Comment by casperklein** [comment]
You can fix this for now with:

`docker exec -it mailserver supervisorctl stop changedetector`
