### ISSUE TITLE
Emails being marked spam by gmail and outlook

### ISSUE THREAD

**Issue by YikeStone** [docker-mailserver/docker-mailserver#2550]
# Subject

I would like some feedback concerning a use case

## Description

I am running docker-mailserver on my home server with static ip and my custom domain name, PTR record, DKIM, SPF, DMARC and SSL everything is setup. I am not on any blacklist.  I am able to send and receive emails.

But https://www.mail-tester.com/ website gives a SPAM score of 6/10 in which 2 points are removed because of the email failing PYZOR_CHECK.
Another thing is google postmaster says that my email server is configured correctly and everything is green and verified. But still when sending emails to gmail it classifies them as spam. What can I do to pass PYZOR_CHECK on mail-tester.com and improve my spam score? And what can I change so that gmail and outlook dont mark the emails as spam?

**Comment by GoliathLabs** [comment]
Just out of curiosity, are you using new TLDs like .work?  I noticed that these are often marked as spam as many spammers prefer to use these for their spamming operations.  So I've resorted to sending emails only from my country TLD, which has a relatively good reputation with all email providers.

**Comment by YikeStone** [comment]
I am using .fun TLD. It was cheaper thats all.

**Comment by GoliathLabs** [comment]
@YikeStone you might want to try out this test here as well https://testconnectivity.microsoft.com/tests/exchange. The `fun` TLD is a new TLD as well. This might result in Microsoft and Google blocking your Mails or marking them as spam.

**Comment by YikeStone** [comment]
I tested my mail server using these tools, everything was green.

**Comment by GoliathLabs** [comment]
> Just out of curiosity, are you using new TLDs like .work? I noticed that these are often marked as spam as many spammers prefer to use these for their spamming operations. So I've resorted to sending emails only from my country TLD, which has a relatively good reputation with all email providers.

I bet it's the TLD as pointed out in my comment above

**Comment by GoliathLabs** [comment]
Or another question, what exact points does mail-tester.com make?

**Comment by YikeStone** [comment]
Thanks for all your help. Its was due to the tld. I bought another domain with my countries tld and now spam score on mail-tester is 10/10
