### ISSUE TITLE
[FR] Postprox with filter

### ISSUE THREAD

**Issue by GoliathLabs** [docker-mailserver/docker-mailserver#2551]
# Feature Request

## Context
Good day,
I've recently listened to a episode of the 2.5 admins podcast in which they went over some good email setup. They've pointed to the Ubuntu wiki which lists postprox in combination with a filtering script 
http://ubuntuwiki.net/index.php/Postfix,_Virtual_Domain_Setup#Installing_Content_Filtering_with_Postprox

### Is your Feature Request related to a Problem?
Better spam handling I guess?

### Describe the Solution you'd like
One might want to have a look at this section in the wiki and evaluate whether it is viable to implement this here as well

### Are you going to implement it?

Yes, because I know the probability of someone else doing it is low and I can learn from it.

I currently don't have that much time on my hands, yet I would give it a shot after this "feature" has been evaluated.

**Comment by casperklein** [comment]
I am not sure if there is great demand for this a feature - at least it was never asked for afaik. Personally, I am quiet happy with the current possibility's given by postifx.
For example, I use things like this in my [`user-patches.sh`](https://docker-mailserver.github.io/docker-mailserver/edge/faq/#how-to-adjust-settings-with-the-user-patchessh-script) to filter out emails.

```bash
# DISCARD/REJECT mails based on header
# http://www.postfix.org/header_checks.5.html
echo '/^Subject:.*Invest In Bitcoin.*/          DISCARD fuckspam' >> /etc/postfix/maps/header_checks.pcre
```


However, if you are going to use it for yourself and are able to properly implement it, feel free to provide a PR afterwards. We'll be happy to review it.
