### ISSUE TITLE
Using host-based mail storage directory?

### ISSUE THREAD

**Issue by g40** [docker-mailserver/docker-mailserver#2553]
# Subject

Other

## Description

Great project - many thanks.

Don't think I've quite understood where incoming mail is stored. Is it possible to configure the docker instance to save incoming mail to the host file system?

A bit of searching finds this but it seems heavyweight: [https://www.techrepublic.com/article/how-to-connect-docker-data-to-its-host-filesystem]().

Preferable but recommended? [https://linuxconfig.org/how-to-share-data-between-a-docker-container-and-host-system-using-volumes]().

Use case: Swap out an existing postfix/dovecot/amavis for the docker instance whilst maintaining the old installation in case of problems etc. The shared folder here would be Dovecot's vmail dirctory.

**Comment by casperklein** [comment]
If you use our default [configuration](https://github.com/docker-mailserver/docker-mailserver/blob/master/docker-compose.yml), the mails are stored in `./docker-data/dms/mail-data/` on the host. There is other persistant data, take a look at the volume section in `docker-compose.yml`.
