### ISSUE TITLE
How to configure mailserver with two different hostname and domainname

### ISSUE THREAD

**Issue by rquevedo** [docker-mailserver/docker-mailserver#2559]
Hi folks, I would like some feedback concerning a use case

I'm running a mail server using this project. Server is deployed in a vps rented to my ISP, this ISP creates automatically a hostname to my vps, "srv5117-206152.vps.isp.com" and respective PTR record to my public IP. Those configurations don't cause any problem to me until now. I config mail server with "OVERRIDE_HOSTNAME=mycustomdomain.com" and everything goes well. Since few days ago, some mails sent by my main domain accounts or other domains account(I have multiple domains in mail server) with destination to gmail accounts are being sent to spam folder. After re-check SPF, DKIM, DMARC, I use [https://www.mail-tester.com/](url) to test the service. The result was a 10/10, but with some alert:
"Your reverse DNS does not match the domain that sends the mail." 
"Your IP address 150.200.100.52 is associated with the srv5117-206152.vps.isp.com domain ."
"However, your mail appears to have been sent from mail.mycustomdomain.com ." 
I have some dubs now:
These alerts are irrelevant to my spam problem?
What configuration in hostname and domainname will be correct ones to my case?

**Comment by georglauterbach** [comment]
This is relevant, because most mail servers check that the reverse-DNS lookup (`PTR` record` matches the "forward" DNS record (`A`). This is however a DNS problem, and you must configure your reverse hostname (i.e. your `PTR` record at your VPS provider.

**Comment by rquevedo** [comment]
> This is relevant, because most mail servers check that the reverse-DNS lookup (`PTR` record) matches the "forward" DNS record (`A`). This is however a DNS problem, **not a DMS problem (!)**, and you must configure your reverse hostname (i.e. your `PTR` record at your VPS provider.

I'm not reporting this like a mailserver problem, I know that this is an issue caused by my ISP, but maybe someone can help me to do a better config. By other side, my ISP let me clear that it is impossible to me change my PTR record.

**Comment by ontheair81** [comment]
> By other side, my ISP let me clear that it is impossible to me change my PTR record.

Having the right PTR record is essential, as other mailservers most likely will not accept your e-mails otherwise. If your ISP refuses you to do so, then sadly it seems like you have to choose another ISP (maybe they don't want their customers to run a mailserver for whatever reason).

**Comment by rquevedo** [comment]
> > By other side, my ISP let me clear that it is impossible to me change my PTR record.
> 
> Having the right PTR record is essential, as other mailservers most likely will not accept your e-mails otherwise. If your ISP refuses you to do so, then sadly it seems like you have to choose another ISP (maybe they don't want their customers to run a mailserver for whatever reason).

I can't change my ISP, is the only one in my country, and international services don't have access to national payments API.
If I change my hostname to "srv5117-206152.vps.isp.com", in order to match with PTR record, is there any way to have @mycustomdomain.com accounts, working right?

**Comment by casperklein** [comment]
BTW: Many ISPs completely block port 25, due to SPAM. There are very few (private) people, running their own mail server. And even less are running those at home.
Maybe your best solution might be a cheap VPS somewhere. This will also allow you, to change the PTR record.

**Comment by rquevedo** [comment]
> BTW: Many ISPs completely block port 25, due to SPAM. There are very few (private) people, running their own mail server. And even less are running those at home. Maybe your best solution might be a cheap VPS somewhere. This will also allow you, to change the PTR record.

You are right, I start this issue to ensure that this cant be done by any config before think in contract other vps only for mailserver.

**Comment by rquevedo** [comment]
Hi folks, I have to change mail server to other vps and be able to change PTR record. Now I have running mail server in new vps. I copied folder by ssh, but old mails of all accounts disappears. How can I move mails to?

**Comment by ontheair81** [comment]
> I copied folder by ssh, but old mails of all accounts disappears

Which folders did you copy? Mails are stored in `/var/mail`, which is - by default - a bind mount. It's content can be archived and compressed, then moved to the new vps.

This is basically "backup and restore", which is described in the [FAQ](https://docker-mailserver.github.io/docker-mailserver/edge/faq/#what-about-backups).

**Comment by rquevedo** [comment]
> > I copied folder by ssh, but old mails of all accounts disappears
> 
> Which folders did you copy? Mails are stored in `/var/mail`, which is - by default - a bind mount. It's content can be archived and compressed, then moved to the new vps.
> 
> This is basically "backup and restore", which is described in the [FAQ](https://docker-mailserver.github.io/docker-mailserver/edge/faq/#what-about-backups).

I stop server by `docker-compose down`, then copied "mail_server" folder from vps1 to vps2. I read FAQs and see backup procedure but i think that only apply if i want backup my data in external server. I remember that i read that this image are managed completely in files, no bbdd required. If i use backup to generate tar file, how i restore this file in other server?

**Comment by ontheair81** [comment]
> I stop server by `docker-compose down`, then copied "mail_server" folder from vps1 to vps2.

According to the [default docker-compose.yml](https://github.com/docker-mailserver/docker-mailserver/blob/master/docker-compose.yml) there is no `mail_server` folder, so this seems to be your individual configuration. Without knowing it, this is a bit hard to troubleshoot.

But basically this should work: Do a backup of all your bind mounts by `tar`-ing (and optionally compressing) them, then restore them on the new server - accordingly to your individually defined paths in your docker-compose.yml.

> how i restore this file in other server?

[FAQ](https://docker-mailserver.github.io/docker-mailserver/edge/faq/#bind-mounts-default)s covers restoring, too:

> Then to restore docker-data/dms/config/ and docker-data/dms/mail-* folders from your backup file:
> `tar --gzip -xf backup-date.tar.gz`

**Comment by rquevedo** [comment]
> > I stop server by `docker-compose down`, then copied "mail_server" folder from vps1 to vps2.
> 
> According to the [default docker-compose.yml](https://github.com/docker-mailserver/docker-mailserver/blob/master/docker-compose.yml) there is no `mail_server` folder, so this seems to be your individual configuration. Without knowing it, this is a bit hard to troubleshoot.
> 
> But basically this should work: Do a backup of all your bind mounts by `tar`-ing (and optionally compressing) them, then restore them on the new server - accordingly to your individually defined paths in your docker-compose.yml.
> 
> > how i restore this file in other server?
> 
> [FAQ](https://docker-mailserver.github.io/docker-mailserver/edge/faq/#bind-mounts-default)s covers restoring, too:
> 
> > Then to restore docker-data/dms/config/ and docker-data/dms/mail-* folders from your backup file:
> > `tar --gzip -xf backup-date.tar.gz`

"mail_server" folder is my root folder, inside reside `config  docker-compose.yml  docker-data  mailserver.env  README.md  setup.sh` files.

I miss the restore part of FAQs. Thank you very much for your help.

**Comment by casperklein** [comment]
If you use the example config, copying your whole "mail_server" directory should be fine. Mails are stored in `docker-data`.
