### ISSUE TITLE
Question: Delete a lot of e-mails

### ISSUE THREAD

**Issue by carlwickham** [docker-mailserver/docker-mailserver#2576]
# Subject

Other

## Description

Hello Developers and Users,

Thank you for this amazing project. I would never imagine I can run private mailserver for my family so easily ;-).

Could you please tell me is there a safe way to delete some e-mails on the server? By safe way I mean without braking Docker Mailserver.

I managed to send myself 5000 e-mails since my shell script misbehaved and I would prefer to delete them from server side, not on client.

The easiest way for me would be to find the e-mails in `/var/mail`. I mean find the actual files using `grep` by their date and subject and `rm` them. But I'm assuming that would break something.

Thank you.

Best regards,

Carl

**Comment by casperklein** [comment]
> The easiest way for me would be to find the e-mails in /var/mail.

Or on the host in `./docker-data/dms/mail-data/`, when you are using our default `docker-compose.yml`.

It should be safe to delete the emails. But to be on the safe side, I advice to do a backup of the directory first.

**Comment by frugan-it** [comment]
Why not using [doveadm](https://doc.dovecot.org/admin_manual/doveadm_mailbox_commands/) inside DMS container?

```
/usr/bin/doveadm expunge -u user@domain.tld mailbox INBOX sentbefore 30d
/usr/bin/doveadm purge -u user@domain.tld
```

**Comment by carlwickham** [comment]
That's great, thank you very much. I'll try to use `doveadm` (thank you for the example) and if that doesn't work for me I'll just delete the files.
