### ISSUE TITLE
[SOLVED] Why I can't access my personal email folders after a migration

### ISSUE THREAD

**Issue by lecoqlibre** [docker-mailserver/docker-mailserver#2579]
Hi, thank you for this great mailserver! I wanted to move my docker-mailserver to another host so I backup my emails with :

`tar czf "backupFile.tar.gz" /var/lib/docker/volumes/docker-mailserver_maildata/`
 
I did not backup the `/var/lib/docker/volumes/docker-mailserver_mailstate/` directory because it was empty.

On my new host I just extracted the archive (sent with `scp`) and copy the files of the email account (`cur`, `dovecot.index`, `dovecot.index.cache`, etc) into the new email folder (`~/docker-mailserver/docker-data/dms/mail-data/<domain>/<user>`).

It worked for the emails of my inbox but I can't view any email of my other personal folders and archives. In Thunderbird, these folders appear in gray and italic and do not contain any email. They are not inside the main Inbox folder.

When I try to archivate a mail, Thunderbird responds with `[TRYCREATE] Mailbox doesn't exist: Archives.2022`.

When I create a new folder with the name of a grayed folder, it shows up normal but do not contain any email.

What did I missed? Thanks

![image](https://user-images.githubusercontent.com/4130370/167360141-87e27a71-d279-4eeb-9493-c82244ff90e1.png)

**Comment by georglauterbach** [comment]
So, you're using our `docker-compose.yml`, then the mail data volume is mounted to `/var/mail/`. Please have a look inside the container and see whether the archive you unpacked is really there and if the layout is fine:

``` CONSOLE
$ docker exec mailserver ls /var/mail
yourdomain.test
$ docker exec mailserver ls /var/mail/yourdomain.test
somemailaccount
$ docker exec mailserver ls /var/mail/yourdomain.test/somemailaccount
cur dovecot.index ...
```

**Comment by lecoqlibre** [comment]
Thank you @georglauterbach!

The personal folders (starting with a dot like `.Archives`) was indeed not present in the new host mail-data! However, these folders were in the tar archive. I suspect there was an error during the copy operation. Don't forget to also set correct permissions on the mail-data files.
