### ISSUE TITLE
Sieve Envelope To filtering

### ISSUE THREAD

**Issue by Bluejanis** [docker-mailserver/docker-mailserver#2590]
# Sieve Envelope "to" filtering

I would like to configure a not documented mail server use case

## I want all emails for an address to be put in a specific folder

I tried this before:
``` if header :contains ["to", "cc", "bcc"]``` 
I will work for to & cc but not for the bcc use case, since that will not be in the header.

I also found this on [StackOverflow](https://stackoverflow.com/a/44138755/6276704):
``` BASH
# Alternative solution
if envelope :localpart :is "to" ["2022"] {
	fileinto :create "INBOX.2022";
}
```
But that does not work. A test mail via bcc got delivered to the main inbox folder.

Now I found this in the [docs](https://doc.dovecot.org/configuration_manual/sieve/examples/#plus-addressed-mail-filtering):

> To work with Postfix, this requires that the envelope “to” still contains the full address, so pass it with the -a flag.

Can we configure this flag somehow?

**Comment by reneploetz** [comment]
This image uses LMTP using virtual_transport where this feature is not available. You would need to switch back to using LDA.

You can try to use the override configuration feature for this (untested).

https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/override-defaults/postfix/

```
# postfix-main.cf

virtual_transport = dovecot
dovecot_destination_recipient_limit = 1
```

```
# postfix-master.cf

dovecot   unix  -       n       n       -       -      pipe
  flags=DROhu user=docker argv=/usr/lib/dovecot/deliver -f ${sender} -a ${original_recipient} -d ${user}@${nexthop} -m ${extension}
```

The idea is to change back to LDA and use the O-flag for LDA in conjunction with dovecot_destination_recipient_limit to handle multiple recipients.

Adapted from: https://github.com/42wim/til/blob/master/postfix/dovecot_and_envelope_recipient_address_for_sieve_filtering.md
