### ISSUE TITLE
Adding lines to postfix-main.cf parsing error

### ISSUE THREAD

**Issue by andrewwong2000** [docker-mailserver/docker-mailserver#2594]
I am trying to add the following postfix rules (which other people are using) via postfix-main.cf:

```
#Postscreen for DNSBL 
postscreen_dnsbl_action = enforce
postscreen_dnsbl_sites = zen.spamhaus.org*3
        b.barracudacentral.org=127.0.0.[2..11]*2
        bl.spameatingmonkey.net*2
        bl.spamcop.net
        dnsbl.sorbs.net
       swl.spamhaus.org*-4,
       list.dnswl.org=127.[0..255].[0..255].0*-2,
       list.dnswl.org=127.[0..255].[0..255].1*-4,
       list.dnswl.org=127.[0..255].[0..255].[2..3]*-6
```

However, when I docker-compose up , I get the following errors .. I've doubled checked the format .. what might I be missing ?

```
mailserver    | postconf: fatal: missing '=' after attribute name: "bl.spameatingmonkey.net*2"
mailserver    | postconf: fatal: missing '=' after attribute name: "bl.spamcop.net"
mailserver    | postconf: fatal: missing '=' after attribute name: "dnsbl.sorbs.net"
```

**Comment by reneploetz** [comment]
Please have a look at the documentation:
https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/override-defaults/postfix/

```
Each line in the provided file will be loaded into postfix.
```


So use a single line for each option you want to overwrite - replacing the newlines with spaces, e.g.:
```
postscreen_dnsbl_sites = zen.spamhaus.org*3 b.barracudacentral.org=127.0.0.[2..11]*2 bl.spameatingmonkey.net*2 bl.spamcop.net dnsbl.sorbs.net swl.spamhaus.org*-4 list.dnswl.org=127.[0..255].[0..255].0*-2 list.dnswl.org=127.[0..255].[0..255].1*-4 list.dnswl.org=127.[0..255].[0..255].[2..3]*-6
```

Most tutorials use multiline statements for this option tough this is just done for readability purposes - postfix accepts any kind of whitespace (or a comma) to provide a list of sites.

**Comment by polarathene** [comment]
I assume the parser just has trouble there due to the mix with a filter (`=`).

Using a single line will avoid it, or explicit `,` on multi-line also seems to work. It might also look a bit easier to maintain when you indent a little to indicate multi-line better to yourself but not necessary (_`,` is in this case for multi-line, and it **must be first** before the value, **not at the end**_).

```
# config/postfix-main.cf

postscreen_dnsbl_sites = zen.spamhaus.org3
 ,b.barracudacentral.org=127.0.0.[2..11]2
 ,bl.spameatingmonkey.net2
 ,bl.spamcop.net
 ,dnsbl.sorbs.net
 ,swl.spamhaus.org-4
 ,list.dnswl.org=127.[0..255].[0..255].0*-2
 ,list.dnswl.org=127.[0..255].[0..255].1*-4
 ,list.dnswl.org=127.[0..255].[0..255].[2..3]*-6
```

**Comment by reneploetz** [comment]
I did not test this, but the parsing in https://github.com/docker-mailserver/docker-mailserver/blob/master/target/scripts/startup/setup-stack.sh#L797 suggests that you need to provide a single line for this specific overwrite feature.
We could probably implement a better parser tough.

**Comment by andrewwong2000** [comment]
> I assume the parser just has trouble there due to the mix with a filter (`=`).
> 

> postscreen_dnsbl_sites = zen.spamhaus.org3
>  ,b.barracudacentral.org=127.0.0.[2..11]2
>  ,bl.spameatingmonkey.net2

Thanks polarathene!

Yes the parser for postfix-main.cf works for multi-line entries if you put the comma in.

**Comment by reneploetz** [comment]
> > I assume the parser just has trouble there due to the mix with a filter (`=`).
> 
> > postscreen_dnsbl_sites = zen.spamhaus.org3
> > ,b.barracudacentral.org=127.0.0.[2..11]2
> > ,bl.spameatingmonkey.net2
> 
> Thanks polarathene!
> 
> Yes the parser for postfix-main.cf works for multi-line entries if you put the comma in.

I would assume it does not work. The lines starting with a comma will be silently ignored and you will end up with just
```
postscreen_dnsbl_sites = zen.spamhaus.org*3
```

You might want to validate your results.

**Comment by andrewwong2000** [comment]
Thanks. I thought that because it didn't throw an error that it had worked.

Yes I confirm only single line works.. the comma means the parser chucks everything except the first line.

Maybe the docker-mailserver wiki could be updated to highlight this ?

**Comment by polarathene** [comment]
> We could probably implement a better parser tough.

At a glance, this is only run during container startup, we do not have change detection support (which would reload postfix anyway), and postfix is not started until later in the startup process. Thus I'm fairly confident that we could just straight-up append the contents?

I haven't checked how postfix handles repeated config values, I assume the newer ones override the previous lines, so I don't think that'd cause any issues..

**Comment by georglauterbach** [comment]
I will have a look too and adjust the script - should be fairly straight-forward, and I have an idea.

**Comment by polarathene** [comment]
> So it would be possible just to append the configuration to the existing one and do not perform a rather complex parsing.

I did give that a go and noticed log gets spammed with each override whenever the config is accessed (not just updated AFAIK).

What about appending followed by `echo "$(postconf -n)" > /etc/postfix/main.cf`, this has [`postconf -n`](https://www.postfix.org/postconf.1.html) read the `main.cf` file and strip out all earlier entries that are overwritten as well as empty lines and comments and replace `main.cf` with that output.

It should be ok to do assuming no one mounts a replacement `main.cf` there (which I don't think anyone would?). I have tested this and it passes everything. Was going to push a PR for it, but maybe @georglauterbach has a better idea?

**Comment by georglauterbach** [comment]
> > So it would be possible just to append the configuration to the existing one and do not perform a rather complex parsing.
> 
> I did give that a go and noticed log gets spammed with each override whenever the config is accessed (not just updated AFAIK).

Thanks for testing this, otherwise I would have run into this myself :)

> What about appending followed by `echo "$(postconf -n)" > /etc/postfix/main.cf`, this has [`postconf -n`](https://www.postfix.org/postconf.1.html) read the `main.cf` file and strip out all earlier entries that are overwritten as well as empty lines and comments and replace `main.cf` with that output.

ShellCheck would say: "useless `echo`" :D -> `postfonf -n >/etc/postfix/main.cf` should be fine :) 

> It should be ok to do assuming no one mounts a replacement `main.cf` there (which I don't think anyone would?).

I actually copy a custom configuration there, but this is fine as I do it in `user-patches.sh`, so no disruption there. The only thing with `postconf -nf` is (`-f` for a bit nicer formatting) is that the original formatting is lost.

> I have tested this and it passes everything. Was going to push a PR for it, but maybe @georglauterbach has a better idea?

I will double-check and push a PR if that is fine with you.

**Comment by georglauterbach** [comment]
Please have a look at the [documentation with the new PR](https://pullrequest-2598--dms-doc-previews.netlify.app/config/advanced/override-defaults/postfix/) and tell us whether the docs have improved :)
