### ISSUE TITLE
[FR]: `misc-stack.sh` should append directories only when relevant services are enabled

### ISSUE THREAD

**Issue by polarathene** [docker-mailserver/docker-mailserver#2602]
# Feature Request

## Context

Despite some features like CLAM AV being disabled by default, we do copy over that data anyway during startup if it doesn't exist:

https://github.com/docker-mailserver/docker-mailserver/blob/0d30b92a83118e7c1cea7cdc40007a3f41d4fe6c/target/scripts/startup/misc-stack.sh#L20-L38

During a test setup with 3 instances of DMS, this had each instance use 220 MB of storage just for ClamAV which I had not enabled, so it was unexpected.

### Is your Feature Request related to a Problem?

Yes, but isn't likely to be an issue for most users / deployments. It only matters if you're low on disk space and have multiple containers running for some reason and choose to persist some state with a `/var/mail-state/` volume bind mount.

### Describe the Solution you'd like

Not persisting / copying over state that isn't relevant.

### Are you going to implement it?

Maybe, otherwise anyone is welcome to take a shot before I get around to it :sweat_smile: 

I am raising the issue as a personal reminder and awareness for which could be a small improvement, instead of burying it in my own todo list :sweat_smile:

**Comment by georglauterbach** [comment]
I'd go about it like this: the `FILES` array could start out with only the necessary files / directories and you add entries to the array on demand:

``` BASH
[[ ${ENABLE_CLAMAV} -eq 1 ]] && FILES+=('lib/clamav') 
```

**Comment by casperklein** [comment]
> During a test setup with 3 instances of DMS, this had each instance use 220 MB of storage just for ClamAV which I had not enabled, so it was unexpected.

When you are not using ClamAV, you can save time and disk space (~230MB) while building, by commenting out this line:

https://github.com/docker-mailserver/docker-mailserver/blob/05e45c349a794af5508f6078c173de3e6c9d317e/Dockerfile#L100

**Comment by polarathene** [comment]
> while building, by commenting out this line:

Yeah, but this was more about the issue with running multiple instances. The image having the ClamAV bloat while not great is not so much the issue here. If layer cache is used fine that issue is minimal AFAIK.

I had 3 instances of DMS running with persisted state which added an additional ~700MB disk storage.

Thankfully not a big issue with tests. At a glance only two containers mount the mail-state, but you could see how much extra storage that could use if that was more common due to the pattern of using dirs unique to tests for config :sweat_smile:
