### ISSUE TITLE
Override Dovecot config don't work

### ISSUE THREAD

**Issue by rquevedo** [docker-mailserver/docker-mailserver#2609]
# Subject

I have questions about Override Dovecot config.

## Description

I need to change 'mail_max_userip_connections' value in dovecot config. I follow the docs https://docker-mailserver.github.io/docker-mailserver/v11.0/config/advanced/override-defaults/dovecot/ but config in file 'dovecot.cf' don't copy to server dovecot config.
Furthermore, I have to use sudo to create  'dovecot.cf' under 'docker-data/dms/config' folder, is that right? What permissions must have this folder?
Other things that I noted:
1. I don't have a file '/etc/dovecot/local.conf' in mail server container.
2. I create manually the file '/etc/dovecot/local.conf' but when down/up mailserver file desapears.

Thanks in advance

**Comment by polarathene** [comment]
> config in file 'dovecot.cf' don't copy to server dovecot config.

It should copy if it's detected:

https://github.com/docker-mailserver/docker-mailserver/blob/3b4f44e8377598eaa03b88c907dbb9e2f70332ac/target/scripts/startup/daemons-stack.sh#L68

> I have to use sudo to create 'dovecot.cf' under 'docker-data/dms/config' folder, is that right? What permissions must have this folder?

If you did not create the folder before hand and Docker is volume mounting the location as root user (default), then you would need root permission to create files there yes. The container itself does not care AFAIK, and will just copy the contents.

Sometimes it will write/update files there (such as adding email account with `setup email add` command).

You may name the local `docker-data/dms/config` folder anything you like, as you mount it to docker container as `/tmp/docker-mailserver/`.

---

> I create manually the file '/etc/dovecot/local.conf' but when down/up mailserver file disappears.

This is expected. Only the data in your volume mounts will be kept. `down` + `up` will recreate the container from the image, giving you a _clean_ state. Your volume mounts then carry over any of your important data like config and email storage.

So try not to edit or create files internally if you want them to stay around. Keep them stored in your volume mounts like `docker-data/dms/config`.

---

> I don't have a file '/etc/dovecot/local.conf' in mail server container.

We have a test that ensures this feature is working. It uses this [`dovecot.cf`](https://github.com/docker-mailserver/docker-mailserver/blob/master/test/config/dovecot.cf). I can confirm that the container properly copies that to `/etc/dovecot/local.conf`. Here is the test:

https://github.com/docker-mailserver/docker-mailserver/blob/3b4f44e8377598eaa03b88c907dbb9e2f70332ac/test/tests.bats#L399-L405

We are using `!include_try` as [mentioned in Dovecot docs](https://doc.dovecot.org/configuration_manual/config_file/#including-config-files) to include the `local.conf` file. This does not seem to be something we've explicitly configured ourselves, but is part of the Dovecot default `/etc/dovecot/dovecot.conf` file:

```
# A config file can also tried to be included without giving an error if
# it's not found:
!include_try local.conf
```

So something in your configuration must be wrong? (_you should have used the proper bug report template so we can have information about your configuration_)

**Comment by rquevedo** [comment]
@polarathene thanks for your reply. I double-check all your notes and found that config folder was in mail server root and volume pointing to that folder. Fix volumes in docker-compose.yml and everything work as expected. I'm using mail server since over a year, I think that folder and volumes layout change, but my config don't update properly.
I will close the issue since there is no bug.
Thanks again

**Comment by polarathene** [comment]
> I'm using mail server since over a year, I think that folder and volumes layout change, but my config don't update properly.

Yes, this project has been going through lots of changes in past two years. It's important to check our changelog and release notes when upgrading especially when its a major version bump.
