### ISSUE TITLE
Selective relaying for specific domains

### ISSUE THREAD

**Issue by vogelfreiheit** [docker-mailserver/docker-mailserver#2647]
# Subject

I would like to configure a not documented mail server use case

## Description

I assume that internal mail (ex. to the FQDN of the docker-mailserver host) will never be relayed. However, I would like to see some documentation for a selective relay: take, for example, @gmail.com, and configure docker-mailserver to always relay outgoing email for @gmail.com addresses through a specific relay host.

I'm helping somebody set up an internal mail server that she wants to use together with an existent Internet-exposed mail server (I believe it uses another docker-based package, mail.u or similar), and so far could not find any pointers such a configuration int he (already excellent) documentation.

Thanks a mil in advance!

**Comment by polarathene** [comment]
> always relay outgoing email for @gmail.com addresses through a specific relay host.

We currently have sender dependent relay-hosts, which allows for choosing a relay-host by the sender domain, but sounds like you want to do it for the recipient domain?

I believe there is something similar for this with Postfix that would let you match a recipient (the destination address) and send it through a relay-host with a transport map. We don't presently have support for such, so you'd need to modify Postfix `master.cf` directly (or with our `user-patches.sh` feature) as our override/extension of that config with `postfix-master.cf` does not support multi-line additions (or defining your own transport).

`main.cf` can then be configured with our `postfix-main.cf` if you like to then enable the setting [`transport_maps=/path/to/file`](https://www.postfix.org/postconf.5.html#transport_maps), where `/path/to/file` points to a config file you provide that maps recipient domains to the next destination (eg, lines like this: `@gmail.com    [mail.other-mailserver.com]:25`), I think if authentication is required the current relay support requires editing `postfix-sasl-password.cf` to include the relay-host followed by credentials (`[mail.other-mailserver.com]:25    account-for-relay:password`).

---

I plan to refactor our relay support in future, this might be something I could add support for but I don't know how far off that would be.
