### ISSUE TITLE
ENABLE_DNSBL but do not check if permit_sasl_authenticated

### ISSUE THREAD

**Issue by michabbb** [docker-mailserver/docker-mailserver#2648]
hi,

i do understand that sending from a regular dynamic IP address of an ISP is not wanted.
but in some cases, I would be happy to send mails from home (with such an IP) through my mail server
without checking DNSBL - if the sender was able to authenticate successfully. but it looks like that DNSBL
is coming first. is there any way to "always" ignore DNSBL if the sender is valid (by username+password) ?

thanks a lot !

**Comment by casperklein** [comment]
How do you send mails, via port 25? You could try 465/587.

**Comment by michabbb** [comment]
https://pbs.twimg.com/media/Cc4punhVIAAfGYn.jpg

no comment 😂 🤦‍♂️ 

thanks !
