### ISSUE TITLE
[FR] Configure smtp_helo_name 

### ISSUE THREAD

**Issue by GoliathLabs** [docker-mailserver/docker-mailserver#2649]
# Feature Request

## Context
I was testing my mailserver and noticed that my server didn't fullfill the SPF_HELO_PASS test of mail-tester.com

### Is your Feature Request related to a Problem?
I didn't pass the SPF_HELO_PASS test of mail-tester.com

### Describe the Solution you'd like
After adding the following to my user-patches.sh file, the test did pass.
```bash
echo "smtp_helo_name = \$mydomain" >> /etc/postfix/main.cf
```
Therefore it might be a good idea to add it directly to the configuration instead of going over the user-patches.sh file

### Are you going to implement it?

Yes, because I know the probability of someone else doing it is low and I can learn from it.

### What are you going to contribute??
Should be an easy fix, so I'd open a PR with the proper change in the main.cf config file.

### What have you done already?
Added the following to my user-patches.sh file
```bash
echo "smtp_helo_name = \$mydomain" >> /etc/postfix/main.cf
```

**Comment by casperklein** [comment]
Whats wrong with that:

```bash
docker exec mailserver postconf smtp_helo_name myhostname

smtp_helo_name = $myhostname
myhostname = mail.example.com
```

`mydomain` does only contain the domainname:

```bash
docker exec mailserver postconf mydomain

mydomain = example.com
```

Please provide more information about the issue you are experiencing.

- What value does your `smtp_helo_name` have?
- What value did you expect to have instead?
- What `hostname/domainname` values did you configure in your `docker-compose.yml`?

**Comment by GoliathLabs** [comment]
@casperklein thanks for the quick answer!

You're right, it is already set to myhostname like this
```bash
docker exec mailserver postconf smtp_helo_name myhostname

smtp_helo_name = $myhostname
myhostname = mail.example.com
```
Yet if I remove the patch from the user-patches.sh I get the "SPF_HELO_NONE" with "SPF: HELO does not publish an SPF Record" over at mail-tester.com

```
  mailserver:
    image: mailserver/docker-mailserver:11.0.0
    hostname: mail
    domainname: example.com
```

example.com is replaced with my actual domain

**Comment by GoliathLabs** [comment]
@casperklein can you test your mailserver and report back whether you get the same result?

**Comment by casperklein** [comment]
I get the same result. But I don't think that's a big issue. I had never problems, getting my mails delivered.

You can try, setting up SPF records for mail.example.com, see also:

- http://www.open-spf.org/action_browse_id_FAQ/Common_mistakes_revision_26/#helo
- https://stackoverflow.com/questions/71786859/email-dns-setup-how-do-i-make-helo-publish-an-spf-record-spf-helo-none-spf

**Comment by polarathene** [comment]
@GoliathLabs what is your DNS records for SPF like? If it helps I have a [rough offline config shared here](https://github.com/docker-mailserver/docker-mailserver/issues/2601#issuecomment-1135520225) which shows `docker-compose.yml` for several DMS instances and DNS records for each. Note that `example.test` has DNS configured for SPF to authorize a mailserver running elsewhere (`mail.relay-service.test`) to send on it's behalf (eg: `user@example.test`).

You'll notice that each instance uses the `mail` subdomain for their mail-server, and that should be used by the SMTP HELO (as `$myhostname` / `mail.example.com` would in discussion above). The SPF records are assigned to the apex domain as the email being sent/received is using that in the mail address "domain part", thus `user@example.com`, while the MX record is to `mail.example.com`.

If you run the linked example, and send mail between them without those SPF records, relayed delivery on behalf of another domain would be rejected (as `docker logs` would show when the receiving container checks SPF).

---

So are you authorizing `mail.example.com` in your `example.com` SPF record? If not, that is probably why you're getting a failure sending mail for `@example.com` from a mail-server that presents itself as `mail.example.com`.

**Comment by GoliathLabs** [comment]
@polarathene thank you for your reply. I had a small error in my environment configuration. Now everything works!
