### ISSUE TITLE
[FR] Add environment variable to add reject_unknown_reverse_client_hostname & reject_unknown_client_hostname to smtpd_sender_restrictions

### ISSUE THREAD

**Issue by GoliathLabs** [docker-mailserver/docker-mailserver#2650]
# Feature Request

## Context
I was receiving quite some amount of spam from servers with invalid reverse DNS records (or none at all)

### Is your Feature Request related to a Problem?
After manually adding the following to my user-patches.sh, these servers are no longer able to send spam to my server because their reverse client hostname does not match the current record or they do not specify a hostname at all.
```bash
sed -i "s/smtpd_sender_restrictions = /smtpd_sender_restrictions = reject_unknown_reverse_client_hostname, /" /etc/postfix/main.cf
sed -i "s/smtpd_sender_restrictions = /smtpd_sender_restrictions = reject_unknown_client_hostname, /" /etc/postfix/main.cf
```

### Describe the Solution you'd like
It might be a good idea to make this configurable, so that you can choose whether to let such servers deliver mail or not. Some mail providers (especially the home-made ones) might not have a reverse DNS record, so everyone should be able to decide for themselves if they want to block these servers.

### Are you going to implement it?

Yes, because I know the probability of someone else doing it is low and I can learn from it.

### What are you going to contribute??
A PR with the appropriate patch.

### Alternatives you've considered
Not implementing it at all and sticking with the user-patches.sh file

### Who will that Feature be useful to?
Those who suffer from a lot of spam from these rouge mail servers

### What have you done already?
Added the above mentioned lines to my user-patches.sh file

**Comment by polarathene** [comment]
For now, a new ENV does not seem appropriate for such a small toggle (_we have some of these already that I rather we didn't_).

This would be better communicated in our docs as a solution via `user-patches.sh`, and referencing this issue for others to chime in or :+1: / :-1: 

If there would be more interest expressed by other users, or a good justification that demonstrates minimal negative impact for the change, we could add it by default I think. Perhaps look at other popular self-host mail-servers to see if they have such a setting by default? It would help provide more confidence adopting the change :)

---

Docs for reference: [`reject_unknown_reverse_client_hostname`](http://www.postfix.org/postconf.5.html#reject_unknown_reverse_client_hostname).

> `reject_unknown_client_hostname`:
> Reject the request when any of the following is true:
> 1. The client IP `address -> name` mapping fails.
> 2. The `name -> address` mapping fails.
> 3. The `name -> address` mapping does not match the client IP address.
> 
> `reject_unknown_reverse_client_hostname`:
> Only rule 1 applies.

- `reject_unknown_client_hostname` makes `reject_unknown_reverse_client_hostname` redundant to apply.
- If I understand correctly, it checks:
  1. A rDNS record exists (_doesn't have to match HELO hostname?_)
  2. HELO hostname has a DNS A record.
  3. That DNS A record resolves to same IP making the request.
- Users could additionally configure known problematic clients to bypass the restriction via [`check_client_access`](http://www.postfix.org/postconf.5.html#check_client_access).

I wouldn't expect this restriction to fail from reputable mail servers, but I don't run any large deployment to have such insights.

**Comment by GoliathLabs** [comment]
@polarathene I have now run some larger installations of docker-mailserver for two organizations. This has helped reduce the spam sent by some rogue mail servers. I believe the `reject_unknown_client_hostname` setting was also used by this guide (https://thomas-leister.de/en/mailserver-debian-stretch/) on which I built my previous mailserver. The guide was quite popular in the German community for self-hosted mail servers.

**Comment by polarathene** [comment]
> I have now run some larger installations of docker-mailserver for two organizations. This has helped reduce the spam sent by some rogue mail servers.

Awesome :)

> The guide was quite popular in the German community for self-hosted mail servers.

I prefer to reference other mail projects where you can track development and community issues with config more easily.

---

I looked at MailCow for you and [they do not have this restriction](https://github.com/mailcow/mailcow-dockerized/blob/94f4ec8b966db57e6623b37ea4a62cc18e113c53/data/conf/postfix/main.cf#L129)..

However on closer investigation with `git blame` it seems they once did and [moved it from Postfix `reject_unknown_reverse_client_hostname`](https://github.com/mailcow/mailcow-dockerized/commit/2e972fb03b5f0ea62a18ecf9a64b9537bb9be278) to [rspamd symbol `HFILTER_HOSTNAME_UNKNOWN`](https://github.com/mailcow/mailcow-dockerized/commit/99326f81deff966519934cd66fdab1a1a8363adc) late 2019. Sadly they commit directly, there doesn't seem to be any commit message or associated PR, just [comments like this](https://github.com/mailcow/mailcow-dockerized/issues/3168#issuecomment-557880328) stating the switch happened and [this discussion about switching](https://github.com/mailcow/mailcow-dockerized/issues/2829#issuecomment-517753084) (_but doesn't communicate that it actually happened_).

[This issue](https://github.com/mailcow/mailcow-dockerized/issues/1536#issuecomment-407812607) notes that a user has an issue with `reject_unknown_reverse_client_hostname`, with a reply:

> _It's not RFC-compliant to send email from a host without a PTR, so your client will have trouble sending to most other servers._

---

So technically another popular mail server already has been using this for a long time and continues to do so (just via rspamd instead). And the quoted reason seems fair.

[`mail-in-a-box`](https://github.com/mail-in-a-box/mailinabox) has no such config or discussion. `mailu` seems to be lacking configuration too, but [I'm given the impression they leverage `HFILTER_HOSTNAME_UNKNOWN` from `rspamd`](https://github.com/Mailu/Mailu/search?q=HFILTER_HOSTNAME_UNKNOWN&type=issues).

You may want to wait on other maintainer input, but I'm ok with a PR :+1:

**Comment by casperklein** [comment]
If already other (big) projects are using this restriction successful for a longer time, it seems to me, that this could also be a sane default for our next major release?

We could make this the default and just provide a documented solution via `user-patches.sh` on how to revert this.

**Comment by GoliathLabs** [comment]
@casperklein sounds good to me 👍🏼
