### ISSUE TITLE
PR #2535 not in v11.1.0 change log

### ISSUE THREAD

**Issue by groupmsl** [docker-mailserver/docker-mailserver#2657]
I was reading the changelog for v11.1.0 this morning and noticed that PR #2535 isn't mentioned anywhere. I think this is the first version it has been present in, so should probably be in the changelog?

Also, not that I'm really fussed, the contributors list hasn't been updated with my contribution.

**Comment by wernerfred** [comment]
Strange, i see both notes regarding your PR:

![image](https://user-images.githubusercontent.com/20406381/175267128-0dc7f4fc-2557-48de-a8cb-ddb400343c16.png)

and 

![image](https://user-images.githubusercontent.com/20406381/175267148-cc84b514-1ed8-458d-b33f-7dc33688d22d.png)

Also if you look at the workflow file for the all-contributors generation (https://github.com/docker-mailserver/docker-mailserver/blob/d2a0a5de2ed450bb13c01ca08ef4130da68fba3a/.github/workflows/contributors.yml#L5) it is scheduled to cron value which is monthly if i'm not wrong so the `README.md` will be updated by 2022/07/01

I will close this, comment if you think this is still an issue. Thanks for your contribution!

**Comment by groupmsl** [comment]
Interesting, the URL provided by the "Mailserver update available" email (https://github.com/docker-mailserver/docker-mailserver/blob/master/CHANGELOG.md) doesn't include this detail, but the release page (https://github.com/docker-mailserver/docker-mailserver/releases/tag/v11.1.0) does.

Anyway, this information is there if you look in the correct place, so ignore this ticket!

**Comment by polarathene** [comment]
> the URL [provided by the "Mailserver update available" email](https://github.com/docker-mailserver/docker-mailserver/blob/master/CHANGELOG.md) doesn't include this detail, but the [release page](https://github.com/docker-mailserver/docker-mailserver/releases/tag/v11.1.0) does.

The release page one was generated by the releases feature, I manually added the release notes above that, which is what was added to the `CHANGELOG.md` with the tagged release commit. Looks like I forgot to mention your feature contribution, sorry about that :sweat_smile: 

I've updated the release notes to include it and a PR to add to the v11.1 changelog :+1: Let me know if you'd like any changes.
