### ISSUE TITLE
Track/Alert when old Password is used in IMAP

### ISSUE THREAD

**Issue by ghnp5** [docker-mailserver/docker-mailserver#2659]
I'm wondering if you know whether it's possible to do something so that if the Old password is used to log in to an email address, we could log or raise an alert.

Even if we need to hardcode the old password somewhere.

This would be very useful in two scenarios I can think of:

1) After changing the password of an email address, to identify applications/cronjobs that are still using it, so we can update them

2) In case of a server being hacked, that contained that password saved in a config file, to be alerted if that hacker tried to access that email address after we changed the password, which indicates that the hacker actually saved files/code from that server and tried to make use of it

Thank you very much

**Comment by polarathene** [comment]
If you're not using LDAP for authentication, the user accounts are stored in `postfix-accounts.cf` and then copied over to a Dovecot config. Passwords are hashed with `SHA512-CRYPT`.

You'd need to keep a history of those hashes and I guess monitor the file to compare against known old password hashes. Additionally hooking into active authentication interactions would be more work.

**Comment by ghnp5** [comment]
Thank you very much for your reply. Yeah, I'm using `postfix-accounts.cf`.
And yup, I have the old hashes as well (I generate them manually and I keep this file versioned in a local repo).

> You'd need to keep a history of those hashes and I guess monitor the file to compare against known old password hashes.

Do you know how/where could I possibly do this?

Thanks much!

**Comment by polarathene** [comment]
> Do you know how/where could I possibly do this?

You could probably just monitor the `postfix-accounts.cf` file outside of the container?

I think inside the container there is logs for when users try to login through Dovecot, I am not sure how much information it logs, I think I recall it showing the hash on failed auth, which is probably what you want.

So perhaps try a failed login and looking at your logs for the container, you should see one from Dovecot like that and find something to monitor your logs for those lines, then a regular expression probably can extract the mentioned hash from the log and send that to some code you have to see if the hash exists in your list of old password hashes file? When that's true then have it notify yourself in your preferred way.

---

We can leave the issue open as a feature request if you want to try hold out for someone implementing it, but that is usually rare to see :sweat_smile:

**Comment by ghnp5** [comment]
Hey

Your suggestion was actually brilliant! That's exactly 100% sufficient for what I need to do.

The logs contain the first characters of the SHA1 hash of the attempted password, so that's perfect.

With a cron that runs "grep", I got what I needed :-)

Thank you!
