### ISSUE TITLE
How to configure markings

### ISSUE THREAD

**Issue by mpldr** [docker-mailserver/docker-mailserver#2668]
## Description

Hi, I am getting quite a number of encrypted mails which always get an obnoxious `***UNCHECKED***` prefix, which I would like to make more subtle by either removing it (which obviously wouldn't be preferable) or changing for a small `[U]` since in my mailclient is only taking up half a screen subjects are sometimes cut off making them hard to read.

It's similar for Spam.

```diff
+ [U] This one sparks joy
- ***UNCHECKED*** This one does not spark …
```

A quick grep over everything unfortunately did not reveal anything So how can I configure these markers?

**Comment by casperklein** [comment]
Take a look [here](https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/optional-config/) how to customize Amavis in DMS.

Adding `$undecipherable_subject_tag = undef;` should do what you want. See also [here](https://amavis-users.amavis.narkive.com/DRMOqoXe/how-to-remove-subject-unchecked#post4).
