### ISSUE TITLE
[BUG]  Fail2ban not blocking ip ranges when captured as a custom ban

### ISSUE THREAD

**Issue by ianb445** [docker-mailserver/docker-mailserver#2669]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

fail2ban is not actually invoking any iptables or equivalent ban

### What happened and when does this occur?

```Markdown
Although I can add custom ip's and ranges to be blocked using ./setup.sh fail2ban ban 123.123.0.0/16 the range is not actually being blocked.

#Fail2ban-client status custom 
Status for the jail: custom
|- Filter
|  |- Currently failed: 0
|  |- Total failed:     0
|  `- File list:
`- Actions
   |- Currently banned: 2
   |- Total banned:     2
   `- Banned IP list:   141.98.0.0/16 45.125.0.0/16

However in the standard logs:

Jun 29 12:56:04 mail postfix/submission/smtpd[2368]: warning: hostname good-server.outreachratio.com does not resolve to address 141.98.10.70: Name or service not known
Jun 29 12:56:04 mail postfix/submission/smtpd[2368]: connect from unknown[141.98.10.70]
Jun 29 12:56:05 mail postfix/submission/smtpd[2368]: Anonymous TLS connection established from unknown[141.98.10.70]: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
Jun 29 12:56:05 mail dovecot: auth: passwd-file(scans,141.98.10.70): unknown user (SHA1 of given password: 5baa61)
Jun 29 12:56:07 mail postfix/submission/smtpd[2368]: warning: unknown[141.98.10.70]: SASL LOGIN authentication failed: UGFzc3dvcmQ6
Jun 29 12:56:07 mail postfix/submission/smtpd[2368]: disconnect from unknown[141.98.10.70] ehlo=2 starttls=1 auth=0/1 quit=1 commands=4/5
```

### What did you expect to happen?

```Markdown
I can see that ip: 141.98.10.70 is still able to connect and try to authenticate.
```

### How do we replicate the issue?

```Markdown
1. Deploy mailserver and watch the logs for disctionary attacks.
2.
3.
...
```

### DMS version

latest

### What operating system is DMS running on?

Linux

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### What container orchestration tool are you using?

Docker Compose

### docker-compose.yml

```yml
version: "3.3"
services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    # If the FQDN for your mail-server is only two labels (eg: example.com),
    # you can assign this entirely to `hostname` and remove `domainname`.
    hostname: mail
    domainname: <<redacted>>
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - ./docker-data/dms/fail2ban/jail.d/:/etc/fail2ban/jail.d
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt/:/etc/letsencrypt/
    environment:
      - OVERRIDE_HOSTNAME=mail.<<redacted>>
      - ENABLE_FAIL2BAN=1
      - SSL_TYPE=letsencrypt
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```

### Relevant log output

```bash
Jun 29 12:56:04 mail postfix/submission/smtpd[2368]: warning: hostname good-server.outreachratio.com does not resolve to address 141.98.10.70: Name or service not known
Jun 29 12:56:04 mail postfix/submission/smtpd[2368]: connect from unknown[141.98.10.70]
Jun 29 12:56:05 mail postfix/submission/smtpd[2368]: Anonymous TLS connection established from unknown[141.98.10.70]: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
Jun 29 12:56:05 mail dovecot: auth: passwd-file(scans,141.98.10.70): unknown user (SHA1 of given password: 5baa61)
Jun 29 12:56:07 mail postfix/submission/smtpd[2368]: warning: unknown[141.98.10.70]: SASL LOGIN authentication failed: UGFzc3dvcmQ6
Jun 29 12:56:07 mail postfix/submission/smtpd[2368]: disconnect from unknown[141.98.10.70] ehlo=2 starttls=1 auth=0/1 quit=1 commands=4/5
```

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [ ] I am inexperienced with mail servers
- [ ] I am uncomfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by casperklein** [comment]
I can confirm this issue. From a quick check I don't think it's a DMS issue. In my test, the network is "banned" by fail2ban, however there seems no trace in nftables of that network. Banning single IPs however, works as expected and they are listed in nftables.

```
#Fail2ban-client status custom 
Status for the jail: custom
|- Filter
|  |- Currently failed: 0
|  |- Total failed:     0
|  `- File list:
`- Actions
   |- Currently banned: 2
   |- Total banned:     2
   `- Banned IP list:   141.98.0.0/16 45.125.0.0/16
```

Can you test, if you also see the banned networks with `nft list table inet f2b-table`?

**Comment by georglauterbach** [comment]
I am using custom nftables rules in addition to what DMS supplies, and I have seen this issue as well, and the key point is, as @casperklein mentioned, the `flags interval` option that NFT needs:

``` NFT
table inet custom_dms {
  set input_ban_censys {
    type ipv4_addr
    flags interval
    elements = { 74.120.14.0/24, 162.142.125.0/24,
           167.94.138.0/24, 167.94.145.0/24,
           167.94.146.0/24, 167.248.133.0/24,
           192.35.168.0/23 }
  }

  ...

  chain input {
    type filter hook input priority filter - 2; policy accept;
    ip saddr @input_ban_censys drop
    ...
  }
}
```

Now, I don't know whether we should open an issue upstream at [`fail2ban/fail2ban`](https://github.com/fail2ban/fail2ban) or adjust this in our configuration.

**Comment by casperklein** [comment]
> Now, I don't know whether we should open an issue upstream at [`fail2ban/fail2ban`](https://github.com/fail2ban/fail2ban) 

This is a known [issue](https://github.com/fail2ban/fail2ban/issues/3125).

**Comment by ianb445** [comment]
@casperklein I tried the script, which is executed (not sure of the output though)
[   INF   ]  Welcome to docker-mailserver 11.1.0
[   INF   ]  Initializing setup
[   INF   ]  Checking configuration
[   INF   ]  Configuring mail server
[CUSTOMIZE]  fail2ban network ban fix
[   INF   ]  Post-configuration checks

However the nft output looks the same, no networks banned. Tried running the script from within the container, no change either. (no errors thrown).

**Comment by casperklein** [comment]
Are there any errors in `/var/log/fail2ban.log`?

**Comment by ianb445** [comment]
No, no errors in the f2b log. Just the usual ban and unbans as it goes along. Since the attacker is using a class B address, I have set the checks and history to scan over 2 days to see whether I can ban more and that seems to improve things as some of the addresses come up more frequently.

**Comment by casperklein** [comment]
@ianb445 

In the meantime, where there any new insights from your side? Unfortunately, I don't have an idea, why it's not working for you with the provided patch 😞

**Comment by georglauterbach** [comment]
I think the `sed` does not what it was supposed to do...

**Comment by casperklein** [comment]
@ianb445 please check, what the output of this command is:

`grep ^_nft_add_set /etc/fail2ban/action.d/nftables.conf`

If it's only:

`_nft_add_set = <nftables> add set <table_family> <table> <addr_set> \{ type <addr_type>\; \}`

then the patch does not work. In that case, double-check, if you have any copy/paste errors or something.

**Comment by GoliathLabs** [comment]
@ianb445 any updates on this?

**Comment by casperklein** [comment]
My fix in https://github.com/docker-mailserver/docker-mailserver/issues/2669#issuecomment-1170524027 missed a parameter. I've edited my post.
