### ISSUE TITLE
Reloading SSL certificate

### ISSUE THREAD

**Issue by ra1u** [docker-mailserver/docker-mailserver#2672]
On the frontend proxy, I use traefik, which generates _acme.json_. For security reasons, I do not want to expose all the private certificates that _acme.json_ exports, so I convert _acme.json_ to standard crt/key files and that's the reason for the manual setup `SSL_TYPE=manual` .

The question is:
 How can I tell [docker-mailserver](https://github.com/docker-mailserver/docker-mailserver) to reload ssl certificates as soon as they are renewed. Currently I restart the service manually, but I think there must be a better way.

**Comment by ra1u** [comment]
Edit :
As per recent [documentaion](https://docker-mailserver.github.io/docker-mailserver/v11.1/config/security/ssl/#bring-your-own-certificates) it seems there is no better way

**Comment by casperklein** [comment]
AFAIK the [changedetector](https://github.com/docker-mailserver/docker-mailserver/blob/master/target/scripts/check-for-changes.sh) service should handle that out of the box. If not, you may open a bug report.

**Comment by Jip-Hop** [comment]
Automatic reloading of manual SSL certificates works for me with DMS version 11.1.0.

Inside my compose file I have:

```yml
    environment:
      - SSL_TYPE=manual
      - SSL_CERT_PATH=/etc/dms/tls/cert.crt
      - SSL_KEY_PATH=/etc/dms/tls/cert.key
      - LOG_LEVEL=debug
```
and
```yml
    volumes:
      - /mnt/ssltest/cert.crt:/etc/dms/tls/cert.crt:ro
      - /mnt/ssltest/cert.key:/etc/dms/tls/cert.key:ro
```

When I generate a new certificate with `openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout cert.key -out cert.crt` in the `/mnt/ssltest` folder I can see it's picked up when connecting with the Apple Mail client. In the logs I can see the dovecot service is restarted:

```
Jul  8 16:57:50 mail2 dovecot: master: Warning: Killed with signal 15 (by pid=7 uid=0 code=kill)
Jul  8 16:57:50 mail2 postfix/master[5064]: terminating on signal 15
Jul  8 16:57:51 mail2 postfix/master[5846]: daemon started -- version 3.5.6, configuration /etc/postfix
Jul  8 16:57:51 mail2 dovecot: master: Dovecot v2.3.13 (89f716dc2) starting up for imap, lmtp
```

But I don't see the logging from `[check-for-changes.sh](https://github.com/docker-mailserver/docker-mailserver/blob/master/target/scripts/check-for-changes.sh)` even with logging set to debug or trace:

```yml
    environment:
      - LOG_LEVEL=debug
```
or
```yml
    environment:
      - LOG_LEVEL=trace
```

I then opened a shell inside the container with `docker exec -it 1888ed55be47 /bin/bash` to inspect the `changedetector.log`:

```
root@mail2:/# tail /var/log/supervisor/changedetector.log 
[  DEBUG  ]  2022-07-08 17:06:48  Manual certificates have changed - extracting certificates
[  DEBUG  ]  Setting up SSL
[  DEBUG  ]  TLS configured with 'modern' ciphers
[  DEBUG  ]  Configuring certificates using key /etc/dms/tls/cert.key and cert /etc/dms/tls/cert.crt
[  DEBUG  ]  2022-07-08 17:06:48  Restarting services due to detected changes
postfix: stopped
postfix: started
dovecot: stopped
dovecot: started
[  DEBUG  ]  2022-07-08 17:06:53  Completed handling of detected change
```

This confirms that the changedetector works 🙂
