### ISSUE TITLE
Kubernetes error 

### ISSUE THREAD

**Issue by IvayLoRD** [docker-mailserver/docker-mailserver#2675]
I would like to configure a not documented mail server use case

Hi, I'm trying to run docker-mailserver as explained here https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/kubernetes/ but I get the following error does anyone have any idea what it's coming from and why ?

# CODE GOES HERE

Еvents:
  Type     Reason       Age               From               Message
  ----     ------       ----              ----               -------
  Normal   Scheduled    16s               default-scheduler  Successfully assigned mail/mailserver-6d576676fc-6kvl8 to ip-172-31-27-16.eu-central-1.compute.internal
  Warning  FailedMount  8s (x5 over 16s)  kubelet            MountVolume.SetUp failed for volume "files" : object "mail"/"mailserver.files" not registered
  Warning  FailedMount  8s (x5 over 16s)  kubelet            MountVolume.SetUp failed for volume "kube-api-access-knr4m" : object "mail"/"kube-root-ca.crt" not registered

**Comment by georglauterbach** [comment]
Please use the bug template, this allows us to properly analyse your problem.

The error message here is simple: you are trying to mount `mailserver.files`, a `ConfigMap` (that is in our docs!), but the configmap does not seems to be there.

**Comment by aliuq** [comment]
I got the same error

```bash
> kgp -n mail-server

NAME                           READY   STATUS    RESTARTS   AGE
mail-server-7bf4dc9cf8-vmfmj   0/1     Blocked   0          9m51s
```

```bash
> k describe -n mail-server po mail-server-7bf4dc9cf8-vmfmj

…………
Type     Reason       Age              From               Message
  ----     ------       ----             ----               -------
  Normal   Scheduled    6s               default-scheduler  Successfully assigned mail-server/mail-server-7bf4dc9cf8-vmfmj to server1
  Warning  FailedMount  3s (x4 over 7s)  kubelet            MountVolume.SetUp failed for volume "certificates-rsa" : object "mail-server"/"mail-tls-certificate-rsa" not registered
  Warning  FailedMount  3s (x4 over 7s)  kubelet            MountVolume.SetUp failed for volume "kube-api-access-tw2fx" : object "mail-server"/"kube-root-ca.crt" not registered
```

I think this cause may be caused by deployment annotation `container.apparmor.security.beta.kubernetes.io/mailserver`, after I delete it, it works running.

According to the [documentation](https://kubernetes.io/docs/tutorials/security/apparmor/), it requires that the kubernetes version be at least `1.4` or higher

```bash
kubectl get nodes -o=jsonpath=$'{range .items[*]}{@.metadata.name}: {@.status.nodeInfo.kubeletVersion}\n{end}'
```

my kubernetes version is `v1.23.9+k3s1`, so I think that's what caused it to blocked
