### ISSUE TITLE
Is it posible to have a truted list (fail2ban)

### ISSUE THREAD

**Issue by Skyfay** [docker-mailserver/docker-mailserver#2676]
Hey, i got a status server who ask my mail server if he is online. 
Now the mail server has blocked the ip of my status server.
Is there a way to always list the IP as not evil?
When I unbanned the IP, I got the following values:
Unbanned IP from dovecot and Unbanned IP from postfix-sasl.

Thanks for help!

**Comment by georglauterbach** [comment]
Took me like 5 seconds to search for this this: <https://www.fail2ban.org/wiki/index.php/Whitelist>. You may use `user-patches.sh` (<https://docker-mailserver.github.io/docker-mailserver/edge/faq/#how-to-adjust-settings-with-the-user-patchessh-script>) to patch the configuration file.

Please note that this issue tracker is not meant for personal support.

**Comment by casperklein** [comment]
First I would check, why the monitoring server is blocked and fix that instead. I assume, wrong credentials are used.

You can customize fail2ban. Look for `fail2ban-jail.conf` [here](https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/optional-config/).

For whitelisting, see the example here:

https://github.com/docker-mailserver/docker-mailserver/blob/061828ce021c24bdb088138a744914c9dfe33422/config-examples/fail2ban-jail.cf#L13-L16

**Comment by muchachagrande** [comment]
I know this was closed a long time ago, but just for the record, I had a problem concerning this issue.
As my network is dual stack my mail server is reachable with both IPv4 and IPv6.
Recently I discovered that my mail server was being used as relay by some spammers because I misunderstood the PERMIT_DOCKER option.
After fixing the problem, fail2ban detected some failed logins coming from an IPv6 address but docker showed 172.17.0.1 as the source address because it's not IPv6 enabled docker installation.
The result is that fail2ban banned 172.17.0.1 and that action blocked IPv6 LAN access for all services.
I think that in this case adding the docker host IP to the ignoreip is needed to avoid being blocked.

**Comment by casperklein** [comment]
> After fixing the problem, fail2ban detected some failed logins coming from an IPv6 address but docker showed 172.17.0.1

There is more to consider than fail2ban. I can imagine, that SPF checks etc. may also fail, when DMS is only aware of local addresses instead of the real ones.

**Comment by muchachagrande** [comment]
May be SPF checks could fail. I didn't dig enough into the problem to see that.
Since I'm using RSPAMD I've configured ENABLE_POLICYD_SPF=0. I don't know if it has something to do with the SPF checking you have mentioned.

**Comment by muchachagrande** [comment]
The only check I could make to test this was sending an email to my server from the phone outside my network using a Gmail account.
I used Gmail because their servers are IPv6 enabled and they reach my server over IPv6.
I didn't find any SPF reference in the headers but I could see the header "Received: from mail-oa1-x2b.google.com (unknown [172.17.0.1])"
If I check the server log I can see the complete transaction:
> May 12 11:35:46 mail postfix/postscreen[111407]: CONNECT from [172.17.0.1]:52880 to [172.17.0.15]:25
> May 12 11:35:46 mail postfix/postscreen[111407]: PASS OLD [172.17.0.1]:52880
> May 12 11:35:46 mail postfix/smtpd[111408]: connect from unknown[172.17.0.1]
> May 12 11:35:47 mail postfix/smtpd[111408]: Anonymous TLS connection established from unknown[172.17.0.1]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature RSA-PSS (4096 bits) server-digest SHA256
> May 12 11:35:47 mail postfix/smtpd[111408]: 2E9C6106170: client=unknown[172.17.0.1]
> May 12 11:35:47 mail postfix/cleanup[111414]: 2E9C6106170: message-id=<0A9F9473-E175-4787-A964-9B4939942AD3@gmail.com>
> May 12 11:35:47 mail postfix/qmgr[811]: 2E9C6106170: from=<mymail@gmail.com>, size=4220, nrcpt=1 (queue active)
> May 12 11:35:47 mail dovecot: lmtp(111420): Connect from local
> May 12 11:35:47 mail dovecot: lmtp(myname@mymailserver.com)<111420><6aH5N8NOXmQ8swEAZU03Dg>: sieve: msgid=<0A9F9473-E175-4787-A964-9B4939942AD3@gmail.com>: stored mail into mailbox 'INBOX'
> May 12 11:35:47 mail postfix/lmtp[111419]: 2E9C6106170: to=<myname@mymailserver.com>, relay=mail.mymailserver.com[/var/run/dovecot/lmtp], delay=0.78, delays=0.76/0.01/0.01/0.01, dsn=2.0.0, status=sent (250 2.0.0 <myname@mymailserver.com> 6aH5N8NOXmQ8swEAZU03Dg Saved)
> May 12 11:35:47 mail dovecot: lmtp(111420): Disconnect from local: Logged out (state=READY)
> May 12 11:35:47 mail postfix/qmgr[811]: 2E9C6106170: removed

You can see that the real IPv6 address is masqueraded with the docker host IPv4 address 172.17.0.1.
This IPv4 address is the one fail2ban see in the logs, so when someone try to access the server from IPv6 guessing a password, after 6 tries fail2ban will ban 172.17.0.1, because the postfix log only can see that address, and not the IPv6.

**Comment by georglauterbach** [comment]
When you inspect the email you received in raw format (with headers), you should see the full list of headers. This is what we're interested in.

**Comment by muchachagrande** [comment]
Return-Path: <mymail@gmail.com>
Delivered-To: myname@mymailserver.com
Received: from mail.mymailserver.com
	by mail.mymailserver.com with LMTP
	id 6aH5N8NOXmQ8swEAZU03Dg
	(envelope-from <mymail@gmail.com>)
	for <myname@mymailserver.com>; Fri, 12 May 2023 11:35:47 -0300
Received: from mail-oa1-x2b.google.com (unknown [172.17.0.1])
	by mail.mymailserver.com (Postfix) with ESMTPS id 2E9C6106170
	for <myname@mymailserver.com>; Fri, 12 May 2023 11:35:47 -0300 (-03)
Received: by mail-oa1-x2b.google.com with SMTP id 586e51a60fabf-18b1c643219so4091463fac.2
        for <myname@mymailserver.com>; Fri, 12 May 2023 07:35:47 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20221208; t=1683902145; x=1686494145;
        h=content-transfer-encoding:mime-version:message-id:references
         :in-reply-to:subject:to:from:date:from:to:cc:subject:date:message-id
         :reply-to;
        bh=pyBvetFwZWeD6wvLy4RT3jK3V9By616pqtJZdVkWK/k=;
        b=InSQ3w5dKoza4yKFPN8IRQoF83Gw7R7aM7MCvei+mAbZQ0nDZuijt2npe2A++3ocex
         OBcljmxsqNk99YwIzQ9UhvF7yx1Io8b9dFsScLyroR4wkK/2doDj6WlRB6ryEQMTBTCM
         D23DsVXcel0MaqTWZAzQeVf5pQ5a6Chup3dLQ639fXyGX3qww6TEseLTKAWawtMKJtLa
         iIxa1TbBkl7BI0PMqyZPgMH7QvfYp05NUqsBXJ3P/IJ+sysDFUlhb3Qw7V3IIIZ4U5Ct
         Fw58cziu3vbLPYvwksUCbLDZ0BbHHJ/w4bq5hE2OyMbS4GGTAoopw7EoI5g4C9Rjkmd0
         jmYQ==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20221208; t=1683902145; x=1686494145;
        h=content-transfer-encoding:mime-version:message-id:references
         :in-reply-to:subject:to:from:date:x-gm-message-state:from:to:cc
         :subject:date:message-id:reply-to;
        bh=hqBvetFwZWeD6wvLu4RT3jK2q9By61tpqtJZdVkWK/k=;
        b=W9A79n8YxtyzCLvsQbZxyIJ5iPzyrfoiuJynriZHFsUK513KliQuempRkMzEi3WNQb
         mJQOV2KL/1LzqpI2ueL7lSWJh87xJ8eTWBuMgdbmoXuHzuN51d7qG4bW1n2Apb5b6uLp
         czi2JS7Q0h4Vw5go+DeG1fx/o8Jq+Pt6Hgnd5JMF3Xc92zU46GM2f0SLQLh5P1Br31GW
         ZxlZ3eLrbtQTWtPohhKyZKtrk29LLloMWvAH+V/n2SkEIXrRk6aJDgtwvGakY54UrvTq
         UbosS80gHYWHlwX6sdPnoe8eXOM3KNw/a6xmjEG1gDulWKNh5mX2eQh0LBQoHwOsC6/NO
         zWtg==
X-Gm-Message-State: AC+VfDxtfOYtQ6pFg0+xA2fMTTpwKh3h2lMc/DRMo+DMB+FMXlO/epp6
	zWH08s+rH7LzNxCFvgcoOI4+UdAxkBE=
X-Google-Smtp-Source: ACHHUZ4pdX5wJyKl+05ibkD6uBV3sZ1RfoP7wKnZzfFcSE76OS5dYqkHlJxvZJpMlc6K9+bmZSGwYw==
X-Received: by 2002:a05:6870:a2c2:b0:184:53f3:ae08 with SMTP id w2-20020a056870a2c200b0018453f3ae08mr13243656oak.9.1683902145301;
        Fri, 12 May 2023 07:35:45 -0700 (PDT)
Received: from [127.0.0.1] ([185.142.133.181])
        by smtp.gmail.com with ESMTPSA id n17-20020a9d7411000000b006ab0981ef17sm4957438otk.64.2023.05.12.07.35.43
        for <myname@mymailserver.com>
        (version=TLS1_3 cipher=TLS_AES_128_GCM_SHA256 bits=128/128);
        Fri, 12 May 2023 07:35:44 -0700 (PDT)
Date: Fri, 12 May 2023 11:35:38 -0300
From: My Name <mymail@gmail.com>
To: My Name <myname@mymailserver.com>
Subject: Re: Test
In-Reply-To: <34f8313a-ecfe-d8c8-1ba4-c5a47ed03067@mymailserver.com>
References: <34f8313a-ecfe-d8c8-1ba4-c5a47ed03067@mymailserver.com>
Message-ID: <0A9F9473-E175-4787-A964-9B4939942AD3@gmail.com>
MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary=----8CQOKAQYI2BUQNRXXTHSLYP8QNN1NI
Content-Transfer-Encoding: 7bit

------8CQOKAQYI2BUQNRXXTHSLYP8QNN1NI
Content-Type: text/plain;
 charset=utf-8
Content-Transfer-Encoding: quoted-printable

Lalala

El 10 de mayo de 2023 17:37:40 ART, My Name <myname@mymailserver=2Ec=
om> escribi=C3=B3:
>
>--=20
>*/My Name/*
------8CQOKAQYI2BUQNRXXTHSLYP8QNN1NI
Content-Type: text/html;
 charset=utf-8
Content-Transfer-Encoding: quoted-printable

<html>
  <head>

    <meta http-equiv=3D"content-type" content=3D"text/html; charset=3DUTF-=
8">
  </head>
  <body><div dir=3D"auto">Lalala</div><br><br><div class=3D"gmail_quote"><=
div dir=3D"auto">El 10 de mayo de 2023 17:37:40 ART, My Name &lt;m=
yname@mymailserver=2Ecom&gt; escribi=C3=B3:</div><blockquote class=3D"gma=
il_quote" style=3D"margin: 0pt 0pt 0pt 0=2E8ex; border-left: 1px solid rgb(=
204, 204, 204); padding-left: 1ex;">

    <br>
    </blockquote></div></body>
</html>

------8CQOKAQYI2BUQNRXXTHSLYP8QNN1NI--

**Comment by muchachagrande** [comment]
Yes. Apparently it is working as expected. I can see the history on the web panel.
Also I can see two errors on the list below the history panel:



> 12/5/2023, 11:06:40 | rspamd_proxy | 744 | lua | 3b55d6 | error querying dns \"208.252.30.192.asn.rspamd.com\" on 192.168.2.1: query timed out
> 11/5/2023, 16:30:18 | rspamd_proxy | 744 | proxy | a2fd31 | cannot  load dkim key /var/lib/rspamd/dkim/gmail.com.dkim.key: cannot stat key  file: '/var/lib/rspamd/dkim/gmail.com.dkim.key' No such file or  directory

**Comment by georglauterbach** [comment]
> Also I can see two errors on the list below the history panel:
>
> > error querying dns "208.252.30.192.asn.rspamd.com" on 192.168.2.1: query timed out

This just means the DNS request was unsuccessful: unrelated.

> cannot load dkim key /var/lib/rspamd/dkim/gmail.com.dkim.key: cannot stat key file: '/var/lib/rspamd/dkim/gmail.com.dkim.key' No such file or directory

You seem to have provided a DKIM signing configuration, but Rspamd cannot access the path. We have proper documentation about this, please check the access rights!

---

> Each time I receive a test mail from Gmail it appears the error above

This does not actually make a lot of sense, because DKIM signing is for **outbound** email, **not for incoming** email. I guess the error is generated each time Rspamd is doing something, regardless of what it is. This is not related to Fail2Ban either. Please check your setup, I'm certain this is an error on your side (access rights, missing permissions, missing files, typos, etc.) and not related to DMS.

---

If you have an issue that you believe to be a bug inside DMS, please open a new bug report, so we can properly evaluate it :) We are currently working on revising our IPv6 docs (see #3244), hopefully this will also help.

Also thank you very much for adding information about your setup here.

**Comment by muchachagrande** [comment]
> You seem to have provided a DKIM signing configuration, but Rspamd cannot access the path. We have proper documentation about this, please check the access rights!

I will check my config, but I can confirm in advance that I didn't provide a DKIM signing configuration. In fact, I didn't read that part of the DMS documentation yet.

> We are currently working on revising our IPv6 docs (see #3244), hopefully this will also help.

Digging into the PR I can confirm what I was suspecting: I need to enable IPv6 all the way to DMS. So I need to enable Docker to use IPv6.

> Also thank you very much for adding information about your setup here.

Sure, thank you for you awesome work on DMS.

**Comment by muchachagrande** [comment]
One last update on this subject.
I followed some instructions from #1438 and from https://github.com/robbertkl/docker-ipv6nat and could enable IPv6 specifically for DMS container. The other containers I have kept untouched.

The only test I made so far is sending a mail from Gmail to myself on DMS and apparently now it goes with IPv6 all along.

> May 14 18:48:20 mail postfix/postscreen[1266]: CONNECT from [2001:4860:4864:20::29]:49388 to [fd00:caca:ceca:c0ca::2]:25
> May 14 18:48:26 mail postfix/postscreen[1266]: PASS NEW [2001:4860:4864:20::29]:49388
> May 14 18:48:34 mail postfix/smtpd[1276]: connect from mail-oa1-x29.google.com[2001:4860:4864:20::29]
> May 14 18:48:35 mail postfix/smtpd[1276]: Anonymous TLS connection established from mail-oa1-x29.google.com[2001:4860:4864:20::29]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature RSA-PSS (4096 bits) server-digest SHA256
> May 14 18:48:35 mail postfix/smtpd[1276]: 786D4101417: client=mail-oa1-x29.google.com[2001:4860:4864:20::29]
> May 14 18:48:35 mail postfix/cleanup[1297]: 786D4101417: message-id=<B555666E-2CB3-4C49-8E05-AA5D4EBC4F62@gmail.com>
> May 14 18:48:43 mail postfix/qmgr[802]: 786D4101417: from=<mymail@gmail.com>, size=4261, nrcpt=1 (queue active)
> May 14 18:48:43 mail dovecot: lmtp(1309): Connect from local
> May 14 18:48:43 mail dovecot: lmtp(myname@mymailserver.com)<1309><TGg0ATtXYWQdBQAAZU03Dg>: sieve: msgid=<B555666E-2CB3-4C49-8E05-AA5D4EBC4F62@gmail.com>: stored mail into mailbox 'INBOX'
> May 14 18:48:43 mail dovecot: lmtp(1309): Disconnect from local: Logged out (state=READY)
> May 14 18:48:43 mail postfix/lmtp[1308]: 786D4101417: to=<myname@mymailserver.com>, relay=mail.mymailserver.com[/var/run/dovecot/lmtp], delay=7.6, delays=7.5/0/0.01/0.02, dsn=2.0.0, status=sent (250 2.0.0 <myname@mymailserver.com> TGg0ATtXYWQdBQAAZU03Dg Saved)
> May 14 18:48:43 mail postfix/qmgr[802]: 786D4101417: removed
> May 14 18:49:16 mail postfix/smtpd[1276]: disconnect from mail-oa1-x29.google.com[2001:4860:4864:20::29] ehlo=2 starttls=1 mail=1 rcpt=1 bdat=1 quit=1 commands=7

Now I can see Google mail server IPv6 address in the places where I was seeing Docker IPv4 host address.
Rspamd web interface also shows IPv6 address correctly.

The steps I made were just three:
1 - created a new bridge network on Docker with IPv6 enabled, just to avoid touching IPv6 flag for the daemon.
2 - created a new [robbertkl/ipv6nat] container following the instructions on its github page.
3 - recreated the DMS container replacing the default bridge with the newly created one.

After these steps DMS obtained an IPv4 and an IPv6 address and that's all.

Thank you for pointing me out to the IPv6 discussion.

**Comment by georglauterbach** [comment]
Just pinging you here @polarathene  because the last comment from @muchachagrande might (or might not) be interesting for your IPv6 research :)

**Comment by polarathene** [comment]
They chose to use the `ipv6nat` image to avoid `ip6tables: true` + `experimental: true` in the `/etc/docker/daemon.json` file. That image was created before Docker added proper support. I've heard it does configure things slightly differently, but I'm not sure if we'll document that.

Should be successful with enabling IPv6 through official Docker settings too :+1: 

Thanks for the ping though, it's appreciated :)

**Comment by muchachagrande** [comment]
> Should be successful with enabling IPv6 through official Docker settings too +1

Ok, I followed the instructions on [#3057](https://github.com/docker-mailserver/docker-mailserver/pull/3057#issuecomment-1416706615) and now I'm using Docker's own IPv6 support not needing ipv6nat container anymore.

Thanks @polarathene for the info.
