### ISSUE TITLE
Deprecation Notice: Dropping `TLS_LEVEL=intermediate` support for TLS < 1.2

### ISSUE THREAD

**Issue by polarathene** [docker-mailserver/docker-mailserver#2679]
A [recent support issue](https://github.com/docker-mailserver/docker-mailserver/issues/2674#issuecomment-1178370911) raised awareness of [RFC 8996](https://www.rfc-editor.org/rfc/rfc8996) (Dec 2021), which **officially deprecates** TLS 1.0 (1999) and TLS 1.1 (2006).

The linked RFC document provides justification.

To clarify, this is the **removal of support for TLS 1.0 and TLS 1.1** protocols. **`TLS_LEVEL=intermediate` will remain** for broader cipher coverage for the time being.

---

### Additional reasoning

TLS 1.2 has been available since 2008 and broadly deployed by around 2016. There had been some exceptions with popular mail clients and devices that especially in the context of mail software deployments + clients lagging behind, that our support via the `intermediate` setting of `TLS_LEVEL` remained supported.

Debian, our current base image has already defaulted to TLS 1.2 as a minimum, requiring us to downgrade security when `TLS_LEVEL=intermediate` is required, simply adjusting a service config such as Dovecots to allow for lower TLS protocols is no longer sufficient. Newer versions of Postfix and Dovecot may likewise in the future drop support completely themselves too.

---

### User Impact

Inbound mail should not be affected. Port 25 does not mandate a secure connection. No serious MTA should lack support for TLS 1.2.

You should not realistically need support for TLS 1.0 or TLS 1.1, except in niche scenarios such as an old printer/scanner devices that refuse to negotiate a compatible non-vulnerable cipher.

Usually these affected devices are old enough that the internet will be failing to verify certificates as the root CA certs on the device expire due to a lack of system updates.

[These ciphers are to be dropped](https://github.com/docker-mailserver/docker-mailserver/blob/061828ce021c24bdb088138a744914c9dfe33422/test/security_tls_cipherlists.bats#L209):

- `ECDHE-ECDSA-AES128-SHA`
- `ECDHE-RSA-AES128-SHA`
- `ECDHE-ECDSA-AES256-SHA`
- `ECDHE-RSA-AES256-SHA`
- `DHE-RSA-AES128-SHA`
- `DHE-RSA-AES256-SHA`

---

### Feedback

**If you have any concerns or real use-cases** requiring this support, please let us know.

Should a few users require support, we can provide documentation for additional configuration steps, but **official support is intended to be dropped** going forward.

**Comment by georglauterbach** [comment]
@polarathene this is already in v11.3, right? If so, can this be closed?

**Comment by polarathene** [comment]
No deprecation notice was added to changelog and release notes for v11.3, so that we can make the changes for v12. I'll create a PR sometime this week for each deprecation.

**Comment by casperklein** [comment]
> No deprecation notice was added to changelog

This bugged me for a while 😆 I thought NO deprecation notice was added to changelog. But looking at the changelog, there is a notice.

**Comment by polarathene** [comment]
> This bugged me for a while

Whoops, I see how I phrased that really poorly, sorry about that! :sweat_smile:
