### ISSUE TITLE
[BUG] Broken links on documentation page

### ISSUE THREAD

**Issue by ladrua** [docker-mailserver/docker-mailserver#2680]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

Docs

### What happened and when does this occur?

```Markdown
On the docs page https://docker-mailserver.github.io/ the internal links/clicks are broken from version 11.1 and up.
```

### What did you expect to happen?

```Markdown
I expected it to work.
```

### How do we replicate the issue?

```Markdown
1. Go to https://docker-mailserver.github.io/docker-mailserver/edge/faq/ and try to click any of the internal page links.
```

### DMS version

v11.1

### What operating system is DMS running on?

Linux

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### What container orchestration tool are you using?

Docker Compose

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [ ] I am inexperienced with mail servers
- [ ] I am uncomfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by polarathene** [comment]
Confirmed, thank you for reporting this. It's likely a bug from the docs generator we use.

The links still work if you open them on a new tab or copy the link and paste it into the url bar. Not a great workaround, and not likely something our CI would be able to easily pick up I guess.

**Comment by polarathene** [comment]
> So if you have to expand a example div it wont work.

Oh, that's even worse. Surely the upstream project must be aware of such a big bug like that, I'll take a look, otherwise I'll raise one there.

**Comment by polarathene** [comment]
This was caught upstream about a month ago and has been resolved. Once the PR updates our version of the docs generator in CI, `edge` docs will no longer have regressed. `v11.1` docs will get regenerated afterwards and fix that regression too.
