### ISSUE TITLE
[BUG] `setup.sh fail2ban` ignores IPv6 bans

### ISSUE THREAD

**Issue by alterNERDtive** [docker-mailserver/docker-mailserver#2687]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

`setup.sh fail2ban` ignores IPv6 bans

### What happened and when does this occur?

```Markdown
So I was troubleshooting connection issues and couldn’t for the life of me connect to either postfix or dovecot over IPv6. Meanwhile I could happily see someone else log in via v6.

I _had_ checked `setup.sh fail2ban` prior, and double checked again. It reported “No IPs have been banned” both times. `exec`ing a shell later, I could see & remove the ban using the regular `fail2ban` command inside the container.
```

### What did you expect to happen?

```Markdown
I expected `setup.sh fail2ban` to list IPv6 bans in addition to IPv4 bans. I also expected a `setup.sh fail2ban unban <IPv6 address>` that I tried anyway to work.
```

### How do we replicate the issue?

```Markdown
1. Enable fail2ban.
2. Get your local IPv6 address banned by e.g. using the wrong password enough times.
3. Observe connection issues.
4. Run `setup.sh fail2ban`.
5. Observe “No IPs have been banned”.
6. Look at fail2bans actual database.
7. Observe your local IPv6 address having been banned.
```

### DMS version

11.1.0

### What operating system is DMS running on?

Linux

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### What container orchestration tool are you using?

Podman (not officially supported)

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [ ] I am inexperienced with mail servers
- [ ] I am uncomfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by alterNERDtive** [comment]
Also thanks for creating this, saved me a lot of effort. And it’s a nice new toy to tinker with ;)

**Comment by casperklein** [comment]
The regex used here, does not cover IPv6 yet:

https://github.com/docker-mailserver/docker-mailserver/blob/684903f8d2642d6a98e4723321ecc2f0d3f0c5a4/target/bin/fail2ban#L12

I'll fix that soon.

**Comment by casperklein** [comment]
@alterNERDtive The current edge build should fix your issue.

**Comment by alterNERDtive** [comment]
> @alterNERDtive The current edge build should fix your issue.

Top, thank you very much <3
