### ISSUE TITLE
[BUG] LDAP bind password shows up in log as cleartext

### ISSUE THREAD

**Issue by spirkaa** [docker-mailserver/docker-mailserver#2692]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

cleartext password in log

### What happened and when does this occur?

```Markdown
At container startup LDAP bind password shows up in log as cleartext at LOG_LEVEL=info.
```

### What did you expect to happen?

```Markdown
No LDAP bind password shows up in log as cleartext at LOG_LEVEL=info.
```

### How do we replicate the issue?

```Markdown
1. Configure LDAP_* env vars
2. Start up container
3. Look at logs
```

### DMS version

v11.1.0

### What operating system is DMS running on?

Linux

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### What container orchestration tool are you using?

Docker

### Relevant log output

```bash
>> /etc/postfix/ldap-users.cf: saslauthd_ldap_password = myLdapBindPass
>> /etc/postfix/ldap-users.cf: bind_pw = myLdapBindPass
>> /etc/postfix/ldap-groups.cf: saslauthd_ldap_password = myLdapBindPass
>> /etc/postfix/ldap-groups.cf: bind_pw = myLdapBindPass
>> /etc/postfix/ldap-aliases.cf: saslauthd_ldap_password = myLdapBindPass
>> /etc/postfix/ldap-aliases.cf: bind_pw = myLdapBindPass
>> /etc/postfix/ldap-domains.cf: saslauthd_ldap_password = myLdapBindPass
>> /etc/postfix/ldap-domains.cf: bind_pw = myLdapBindPass
>> /etc/postfix/ldap-senders.cf: saslauthd_ldap_password = myLdapBindPass
>> /etc/postfix/ldap-senders.cf: bind_pw = myLdapBindPass
>> /etc/dovecot/dovecot-ldap.conf.ext: dnpass = myLdapBindPass
```

### Other relevant information

```Markdown
I'm using read-only service account created exclusively for docker-mailserver, but someone less experienced may use personal or even domain admin account for ldap bind and leak his password through the log.
```

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [ ] I am inexperienced with mail servers
- [ ] I am uncomfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by polarathene** [comment]
This looks like [it's probably caused by a third-party dependency](https://github.com/alinmear/docker-configomat/blob/415550485438d7e6ca6136016cca4bbab99ccf6f/configomat.sh#L50) (`configomat.sh`), not us directly.

@alinmear is the maintainer of that project. I'm not sure why it's doing the `echo`, if it cannot be fixed upstream, we could perhaps swap out the git submodule and maintain our own copy?

**Comment by alinmear** [comment]
hi, the Implementation is an easy way to parametrize multiple config values in an easy way. therefore how can we separate sensitive from non sensitive data to hide them from being printed? or should we use some sort of debug flag?

**Comment by polarathene** [comment]
@georglauterbach or @casperklein probably have a better opinion about resolving that.

Is it necessary to output those lines, or is it just debug info? A debug flag to omit the lines being output unnecessarily would be good I think :)

**Comment by georglauterbach** [comment]
I have had a look at the LDAP code and therefore this submodule before. Please, don't get me wrong, but I found it hard to understand, and it is therefore hard to maintain. If we can somehow do the same with our own code (i.e. without the submodule), I'd definitely go for that. If this cannot be done, maybe the submodule could try to make use of the log level we set and use.

**Comment by alinmear** [comment]
feel free :)

**Comment by georglauterbach** [comment]
> feel free :)

I would, but I am currently ill and I do not have proper knowledge of the LDAP code to write a proper alternative. Could you shortly explain how your tool works @alinmear? Maybe we can find time in the future, and provide a quick-fix for now.

**Comment by polarathene** [comment]
I took a shot at this, but I wrote it in rust which I'm more comfortable with. If you're open to introducing a rust binary instead of a script file for this functionality we can use it.

---

I ran my port against the [`configomat.sh` test suite](https://github.com/alinmear/docker-configomat/blob/415550485438d7e6ca6136016cca4bbab99ccf6f/test/tests.bats) and it passed everything correctly (_including the disabled tests_). Some failures were only due to `configomat.sh` itself only supporting `key = value`, whereas my port won't adjust the white-space (which AFAIK was a limitation of `configomat.sh`:

Test suite output:
```
cat /tmp/example.conf

key_1 = (&(objectClass=PostfixBookMailAccount)(|(uniqueIdentifier=%n)(mail=%u)))
key_2 = *+=/_-%&
key_3 =new_value_3
key_4 =new_value_4
key_5= new_value_5
key_6=new_value_6
key_7 = uid=user,userPassword=password
key_8 = (&(objectClass=mailAccount)(uid=%n))
key_9 = =home=/var/mail/%{ldap:mail}, =mail=maildir:/var/mail/%{ldap:mail}/Maildir
key_10 = (&(objectClass=mailAccount)(uid=%n))
```

---

I've deviated a bit to use an option for the ENV prefix, but keep the file path list CLI syntax. I figured it'd be a bit nicer to be more explicit about the ENV prefix, if it's not supplied the tool will still fail and notify the user.

There's also additional options:
- `-d` / `--delimiter` for choosing a different key/value delimiter than `=` if preferred.
- `--log-level` (or the ENV `CONFIGOMAT_LOG_LEVEL`) which defaults to `info`, but when `debug` or higher will output lines being changed like `configomat.sh` does.

Help output generated (it's also colour coded similar to our utilities):

```console
$ configomat-rs --help

configomat-rs 0.1.0
A rust port of configomat.sh

USAGE:
    configomat-rs [OPTIONS] --env-prefix <ENV_PREFIX> <FILE_PATHS>...

ARGS:
    <FILE_PATHS>...    A list of file paths to process

OPTIONS:
    -d, --delimiter <DELIMITER>      The first occurrence in a line delimits the key from the value [default: =]
    -e, --env-prefix <ENV_PREFIX>    The prefix to match ENV to keys in config files
    -h, --help                       Print help information
        --log-level <LOG_LEVEL>      Set the log level [env: CONFIGOMAT_LOG_LEVEL=] [default: info]
    -V, --version                    Print version information
```

<details>
<summary>Source Code</summary>

**`Cargo.toml`:**
```toml
[package]
name = "configomat-rs"
version = "0.1.0"
description = "A rust port of configomat.sh"
edition = "2021"

[dependencies]
anyhow = "1.0.58"
atomicwrites = "0.3.1"
clap = { version = "3.2.15", features = ["derive", "env"] }
flexi_logger = { version = "0.22.5", default_features = false, features = ["colors"] }
log = "0.4.17"
```

**`src/main.rs`:**
```rust
use anyhow::{Context, Result};
use atomicwrites::{AtomicFile,AllowOverwrite};
use clap::Parser;
use flexi_logger::Logger;
use log::{debug};
use std::env;
use std::collections::HashMap;
use std::io::{Write};
use std::path::PathBuf;

#[derive(Parser)]
#[clap(about, version)]
struct Args {
  /// The first occurrence in a line delimits the key from the value
  #[clap(short, long, default_value="=")]
  delimiter: char,

  /// The prefix to match ENV to keys in config files
  #[clap(short, long)]
  env_prefix: String,

  /// A list of file paths to process
  #[clap(value_parser, required(true))]
  file_paths: Vec<PathBuf>,

  /// Set the log level
  #[clap(long, env("CONFIGOMAT_LOG_LEVEL"), default_value="info")]
  log_level: log::Level,
}

fn main() -> Result<(), anyhow::Error> {
  let args = Args::parse();
  Logger::try_with_str(args.log_level.as_str())?.start()?;

  // Parse ENV and collect any matching the requested prefix:
  let mut env_with_prefix = HashMap::new();
  for (key, value) in env::vars() {
    if let Some(matched_key) = key.strip_prefix(&args.env_prefix) {
      env_with_prefix.insert(matched_key.to_lowercase(), value);
    }
  }

  // Update config files to use values for keys matched by ENV:
  for path in args.file_paths {
    let file_contents = std::fs::read_to_string(&path)
      // Using `anyhow` crate for nicer error message output:
      .with_context(||
        format!("Could not read file `{}`", &path.display())
      )?;

    // Match any keys (with ENV prefix stripped) in the config files,
    // then replace the value of that key with the one provided from ENV:
    debug!("Updating `{}` with values from ENV...", path.display());
    let with_contents = replace_values(&file_contents, &env_with_prefix, args.delimiter);

    // Writes modified content to a temporary file,
    // performs a filesystem sync,
    // then replaces the original file atomically via rename:
    AtomicFile::new(&path, AllowOverwrite).write(|file| {
      file.write_all(with_contents.as_bytes())
    })?;
  }

  Ok(())
}

fn replace_values(contents: &str, keys_to_update: &HashMap<String,String>, delimiter: char) -> String {
  contents.lines().map(|line| {
    // Split a line into key/value pair with white-space trimmed.
    // If the ENV lookup matches the key, replace the value.
    line.split_once(delimiter)
      .and_then(|(k,v)| {
        let key = k.trim_end().to_lowercase();
        let val = v.trim_start();

        // Reconstruct original line, but replace original value with ENV:
        keys_to_update.get(&key).map(|env_val| {
          debug!("- {key} = {env_val}");
          format!("{k}={}", v.replace(val, env_val))
        })
      })
      // Otherwise keep the original line unmodified:
      .unwrap_or_else(|| line.to_string())
  })
  // Merge all lines back into a multi-line string:
  .collect::<Vec<String>>().join("\n")
}
```

</details>

<details>
<summary>Error output scenarios handled</summary>

Error example when potential option has a typo:

```console
$ configomat-rs --envprefox 'LDAP_' 'path/to/file.cf'

error: Found argument '--envprefox' which wasn't expected, or isn't valid in this context

  Did you mean '--env-prefix'?

  If you tried to supply `--envprefox` as a value rather than a flag, use `-- --envprefox`

USAGE:
    configomat-rs --env-prefix <ENV_PREFIX> <FILE_PATHS>...

For more information try --help
```

Error for missing required arg:

```console
$ configomat-rs 'path/to/file.cf'

error: The following required arguments were not provided:
    --env-prefix <ENV_PREFIX>

USAGE:
    configomat-rs --env-prefix <ENV_PREFIX> <FILE_PATHS>...

For more information try --help
```

No file paths provided (same error):

```console
$ configomat-rs --env-prefix='LDAP_'

error: The following required arguments were not provided:
    <FILE_PATHS>...

USAGE:
    configomat-rs --env-prefix <ENV_PREFIX> <FILE_PATHS>...

For more information try --help
```

Multiple missing required args:

```console
$ configomat-rs

error: The following required arguments were not provided:
    --env-prefix <ENV_PREFIX>
    <FILE_PATHS>...

USAGE:
    configomat-rs --env-prefix <ENV_PREFIX> <FILE_PATHS>...

For more information try --help
```

Internal failure when a file path is provided that is invalid:

```console
$ configomat-rs --env-prefix='LDAP_' 'invalid_file.txt'

Error: Could not read file `invalid_file.txt`

Caused by:
    No such file or directory (os error 2)
```

</details>

**Comment by polarathene** [comment]
Quite possibly :)

**Comment by casperklein** [comment]
Just edited my post, after I saw your post 😉

**Comment by georglauterbach** [comment]
Got to admin, I too think this is a Bash project, but I like the Rust-port alot :D I have no objection against introducing it because it seems more up-to-date (and maybe I can get my hands dirty with Rust again... :D).

**Comment by casperklein** [comment]
I've provided a quick fix for the issue. Replacing configomat - if still needed - should be handled in a different issue/PR.
