### ISSUE TITLE
[FR] improving documentation in cron tasks

### ISSUE THREAD

**Issue by JiLleON** [docker-mailserver/docker-mailserver#2702]
# Feature Request

## Context

1. When using the [example](https://docker-mailserver.github.io/docker-mailserver/edge/faq/#how-can-i-make-spamassassin-better-recognize-spam) from the documentation with cron tasks inside the container, I receive information about the execution of these tasks by email.
2. In the variant with the [Xapian](https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/full-text-search/#xapian) plugin, in step 5 it is proposed to add a system cron task. I would like to add as a possible option 6 with cron inside the container as it was done [here](https://docker-mailserver.github.io/docker-mailserver/edge/faq/#how-can-i-make-spamassassin-better-recognize-spam)

### Is your Feature Request related to a Problem?

1. To some extent. At first, I didn't quite understand why I was getting these messages, but after "google" my problem, I found out that cron can actually send messages and found ways to solve it.
2. Nope

### Describe the Solution you'd like

1. I found solutions [here](https://www.cyberciti.biz/faq/disable-the-mail-alert-by-crontab-command/) and [here](https://serverfault.com/questions/256712/how-to-disable-cron-job-mailing-to-root-user) + check [man cron](https://manpages.debian.org/bullseye/cron/cron.8.en.html#NOTES) which has a mention of this behavior. I suggest adding `MAILTO=""` to the cron task with spamassassin configuration, as well as to my second suggestion, if it is accepted.
2. Write a process about the same as with [spamassassin example in faq](https://docker-mailserver.github.io/docker-mailserver/edge/faq/#how-can-i-make-spamassassin-better-recognize-spam)

### Are you going to implement it?

Yes, because I know the probability of someone else doing it is low and I can learn from it.

### What are you going to contribute??

PR with an edited addition to the documentation

### Alternatives you've considered

Description in 1 case below in the example that you will receive emails from cron every day with the result of this task (6 emails in the morning, xd)
![betterbird_dIu1zxoKAo](https://user-images.githubusercontent.com/28780165/181652522-ec45f05b-0653-4842-ab43-66c2f841e7a4.png)

### Who will that Feature be useful to?

All by default. Some will not need it, for this you should leave a description of what `MAILTO=""` does.

### What have you done already?

I tested option with `MAILTO=""` and the option with `> /dev/null 2>&1`. Both are working and I have not received any more emails in my installation.

**Comment by polarathene** [comment]
Nicely detailed, thank you! :)

> ### What are you going to contribute??
> PR with an edited addition to the documentation

Improvement to the docs would be greatly appreciated. This request looks worthwhile to document for users.

I think the appropriate section might be in [`Config --> Advanced --> Maintenance`](https://github.com/docker-mailserver/docker-mailserver/tree/428477a87879ed9d48a725ddc6372e4fba16779c/docs/content/config/advanced/maintenance)? You could create a new page (markdown document) there about managing cron, and if you like shift relevant content from the existing pages detailing cron management/examples. If you do add a new page, just reference it in our [`mkdocs.yml` here](https://github.com/docker-mailserver/docker-mailserver/blob/428477a87879ed9d48a725ddc6372e4fba16779c/docs/mkdocs.yml#L135-L136) and it'll appear in navigation menus.

You can [follow these instructions](https://docker-mailserver.github.io/docker-mailserver/edge/contributing/documentation/#docker-way) if you'd like to spin up a docker container to locally preview your changes while you work on them.

Alternatively, if you'd like to keep the contribution simple, adding a small FAQ entry and having the referenced docs content link to that is fine too.

**Comment by casperklein** [comment]
Have you tested, if `> /dev/null` produce any output? If there is no output, this should be used IMO, instead of completely makeing cron silence. This way, the postmaster gets notified, when something goes wrong.

**Comment by JiLleON** [comment]
@casperklein
>This way, the postmaster gets notified, when something goes wrong.

Maybe I'm wrong, but how did I understand using `MAILTO=""` = `> /dev/null 2>&1` except that with `MAILTO=""`:
>it might be worth mentioning that even with this, the output will be retained in a temporary file until the process exits without sending a mail; this may even fill up the filesystem where /tmp is.

With my tests, at any value, `postmaster@example.com` does not receive emailing notifications after cron tasks are performed.

Perhaps this is undesirable by default and as an alternative I can specify in the [example](https://docker-mailserver.github.io/docker-mailserver/edge/faq/#how-can-i-make-spamassassin-better-recognize-spam) that if you do not use any of these options you will receive notifications for the `postmaster@example.com`every day.

I see no point in giving this behavior a separate entry in the FAQ or anywhere else in the documentation because we have only 1 cron task in all documentation (not counting cron task that I suggested adding for dovecot-fts-xapian).

**Comment by polarathene** [comment]
> Writing to `/dev/null` seemed like "cheating", especially for documentation.

I don't see why it's cheating. You're just saying redirect the output stream to this location (could be `/dev/null` or log file, etc).

If you go over your linked references from your original issue message, they do clarify that you can only send `stdout` to `/dev/null` so that only errors raised by `stderr` would be noticed by cron to react to. This is what @casperklein meant AFAIK.

Some programs still output to `stderr` even when it's not an actual error however. So it depends on the command running, if redirecting `stdout` to the void is effective at preventing mail of successful runs, but still mailing errors for the admin to be aware of.

**Comment by JiLleON** [comment]
@polarathene 
> I don't see why it's cheating

I put it wrong:smiling_face_with_tear:

>from your original issue message

Oh, I understand what you mean. I misunderstood what @casperklein wrote, I thought he meant the same option that I originally suggested, and not the one that involves sending messages only in case with errors in `stderr` with `/dev/null`, sorry.

I tested the behavior with `/dev/null` just now. In the case of `sa-learn`, only error messages come to the email. In the case of  `dovecot-fts-xapian`, all messages are sent to the email.

It is perfectly. With `sa-learn` we can specify `> /dev/null` in the cron task without any notes, since only errors will be sent to the email. With `dovecot-fts-xapian`, we can leave the current variant in PR. What do you think about this?

**Comment by JiLleON** [comment]
@casperklein 
I agree that adding `MAILTO=""` to crontab is unacceptable, but I'm not suggesting adding it to crontab, only leaving it in a separate task that I suggested in PR, that regarding `dovecot-fts-xapian`.
