### ISSUE TITLE
TLS Connection Error with Thunderbird but Rainloop Webmail Client Connects Okay

### ISSUE THREAD

**Issue by dc-bond** [docker-mailserver/docker-mailserver#2710]
# Subject

I have questions about TLS/SSL/STARTTLS/OpenSSL

## Description

I have docker-mailserver deployed and working perfectly fine with a separate rainloop webmail container. When I setup the rainloop client to connect to IMAP (port 993) and SMTP submission (port 587) with the relevant details, it connects fine with this docker-mailserver log result:

```
Jul 31 20:34:04 ef7ae9e64cf8 postfix/submission/smtpd[64445]: Anonymous TLS connection established from unknown[192.168.1.1]: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
```

Using the exact same connection details in Thunderbird produces the following error from docker-mailserver logs:

``` 
Jul 31 20:30:29 ef7ae9e64cf8 dovecot: imap-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=192.168.1.1, lip=192.168.160.2, TLS handshaking: SSL_accept() failed: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca: SSL alert number 48, session=<64JiGyPlRpXAqAEB>
```

Happy to provide more details on my setup if needed, otherwise any ideas on why Thunderbird is throwing a TLS error when my other webmail client works okay? Thanks!

**Comment by georglauterbach** [comment]
This is probably something related to certificates. How did you get your certificates, what does your setup look like?

**Comment by dc-bond** [comment]
I got custom certificates directly from my DNS provider cloudflare and plugged them into the container.

docker-compose environment snippet:

```
- SSL_TYPE=manual
- SSL_CERT_PATH=/tmp/dms/custom-certs/example.dev.cert
- SSL_KEY_PATH=/tmp/dms/custom-certs/example.dev.key
- SSL_DOMAIN=example.dev
```
docker-compose volume snippet:

```
- /home/dc-bond/docker-stack/mailserver/certs/:/tmp/dms/custom-certs/:ro
```

**Comment by georglauterbach** [comment]
Try removing `SSL_DOMAIN`. Can you somehow try to validate the certs in another way, to see whether they work?

**Comment by casperklein** [comment]
`unknown ca` is pretty clear. Thunderbird is not aware of the signing CA. This must be fixed.

**Comment by polarathene** [comment]
I am not familiar with Cloudflare providing certs, unless it's [like described here](https://community.cloudflare.com/t/https-certificate-not-trusted/3610/12) which says they are only meant for web. The link has an earlier mention of intermediate chain that you may also need.

It may explain why a webmail client works fine (_although I'd have thought it would have similar problems to Thunderbird with the TLS connection to the actual mail server_), are you using the Cloudflare cert for the HTTPS cert of Rainloop as well or just your mail?

Could you try with LetsEncrypt? We have [docs on how to do that easily with `certbot`](https://docker-mailserver.github.io/docker-mailserver/edge/config/security/ssl/#example-using-docker-for-lets-encrypt). We also have a [guide on generating self-signed certs here](https://docker-mailserver.github.io/docker-mailserver/edge/config/security/ssl/#generating-a-self-signed-certificate), but you must add the generated root CA to your system trust store.

**Comment by georglauterbach** [comment]
I agree with @polarathene. I am using Cloudflare's Origin certificates for web services (HTTP(S)), and Let'sEncryot for my mail certs. I do not think CF issues certs in general like LE does.

**Comment by dc-bond** [comment]
Solved! So I just reconfigured my traefik instance to pull a Let's Encrypt certificate for my example.dev domain, and then wired up the docker-mailserver container to use that certificate instead of the "Cloudflare Origin Certificate" I was using before. Now all works in both Rainloop and Thunderbird as it should.

Thanks all!
