### ISSUE TITLE
Settings discovery

### ISSUE THREAD

**Issue by Akronae** [docker-mailserver/docker-mailserver#2719]
# Subject

I would like to configure a not documented mail server use case

## Description

Is it possible to configure the mail server "settings discovery"?
For instance when using Google Apps as mail server, I can just enter my domain (linked to google app), my username and password and the mail client will figure out automatically the correct host to use :
![image](https://user-images.githubusercontent.com/17302866/184086759-67a0d135-1f91-4842-b7bf-aeec740577d9.png)

However when using a custom mail server I have to manually enter the mail server address, even is there is a MX record pointing to the correct mail server on my domain.

**Comment by ontheair81** [comment]
This is not done by the mailserver itself and has nothing to do with MX records. You need to create a webserver on that domain, delivering a XML-file with all the necesseary informations.
Mail clients will search for this XML and adapt the settings.

There are - as far as I know - two different syntaxes:
- "autodiscover" for Outlook
- "autoconfig" for all other mail clients

Just search for "autoconfig" / "autodiscover" online and you will find the necessary informations.
For all of my mail domains I am running an "autoconfig" webserver and all client softwares are therefore configured automatically without any problem.

**Comment by Akronae** [comment]
Thank you @ontheair81 I did not know about that spec!

**Comment by casperklein** [comment]
See also here: https://docker-mailserver.github.io/docker-mailserver/edge/config/best-practices/autodiscover/
