### ISSUE TITLE
[BUG] `ENABLE_SRS=1` causing high CPU usage with `postsrsd`

### ISSUE THREAD

**Issue by polarathene** [docker-mailserver/docker-mailserver#2722]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

postsrsd

### What happened and when does this occur?

Another user [reported to upstream `postsrsd`](https://github.com/roehling/postsrsd/issues/122) experiencing this same issue earlier in the year (_specifically with DMS_).

I noticed this while working on a PR and debugging local test failures. Why the tests do not fail in our CI is unclear (_might be due to older environment/packages in CI?_):

```
 ✗ checking configuration: hostname/domainname override: check headers of received mail [235]
   (from function `assert_success' in file test/test_helper/bats-assert/src/assert.bash, line 114,
    in test file test/mail_hostname.bats, line 104)
     `assert_success' failed
   
   -- command failed --
   status : 1
   output : ls: cannot access '/var/mail/localhost.localdomain/user1/new': No such file or directory
   --
```

```
 ✗ checking configuration: non-subdomain: check headers of received mail [308]
   (from function `assert_success' in file test/test_helper/bats-assert/src/assert.bash, line 114,
    in test file test/mail_hostname.bats, line 163)
     `assert_success' failed
   
   -- command failed --
   status : 1
   output : ls: cannot access '/var/mail/localhost.localdomain/user1/new': No such file or directory
   --
```

I had a process monitor active in the background and noticed the four containers spun up in that test each used 25% CPU for the containers `postsrsd` process.

When starting a single container in my VM (2vCPU) `postsrsd` was consistently showing 50% CPU usage, despite no mail to process.

The ports `10001` and `10002` are not bound to localhost:

```console
$ ss -tulpn | grep LISTEN

tcp   LISTEN 0      4096       127.0.0.1:10024      0.0.0.0:*                                     
tcp   LISTEN 0      100        127.0.0.1:10025      0.0.0.0:*                                     
tcp   LISTEN 0      100          0.0.0.0:587        0.0.0.0:*                                     
tcp   LISTEN 0      100          0.0.0.0:143        0.0.0.0:*    users:(("dovecot",pid=642,fd=32))
tcp   LISTEN 0      100          0.0.0.0:465        0.0.0.0:*                                     
tcp   LISTEN 0      100          0.0.0.0:65265      0.0.0.0:*    users:(("dovecot",pid=642,fd=54))
tcp   LISTEN 0      100          0.0.0.0:25         0.0.0.0:*                                     
tcp   LISTEN 0      4096       127.0.0.1:8891       0.0.0.0:*                                     
tcp   LISTEN 0      4096       127.0.0.1:8893       0.0.0.0:*                                     
tcp   LISTEN 0      100             [::]:587           [::]:*                                     
tcp   LISTEN 0      100             [::]:143           [::]:*    users:(("dovecot",pid=642,fd=33))
tcp   LISTEN 0      100             [::]:465           [::]:*                                     
tcp   LISTEN 0      100             [::]:65265         [::]:*    users:(("dovecot",pid=642,fd=55))
tcp   LISTEN 0      100             [::]:25            [::]:*
```

`postsrsd` process is running:

```console
$ ps aux | grep postsrsd

root         591  0.0  0.0   4864  3872 pts/0    S    02:37   0:00 /bin/bash /usr/local/bin/postsrsd-wrapper.sh
root         623  0.0  0.0   2420  1592 pts/0    S    02:37   0:00 /bin/sh /etc/init.d/postsrsd start
root         774 98.2  0.0   2332   708 pts/0    R    02:37   3:01 /usr/sbin/postsrsd -f 10001 -r 10002 -d example.test -s /etc/postsrsd.secret -a = -n 4 -N 4 -u postsrsd -p /var/run/postsrsd.pid -c /var/lib/postsrsd -l 127.0.0.1 -D -X
```

However after roughly 10 minutes running like this, `postsrsd` heavy CPU activity ceases and the ports do show as bound. It's unclear why it takes this long.

### What did you expect to happen?

`postsrsd` should not be consuming so much CPU activity, nor taking about 10 minutes to finish starting up. Possibly stuck in [this upstream _while loop_](https://github.com/roehling/postsrsd/blob/6e701fa51f26bb344bc0230cdfb13ae1e14afb8d/postsrsd.c#L645)?

### How do we replicate the issue?

1. Next step uses the config dir of the failed test container, but it should reproduce with a minimal config containing `postfix-accounts.cf` from the `make generate-accounts` command.
2. Run:
   ```bash
   docker run --rm -it \
     --volume "${PWD}/test/duplicate_configs/mail_override_hostname:/tmp/docker-mailserver" \
     --volume "${PWD}/test/test-files:/tmp/docker-mailserver-test:ro" \
     -e ENABLE_SRS=1 \
     -h 'example.com' \
     --name 'postsrsd_cpu' \
     "mailserver/docker-mailserver:edge"
   ```
   
2. Monitor the `postsrsd` process, it should show high CPU activity (_can be observed on the host, does not require running anything within the container_).
3. Run `docker exec -it postsrsd_cpu bash` in a separate terminal, and then try send a mail `sendmail -f 'user@external.tld' 'user1@localhost.localdomain' < /tmp/docker-mailserver-test/email-templates/existing-user1.txt`
4. DMS will respond to it but fail as it can't reach the PostSRSD service on `localhost:10001`, as the service is running (`ps aux | grep postsrsd`) but ports are not yet bound (`ss -tulpn | grep LISTEN`), and our logs appear to be useless (_`cat /var/log/supervisor/postsrsd.log` only has a line about the service being started, nothing added once it quiets down 10 mins later_).
5. Monitor the `postsrsd` process, it should cease the heavy workload after a while, and ports for the service finally bound. Mail can then be sent to the local user account as before and actually be received (`ls /var/mail/localhost.localdomain/user1`).

### DMS version

v11.1

### What operating system is DMS running on?

Linux

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### What container orchestration tool are you using?

Docker

### Docker CLI command

```bash
docker run --rm -it \
  --volume "${PWD}/test/duplicate_configs/mail_override_hostname:/tmp/docker-mailserver" \
  --volume "${PWD}/test/test-files:/tmp/docker-mailserver-test:ro" \
  -e ENABLE_SRS=1 \
  -h 'example.com' \
  --name 'postsrsd_cpu' \
  'mailserver/docker-mailserver:edge'
```

### Relevant log output

Nothing relevant was logged, other than the failure to handle the mail due to the service not yet being up.

### Other relevant information

I suspect the environment may have something to do with it.

Environment is:

- VMWare Workstation Player 16.3 on a Linux 5.17 x86_64 host.
- VM guest is Fedora 36 (5.18.9 kernel), Docker version is 20.10.17.
- CPU (2vCPU) under 50% load reported in the guest OS, 4GB RAM + 4GB swap (ZRAM), 2GB of each free.

Network if it's something going wrong with the binding step:

```console
$ ip addr show

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever

1511: eth0@if1512: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:ac:11:00:03 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.17.0.3/16 brd 172.17.255.255 scope global eth0
       valid_lft forever preferred_lft forever
```

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

### Improvements to this form?

It's eating up markdown syntax when some inputs are wrapped in codefences upon submission, while others are assuming formats such as `yml` for `docker-compose.yml` config sharing, despite saying you can also provide a docker CLI command instead.

**Comment by polarathene** [comment]
I've identified the cause upstream in `postsrsd`. It normally would perform 1024 iterations at most closing file descriptors, but in a Docker container the max limit is massively larger (over 1 billion), hence the huge delay starting the command (_if calling it directly with only the `-d` option and not `-s` that is also required, it fails that validation after the FD iterations_).

Presumably there is something with the Ubuntu 20.04 environment in the CI, or Github configures the Docker daemon to use a much more sane limit (`ulimit -n`) for containers. If anyone does run into this issue until it's resolved upstream (_and I guess as a package in Debian?_), you can use [`--ulimit 'nofile=1024'`](https://docs.docker.com/engine/reference/commandline/run/#set-ulimits-in-container---ulimit) as a workaround.

**Comment by polarathene** [comment]
This also affects `fail2ban` upstream.

Although that's much more complicated for me to pinpoint if it's in their codebase or an upstream dependency of theirs. I [raised an issue about it](https://github.com/fail2ban/fail2ban/issues/3334) upstream.

So that's another test suite failure resolved :sweat_smile: 

---

Without the workaround (_if your environment is affected_), `fail2ban` fails to start and with our service wrapper `fail2ban-wrapper.sh` log for the service is spammed:

```
2022-08-16 03:27:05,570 fail2ban                [2369]: ERROR   Could not start server. Maybe an old socket file is still present. Try to remove /var/run/fail2ban/fail2ban.sock. If you used fail2ban-client to start the server, adding the -x option will do it
/usr/local/bin/fail2ban-wrapper.sh: line 27: /var/run/fail2ban/fail2ban.pid: No such file or directory
/usr/local/bin/fail2ban-wrapper.sh: line 27: kill: `': not a pid or valid job spec
```

which also results in `fail2ban-server` instances accumulating (_presumably due to our `kill` handling failing?_):

```console
$ ps aux | grep fail2ban

root         558 33.5  0.2  22780 11768 ?        R    03:20   3:22 /usr/bin/python3 /usr/bin/fail2ban-server --async -b -s /var/run/fail2ban/fail2ban.sock -p /var/run/fail2ban/fail2ban.pid --loglevel INFO --logtarget /var/log/fail2ban.log --syslogsocket auto
root        1362 29.6  0.2  22780 11856 ?        R    03:21   2:48 /usr/bin/python3 /usr/bin/fail2ban-server --async -b -s /var/run/fail2ban/fail2ban.sock -p /var/run/fail2ban/fail2ban.pid --loglevel INFO --logtarget /var/log/fail2ban.log --syslogsocket auto
root        1481 25.1  0.2  22780 11828 ?        R    03:21   2:13 /usr/bin/python3 /usr/bin/fail2ban-server --async -b -s /var/run/fail2ban/fail2ban.sock -p /var/run/fail2ban/fail2ban.pid --loglevel INFO --logtarget /var/log/fail2ban.log --syslogsocket auto
root        1592 22.2  0.2  22780 11736 ?        R    03:22   1:50 /usr/bin/python3 /usr/bin/fail2ban-server --async -b -s /var/run/fail2ban/fail2ban.sock -p /var/run/fail2ban/fail2ban.pid --loglevel INFO --logtarget /var/log/fail2ban.log --syslogsocket auto
root        1706 20.2  0.2  22780 11824 ?        R    03:22   1:33 /usr/bin/python3 /usr/bin/fail2ban-server --async -b -s /var/run/fail2ban/fail2ban.sock -p /var/run/fail2ban/fail2ban.pid --loglevel INFO --logtarget /var/log/fail2ban.log --syslogsocket auto
root        1816 18.6  0.2  22780 11776 ?        R    03:23   1:19 /usr/bin/python3 /usr/bin/fail2ban-server --async -b -s /var/run/fail2ban/fail2ban.sock -p /var/run/fail2ban/fail2ban.pid --loglevel INFO --logtarget /var/log/fail2ban.log --syslogsocket auto
root        1930 17.2  0.2  22780 11780 ?        R    03:24   1:07 /usr/bin/python3 /usr/bin/fail2ban-server --async -b -s /var/run/fail2ban/fail2ban.sock -p /var/run/fail2ban/fail2ban.pid --loglevel INFO --logtarget /var/log/fail2ban.log --syslogsocket auto
root        2041 16.3  0.2  22780 11844 ?        R    03:24   0:57 /usr/bin/python3 /usr/bin/fail2ban-server --async -b -s /var/run/fail2ban/fail2ban.sock -p /var/run/fail2ban/fail2ban.pid --loglevel INFO --logtarget /var/log/fail2ban.log --syslogsocket auto
root        2151 15.3  0.3  22780 11936 ?        R    03:25   0:48 /usr/bin/python3 /usr/bin/fail2ban-server --async -b -s /var/run/fail2ban/fail2ban.sock -p /var/run/fail2ban/fail2ban.pid --loglevel INFO --logtarget /var/log/fail2ban.log --syslogsocket auto
root        2264 14.5  0.2  22780 11816 ?        R    03:25   0:41 /usr/bin/python3 /usr/bin/fail2ban-server --async -b -s /var/run/fail2ban/fail2ban.sock -p /var/run/fail2ban/fail2ban.pid --loglevel INFO --logtarget /var/log/fail2ban.log --syslogsocket auto
root        2372 14.1  0.2  22780 11800 ?        R    03:26   0:34 /usr/bin/python3 /usr/bin/fail2ban-server --async -b -s /var/run/fail2ban/fail2ban.sock -p /var/run/fail2ban/fail2ban.pid --loglevel INFO --logtarget /var/log/fail2ban.log --syslogsocket auto
root        2484 13.6  0.2  22780 11804 ?        R    03:27   0:28 /usr/bin/python3 /usr/bin/fail2ban-server --async -b -s /var/run/fail2ban/fail2ban.sock -p /var/run/fail2ban/fail2ban.pid --loglevel INFO --logtarget /var/log/fail2ban.log --syslogsocket auto
root        2595 12.9  0.2  22780 11800 ?        R    03:27   0:22 /usr/bin/python3 /usr/bin/fail2ban-server --async -b -s /var/run/fail2ban/fail2ban.sock -p /var/run/fail2ban/fail2ban.pid --loglevel INFO --logtarget /var/log/fail2ban.log --syslogsocket auto
root        2709 12.4  0.2  22780 11864 ?        R    03:28   0:17 /usr/bin/python3 /usr/bin/fail2ban-server --async -b -s /var/run/fail2ban/fail2ban.sock -p /var/run/fail2ban/fail2ban.pid --loglevel INFO --logtarget /var/log/fail2ban.log --syslogsocket auto
root        2822 11.9  0.2  22780 11760 ?        R    03:28   0:12 /usr/bin/python3 /usr/bin/fail2ban-server --async -b -s /var/run/fail2ban/fail2ban.sock -p /var/run/fail2ban/fail2ban.pid --loglevel INFO --logtarget /var/log/fail2ban.log --syslogsocket auto
root        2928 11.8  0.2  22780 11752 ?        R    03:29   0:07 /usr/bin/python3 /usr/bin/fail2ban-server --async -b -s /var/run/fail2ban/fail2ban.sock -p /var/run/fail2ban/fail2ban.pid --loglevel INFO --logtarget /var/log/fail2ban.log --syslogsocket auto
root        3032  0.0  0.0   4204  3024 pts/0    S    03:30   0:00 /bin/bash /usr/local/bin/fail2ban-wrapper.sh
root        3033  0.3  0.3  18840 15380 pts/0    S    03:30   0:00 /usr/bin/python3 /usr/bin/fail2ban-client start
root        3034  0.3  0.0      0     0 pts/0    Z    03:30   0:00 [fail2ban-server] <defunct>
root        3042 11.1  0.2  22780 11856 ?        R    03:30   0:03 /usr/bin/python3 /usr/bin/fail2ban-server --async -b -s /var/run/fail2ban/fail2ban.sock -p /var/run/fail2ban/fail2ban.pid --loglevel INFO --logtarget /var/log/fail2ban.log --syslogsocket auto
root        3123  0.0  0.0   3180   668 pts/1    S+   03:30   0:00 grep fail2ban
```

**Comment by polarathene** [comment]
Sharing some findings here for result of running `docker run --rm alpine ash -c 'ulimit -Sn && ulimit -Hn'` (_numbers formatted for glancing over quickly_), where `-Sn` is the _soft limit_ and `-Hn` the _hard limit_:

- On the Fedora 36 VM guest (hypervisor VMware Workstation 16.3): **1 073 741 816**
- On my current Manjaro host: **1 048 576**

`ulimit -n` outputs **1024** outside of docker for both OS.

In the containers the `-Sn` and `-Hn` values are equivalent (_hard limit is optional and inherits the soft limit unless set separately_). The default limits are defined in the kernel (_with overrides set in `/etc/security/limit.conf`_), but [systemd can also override the limits since v240 with 512K (**524 288**)](https://github.com/systemd/systemd/blob/1742aae2aa8cd33897250d6fcfbe10928e43eb2f/NEWS#L60..L94) (_see linked changelog for reasoning, noting some software requiring 300K and other software such as Java allocating excessive memory if set too high such as 1G_).

---

**UPDATE:** I've since learned that [`/etc/security/limits.conf` is specifically config for the `pam_limits` module used in PAM](https://wiki.archlinux.org/title/Realtime_process_management#Configuring_PAM) and affects users logged in (_[but not systemd managed services](https://wiki.archlinux.org/title/Limits.conf)_):

> _There are two types of resource limits that `pam_limits` provides: **hard limits** and **soft limits**. Hard limits are set by `root` and enforced by the kernel, while soft limits may be configured by the user within the range allowed by the hard limits._

That's further described in the [2011 commit to the linux kernel that bumped the default hard limit from `1024` to `4096`](https://github.com/torvalds/linux/commit/0ac1ee0bfec2a4ad118f907ce586d0dfd8db7641), which additionally explains reasoning for keeping a default soft limit of `1024` for legacy reasons (_that [source has since moved](https://github.com/torvalds/linux/blob/e2b542100719a93f8cdf6d90185410d38a57a4c1/include/uapi/linux/fs.h#L37-L38), but remains the same values today_).

With this information, all that's left is to explain why the defaults differ in containers between the Manjaro host and the Fedora 36 VM guest. Neither has configured the Docker daemon explicitly, but rather the systemd services have configured limit overrides:

```console
$ rg 'LimitNOFILE' /usr/lib/systemd/system

# Fedora 36
/usr/lib/systemd/system/containerd.service
33:LimitNOFILE=infinity

/usr/lib/systemd/system/docker.service
31:LimitNOFILE=infinity


# Manjaro
/usr/lib/systemd/system/containerd.service
33:LimitNOFILE=infinity

/usr/lib/systemd/system/docker.service
15:LimitNOFILE=1048576
```

Both share the same systemd service-wide defaults (_1024 soft, 512K hard_):

```console
$rg 'DefaultLimitNOFILE' /etc/systemd

/etc/systemd/user.conf
40:#DefaultLimitNOFILE=

/etc/systemd/system.conf
66:#DefaultLimitNOFILE=1024:524288
```

<details>
<summary>Full list of varying values for different services for any other readers it may interest to reference</summary>

**Fedora 36:**

```console
$ rg 'LimitNOFILE' /usr/lib/systemd/system

/usr/lib/systemd/system/systemd-homed.service
26:LimitNOFILE=524288

/usr/lib/systemd/system/systemd-userdbd.service
22:LimitNOFILE=524288

/usr/lib/systemd/system/systemd-logind.service
65:LimitNOFILE=524288

/usr/lib/systemd/system/systemd-journald@.service
43:LimitNOFILE=524288

/usr/lib/systemd/system/systemd-journald.service
51:LimitNOFILE=524288

/usr/lib/systemd/system/docker.service
31:LimitNOFILE=infinity

/usr/lib/systemd/system/dbus-broker.service
14:LimitNOFILE=16384

/usr/lib/systemd/system/containerd.service
33:LimitNOFILE=infinity

/usr/lib/systemd/system/mariadb.service
13:# you need to increase systemd's LimitNOFILE setting, use the contents below:
16:#    LimitNOFILE=10000

/usr/lib/systemd/system/mariadb@.service
36:# you need to increase systemd's LimitNOFILE setting, use the contents below:
39:#    LimitNOFILE=10000

/usr/lib/systemd/system/rsyslog.service
18:LimitNOFILE=16384

/usr/lib/systemd/system/NetworkManager.service
26:LimitNOFILE=65536

/usr/lib/systemd/system/plocate-updatedb.service
8:LimitNOFILE=131072
```

**Manjaro:**

```console
$ rg 'LimitNOFILE' /usr/lib/systemd/system

/usr/lib/systemd/system/docker.service
15:LimitNOFILE=1048576

/usr/lib/systemd/system/virtqemud.service
33:LimitNOFILE=8192

/usr/lib/systemd/system/dbus-broker.service
14:LimitNOFILE=16384

/usr/lib/systemd/system/virtchd.service
31:LimitNOFILE=8192

/usr/lib/systemd/system/virtlxcd.service
31:LimitNOFILE=8192

/usr/lib/systemd/system/NetworkManager.service
26:LimitNOFILE=65536

/usr/lib/systemd/system/libvirtd.service
41:LimitNOFILE=8192

/usr/lib/systemd/system/containerd.service
33:LimitNOFILE=infinity

/usr/lib/systemd/system/virtlogd.service
23:LimitNOFILE=16384

/usr/lib/systemd/system/virtlockd.service
21:LimitNOFILE=40960

/usr/lib/systemd/system/smb.service
10:LimitNOFILE=16384

/usr/lib/systemd/system/samba.service
10:LimitNOFILE=16384

/usr/lib/systemd/system/systemd-userdbd.service
22:LimitNOFILE=524288

/usr/lib/systemd/system/systemd-logind.service
65:LimitNOFILE=524288

/usr/lib/systemd/system/systemd-journal-upload.service
40:LimitNOFILE=524288

/usr/lib/systemd/system/systemd-journal-gatewayd.service
38:LimitNOFILE=524288

/usr/lib/systemd/system/systemd-journald@.service
43:LimitNOFILE=524288

/usr/lib/systemd/system/systemd-journald.service
51:LimitNOFILE=524288

/usr/lib/systemd/system/systemd-homed.service
25:LimitNOFILE=524288

/usr/lib/systemd/system/ctdb.service
10:LimitNOFILE=1048576

/usr/lib/systemd/system/systemd-journal-remote.service
43:LimitNOFILE=524288
```

</details>

---

It may be better to be more specific then to avoid having a container set `1024` as it's hard limit for it's processes? (_especially with that being 4096 by default in the kernel since 2011_)

Inheriting the Docker hosts limits could be done like so:

`docker run --rm -it --ulimit "nofile=$(ulimit -Sn):$(ulimit -Hn)" alpine ash -c 'ulimit -Sn && ulimit -Hn'`

I think this is probably useful to add to the tests that need it, not sure if it should be mentioned in the `docker-compose.yml` example we provide, but perhaps in our docs somewhere.

**Comment by casperklein** [comment]
Just a quick info, that I cannot reproduce the problem.

`Windows 10 --> VMware Workstation 16.2.4 --> Debian 11 VM`

<details>
<summary>Details</summary>

```
debian11:/# getconf -a | grep ^OPEN_MAX
OPEN_MAX                           1024

debian11:/# docker run --rm -it alpine ash
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
213ec9aee27d: Pull complete
Digest: sha256:bc41182d7ef5ffc53a40b044e725193bc10142a1243f395ee852a8d9730fc2ad
Status: Downloaded newer image for alpine:latest

/ # getconf -a | grep ^OPEN_MAX
OPEN_MAX = 1048576

/ # apk add fail2ban
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
(1/20) Installing libbz2 (1.0.8-r1)
(2/20) Installing expat (2.4.8-r0)
(3/20) Installing libffi (3.4.2-r1)
(4/20) Installing gdbm (1.23-r0)
(5/20) Installing xz-libs (5.2.5-r1)
(6/20) Installing libgcc (11.2.1_git20220219-r2)
(7/20) Installing libstdc++ (11.2.1_git20220219-r2)
(8/20) Installing mpdecimal (2.5.1-r1)
(9/20) Installing ncurses-terminfo-base (6.3_p20220521-r0)
(10/20) Installing ncurses-libs (6.3_p20220521-r0)
(11/20) Installing readline (8.1.2-r0)
(12/20) Installing sqlite-libs (3.38.5-r0)
(13/20) Installing python3 (3.10.5-r0)
(14/20) Installing libmnl (1.0.5-r0)
(15/20) Installing libnftnl (1.2.3-r0)
(16/20) Installing iptables (1.8.8-r1)
(17/20) Installing ip6tables (1.8.8-r1)
(18/20) Installing popt (1.18-r0)
(19/20) Installing logrotate (3.19.0-r2)
(20/20) Installing fail2ban (0.11.2-r2)
Executing busybox-1.35.0-r17.trigger
OK: 62 MiB in 34 packages

/ # rm /etc/fail2ban/jail.d/alpine-ssh.conf

/ # time fail2ban-client start
Server ready
real    0m 0.26s
user    0m 0.06s
sys     0m 0.00s
```
</details>

**Comment by georglauterbach** [comment]
Very interesting! Can someone explain why the values in the containers are so enormous? Seems kind of odd to me...

**Comment by polarathene** [comment]
>  Can someone explain why the values in the containers are so enormous?

I explained that in [my last comment](https://github.com/docker-mailserver/docker-mailserver/issues/2722#issuecomment-1216387291):

```
/usr/lib/systemd/system/containerd.service
33:LimitNOFILE=infinity

/usr/lib/systemd/system/docker.service
31:LimitNOFILE=infinity
```

systemd services on Fedora is configured to use the maximum possible. Manjaro differs by setting `dockerd.service` to 1 million (_while host default with systemd is half that for the hard limit and only 1024 for soft limit_).

>  Seems kind of odd to me..

1024 is legacy to avoid breakage of some old software, but an app can request to raise the soft limit so long as it doesn't exceed the hard limit AFAIK. Some real-world software apparently use 300k, Kafka advises 64-128k apparently.

**Comment by casperklein** [comment]
As soon as I add the `--ulimit` switch I get this:

```
debian11:/# docker run --rm -it --ulimit 'nofile=1073741816' alpine ash
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting rlimits for ready process: error setting rlimit type 7: operation not permitted: unknown.

debian11:/# docker -v
Docker version 20.10.17, build 100c701
```

**Comment by polarathene** [comment]
> As soon as I add the `--ulimit` switch I get this

Try check what is set here:

```bash
grep LimitNOFILE /usr/lib/systemd/system/containerd.service
grep LimitNOFILE /usr/lib/systemd/system/docker.service
```

I was not able to reproduce that failure on either Manjaro or Fedora 36. Both are running the exact same Docker version you have.

I assume you cannot use `--ulimit` option at all, not just the high value? In my systems Docker is being run as my logged in user that is a member of the `docker` group (to avoid requiring sudo). Perhaps something is restricting permissions for setting that ulimit on your end :thinking: 

At the very least, I expect that `docker.service` has `LimitNOFILE=1048576`.

**Comment by polarathene** [comment]
Tracked down the issue in `fail2ban` python code. It's from 2006 where things have changed since (_much larger limits than the assumed 256 fallback_).

---

I'll open a PR that adds the workaround fix to our tests as I don't know how long it'd take until we can get both upstream dependencies resolved and available.

**Comment by casperklein** [comment]
```bash
debian11:/# grep LimitNOFILE /usr/lib/systemd/system/containerd.service
LimitNOFILE=infinity
debian11:/# grep LimitNOFILE /usr/lib/systemd/system/docker.service
LimitNOFILE=infinity
```

> I assume you cannot use --ulimit option at all, not just the high value?

I found out, it's just the high value. When the value is below 1048577, it works 😮 

<details>
<summary>Details</summary>

```bash
debian11:/# docker run --rm -it --ulimit 'nofile=1048576' alpine ash -c 'apk add fail2ban && rm /etc/fail2ban/jail.d/alpine-ssh.conf && time fail2ban-client start && ulimit -n'
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
(1/20) Installing libbz2 (1.0.8-r1)
(2/20) Installing expat (2.4.8-r0)
(3/20) Installing libffi (3.4.2-r1)
(4/20) Installing gdbm (1.23-r0)
(5/20) Installing xz-libs (5.2.5-r1)
(6/20) Installing libgcc (11.2.1_git20220219-r2)
(7/20) Installing libstdc++ (11.2.1_git20220219-r2)
(8/20) Installing mpdecimal (2.5.1-r1)
(9/20) Installing ncurses-terminfo-base (6.3_p20220521-r0)
(10/20) Installing ncurses-libs (6.3_p20220521-r0)
(11/20) Installing readline (8.1.2-r0)
(12/20) Installing sqlite-libs (3.38.5-r0)
(13/20) Installing python3 (3.10.5-r0)
(14/20) Installing libmnl (1.0.5-r0)
(15/20) Installing libnftnl (1.2.3-r0)
(16/20) Installing iptables (1.8.8-r1)
(17/20) Installing ip6tables (1.8.8-r1)
(18/20) Installing popt (1.18-r0)
(19/20) Installing logrotate (3.19.0-r2)
(20/20) Installing fail2ban (0.11.2-r2)
Executing busybox-1.35.0-r17.trigger
OK: 62 MiB in 34 packages
Server ready
real    0m 0.27s
user    0m 0.07s
sys     0m 0.01s
1048576
```
</details>

> Perhaps something is restricting permissions for setting that ulimit on your end 🤔

I've run it as root in my test VM.

**Comment by polarathene** [comment]
The performance difference could possibly be Debian is triggering faster paths for closing FDs than my tested systems. I [investigated and detailed `os.closerange()` and related logic](https://github.com/fail2ban/fail2ban/issues/3334#issuecomment-1219098856) to what syscalls were used and found that whatever was chosen for my systems, the performance wasn't changing across various Python releases :confused: 

I could probably look into testing the syscall availability directly with some rust code, and spin up a Debian VM to see if I can reproduce the experience you and the `fail2ban` maintainer had with Debian - but I've sunk enough time into this topic already and don't see much value in continuing.

**Comment by polarathene** [comment]
For reference, Github Actions with Ubuntu 20.04 runner OS has both soft (`-Sn`) and hard (`-Hn`) set to:

- Host: `65536`
- Docker containers (root): `1048576`
