### ISSUE TITLE
Bringing my own wildcard ssl certificate doesn't work

### ISSUE THREAD

**Issue by SchmiddyFolkwang** [docker-mailserver/docker-mailserver#2726]
# Bringing my own wildcard ssl certificate doesn't work

I have questions about TLS/SSL/STARTTLS/OpenSSL

So I'm currently building a website using docker-compose and I want to include a Mailserver in the stack.
It all works pretty nicely so far, I got the server running, set up a basic email and configured DKIM (at least as far as I can tell)

So now I need to set up TLS/SSL so that the mail clients can send mails securely. My DNS is being hosted via Ionos.de and they supply a wildcard ssl certificate with a .cer and .key file which already works great for my webapp.

I followed the documentation https://docker-mailserver.github.io/docker-mailserver/edge/config/security/ssl/#bring-your-own-certificates, connected a volume with the two files

`./docker-data/dms/custom-certs/:/tmp/dms/custom-certs/:ro`

set SSL_TYPE to manual and the environment variable to

```
- SSL_CERT_PATH=/tmp/dms/custom-certs/periton.media_ssl_certificate.cer
- SSL_KEY_PATH=/tmp/dms/custom-certs/periton.media_private_key.key
```

The hostname is "mail" just like one of the A records in DNS, MX points to that Record
The domainname is... well... my domain.

I start the mailserver with `docker compose up -d` which doesn't throw any errors or something. I enter the bash shell and check the SSL certificate with the commands from the documentation

`openssl s_client -connect 0.0.0.0:25 -starttls smtp -CApath /etc/ssl/certs/`

and it returns "Verify return code: 21 (unable to verify the first certificate)"

It states in the documentation that wildcard certificates are being supported when SSL_TYPE=letsencrypt.
So maybe I could use my existing certificates with the letsencrypt type. If so, I don't know how.

I don't want to create a new certificate with letsencrypt, the one I have should work just fine since it's already connected to the webapp. I just don't know how to get it running on the Docker Mailserver.

Hope you can help! Big thanks in advance!

**Comment by SchmiddyFolkwang** [comment]
I am kind of able to connect. The gmail phone app sends a warning that the certificate couldn't be verified but after fiddling around with the dialogs it lets me proceed. I tried sending a mail to my personal gmail which but got only an empty "returned to sender" mail back. I also tried sending a mail from my personal mail to the new one but that was never received. It showed this in the logs:

`Recipient address rejected: Delayed by Postgrey;`

If I understand you correctly I need to create a counterpart in /etc/ssl/certs/? Is it just copying the existing certs into that folder aswell?

**Comment by casperklein** [comment]
> If I understand you correctly I need to create a counterpart in /etc/ssl/certs/? 

This is only for manual verification/testing. As you also got a cert warning in your mail client, it's not openssl specific you used for testing.

I am wondering, why the exact same certificates works for you with HTTPS. If something with the certificate (chain) is wrong, you would also get an error in a browser.

**Comment by SchmiddyFolkwang** [comment]
I found this article on stackoverflow
https://stackoverflow.com/questions/7587851/openssl-unable-to-verify-the-first-certificate-for-experian-url

OpenSSL other than Firefox apparently doesn't fetch the full certificate or something. I'm still completely lost here (first time doing this) but I guess it's part of how my server setup works. That would also be the reason why the Email clients can't fetch the data. I'll continue to look into this, but I hope someone here can find a working solution

**Comment by casperklein** [comment]
For testing, you can obtain a free letsencrypt certificate and see if you got this working.

**Comment by polarathene** [comment]
> `openssl s_client -connect 0.0.0.0:25 -starttls smtp -CApath /etc/ssl/certs/`

Are you running this outside or inside the container?

Ensure that your root CA cert is available to verify, our tests need to do this to verify custom certs as well:

https://github.com/docker-mailserver/docker-mailserver/blob/0d5f550bdf22ab21bb7a852861221ae0b82264e1/test/mail_ssl_manual.bats#L86-L101

We also have wildcard support tested in [`letsencrypt` test](https://github.com/docker-mailserver/docker-mailserver/blob/master/test/mail_ssl_letsencrypt.bats), but the test itself is not useful for you to look at IIRC and AFAIK the support shouldn't be specific to `letsencrypt` mode, providing your own should work fine (_the `letsencrypt` test doesn't actually use LetsEncrypt certs, but custom generated ones_).

We have maintainer [documentation on our TLS certs and generation process for the tests](https://github.com/docker-mailserver/docker-mailserver/tree/master/test/test-files/ssl/example.test). You can use one of the [wildcard cert + key](https://github.com/docker-mailserver/docker-mailserver/tree/master/test/test-files/ssl/example.test/with_ca/ecdsa/wildcard) sets if you like, but you need to pair that with `/etc/hosts` or custom DNS for `example.test` that the certs are generated for, and add them to the trust store of your OS or any clients that require that.

Your actual wildcard certs should not require your OS or client software to add trust as the root CA certs should already be available on your system (_and I would think that should be the case for the container_). If there are intermediate certs involved, you should bundle these into your DMS cert files. Chain of trust can then be verified with everything available to the client.

**Comment by SchmiddyFolkwang** [comment]
I tested it with a letsencrypt certificate now and it has the exact same error.

The openssl command is run withing the container after entering it with
`docker exec -it mailserver bash`

And I don't think there are intermediate certs involved. I can however acquire one, but I don't know if Docker Mailserver has an option for including those.

**Comment by SchmiddyFolkwang** [comment]
Alright I got it working but I'm kinda disappointed

So I did try it again by generating a letsencrypt certificate for domain.com, www.domain.com and mail.domain.com and used that one for both the Mailserver and the Webserver.
And then it worked no problem. I don't know if it was because the certificate was on both servers or if it was because now the certificate was also generated for the domain.com and www.domain.com names.

It works now, but I can't send mails to gmail, etc. because of the trust thingy. I'm currently working on getting a relay working.

However the original issue isn't really fixed. I still wasn't able to bring my own certificate. So I'm hoping that someone can figure out what's wrong there. I will continue to use the letsencrypt one for now. But I hope that there can be an answer to why this doesn't work for the people after me that might run into the same issues.


Thank you all so much again!

**Comment by polarathene** [comment]
> However the original issue isn't really fixed. I still wasn't able to bring my own certificate. So I'm hoping that someone can figure out what's wrong there.

Follow the advice I direct you to.

You can use the certificates that we have for `example.test` and get that working or generate your own ones for local testing (they won't work with gmail). Our tests verify those successfully, so if you're not able to get that far it's likely an issue with train of trust being misconfigured.

> It works now, but I can't send mails to gmail, etc. because of the trust thingy. I'm currently working on getting a relay working.

I can also provide you an example of setting up multiple DMS containers locally for relay or send/receive testing. It may help troubleshoot your issue in a controlled environment.
