### ISSUE TITLE
[BUG] sha512sum hangs when no files included, target/scripts/helpers/change-detection.sh

### ISSUE THREAD

**Issue by winllc** [docker-mailserver/docker-mailserver#2743]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

target/scripts/helpers/change-detection.sh

### What happened and when does this occur?

```Markdown
The last log message I saw "Creating /tmp/docker-mailserver-config-chksum" in the container output. I added more debugging to target/scripts/helpers/change-detection.sh and found it wouldn't get past sha512sum -- "${CHANGED_FILES[@]}". This caused the setup to stall indefinitely. The install wall complete if this line was commented out. I switched to version 11.0.0 and did not have this issue.
```

### What did you expect to happen?

```Markdown
For the container to start without issue.
```

### How do we replicate the issue?

```Markdown
RHEL 8.6
Podman 4.1.1
```

### DMS version

v11.1.0

### What operating system is DMS running on?

Linux

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### What container orchestration tool are you using?

Podman (not officially supported)

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [X] I am inexperienced with mail servers
- [ ] I am uncomfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by winllc** [comment]
Okay that fix works, thanks!

**Comment by polarathene** [comment]
@winllc even though you're happy with the workaround, could you please provide a bit more information?

- Did you have no config volume mounted to `/tmp/docker-mailserver`? (or no files in this volume?)
- Did you not use `SSL_TYPE` of `manual` or `letsencrypt`?

How are you handling your certificates? Disabling this service may cause you problems later when certs are renewed.

**Comment by casperklein** [comment]
https://github.com/docker-mailserver/docker-mailserver/pull/2776 have fixed this.
