### ISSUE TITLE
Fetchmail documentation

### ISSUE THREAD

**Issue by Bluejanis** [docker-mailserver/docker-mailserver#2773]
Fetchmail documentation

Other

## The documentation is confusing. 
[Link to documentaion](https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/mail-fetchmail/#polling-interval)
It does not explain the examples very well. I am wondering what the option `is` means and how to configure it.
I even checked the [fetchmail manual](https://www.fetchmail.info/fetchmail-man.html#id34), but it doesnt mention an option -is, and looking for the word it comes up 466 times in that document. 

Another thing I noticed in those examples, is that the configuration is stored in a special subfolder (/dms/). Is there any reason why fetchmail wants a different folder?

**Comment by Bluejanis** [comment]
Sorry for those tags! I don't know how I created those, but I cannot change them anymore.

**Comment by casperklein** [comment]
> Sorry for those tags! I don't know how I created those, but I cannot change them anymore.

No worry. Those tags are added automatically.
