### ISSUE TITLE
[BUG] Dockerfile is not longer compatible with 

### ISSUE THREAD

**Issue by ap-wtioit** [docker-mailserver/docker-mailserver#2791]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

not buildable

### What happened and when does this occur?

```Markdown
Error response from daemon: Dockerfile parse error line 43: Unknown flag: link
```

### What did you expect to happen?

I expected to be able to build this image on Ubuntu 18.04 LTS with docker:
```
Client: Docker Engine - Community
 Version:           20.10.18
 API version:       1.40
 Go version:        go1.18.6
 Git commit:        b40c2f6
 Built:             Thu Sep  8 23:11:34 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.14
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       5eb3275d40
  Built:            Tue Dec  1 19:18:45 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

### How do we replicate the issue?

```Markdown
1. Use Ubuntu 18.04
2. Use Docker
3. try to build image
4. Get the following error:

Error response from daemon: Dockerfile parse error line 43: Unknown flag: link

```

### DMS version

dockerfile from master

### What operating system is DMS running on?

Linux

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### What container orchestration tool are you using?

Docker

### docker-compose.yml

```yml
--
```

### Relevant log output

```bash
Error response from daemon: Dockerfile parse error line 43: Unknown flag: link
```

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [ ] I am inexperienced with mail servers
- [ ] I am uncomfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by casperklein** [comment]
You can use this workaround:

`sed -i 's/^COPY --link/COPY/' Dockerfile`

**Comment by georglauterbach** [comment]
We introduced the `--link` flag for the ClamAV Anti Virus bytecode signatures to have better caching. This is a breaking changes when it comes to building the image. Ubuntu 18.04 may not ship the latest Docker version that supports it. Did you run `make build` or did you try to build manually?

**Comment by ap-wtioit** [comment]
@georglauterbach that's why i added the docker information, we use the docker setup as documented by docker using their package repositories https://docs.docker.com/engine/install/ubuntu/

i use our own gitlab ci and build with:
```bash
git submodule update --init --recursive
docker build -t $CI_REGISTRY_IMAGE:ci-$CI_PIPELINE_ID --pull . 
```
which worked until the `--link` change

@casperklein thanks for the workarround, still i expected a mention in the documentation that a certain (recent) docker version is required for building this image if there is a breaking change.

**Comment by georglauterbach** [comment]
We will add this information to the docs :)

**Comment by ap-wtioit** [comment]
FYI: When i tested the workaround i discovered that the docker version in Ubuntu 20.04 LTS and Ubuntu 22.04 LTS are also not enough and give the same error.

**Comment by casperklein** [comment]
I recommend, not to use the default repo of your distribution for Docker installation. If you use the repo directly from Docker, you'll get a much more recent docker version. In case of ubuntu, see [here](https://docs.docker.com/engine/install/ubuntu/).

**Comment by ap-wtioit** [comment]
@casperklein:
> ... that's why i added the docker information, we use the docker setup as documented by docker using their package repositories https://docs.docker.com/engine/install/ubuntu/

**Comment by georglauterbach** [comment]
That should actually not be happening with your version. On my machine, it works fine and we seems to have the same versions:

``` CONSOLE
georg@../docker-mailserver $ docker version
Client: Docker Engine - Community
 Version:           20.10.18
 API version:       1.41
 Go version:        go1.18.6
 Git commit:        b40c2f6
 Built:             Thu Sep  8 23:11:43 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.18
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.6
  Git commit:       e42327a
  Built:            Thu Sep  8 23:09:30 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

georg@../docker-mailserver $ make build
[+] Building 1.4s (58/58) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                          0.0s
 => => transferring dockerfile: 38B                                                                                                                                                                           0.0s
...
 => exporting to image                                                                                                                                                                                        0.1s
 => => exporting layers                                                                                                                                                                                       0.0s
 => => writing image sha256:060747bed7b578af434f6cdfcda0949bf3a147b43e7c3a275b3349f9fa7474b6                                                                                                                  0.0s
 => => naming to docker.io/library/mailserver-testing:ci
```

**Comment by ap-wtioit** [comment]
`COPY --link` is requiring buildkit and does not work without it. This works:
```bash
DOCKER_BUILDKIT=1 docker build --pull .
```
while without buildkit it doesn't
```bash
docker build --pull .
```

Your build output looking different did point me in the right direction.

The  [blog post](https://www.docker.com/blog/image-rebase-and-improved-remote-cache-support-in-new-buildkit/ ) for `COPY --link` does mention that you need buildkit "In order to get the correct cache semantics for the flag, BuildKit v0.10 needs to be used as well." but the [documentation](https://docs.docker.com/engine/reference/builder/#copy---link) i looked it up unfortunately doesn't.
