### ISSUE TITLE
[BUG] Clamav is failing

### ISSUE THREAD

**Issue by chongma** [docker-mailserver/docker-mailserver#2794]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

ClamAV

### What happened and when does this occur?

```Markdown
Clam antivirus appears as using lots of CPU and Mem when using `top` command.  Eventually I am forced to go back to `ENABLE_CLAMAV=0`.  But the logs show mailserver could not connect to clamscan so I am not sure how it is even started
```

### What did you expect to happen?

```Markdown
Clamscan to start and use a normal amount of cpu and memory
```

### How do we replicate the issue?

```Markdown
1.
2.
3.
...
```

### DMS version

v11.1.0

### What operating system is DMS running on?

Linux

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### What container orchestration tool are you using?

Docker Compose

### docker-compose.yml

```yml
version: '3.8'

services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    container_name: ${CONTAINER_NAME}
    env_file: mailserver.env
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
      - "4190:4190"
    volumes:
      - /home2/mail/maildata:/var/mail
      - /home2/mail/mailstate:/var/mail-state
      - /home2/mail/maillogs:/var/log/mail
      - /etc/localtime:/etc/localtime:ro
      - ./config/:/tmp/docker-mailserver/${SELINUX_LABEL}
      #- ./config/dovecot/fts-xapian-plugin.conf:/etc/dovecot/conf.d/10-plugin.conf:ro
      - ./cron/sa-learn:/etc/cron.d/sa-learn
      #- ./docker-data/dms/cron/fts_xapian:/etc/cron.d/fts_xapian
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: always
    stop_grace_period: 1m
    cap_add: [ "NET_ADMIN", "SYS_PTRACE" ]
```

### Relevant log output

```bash
Sep 24 15:48:05 localhost amavis[4995]: Using primary internal av scanner code for ClamAV-clamd
Sep 24 15:48:05 localhost amavis[4995]: Found secondary av scanner ClamAV-clamscan at /usr/bin/clamscan
Sep 24 15:48:09 localhost amavis[5593]: (05593-01) (!)connect to /var/run/clamav/clamd.ctl failed, attempt #1: Can't connect to a UNIX socket /var/run/clamav/clamd.ctl: No such file or directory
Sep 24 15:48:10 localhost amavis[5593]: (05593-01) (!)connect to /var/run/clamav/clamd.ctl failed, attempt #1: Can't connect to a UNIX socket /var/run/clamav/clamd.ctl: No such file or directory
Sep 24 15:48:10 localhost amavis[5593]: (05593-01) (!)ClamAV-clamd: All attempts (1) failed connecting to /var/run/clamav/clamd.ctl, retrying (2)
Sep 24 15:48:16 localhost amavis[5593]: (05593-01) (!)connect to /var/run/clamav/clamd.ctl failed, attempt #1: Can't connect to a UNIX socket /var/run/clamav/clamd.ctl: No such file or directory
Sep 24 15:48:16 localhost amavis[5593]: (05593-01) (!)ClamAV-clamd av-scanner FAILED: run_av error: Too many retries to talk to /var/run/clamav/clamd.ctl (All attempts (1) failed connecting to /var/run/clamav/clamd.ctl) at (eval 95) line 659.\n
Sep 24 15:48:16 localhost amavis[5593]: (05593-01) (!)WARN: all primary virus scanners failed, considering backups
```

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [ ] I am inexperienced with mail servers
- [ ] I am uncomfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by georglauterbach** [comment]
How much memory is available on your system? What do you mean by "normal amount of cpu and memory"? Clam needs at least 2GB of main memory.

**Comment by chongma** [comment]
I forgot to say it's been running on the server for years. It's only the recent upgrade where I've started having trouble. The box has 4gb ram I think

**Comment by georglauterbach** [comment]
How did you upgrade exactly? Please check how much memory is available on your machine exactly and how much is used - could be the OOM killer is doing its thing..

**Comment by chongma** [comment]
I add this user-patches.sh https://github.com/docker-mailserver/docker-mailserver/issues/2685#issuecomment-1221342570 and it seems to be working ok for the time being.
