### ISSUE TITLE
[BUG] cron jobs work when ENABLE_AMAVIS=0

### ISSUE THREAD

**Issue by ctapmex** [docker-mailserver/docker-mailserver#2823]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

error in server logs

### What happened and when does this occur?

```Markdown
We have two problems.
1. Server deployed with ENABLE_AMAVIS=0. But /etc/cron.d/amavisd-new not disabled. Unnecessary work of processes every 3 hours
2. By default, no alias is created for the internal mail of the docker image.
For example: cron execute /etc/cron.d/amavisd-new . A line gets into stdout, which cron is obliged to send to the user as a result of work.

From: root@mail.example.com (Cron Daemon)
To: amavis@mail.example.com
Subject: Cron <amavis@imap>  test -e /usr/sbin/amavisd-new-cronjob && /usr/sbin/amavisd-new-cronjob sa-sync

Mail server received this mail. Since there is no alias for amavis@mail.example.com, the mail will be stored in /var/mail/amavis. it`s 'ok', but we do not see mail, and potentially problems.
```

### What did you expect to happen?

```Markdown
1. /etc/cron.d/amavisd-new don`t work
2. description in the documentation about mandatory creation of an alias for internal users
For example `./setup.sh alias add @mail.example.com postmaster@example.com`
```

### How do we replicate the issue?

```Markdown
1. deploy container with ENABLE_AMAVIS=0
2. wait some time
3. check file /var/mail/amavis
```

### DMS version

v11.1.0

### What operating system is DMS running on?

Linux

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### What container orchestration tool are you using?

Docker Compose

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [ ] I am inexperienced with mail servers
- [ ] I am uncomfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by casperklein** [comment]
Thanks for reporting this issues.

>1. /etc/cron.d/amavisd-new don`t work
>2. description in the documentation about mandatory creation of an alias for internal users

1. I will take care that the cronjob is disabled when Amavis is not used.
2. You are right, adding an alias will fix this issue. It would be nice, if you could provide a PR to update our documentation 👍

**Comment by georglauterbach** [comment]
Thanks for the report! If you do not find time for the PR as @casperklein, please let us know. I would then try to find a bit of time to fix the alias issue and I would then just like you to review the PR.

**Comment by ctapmex** [comment]
Sorry, I can't help you with PR anytime soon. still plunging into the configuration and structure of the solution on first installation
