### ISSUE TITLE
HA Proxy with IPv6

### ISSUE THREAD

**Issue by cloud-erik** [docker-mailserver/docker-mailserver#2826]
# Subject

Other

## Description

I use HA-Proxy in front of docker-mailserver which works fine so far. But as I am more and more implementing IPv6 in my network I also activted a IPv6 DNS MX record of my HA-Proxy to be able to receice maisl via IPv6.
But herer I get following log warning and connection fails.
``` BASH
# mail postfix/postscreen: warning: haproxy read: unsupported protocol type: PROXY TCP6 IP_other_Server IP_my_HA_Proxy 25

```
I was wondering if someone else is using HA-Proxy in an IPv6 environment and has simliar issues or any tips how to solve.

Erik

**Comment by cloud-erik** [comment]
OMG its solved, sometimes it really helps to write it down to get to the point :-)
Just had to add
```
inet_protocols = ipv4, ipv6
```

in postfix-main.cf.

**Comment by casperklein** [comment]
fyi: There is an ENV for that: https://github.com/docker-mailserver/docker-mailserver/blob/70ad765a30cd5ce8385994f592f51e05b1e0a744/mailserver.env#L269-L275

**Comment by cloud-erik** [comment]
Yes fount it as well. but be aware that
```
POSTFIX_INET_PROTOCOLS=ipv4, ipv6
```
works fine but 
```
DOVECOT_INET_PROTOCOLS=ipv4, ipv6
```
yields an error. but "all" is working for postfix and dovecoat.

**Comment by casperklein** [comment]
``POSTFIX_INET_PROTOCOLS=ipv4, ipv6`` is not valid. You can either use `all, ipv4 or ipv6`.

**Comment by cloud-erik** [comment]
I have to disaggree.
As I wrote I tested it and its working. I expect that the POSTFIX_INET_PROTOCOLS parameter is just forwarded to INET_PROTOCOLS parameter of postfix and theree its valid and also working. see:
http://www.postfix.org/postconf.5.html#inet_protocols

**Comment by casperklein** [comment]
I didn't say it doesn't work. But as per our documentation, we expect one of those three mentioned values. So if you need both, use "all". Anything else might break in the future.
