### ISSUE TITLE
dovecot.cf setting mail_max_userip_connections not taking into account IPv6

### ISSUE THREAD

**Issue by cloud-erik** [docker-mailserver/docker-mailserver#2827]
# Subject

I would like some feedback concerning a use case

## Description

Issue is that I am running in 

``` BASH
# CODE GOES HERE
mail dovecot: imap-login: Maximum number of connections from user+IP exceeded (mail_max_userip_connections=10)
```
If I set e.g. 
```
mail_max_userip_connections = 100
```
in docker-data/dms/config/dovecot.cf

I could seee that this is also copied to dovecot-local.conf/dovecot.cf but it seams to have no effect, espacially for IPv6 connection.
Other setting in dovecot.cf are taken into account.

Is there probably an additional place where the config is overwritten?

Also strange is, that I am only running in that issue when I access server via IPv6, not sure if maybe connections are not closed correct and keept open longer as in IPv4?

I would appreachiate any help how to check or change settings.

Erik

**Comment by casperklein** [comment]
[There is probably a NAT in place for all IPv6 connections - which is bad](https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/ipv6/). All IPv6 connections appear to come from the same IPv4 address from DMS point of view. This can lead to multiple problems, like SPF failures, Fail2ban problems or the connection limits you mention.

**Comment by cloud-erik** [comment]
Dont thik its a NAT issue. I connected the container trough an IPv6 bridge network with a fixed IPv6 address. Also I see in the logs the correct IPv6 addreses of client and server.
My major question is why the logs shows "mail_max_userip_connections=10" when in dovecot.cf 100 connections are definend. I worry that the setting is not taken into account.
Is there an easy way to check which parameters / values are active in dovecoat?

**Comment by casperklein** [comment]
Here is the relevant code that handles the custom settings, pretty flat and simple:

https://github.com/docker-mailserver/docker-mailserver/blob/032ed00a17a1114465bec2b88639ac7222f2a5d0/target/scripts/startup/daemons-stack.sh#L68-L70

> Is there an easy way to check which parameters / values are active in dovecoat?

[`doveconf`](https://wiki.dovecot.org/Tools/Doveconf)
