### ISSUE TITLE
[BUG] Typo at documentation

### ISSUE THREAD

**Issue by KES777** [docker-mailserver/docker-mailserver#2829]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

Typo at documentation

### What happened and when does this occur?

```Markdown
$ docker exec -it mailserver setup config dkim help
OPEN-DKIM(8)

NAME
    open-dkim - configure DomainKeys Identified Mail (DKIM)

SYNOPSIS
    ./setup.sh config dkim [ OPTIONS... ]

DESCRIPTION
    Configures DKIM keys. OPTIONS can be used to configure a more complex setup.
    LDAP setups require these options.

OPTIONS
    Generic Program Information
        help       Print the usage information.

    Configuration adjustments
        keysize    Set the size of the keys to be generated. Possible are 1024, 2024 and 4096 (default).
        selector   Set a manual selector (default is 'mail') for the key. (ATTENTION: NOT IMPLEMENTED YET!)
        domain     Provide the domain(s) for which keys are to be generated.

```
```


### What did you expect to happen?

```Markdown
`keysize    Set the size of the keys to be generated. Possible are 1024, 2048 and 4096 (default).`

Notice, it should be 2048
```

### How do we replicate the issue?

```Markdown
1. `docker exec -it mailserver setup config dkim help`
```

### DMS version

***

### What operating system is DMS running on?

Linux

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### What container orchestration tool are you using?

Docker Compose

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [ ] I am inexperienced with mail servers
- [ ] I am uncomfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by casperklein** [comment]
Thanks for reporting this.
