### ISSUE TITLE
[BUG] Fetchmail forget's id's after recreating DMS container

### ISSUE THREAD

**Issue by bjoernbrings** [docker-mailserver/docker-mailserver#2832]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

Fetchmail

### What happened and when does this occur?

```Markdown
After an update of the docker image and a container restart the fetchmailid's are not kept and all kept email are again retrieved (using the keep option in fetchmail).

Was unfortunately not able to find the .fetchids file and hence couldn't investigate why it is not stored somewhere in /var/mail-state
```

### What did you expect to happen?

```Markdown
Fetchmail knows the emails already retrieved even after image update
```

### How do we replicate the issue?

```Markdown
Create an old version of DMS. Use fetchmail an keep messages on mailserver.
Update DMS to a newer version.
```

### DMS version

11.1

### What operating system is DMS running on?

Linux

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### What container orchestration tool are you using?

Docker

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [X] I am inexperienced with mail servers
- [ ] I am uncomfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by georglauterbach** [comment]
Thank you for the report :) I think active maintainers have not used Fetchmail themselves, so we have a bit of a support-issue here.

Do you have any idea why this could be happening?

**Comment by gutmensch** [comment]
The supervisor [config](https://github.com/docker-mailserver/docker-mailserver/blame/master/target/supervisor/conf.d/supervisor-app.conf#L107) with `-i idfile` looks quite dated? Judging from this it seems it was overlooked from the beginning. I'm using always nokeep and I assume most people do too (no use to keep mails that were transfered already), so I didn't spot this.

**Comment by casperklein** [comment]
I think this happens, when the container is recreated and `/var/lib/fetchmail/.fetchmail-UIDL-cache` is lost.

**Comment by bjoernbrings** [comment]
Thanks @casperklein. Looking in the file it seems to be the .fetchids file that I was looking for. With that hint I could save it manually before an update. Thanks already for that

To solve that issue I guess making sure that the folder is linked into a subfolder of /var/mail-state/ like for clamav, fail2ban and others could solve the issue

**Comment by casperklein** [comment]
> To solve that issue I guess making sure that the folder /var/lib/fetchmail/ is linked into a subfolder of /var/mail-state/ like it is done for clamav, fail2ban and others could solve the issue

I'll provide a fix for that.

**Comment by casperklein** [comment]
@bjoernbrings Can you confirm, the fix works for you? You can build the image from the fixed branch with:

```bash
git clone --recurse-submodules https://github.com/casperklein/archive_docker-mailserver dms
cd dms
git checkout fix-fetchmail-forgets-ids-after-docker-update-2832

# you can choose another image tag, but then don't forget to also update your docker-compose.yml file accordingly
TAG=mailserver/docker-mailserver:latest
DOCKER_BUILDKIT=1 docker build -t $TAG .
```

**Comment by bjoernbrings** [comment]
I did upgrade to `mailserver/docker-mailserver:edge` and the fetchmail setup worked seamlessly.
Thanks @casperklein for the quick fix.
