### ISSUE TITLE
mail logs in stdout

### ISSUE THREAD

**Issue by ctapmex** [docker-mailserver/docker-mailserver#2858]
# Subject

I have question about logging

## Description

Why do mail logs go to stdout?  I run `docker logs mailserver` and see logs from mail.log. 
But rsyslog.conf  does not contain such settings.
As a result, we have double logs:
 - mail.log
 - /var/lib/docker/containers/<container-id>/<container-id>-json.log

sended message to syslog also go to stdout
`logger 'ha-ha' -p mail.1`
but not
`logger 'ha-ha' -p user.1`

**Comment by casperklein** [comment]
The output of our `start-mailserver.sh` script goes to STDOUT (line 12):

https://github.com/docker-mailserver/docker-mailserver/blob/c4df9c116b5aa0c8fd478b4fc11d5d107deede0e/target/supervisor/conf.d/supervisor-app.conf#L7-L16

And in that script we have this at the end:

https://github.com/docker-mailserver/docker-mailserver/blob/c4df9c116b5aa0c8fd478b4fc11d5d107deede0e/target/scripts/start-mailserver.sh#L239

> As a result, we have double logs

[Docker keeps only 100MB logs per default.](https://docs.docker.com/config/containers/logging/local/) This limit can be changed.


>sended message to syslog also go to stdout
>`logger 'ha-ha' -p mail.1`
>but not
>`logger 'ha-ha' -p user.1`

Take a look at `/etc/rsyslog.conf`. The first one goes to `/var/log/mail.log` ==> STDOUT, the second one not.

**Comment by ctapmex** [comment]
ok, thx
