### ISSUE TITLE
[BUG] amavis: (!!)TROUBLE in child_init_hook: BDB can't connect db env. at /var/lib/amavis/db

### ISSUE THREAD

**Issue by plittlefield** [docker-mailserver/docker-mailserver#2871]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

amavis leading to system crash

### What happened and when does this occur?

```Markdown
At a random time (but possibly due to a SMTP flood) the Amavis part will crash and die leading to a system wide CPU hog.
```

### What did you expect to happen?

```Markdown
Not this.
```

### How do we replicate the issue?

```Markdown
I am not sure.
```

### DMS version

v11.2.0  (latest)

### What operating system is DMS running on?

Linux

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### What container orchestration tool are you using?

Docker Compose

### docker-compose.yml

```yml
version: "3.8"
services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    hostname: mail
    domainname: xxxxxx.co.uk
    container_name: mail.xxxxxxx.co.uk-mailserver
    env_file: mailserver.env
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - ./data/maildata/:/var/mail
      - ./data/mailstate/:/var/mail-state
      - ./data/maillogs/:/var/log/mail
      - ./data/config/:/tmp/docker-mailserver/${SELINUX_LABEL}
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/London
      - SSL_TYPE=letsencrypt
    restart: unless-stopped
    cap_add:
      - "NET_ADMIN"
      - "SYS_PTRACE"
```

### Relevant log output

```bash
Oct 28 01:17:51 mail amavis[2705601]: (!!)TROUBLE in child_init_hook: BDB can't connect db env. at /var/lib/amavis/db: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery, No such file or directory. at (eva
l 90) line 338.
Oct 28 01:17:51 mail amavis[2705601]: (!)_DIE: Suicide in child_init_hook: BDB can't connect db env. at /var/lib/amavis/db: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery, No such file or directory. at
 (eval 90) line 338.
Oct 28 01:17:51 mail amavis[2705602]: (!!)TROUBLE in child_init_hook: BDB can't connect db env. at /var/lib/amavis/db: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery, No such file or directory. at (eva
l 90) line 338.
Oct 28 01:17:51 mail amavis[2705602]: (!)_DIE: Suicide in child_init_hook: BDB can't connect db env. at /var/lib/amavis/db: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery, No such file or directory. at
 (eval 90) line 338.
Oct 28 01:17:52 mail amavis[2705607]: (!!)TROUBLE in child_init_hook: BDB can't connect db env. at /var/lib/amavis/db: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery, No such file or directory. at (eva
```

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [ ] I am inexperienced with mail servers
- [ ] I am uncomfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by georglauterbach** [comment]
Are there resource employed on the host? Maybe Amavis runs into limits in the first place and gets killed leading to this situation.
