### ISSUE TITLE
[FR] Add option to discard instead of reject for receive restrictions

### ISSUE THREAD

**Issue by mpldr** [docker-mailserver/docker-mailserver#2872]
# Feature Request

## Context

On some (if not most) send-only addresses I would prefer to discard the mails instead of rejecting them.

### Is your Feature Request related to a Problem?

The amount of people not understanding what "no-reply" means is staggering

### Describe the Solution you'd like

Add a switch to use `DISCARD` instead of `REJECT` in `config/postfix-receive-access.cf` when using `setup.sh`. Otherwise making it the default and making `REJECT` optional is also something I could see being sensible.

### Are you going to implement it?

Probably no, and I understand that it is highly likely no one will implement it. Furthermore, I understand that this issue will likely become stale and will be closed.

If I find the time, I might give it a shot

### What are you going to contribute?

Documentation for all modifications/settings I may find useful.

**Comment by casperklein** [comment]
You can use [user-patches.sh](https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/override-defaults/user-patches/) as workaround:

`sedfile -i 's/REJECT/DISCARD/' /tmp/docker-mailserver/postfix-receive-access.cf`

For reference: https://www.postfix.org/access.5.html
