### ISSUE TITLE
[BUG] './setup.sh email list' does not display aliases correctly

### ISSUE THREAD

**Issue by casperklein** [docker-mailserver/docker-mailserver#2877]
For reference: https://github.com/docker-mailserver/docker-mailserver/discussions/2875

### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

./setup.sh email list

### What happened and when does this occur?

On a fresh setup:
```bash
./setup.sh email add media@example.com
./setup.sh email add socialmedia@example.com

./setup.sh alias add facebook@example.com socialmedia@example.com

./setup.sh email list
* media@example.com
    [ aliases -> facebook@example.com ]

* socialmedia@example.com
    [ aliases -> facebook@example.com ]
```

### What did you expect to happen?

```Markdown
facebook@example.com should only be listed for the socialmedia@example.com mail account.
```

### DMS version

v11.2.0

### What operating system is DMS running on?

Linux

### Which operating system version?

Debian 11

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### What container orchestration tool are you using?

Docker

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by polarathene** [comment]
Technically that's invalid I think? You shouldn't be able to have an account and alias with the same address? So rather the methods should avoid creating an account/alias if either exists already, not just the one of it's kind?

**Comment by casperklein** [comment]
Sorry, I just recognized that I forgot a little part in my example - fixed. I hope that makes it more clear.
