### ISSUE TITLE
[FR] setup.sh list email | alias should return only list of emails/aliases

### ISSUE THREAD

**Issue by fab-kaz** [docker-mailserver/docker-mailserver#2878]
# Feature Request

setup.sh list email | alias should return only list of emails/aliases (without quota or CR/LF or asterisk at the begining of the line)

## Context
 I've read "Since Docker Mailserver v10.2.0, setup.sh functionality is included within the container image. The external convenience script is no longer required. "
Nice! i'd like to stop using my "old" external script setup.sh. But it seems the very new setup.sh returns different output as the "old" setup.sh did. 

### Is your Feature Request related to a Problem?

setup.sh included in the container image doesn't show the same output as the "old" external setup.sh.

OLD:
```
./setup.old.sh email list
guy0@mydomain.fr
guy1@mydomain.fr
guy2@mydomain.fr
```

NEW:
```
./setup.sh email list
* guy0@mydomain.fr ( 3,0K / 1,0G ) [0%]

* guy1@mydomain.fr ( 4,0K / 1,0G ) [0%]

* guy2@mydomain.fr ( 2,0K / 1,0G ) [0%]
```

And this is a problem because lots of others scripts use the output of ```./setup email list```

### Describe the Solution you'd like

```./setup email list``` should return only one simple line per email with no other caracter or information.

To know quotas, we could use the command ```./setup.sh list quota```

To know alias with email, we could use the command ```./setup.sh list email with alias```

I'd like to add: Thank you for all this awsome work  by the way !!!

regards,

fab.

**Comment by georglauterbach** [comment]
A short explanation before we begin: `setup.sh` was not actually moved into the container, but a script called `setup` was added inside the container that can _dispatch_ commands in the container. `setup.sh` is now in place to easily communicate with the container, i.e. when you call `./setup.sh email list`, the script will try to find the DMS container and run `docker exec <CONTAINER NAME> setup email list`. The changes you experience come from changes to a script that `setup` actually calls when given the parameters `email list`. This script is called [`listmailuser`](https://github.com/docker-mailserver/docker-mailserver/blob/master/target/bin/listmailuser).

I understand your problem. But at the same time, we won't be reverting the changes to `listmailuser` as many users like the format, and we changed it on purpose. We could probably add a flag like `--plain`, but we're short on time. If you want to take a shot at it, have a look at [Contributing Section](https://docker-mailserver.github.io/docker-mailserver/edge/contributing/issues-and-pull-requests/#pull-requests). I've linked `listmailuser` as above, we would then, when you opened a PR, guide you and provide a bit of help on the final meters.

In the meantime, you can just pipe the output through `cut -d ' ' -f 2 | awk 'NF` which should provide you witht the old format again.

**Comment by fab-kaz** [comment]
and postfix-virtual.cf for aliases, thank you!
