### ISSUE TITLE
[FR] Not enough details in Weekly logwatch report for amavisd

### ISSUE THREAD

**Issue by winks** [docker-mailserver/docker-mailserver#2893]
I am torn between FR and bug report, but in the weekly report under the Amavisd section I just got this today, but the "Warning: security risk" is not elaborated on, so I have to log in to the server and manually find out what might be, and additionally I don't even know what to look for - in the dovecot section there are at leas the usernames/email addresses to look for.

```
 --------------------- Amavisd-new Begin ------------------------ 

        1   *Warning: Security risk
 
      654   Total messages scanned ------------------  100.00%
   35.453M  Total bytes scanned                     37,174,965
 ========   ==================================================
 
      654   Passed ----------------------------------  100.00%
      187     Spam passed                               28.59%
        4     Bad header passed                          0.61%
      463     Clean passed                              70.80%
 ========   ==================================================
 
      187   Spam ------------------------------------   28.59%
      187     Spam passed                               28.59%
 
      467   Ham -------------------------------------   71.41%
        4     Bad header passed                          0.61%
      463     Clean passed                              70.80%
 ========   ==================================================
 
       66   Extra code modules loaded at runtime
      667   SpamAssassin diagnostics
 
 
 ---------------------- Amavisd-new End -------------------------
```

**Comment by casperklein** [comment]
[Logwatch](https://sourceforge.net/projects/logwatch/) basically parses `mail.log`. I think you can find more information there: `grep 'Security risk' mail.log`.

Debian provides version 7.5.5 of logwatch. There are three newer versions, the latest is 7.6, so this bug may be already fixed. Anyway, there isn't much we can easily do right know. This is a bug in logwatch and IMO not related to DMS.

**Comment by winks** [comment]
Fair, I haven't had time to dig deeper today and saw it more as "logwatch is shipped/enabled? by default in DMS, so maybe it's an easy thing to double check DMS' config here" - but feel free to close.
