### ISSUE TITLE
docs: `setup` command within container has replaced most functionality of external `setup.sh` helper

### ISSUE THREAD

**Issue by MohammedNoureldin** [docker-mailserver/docker-mailserver#2899]
The docs have fallen a bit out of date since much of the `setup.sh` functionality was migrated into the container releases from `v10.1` into a `setup` command.

It would be ideal if the docs were updated to reflect that, instead of implying `setup.sh` is the only way.

---

<details>
<summary>Original message</summary>

After Kubernetes deprecated the usage of Docker, and started using **Containerd** instead (which Docker itself uses behind the scences), here we also should be able to run Mailserver without having Docker installed to run the `setup.sh`, but rather only using Containerd. By this, we stay completely decoupled from Docker runtime, and the `setup.sh` can be used on Kubernetes cluster nodes without any need to install Docker.

This seems to be not a big task to do, just the CRI commands should be adapted to execute in the container using containerd syntax instead of Docker.

The syntax to be used could be `kubectl` syntax, if the `setup.sh` script is going to be executed always on the control-plane node. If it is going to be run on the worker node, then `cricli` can be used.

I am not really very familiar with the details of how or by whom the script is executed, but I checked the usages of the CRI, and it looks that this can be done relatively quickly by anyone who is familiar with the setup.sh script. I am not sure if anybody has time for this, but it is good to keep this issue documented.

</details>

**Comment by polarathene** [comment]
> without having Docker installed to run the `setup.sh`, but rather only using Containerd.

What exactly are you wanting to use `setup.sh` for? Most of the functionality is available from within the container as the `setup` command.

Our docs don't seem to have updated since the change in `v10.x` that migrated lots of the `setup.sh` code into the container via the `setup` command. 

---

So if that covers most of your needs, you'd just run the equivalent of `docker exec -it <container_name> setup <setup_command>` :+1: 

Then hopefully someone finds time to update the docs :sweat_smile: There's rarely a need for `setup.sh` now AFAIK besides a few conveniences it can provide that can't be ported to the `setup` command inside the container.

**Comment by MohammedNoureldin** [comment]
> > without having Docker installed to run the `setup.sh`, but rather only using Containerd.
> 
> What exactly are you wanting to use `setup.sh` for? Most of the functionality is available from within the container as the `setup` command.
> 
> Our docs don't seem to have updated since the change in `v10.x` that migrated lots of the `setup.sh` code into the container via the `setup` command.
> 
> So if that covers most of your needs, you'd just run the equivalent of `docker exec -it <container_name> setup <setup_command>` 👍
> 
> Then hopefully someone finds time to update the docs 😅 There's rarely a need for `setup.sh` now AFAIK besides a few conveniences it can provide that can't be ported to the `setup` command inside the container.

Thank you for your reply.

Actually, I have seen that the setup is also included in the container itself after I posted this issue. I just it is very overemphasized in the documentation that the recommended way is the external `setup.sh`, where I find using the internal script much simpler. When I get the whole things working in Kubernetes with LDAP, I may edit the docs to give the focus again to the internal script, rather than the external.

So considering that the internal `setup` script does not use any Docker API, I think it solves the whole the issue.

**Comment by polarathene** [comment]
> It is very overemphasized in the documentation that the recommended way is the external `setup.sh`, where I find using the internal script much simpler.

It was the only way for some time, the docs just haven't been updated during the transition :sweat_smile: 

If you find the time to contribute an update, that'd be amazing :heart: I'll use this issue to remind us that the docs need to get revised :+1:

**Comment by georglauterbach** [comment]
We had some big updates to our docs, and some pages got revised, including:

1. Usage section: <https://docker-mailserver.github.io/docker-mailserver/latest/usage/> on `latest`
2. "About `setup.sh`": <https://docker-mailserver.github.io/docker-mailserver/edge/config/setup.sh/> on `edge`

While I did not have this issue on my watch, I was noticing it while searching for other issues. I think we can close this, as the docs now recommend the internal `setup` script over `setup.sh`.
