### ISSUE TITLE
[BUG] Dovecot server isn't responding after 1 request

### ISSUE THREAD

**Issue by Lokilife** [docker-mailserver/docker-mailserver#2909]
### Miscellaneous first checks

- [x] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

Dovecot isn't responding after 1 request

### What happened and when does this occur?

```Markdown
I setted up server like two days ago and everything worked smoothly but right now it's just stopped to work without reason.
I checked logs and found error from amavis, i had no time to work on it so i just disabled amavis but that doesn't seem to solve the problem, i checked logs but here is nothing. After start of the server it can send response only to one request but not more, no matter the same mail or different.
```

### What did you expect to happen?

```Markdown
I expected server send response to more than 1 request after it's start
```

### How do we replicate the issue?

```Markdown
Idk so here is only how i setted up server:
1. Clone git repo https://github.com/docker-mailserver/docker-mailserver.
2. Install free SSL-cert from Let's Encrypt via certbot.
3. cd docker-mailserver
4. Paste mine config of docker-compose.yml and .env from "other relevant information"
5. chmod +x ./setup.sh
6. ./setup.sh
7. ./setup.sh config dkim
8. ./setup email add <user>@<domain> [password]
Done
...
```

### DMS version

v11.2.0

### What operating system is DMS running on?

Linux

### Which operating system version?

Ubuntu 20.04

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### What container orchestration tool are you using?

Docker Compose

### docker-compose.yml

```yml
services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    # If the FQDN for your mail-server is only two labels (eg: example.com),
    # you can assign this entirely to `hostname` and remove `domainname`.
    hostname: lokilife.fun
    domainname: lokilife.fun
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```

### Relevant log output

```bash
[ When i meet Amavis error ]
Nov 25 01:42:55 lokilife postfix/master[1244]: daemon started -- version 3.5.13, configuration /etc/postfix
Nov 25 01:44:21 lokilife dovecot: master: Dovecot v2.3.13 (89f716dc2) starting up for imap, lmtp, pop3
Nov 25 01:44:21 lokilife opendkim[497]: OpenDKIM Filter v2.11.0 starting (args: -f)
Nov 25 01:44:22 lokilife opendmarc[512]: OpenDMARC Filter v1.4.0 starting (args: -f -p inet:8893@localhost -P /var/run/opendmarc/opendmarc.pid)
Nov 25 01:44:22 lokilife opendmarc[512]: additional trusted authentication services: lokilife.fun
Nov 25 01:44:23 lokilife dovecot: imap-login: Login: user=<maxim@coders-squad.com>, method=PLAIN, rip=46.159.2.106, lip=172.24.0.2, mpid=624, TLS, session=<3oFAqUHuG9gunwJq>
Nov 25 01:44:24 lokilife amavis[640]: starting. /usr/sbin/amavisd-new at lokilife.fun amavisd-new-2.11.1 (20181009), Unicode aware, LC_CTYPE="C.UTF-8"Nov 25 01:44:24 lokilife amavis[640]: perl=5.032001, user=, EUID: 110 (110);  group=, EGID: 112 112 (112 112)
Nov 25 01:44:24 lokilife amavis[640]: Net::Server: Group Not Defined.  Defaulting to EGID '112 112'
Nov 25 01:44:24 lokilife amavis[640]: Net::Server: User Not Defined.  Defaulting to EUID '110'
Nov 25 01:44:24 lokilife amavis[640]: No ext program for   .zoo, tried: zoo
Nov 25 01:44:24 lokilife amavis[640]: No ext program for   .doc, tried: ripole
Nov 25 01:44:24 lokilife amavis[640]: No decoder for       .F
Nov 25 01:44:24 lokilife amavis[640]: No decoder for       .doc
Nov 25 01:44:24 lokilife amavis[640]: No decoder for       .zoo
[ Server not responding ]

[ Amavis disabled ]
Nov 25 01:44:26 lokilife postfix/master[1241]: daemon started -- version 3.5.13, configuration /etc/postfix
Nov 25 01:46:17 lokilife dovecot: master: Dovecot v2.3.13 (89f716dc2) starting up for imap, lmtp, pop3
Nov 25 01:46:18 lokilife opendkim[502]: OpenDKIM Filter v2.11.0 starting (args: -f)
Nov 25 01:46:18 lokilife opendmarc[511]: OpenDMARC Filter v1.4.0 starting (args: -f -p inet:8893@localhost -P /var/run/opendmarc/opendmarc.pid)
Nov 25 01:46:18 lokilife opendmarc[511]: additional trusted authentication services: lokilife.fun
Nov 25 01:46:18 lokilife dovecot: imap-login: Login: user=<maxim@coders-squad.com>, method=PLAIN, rip=46.159.2.106, lip=172.25.0.2, mpid=517, TLS, session=<cIIasEHuJtgunwJq>
[ And again nothing from server ]
```

### Other relevant information

```Markdown
mailserver.env: https://pastebin.com/zbSPc3bz
```

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [X] I am rather experienced with docker
- [X] I am inexperienced with mail servers
- [ ] I am rather experienced with mail servers
- [ ] I am uncomfortable with the CLI
- [X] I am rather comfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by Lokilife** [comment]
Also I can provide some read-access to the server if needed

**Comment by Lokilife** [comment]
UPDATE. It stopped working altogether, the server no longer responds at all.

**Comment by georglauterbach** [comment]
Some points t clarify, maybe the solution hides behind one of them:

1. You are using POP3 - is that intended?
2. You are using mail quotas - is that intended? Are you at a quote limit?
3. What do you mean by `[ And again nothing from server ]`? No logs? Is it still running? Can you ´exec´ into the container?
4. Dovecot is set to use IPv6 as well? Is that intended? If not, please set `DOVECOT_INET_PROTOCOLS=ipv4`
5. Are you using LDAP? If not, why is `DOVECOT_TLS=yes` set?

**Comment by Lokilife** [comment]
Hello, @georglauterbach.
1. Yes, it was enabled when i had some troubles with connecting to the server but currently it's not in use.
2. As far as I remember they were enabled by default.
3. Container is still running, i can exec into it but here is no more logs after my requests.
4. Initially there was a need for IPv6, but it was gone before I could configure server to use it, but I didn't think it would make any difference given that it's working now, so I left it that way.
5. Tbh idk why is it set, I'm not the only one who initially configured the server and maybe it was set by accident.
6. Here is 2 ips but none of them are mine.
And if the problem was in these variables then the most strange thing here is that server were working, nobody touched it, but it's stopped working without the reason.
