### ISSUE TITLE
550 5.5.1 Protocol error when testing email reception

### ISSUE THREAD

**Issue by mickenorlen** [docker-mailserver/docker-mailserver#2919]
# 550 5.5.1 Protocol error when testing email reception

Other -> Email reception. With nginx proxy companion.

## Description

I have a home server with `docker-mailserver` and `nginx-proxy companion`. I've been running some tests and now have the basics working:

- DKIM
- SPF
- DMARC
- Ports open 

But when I use these tools to test email reception:

- [https://checkeremail.com/](https://checkeremail.com/)
- [https://gsuite.tools/verify-email](https://gsuite.tools/verify-email)
- [https://dnslytics.com/email-test](https://dnslytics.com/email-test)

They tell me that I cannot properly receive email with error `550 5.5.1 Protocol error` (See screenshots and logs below). 

This error is explained [here](https://mailtrap.io/blog/550-5-1-1-rejected-fix/) to potentially signify that they are trying to send me unencrypted SMTP content through ESMTP channels. Which `docker-mailserver`  (more specifically postscreen?) then rejects as explained [here](https://docker-mailserver.github.io/docker-mailserver/v10.0/config/security/understanding-the-ports/)

In practice email reception seems to be working when I'm sending emails to myself from different addresses. But I'm not sure it's working all of the time as we had some issues in the past. And I cannot believe all these tools could send emails through the wrong channels...

So I bet there is something wrong with my setup? Could this be related to nginx proxy companion? Thanks

---

## Screenshots and logs
 (`email@domain.com`, `my@mail.com` etc are fake address i hardcoded to hide my own after running the test).

![image](https://user-images.githubusercontent.com/9784434/205368646-5f0d3db9-740e-442f-a039-4e0c769f7182.png)

```BASH
Dec  2 19:58:35 mail postfix/postscreen[12001]: CONNECT from [51.38.115.65]:50038 to [172.21.0.5]:25
Dec  2 19:58:35 mail postfix/postscreen[12001]: PREGREET 23 after 0.16 from [51.38.115.65]:50038: HELO checkeremail.com\r\n
Dec  2 19:58:35 mail postfix/postscreen[12001]: NOQUEUE: reject: RCPT from [51.38.115.65]:50038: 550 5.5.1 Protocol error; from=<example@gmail.com>, to=<my@mail.com>, proto=SMTP, helo=<checkeremail.com>
Dec  2 19:58:35 mail postfix/postscreen[12001]: DISCONNECT [51.38.115.65]:50038
```

Same thing with gsuite:
![image](https://user-images.githubusercontent.com/9784434/205369066-8df79bb7-332a-4894-8562-585129f5b222.png)

```BASH
Dec  2 20:16:46 mail postfix/postscreen[14959]: PREGREET 19 after 0.05 from [83.136.248.69]:49628: HELO gsuite.tools\r\n
Dec  2 20:16:46 mail postfix/postscreen[14959]: NOQUEUE: reject: RCPT from [83.136.248.69]:49628: 550 5.5.1 Protocol error; from=<smtp-tester@gsuite.tools>, to=<email@domain.com>, proto=SMTP, helo=<gsuite.tools>
Dec  2 20:16:46 mail postfix/postscreen[14959]: HANGUP after 0.14 from [83.136.248.69]:49628 in tests after SMTP handshake
Dec  2 20:16:46 mail postfix/postscreen[14959]: DISCONNECT [83.136.248.69]:49628
```

**Comment by casperklein** [comment]
You can try: https://github.com/docker-mailserver/docker-mailserver/blob/2bc4078e351bc6f3867524e38d0b5c578b107fb5/mailserver.env#L82-L85

`TLS_LEVEL=intermediate`

**Comment by mickenorlen** [comment]
Thanks for the suggestion. The error is still there though.
