### ISSUE TITLE
Port 25 is blocked on AWS EC2 / Lightsail - any way to always proxy to a AWS SES login?

### ISSUE THREAD

**Issue by ghnp5** [docker-mailserver/docker-mailserver#2920]
I cannot send emails using the SMTP logins that this "docker-mailserver" provides, because port 25 is blocked on AWS EC2/Lightsail.

That's fine for me - I simply use AWS SES as my SMTP login on Thunderbird and similar.

However, for alerts from mailserver and similar things, I wonder if I could potentially lose emails because they may be accidentally be sent through mailserver itself.

Is there a way to proxy everything that attempts to use the SMTP protocol, forward to an AWS SES SMTP login?

**Comment by ghnp5** [comment]
Hey. Still interested in an answer, if anyone knows 😊
Cheers!

**Comment by casperklein** [comment]
TBH, I don't understand your setup and your current problem.

You can submit mails via port 465 for example. What's the purpose of docker-mailserver if port 25 is blocked by AWS?

> Is there a way to proxy everything that attempts to use the SMTP protocol, forward to an AWS SES SMTP login?

Maybe https://docker-mailserver.github.io/docker-mailserver/edge/config/environment/#default-relay-host ?

**Comment by ghnp5** [comment]
Thank you @casperklein 

> What's the purpose of docker-mailserver if port 25 is blocked by AWS?

To have my own mailboxes there, to receive and store emails :)
But to send emails, I use AWS SES.
docker-mailserver surely does have a purpose!

> You can submit mails via port 465 for example.

Yeah, using AWS SES, I use port 2587. That's fine.

However, emails sent by default, unauthenticated, such as Alerts coming from docker-mailserver (like "update available", etc), those go through port 25 by default, is that correct? (I'm confused)

**Comment by ghnp5** [comment]
Thank you very much @casperklein - this helps!

Can I just confirm that the Relay is only used if the mailbox password is correctly provided?

Meaning, AWS SES (the relay host) will **not** be invoked, if someone unknown attempts to connect to my SMTP server with an incorrect password.

Thanks again!

**Comment by casperklein** [comment]
Why don't you try/verify that yourself? 😉 Sending an email without correct credentials should not be possible.

You can check for an "open-relay" via https://mxtoolbox.com/diagnostic.aspx

**Comment by ghnp5** [comment]
Aaahhh... thanks so much. That's very helpful!

> SMTP Open Relay | OK - Not an open relay.

🥳🍾👍🏼
