### ISSUE TITLE
IPv4 address must be set in docker-compose.yml explicitly

### ISSUE THREAD

**Issue by ki9us** [docker-mailserver/docker-mailserver#2927]
I recently noticed that gmail users were unable to send email to my docker-mailserver instance.  Messages were being bounced back with this message

```
450 4.7.25 Client host rejected: cannot find your hostname, [172.23.0.1]
```

In the docker logs: 

```
CONNECT from [172.23.0.1]:32968 to [172.23.0.1]:25
PASS OLD [172.23.0.1]:32968
connect from unknown[172.23.0.1]
Anonymouse TLS connection established from unknown[172.23.0.1]...
NOQUEUE: reject: RCPT from unknown[172.23.0.1]: 450 4.7.25 Client host rejected: cannot find your hostname, [172.23.0.1]
disconnect from unknown[172.23.0.1]...
```

`172.23.0.1` is the docker gateway address to the docker network.  What was weird is that *other* mail services, like yahoo, were sending mail correctly and the logs were showing CONNECT from the correct external IP: 

```
CONNECT from [170.249.216.138]:39102 to [172.23.0.3]:25
PASS OLD [170.249.216.138]:39102
connect from atl.slvit.us[170.249.216.138]
Anonymous TLS connection established from atl.slvit.us[170.249.216.138]...
prepend Received-SPF: Pass (mailfrom)...
...
```

It took some googling before I found out what was happening.  The diagnostics were done by @Rillke in [a comment](https://github.com/docker-mailserver/docker-mailserver/issues/1405#issuecomment-590106498) in #1405, which I quote: 

> Compose created an IPv4 network, since IPv6 is not enabled for Docker on that host. When another host connects to the host running the container using IPv6, the **Docker Proxy translates IPv6 to IPv4** and inserts itself/its **Gateway as Source IP Address**, essentially doing NAT.

The first thing I did was to enable IPv6 and assign an IPv6 address to the container.  But to my surprise, it was showing connections from the docker gateway's IPv6 address, instead of the external IPv6 address.  That is to say, it seems like the IPv6 implementation is broken in docker (as usual).  

```
CONNECT from [2001:db8:1::1:0:1]:32968 to [2001:db8:1::1:0:2]:25
PASS OLD [2001:db8:1::1:0:1]:32968
connect from unknown[2001:db8:1::1:0:1]
Anonymouse TLS connection established from unknown[2001:db8:1::1:0:1]...
NOQUEUE: reject: RCPT from unknown[2001:db8:1::1:0:1]: 450 4.7.25 Client host rejected: cannot find your hostname, [2001:db8:1::1:0:1]
disconnect from unknown[2001:db8:1::1:0:1]...
```

The only ~solution~ workaround that worked for me was @Rillke's: 

> As an interim solution I bound port 25 to the public IPv4 interface instead of any interface. If my host wants to send email, it has to authenticate now, but that's okay.
> 
> ```
>     ports:
> -      - "25:25"
> +      - "the_IP_v4:25:25"
> ```

This closes port 25 on the VPS's IPv6 address and works around the problem.  Now, seeing as: 

 - The only requirement to reproduce this is to have a server with IPv6 (pretty common)
 - The result is silently not receiving emails from gmail and other big services (very serious)
 - Docker is not likely to fix their IPv6 implementation anytime soon (unfortunately)

... I am proposing making the README and docker-compose.yml explicit about putting the server's external IP address in the ports section.  I'd be happy to PR it.

**Comment by georglauterbach** [comment]
> If having an AAAA record prevents receiving mail, there should be big bold warnings about it.

What @casperklein meant was that if you do not publish AAAA records, servers will only try IPv4. I personally do that (because I think IPv6 is a _really_ bad protocol) and never had any issues.

**Comment by casperklein** [comment]
> If having an AAAA record prevents receiving mail, there should be big bold warnings about it.

It's best practice, to only publish DNS records, that a service supports. What's the point in creating an AAAA record for a service that you only want to be used via IPv4?

**Comment by super9mega** [comment]
tested it myself, adding `network_mode: "host"` does solve the issue and gives the container IPv4 and IPv6

**Comment by ki9us** [comment]
I know what @casperklein meant.  What I mean is that having AAAA records is no edge case.  

The point of IPv6 is that all devices can have their own IP so NAT is unnecessary.   It's much easier to configure because you can open ports on devices without messing with port-forwarding on your router.  This makes it much more accessible to self-host services, which makes the internet more decentralized, which is what the world needs.  Point is, there just aren't enough IPv4 addresses for the world's devices; NAT was a patch, IPv6 is the solution.  

This is why IPv6 is meant to supercede IPv4.  It's why everyone should have AAAA records on their websites, and docker should fix their IPv6 implementation, and my ISP should implement IPv6, and people should stop treating it as some fringe technology that exists for no reason.  

Ok, I'm done ranting and am ready to be helpful.  Some observations: 

 - When I tried `0.0.0.0:25:25` in docker-compose.yml, I got an `Address already in use error`.  I guess docker-compose doesn't support binding to 0.0.0.0.  
 - `network_mode: host` works too (thanks @super9mega)  The downside is that you miss out on the security of having the mailserver network-isolated from the rest of the server.  The upside would be that IPv6 works.  

I propose a clear warning in the "DNS - DKIM" section of the README, something like "WARNING: if you have an AAAA record for your server, this can break docker-mailserver.  See the FAQ" and then link to a FAQ question like "What if I have AAAA records?"  The answer would be a quick explanation of why that prevents receiving emails (or a link to this thread) and the two workarounds.

**Comment by ki9us** [comment]
> Not quite I think; Docker cannot bind to port 25 because it seems to be already in use. Please double-check with ss -tulpn | grep 25. Ports are a concept that live above OSI L4.

I know.  Nothing else is running on 25.  

> DNS records have nothing to do on your websites. You're mixing two protocols here: DNS and HTTP.

I am not.  I mean I have more than one service on my server, after @casperklein said:

> It's best practice, to only publish DNS records, that a service supports. What's the point in creating an AAAA record for a service that you only want to be used via IPv4?

I don't have time to argue about whether IPv6 is good or bad.  I'm just saying that not receiving mail because you dare to publish an AAAA record is a serious bug and should be in the documentation.  

> people who think they understood networking in fact do not

Fine.  Get someone who understands it to fix your documentation.  Or deny that there is a problem and let anyone with AAAA records miss emails.  I'm done here.

**Comment by ki9us** [comment]
> Not quite I think; Docker cannot bind to port 25 because it seems to be already in use. Please double-check with ss -tulpn | grep 25. Ports are a concept that live above OSI L4.

I know.  Nothing else is running on 25.  

> DNS records have nothing to do on your websites. You're mixing two protocols here: DNS and HTTP.

I am not.  I mean I have more than one service on my server, after @casperklein said:

> It's best practice, to only publish DNS records, that a service supports. What's the point in creating an AAAA record for a service that you only want to be used via IPv4?

I don't have time to argue about whether IPv6 is good or bad.  I'm just saying that not receiving mail because you dare to publish an AAAA record is a serious problem and should be in the documentation.  

> people who think they understood networking in fact do not

Fine.  Get someone who understands networking to fix your documentation.  Or don't, and let anyone with AAAA records miss emails.  I'm done here.
