### ISSUE TITLE
emails with failing DMARC policy=reject are not rejected

### ISSUE THREAD

**Issue by k3it** [docker-mailserver/docker-mailserver#2932]
# Subject

I would like some feedback concerning a use case

## Description

It appears that  mailserver detects DMARC policy failures, however the test spoofed emails are delivered to the mailbox even when the reject policy is set for the sender domain

relevant log:
```
Dec 12 18:58:48 mail postfix/smtpd[219195]: 727171F825F: client=m42-5.mailgun.net[69.72.42.5]
Dec 12 18:58:48 mail postfix/cleanup[219206]: 727171F825F: message-id=<20221212185846.eb1c91f1e50fc8d2@mg.spoofing.science>
Dec 12 18:58:48 mail opendkim[457]: 727171F825F: m42-5.mailgun.net [69.72.42.5] not internal
Dec 12 18:58:48 mail opendkim[457]: 727171F825F: not authenticated
Dec 12 18:58:48 mail opendkim[457]: 727171F825F: DKIM verification successful
Dec 12 18:58:48 mail opendkim[457]: 727171F825F: s=mx d=mg.spoofing.science a=rsa-sha256 SSL 
Dec 12 18:58:48 mail opendmarc[466]: 727171F825F: ibm.com fail
...
<*** mailserver continues with the message delivery to the mailbox ***>
```

This can be easily reproduced by sending a test spoof email from https://dmarc-tester.com/ .  Use a sender from a domain with the reject DMARC policy enabled for example  tony.soprano@ibm.com

for comparison., the same test email is rejected, as it supposed to,  when sending to a gmail address

**Comment by georglauterbach** [comment]
A very understandable issue; thank you for submitting it. The truth in the mail ecosystem is this though: it is better to receive one more illegitimate email than to loose one legit email. Hence, the option's (`RejectFailures`) current value (`false`) is actually a good default.

I agree though that this should be changable. The easiest thing would be to introduce an ENV variable like `DMARC_REJECT_ON_FAILURE`. I'd like to hear other maintainer's opinions on this a well though (CC @docker-mailserver/maintainers).

---

Personal opinion: I think the best thing would be to have anti-spam software that classifies these emails as SPAM but still delivers it to some folder. I am working on getting rspamd integrated into DMS, but I guess this should be achievable with the current software (Amavis + SpamAssassin) as well.

**Comment by k3it** [comment]
hello.  the DMARC action upon failure is controlled by the sender’s domain via the _dmarc dns record: pass, quarantine (move to spam folder), or reject.   Overriding this action by accepting the message and redirecting to another subsystem like spam assassin defeats the idea of DMARC, imo.  It is unnecessary to deliver a failing message if the domain owner requests a reject.  thank for your reply.   I understand this maybe a matter of personal preference.

**Comment by k3it** [comment]
It is true that the *default* setting in opendmarc is to accept emails even on failures, regardless of the policy setting specified in the sender's domain _dmarc DNS record.  perhaps this is an opendmarc issue rather than the mailserver's.    

Inventing additional variables which second guess the specified policy can lead to undesirable side effect and complication. The sender clearly communicates the desired behavior through their _dmarc. dns record.  Note that opendmarc would reject a message only if the DMARC check fails *and* the sender's domain policy is set to reject.  I have verified this by sending a "spoofed" email from a domain with a policy set to 'none'.   The email was accepted by opendmarc, as expected, even with the  `RejectFailures true` setting.


https://datatracker.ietf.org/doc/rfc7489/

       none:  The Domain Owner requests no specific action be taken
         regarding delivery of messages.

      quarantine:  The Domain Owner wishes to have email that fails the
         DMARC mechanism check be treated by Mail Receivers as
         suspicious.  Depending on the capabilities of the Mail
         Receiver, this can mean "place into spam folder", "scrutinize
         with additional intensity", and/or "flag as suspicious".

      reject:  The Domain Owner wishes for Mail Receivers to reject
         email that fails the DMARC mechanism check.  **Rejection SHOULD
         occur during the SMTP transaction.**  See Section 10.3 for some
         discussion of SMTP rejection methods and their implications.

**Comment by georglauterbach** [comment]
I see, thanks for the clarification. Then LGTM!
