### ISSUE TITLE
SSL cert unused 

### ISSUE THREAD

**Issue by cainiaoxiao** [docker-mailserver/docker-mailserver#2939]
HI I meet a problem when i deploy dms on my docker server. At first I use it with out SSL cert and I can used imap connect to my client. And then I turn on SSL by env ，but I found server refuse my tls request, then I found author provied a way to verify if the cert is right I found some wrong like this 
![ccf99fd1681ecfde49ef53368822dd4](https://user-images.githubusercontent.com/30982115/208641129-a6bf0f90-13a1-4935-974d-3dedfe7190dd.png)
![e057e95a23147ff089fcb13f4199d9c](https://user-images.githubusercontent.com/30982115/208641172-821554d5-ea7b-4677-a718-08660a0c377c.png)
it looks like ssl function unavailable so i think some wrong in postfix setting.  I look into /etc/postfix/10-ssl.conf,and find the ssl is disable:
![ea8b273f85c44ed07e8197710d29c11](https://user-images.githubusercontent.com/30982115/208641824-2addd069-27f8-4911-9f5c-4a35e33b934c.png)
so I enable ssl at this conf,restart container and succeed. Then I want to know how it happend .repetition :I remove it and creat it again . At default I Turn on ssl , there is no problem. And I remove it and create again ,with out SSL ,turn on SSL later,the problem find again,I recreate it again The problem disappear So I think a probably: The ssl setting only execute at first run in docker if you choose turn on ssl later one choice is modify conf second choice is recreate the container.

**Comment by cainiaoxiao** [comment]
sorry, it's dovecot instead of postfix and i'm sorry about my English

**Comment by georglauterbach** [comment]
hello :) Can you formulate the question you have again please; or is this a bug report?

**Comment by polarathene** [comment]
When you are doing your tests, you should also confirm that the ENV inside the container has in fact changed.

Note that container restarts (instead of recreating a fresh container) restores previous internal state since the container last run. We document this as potentially buggy, and advise you always `docker-compose down && docker-compose up` or `docker-compose up --force-recreate` to ensure that issue is avoided when you want to change settings or restart the container.

**Comment by cainiaoxiao** [comment]
> 

emmm I know you mean When problem first happend ,  I went to conform if my ENV have some problem , so I read the document again and use LOG_LEVEL = debug to get more information about it . On attach console I find my ENV is OK .
AS well,I not use docker-compose I watch the yaml and manual setting my container.
The most important is : If i setup my dms all right in my first boot my dms ,there is nothing happend. It work well.Only at first I don't use SSL then, boot dms up then turn SSL on the problem was happend...... So I suspect if dms set SSL configuration at first boot? my env set like this:
![6b7ee0e03502588db24bce31c2fde0c](https://user-images.githubusercontent.com/30982115/208795249-bd978f40-e2c7-40dc-91f9-fa23136251c7.jpg)
debug log like this:
![c8fa3075b5fcd269b55d9d8b3c463c2](https://user-images.githubusercontent.com/30982115/208795308-4aa1b77a-5708-4a01-8839-f7c44316acdd.png)

**Comment by cainiaoxiao** [comment]
I am sorry about my ENGLISH level . And I'm a beginner on github as well. Later I well study more about how to use github ,and then wirte a blog with native language and translate into English try my best.I'm so sorry about this. And I deploy it on my docker I  meet some other problem. After I  set some config document in dms it now work all right.I think maybe I should to learn postfix more. But In my country I cannot open postfix website.....Too difficult....although it work right now,I want to know more...
