### ISSUE TITLE
[FR] Spamhaus Data Query Service support

### ISSUE THREAD

**Issue by tjedmunds** [docker-mailserver/docker-mailserver#2955]
# Feature Request

It would be nice to be able to add support for Spamhaus Data Query Service to avoid queries being blocked when using a public DNS provider. Accounts are free for small usage and the feature would make configuration much easier. Another problem DQS resolves is that it works around the many ISP's that are now hijacking DNS queries and forcing you to use their servers.

## Context

Right now to avoid Spamhaus from blocking queries you need to either stand up your own recursive DNS server or register for a key which becomes part of the spamhaus URL in the postfix main.cf file. For example references to:

zen.spamhaus.org=127.0.0.[2..11]

become:

<your-key-goes-here>.zen.dq.spamhaus.net=127.0.0.[2..255]

While it is possible to replace the usage in main.cf directly it is possible that the user will lose a future addition made by docker-mailserver since there are likely other *restrictions that are provided out of box. A safer/cleaner work around is presently to run a sed command from user-patches.sh.

This feature just makes it easier to do without doing hack-ish like changes which could break something down the road.

### Is your Feature Request related to a Problem?

Not really. Sed seems to be a good workaround for now. Sed can change the URL's if DNSBL is enabled.

### Describe the Solution you'd like

Adding my key as an optional environment variable would be really nice. If the key is present then fix up the URL's in main.cf as appropriate.

### Are you going to implement it?

No, and I understand that it is highly likely no one will implement it. Furthermore, I understand that this issue will likely become stale and will be closed.

### What are you going to contribute??

I could test and verify functionality.

**Comment by tjedmunds** [comment]
Text above was lost when in between angle brackets. 

.zen.dq.spamhaus.net=127.0.0.[2..255] 

should read as 

your-key.zen.dq.spamhaus.net=127.0.0.[2..255]

**Comment by georglauterbach** [comment]
If this only requires a bit of `sed`, I can likely provide a solution.
