### ISSUE TITLE
[BUG] Server (docker) no longer accessible after upgrade

### ISSUE THREAD

**Issue by tanglebridge** [docker-mailserver/docker-mailserver#2956]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

Unable to connect to mailserver from client

### What happened and when does this occur?

```Markdown
I updated to 11.3.1 from 11.3.0. I am quite sure that when it broke, although I updated to 11.3.0 very shortly before that.
```

### What did you expect to happen?

```Markdown
Without changes in the configuration, I expected the server to function as before.
```

### How do we replicate the issue?

```Markdown
1. docker-compose down
2. docker-compose pull
3. docker-compose up -d

Attempt to connect client.
```

### DMS version

11.3.1

### What operating system is DMS running on?

Linux

### Which operating system version?

Asustor ADM4 - Linux version 5.4.x (root@sw1-server) (gcc version 7.4.0 (crosstool-NG 1.24.0))

### What instruction set architecture is DMS running on?

AMD64 / x86_64

### What container orchestration tool are you using?

Docker

### docker-compose.yml

```yml
services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    # If the FQDN for your mail-server is only two labels (eg: example.com),
    # you can assign this entirely to `hostname` and remove `domainname`.
    hostname: mail
    domainname: tanglebridge.com
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /volume0/usr/builtin/etc/certificate:/certs:ro
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```

### Relevant log output

```bash
Dec 24 13:03:08 mail dovecot: master: Dovecot v2.3.13 (89f716dc2) starting up for imap, lmtp (core dumps disabled)
Dec 24 13:03:09 mail opendkim[614]: OpenDKIM Filter v2.11.0 starting (args: -f)
Dec 24 13:03:10 mail opendmarc[623]: OpenDMARC Filter v1.4.0 starting (args: -f -p inet:8893@localhost -P /var/run/opendmarc/opendmarc.pid)
Dec 24 13:03:10 mail opendmarc[623]: additional trusted authentication services: mail.tanglebridge.com
Dec 24 13:03:13 mail amavis[772]: starting. /usr/sbin/amavisd-new at mail.tanglebridge.com amavisd-new-2.11.1 (20181009), Unicode aware, LC_CTYPE="C.UTF-8"
Dec 24 13:03:13 mail amavis[772]: perl=5.032001, user=, EUID: 110 (110);  group=, EGID: 112 112 (112 112)
Dec 24 13:03:14 mail amavis[772]: Net::Server: Group Not Defined.  Defaulting to EGID '112 112'
Dec 24 13:03:14 mail amavis[772]: Net::Server: User Not Defined.  Defaulting to EUID '110'
Dec 24 13:03:14 mail amavis[772]: No ext program for   .zoo, tried: zoo
Dec 24 13:03:14 mail amavis[772]: No ext program for   .doc, tried: ripole
Dec 24 13:03:14 mail amavis[772]: No decoder for       .F   
Dec 24 13:03:14 mail amavis[772]: No decoder for       .doc 
Dec 24 13:03:14 mail amavis[772]: No decoder for       .zoo 
Dec 24 13:03:17 mail postfix/master[1320]: daemon started -- version 3.5.17, configuration /etc/postfix
Dec 24 13:03:17 mail postfix/pickup[1323]: 563E65560732: uid=0 from=<root>
Dec 24 13:03:17 mail postfix/cleanup[1328]: 563E65560732: message-id=<20221224210317.563E65560732@mail.tanglebridge.com>
Dec 24 13:03:17 mail opendkim[614]: 563E65560732: DKIM-Signature field added (s=mail, d=tanglebridge.com)
Dec 24 13:03:17 mail postfix/qmgr[1324]: 563E65560732: from=<root@mail.tanglebridge.com>, size=761, nrcpt=1 (queue active)
Dec 24 13:03:17 mail dovecot: lmtp(1343): Connect from local
Dec 24 13:03:17 mail dovecot: lmtp(willem.atsma@tanglebridge.com)<1343><uxOXIRVpp2M/BQAAbwmJbQ>: sieve: msgid=<20221224210317.563E65560732@mail.tanglebridge.com>: stored mail into mailbox 'INBOX'
Dec 24 13:03:17 mail postfix/lmtp[1342]: 563E65560732: to=<willem.atsma@tanglebridge.com>, orig_to=<postmaster@tanglebridge.com>, relay=mail.tanglebridge.com[/var/run/dovecot/lmtp], delay=8.3, delays=8/0.02/0.02/0.2, dsn=2.0.0, status=sent (250 2.0.0 <willem.atsma@tanglebridge.com> uxOXIRVpp2M/BQAAbwmJbQ Saved)
Dec 24 13:03:17 mail dovecot: lmtp(1343): Disconnect from local: Client has quit the connection (state=READY)
Dec 24 13:03:17 mail postfix/qmgr[1324]: 563E65560732: removed
```

### Other relevant information

```Markdown
I don't see anything unusual in the log. The /certs/ volume mount points to certificates obtained by the host via letsencrypt and they are present and up to date. They have been working fine.

I use the setup.sh to create accounts. Nothing particular to the setup other than the way the letsencrypt certs are used. DKIM is configured and has been working without problems.

For the above both loglevel options were set to "debug".
```

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [X] I am rather experienced with docker
- [ ] I am inexperienced with mail servers
- [X] I am rather experienced with mail servers
- [ ] I am uncomfortable with the CLI
- [X] I am rather comfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by georglauterbach** [comment]
v11.3.1 fixes a _build time_ issue compared to v11.3.0; so, in theory, there should be no difference at runtime.

**Comment by tanglebridge** [comment]
Thanks for responding! Yeah I don't get it either. I used `docker-compose pull`. I will get the trace info.

**Comment by georglauterbach** [comment]
Also make sure the IP you're connecting from is not banned by Fail2Ban. If startup logs show nothing, we need to dig deeper. Is the client you're connecting from showing an error, or a timeout?

**Comment by tanglebridge** [comment]
I updated from the most recent version before that, so 11.3.0. Fail2ban is not activated, and not running on the host.  I turned on trace but there is nothing that seems strange or out of place. It looks like there is a connection problem. I am now experimenting with my DNS setup and will look into ways to test connectivity, or get logs out of my client. Port scanning shows all is well and good.

**Comment by tanglebridge** [comment]
Setup is failing basic connectivity test (nc -vz). 
In the container netstat -an shows all is well. Dovecot is listening on the imaps port.

I figured maybe docker did not manage to reconnect the network bridge, and indeed rebooting the host fixed the problem!!! A new thing for me but perhaps a note of caution for others.
