### ISSUE TITLE
unknown user when login

### ISSUE THREAD

**Issue by 0xZoomEye** [docker-mailserver/docker-mailserver#2961]
# Subject

Other

## Description

I added user `./setup.sh email add test@suntopo.com password`, but when i login and i got those log message. i checked the email list, and this email was on the list.

``` BASH
Dec 27 14:50:54 mail dovecot: auth: passwd-file(test@suntopo.com,1.14.69.203,</kQ+qMnwgdABDkXL>): unknown user (SHA1 of given password: 523336)
Dec 27 14:50:56 mail dovecot: auth: passwd-file(test@suntopo.com,1.14.69.203,</kQ+qMnwgdABDkXL>): unknown user (SHA1 of given password: 523336)
Dec 27 14:50:58 mail dovecot: auth: passwd-file(test@suntopo.com,1.14.69.203,</kQ+qMnwgdABDkXL>): unknown user (SHA1 of given password: 523336)


```

**Comment by casperklein** [comment]
It's hard to tell what the cause is, you may try to restart the container (`docker-compose down; docker-compose up -d`) to see if that helps.
