### ISSUE TITLE
Outgoing email end up as SPAM no matter what

### ISSUE THREAD

**Issue by springcomp** [docker-mailserver/docker-mailserver#2962]
# Subject

I have been scratching my head to figure out why outgoing emails end up as SPAM.

## Description

I used MX Toolbox to analyze headers from one such email and this gave me some useful diagnostics:
However, I have no idea how to solve this problem.

![image](https://user-images.githubusercontent.com/8488398/209634598-609389a8-0bc8-4bcc-8650-35d5b4014de2.png)

**Comment by casperklein** [comment]
You may disable DKIM to see, if mails are not tagged as spam afterwards.

Also, your mailserver IP address/network may be on a DNS blacklist.

**Comment by springcomp** [comment]
@casperklein Thanks  for your feedback.

I was under the assumption that somehow my config prevented `docker-mailserver` from correctly signing the outbound message  as the signature seems to not be validated by third-parties.

My IP is definitively on blacklists. My guess is that this is one of the reasons why. Hence I‘m trying to figure out how to correctly configure everything.

**Comment by casperklein** [comment]
If your host/network is on a blacklist, there isn't much you can do configuration wise (unless you are running an open relay 😆).
