### ISSUE TITLE
Setting up aliases, when using relay due to outgoing port 25 being blocked.

### ISSUE THREAD

**Issue by ferdinandyb** [docker-mailserver/docker-mailserver#2967]
# Subject

I would like to configure a not documented mail server use case

## Description

I'm trying to set up alias to external domains on Oracle Always Free. Unfortunately, for any new tenants Oracle blocks any outgoing traffic on port 25. They offer an smtp service (3100 per month free emails), which I have been able to set up as a relay for my outgoing mail, but the problem is, that you have to explicitly whitelist each and every address that can send, so setting up a `DEFAULT_RELAY_HOST` results in the mail being rejected, since the "from" address is the original sender of the email:

```
535 Authorization failed: Envelope From address <[original sender]> not authorized (in reply to MAIL FROM command))
```
E.g. I have an alias `x@mydomain.com -> somebody@gmail.com` and somebody@outlook.com sends an email to x@mydomain.com then Oracle will complain the somebody@outlook.com is not authorized to send.

Do you have any ideas or recommendations on how to get around this? Thanks very much! (And also for the project in general it was extremely easy to set up even with relays and stuff!)

**Comment by casperklein** [comment]
If you can't whitelist your mailserver by IP, I think there isn't much you can do.

**Comment by ferdinandyb** [comment]
On Tue Jan 03, 2023 at 20:27, Casper wrote:
> If you can't whitelist your mailserver by IP, I think there isn't much you can do.

Would it be maybe possible to somehow force sieve to use the relay? in the logs
(when sieve is triggered to copy to external address) it says `relay=[myhost]`
so it at least knows the concept. Or force the alias to use the relay when
sending externally? Or even always?

**Comment by casperklein** [comment]
Not exactly sure, what you mean by forcing sieve. However, **forwarding** mails is always problematic, as it breaks SPF and other features.

1. `somebody@outlook.com --> x@mydomain.com (DMS).`
2. `somebody@outlook.com (DMS) --> somebody@gmail.com (Oracle)`  At this point, oracle recognize that your DMS is not allowed to send mails in behalf of `outlook.com`. Take a look at the SPF record to get a list of authorized server. That's why you have to whitelist the sender mail address.
3. `somebody@outlook.com (Oracle) --> somebody@gmail.com` Same here. At the final destination, gmail recognize that oracle is not allowed to send mails in behalf of `outlook.com` and could reject the mail.

I think, the oracle SMTP service is fine for **sending** mails (as long as there are no or correct SPF records set, allowing oracle to send mails in behalf).

To avoid all this, I would recommend to use any cheap VPS, where port 25 is not blocked.

PS: Just wondering, oracle just blocks outgoing (port 25) traffic, but allows incoming port 25 traffic?

**Comment by ferdinandyb** [comment]
On Sat Jan 07, 2023 at 13:19, Casper wrote:
> Not exactly sure, what you mean by forcing sieve. However, **forwarding** mails is always problematic, as it breaks SPF and other features.
What I saw is that even though postfix is configured to use the relay, via the environment variables, when sieve triggers a forward or when aliasing is set up, the relay is not used and postfix is trying to connect directly via port 25 to the other mailserver.

>
> 1. ***@***.*** --> ***@***.*** (DMS).`
> 2. ***@***.*** (DMS) --> ***@***.*** (Oracle)`  At this point, oracle recognize that your DMS is not allowed to send mails in behalf of `outlook.com`. Take a look at the SPF record to get a list of authorized server. That's why you have to whitelist the sender mail address.
> 3. ***@***.*** (Oracle) --> ***@***.***` Same here. At the final destination, gmail recognize that oracle is not allowed to send mails in behalf of `outlook.com` and could reject the mail.

Hmm, now I don't understand how you could have aliases to external email addresses even with outgoing port 25 open 😅 SPF would be bad anyway, even if I could just send it. Oh, or this is what you meant in your earlier comment by whitelisting? Not for outgoing port 25, but getting my server set as an allowed sender for e.g. outlook (so not possible in general).

In that case I guess what I could do is basically create a new email from the one I need to forward, send it from say a ***@***.*** with the reply-to header set for the original ***@***.***".
>
> I think, the oracle SMTP service is fine for **sending** mails (as long as there are no or correct SPF records set, allowing oracle to send mails in behalf).
>
> To avoid all this, I would recommend to use any cheap VPS, where port 25 is not blocked.

But this would not solve the SPF/DKIM issue really, right?
>
> PS: Just wondering, oracle just blocks outgoing (port 25) traffic, but allows incoming port 25 traffic?
Yes, exactly, so the only issue I've run into is forwarding really, everything else works fine.

Thanks very much for your time!

**Comment by casperklein** [comment]
> the relay is not used and postfix is trying to connect directly via port 25 to the other mailserver.

Not sure about this, could be a bug.

> SPF would be bad anyway, even if I could just send it.

Correct. Just google for "mail forwarding spf" 😉

> But this would not solve the SPF/DKIM issue really, right?

Yes.

Two "problems" here:

1. Port 25 blocked, Relay service needed  --> Cheap VPS with port 25 available --> no relay needed.
2. SPF problems with mail forwarding --> AFAIK no real solution available.

**Comment by casperklein** [comment]
> are there steps I can do to verify this?

You could open a new issue to see if another maintainer/user may be able to help. I am not using a relay setup myself, so my experience with that is limited.

**Comment by ferdinandyb** [comment]
sure, thanks!

**Comment by ferdinandyb** [comment]
Figure out that to send forwards via the relay you need to also set `DEFAULT_RELAY` (not that is helps, but for the record).
