### ISSUE TITLE
[  ERROR  ]  Fail2ban not running

### ISSUE THREAD

**Issue by carldavis** [docker-mailserver/docker-mailserver#2977]
I cannot interact with Fail2ban and not sure what to try next.

```
./setup.sh -c mailserver-mydomain fail2ban
[  ERROR  ]  Fail2ban not running
[  ERROR  ]  Aborting
```

But it is running

```
docker exec -it 3f3b1a208ced ps auxfww | grep fail2ban
root         498  0.0  0.0   4268  3196 ?        S    06:56   0:00  \_ /bin/bash /usr/local/bin/fail2ban-wrapper.sh
root         508  0.3  0.0 761612 19636 ?        Sl   06:56   0:01 /usr/bin/python3 /usr/bin/fail2ban-server --async -b -s /var/run/fail2ban/fail2ban.sock -p /var/run/fail2ban/fail2ban.pid --loglevel INFO --logtarget /var/log/fail2ban.log --syslogsocket auto
```

I am running 'docker-mailserver:latest' and have downloaded the most recent version of setup.sh

**Comment by casperklein** [comment]
How do you restart your container? Use `docker-compose down; docker-compose up` for that.

**Comment by carldavis** [comment]
Usually I am doing ```docker-compose up -d --force-recreate``` after a ```docker-compose pull```

**Comment by casperklein** [comment]
> ls: cannot access '/var/run/fail2ban/fail2ban.sock': No such file or directory

Does the directory `/var/run/fail2ban` exists?

**Comment by polarathene** [comment]
This would likely be due to ulimit being too high in the container. Our tests specifically restrict this for contributors that it'd impact (such as myself).

The master branch recently merged a new update for F2B version since the issue was opened. I believe that includes a proper fix to avoid the need for configuring the containers ulimits.

Please update to the the latest `:latest` image to verify :+1:

**Comment by yougeedev** [comment]
> I cannot interact with Fail2ban and not sure what to try next.
> 
> ```
> ./setup.sh -c mailserver-mydomain fail2ban
> [  ERROR  ]  Fail2ban not running
> [  ERROR  ]  Aborting
> ```
>
`sudo ./setup.sh fail2ban`  is working. Just struggled the last hour with the same issue.

**Comment by jor32233223** [comment]
Same issue here..
docker exec -it mailserver fail2ban works
in mailserver.env enabled in  cap_add:
      - NET_ADMIN enabled.
Is it working and the setup script just not working with setup fail2ban?

Would be nice if i could validate it works you def want to block spammers
