### ISSUE TITLE
What is the DNS Server used by DMS? dig/dog to the rescue?

### ISSUE THREAD

**Issue by scara** [docker-mailserver/docker-mailserver#2987]
# What is the DNS Server used by DMS? `dig`/`dog` to the rescue?

## Description
I'm very new to DMS: just installed yesterday (`11.3.1`) on my RPI4 to replace the SMTP/POP3/IMAP environment in my Homelab, used for testing purposes i.e. where https://github.com/mailhog/MailHog cannot be useful e.g. when an actual IMAP account is required to implement/test a specific feature.
I'm very happy with the ENV VAR driven setup and its SW selection, including the slim image.

BTW I cannot understand what is the actual DNS resolver the DMS container is using, guessing the DNS used by the Docker Engine Host: I'm missing something like `dig` to be sure that DMS reads the proper info from my local DNS Server.

I was not able to find anything related in both the Docs and the FAQ.

TIA,
Matteo

**Comment by casperklein** [comment]
> I cannot understand what is the actual DNS resolver the DMS container is using, guessing the DNS used by the Docker Engine Host

That is correct (like every container?).

> I'm missing something like dig

You can install `dig` by running: `apt update && apt install bind9-dnsutils`.

**Comment by scara** [comment]
TNX @casperklein!
> That is correct, see [here](https://docs.docker.com/config/containers/container-networking/#dns-services) for more details.

Not always, it depends as per your link: you can even provide `dns` settings which doesn't work in my DMS container since I used a `compose` file to start it i.e. custom default network and `resolv.conf` is always overwritten by Docker.
I'll give a "standard" `docker run` a try since in my Homelab `pi-hole` is used as the DNS Server, hosted in a container in the same Docker Engine where DMS is running and it gives me some constraints about how to let other container to use that service.

> You can install `dig` by running: `apt update && apt install bind9-dnsutils`.

Yes but what about increase the surface of the default image by adding a CLI command for DNS lookup purposes?

BTW, I know mine is a specific use case: I'm going to close this question given my "broken" setup.

Thanks for your time!
Matteo

**Comment by casperklein** [comment]
> you can even provide dns settings which doesn't work in my DMS container since I used a compose file to start it

You can [set DNS](https://docs.docker.com/compose/compose-file/#dns) servers also with docker-compose.

> Yes but what about increase the surface of the default image by adding a CLI command for DNS lookup purposes?

`ping` & `dig` will [be added](https://github.com/docker-mailserver/docker-mailserver/pull/2989) to the image 👍

**Comment by scara** [comment]
Hi @casperklein,
> You can [set DNS](https://docs.docker.com/compose/compose-file/#dns) servers also with docker-compose.

it doesn't work since a compose forces its own `resolve.conf` to point to `nameserver 127.0.0.11` due to the need of the Docker Engine to provide _service_ name resolution.
I just solved my issue a couple of minutes ago by adding the following conf to the compose to avoid to create a network different from the default `bridge` network:
```yaml
services:
  # There is just the 'mailserver' service in this compose, even to play fine w/ default bridge network.
  mailserver:
    image: docker.io/mailserver/docker-mailserver:11.3.1
    container_name: mailserver
    restart: unless-stopped
    network_mode: bridge
    hostname: mail
    ...
 ```
Being the compose "composed" by just the `mailserver` service it gives me the opportunity to set the DNS server i.e. the IP of the Docker Engine in the `bridge` network where the published ports of the other containers are available even for the local containers like my internal DNS Server.
Just for Community ref.

> `ping` & `dig` will [be added](https://github.com/docker-mailserver/docker-mailserver/pull/2989) to the image 👍

Great, thanks!
May I suggest to add only `dig` to avoid issues in a rootless context like podman?
`curl` is already there in the image and you can check if an host is reachable using TCP and not ICMP like with `ping`:
```
# curl -v --connect-timeout 3 telnet://<host>:<port>
```

HTH,
Matteo

**Comment by polarathene** [comment]
> compose to avoid to create a network different from the default `bridge` network

If you need to use the default Docker Engine `bridge` network (configured with `/etc/docker/daemon.json` settings), this is the correct approach yes.

Note that you can specify a custom network in your compose config, and for the network key, you can choose `default` to override the one compose implicitly creates, but by using the `default` key for the network, it will still be implicitly attached to all services defined in the compose config.

That should still provide an embedded DNS, but allow for you to configure the subnets and assign specific IP to each service.

---

FWIW, the official Docker Engine docs discourage using the default bridge network, and consider it legacy / convenience IIRC, not something that should be relied upon in production.

**Comment by polarathene** [comment]
> May I suggest to add only `dig` to avoid issues in a rootless context like podman?

- What issues does `ping` cause? Nothing changes does it, other than `ping` not working as expected?
- If the user does not understand why, they'd still have that frustration if they manually add it themselves?
- What is the benefit of not including a tool useful for rootful context?

**Comment by scara** [comment]
Hi @polarathene,
> FWIW, the official Docker Engine docs discourage using the default bridge network, and consider it legacy / convenience IIRC, not something that should be relied upon in production.

I fully agree: mine is an Homelab i.e. _production_ but for home purposes.
I started simplifying it removing stuff relying on OSes like mine always-up-to-date `bind` setup (almost 20yrs of local good service) to leverage what I've already in place for general purposes (`pi-hole` and `ubound`) using the few HW as possible and almost in containers on a little Pi4 4GB RAM.

Matteo

**Comment by scara** [comment]
Hi @polarathene,
> * What issues does `ping` cause? Nothing changes does it, other than `ping` not working as expected?

Nothing but it doesn't work (`permission denied`): you can argue that who goes with the _rootless_ path will be skilled enough to understand the potential issues.

> * If the user does not understand why, they'd still have that frustration if they manually add it themselves?

That's the point: a production-ready image should be immutable when deployed and the user should create their own flavour using the current image as their own base image if the tools they want are not there and not of common interest to be there in the base.
I know: it's hard and I agree with you in advance 😉.

> * What is the benefit of not including a tool useful for rootful context?

Nothing but providing the right tool for the specific use case.
Usually `ping` is used to determine if a host is reachable, using ICMP which some Companies/Providers still filter (I'm not a fan of such policy).
Mostly, the ultimate end of "being reachable" is actually the possibility to consume a network service hosted in that "reachable host:" why not using a TCP check using `curl` as proposed above?
It will even save the _rootless_ use case.

I'm not voting against `ping` being added here: just proposing a different point of view focusing on what a tool should be useful for.

I'm new here so thanks for taking the time to consider and reply to my comments: appreciated!
Matteo

**Comment by polarathene** [comment]
> I fully agree: mine is an Homelab i.e. _production_ but for home purposes.

That doesn't seem to give any reason to go against the advice?

You can create an explicit named network `docker network create my-network` and use that, possibly configuring it further depending on your needs.

If you don't see any benefit from following the upstream advice, that's fine it's your setup :+1: 

---

> Nothing but it doesn't work (`permission denied`):

Yeah, not a concern, it's not going to work either way.

If you attempt to use `ping` in that context you'll be unsuccessful either way. That doesn't justify a reason to avoid including it.

> the user should create their own flavour using the current image as their own base image if the tools they want are not there and not of common interest to be there in the base.

I agree with you. However this image caters to an audience where there will often be content in the image that's not of interest to many. Notably with certain features that get approved and contributed.  Where possible, we do defer more niche changes to using `user-patches.sh`.

The focus is on providing a single image that simplifies setting up and deploying a mail-server. Competing projects take a different approach with feature support spread across multiple images (_usually my preference_), those tend to be more pure / upstream images for services instead.

> I'm not voting against `ping` being added here: just proposing a different point of view focusing on what a tool should be useful for

I think you make a fair point :)

These tools have a very small footprint, so I don't mind them being included to assist debugging network issues. We're rather friendly maintainers though, if there were enough users expressing good reasons for a change we'd definitely take that into consideration :grinning:
