### ISSUE TITLE
how to setup PTR record?

### ISSUE THREAD

**Issue by epubreader** [docker-mailserver/docker-mailserver#2991]
docker-compose setting:
    hostname: mail
    domainname: xxxx.com

I have added a ptr records to xxxx.com, but Gmail  rejected all my emails,
which PTR records should be added mail.xxxx.com or xxxx.com?

host gmail-smtp-in.l.google.com[108.177.15.27] said:
    550-5.7.25 [144.76.109.34] The IP address sending this message does not
    have a 550-5.7.25 PTR record setup, or the corresponding forward DNS entry
    does not 550-5.7.25 point to the sending IP. As a policy, Gmail does not
    accept messages 550-5.7.25 from IPs with missing PTR records. Please visit
    550-5.7.25  https://support.google.com/mail/answer/81126#ip-practices for
    more 550 5.7.25 information.
    o7-20020a05600002c700b002423d081bc9si7786936wry.828 - gsmtp (in reply to
    end of DATA command)

**Comment by casperklein** [comment]
>  which PTR records should be added mail.xxxx.com or xxxx.com?

mail.xxxx.com

If you just added the PTR record, DNS can take some time to populate.
