### ISSUE TITLE
Multiple Domains SSL Certificate

### ISSUE THREAD

**Issue by johncadengo** [docker-mailserver/docker-mailserver#2995]
Hi, I want to use docker mail server with multiple domains. The documentation says I can do the following:

https://github.com/docker-mailserver/docker-mailserver#support-for-multiple-domains

```
./setup.sh email add user1@docker.example.com
./setup.sh email add user1@mail.example.de
./setup.sh email add user1@server.example.org
```

I was able to complete this step. However, I want to be able to have the domains have SSL certificates. I ran certbot like this:

```
certbot certonly --config-dir /home/john/docker-mailserver/letsencrypt --logs-dir /home/john/docker-mailserver/letsencrypt/log --work-dir /home/john/docker-mailserver/letsencrypt -d domain2.com -d "*.domain2.com" --preferred-challenges dns-01 --manual
```

And I was able to produce a new certificate in the `letsencrypt/live` folder. However, when I try using my mail client to connect, it says the connection is insecure and when I show certificate, it shows only the certificate for the original domain, which is listed in my docker-compose.yml file, and works just fine. 

How do I have an SSL certificate for my 2nd domain?

**Comment by casperklein** [comment]
Normally, you use one certificate per mail server, e.g. mail.example.com.

This mail server may handle different domains, e.g. @example2.com and @example3.com.

No matter for which domain you want to login and fetch mails, you use "mail.example.com" as server name in your mail client.

---

You can create a SAN certificate which can contain more than one DNS name, but I wouldn't recommend it.

**Comment by casperklein** [comment]
> certbot certonly --config-dir /home/john/docker-mailserver/letsencrypt --logs-dir /home/john/docker-mailserver/letsencrypt/log --work-dir /home/john/docker-mailserver/letsencrypt -d domain2.com -d "*.domain2.com" --preferred-challenges dns-01 --manual

You have to run

`certbot certonly --config-dir /home/john/docker-mailserver/letsencrypt --logs-dir /home/john/docker-mailserver/letsencrypt/log --work-dir /home/john/docker-mailserver/letsencrypt -d mail.example.com --preferred-challenges dns-01 --manual`

**Comment by dennismenken** [comment]
Would be a great feature to handle multiple certificates for different domain names.

**Comment by brenoperucchi** [comment]
@casperklein 
Each domain gets your SSL Certificate. Can I do that? Because I have been receiving this error of [CheckTLS.com](https://www.checktls.com/TestReceiver)

```bash
./setup.sh email add user@DOMAIN1.com
docker run --rm -it   -v "${PWD}/docker-data/certbot/certs/:/etc/letsencrypt/"   -v "${PWD}/docker-data/certbot/logs/:/var/log/letsencrypt/"   -p 80:80   certbot/certbot certonly --standalone -d domain1.com

./setup.sh email add user@DOMAIN2.com
docker run --rm -it   -v "${PWD}/docker-data/certbot/certs/:/etc/letsencrypt/"   -v "${PWD}/docker-data/certbot/logs/:/var/log/letsencrypt/"   -p 80:80   certbot/certbot certonly --standalone -d domain2.com

./setup.sh email add user@DOMAIN3.com
docker run --rm -it   -v "${PWD}/docker-data/certbot/certs/:/etc/letsencrypt/"   -v "${PWD}/docker-data/certbot/logs/:/var/log/letsencrypt/"   -p 80:80   certbot/certbot certonly --standalone -d domain3.com
```

```
ssl | : scheme=smtp cert=94220924939120: identity=stabio.com.br cn=imentore.com alt=2 imentore.com
-- | --
  |   | Cert Hostname DOES NOT VERIFY (stabio.com.br != imentore.com \| DNS:imentore.com)
  |   | So email is encrypted but the host is not verified
  |   | cert not revoked by OCSP

```

**Comment by casperklein** [comment]
Multiple certificates are not supported by DMS afaik.

**Comment by brenoperucchi** [comment]
I changed all domains of the MX DNS to respond with a single certificate, in my case imentore.com. Tks

**Comment by casperklein** [comment]
See my comment [here](https://github.com/docker-mailserver/docker-mailserver/issues/2995#issuecomment-1378163233).

You don't need to create certificates for each mail domain. Just one for your mailserver `imentore.com`. However I recommend to not use a bare domain for that, instead use something like `mail.imentore.com`.
