### ISSUE TITLE
SPF and DKIM when sending to Gmail

### ISSUE THREAD

**Issue by johncadengo** [docker-mailserver/docker-mailserver#2996]
I was reading through the logs when I sent out some emails during testing and saw this:

```
Jan 11 02:21:49 postfix/smtp[2755]: A16D218A1FD9: host gmail-smtp-in.l.google.com[172.253.124.27] said: 421-4.7.0 This message does not pass authentication checks (SPF and DKIM both do 421-4.7.0 not pass). SPF check for [domain.com] does not pass with ip: 421-4.7.0 [ipaddress].To best protect our users from spam, the message has 421-4.7.0 been blocked. Please visit 421-4.7.0  https://support.google.com/mail/answer/81126#authentication for more 421 4.7.0 information. g206-20020a2552d7000000b006fcc3d767efsi15421136ybb.469 - gsmtp (in reply to end of DATA command)
```

The link the message references is here: https://support.google.com/mail/answer/81126#authentication

What do I have to do to get this to work?

**Comment by raidensakura** [comment]
The docs have some guides for best practices with [SPF](https://docker-mailserver.github.io/docker-mailserver/edge/config/best-practices/spf/) and [DKIM](https://docker-mailserver.github.io/docker-mailserver/edge/config/best-practices/dkim/) keys
