### ISSUE TITLE
Abusix Configuration - user-patches

### ISSUE THREAD

**Issue by Caffe1neAdd1ct** [docker-mailserver/docker-mailserver#3003]
# Abusix Configuration

I would like to configure a not documented mail server use case

## Description

I've been using [abusix](https://abusix.com) to help reduce the amount of spam and malicious mail targeted at our mailboxes, it reduced these by around 80% without having dropping legitimate business/personal mail. 

Setup documentation for postfix:

https://docs.abusix.com/abusix-mail-intelligence/gbG8EcJ3x3fSUv8cMZLiwA/getting-started/dmw9dcwSGSNQiLTssFAnBW#postfix%E2%80%93dcxrjl

I'm looking at making a [user-patches.sh](https://github.com/docker-mailserver/docker-mailserver/blob/master/config-examples/user-patches.sh) script to implement, however may need some help as some of the configurations are on multiple lines, for example `postscreen_dnsbl_sites =`

Has anyone already implemented or have examples to amend the main.cf to implement these configs?

**Comment by Caffe1neAdd1ct** [comment]
So ignoring the `postscreen` setup and using `reject_rbl_client` instead i've ended up with something along the lines of:

```bash
#!/bin/bash

# This user patches script runs right before starting the daemons.
# That means, all the other configuration is in place, so the script
# can make final adjustments.
# If you modify any supervisord configuration, make sure to run
# "supervisorctl update" or "supervisorctl reload" afterwards.

# For more information, see
# https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/override-defaults/user-patches/


ABUSIX_API_KEY="API_KEY_HERE"
ABUSIX_RECIPIENT_RESTRICTIONS="reject_rhsbl_client $ABUSIX_API_KEY.dblack.mail.abusix.zone, reject_rhsbl_helo $ABUSIX_API_KEY.dblack.mail.abusix.zone, reject_rhsbl_sender $ABUSIX_API_KEY.dblack.mail.abusix.zone, reject_rbl_client $ABUSIX_API_KEY.combined.mail.abusix.zone"

# Introduce the Abusix restrictions after "reject_unauth_destination" and before ""
sed -i -r 's/^smtpd_recipient_restrictions(.*)/smtpd_recipient_restrictions\1, '"$ABUSIX_RECIPIENT_RESTRICTIONS"'/' main.cf

# Load rbl reply mappings to hide Abusix API keys in responses
cat >>main.cf << "END"
rbl_reply_maps = texthash:/etc/postfix/rbl_reply_map
END

# Response message rewrites
cat >>rbl_reply_map << END
${ABUSIX_API_KEY}.combined.mail.abusix.zone        \$rbl_code Service unavailable; \$rbl_class [\$rbl_what] blocked using Abusix Mail Intelligence\$\{rbl_reason?; \$rbl_reason\}
${ABUSIX_API_KEY}.dblack.mail.abusix.zone        \$rbl_code Service unavailable; \$rbl_class [\$rbl_what] blocked using Abusix Mail Intelligence\$\{rbl_reason?; \$rbl_reason\}
END

echo -e 'user-patches.sh successfully executed'
```

Not tested yet but hopefully close ...

**Comment by georglauterbach** [comment]
We can definitely put this into our documentation :D Just open a PR and we'll guide you, or ask in this issue :)

**Comment by georglauterbach** [comment]
I'll be trying out Abusix too; we can collaborate on the doc PR

**Comment by Caffe1neAdd1ct** [comment]
I've been meaning to start a PR for this just not had time, i'll see what the weekend brings :+1:

**Comment by georglauterbach** [comment]
I have a running setup now, it's pretty nice! One question: you're not integrating into Postscreen. Is there a special reason behind this? DMS uses Postscreen and I have never had a problem with it. Maybe there is a special reason though that I might be missing.

**Comment by Caffe1neAdd1ct** [comment]
Think i just found it easier with the user patch script to implement using `reject_rbl_client`, no special reason to be honest.

What would be the advantage of Postscreen over `reject_rbl_client`? just for future knowledge :)

**Comment by Caffe1neAdd1ct** [comment]
Ah ok quick read on Postscreen, these block lists could be used to effectively screen the connections preventing useless connections to the SMTP service in postfix. Yes I can definitely see an advantage to moving this configuration over to postscreen.

**Comment by georglauterbach** [comment]
I guess there are two upsides IMO, but the outcome stays more or less the same for smaller setups:

1. Postscreen handles the connection before it is given to Postfix. This allows Postscreen to reject (in case Abusix recommends it) and not bother Postfix, which should (IMO) only be an MTA (UNIX philosophy: do _one_ task right) :D
2. Postscreen's DNSBLs can be given weights, and then reject on a configurable threshold, which allows extensive configuration

**Comment by georglauterbach** [comment]
The patches script woudl only become marginally bigger too.

**Comment by Caffe1neAdd1ct** [comment]
Fully agree :+1: 

I'm slightly up against it this week, but may have some time to test / make a new patch script over the weekend :)

**Comment by georglauterbach** [comment]
Update: the Postfix/Postscreen integration is really good and we should document it. I did move away from Postfix's integration however and I am now using the Postscreen & Rspamd integration. This way, Postfix does not handle DNSBLs at all. One does not need to do it like his though, and I think that Postfix handling DNSBLs is still fine. This is just FYI.

The Rspamd integration works really nice as well. From my PoV, this is where Abusix should really live; together with Postscreen and an AV/anti-spam milter, as these programs are designed for exactly that. The ["Abusix - Getting Started"](https://docs.abusix.com/abusix-mail-intelligence/gbG8EcJ3x3fSUv8cMZLiwA/getting-started/dmw9dcwSGSNQiLTssFAnBW#rspamd) has really nice documentation for Rspamd integration.

**Comment by georglauterbach** [comment]
I maybe be able to add a section to the Rspamd documentation about Abusix. I am currently deploying Abusix with Rspamd only (since running Postscreen & Postfix at the same time did not really make sense - it's just double the API queries..). When it comes to the Postscreen docs, I hope you find the time to propose a PR :)
