### ISSUE TITLE
Unclear documentation for the description of the port 110

### ISSUE THREAD

**Issue by i-C-o-d-e-r** [docker-mailserver/docker-mailserver#3007]
# Clearification of the documentation for the description of the port 110 is necessary

I have questions/comment about the documentation for TLS/SSL/STARTTLS/OpenSSL

## Description

The documentation "Understanding the Ports" (https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/) is somehow irritating.

The note/footnote 1 under the table "Overview of Email Ports" clearly states that docker-mailserver will reject a connection on port 110 (Explicit TLS) that cannot be secured.

The section "Explicit TLS (aka Opportunistic TLS) - Opt-in Encryption" however states in the second sentence "...., otherwise no encryption will be used."

So as port 110 is configured for explicit TLS, which of the two sentences is true? It seems that the note/footnote seems to be true. But in that case the second sentence has to be changed or rephrased.

If the port 110 always rejects a connection that cannot be secured, how can I run docker-mailserver so that it supports both secured (with TLS/SSL/...) and unsecured POP3?

Thanks in advance!

**Comment by polarathene** [comment]
> The section "Explicit TLS (aka Opportunistic TLS) - Opt-in Encryption" however states in the second sentence "...., otherwise no encryption will be used."

This is describing what Explicit / Opportunistic TLS is (_using StartTLS to negotiate a secure connection from an insecure one_). It's not specific to DMS, but explains what it is in general.

> The note/footnote 1 under the table "Overview of Email Ports" clearly states that docker-mailserver will reject a connection on port 110 (Explicit TLS) that cannot be secured.

The footnote references the entire column, which is the case. Port 25 does not require authentication, so it can establish an unencrypted connection and receive mail if necessary. The other ports will begin in plain-text and attempt to establish a secure TLS connection, if they cannot do this, then they drop the connection before starting authentication with the intention that your credentials aren't sent over.

---

> If the port 110 always rejects a connection that cannot be secured, how can I run docker-mailserver so that it supports both secured (with TLS/SSL/...) and unsecured POP3?

If you want 110 to be available with StartTLS, that's what we support. Are you wanting to disable the security measure we have in place here for some reason?

**Comment by i-C-o-d-e-r** [comment]
I understand now that the section about "Explicit TLS" shall be read as not specific to DMS, but a more general explaination. From what you have stated, I can tell now that DMS does not do what is described in that section. It rejects a connection on port 110 (Explicit TLS) that cannot be secured.

My suggestion is now to make the description more clear in that respect. So explicitly emphasize that the one section is not specific to DMS, but more general and emphasize in the footnote that the behaviour is different than described in the general section about Explicit TLS as unsecured connections are rejected.

**Comment by i-C-o-d-e-r** [comment]
My other point was about my use case:

I need DMS to support SSL secured ports and unsecured ports, so that I can confirm with tests that my implementation runs with Mail-servers running SSL and Mail-servers running without SSL. How would such a configuration be possible?

**Comment by polarathene** [comment]
> How would such a configuration be possible?

I believe you can provide an empty `SSL_TYPE` (_[should be the default](https://github.com/docker-mailserver/docker-mailserver/blob/e64827e4b24188ce4947310b778fcbec64be433f/target/scripts/helpers/variables.sh#L110)_):

https://github.com/docker-mailserver/docker-mailserver/blob/e64827e4b24188ce4947310b778fcbec64be433f/target/scripts/helpers/ssl.sh#L345-L356

But that removes SSL connections entirely I think. You'd have to adjust `DOVECOT_SSL_ENABLED` value, easier with a `user-patches.sh` script to run:

```bash
#!/bin/bash
sed -i -r "s|^(ssl =).*|\1 yes|" /etc/dovecot/conf.d/10-ssl.conf
```

That should do it I think.

---

**NOTE:** AFAIK there is similar in place for port 25, where presently it does allow authentication, but this is uncommon and [there is a PR being worked on](https://github.com/docker-mailserver/docker-mailserver/pull/3006) that will change that to no longer be supported. I haven't looked into support for trying to auth on 25 or 587 without a secure connection established, but assume that there is some preventative measures in place too :sweat_smile:

**Comment by polarathene** [comment]
> My suggestion is now to make the description more clear in that respect.

We welcome contributions :+1: 

The docs do need some love as the active maintainers are often allocating time elsewhere on higher priority tasks for the project.

**Comment by i-C-o-d-e-r** [comment]
> I believe you can provide an empty SSL_TYPE
>....
> But that removes SSL connections entirely I think.

Unfortunately that is exactly the case, so this use case is not supported, but should be supported in my opinion. But anyway I worked around this problem by running two instances of docker-mailserver. One with SSL and one without SSL. It is not as convenient, but possible.

@polarathene Thank you for you support!

**Comment by i-C-o-d-e-r** [comment]
> We welcome contributions

My intention was to make sure that we agree on the topic, before I create a PR for the docs. I guess it is clear now. I try to create a PR within the next days. I will refer to this ticket, so I keep this issue open until then.

**Comment by polarathene** [comment]
> Unfortunately that is exactly the case, so this use case is not supported, but should be supported in my opinion.

It's not something we would support unless there was sufficient demand from users for it. Your justification is to test your software against a configuration that is not advisable in production services to be deployed with.

Similarly, you may argue that you want to test against earlier versions of TLS that we no longer support, or certain cipher-suites that are no longer deemed appropriate but are likely offered by some outdated deployed services?

These are too niche and small changes for us to maintain, and for that we defer our users to `user-patches.sh` to apply the configuration changes on your end. Should there be sufficient interest from users to warrant it, then we'd consider a PR to add the feature.

---

> My intention was to make sure that we agree on the topic, before I create a PR for the docs.

All good, totally understand that :+1: 

If you can improve the docs to be more clear on the topic that'd be fantastic :grin:
