### ISSUE TITLE
restoring from backup

### ISSUE THREAD

**Issue by s0ftcorn** [docker-mailserver/docker-mailserver#3023]
i accidentally deleted the directory containing:
- docker-compose.yml
- mailserver.env
- config/*
- etc/*

Basically a classic "rm -rf *"-NOOOO!-moment.
While i had luck restoring the files, the server cant receive mails. Outgoing is fine, internal is fine, but incoming... nothing.
In the logs there is only:

`[ WARNING ] User user@domain.tld will not be added to '/etc/postfix/vmailbox' twice`

And i had to create a new user when starting the container again. Did i miss a step in restoring? Thought i could just place the files where they were, regenerate/renew certs for DKIM and SSL and be fine.

**Comment by polarathene** [comment]
Your users should be stored in a `postfix-accounts.cf` file. If the user is not duplicated, and you don't need Dovecot Quota support, perhaps try disabling that. I think a workaround for that feature creates dummy accounts for any aliases a user may have. Might be related to the issue you're experiencing.

**Comment by s0ftcorn** [comment]
I had ONE_DIR=0 enabled at the first startup of the container, changed it before creating a "first" user. Via DOVECOT_QUOTAS=0 i disabled dovecot qutoas, but the warning persists. Im a bit anxious that my reimport has unforeseen side-effects that the warning is trying to tell me.

The issue with receiving mails was related to UFW and my config for using roundcube with a local mysql database, resolved through: [enabled at the first startup of the container, changed it immediatly after.](https://github.com/chaifeng/ufw-docker)

**Comment by polarathene** [comment]
> Im a bit anxious that my reimport has unforeseen side-effects that the warning is trying to tell me.

The warning is from our startup scripts:

https://github.com/docker-mailserver/docker-mailserver/blob/7eeb9c33ab46c66251147bb652cc7f70f47d11cb/target/scripts/helpers/accounts.sh#L70-L76

It is reading your `postfix-accounts.cf` file for users and adding them into that vmailbox file. When doing that it found there was a user that had already been added. So it's likely to do with what you have there. If you don't have many users in it, you could probably make a backup copy, then just remove a user each time (or remove half each time), to try narrow it down to what the extra user is that triggers it, and see if you can find the first one as well that conflicts?
