### ISSUE TITLE
Why does the default docker-compose.yml require NET_ADMIN capability?

### ISSUE THREAD

**Issue by chtpl** [docker-mailserver/docker-mailserver#3024]
# Subject

I would like some feedback concerning a use case

## Description

I want to use the service as a test target for integration testing of a web application that will be sending mails.
However, I want to give as little permissions to 3rd Party code as possible on my machine.

Is there aw way to configure it so that it does not need NET_ADMIN?

**Comment by georglauterbach** [comment]
If you don't need Fail2Ban, I think you can omit this capability.

**Comment by chtpl** [comment]
thanks for the hint :)

but unfortunately, I have chosen nodemailers "smtp-server" library to test my application.
It is way more suitable for my usecase as I also might need to access the received data in an integration test for a NestJS application.

**Comment by georglauterbach** [comment]
Alright :) I will then go ahead and close this PR.
