### ISSUE TITLE
Is there a way / feature to add automatic signatures?

### ISSUE THREAD

**Issue by Laurenz1606** [docker-mailserver/docker-mailserver#3044]
Is there a way / feature to add automatic signatures?

I would like to configure a not documented mail server use case

## Description
I was wondering if there is a method to add a signature to every email sent via the docker-mailserver. I know there are tools for postfix, but how would i integrate them with docker-mailserver? is there a way to do this?

**Comment by georglauterbach** [comment]
What kind of signature? One for identifying an email, or one that can be used for authentication? You can use DKIM, GPG, S/MIME? DMS does ship with a proper DKIM integration, you will just need to [set it up](https://docker-mailserver.github.io/docker-mailserver/edge/config/best-practices/dkim/).

GPP & S/MIME are independent of the underlying MTA AFAIK. Just use the search engine you trust the most and find out more.

**Comment by polarathene** [comment]
> What kind of signature?

Beyond digital signatures like that, they may also want to append static content after a message.

You might be familiar with apps that would do similar such as "Sent by app-name on phone model", forum signatures, or legal notice in corporate emails.

**Comment by Laurenz1606** [comment]
Yeah my bad, sorry for not giving enough details xD I Would like to append a small text to all my messages like a legal notice. Thanks for the help @polarathene

**Comment by Laurenz1606** [comment]
> "Sent by app-name on phone model"

I think these are just a thing that the MTA-APP adds to their Input fields, but i recently was working at a company where my name was added with a small legal notice to every email i was sending.

**Comment by Laurenz1606** [comment]
https://www.dokuwiki.tachtler.net/doku.php?id=tachtler:postfix_altermime_installieren

There is something that is called alterMIME, but i don't know how i would integrate this with DMS.

**Comment by georglauterbach** [comment]
I see; I don't have experience with this though. [This](https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/override-defaults/user-patches/) might be interesting for you though.

**Comment by Laurenz1606** [comment]
How would i modify my amavis with the `user-patches.sh`? U see in the link i provided that alterMIME could be interated into amavis or postfix directly. I would prefer amavis but how would i edit the amavis configuration? Would i need to do some regex magic to change config values? And could i simply run `apt install` scripts via the `user-patches.sh`?

**Comment by georglauterbach** [comment]
You can simply run `apt`, but make sure you run `apt update` in the beginning. And you probably want to use `apt-get` instead of `apt`.

What you need to do for Amavis/Postfix integration I cannot tell; the issue tracker is not for personal support, and this request falls under the category personal support. I do think that Google & Co. will be of better help here than I would. If someone else wants to chime in though, I have absolutely no objections.

**Comment by Laurenz1606** [comment]
No problem at all, my general question was just if I could directly modify the config files, and which file of amavis I would need to modify because they are splitted into multiple config files and in the alterMIME guide they are all in on file. Should I search through all config files and replace the values at the certain places or could I just add all of the changes to the amavis `50-user`?

**Comment by polarathene** [comment]
I don't know if any of the active maintainers have much experience working with Amavis. We mostly focus on keeping the project healthy and updated, responding to bug reports and reviewing contributions (features, fixes, docs).

`user-patches.sh` is the right approach usually when you need to carry your own changes, and is much easier than contributing a feature which usually requires adding documentation + tests to get accepted, plus you don't have to wait on a new release.

You'll mostly have to pay attention the guides you find, and look at whatever amavis configs we have to find the equivalent / appropriate files to update (or add).

---

Alternatively, if you're not invested into our project right now, you might want to check out other options like Mailu or mailcow. Neither use Amavis, and I'm not sure if they do offer such a feature, but they might? :) (_if not, we are probably one of the easier projects to add your own customizations I think_)

**Comment by Laurenz1606** [comment]
> I don't know if any of the active maintainers have much experience working with Amavis. We mostly focus on keeping the project healthy and updated, responding to bug reports and reviewing contributions (features, fixes, docs).
> 
> `user-patches.sh` is the right approach usually when you need to carry your own changes, and is much easier than contributing a feature which usually requires adding documentation + tests to get accepted, plus you don't have to wait on a new release.
> 
> You'll mostly have to pay attention the guides you find, and look at whatever amavis configs we have to find the equivalent / appropriate files to update (or add).
> 
> Alternatively, if you're not invested into our project right now, you might want to check out other options like Mailu or mailcow. Neither use Amavis, and I'm not sure if they do offer such a feature, but they might? :) (_if not, we are probably one of the easier projects to add your own customizations I think_)

Thanks for your answer :D I've tested it and it works like it should but with mail disclaimers there is a whole new rabbit hole to place them at the right part of an E-Mail.

Thanks for all of your help!
