### ISSUE TITLE
i need just send in noreply account

### ISSUE THREAD

**Issue by vahidalvandi** [docker-mailserver/docker-mailserver#3054]
hi i want to have multi account like info@me.com and **noreply@me.com** . but i want **noreply@me.com** Don't receive an email, just be the sender

**Comment by georglauterbach** [comment]
We have a [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/). Use it.

**The issue tracker is not for personal support!**

**Comment by vahidalvandi** [comment]
where is it ?

**Comment by georglauterbach** [comment]
> where is it ?

You can literally click on the link in my previous comment (blue).
