### ISSUE TITLE
Mailclients cannot connect on port 25 ony on 587 submission

### ISSUE THREAD

**Issue by di-rect** [docker-mailserver/docker-mailserver#3056]
I found out that the mailclients, so not mailrelays, are only able to connect on port 587.

Why is this happening and can it be changed so TLS/SSL just works on port 25 for mailclients ?

**Comment by polarathene** [comment]
File a proper bug report with config and logs please.

**Comment by di-rect** [comment]
> File a proper bug report with config and logs please.

I would like to, but with which loglevel should be right and what to filter for ?

**Comment by polarathene** [comment]
You can use this snippet to properly format your container logs (_via `docker logs <container name>`, or logs directly output to the terminal_):

````markdown
<details>
<summary>Docker Logs</summary>

```
# Replace this line with your logs copy/paste
```

</details>
````

`-env LOG_LEVEL='trace'` will provide maximum verbosity, usually `debug` is enough and `trace` is rarely more helpful.

With the above snippet you can just provide the full log output. It'd be good to start the container and then try send a mail on both ports from your mail client. You should see a success with port 587, and some failure with port 25 if all goes well based on your description. If not, your `docker-compose.yml` or environment like host OS/distro might tell us more.

**Comment by georglauterbach** [comment]
Please also check whether port 25 is not blocked by anyone!
