### ISSUE TITLE
Mailserver behind Traefik or direct ports exposed mailserver

### ISSUE THREAD

**Issue by di-rect** [docker-mailserver/docker-mailserver#3063]
In reference to topic: https://github.com/docker-mailserver/docker-mailserver/issues/3056 I'm still investigating what is best way to run docker-mailserver.

As I see a lot of people having issues with docker-mailserver behind Traefik I ask myself; why ?

Can anyone confirm a working environment with all changes that has been made to Traefik, mailserver compose and overridden configfiles of postfix/dovecot ?

Maybe it can convince me to not to go back to direct exposed ports and having a whoami container for the certificate.

Thanks!

**Comment by polarathene** [comment]
> As I see a lot of people having issues with docker-mailserver behind Traefik I ask myself; why ?

It would be good to link those as references.

> Can anyone confirm a working environment with all changes that has been made to Traefik, mailserver compose and overridden configfiles of postfix/dovecot ?

I know of @wernerfred having used Traefik successfully with DMS. If you search for issues with his comments and the keyword "Traefik" you'll probably find some `docker-compose.yml` configs shared by him :+1: 

---

Our tests are getting heavily refactored presently, and hopefully will go through another pass switching them over to use `docker compose`. Once that is done, we could probably throw in some tests with setups like Traefik or alternatively maintain a folder (or docs page) with example configs like this.

> Maybe it can convince me to not to go back to direct exposed ports and having a whoami container for the certificate.

Is there an issue with exposing the ports without a reverse-proxy? Usually a reverse-proxy is helpful for when services would overlap ports used, and I think is common to delegate for cert management.

**Comment by georglauterbach** [comment]
I am running Traefik next to DMS for other services. Traefik is really nice (even though [it has become worse](https://github.com/traefik/traefik/issues/9108)..) and I cannot complain.

I have not put DMS behind Traefik though. The reason is that it would introduce another moving part into the system where it is not really needed. As @polarathene mentioned, ports do not overlap here either. And it introduces the issue of DMS not seeing the real origin IPs without a bit of effort. As mail servers can be rather complex, if you don't see any gains for you specifically uising Traefik, I'd not put it in front of DMS.

**Comment by wernerfred** [comment]
It's been a while but i wrote down basically 1:1 my configuration in the docs: https://docker-mailserver.github.io/docker-mailserver/edge/examples/tutorials/mailserver-behind-proxy/

That config is unchanged since then and DMS still up and running 😄 🚀 

> if you don't see any gains for you specifically uising Traefik

In my case: only one system internet facing + being able to have one dashboard so see each service/route on the network including adding all configs directly on the service (especially for certs - no need of whoami containers) and a few more (taking learning into account as well)

**Comment by di-rect** [comment]
@mschoeffel Super thanks for this example, it looks good but in some way I don't seem to be able to connect on IMAP and my connectime for SMTP is very slow. 

Do you have an idea maybe ?

**Comment by TheKving** [comment]
> @mschoeffel Super thanks for this example, it looks good but in some way I don't seem to be able to connect on IMAP and my connectime for SMTP is very slow.
> 
> ~/edit: I don't see the TCP routers in the dashboard to begin with.~
> 
> I get the following on SMTP connection when I want to send and email:
> 
> > mailserver    | Apr 14 01:46:54 mail postfix/smtps/smtpd[706]: disconnect from traefik_traefik_1.traefik_internal[10.0.5.200] commands=0/0
> > mailserver    | Apr 14 01:49:40 mail postfix/smtps/smtpd[1002]: connect from traefik_traefik_1.traefik_internal[10.0.5.203]
> > mailserver    | Apr 14 01:49:40 mail postfix/smtps/smtpd[1002]: SSL_accept error from traefik_traefik_1.traefik_internal[10.0.5.203]: -1
> > mailserver    | Apr 14 01:49:40 mail postfix/smtps/smtpd[1002]: warning: TLS library problem: error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:331:
> > mailserver    | Apr 14 01:49:40 mail postfix/smtps/smtpd[1002]: lost connection after CONNECT from traefik_traefik_1.traefik_internal[10.0.5.203]
> > mailserver    | Apr 14 01:49:40 mail postfix/smtps/smtpd[1002]: disconnect from traefik_traefik_1.traefik_internal[10.0.5.203] commands=0/0
> 
> With IMAP I actually can't do anything and also if I interact I don't see anything in the logs but my client says "lower down your cached connections".
> 
> Do you have an idea maybe ?

I'm the same way, I can't find a way to use IMAP through Traefik, but I can send mail immediately through another container that uses SMTP.

**Comment by di-rect** [comment]
@TheKving I just tried the example of @mschoeffel plain as it comes; doesn't work, same error.

**Comment by di-rect** [comment]
It actually should work as expected by @mschoeffel. Closing this for now.

**Comment by di-rect** [comment]
@mschoeffel I get slow connectiontimes on SMTP (also with Swarm) and the following error on 465/SSL:

`Jul 12 17:04:44 mail postfix/smtps/smtpd[11996]: warning: TLS library problem: error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:331:`

Any idea what could go wrong here?

**Comment by mich2k** [comment]
I followed all the steps but yet not manage to make this work
as proxy IP I put the trafik container's (with a wide cidr, should be /16)

and having these kind of errors
```
(base) mich@sbserver:~$ docker logs mailserver 
[   INF   ]  Welcome to docker-mailserver 12.1.0
[   INF   ]  Checking configuration
[   INF   ]  Configuring mail server
[   INF   ]  Starting daemons
[   INF   ]  mail.domain.com is up and running
Sep 16 21:19:47 mail dovecot: imap-login: Disconnected: Connection closed: SSL_accept() failed: error:1408F10B:SSL routines:ssl3_get_record:wrong version number (disconnected before auth was ready, waited 0 secs): user=<>, rip=my_public_ip, lip=172.25.0.2, TLS handshaking: SSL_accept() failed: error:1408F10B:SSL routines:ssl3_get_record:wrong version number, session=<VA/Syn4FJMEFkL2y>

Sep 16 21:19:47 mail dovecot: imap-login: Disconnected: Connection closed: SSL_accept() failed: error:1408F10B:SSL routines:ssl3_get_record:wrong version number (no auth attempts in 0 secs): user=<>, rip=my_public_ip, lip=172.25.0.2, TLS handshaking: SSL_accept() failed: error:1408F10B:SSL routines:ssl3_get_record:wrong version number, session=<YcfWyn4FJ8EFkL2y>

Sep 16 21:19:47 mail dovecot: imap-login: Disconnected: Connection closed: SSL_accept() failed: error:1408F10B:SSL routines:ssl3_get_record:wrong version number (no auth attempts in 0 secs): user=<>, rip=my_public_ip, lip=172.25.0.2, TLS handshaking: SSL_accept() failed: error:1408F10B:SSL routines:ssl3_get_record:wrong version number, session=<r5rXyn4FKMEFkL2y>
```

Am I doing something wrong?
I also got this other kind of errors

```
Sep 16 21:15:05 mail postfix/submission/smtpd[768]: warning: haproxy read: timeout error
Sep 16 21:15:05 mail postfix/submission/smtpd[768]: connect from unknown[172.25.0.1]
Sep 16 21:15:05 mail postfix/submission/smtpd[768]: disconnect from unknown[172.25.0.1] commands=0/0
Sep 16 21:15:11 mail postfix/submission/smtpd[768]: warning: haproxy read: timeout error
Sep 16 21:15:11 mail postfix/submission/smtpd[768]: connect from unknown[172.25.0.1]
Sep 16 21:15:11 mail postfix/submission/smtpd[768]: disconnect from unknown[172.25.0.1] commands=0/0
```

This is the traefik compose

``` 
mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    restart: always
    container_name: mailserver

    hostname: mail.domain.com
    env_file: mailserver.env

    volumes:
      - ${DOCKER_VOLUMES_FOLDER}/dms/mail-data/:/var/mail/
      - ${DOCKER_VOLUMES_FOLDER}/dms/mail-state/:/var/mail-state/
      - ${DOCKER_VOLUMES_FOLDER}/dms/mail-logs/:/var/log/mail/
      - ${DOCKER_VOLUMES_FOLDER}/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_VOLUMES_FOLDER}/traefik/acme.json:/etc/letsencrypt/acme.json:ro # /live:ro

    cap_add:
      - NET_ADMIN # For Fail2Ban to work
    stop_grace_period: 1m
    environment:
      - SSL_TYPE=letsencrypt
      - SSL_DOMAIN=gmichele.com  # wildcard hence is not needed mail.gmichele.com

    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0

    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.smtp.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.smtp.entrypoints=smtp"
      - "traefik.tcp.routers.smtp.service=smtp"
      - "traefik.tcp.services.smtp.loadbalancer.server.port=25"
      - "traefik.tcp.services.smtp.loadbalancer.proxyProtocol.version=1"
      - "traefik.tcp.routers.smtp-ssl.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.smtp-ssl.tls=false"
      - "traefik.tcp.routers.smtp-ssl.entrypoints=smtp-ssl"
      - "traefik.tcp.routers.smtp-ssl.service=smtp-ssl"
      - "traefik.tcp.services.smtp-ssl.loadbalancer.server.port=465"
      - "traefik.tcp.services.smtp-ssl.loadbalancer.proxyProtocol.version=1"
      - "traefik.tcp.routers.imap-ssl.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.imap-ssl.entrypoints=imap-ssl"
      - "traefik.tcp.routers.imap-ssl.service=imap-ssl"
      - "traefik.tcp.services.imap-ssl.loadbalancer.server.port=10993"
      - "traefik.tcp.services.imap-ssl.loadbalancer.proxyProtocol.version=2"
      - "traefik.tcp.routers.sieve.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.sieve.entrypoints=sieve"
      - "traefik.tcp.routers.sieve.service=sieve"
      - "traefik.tcp.services.sieve.loadbalancer.server.port=4190"
    
    networks:
      proxy:
        ipv4_address: 172.25.0.12```


![immagine](https://github.com/docker-mailserver/docker-mailserver/assets/13397578/b6dc31a8-623d-485c-8b50-6e28f66c309c)

**Comment by dolanor** [comment]
> I have not put DMS behind Traefik though. The reason is that it would introduce another moving part into the system where it is not really needed. As @polarathene mentioned, ports do not overlap here either. And it introduces the issue of DMS not seeing the real origin IPs without a bit of effort. As mail servers can be rather complex, if you don't see any gains for you specifically uising Traefik, I'd not put it in front of DMS.

You make good point about DMS not seeing the real origin IP. I don't believe there is a way to transmit that the way HTTP has Origin-*.
I guess I'll follow your advice and keep DMS on the front, but let traefik deal with the LE certificates.

**Comment by polarathene** [comment]
> You make good point about DMS not seeing the real origin IP. I don't believe there is a way to transmit that the way HTTP has Origin-*.

When v14 is published the docs for this will be these current edge docs: https://docker-mailserver.github.io/docker-mailserver/edge/examples/tutorials/mailserver-behind-proxy/

If you want to preserve the IP you need to use PROXY protocol with Traefik for TCP routed traffic and configure DMS to accept that as covered in the docs page.

It is added complexity though, you still need Postfix and Dovecot to handle the TLS verification IIRC, thus you're not gaining much benefit when both services run on the same machine and don't have routing concerns to address.

---

Closing as this has since been addressed and verified with the new docs rewrite 👍
