### ISSUE TITLE
SSL configuration

### ISSUE THREAD

**Issue by ckvist72** [docker-mailserver/docker-mailserver#3086]
Configuration warning that i can not understand.

I have questions about TLS/SSL/STARTTLS/OpenSSL

## Description

[ WARNING ]  !! INSECURE !! SSL configured with plain text access - DO NOT USE FOR PRODUCTION DEPLOYMENT

i keep getting this. But i can not figure out why. - I can not seem to find a solution in the manual. :-(

**Comment by georglauterbach** [comment]
<https://docker-mailserver.github.io/docker-mailserver/edge/config/environment/#ssl_type>
