### ISSUE TITLE
how i can active Extension Delimiters for a address ?

### ISSUE THREAD

**Issue by vahidalvandi** [docker-mailserver/docker-mailserver#3088]
hi , i want to send any prefix before + to info like bellow
123+info@site.com
323+info@site.com
You mentioned Extension Delimiters in the documentation, but I don't know how to activate it

**Comment by fab-kaz** [comment]
Hello,

you mean info+123@site.com ?

it works out of the box i think.

f.

**Comment by vahidalvandi** [comment]
thank you work fine
