### ISSUE TITLE
[BUG] extended parameters not parsed main.cf

### ISSUE THREAD

**Issue by hanscees** [docker-mailserver/docker-mailserver#3090]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

cant add mynetworks by using extended parameters

### What happened and when does this occur?

Mailserver refuses my email form 192.168.0.x address. 
This is because I cant add such networks in the environment
so after reading 
https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/override-defaults/postfix/

I have created a file on the host in the docker dir /root/containers/mailserver like so
```

root@mail [ ~/containers/mailserver ]# ls -all docker-data/dms/config/
total 16
drwxr-xr-x 2 root root 4096 Feb 14 21:42 .
drwxr-xr-x 3 root root 4096 Feb  7 22:27 ..
-rw-r--r-- 1 root root  143 Feb  7 22:27 postfix-accounts.cf
-rwxrwxrwx 1 root root   69 Feb 14 21:42 postfix-main.cf
root@mail [ ~/containers/mailserver ]# cat docker-data/dms/config/postfix-main.cf 
mynetworks = 127.0.0.0/8  192.168.0.0/24 172.26.0.2/32 172.18.0.2/32
```
 
I hope this is what the documentation means since it does not say if you should create these files inside of outside of the container

When I stop and start the container
docker-compose stop
docker-compose start

nothing happens and the networks do not end up in the container.

```
root@mail [ ~/containers/mailserver ]# docker exec -it mailserver cat /etc/postfix/main.cf| grep mynet
mynetworks = 
smtpd_helo_restrictions = permit_mynetworks, reject_invalid_helo_hostname, permit
```

### What did you expect to happen?

I expected mynetworks to be adjusted as the docs promis

### How do we replicate the issue?

1.
2.
3.
...

### DMS version

v11.3.1 

### What operating system is DMS running on?

Linux

### Which operating system version?

photon 4

### What instruction set architecture is DMS running on?

AMD64 / x86_64

### What container orchestration tool are you using?

Docker

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [X] I am rather experienced with docker
- [ ] I am inexperienced with mail servers
- [X] I am rather experienced with mail servers
- [ ] I am uncomfortable with the CLI
- [X] I am rather comfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by georglauterbach** [comment]
We use `docker-data/dms/config/` in the docs to refer to the host path which is mounted into the container at `/tmp/docker-mailserver/`, so `postfix-main.cf` should be at `/tmp/docker-mailserver/postfix-main.cf` in the container.

Additionally, please always use `docker compose down` and `docker compose up`, not `docker compose stop / start` (also noted in the README and I hope it's somewhere in the docs).

**Comment by polarathene** [comment]
Order of updating `mynetworks` and then overriding `main.cf` with `postfix-main.cf` afterwards is correct:

<details>
<summary>References to start-up scripts</summary>

https://github.com/docker-mailserver/docker-mailserver/blob/16f46c1e1465212b7bd648c9690896cdf6c9a2e8/target/scripts/start-mailserver.sh#L108

https://github.com/docker-mailserver/docker-mailserver/blob/16f46c1e1465212b7bd648c9690896cdf6c9a2e8/target/scripts/start-mailserver.sh#L143

https://github.com/docker-mailserver/docker-mailserver/blob/16f46c1e1465212b7bd648c9690896cdf6c9a2e8/target/scripts/startup/setup-stack.sh#L719-L792

https://github.com/docker-mailserver/docker-mailserver/blob/16f46c1e1465212b7bd648c9690896cdf6c9a2e8/target/scripts/startup/setup-stack.sh#L801-L807

</details>

---

This works perfectly fine:

```console
# Add config:
$ mkdir -p /tmp/dms
$ echo 'mynetworks = 192.168.0.42' >> /tmp/dms/postfix-main.cf

# Run container (SMTP_ONLY=1 used here to skip account creation check):
$ docker run --rm -itd --volume 'tmp/dms:/tmp/docker-mailserver' --env SMTP_ONLY=1 --hostname example.test --name dms-test mailserver/docker-mailserver

# Query setting from Postfix main.cf
$ docker exec -it dms-test postconf mynetworks

mynetworks = 192.168.0.42
```

Chances are your stop/start of the container is giving unexpected behaviour (_due to all the startup scripts, you should always create a new container instance, avoiding persisting internal state so that it's always deterministic upon startup_).

**Comment by hanscees** [comment]
You can close tickets all you want but ity does not work in edge:

the file is not copied into the container.

```
docker exec -it mailserver sh
cd /tmp	
# ls
docker-mailserver  docker-mailserver-config-chksum  ssl
# ls do*
docker-mailserver-config-chksum

docker-mailserver:
postfix-accounts.cf  postfix-virtual.cf

# exit
root@mail [ ~/containers/mailserver ]# pwd
/root/containers/mailserver
root@mail [ ~/containers/mailserver ]# ls
docker-compose.yml  docker-data  mailserver.env  setup.sh  surbl-whitelist.inc.zst
root@mail [ ~/containers/mailserver ]# ls docker-data/dms/
config
root@mail [ ~/containers/mailserver ]# ls docker-data/dms/config/
postfix-accounts.cf  postfix-main.cf
root@mail [ ~/containers/mailserver ]# 
```

**Comment by georglauterbach** [comment]
_You_ have to place the file into the directory that _you_ then mount into the container at `/tmp/docker-mailserver`.

I tested it too; it does work.

**Comment by hanscees** [comment]
yes, you are right. Staring too long in the wrong place. 
sorry
