### ISSUE TITLE
User change their own password

### ISSUE THREAD

**Issue by ckvist72** [docker-mailserver/docker-mailserver#3092]
It would be noce fora way for the users to change their own password

Other

I have this up and running. And it is LOVELY. THANKS so much.

I have setup a RoundCube docker for webmail. And It works fine. But i have no idea, how to make it possible to change password.
I looked at something like the roundcube password plugin, and dovecot_passwordfile. But that would then be the postfix-accounts.cf ... That is ofcourse locked by this container.
I even tryed it with shared volume, but ofcourse the file was still locked.

Is there another snart way of doing the password change?

**Comment by georglauterbach** [comment]
You cannot currently easily do that. There is an effort though: <https://github.com/docker-mailserver/docker-mailserver-admin>. I cannot say what the current status of this project is though..

**Comment by HadrienVerrier** [comment]
I've build a little plugin for Cockpit Project Dashboard to manage email (create, delete, list), i'll share it on my git if someone is interessted. I'll update with create alias and set password too.

**Comment by jarredkenny** [comment]
> I've build a little plugin for Cockpit Project Dashboard to manage email (create, delete, list), i'll share it on my git if someone is interessted. I'll update with create alias and set password too.

Very interested!

**Comment by HadrienVerrier** [comment]
> > I've build a little plugin for Cockpit Project Dashboard to manage email (create, delete, list), i'll share it on my git if someone is interessted. I'll update with create alias and set password too.
> 
> Very interested!

I'll make the necessary to make it public soon !
