### ISSUE TITLE
[BUG] edge when using custom letsencrypt chain has tls error blocking client email access

### ISSUE THREAD

**Issue by hanscees** [docker-mailserver/docker-mailserver#3095]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

tls doesnt work properly

### What happened and when does this occur?

I am using custom tls certificates and keys from another host that gets many letsencrypt certificates at once. 

 so like this in docker-compose.yml

```
    volumes:
      - etc:/etc
      - maildata:/var/mail/
      - mailstate:/var/mail-state/
      - log:/var/log/
      - Tconfig:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - ssl:/tmp/ssl
    restart: always
    stop_grace_period: 1m
    environment:
     # If you need SSL connection, you can provide your own certificates
     - SSL_TYPE=manual
     - SSL_CERT_PATH=/tmp/ssl/fullchain.pem
     - SSL_KEY_PATH=/tmp/ssl/privkey.pem
```

This leads to this error: 

```
Feb 16 21:13:22 mail dovecot: imap-login: Login: user=<hanscees@fanscees.com>, method=PLAIN, rip=192.168.0.21, lip=172.20.0.2, mpid=5801, TLS, session=<mdQa1Nb0xqPAqAAC>
Feb 16 21:14:52 mail postfix/smtps/smtpd[6006]: warning: key at index 1 in /etc/dms/tls/fallback_key does not match next certificate
Feb 16 21:14:52 mail postfix/smtps/smtpd[6006]: warning: TLS library problem: error:1426D121:SSL routines:ssl_set_cert_and_key:not replacing certificate:../ssl/ssl_rsa.c:1081:
Feb 16 21:14:52 mail postfix/smtps/smtpd[6006]: warning: error loading private keys and certificates from: /etc/dms/tls/key /etc/dms/tls/cert /etc/dms/tls/fallback_key /etc/dms/tls/fallback_cert: disabling TLS support
Feb 16 21:14:52 mail postfix/smtps/smtpd[6006]: connect from unknown[192.168.0.21]
Feb 16 21:14:52 mail postfix/smtps/smtpd[6006]: warning: Wrapper-mode request dropped from unknown[192.168.0.21] for service smtps. TLS context initialization failed. For details see earlier warnings in your logs.
```

I have solved this by changing the tls-chains line in main.cf like so:
```

vi /var/lib/docker/volumes/mailserver_Tconfig/_data/postfix-main.cf
smtpd_tls_chain_files = /etc/dms/tls/key /etc/dms/tls/cert  
```

Now tls works again. 
Discovered this because dkim didnt work, what apparently was caused by this issue

### What did you expect to happen?

I expect my email client to be able to sent emails info the server.

### How do we replicate the issue?

see above. 
feed the config some custom letsencrypt certificates.

### DMS version

v11.3.1 

### What operating system is DMS running on?

Linux

### Which operating system version?

vmware photon 4

### What instruction set architecture is DMS running on?

AMD64 / x86_64

### What container orchestration tool are you using?

Docker

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [X] I am rather experienced with docker
- [ ] I am inexperienced with mail servers
- [X] I am rather experienced with mail servers
- [ ] I am uncomfortable with the CLI
- [X] I am rather comfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by georglauterbach** [comment]
@polarathene an idea what could be causing the scripts to think there is a fallback cert/key?

**Comment by hanscees** [comment]
> @polarathene an idea what could be causing the scripts to think there is a fallback cert/key?
> 
> @hanscees plesse show use the complete startup log with `LOG_LEVEL=trace`

One of your scripts just copies the letsencrypt files twice. This causes there to be two identical keys and certs, with just different names. so /etc/dms/tls/key is identical to /etc/dms/tls/fallback_key

and /etc/dms/tls/cert is identical to /etc/dms/tls/fallback_cert

But the config like this is probably just wrong:

smtpd_tls_chain_files = /etc/dms/tls/key /etc/dms/tls/cert /etc/dms/tls/fallback_key /etc/dms/tls/fallback_cert

**Comment by georglauterbach** [comment]
I'm running `SSL_TYPE=manual` as well, but with proper fallback certs, and all is well for me. So I'm wondering why not using fallback certs would cause this issue.

**Comment by georglauterbach** [comment]
We really need the startup log with log level trace though. I looked at the scripts, and there is nothing that leads me to believe they are faulty at the moment.

**Comment by hanscees** [comment]
> @polarathene an idea what could be causing the scripts to think there is a fallback cert/key?
> 
> @hanscees plesse show use the complete startup log with `LOG_LEVEL=trace`

How can I pick up that logfile easily? Is it written some place? I have been copy=pasting, but thats cumbersome

**Comment by hanscees** [comment]
> We really need the startup log with log level trace though. I looked at the scripts, and there is nothing that leads me to believe they are faulty at the moment.
> 
> > One of your scripts just copies the letsencrypt files twice.
> 
> That would be very much new to me; and I have touched almost every single line of code in our scripts for this project. Unless you show me where exactly that is happening, I'd not expect this to be the case.
> 
> Is very much more likely that `SSL_ALT_KEY_PATH` and `SSL_ALT_CERT_PATH` are set. You did not provide the whole environment or the log as the template suggested you to do. Hence we have to guess right now. Please update!

you are right these are set:

SSL_ALT_CERT_PATH=/tmp/ssl/fullchain.pem
SSL_ALT_KEY_PATH=/tmp/ssl/privkey.pem

does that explain all?

**Comment by georglauterbach** [comment]
> you are right these are set:
> 
> SSL_ALT_CERT_PATH=/tmp/ssl/fullchain.pem SSL_ALT_KEY_PATH=/tmp/ssl/privkey.pem
> 
> does that explain all?

Yes, yes indeed. Just don't set them. If you set them, DMS will try to use them as fallbacks, which exactly explains your behavior. These are only needed if you want to use _different_ certificates as a fallback (e.g., you use ECDSA certs and RSA as fallbacks).

**Comment by hanscees** [comment]
I think you can close this one.
