### ISSUE TITLE
[BUG] Submitting/Receiving a mail on port 25 generates warning when SPOOF_PROTECTION=1 is set

### ISSUE THREAD

**Issue by casperklein** [docker-mailserver/docker-mailserver#3117]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

postfix

### What happened and when does this occur?

~~With `SPOOF_PROTECTION=1`, the following warning appears in `mail.log` when an email is send:~~
The following warning is shown, when submitting or receiving an email on port 25 and `SPOOF_PROTECTION=1` is set.

```Feb 25 22:47:39 mail postfix/smtpd[4800]: warning: restriction `reject_authenticated_sender_login_mismatch' ignored: no SASL support```

---

`reject_authenticated_sender_login_mismatch` is added here:

https://github.com/docker-mailserver/docker-mailserver/blob/ae05e6a7c379825fb464a648acc04b4074dd547f/target/scripts/startup/setup-stack.sh#L486-L491

### What did you expect to happen?

No warning.

### How do we replicate the issue?

1. Send or receive an unauthenticated email
2.
3.
...

### DMS version

edge

### What operating system is DMS running on?

Linux

### Which operating system version?

Debian 11

### What instruction set architecture is DMS running on?

AMD64 / x86_64

### What container orchestration tool are you using?

Docker

### Other relevant information

I think this is a regression introduced with https://github.com/docker-mailserver/docker-mailserver/pull/3006

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [X] I am rather experienced with docker
- [ ] I am inexperienced with mail servers
- [X] I am rather experienced with mail servers
- [ ] I am uncomfortable with the CLI
- [X] I am rather comfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by georglauterbach** [comment]
I saw this a while ago; since I'm running a custom `main.cf` I didn't care.

I read this: <https://unix.stackexchange.com/questions/491033/warning-in-the-logs-of-postfix-restriction-nnn-ignored-no-sasl-support-but>.

Hence, I think we should not add it to `main.cf` where it applies to everything, but to `master.cf` for submission and smtps.

**Comment by polarathene** [comment]
> Feb 25 22:47:39 mail postfix/smtpd[4800]: warning: restriction `reject_authenticated_sender_login_mismatch' ignored: no SASL support

Is this due to the [recent change to by default disable SASL support](https://github.com/docker-mailserver/docker-mailserver/pull/3006) so you cannot use it on Port 25? Instead only allowing the submission ports we opt-in via `master.cf`?

If so, I share the upstream Debian default `master.cf` in [a collapsed details section in this PR](https://github.com/docker-mailserver/docker-mailserver/pull/3033). You would find similar advice in Alpine or official Postfix upstream example config IIRC, where they mention configuring some settings in `main.cf` so services in `master.cf` can reference different settings from default:

```
-o smtpd_sender_restrictions=$mua_sender_restrictions
```

**Comment by casperklein** [comment]
BTW: I see this also for incoming mails:

```
Feb 26 01:35:06 mail postfix/smtpd[6289]: connect from out-18.smtp.github.com[192.30.252.201]
Feb 26 01:35:06 mail postfix/smtpd[6289]: Anonymous TLS connection established from out-18.smtp.github.com[192.30.252.201] TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
Feb 26 01:35:06 mail postfix/smtpd[6289]: warning: restriction `reject_authenticated_sender_login_mismatch' ignored: no SASL support

```

**Comment by polarathene** [comment]
> the following warning appears in `mail.log` when an email is send

Sending from submitting to a particular submission port? Or just submitting to port 25 for sending? I think if it was for a submission port, the log would not be `postfix/smtpd` but the assigned name for 587 / 465 in `master.cf`?

**Comment by casperklein** [comment]
> Or just submitting to port 25 for sending? 

This. I am using the `mail` command from `bsd-mailx` package which uses `sendmail` command from `nullmailer`.
`nullmailer` uses unauthenticated port 25 for sending. I think I could change that to send authenticated via 465, but that's not what I prefer. I like the simple setup I currently have. Disabling authentication should not issue a warning when sending from whitelisted IP (mynetworks).

Also the warning is issued, when receiving external mails on port 25.

**Comment by georglauterbach** [comment]
So, I'd go about fixing this the following way:

1. Add `mua_sender_restrictions_not_plain = reject_authenticated_sender_login_mismatch` to `main.cf` so we can reference it in `master.cf` (no strict need for this, but this way, we avoid duplication of the actual directive).
2. Add `mua_sender_restrictions_default` with the current value of `smtpd_recipient_restrictions` in `main.cf` (**ONLY NECESSARY IF THE OPTIONS IN `master.cf` ARE ADDITIVE TO THE OPTIONS IN ´main.cf` - PLEASE TELL ME)
3. Set `smtpd_recipient_restrictions`'s value to `$mua_sender_restrictions_default` (**ONLY NECESSARY IF THE OPTIONS IN `master.cf` ARE ADDITIVE TO THE OPTIONS IN ´main.cf` - PLEASE TELL ME)
4. Do not append it in `main.cf` as this would set the default for port 25 as well
5. Add a line `  -o smtpd_recipient_restrictions=$mua_sender_restrictions_not_plain,reject`
6. Add `$mua_sender_restrictions_default to `smtpd_recipient_restrictions` in `master.cf` (**ONLY NECESSARY IF THE OPTIONS IN `master.cf` ARE ADDITIVE TO THE OPTIONS IN ´main.cf` - PLEASE TELL ME)

If `SPOOF_PROTECTION` is enabled, do nothing; if it's disabled, remove `$mua_sender_restrictions_not_plain` everywhere.

**Comment by georglauterbach** [comment]
T think I have a working fix (locally). I'd like to provide a PR after

- #3121
- #3123

to minimize merge conflicts (more work for me..).

**Comment by polarathene** [comment]
> **ONLY NECESSARY IF THE OPTIONS IN `master.cf` ARE _NOT_ ADDITIVE TO THE OPTIONS IN ´main.cf` - PLEASE TELL ME**

AFAIK they override the equivalent default specified in `main.cf`, as with all settings there with `-o setting_name` in `master.cf`.

Your approach in the PR to handle this seems to differ from what you discussed here a bit, I've provided review feedback there with the preferred approach:
- `master.cf` submission(s) services reference `mua` specific setting that inherits the default `smtpd_sender_restrictions` that is also used for Port 25 (_that `v12` is ceasing to allow SASL-authenticated submission for Postfix to send mail on this port_).
- `main.cf` provides that `mua` setting variant, which can include other changes from the default `smtpd_sender_restrictions` value that is interpolated with `$smtpd_sender_restrictions` as you're familiar with already.

Here you also referred to [`smtpd_recipient_restrictions`](https://www.postfix.org/postconf.5.html#smtpd_recipient_restrictions) and [`smtpd_sender_restrictions`](https://www.postfix.org/postconf.5.html#smtpd_sender_restrictions). Not sure why you've thought of mixing the two together like that, I know the [Postfix docs](https://www.postfix.org/SASL_README.html#server_sasl_authz) mistakenly mixes up the two settings with the example config for [`reject_sender_login_mismatch`](https://www.postfix.org/postconf.5.html#reject_sender_login_mismatch), but as you'd see via those doc links, it is only valid for `smtpd_sender_restrictions`. These are for specifying restrictions to different stages, so if your question was related to that being additive, then no, they're meant to be distinct. See [this Postfix docs page](https://www.postfix.org/SMTPD_ACCESS_README.html#lists) for more information about all these related settings, complimentary to the usual config docs.
