### ISSUE TITLE
[FR] Option to use external Redis server

### ISSUE THREAD

**Issue by alexanderadam** [docker-mailserver/docker-mailserver#3126]
# Feature Request

It would be nice being able to disable the internal Redis server and just provide credentials to an external one (i.e. with ENV variables).

## Context

Some users are running Redis anyway so it might make sense just to use a single instance.
At least provide an ENV variable to change the Redis port, so that there's no conflict if containers are running within the same Pod.

### Are you going to implement it?

No, and I understand that it is highly likely no one will implement it. Furthermore, I understand that this issue will likely become stale and will be closed. :disappointed: 

### What are you going to contribute??

Whatever I can

## Additional context

See description

### Alternatives you've considered

Well, i guess the existing Redis instance would need to be reconfigured.

### Who will that Feature be useful to?

People who are already using Redis.

**Comment by georglauterbach** [comment]
I can implement this.

**Comment by alexanderadam** [comment]
> I can implement this

That would be fantastic! :hand

> Are you using Redis for Rspamd?

Well, DMS does, doesn't it?

**Comment by georglauterbach** [comment]
The changes are on `:edge` in a few minutes.

**Comment by georglauterbach** [comment]
NOTE: PLEASE BE AWARE THAT #3143 will rename `ENABLE_REDIS` to `ENABLE_RSPAMD_REDIS`. If you are using `:edge` and you update, also update the ENV name. Functionality-wise, nothing changes though.
