### ISSUE TITLE
[BUG] OpenDMARC rejecting specific messages without obvious reason

### ISSUE THREAD

**Issue by groupmsl** [docker-mailserver/docker-mailserver#3130]
# Mailserver rejecting some messages that I want (milter-reject)

Other

## Description

I subscribe to a weekly newsletter and a few weeks ago I stopped receiving it. The first week I thought nothing of it, but more recently I have become concerned. Looking at the logs, my server appears to be rejecting this message:

```
Feb 21 23:01:48 mail postfix/smtpd[279717]: 62B3E583B1D: client=mail12.suw91.mcdlv.net[198.2.184.12]
Feb 21 23:01:48 mail postfix/cleanup[279726]: 62B3E583B1D: message-id=<6a9e465ab1570df8aaecb2292.a2a85a8a2f.20230221230123.006a7961cd.708246d1@mail12.suw91.mcdlv.net>
Feb 21 23:01:48 mail opendmarc[703]: 62B3E583B1D: SPF(mailfrom): mail12.suw91.mcdlv.net pass
Feb 21 23:01:48 mail opendmarc[703]: 62B3E583B1D: danielmiessler.com fail
Feb 21 23:01:48 mail postfix/cleanup[279726]: 62B3E583B1D: milter-reject: END-OF-MESSAGE from mail12.suw91.mcdlv.net[198.2.184.12]: 5.7.1 rejected by DMARC policy for danielmiessler.com; from=<bounce-mc.us8_31276059.2676496-a2a85a8a2f@mail12.suw91.mcdlv.net> to=<MYEMAILADDRESS> proto=ESMTP helo=<mail12.suw91.mcdlv.net>
```

So, as you can see, the opendmarc for `danielmiessler.com` fails and then the message is rejected. But this raises two further questions:

1. Why is it rejected? If you look at the SPF record for `danielmiessler.com` it is as below:

```
v=spf1 include:_spf.google.com include:servers.mcsv.net ~all
```

And the SPF record for `servers.mcsv.net`:

```
v=spf1 ip4:205.201.128.0/20 ip4:198.2.128.0/18 ip4:148.105.8.0/21 -all
```

And the IP the message came from, I believe was within that range.

I don't know if the DMARC record has any relevance to this issue, but it is as below:

```
v=DMARC1; p=reject; rua=mailto:daniel@danielmiessler.com
```

2. Another newsletter I subscribe to, from the BBC, also comes up as a opendmarc fail, but for some reason I don't understand my mailserver is happy enough and it ends up in my inbox?

```
Feb 21 07:11:55 mail postfix/smtpd[69464]: 068C8583B1D: client=mta3.ma.mailenvelope.bbc.co.uk[161.71.36.22]
Feb 21 07:11:55 mail postfix/cleanup[69473]: 068C8583B1D: message-id=<a129914a-7feb-433b-a084-4656c43e16dd@fra3s50mta23.xt.local>
Feb 21 07:11:55 mail opendmarc[703]: 068C8583B1D: SPF(mailfrom): bounce.ma.mailenvelope.bbc.co.uk pass
Feb 21 07:11:55 mail opendmarc[703]: 068C8583B1D: bbc.co.uk fail
Feb 21 07:11:55 mail postfix/qmgr[1445]: 068C8583B1D: from=<bounce-20_HTML-18533246-58629-7225364-12008@bounce.ma.mailenvelope.bbc.co.uk>, size=112669, nrcpt=1 (queue active)
Feb 21 07:11:55 mail postfix/smtpd[69464]: disconnect from mta3.ma.mailenvelope.bbc.co.uk[161.71.36.22] ehlo=2 starttls=1 mail=1 rcpt=1 data=1 quit=1 commands=7
Feb 21 07:11:57 mail dovecot: auth: passwd-file(bookingform,46.148.40.152): unknown user (SHA1 of given password: 0d2456)
Feb 21 07:11:57 mail postfix/smtpd-amavis/smtpd[69497]: connect from localhost[127.0.0.1]
Feb 21 07:11:57 mail postfix/smtpd-amavis/smtpd[69497]: EBC0E583F8D: client=localhost[127.0.0.1]
Feb 21 07:11:57 mail postfix/cleanup[69473]: EBC0E583F8D: message-id=<a129914a-7feb-433b-a084-4656c43e16dd@fra3s50mta23.xt.local>
Feb 21 07:11:57 mail postfix/qmgr[1445]: EBC0E583F8D: from=<bounce-20_HTML-18533246-58629-7225364-12008@bounce.ma.mailenvelope.bbc.co.uk>, size=113078, nrcpt=1 (queue active)
Feb 21 07:11:57 mail amavis[64303]: (64303-01) Passed CLEAN {RelayedInbound}, [161.71.36.22]:40663 [161.71.36.22] <bounce-20_HTML-18533246-58629-7225364-12008@bounce.ma.mailenvelope.bbc.co.uk> -> <MYEMAILADDRESS>, Queue-ID: 068C8583B1D, Message-ID: <a129914a-7feb-433b-a084-4656c43e16dd@fra3s50mta23.xt.local>, mail_id: e59e3TJ2kygK, Hits: -5.187, size: 112609, queued_as: EBC0E583F8D, 2628 ms
Feb 21 07:11:57 mail postfix/smtp-amavis/smtp[69484]: 068C8583B1D: to=<MYEMAILADDRESS>, relay=127.0.0.1[127.0.0.1]:10024, delay=3.2, delays=0.55/0.03/0.01/2.6, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as EBC0E583F8D)
Feb 21 07:11:57 mail postfix/qmgr[1445]: 068C8583B1D: removed
```

A few weeks before this I received an SMS from my bank saying they couldn't send me my statement by email because it had failed. Again at the time I didn't think much of it, and no longer have the logs from back then, but it seems there is a wider issue here.

I can't say for sure when it started happening, but I think it might be when I upgraded to 11.3.0 (which I am still running).

I have tried the workaround in #3078 as the issues sound similar, but this has not helped.

Any help would be really appreciated, as I'm lost at the moment, and can't afford to keep loosing emails.

Thank you

**Comment by groupmsl** [comment]
I wonder if my next step should be to downgrade to 11.2.0 and see if I get my newsletter next Monday, wondering if #2933 has brought this issue to light, as suggested by #3078.

Even if this does work, it doesn't help fix the issue, so some help / assistance as to what is going on would be really useful here.

**Comment by georglauterbach** [comment]
Thank for the report! This looks concerning indeed; I am currently involved in other issues though, so I'll tackle them first.

But for the time being, you could upgrade to `:edge` and use `ENABLE_OPENDMARC=0` to disable DMARC checks completely until we can dig into this.

---

So, your bank, and two newsletters could not deliver emails? That's a bit weird to be honest.. can you please double-check your DNS setup and have a look at which DNS servers the DMARC service uses?

**Comment by groupmsl** [comment]
Thanks for the quick reply. I will upgrade as you suggested.

It's just my bank and one newsletter. The other newsletter that fails opendmarc still ends up in my inbox (which is even more confusing..)

When you have some time to look, let me know what I can do to help - I'm happy to get my hands dirty and understand it a bit more.

**Comment by groupmsl** [comment]
### Me:

My DNS in on AWS Route53 (but my DMS is self hosted). My DMARC is as below:

```
v=DMARC1; p=reject; rua=mailto:mailauth-reports@MYDOMAIN.co.uk
```

My SPF:

```
 v=spf1 include:mailgun.org include:_spf.google.com ~all 
```

According to dmarcanalyzer.com the whole chain looks good.

For context I use mailgun as a relay for sending, as I'm running my server on a residential IP which isn't so reliable. As for google, I used to use google apps (the free one), and it's all still there and configured, but my DMS has a lower MX record - it's actually a good backup MX when I have internet issues!

### danielmiessler.com newsletter (does NOT get to my inbox)

DMARC:

```
v=DMARC1; p=reject; rua=mailto:daniel@danielmiessler.com
```

SPF:
```
 v=spf1 include:_spf.google.com include:servers.mcsv.net ~all 
```


### bbc.co.uk newsletter (does get to my inbox)

DMARC:

```
v=DMARC1;p=none;aspf=s;adkim=s;pct=100;fo=0;ri=86400; rua=mailto:02fd5b325c28457@rep.dmarcanalyzer.com; ruf=mailto:02fd5b325c28457@for.dmarcanalyzer.com;
```

SPF:

```
v=spf1 a ip4:212.58.224.0/19 ip4:132.185.0.0/16 ip4:78.136.53.80/28 ip4:78.136.14.192/27 ip4:78.136.19.8/29 ip4:89.234.10.72/29 ip4:89.234.53.236 ip4:212.111.33.181 ip4:78.137.117.8 ip4:46.37.176.74 ip4:185.184.237.181 ip4:185.119.233.144/30 ip4:185.119.232.158 +include:sf.sis.bbc.co.uk +include:spf.messagelabs.com ~all
```


So, is the reason the BBC newsletter gets to my inbox but the DanielMiessler one does not because the BBC has a DMARC policy of `none` vs Daniels `reject`?

But it still doesn't help at all as to why both newsletters are marked as fail by opendmarc...

**Comment by georglauterbach** [comment]
> So, is the reason the BBC newsletter gets to my inbox but the DanielMiessler one does not because the BBC has a DMARC policy of `none` vs Daniels `reject`?

This is very likely.

> But it still doesn't help at all as to why both newsletters are marked as fail by opendmarc...

Indeed.

--- 

I will let you know when I have some time.

**Comment by georglauterbach** [comment]
I know this might sound stupid, and I shamelessly promote features I added myself, but you might want to try Rspamd? The integration and documentation is maturing to a point where I can recommend it; here is the getting-started section in our docs: <https://docker-mailserver.github.io/docker-mailserver/edge/config/security/rspamd/#a-very-basic-configuration>.

Rspamd will perform DKIM, SPF and DMARC checks, and AFAIK without errors. You can leave OpenDKIM enabled I think if you don't want Rspamd to sign your emails.

This way, I may be able to get a bit more feedback for Rspamd as well.

There is currently an open PR that adds more functionality, if you want to wait for that: #3159

**Comment by groupmsl** [comment]
Sorry for the slow reply, I've been really busy. I have no issue to switching to Rspamd, I will have a look into it and give it a test. It will probably take me a while though...

Is there a plan to switch to Rspamd being the default for the things it replaces at any point?

I will let you know how it goes!

**Comment by georglauterbach** [comment]
> Sorry for the slow reply, I've been really busy. I have no issue to switching to Rspamd, I will have a look into it and give it a test. It will probably take me a while though...

Take your time :)

> Is there a plan to switch to Rspamd being the default for the things it replaces at any point?

Yes. v13 should deprecate the defaults and v14 will probably switch them. Rspamd should be the default then.

> I will let you know how it goes!

Nice! Thanks :)

**Comment by groupmsl** [comment]
I have upgraded to 12.0 and switched to using rspamd (as per the link you suggested) and this is working fine for me. I haven't yet investigated much around rspamd, and infact I haven't been able to log into the web interface, even with the suggested `set-option-for-controller secure_ip "0.0.0.0/0"`. I'm sure I am just doing something wrong though? The documentation also says that DMS doesn't set a default password, which I assumed meant the password was empty, but this also doesn't seem to work?

Anyway, it seems (with rspamd) my issue goes away and I'm happy with that! Thanks for the help

**Comment by georglauterbach** [comment]
IIRC you have to set a password to log in.

But I'm happy that the switch solved your problem. Can this be closed?

**Comment by groupmsl** [comment]
Yep, definitely - closing!
