### ISSUE TITLE
Two local mailservers reject each others' emails

### ISSUE THREAD

**Issue by Mwni** [docker-mailserver/docker-mailserver#3139]
I'm running two mailserver containers on the same machine. Each is configured properly and email delivery works well. The issue arrises when one tries to send an email to the other:
```
NOQUEUE: reject: RCPT from unknown[20.10.0.1]: 450 4.7.25 Client host rejected: cannot find your hostname
```
It appears that the smtp connection is made directly via the localhost network, which then of course does not have the correct ip address that statisfies PTR/SPF/DKIM.

How to either prevent the containers from routing locally, or make them tolerate emails coming from local?

**Comment by polarathene** [comment]
Raise a proper bug report with config and preferably the steps you've used to reproduce.

In the past for offline testing with multiple instances of DMS, I have used CoreDNS as a container that handled DNS for the DMS containers, they would connect to each other fine and respect the DNS records.
