### ISSUE TITLE
[BUG] `_shutdown` will continue when called in a subshell (causing UB)

### ISSUE THREAD

**Issue by polarathene** [docker-mailserver/docker-mailserver#3140]
# Description

Not too important.

[A user showed a particular failure scenario](https://github.com/docker-mailserver/docker-mailserver/issues/3133) where shutdown was called twice, and additionally two `sedfile` errors that came afterwards, but it should have stopped from the first shutdown.

The function involved likely continues running instead of exiting early on failure. This may be the case for other scripts that invoke shutdown on failure. A workaround could just involve the logger being aware of the shutdown call to silence it's logging from then on? :man_shrugging: 

Or we can just leave it as-is. I believe there's some desired changes in future for running bash scripts that handle failure better? Or the potential that we migrate away from bash scripts.

**Comment by polarathene** [comment]
It'll be easier going forward I think.

If compiling something like Rust was an issue (_more likely relevant to DX when iterating on a fix or feature_), it can always [augment parts with some runtime scripting or wasm](https://www.reddit.com/r/rust/comments/s63j6n/which_scripting_languages_work_well_embedded_with/).

We'd probably start with rust based utilities such as replacing `variables.sh` for all the benefits in centralizing ENV management / docs. As features are better isolated like changes you've been making lately to split up `setup-stack.sh`, they could technically be replaced piece-meal too.

Time wise it's not something I can make any commitments to myself though :sweat_smile:

**Comment by georglauterbach** [comment]
Funnily enough, this issue is more or less the same that #3137 solves for our tests. It's not so easy to resolve for the scripts though. I wouldn't bother to be honest.

**Comment by georglauterbach** [comment]
Nevermind, had an idea that works. Changes are not too big, so I added them to the v12.0.0 milestone.
