### ISSUE TITLE
[FR] Alternative to team discussions

### ISSUE THREAD

**Issue by casperklein** [docker-mailserver/docker-mailserver#3148]
I just found out, that team discussions are deprecated:

> Team Discussions will be deprecated on May 8th, 2023. We encourage you to transfer these posts to GitHub Discussions. Read more about this deprecation in our [changelog](https://github.co/AAjbqar).

The only way I found to have non public discussions would be a private repository with "Discussions" enabled.

@georglauterbach can you create a new repo for that? `dms-discussions` or something.

**Comment by georglauterbach** [comment]
Yeah, I noticed this a while back as well and I couldn't figure out where to have private discussions now.. I will take care.

**Comment by georglauterbach** [comment]
There you go: <https://github.com/docker-mailserver/discussions/discussions>

**Comment by polarathene** [comment]
> I hope you have the rights to open a discussion

Works :+1: 

Closing as I think it's resolved?

---

Might as well let another existing maintainers know about this too @docker-mailserver/admin-maintainers @docker-mailserver/helm-maintainers
