### ISSUE TITLE
[FR] Rspamd: make it possible to move e-mails to Junk automatically

### ISSUE THREAD

**Issue by georglauterbach** [docker-mailserver/docker-mailserver#3156]
# Feature Request

## Context

Users should be able to toggle behavior to automatically move mail to the Junk folder when Rspamd adds the `X-Spam: Yes` header.

### Is your Feature Request related to a Problem?

Currently, users must move them automatically.

### Describe the Solution you'd like

This should be done by Sieve automatically if desired.

### Are you going to implement it?

Yes.

### What are you going to contribute??

Everything.

**Comment by hanscees** [comment]
I have the new image running and its wonderful. It nicely retains learned spam and ham after a docker-config down. 
And it automagically fills my junk folder with spam email. 

Really nice and cool!!

**Comment by georglauterbach** [comment]
> I have the new image running and its wonderful. It nicely retains learned spam and ham after a docker-config down. 

Thanks for the report!

> And it automagically fills my junk folder with spam email. 

That feature is not yet merged; I guess you enabled it via `user-patches.sh`?

> Really nice and cool!! 

🚀

**Comment by alexanderadam** [comment]
@georglauterbach thank you so much for your implementation.
So this is now in `edge` but there's no `12` release yet, right?

**Comment by polarathene** [comment]
> there's no `12` release yet, right?

Not yet. I think we only have one more pressing change to get in before the 1 week freeze before v12 release. That's disabling chroot for Dovecot and PostSRSd. I should have time for that in the next few days, so v12 should be out first week of April.

**Comment by casperklein** [comment]
No, rspamd will be additional to spamassassin in v12. You can choose which one to use.
