### ISSUE TITLE
[Q]mail.err shows opendkim error loading key

### ISSUE THREAD

**Issue by JivinDotL** [docker-mailserver/docker-mailserver#3163]
Mar  7 14:17:27 mail opendkim[529]: mail._domainkey.axas.com: key data is not secure: /etc can be read or written by other users
Mar  7 14:17:27 mail opendkim[529]: BDF2E1C1982: error loading key 'mail._domainkey.axas.com'

I can't fix this issue, anyone can help me? I use docker image.

**Comment by georglauterbach** [comment]
We have issue templates. Use them.
