### ISSUE TITLE
[BUG] OpenDKIM running when disabled

### ISSUE THREAD

**Issue by jrpear** [docker-mailserver/docker-mailserver#3169]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

opendkim is started even though `ENABLE_OPENDKIM=0`

### What happened and when does this occur?

opendkim is started even though `ENABLE_OPENDKIM=0`

### What did you expect to happen?

I expected opendkim to not be started

### How do we replicate the issue?

Just run a container with `ENABLE_OPENDKIM` set to zero (and `ENABLE_OPENDMARC` for good measure). Observe that the log contains repeated messages like:

```
mailserver    | 2023-03-09 15:50:43,589 INFO spawned: 'opendkim' with pid 1465
mailserver    | 2023-03-09 15:50:43,598 INFO success: opendkim entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
mailserver    | 2023-03-09 15:50:43,598 INFO exited: opendkim (exit status 78; not expected)
```

Here are the commands I ran:

```bash
wget https://raw.githubusercontent.com/docker-mailserver/docker-mailserver/dab70709d90df1d83b920eccc6c0386b283d677e/docker-compose.yml
cat <<-EOF >mailserver.env
	LOG_LEVEL=info
	SUPERVISOR_LOGLEVEL=info
	ENABLE_OPENDKIM=0
	ENABLE_OPENDMARC=0
EOF
docker-compose up -d
docker exec -it $(docker-compose ps -q) setup email add user@example.com
# Enter password
docker-compose logs --tail=10 -f
```

### DMS version

v11.3.1

### What operating system is DMS running on?

Linux

### Which operating system version?

Debian testing

### What instruction set architecture is DMS running on?

AMD64 / x86_64

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by polarathene** [comment]
I think there is a misunderstanding here due to our default docs showing `:edge` (unreleased), this ENV is part of an upcoming v12 release due out this month :+1:  ([not present in 11.3 docs](https://docker-mailserver.github.io/docker-mailserver/v11.3/config/environment/))

**Comment by jrpear** [comment]
Ah yep, that was indeed the problem 😅.

I wish MkDocs showed the documentation version even after scrolling down.

**Comment by polarathene** [comment]
> I wish MkDocs showed the documentation version even after scrolling down.

Me too. I think we can change our default docs to point to the last released tag, which might at least help (_this is a common problem lately_).

**Comment by jrpear** [comment]
I just opened an issue for it: #3173 . If no one objects, I'll take a stab at it in the next few days.
