### ISSUE TITLE
Postfix configure master process limit

### ISSUE THREAD

**Issue by gulecroc** [docker-mailserver/docker-mailserver#3171]
Hello,

In the documentation, we can configure [postfix master service parameter](https://docker-mailserver.github.io/docker-mailserver/v11.3/config/advanced/override-defaults/postfix/).
Is it possible to configure [postfix master process limit](https://www.postfix.org/master.5.html), for example set smtp process limit :

```
smtp       unix  -       -       y       -       mySmtpProcessLimit       smtp
```

Thank you.

**Comment by polarathene** [comment]
As the docs for `main.cf` say, there is a [default parameter of 100 processes](https://www.postfix.org/postconf.5.html#default_process_limit). You should be able to apply this to the smtp service apparently with our `postfix-master.cf`:

```
smtp/inet/default_process_limit=42
```

---

**EDIT:** Nevermind, just noticed it was not `-` so you must replace the existing `1` value. You can do this with [`user-patches.sh`](https://docker-mailserver.github.io/docker-mailserver/v11.3/config/advanced/override-defaults/user-patches/) and using something like a `sed` command on `/etc/postfix/master.cf` to replace the value on that line.

I am not sure how well that is supported or advised though, [it seems to be](https://www.postfix.org/STRESS_README.html#concurrency).

**Comment by gulecroc** [comment]
Using user-patches.sh works perfectly, thank you !
