### ISSUE TITLE
Emails routing internally for domain managed by another server

### ISSUE THREAD

**Issue by Caffe1neAdd1ct** [docker-mailserver/docker-mailserver#3181]
# Subject

I would like some feedback concerning a use case

## Description

I've configured an email which is restricted to send only, updated SPF records to allow the server to send out on that domain's behalf, however other users on this mailserver now cannot send emails to users on that domain which resides in Gmail:

```
host mail.mydomain.com[/var/run/dovecot/lmtp] said:
    550 5.1.1 <site@domain2.com> User doesn't exist:
    site@domain2.com (in reply to RCPT TO command)
```

To explain:

Added 

site@domain2.com to mail.mydomain.com to be used inside wordpress for SMTP authenticated email sending
domain2.com mail is actually handled by gmail

sending from myaddress@mydomain.com to theiraddress@domain2.com no longer works as it's being routed internally to a non existent mailbox, any ideas how to get around this?

**Comment by Caffe1neAdd1ct** [comment]
Looking into this a little more, it would be awesome to have an exclude list of domains to prevent

https://github.com/docker-mailserver/docker-mailserver/blob/e58dd1b95b3552ea850dad6b2ef0b87f8a9bae78/target/scripts/helpers/postfix.sh#L33

from adding them to the vhosts file `/etc/postfix/vhost` which is loaded as `virtual_mailbox_domains = /etc/postfix/vhost`

Removing (from the example above) domain2.com from the vhost file allows sending to that domain from other domain mailboxes on this instance.

Alternatively, if not in the interest of the project, i'll attach another IP, run up another box bound to the other IP and run two separate instances... one for actual mailboxes and one for website SMTP send only accounts..

-----------------------

For anyone else hitting this issue and wishing to maintain this domain list manually:

1. create a postfix.cf override file:
```
vim ./docker-data/dms/config/postfix-main.cf
virtual_mailbox_domains = /etc/postfix/vhost-custom
```
2. create a custom vhost file
```
vim ./docker-data/dms/config/vhost-custom
mydomain.com
mydomain-other.com
```
exclude domains which don't actually reside on this server for mailboxes

3. mount the file into the box using docker compose volumes:

```
volumes:
      - ./docker-data/dms/config/vhost-custom:/etc/postfix/vhost-custom

```

Gets around the issue but not ideal :monocle_face:

**Comment by georglauterbach** [comment]
I see the issue. This is a first though I think. Providing a native solution would require more users to face this issue to have a reason for maintaining the code.

The solution would be to read a file line by line and remove the read line from the vhosts file.

The very simple solution would be to mount the vhosts file read-only (`:ro`) though, right? This would resolve in `sed` showing an error but other than that, would be fine.

**Comment by polarathene** [comment]
You can add your override via [`postfix-main.cf`](https://docker-mailserver.github.io/docker-mailserver/latest/config/advanced/override-defaults/postfix/):

```
# postfix-main.cf:
virtual_mailbox_domains = /etc/postfix/vhost-custom
```

Then use bind volume mount to include that `vhost-custom` file at that path, or create it internally with [`user-patches.sh`](https://docker-mailserver.github.io/docker-mailserver/latest/config/advanced/override-defaults/user-patches/), which prevents needing a separate bind mount just for this file:

```
# user-patches.sh:
#!/bin/bash
cp /tmp/docker-mailserver/vhost-custom /etc/postfix/vhost-custom
```

---

As mentioned, we cannot be expected to maintain niche requirements.

Our policy is to request a feature:
- Simple to DIY: Resolve on Github, optionally contributing to our docs to help share that knowledge with others.
- Complex: Get approval to contribute, create a PR implementing the feature, provide docs and tests to be reviewed and approved.

Getting feature approval often requires multiple users expressing interest in the feature, especially if maintainers are to implement it.

**Comment by lennardv2** [comment]
I too would appreciate this feature. I believe it's not such a niche request to have the server capable of sending emails through a mailbox, while also providing the flexibility to use services like Google Mail, especially when it comes to client work.

Anyway, i use this user-patches.sh:

```bash
#!/bin/bash
IGNORE=("example.com")

# Copy /etc/postfix/vhost
cp /etc/postfix/vhost /etc/postfix/vhost-custom

# Remove items from the ignore list
for i in "${IGNORE[@]}"
do
    sed -i "/$i/d" /etc/postfix/vhost-custom
done
```

And the override in postfix-main.cf:
```
virtual_mailbox_domains = /etc/postfix/vhost-custom
```
