### ISSUE TITLE
Problem with send to GMAIL

### ISSUE THREAD

**Issue by infortek1991** [docker-mailserver/docker-mailserver#3189]
Hallo,

I have a problem with communicate to gmail from Docker Mailserver.
- Everything was set np. DKIM, SPF Record and any domain settings. 
- I can receive messages. I can send to my own, but I cannot send to outside np. gmail.

Received mail:

```
This is the mail system at host mail.workhome.augustow.pl.

I'm sorry to have to inform you that your message could not be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can delete your own text from the attached returned message.

                   The mail system

<(mailto:lukasz@gmail.com)>: mail for gmail.com loops back to myself
```

**Comment by infortek1991** [comment]
2023/03/20-20:29:37 Server closing!
[   INF   ]  Welcome to docker-mailserver 11.3.0
[   INF   ]  Initializing setup
[   INF   ]  Checking configuration
[   INF   ]  Configuring mail server
Nameservers 8.8.8.8,8.8.4.4
[   INF   ]  Post-configuration checks
[   INF   ]  Starting miscellaneous tasks
[   INF   ]  Starting daemons
[   INF   ]  mail.workhome.augustow.pl is up and running
Mar 20 20:30:20 mail amavis[658]: starting. /usr/sbin/amavisd-new at mail.workhome.augustow.pl amavisd-new-2.11.1 (20181009), Unicode aware, LC_CTYPE="C.UTF-8"
Mar 20 20:30:20 mail amavis[658]: perl=5.032001, user=, EUID: 110 (110);  group=, EGID: 112 112 (112 112)
Mar 20 20:30:20 mail amavis[658]: Net::Server: Group Not Defined.  Defaulting to EGID '112 112'
Mar 20 20:30:20 mail amavis[658]: Net::Server: User Not Defined.  Defaulting to EUID '110'
Mar 20 20:30:20 mail amavis[658]: No ext program for   .zoo, tried: zoo
Mar 20 20:30:20 mail amavis[658]: No ext program for   .doc, tried: ripole
Mar 20 20:30:20 mail amavis[658]: No decoder for       .F
Mar 20 20:30:20 mail amavis[658]: No decoder for       .doc
Mar 20 20:30:20 mail amavis[658]: No decoder for       .zoo
Mar 20 20:30:20 mail amavis[658]: Using primary internal av scanner code for ClamAV-clamd
Mar 20 20:30:20 mail amavis[658]: Found secondary av scanner ClamAV-clamscan at /usr/bin/clamscan
Mar 20 20:30:26 mail postfix/master[1220]: daemon started -- version 3.5.17, configuration /etc/postfix
Mar 20 20:30:26 mail postfix/pickup[1222]: 5D6A26000C9: uid=0 from=<root>
Mar 20 20:30:26 mail postfix/cleanup[1225]: 5D6A26000C9: message-id=<20230320193026.5D6A26000C9@mail.workhome.augustow.pl>
Mar 20 20:30:26 mail opendkim[500]: 5D6A26000C9: no signing table match for 'root@mail.workhome.augustow.pl'
Mar 20 20:30:26 mail opendkim[500]: 5D6A26000C9: no signature data
Mar 20 20:30:26 mail postfix/qmgr[1223]: 5D6A26000C9: from=<root@mail.workhome.augustow.pl>, size=783, nrcpt=1 (queue active)
Mar 20 20:30:26 mail dovecot: lmtp(1238): Connect from local
Mar 20 20:30:26 mail dovecot: lmtp(postmaster@workhome.augustow.pl)<1238><qcyNGlK0GGTWBAAA9Pu0KA>: sieve: msgid=<20230320193026.5D6A26000C9@mail.workhome.augustow.pl>: stored mail into mailbox 'INBOX'
Mar 20 20:30:26 mail postfix/lmtp[1229]: 5D6A26000C9: to=<postmaster@workhome.augustow.pl>, relay=mail.workhome.augustow.pl[/var/run/dovecot/lmtp], delay=10, delays=10/0.03/0.02/0.02, dsn=2.0.0, status=sent (250 2.0.0 <postmaster@workhome.augustow.pl> qcyNGlK0GGTWBAAA9Pu0KA Saved)
Mar 20 20:30:26 mail postfix/qmgr[1223]: 5D6A26000C9: removed
Mar 20 20:30:26 mail dovecot: lmtp(1238): Disconnect from local: Client has quit the connection (state=READY)
Mar 20 20:32:20 mail postfix/submission/smtpd[1523]: connect from unknown[77.252.47.51]
Mar 20 20:32:21 mail postfix/submission/smtpd[1523]: Anonymous TLS connection established from unknown[77.252.47.51]: TLSv1.2 with cipher ECDHE-ECDSA-AES128-GCM-SHA256 (128/128 bits)
Mar 20 20:32:21 mail postfix/submission/smtpd[1523]: 928EB6000C9: client=unknown[77.252.47.51], sasl_method=LOGIN, sasl_username=test1@workhome.augustow.pl
Mar 20 20:32:21 mail postfix/sender-cleanup/cleanup[1534]: 928EB6000C9: message-id=<001e01d95b62$b171fb20$1455f160$@workhome.augustow.pl>
Mar 20 20:32:21 mail postfix/sender-cleanup/cleanup[1534]: 928EB6000C9: replace: header MIME-Version: 1.0 from unknown[77.252.47.51]; from=<test1@workhome.augustow.pl> to=<l.naszewski@gmail.com> proto=ESMTP helo=<DESKTOPAFGMMHH>: Mime-Version: 1.0
Mar 20 20:32:21 mail opendkim[500]: 928EB6000C9: DKIM-Signature field added (s=mail, d=workhome.augustow.pl)
Mar 20 20:32:21 mail postfix/qmgr[1223]: 928EB6000C9: from=<test1@workhome.augustow.pl>, size=2352, nrcpt=1 (queue active)
Mar 20 20:32:24 mail dovecot: imap-login: Login: user=<test1@workhome.augustow.pl>, method=PLAIN, rip=77.252.47.51, lip=172.17.0.2, mpid=1544, TLS, session=<07aE/Fn3pd5N/C8z>
Mar 20 20:32:24 mail postfix/submission/smtpd[1523]: disconnect from unknown[77.252.47.51] ehlo=2 starttls=1 auth=1 mail=1 rcpt=1 data=1 quit=1 commands=8
Mar 20 20:32:32 mail postfix/smtpd-amavis/smtpd[1565]: connect from localhost[127.0.0.1]
Mar 20 20:32:32 mail postfix/smtpd-amavis/smtpd[1565]: 679B960014C: client=localhost[127.0.0.1]
Mar 20 20:32:32 mail postfix/cleanup[1566]: 679B960014C: message-id=<001e01d95b62$b171fb20$1455f160$@workhome.augustow.pl>
Mar 20 20:32:32 mail postfix/qmgr[1223]: 679B960014C: from=<test1@workhome.augustow.pl>, size=3461, nrcpt=1 (queue active)
Mar 20 20:32:32 mail amavis[1090]: (01090-01) Passed CLEAN {RelayedOpenRelay}, [77.252.47.51]:57218 [77.252.47.51] <test1@workhome.augustow.pl> -> <l.naszewski@gmail.com>, Queue-ID: 928EB6000C9, Message-ID: <001e01d95b62$b171fb20$1455f160$@workhome.augustow.pl>, mail_id: oIrOKgMRz2pS, Hits: 3.285, size: 3219, queued_as: 679B960014C, 10448 ms
Mar 20 20:32:32 mail postfix/smtp-amavis/smtp[1535]: 928EB6000C9: to=<l.naszewski@gmail.com>, relay=127.0.0.1[127.0.0.1]:10024, delay=11, delays=0.46/0.03/0.02/10, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as 679B960014C)
Mar 20 20:32:32 mail postfix/qmgr[1223]: 928EB6000C9: removed
Mar 20 20:32:33 mail postfix/postscreen[1568]: CONNECT from [10.5.101.1]:46328 to [172.17.0.2]:25
Mar 20 20:32:33 mail postfix/postscreen[1568]: PASS OLD [10.5.101.1]:46328
Mar 20 20:32:33 mail postfix/smtpd[1569]: connect from unknown[10.5.101.1]
Mar 20 20:32:33 mail postfix/smtp[1567]: warning: host gmail-smtp-in.l.google.com[64.233.166.26]:25 greeted me with my own hostname mail.workhome.augustow.pl
Mar 20 20:32:33 mail postfix/smtp[1567]: warning: host gmail-smtp-in.l.google.com[64.233.166.26]:25 replied to HELO/EHLO with my own hostname mail.workhome.augustow.pl
Mar 20 20:32:33 mail postfix/smtp[1567]: 679B960014C: to=<l.naszewski@gmail.com>, relay=gmail-smtp-in.l.google.com[64.233.166.26]:25, delay=0.79, delays=0.02/0.02/0.75/0, dsn=5.4.6, status=bounced (mail for gmail.com loops back to myself)
Mar 20 20:32:33 mail postfix/smtpd[1569]: disconnect from unknown[10.5.101.1] ehlo=1 quit=1 commands=2
Mar 20 20:32:33 mail postfix/cleanup[1566]: 3703A60014D: message-id=<20230320193233.3703A60014D@mail.workhome.augustow.pl>
Mar 20 20:32:33 mail postfix/qmgr[1223]: 3703A60014D: from=<>, size=5425, nrcpt=1 (queue active)
Mar 20 20:32:33 mail postfix/bounce[1570]: 679B960014C: sender non-delivery notification: 3703A60014D
Mar 20 20:32:33 mail postfix/qmgr[1223]: 679B960014C: removed
Mar 20 20:32:33 mail dovecot: lmtp(1576): Connect from local
Mar 20 20:32:33 mail dovecot: lmtp(test1@workhome.augustow.pl)<1576><KW8fEdG0GGQoBgAA9Pu0KA>: sieve: msgid=<20230320193233.3703A60014D@mail.workhome.augustow.pl>: stored mail into mailbox 'INBOX'
Mar 20 20:32:33 mail postfix/lmtp[1572]: 3703A60014D: to=<test1@workhome.augustow.pl>, relay=mail.workhome.augustow.pl[/var/run/dovecot/lmtp], delay=0.08, delays=0.01/0.03/0.03/0.01, dsn=2.0.0, status=sent (250 2.0.0 <test1@workhome.augustow.pl> KW8fEdG0GGQoBgAA9Pu0KA Saved)
Mar 20 20:32:33 mail postfix/qmgr[1223]: 3703A60014D: removed
Mar 20 20:32:33 mail dovecot: lmtp(1576): Disconnect from local: Client has quit the connection (state=READY)

**Comment by jrpear** [comment]
Gmail has probably blocked your email because it thinks it's spam.

There are many reasons why email might be rejected: a misconfigured SSL certificate, a TLD or IP address with a bad reputation, misconfigured DNS records, etc.

Maybe helpful links: https://www.mail-tester.com/ https://www.helloinbox.email/

**Comment by infortek1991** [comment]
Thank You for Your help. I try but nothing go outside to any domains. In internal work great but to outside nothing. I don't know what to do :(

**Comment by reneploetz** [comment]
The likely reason for this is that you are lacking the correct PTR DNS record (also named rDNS) for your mail servers IP address.
As the IP resolving to the domain ```mail.workhome.augustow.pl``` is located in the Hetzner IP space I assume you are hosted there. Your current record points to ```srv.itpsysteme.de```.
The problem is that you are reporting ```mail.workhome.augustow.pl``` as the name in HELO to the google mail server which then checks this name against the PTR record and is classifying your connection as SPAM because it's not ```srv.itpsysteme.de```.
Depending on what you actually want you need to either set the PTR record to ```mail.workhome.augustow.pl``` or the mail domain to ```srv.itpsysteme.de```. Note that the latter will also not work out-of-the-box as srv.itpsysteme.de already has an MX record itself which does not point to your server. This record is also invalid - MX records MUST point to an A or AAAA record not a CNAME record.

**Comment by infortek1991** [comment]
Hallo,

Thank You for Help. :)
I have a set PTR Record for Mail Server.
I don't know what to do and problem is stil not resolved.

[   INF   ]  Welcome to docker-mailserver 11.3.0
[   INF   ]  Initializing setup
[   INF   ]  Checking configuration
[   INF   ]  Configuring mail server
Nameservers 8.8.8.8,8.8.4.4
[   INF   ]  Post-configuration checks
[   INF   ]  Starting miscellaneous tasks
[   INF   ]  Starting daemons
[   INF   ]  mail.workhome.augustow.pl is up and running
Mar 23 16:56:05 mail amavis[636]: starting. /usr/sbin/amavisd-new at mail.workhome.augustow.pl amavisd-new-2.11.1 (20181009), Unicode aware, LC_CTYPE="C.UTF-8"
Mar 23 16:56:05 mail amavis[636]: perl=5.032001, user=, EUID: 110 (110);  group=, EGID: 112 112 (112 112)
Mar 23 16:56:06 mail amavis[636]: Net::Server: Group Not Defined.  Defaulting to EGID '112 112'
Mar 23 16:56:06 mail amavis[636]: Net::Server: User Not Defined.  Defaulting to EUID '110'
Mar 23 16:56:06 mail amavis[636]: No ext program for   .zoo, tried: zoo
Mar 23 16:56:06 mail amavis[636]: No ext program for   .doc, tried: ripole
Mar 23 16:56:06 mail amavis[636]: No decoder for       .F
Mar 23 16:56:06 mail amavis[636]: No decoder for       .doc
Mar 23 16:56:06 mail amavis[636]: No decoder for       .zoo
Mar 23 16:56:06 mail amavis[636]: Using primary internal av scanner code for ClamAV-clamd
Mar 23 16:56:06 mail amavis[636]: Found secondary av scanner ClamAV-clamscan at /usr/bin/clamscan
Mar 23 16:56:11 mail postfix/master[1217]: daemon started -- version 3.5.17, configuration /etc/postfix
Mar 23 16:56:11 mail postfix/pickup[1220]: DAEAB6001D4: uid=0 from=<root>
Mar 23 16:56:11 mail postfix/cleanup[1222]: DAEAB6001D4: message-id=<20230323155611.DAEAB6001D4@mail.workhome.augustow.pl>
Mar 23 16:56:11 mail opendkim[503]: DAEAB6001D4: no signing table match for 'root@mail.workhome.augustow.pl'
Mar 23 16:56:11 mail opendkim[503]: DAEAB6001D4: no signature data
Mar 23 16:56:11 mail postfix/qmgr[1221]: DAEAB6001D4: from=<root@mail.workhome.augustow.pl>, size=783, nrcpt=1 (queue active)
Mar 23 16:56:11 mail dovecot: lmtp(1225): Connect from local
Mar 23 16:56:11 mail dovecot: lmtp(postmaster@workhome.augustow.pl)<1225><mhanOJt2HGTJBAAA9Pu0KA>: sieve: msgid=<20230323155611.DAEAB6001D4@mail.workhome.augustow.pl>: stored mail into mailbox 'INBOX'
Mar 23 16:56:11 mail postfix/lmtp[1224]: DAEAB6001D4: to=<postmaster@workhome.augustow.pl>, relay=mail.workhome.augustow.pl[/var/run/dovecot/lmtp], delay=11, delays=11/0.01/0.02/0.03, dsn=2.0.0, status=sent (250 2.0.0 <postmaster@workhome.augustow.pl> mhanOJt2HGTJBAAA9Pu0KA Saved)
Mar 23 16:56:11 mail dovecot: lmtp(1225): Disconnect from local: Client has quit the connection (state=READY)
Mar 23 16:56:11 mail postfix/qmgr[1221]: DAEAB6001D4: removed
Mar 23 16:56:53 mail dovecot: imap-login: Login: user=<test1@workhome.augustow.pl>, method=PLAIN, rip=77.252.47.51, lip=172.17.0.2, mpid=1329, TLS, session=<IapJU5P3DNxN/C8z>
Mar 23 16:57:09 mail postfix/submission/smtpd[1369]: connect from unknown[77.252.47.51]
Mar 23 16:57:09 mail postfix/submission/smtpd[1369]: Anonymous TLS connection established from unknown[77.252.47.51]: TLSv1.2 with cipher ECDHE-ECDSA-AES128-GCM-SHA256 (128/128 bits)
Mar 23 16:57:10 mail postfix/submission/smtpd[1369]: 0746960014E: client=unknown[77.252.47.51], sasl_method=LOGIN, sasl_username=test1@workhome.augustow.pl
Mar 23 16:57:10 mail postfix/sender-cleanup/cleanup[1377]: 0746960014E: message-id=<000001d95da0$2124ca30$636e5e90$@workhome.augustow.pl>
Mar 23 16:57:10 mail postfix/sender-cleanup/cleanup[1377]: 0746960014E: replace: header MIME-Version: 1.0 from unknown[77.252.47.51]; from=<test1@workhome.augustow.pl> to=<l.naszewski@gmail.com> proto=ESMTP helo=<DESKTOPAFGMMHH>: Mime-Version: 1.0
Mar 23 16:57:10 mail opendkim[503]: 0746960014E: DKIM-Signature field added (s=mail, d=workhome.augustow.pl)
Mar 23 16:57:10 mail postfix/qmgr[1221]: 0746960014E: from=<test1@workhome.augustow.pl>, size=2376, nrcpt=1 (queue active)
Mar 23 16:57:11 mail dovecot: imap-login: Login: user=<test1@workhome.augustow.pl>, method=PLAIN, rip=77.252.47.51, lip=172.17.0.2, mpid=1382, TLS, session=<MwhdVJP3MtxN/C8z>
Mar 23 16:57:12 mail postfix/submission/smtpd[1369]: disconnect from unknown[77.252.47.51] ehlo=2 starttls=1 auth=1 mail=1 rcpt=1 data=1 quit=1 commands=8
Mar 23 16:57:19 mail postfix/smtpd-amavis/smtpd[1404]: connect from localhost[127.0.0.1]
Mar 23 16:57:19 mail postfix/smtpd-amavis/smtpd[1404]: D8C126001DC: client=localhost[127.0.0.1]
Mar 23 16:57:19 mail postfix/cleanup[1222]: D8C126001DC: message-id=<000001d95da0$2124ca30$636e5e90$@workhome.augustow.pl>
Mar 23 16:57:19 mail postfix/qmgr[1221]: D8C126001DC: from=<test1@workhome.augustow.pl>, size=3485, nrcpt=1 (queue active)
Mar 23 16:57:19 mail amavis[1228]: (01228-01) Passed CLEAN {RelayedOpenRelay}, [77.252.47.51]:56935 [77.252.47.51] <test1@workhome.augustow.pl> -> <l.naszewski@gmail.com>, Queue-ID: 0746960014E, Message-ID: <000001d95da0$2124ca30$636e5e90$@workhome.augustow.pl>, mail_id: Xlv0R3xV1u9o, Hits: 0.7, size: 3243, queued_as: D8C126001DC, 9505 ms
Mar 23 16:57:19 mail postfix/smtp-amavis/smtp[1378]: 0746960014E: to=<l.naszewski@gmail.com>, relay=127.0.0.1[127.0.0.1]:10024, delay=10, delays=0.44/0.01/0.01/9.5, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as D8C126001DC)
Mar 23 16:57:19 mail postfix/qmgr[1221]: 0746960014E: removed
Mar 23 16:57:20 mail postfix/smtp[1409]: connect to gmail-smtp-in.l.google.com[2a00:1450:400c:c09::1a]:25: Cannot assign requested address
Mar 23 16:57:20 mail postfix/postscreen[1410]: CONNECT from [10.5.101.1]:60022 to [172.17.0.2]:25
Mar 23 16:57:20 mail postfix/postscreen[1410]: PASS OLD [10.5.101.1]:60022
Mar 23 16:57:20 mail postfix/postscreen[1410]: cache btree:/var/lib/postfix/postscreen_cache full cleanup: retained=5 dropped=0 entries
Mar 23 16:57:20 mail postfix/smtpd[1411]: connect from unknown[10.5.101.1]
Mar 23 16:57:20 mail postfix/smtp[1409]: warning: host gmail-smtp-in.l.google.com[64.233.166.27]:25 greeted me with my own hostname mail.workhome.augustow.pl
Mar 23 16:57:20 mail postfix/smtp[1409]: warning: host gmail-smtp-in.l.google.com[64.233.166.27]:25 replied to HELO/EHLO with my own hostname mail.workhome.augustow.pl
Mar 23 16:57:20 mail postfix/smtp[1409]: D8C126001DC: to=<l.naszewski@gmail.com>, relay=gmail-smtp-in.l.google.com[64.233.166.27]:25, delay=0.73, delays=0.01/0.02/0.71/0, dsn=5.4.6, status=bounced (mail for gmail.com loops back to myself)
Mar 23 16:57:20 mail postfix/smtpd[1411]: disconnect from unknown[10.5.101.1] ehlo=1 quit=1 commands=2
Mar 23 16:57:20 mail postfix/cleanup[1222]: 9B5356001DE: message-id=<20230323155720.9B5356001DE@mail.workhome.augustow.pl>
Mar 23 16:57:20 mail postfix/qmgr[1221]: 9B5356001DE: from=<>, size=5449, nrcpt=1 (queue active)
Mar 23 16:57:20 mail postfix/bounce[1412]: D8C126001DC: sender non-delivery notification: 9B5356001DE
Mar 23 16:57:20 mail postfix/qmgr[1221]: D8C126001DC: removed
Mar 23 16:57:20 mail dovecot: lmtp(1414): Connect from local
Mar 23 16:57:20 mail dovecot: lmtp(test1@workhome.augustow.pl)<1414><gQrXJ+B2HGSGBQAA9Pu0KA>: sieve: msgid=<20230323155720.9B5356001DE@mail.workhome.augustow.pl>: stored mail into mailbox 'INBOX'
Mar 23 16:57:20 mail postfix/lmtp[1224]: 9B5356001DE: to=<test1@workhome.augustow.pl>, relay=mail.workhome.augustow.pl[/var/run/dovecot/lmtp], delay=0.05, delays=0/0/0.03/0.01, dsn=2.0.0, status=sent (250 2.0.0 <test1@workhome.augustow.pl> gQrXJ+B2HGSGBQAA9Pu0KA Saved)
Mar 23 16:57:20 mail dovecot: lmtp(1414): Disconnect from local: Client has quit the connection (state=READY)
Mar 23 16:57:20 mail postfix/qmgr[1221]: 9B5356001DE: removed
Mar 23 16:57:44 mail dovecot: imap(test1@workhome.augustow.pl)<1382><MwhdVJP3MtxN/C8z>: Logged out in=3094 out=5767 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0

**Comment by casperklein** [comment]
It seems to me, that all outgoing tcp/25 traffic is redirected to `localhost:25`:

` Mar 23 16:57:20 mail postfix/smtp[1409]: warning: host gmail-smtp-in.l.google.com[64.233.166.27]:25 greeted me with my own hostname mail.workhome.augustow.pl`

`<(mailto:lukasz@gmail.com)>: mail for gmail.com loops back to myself`

**Comment by infortek1991** [comment]
Hallo,

Thank You all for Your help in solving the problem. My mail is finally working. :)
The reason was sending on port 25, and without the correct PTR and DKIM record.
Everyone who will configure mail, please remember to configure A records, SPF, DMARC, DKIM, SSL, PTR - all these are important.
Thanks again for Your help. :)

**Comment by stratisoft** [comment]
Sometimes the opendkim Folder is not copied. with Domain mail.abusiness.cloud / abusiness.cloud it works and with mail.abusiness.net / abusiness.net it not works. I dont know why!? Here is my Solution / Workaround:

#!/bin/bash

domain="abusiness.net"
domain_mail="mail.abusiness.net"
mailserver_name="mailserver-test"

docker run -d --name ${mailserver_name} \
  --hostname $domain_mail \
  --domainname $domain \
  --network $network_name \
  --network $network_name_ip6 \
  --restart=unless-stopped \
  --log-opt max-size=250m \
  --log-opt max-file=2 \
  -v ${mailserver_name}_data:/var/mail \
  -v /etc/letsencrypt:/etc/letsencrypt:ro \
  -v /root/docker-mailserver-data/$domain_mail:/tmp/docker-mailserver \
  -e ENABLE_SPAMASSASSIN=1 \
  -e SPAMASSASSIN_SPAM_TO_INBOX=1 \
  -e MOVE_SPAM_TO_JUNK=0 \
  -e SPAM_SUBJECT="***Spam*** " \
  -e SA_KILL=10.0 \
  -e ENABLE_RSPAMD=0 \
  -e ENABLE_CLAMAV=1 \
  -e ENABLE_FAIL2BAN=1 \
  -e SSL_TYPE=manual \
  -e ENABLE_TLS=1 \
  -e SSL_CERT_PATH=/etc/letsencrypt/live/$domain_mail/fullchain.pem \
  -e SSL_KEY_PATH=/etc/letsencrypt/live/$domain_mail/privkey.pem \
  -p 25:25 \
  -p 143:143 \
  -p 465:465 \
  -p 587:587 \
  -p 993:993 \
  mailserver/docker-mailserver:latest

# Add Accounts
docker cp /tmp/accounts-${mailserver_name}.sh ${mailserver_name}:/tmp/accounts.sh
docker exec -i ${mailserver_name} bash /tmp/accounts.sh

# DKIM Setup
docker exec -i ${mailserver_name} setup config dkim

# copy opendkim Directory from /tmp to /etc, because sometimes it does this not automatically!
# The file mail.private serves as an indicator that it did not work.
echo "Check if /tmp/docker-mailserver/opendkim Folder is copied..."
if [ ! -f /etc/opendkim/keys/$domain/mail.private ]; then
    docker exec -i ${mailserver_name} cp -ar --preserve=all /tmp/docker-mailserver/opendkim /etc
    # Permissions must be set to opendkim
    docker exec -i ${mailserver_name} chown -R opendkim:opendkim /etc/opendkim

    echo "The Docker-Setup did not copy the /etc/opendkim Folder. We fixed it for you!"
else
    echo "Good News: Files from opendkim Folder already exists at /etc/opendkim"
fi
