### ISSUE TITLE
docs: update earlier versions or archive

### ISSUE THREAD

**Issue by polarathene** [docker-mailserver/docker-mailserver#3196]
## Description

As noted in a [recent PR](https://github.com/docker-mailserver/docker-mailserver/pull/3190#issuecomment-1477288498) that adjusted docs to prefer the `latest` version alias (_symlinked folder on `gh-pages` branch to the latest tagged release folder_), the "canonical" link for earlier versions of the docs is `edge`, while future releases will use `latest`.

- It would be good to update the previous versions as well, but this would need to be done directly on the `gh-pages` branch.
- CI workflow for docs could be improved to support manual trigger with inputs, but earlier versions of docs are tied to their tagged commit, while the version of the docs generator is not and some feature syntax has been deprecated, updating those docs with new builds would break them (_unless using the version of the docs generator at that point in time_).
- Updating the `v11.1` docs to resolve https://github.com/docker-mailserver/docker-mailserver/issues/2688 may not be worth the hassle right now (_but can be done with a manual build locally, and applying the same changes the CI does for production docs_).

I'd like to consider archiving older versions away, but we probably shouldn't be more aggressive than a year since release (`v11.0` was released in April 2022).

**Comment by jrpear** [comment]
I just found myself linking to a particular version of the docs in an issue. If we archive the docs after a year, people reading that issue in a year will lose context.

Mozilla has chosen to keep old docs up even in a maybe broken state: https://firefox-source-docs.mozilla.org/security/nss/legacy/index.html

I think we shouldn't start archiving old docs until they become a pain to maintain in any form.

**Comment by jrpear** [comment]
Good points. It doesn't really matter if the link I post is broken long in the future. Maintainers will know how to find the relevant info, and users will know that there are relevant docs *somewhere*. A link to `latest` might even last quite a while.

**Comment by georglauterbach** [comment]
What's the consens here? This issue is marked for v12.1.0, hence I'm applying a bit of pressure to resolve all issues for v12.1.0 as maintainers agreed v12.1.0 should be a "fast" release :)

**Comment by polarathene** [comment]
> What's the consens here?

Either a lack of time or interest to pursue the preferred options I think.

Nothing too pressing here, we can just close the issue, and optionally delete doc versions over a year old from `gh-pages` (_pretty much any release prior to v11_), but that's not causing any actual problems leaving them as-is.

I haven't looked into Netlify, I imagine we have over a thousand previews deployed that could be cleaned up. Not sure if there is any limits there.

**Comment by georglauterbach** [comment]
> optionally delete doc versions over a year old from `gh-pages` (_pretty much any release prior to v11_), but that's not causing any actual problems leaving them as-is.

I will sort this out :) I won't be too aggressive with deletions though. Maybe delete everything before v10.

> I haven't looked into Netlify, I imagine we have over a thousand previews deployed that could be cleaned up. Not sure if there is any limits there.

A small cleanup there should not hurt either. Can you do that? I'd take care of the rest and we can then close this.

**Comment by polarathene** [comment]
> Can you do that?

Doesn't seem to be easy for me to tackle atm. If an API is supported perhaps something could be scripted (_**EDIT:** [API available](https://docs.netlify.com/api/get-started/#deploys), get list of deploys, check timestamps, send delete request_), but I think we can leave it until it presents an actual problem.

In Sep 2021, they announced [from Oct 2021 there would be a retention policy introduced which deletes deploys older than 90 days](https://www.netlify.com/blog/automated-deploy-cleanup-and-new-deploy-retention-policies/), but not the latest published site. [Netlify related docs page](https://docs.netlify.com/site-deploys/manage-deploys/#automatic-deploy-deletion).

I'm not sure how the deploy previews for PRs with unique URL prefixes play into that, I'd have thought they'd be affected, but older PRs [like this one](https://github.com/docker-mailserver/docker-mailserver/pull/2129#issuecomment-898285978) still have working deploy links.

I have checked [deploys via the web UI](https://app.netlify.com/sites/dms-doc-previews/deploys), which isn't too helpful but there is 22 pages of 15 items each, plus 1 more page of 5, total deploys active is 335, starting from May 2021. The most recent deploys do show multiple for recent PRs, hence whenever a PR updates doc previews the retention policy is at least discarding the earlier previews for a PR after 90 days.

Our docs don't have too much disk usage AFAIK, or much traffic to the previews Netlify hosts, so we're not likely to have any problems there. Worst case, is manually deleting each deploy which involves several clicks (_each deploy item listed on a page needs to switch to a deploy details page, then a drop down to delete_).

---

335 deploys isn't too bad, should be fine.

**Comment by polarathene** [comment]
> I won't be too aggressive with deletions though. Maybe delete everything before v10.

That's fine. Maybe only ever a concern with the version selector list growing long.

Probably easier to remove a full major version series, so if it makes more sense to remove old docs versions when 2 years have passed since the last release of a series, go with that :man_shrugging: :+1:
