### ISSUE TITLE
[FR] implement intelligent grey listing

### ISSUE THREAD

**Issue by RebelSoftware** [docker-mailserver/docker-mailserver#3215]
# Feature Request

## Context
to reduce spam greylisting can be a very effective tool, however it causes many issues for the timely delivery of email and end users complain.

My own implementing of greylisting was very shortlived after receiving numerous complaints within hours of turning it on. I have not re-implemented greylisting since then, about 5 years ago.

The default delay is particularly a problem when getting security codes by email which have very short lifespans often measured in minutes. the user never receives the code even though they are hovering over their mail client waiting to pounce.

### Is your Feature Request related to a Problem?
Yes, spam reduction

### Describe the Solution you'd like
Can I suggest looking to implement intelligent grey listing, this means that the email is automatically passed through if extra checks pass such as valid SPF records

This active project seems to fit the bill and is already available for postfix
https://github.com/evgeni/bley

I am not suggesting it is the solution to use, I am not related to that project however it seems an excellent starting point.

### Are you going to implement it?

Yes, because I know the probability of someone else doing it is low and I can learn from it.

### What are you going to contribute??

Not sure what I can contribute but am happy to if I get it working properly and securely

## Additional context
None

### Alternatives you've considered
None at this stage

### Who will that Feature be useful to?
All users wishing to reduce spam but not at the loss of timely email delivery. so in short administrators of mail systems rather than individual users

### What have you done already?
I am just now implementing Docker-mailserver for the first time and was reviewing the existing greylisting tool as it implements first sight greylisting apparently irrespective of the reputation of the sender (SPF/DKIM) it is a blunt force tool.

As such I started looking for alternatives.

**Comment by georglauterbach** [comment]
As of now, you can use Postgrey (with `ENABLE_POSTGREY=1`), but I already linked a pending PR that introduces a new ENV (`RSPAMD_GREYLISTING`), which basically is a spam-score-based greylisting solution that behaves better than Postgrey.

**Comment by RebelSoftware** [comment]
@georglauterbach 
Thanks

I am new to rspamd it will be interesting to see how well it works, Most certainly it will be an improvement on the blunter approach.
