### ISSUE TITLE
DKIM signing with RSpamd

### ISSUE THREAD

**Issue by alexanderadam** [docker-mailserver/docker-mailserver#3220]
# Subject

Other

## Description

Hi @georglauterbach  here's the issue [as wished](https://github.com/orgs/docker-mailserver/discussions/3207#discussioncomment-5486842) :wink: 

I followed [the documentation](https://docker-mailserver.github.io/docker-mailserver/edge/config/security/rspamd/#dkim-signing) but outgoing emails are still not signed.
I'm not seeing errors in the log so what's the best way to debug this?

The email headers are missing.

<details>
  <summary>Volume mounts (click to expand)</summary>

```
/etc/letsencrypt        => /etc/letsencrypt/
/etc/localtime  => /etc/localtime
/var/run/user/1001/podman/podman.sock   => /var/run/docker.sock
/home/user/volumes/mailserver/logs       => /var/log/mail/
/home/user/volumes/mailserver/supervisor_logs    => /var/log/supervisor/
/home/user/volumes/mailserver/state      => /var/mail-state/
/home/user/volumes/mailserver/mail       => /var/mail/
/home/user/volumes/mailserver/config/redis.conf  => /etc/rspamd/local.d/redis.conf
/home/user/volumes/mailserver/config     => /tmp/docker-mailserver/
/home/user/volumes/mailserver/config/dkim_signing.conf   => /etc/rspamd/local.d/dkim_signing.conf
```

</details>

<details>
  <summary>ENV variables (click to expand)</summary>

```bash
   2   │ ACCOUNT_PROVISIONER=FILE
   3   │ container=podman
   4   │ DOCKER_HOST=unix:///var/run/user/1001/podman/podman.sock
   5   │ domainname=a-domain.com
   6   │ ENABLE_AMAVIS=0
   7   │ ENABLE_CLAMAV=1
   8   │ ENABLE_DNSBL=1
   9   │ ENABLE_FAIL2BAN=1
  10   │ ENABLE_OPENDKIM=False
  11   │ ENABLE_POSTGREY=1
  12   │ ENABLE_RSPAMD=1
  13   │ ENABLE_RSPAMD_REDIS=0
  14   │ ENABLE_SPAMASSASSIN=0
  15   │ ENABLE_SPAMASSASSIN_KAM=0
  16   │ ENABLE_UPDATE_CHECK=1
  17   │ FETCHMAIL_POLL=300
  18   │ HOME=/root
  19   │ hostname=a-domain.com
  20   │ HOSTNAME=host
  21   │ LDAP_BIND_DN=
  22   │ LDAP_BIND_PW=
  23   │ LDAP_QUERY_FILTER_ALIAS=(&(objectClass=inetOrgPerson)(mailAlias=%s))
  24   │ LDAP_QUERY_FILTER_DOMAIN=(|(mail=*@%s)(mailAlias=*@%s)(mailGroupMember=*@%s))
  25   │ LDAP_QUERY_FILTER_GROUP=(&(objectClass=inetOrgPerson)(mailGroupMember=%s))
  26   │ LDAP_QUERY_FILTER_SENDERS=(&(objectClass=inetOrgPerson)(|(mail=%s)(mailAlias=%s)(mailGroupMember=%s)))
  27   │ LDAP_QUERY_FILTER_USER=(&(objectClass=inetOrgPerson)(mail=%s))
  28   │ LDAP_SEARCH_BASE=
  29   │ LDAP_SERVER_HOST=
  30   │ LETSENCRYPT_mail_EMAIL=letsencrypt.57@a-domain.com
  31   │ LETSENCRYPT_mail_TEST=True
  32   │ LETSENCRYPT_TEST=False
  33   │ LOG_LEVEL=info
  34   │ MOVE_SPAM_TO_JUNK=1
  35   │ NETWORK_INTERFACE=tap0
  36   │ ONE_DIR=1
  37   │ OVERRIDE_HOSTNAME=a-domain.com
  38   │ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  39   │ PODMAN_ROOTLESS=true
  40   │ POSTGREY_AUTO_WHITELIST_CLIENTS=5
  41   │ POSTGREY_DELAY=300
  42   │ POSTGREY_MAX_AGE=35
  43   │ POSTGREY_TEXT=Delayed by Postgrey
  44   │ POSTMASTER_ADDRESS=admin@a-domain.com
  45   │ RSPAMD_LEARN=1
  46   │ SASLAUTHD_MECHANISMS=pam
  47   │ SASLAUTHD_MECH_OPTIONS=
  48   │ SPAMASSASSIN_SPAM_TO_INBOX=1
  49   │ SPOOF_PROTECTION=1
  50   │ SSL_TYPE=letsencrypt
  51   │ SUPERVISOR_LOGLEVEL=info
  52   │ TERM=xterm
  53   │ TLS_LEVEL=modern
  54   │ TZ=Europe/Berlin
  55   │ VIRTUAL_HOST=a-domain.com
```

</details>

<details>
  <summary>dkim_signing.conf (click to expand)</summary>

```conf
enabled = true;

# Default path to key, can include '$domain' and '$selector' variables
# path = "/var/lib/rspamd/dkim/$domain.$selector.key";
path = "/tmp/docker-mailserver/rspamd_dkim_keys/$domain/keys/$selector.private";

# Default selector to use
selector = "mail";


sign_authenticated = true;
sign_local = true;

use_domain = "header";
use_redis = false; # don't change unless Redis also provides the DKIM keys
use_esld = true;
check_pubkey = true;

domain {
      a-domain.com {
        path = "/tmp/docker-mailserver/rspamd_dkim_keys/a-domain.com/keys/mail.private";
        selector = "mail";
    }
      some-domain.com {
        path = "/tmp/docker-mailserver/rspamd_dkim_keys/some-domain.com/keys/mail.private";
        selector = "mail";
    }
      another-domain.com {
        path = "/tmp/docker-mailserver/rspamd_dkim_keys/another-domain.com/keys/mail.private";
        selector = "mail";
    }
  }
```

</details>

<details>
  <summary>directory structure on the host (click to expand)</summary>

```bash
lh /home/user/volumes/mailserver/config/rspamd_dkim_keys
Permissions Size User Date Modified Name
drwxr-xr-x     - user  29 Mar 17:06   ./
drwxrwxr-x     - user  29 Mar 22:25   ../
drwxr-xr-x     - user  29 Mar 17:06   some-domain.com/
drwxr-xr-x     - user  29 Mar 17:06   another-domain.com/
drwxr-xr-x     - user  29 Mar 17:00   a-domain.com/

lh /home/user/volumes/mailserver/config/rspamd_dkim_keys/some-domain.com
Permissions Size User Date Modified Name
drwxr-xr-x     - user  29 Mar 17:06   ./
drwxr-xr-x     - user  29 Mar 17:06   ../
drwxr-xr-x     - user  29 Mar 18:23   keys/

lh /home/user/volumes/mailserver/config/rspamd_dkim_keys/some-domain.com/keys
Permissions Size User Date Modified Name
drwxr-xr-x     - user  29 Mar 18:23   ./
drwxr-xr-x     - user  29 Mar 17:06   ../
.rw-r-----  1.7k user  29 Mar 22:25   mail.private
.rw-rw-r--   455 user  29 Mar 22:25   mail.txt
```

</details>

**Comment by georglauterbach** [comment]
Setup looks good at first sight. Please provide the (anonymized of needed) output of

1. `rspamadm configdump`
2. `cat /var/log/supervisor/rspamd.log`

when running these commands inside the container.

**Comment by georglauterbach** [comment]
> Does it still need a `chown _rspamd /tmp/docker-mailserver/rspamd_dkim_keys/some-domain.com/keys/mail.private` afterwards?

Maybe; it depends on how you want to configure it. The user `_rspamd` will need to be able to

1. actually go into and list files inside the directory
2. then read the actual file

> And why does the user start with an underscore?

Good question; that's just the way it is on Debian..

**Comment by alexanderadam** [comment]
@georglauterbach thanks to your hint a got the permissions issue fixed and now the emails are signed.
But there's still something off and I guess it's related to the DNS entry.

Could you please elaborate how the txt needs to be interpreted?

It looks like

```
mail._domainkey IN TXT ( "v=DKIM1; k=rsa; "
	"p=MIIBIFooBarBaz…2m8a/0"
	"JkzK6…IBananaDAQAB"
) ;
```

And this obviously isn't how I should add it in the portal of my provider, right?
I guess this string needs to be concatenated, right? So that it looks like `"v=DKIM1; k=rsa; p=MIIBIFooBarBaz…2m8a/0JkzK6…IBananaDAQAB"`. Does the `/0` mean something special?
Or is there just a way how I could see exactly how this entry should look like?

>> And why does the user start with an underscore?
> Good question; that's just the way it is on Debian..

Actually the other users like `dovecot`, `opendkim`, `postgrey`, `opendmarc`, `clamav`, `postfix`, `dovenull` and `docker` look pretty normal.
`_rspamd` is the only user beginning with an underscore in the whole DMS image.

**Comment by georglauterbach** [comment]
Because you have `check_pubkey = true;`, Rspamd should first of all tell you in the log that there is a mismatch - please check that as it helps in confirming that the private key does not match the public key.

---

The public key files Rspamd (and OpenDKIM alike) produces is very weird IMO, but it seems like this is a standard.. it produces the notation tools like `dig` produce, kind of.

> And this obviously isn't how I should add it in the portal of my provider, right?

Yes, this is the presentation of tools like `dig`.

> I guess this string needs to be concatenated, right?

Indeed.

> So that it looks like `"v=DKIM1; k=rsa; p=MIIBIFooBarBaz…2m8a/0JkzK6…IBananaDAQAB"`.

Correct.

> Does the /0 mean something special?

No.

> Or is there just a way how I could see exactly how this entry should look like?

I can show you: when I query my own record, `dig` produces

```console
$ dig @1.1.1.1 +short TXT dkim-rsa._domainkey.example.com
"v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0ZHNlO13HU3P0vfSwmdaTv8iJiKXY9s7F2G+j5LU9BuREFXJIMPKIVuOBLYs9xKZXxTXYzUMTUFd3e1ykQEtMOCWM9S6dodWXNhwobXzBgUJl46ui1ptp9V0ypkZfJO5k279LGdNRYAuDW1HiYo1e+aj+T/mRj4z9JHLiOXaXROqEbx+SfDZceSK+MPY7P5wr" "qWLdQtgwwjLohMbZ0aFlq8OZJbd3uV29Egfxian06UgY2e04cp54/3MEnlolZ9BnqcASXBPK+D+W8+kP/3QMAWcX3CMHICcqGQhOkfA4JcKE48041f9ilv9dCp56Rlw1eF5914Eue8cX0wXTchMWwIDAQAB"
```

---

About the user name: this is nothing to worry about. Thats really just how someone chose to name the user - no special meaning. At least I haven't come across anything special.

**Comment by alexanderadam** [comment]
@georglauterbach it seems to be more permission errors :thinking: 

```
#4306(rspamd_proxy) <8d15ed>; proxy; dkim_module_load_key_format: cannot load dkim key /tmp/docker-mailserver/rspamd_dkim_keys/…/keys/mail.private: cannot stat key file: '/tmp/docker-mailserver/rspamd_dkim_keys/…/keys/mail.private' Permission denied
```

Which should be the owner, group and permissions on private and public key?

**Comment by georglauterbach** [comment]
> Does the DKIM need to be defined on the dedicated domain or its MX if the sender domain is different from its MX?

I do not understand this question. The DNS record for the DKIM is just there to fetch the public key to check the signature. Whether you use `this._domainkey.example.com` or `sometotallydifferentthing._domainkey.example.com` does not matter, as long as Rspamd knows about it and the keys were created with the proper record name.

I recommend you recreate the keys, because I had a similar issue when I started out. After starting anew with a clean state, it worked.

If this not work, then please post what the records look like here so we can investigate further.

**Comment by georglauterbach** [comment]
Because OpenDKIM is still installed, you can also use [`opendkim-testkey`](http://www.opendkim.org/opendkim-testkey.8.html) - this was a nice debugging tool I used.

**Comment by polarathene** [comment]
> Good question; that's just the way it is on Debian..

I haven't checked as it's kind of a hassle, but since you source the ARM package from a different source (Debian instead of rspamd repo?), are you sure that it's consistent?

I know Debian packages tend to stray a bit from upstream, so there is some risk there.

**Comment by georglauterbach** [comment]
On my M1 machine, I think it checked out. I can verify that tomorrow though.

**Comment by polarathene** [comment]
Could you also verify if your M1 is using Vectorscan? I'm not sure how many differences there are between Debian packaging and Upstream Rspamd repo. They're meant to be publishing ARM64 releases now, but you'd probably want to check that upstream also provides builds with Vectorscan?

Likewise with the x86_64 builds, they should be using Hyperscan I think, but I'm not too experienced with building and packaging such projects. I have a `Dockerfile` that builds rspamd and attempts to package it, but the only testing I did was if `rspamd --version` was successful (_failed when required shared libraries were missing or version mismatched from build_). I'll be making a PR for that to rspamd at some point (_presently juggling that, DMS and some other commitments_).

**Comment by georglauterbach** [comment]
Preliminary results:

```console
$ docker run --rm -it mailserver-testing:ci rspamd --version
Rspamd daemon version 3.4
$ docker run --rm -it mailserver-testing:ci cat /etc/passwd
root:x:0:0:root:/root:/bin/bash
...
redis:x:112:114::/var/lib/redis:/usr/sbin/nologin
_rspamd:x:113:115:rspamd spam filtering system,,,:/var/lib/rspamd:/usr/sbin/nologin
syslog:x:114:65534::/home/syslog:/usr/sbin/nologin
docker:x:5000:5000::/home/docker:/bin/bash
```

How do I check for Vectorscan/Hyperscan?

**Comment by polarathene** [comment]
> How do I check for Vectorscan/Hyperscan?

I have no clue :sweat_smile: 

I just know that they're used at build time with CMake for rspamd. I don't think I saw any linked library in the rspamd binaries via `readelf -d rspamd`, maybe it was compiled in statically, really not my forte :sweat_smile: 

All I know is they're meant to be relevant for providing the regex engine that performs well? If you don't have any idea, that's fine and if everything appears to work fine, perhaps we can just assume both builds include their respective engine.

**Comment by alexanderadam** [comment]
> Because OpenDKIM is still installed, you can also use [`opendkim-testkey`](http://www.opendkim.org/opendkim-testkey.8.html) - this was a nice debugging tool I used.

I deleted the keys and `opendkim-testkey` is indeed a great way to have quick checks on the DKIM config. Thank you.

I'll close this issue then, right?
