### ISSUE TITLE
Is there a statistical function?

### ISSUE THREAD

**Issue by lizonggang** [docker-mailserver/docker-mailserver#3223]
# Subject

Is there a statistical function?

## Description

Is there a command related to viewing statistics? For example, how many emails are sent/received per mailbox per day?

**Comment by georglauterbach** [comment]
When you enable Rspamd, you have something similar with Rspamd's web interface: <https://rspamd.com/webui/>

**Comment by lizonggang** [comment]
> 当您启用 Rspamd 时，您会看到与 Rspamd 的网络界面类似的东西：https://rspamd.com/webui/

Thanks, I'll go learn it.

**Comment by lizonggang** [comment]
> When you enable Rspamd, you have something similar with Rspamd's web interface: https://rspamd.com/webui/

Thanks, I'll go learn it.

**Comment by georglauterbach** [comment]
I'll close this as done then ;) The version of Rspamd that we employ is even newer than shown in the link :)

**Comment by lizonggang** [comment]
> I'll close this as done then ;) The version of Rspamd that we employ is even newer than shown in the link :)

Hi, brother, I didn't see the rspamd configuration in the v11.3.1 version, I need to install it separately, is that right? 
Or use the master branch?

**Comment by georglauterbach** [comment]
You need to use the `:edge` tag as of today. Tomorrow, v12.0.0 will be released, and this release will contain Rspamd.

**Comment by lizonggang** [comment]
> You need to use the `:edge` tag as of today. Tomorrow, v12.0.0 will be released, and this release will contain Rspamd.

Ok,  I have used `:edge` tag. 

I am following.

**Comment by georglauterbach** [comment]
We do have a [**documentation**](https://docker-mailserver.github.io/docker-mailserver/edge/) that you can read. Please refer to [this section](https://docker-mailserver.github.io/docker-mailserver/edge/usage/#tagging-convention).

Make sure to read through our docs thoroughly. Thank you!

**Comment by lizonggang** [comment]
Ok bro, I'm clear again.
