### ISSUE TITLE
other: fts-xapian-plugin does not work after upgrading dms to 12.0

### ISSUE THREAD

**Issue by JiLleON** [docker-mailserver/docker-mailserver#3247]
### Subject

Other

### Description

If you use the fts-xapian-plugin specified in the documentation https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/full-text-search/#xapian , then after updating dms to 12.0, it will stop working for you. On 11.3.1 I am not getting any errors. I found [mention of a similar problem since 2022 in the repository of this plugin](https://github.com/grosjo/fts-xapian/issues/125). This was not fixed, and after a while the error was closed by the initiator. I think it would be right to remove the recommendation of this plugin from the documentation concerning 12.0, latest and edge, because everything works on 11.3.1 (I checked on my amd64 configuration, Debian 11, Docker 23.0.2, build 569dd73, Docker Compose v2.17.2). Or you can specify a link in the documentation to your answer [here](https://github.com/docker-mailserver/docker-mailserver/issues/3100#issuecomment-1435971388) to a similar error as an option for using this plugin.
### What happened and when does this occur?
when start container:
```
[  DEBUG  ]  Configuring Amavis
[  DEBUG  ]  Spam emails will be moved to the Junk folder
sievec: Fatal: Couldn't load required plugin /usr/lib/dovecot/modules/lib21_fts_xapian_plugin.so: Module is for different ABI version 2.3.ABIv13(2.3.13) (we have 2.3.ABIv20(2.3.20))
chown: cannot access '/usr/lib/dovecot/sieve-global/after/spam_to_junk.svbin': No such file or directory
```

**Comment by georglauterbach** [comment]
You are correct! Sadly, this seems to be an upstream issue, i.e DMS cannot really do something about that, or Dovecot version is just too new :(

We should do something about the docs though, right. Could you provide a PR @JiLleON?

**Comment by georglauterbach** [comment]
Very nice, thank you very much!

**Comment by eleith** [comment]
when dovecot 2.4 is released, flatcurve will be included in dovecot core, making this plugin very easy to enable. 

until then, to use fts-flatcurve, one would have to manual compile both dovecot and flatcurve as stated in this [issue](https://github.com/slusarz/dovecot-fts-flatcurve/issues/28)

**Comment by eleith** [comment]
originally, DMS only had solr as an option for FTS. but solr was very memory/cpu intense and xapian proved to be much more efficient.

i helped introduce it in [this PR](https://github.com/docker-mailserver/docker-mailserver/pull/2064/files)

today, those libraries are [still included](https://github.com/docker-mailserver/docker-mailserver/blob/master/target/scripts/build/packages.sh#L101) but apparently they no longer work (and likely one reason why dovecot is moving to flatcurve)

unfortunately, things are in a broken state until dovecot pushes out 2.4 (which may be awhile), so users will either have to choose to compile their own dovecot, use solr or go without search.

**Comment by tbutter** [comment]
i think xapian is a really useful fts index and there is currently no other alternative with small overhead.
the problem currently is just a version conflict between debian buster and the community repo. would it be acceptable to compile fts_xapian at docker build? if this is an option for the project I can work on a pull request.
