### ISSUE TITLE
feature request: Allow setting `mail_max_userip_connections`

### ISSUE THREAD

**Issue by CDaut** [docker-mailserver/docker-mailserver#3254]
### Context

Some clients make a lot of connections for one IP or if you have multiple clients on the same network the server might not allow fetching mail because of this. By increasing `mail_max_userip_connections` this can be fixed.

### Description

By providing an environment variable in mailserver.env to adjust this setting this problem would be easily mitigatable.

### Alternatives

Corrently I have the file mounted manually via a docker volume. This is an okay workaround but caused e.g. issue #3250 .

### Applicable Users

This would be useful to all users with multiple devices on the same network.

### Are you going to implement it?

No, and I understand that it is highly likely no one will implement it. Furthermore, I understand that this issue will likely become stale and will be closed.

### What are you going to contribute?

I might get around to implementing this if I find out how to use envvars in config files and if my exam phase is over (+1 Month).

**Comment by georglauterbach** [comment]
What about using `user-patches.sh`? If you didn't know about it, our docs provide a good explanation :)

**Comment by ap-wtioit** [comment]
It should work like this:
https://docker-mailserver.github.io/docker-mailserver/latest/config/advanced/override-defaults/dovecot/#add-configuration

there is even a test for this feature:
https://github.com/docker-mailserver/docker-mailserver/blob/master/test/config/override-configs/dovecot.cf
https://github.com/docker-mailserver/docker-mailserver/blob/master/test/tests/parallel/set1/config_overrides.bats#L40

after looking at #3250 it seems you already have a dovecot folder in your project that is mounted to /etc/dovecot, and the ./config to /tmp/docker-mailserver/, do you have a dovecot.cf in ./config?

**Comment by georglauterbach** [comment]
@ap-wtioit is absolutely right! (Why didn't I think of this? :D). Closing this as the issue can easily be resolved.
