### ISSUE TITLE
other: issues with 12.0.0 and munin ssl-certificate-expiry

### ISSUE THREAD

**Issue by ap-wtioit** [docker-mailserver/docker-mailserver#3256]
### Subject

Other

### Description

The new fail2ban version in 12.0.0 seems to block servers using the [ssl-certificate-expiry](https://github.com/munin-monitoring/contrib/blob/master/plugins/ssl/ssl-certificate-expiry) munin plugin.

Right after the deployment we banned our own monitoring servers (i have an additional supervisor service running showing bans right in the container output):
```
mail    | Apr 13 11:46:53 mail postfix/smtpd[2507]: connect from redacted.domain.tld[256.256.256.256]                                                                                                          
mail    | Apr 13 11:46:53 mail postfix/smtpd[2507]: Anonymous TLS connection established from redacted.domain.tld[256.256.256.256]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature ECDSA (P-256) server-digest SHA256
mail    | Apr 13 11:46:53 mail postfix/smtpd[2507]: lost connection after STARTTLS from redacted.domain.tld[256.256.256.256]                                                                                  
mail    | Apr 13 11:46:53 mail postfix/smtpd[2507]: disconnect from redacted.domain.tld[256.256.256.256] ehlo=1 starttls=1 commands=2         
mail    | Apr 13 11:46:53 mail postfix/smtps/smtpd[2846]: connect from redacted.vpn[10.256.256.256]                                                                                                      
mail    | Apr 13 11:46:53 mail postfix/smtps/smtpd[2846]: Anonymous TLS connection established from redacted.vpn[10.256.256.256]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature ECDSA (P-256) server-digest SHA256                                                                                                                                                   
mail    | Apr 13 11:46:53 mail postfix/smtps/smtpd[2846]: lost connection after CONNECT from redacted.vpn[10.256.256.256]                                                                                
mail    | Apr 13 11:46:53 mail postfix/smtps/smtpd[2846]: disconnect from redacted.vpn[10.256.256.256] commands=0/0                                                                                     
mail    | Apr 13 11:46:53 mail postfix/submission/smtpd[2852]: connect from redacted.vpn[10.256.256.256]                                                                                                
mail    | Apr 13 11:46:53 mail postfix/submission/smtpd[2852]: Anonymous TLS connection established from redacted.vpn[10.256.256.256]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature ECDSA (P-256) server-digest SHA256                                                                                                                                             
mail    | Apr 13 11:46:53 mail postfix/submission/smtpd[2852]: lost connection after STARTTLS from redacted.vpn[10.256.256.256]                                                                         
mail    | Apr 13 11:46:53 mail postfix/submission/smtpd[2852]: disconnect from redacted.vpn[10.256.256.256] ehlo=1 starttls=1 commands=2                                                                 
mail    | 2023-04-13 11:46:53,689 fail2ban.filter         [849]: INFO    [postfix] Found 256.256.256.256 - 2023-04-13 11:46:53                                                                              
mail    | 2023-04-13 11:46:53,691 fail2ban.filter         [849]: INFO    [postfix] Found 10.256.256.256 - 2023-04-13 11:46:53                                                                                    
mail    | 2023-04-13 11:46:53,697 fail2ban.filter         [849]: INFO    [postfix] Found 10.256.256.256 - 2023-04-13 11:46:53                                                                                     
mail    | 2023-04-13 11:46:54,001 fail2ban.actions        [849]: NOTICE  [postfix] Ban 256.256.256.256
mail    | 2023-04-13 11:46:54,005 fail2ban.actions        [849]: NOTICE  [postfix] Ban 10.256.256.256
```

I'm still investigating which fail2ban filter expression / mode banned the monitoring server.

Edit: first i thought it was the smtp_hello_ plugin, but that didn't use STARTTLS in the code, i could then reproduce it with ssl-certificate-expiry

**Comment by georglauterbach** [comment]
This is IMO intended behavior of F2B, and not something DMS should take care of. Your workaround seems like a proper solution to. Clients that just connect but immediately disconnect again are suspicious, and F2B cannot know they are monitoring services. Ignoring these IPs specifically is sound to me.

**Comment by ap-wtioit** [comment]
> This is IMO intended behavior of F2B, and not something DMS should take care of.
Well, it is not the intended default behaviour of fail2ban, DMS changes the mode from `normal` to `aggressive`, the findtime to 1 week, bantime to 1 week and the maxretry to 2. Which makes it very sensitive to not only such monitoring plugins but also a lot of regular stuff that might happen (e.g. a lost connection twice a week from a node that is connecting via 4G or 3G). What makes it worse (from my point of view) is that those logs are not shown in the container log per default so others might have no clue why their mailserver is suddenly down.

Anyhow after adding a few more sanity integration tests on our side i followed the [docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/security/fail2ban/) for fail2ban and decided on our version of the settings:
```
[DEFAULT]

# "bantime" is the number of seconds that a host is banned.
bantime = 3h

# A host is banned if it has generated "maxretry" during the last "findtime"
# seconds.
findtime = 10m

# "maxretry" is the number of failures before a host get banned.
maxretry = 5

# "ignoreip" can be a list of IP addresses, CIDR masks or DNS hosts. Fail2ban
# will not ban a host which matches an address in this list. Several addresses
# can be defined using space (and/or comma) separator.
ignoreip = 127.0.0.1/8

# default ban action
# nftables-multiport: block IP only on affected port
# nftables-allports:  block IP on all ports
banaction = nftables-allports

[dovecot]
enabled = true

[postfix]
enabled = true
mode = extra

[postfix-dos]
enabled = true
filter = postfix[mode=ddos]
maxretry = 10
logpath = %(postfix_log)s
backend = %(postfix_backend)s


[postfix-sasl]
enabled = true

# This jail is used for manual bans.
# To ban an IP address use: setup.sh fail2ban ban <IP>
[custom]
enabled = true
bantime = 180d
port = smtp,pop3,pop3s,imap,imaps,submission,submissions,sieve
```

One more question: should we update the [config-examples/fail2ban-jail.cf](https://github.com/docker-mailserver/docker-mailserver/blob/master/config-examples/fail2ban-jail.cf) to reflect the new defaults? I would have found it more transparent if the values in there would have been the actual values present in the fail2ban installation in the server as default.

**Comment by georglauterbach** [comment]
This is actually why we recommend people to use the bug template for such problems. With the information you provided, I had to assume you are running `:v12.0.0` / `:latest`, which does not have the new F2B changes - even though I thought this might be the reason.

But you seem to be running `:edge`?

> (e.g. a lost connection twice a week from a node that is connecting via 4G or 3G).

A mail server node connecting via 3G / 4G? We are running aggressive mode for Postfix (and Postfix SASL), but not for Dovecot.

> What makes it worse (from my point of view) is that those logs are not shown in the container log per default so others might have no clue why their mailserver is suddenly down.

I agree; we should think about having this log in the "big mail server log" as well.


> One more question: should we update the [config-examples/fail2ban-jail.cf](https://github.com/docker-mailserver/docker-mailserver/blob/master/config-examples/fail2ban-jail.cf) to reflect the new defaults?

Absolutely! We forgot about that, sorry. Could you open a PR? I can the review and merge it directly.

---

If there are more such issues in the future, we might increase `finddtime` or `maxretries`.

**Comment by ap-wtioit** [comment]
Sorry for the missing info. It's because we are running edge + some custom patches, that i wanted to check for other peoples opinion first before labeling it a bug / issue of DMS.

I'll add the PR for the config-examples once i get the new default values for edge.

> A mail server node connecting via 3G / 4G?
It's not just mail server nodes connecting to mailservers but also clients sending mails directly (e.g. in our case for alerting) and they might have a wrong password (e.g. after it was rotated) or just a wonky connection. With 2 retries you are insta banning a lot of usecases (some legimitate usecases of DMS cause more than one match in the log files).

PS: i didn't notice #3243 was causing our issues and merged after 12.0.0, it took me a few days to verify the release for our infrastructure, that's why i said 12.0.0 in the beginning.

**Comment by georglauterbach** [comment]
No worries, no we know. We could raise `maxretries` back to 3, but I'd like to have feedback from @docker-mailserver/maintainers about that :) The change is currently "only" on `:edge`, so no harm done for poeple using stable releases (which one should be running in production).

---

One more note about our F2B docs: the page for F2B needs an overhaul in general IMO, just FYI.

**Comment by casperklein** [comment]
Introducing issues like this with `mode=aggressive` were also my concerns [here](https://github.com/docker-mailserver/docker-mailserver/issues/3178#issuecomment-1483471853).

We have two kinds of users:

1. DMS fail2ban is not strict enough, it should block more SPAM in it's default configuration
2. DMS fail2ban is too strict, it breaks monitoring tools and bans to fast on password typos

We'll never meet both requirements. I am team "more strict". However, I understand the problems that are introduced. Therefore I propose to revert https://github.com/docker-mailserver/docker-mailserver/pull/3243.

Everyone like me wanting it more strict, can do so easily via [configuration files](https://docker-mailserver.github.io/docker-mailserver/latest/config/advanced/optional-config/#files).

**Comment by georglauterbach** [comment]
> Introducing issues like this with `mode=aggressive` were also my concerns [here](https://github.com/docker-mailserver/docker-mailserver/issues/3178#issuecomment-1483471853).
> 
> We have two kinds of users:
> 
>     1. DMS fail2ban is not strict enough, it should block more SPAM in it's default configuration
> 
>     2. DMS fail2ban is too strict, it breaks monitoring tools and bans to fast on password typos
> 
> 
> We'll never meet both requirements. I am team "more strict". However, I understand the problems that are introduced. Therefore I propose to revert #3243.

I would really not like to revert this PR, but increase `maxretries`. @polarathene proposed a value of 6, and I am fine with this. I do think that F2B should note these attempts, as this is really useful IMO, but banning them after only 2 tries might really be too aggressive.

> Everyone like me wanting it more strict, can do so easily via [configuration files](https://docker-mailserver.github.io/docker-mailserver/latest/config/advanced/optional-config/#files).

The same argument holds for the opposite direction though :)

**Comment by casperklein** [comment]
My point was more: sticking as much as possible to upstream defaults (I assume they were chosen wisely after similar discussions we do at the moment) and let the user decide to keep or adjust these values.

**Comment by georglauterbach** [comment]
Then I propose a middle-ground. Let's keep the aggressive mode for the `postfix-sasl`, use normal again for `postfix`, and increase `maxretries` to `3` (original value) or `4`.

**Comment by polarathene** [comment]
Max retries 3 is rarely a well thought out choice AFAIK.

Worst case scenario, you're dealing with someone who is targeting you directly, but if they're able to guess your password in so few tries then you're better off with better security policy (including password management).

Other scenario, random bots and the like attempting login to X accounts with Y IP addresses? Number of retries is irrelevant beyond trying to deter the scaling of the attack. Ban time was raised as an improved deterrent for that AFAIK?

Online login attempts are slow / ineffective with reasonable entropy for the password. 10 should be no problem and barely would affect raise in resource usage for a DoS? Before 10 failures, legitimate user is likely to stop trying and realize they need to look up a password stored somewhere, or reset.

Unfortunately the find time was also raised a fair bit, so a user that has some friction due to a11y might result in a few accidental failures with manual input, and that stacks up over the days before max retries is reset :sweat_smile: I doubt it's that effective against bad actors at such a duration as well.

**Comment by georglauterbach** [comment]
Agreed. We can raise it to 6, or 10 - whatever the majority wants.

You are very much correct about findtime being so large, maxretries can be increased.

**Comment by ap-wtioit** [comment]
> random bots and the like attempting login to X accounts with Y IP addresses

I think fail2ban is not the tool for this scenario, AFAIK it was more designed to handle someone trying to break passwords by trying a bunch of them. At least that is what we use it for. If someone has lots of IPs (e.g. with IPv6, a VPN or you are running behind cloudflare) it get's really tricky to tune fail2ban for that. But you can easily catch the ones trying from one IP over weeks / months.

**Comment by casperklein** [comment]
> The new fail2ban version in 12.0.0 seems to block servers using the [ssl-certificate-expiry](https://github.com/munin-monitoring/contrib/blob/master/plugins/ssl/ssl-certificate-expiry?rgh-link-date=2023-04-13T12%3A02%3A05Z) munin plugin.

`mode=aggressive` also successfully blocks diagnostic services like [internet.nl](https://internet.nl/) or [mxtools](https://mxtoolbox.com). Whitelisting those IP addresses is not practical.

PS: What is the correct way to get the old/default behaviour? `mode = extra`?

**Comment by ap-wtioit** [comment]
The default behavior from fail2ban for postfix is [`mode = more`](https://github.com/fail2ban/fail2ban/blob/master/config/filter.d/postfix.conf#L73) which is equivalent to `mode = normal`. 

`mode = extra` would mean normal + auth (`authentication failed:(?! Connection lost to authentication server| Invalid authentication mechanism)`)

`mode = aggressive` is extra + ddos (lost connections (regardless if they are on purpose or not), fail2ban really only can prevent DOS). Also blocking lost connections could be a problem when we still make people/clients wait a quasi random number on first connect to detect bots if there are clients out there that have very strict timeouts.

**Comment by georglauterbach** [comment]
Then using `mode = extra` should be ideal for us, right?

**Comment by polarathene** [comment]
> But you can easily catch the ones trying from one IP over weeks / months.

Sure, but online attacks are much slower, if they're not putting load on your systems I don't think there's much damage. 10 tries a day for example is still under 12 bits of entropy (4096) and I would say 44 bits of entropy or more is where passwords _should be_, several billion times harder :sweat_smile: 

---

I've haven't got much opinion on mode choice, but `aggressive` sounds a bit too much from description above.
