### ISSUE TITLE
other: Unable to recieve email after chaging hostname from mail.example.com to example.com 

### ISSUE THREAD

**Issue by tim-field** [docker-mailserver/docker-mailserver#3284]
### Subject

I would like to configure a not documented mail server use case

### Description

I have **had** dockermailserver running successfully at mail.example.com for some time. Recently the PTR record on my IP address was set as example.com and this was effecting deliverability so I wanted to change to straight example.com.  I did this by setting `OVERRIDE_HOSTNAME=example.com`  in `mailserver.env` I also updated my MX records in my DNS moving them from mail.example.com to the example.com and waited for them to propagate.

Now however I can still **send email but cannot receive**.  In the logs I see the following 

```<tim@example.com>: Recipient address rejected: User unknown in local recipient table; from=<tim@test.com> to=<tim@example.com>``` 

Please let me know if you have any idea what I could do to get this working again. Thanks

**Comment by tim-field** [comment]
I found the docs for this here https://docker-mailserver.github.io/docker-mailserver/latest/faq/#can-i-use-a-nakedbare-domain-ie-no-hostname

for future travelers in this section 
> Add the latter line to docker-data/dms/config/postfix-main.cf.

you can just create an new `postfix-main.cf` file inside your linked config dir with the single change in it 

`mydestination = localhost.$mydomain, localhost`

( I was a bit confused about creating a new file in here for just this, but it seemed to work )

**Comment by polarathene** [comment]
Heads-up about a related PR that may introduce a change to `mydestination` in future release: https://github.com/docker-mailserver/docker-mailserver/pull/3264
