### ISSUE TITLE
[Question]: How does `mail.example.com` affect email address and LetsEncrypt / TLS cert

### ISSUE THREAD

**Issue by zzwxrchi** [docker-mailserver/docker-mailserver#3291]
### Subject

Domain address or subdomain address

### Description

Hi everyone, I have a question.

When we config "hostname: **mail**.xxxx.com". 
Which email address we'll use ? name@**mail**.xxxx.com or name@xxxx.com ?
And which letsencrypt certificate we need for ? mail.xxx.com or xxx.com ?

Thanks !!

**Comment by casperklein** [comment]
It's completely up to you. The hostname used for the mailserver has no direct relation to the email addresses configured.

Most people use `mail.example.com` for their mailserver, which is responsible for one or more domains like @example.com, @example2.com etc.

This is not specific to docker-mailserver, all mailserver are working this way.

**Comment by zzwxrchi** [comment]
> It's completely up to you. The hostname used for the mailserver has no direct relation to the email addresses configured.
> 
> Most people use `mail.example.com` for their mailserver, which is responsible for one or more domains like @example.com, @example2.com etc.
> 
> This is not specific to docker-mailserver, all mailserver are working this way.

Thank you very much @casperklein !!
