### ISSUE TITLE
[Question]: How to stop trying to resend email stuck in queue

### ISSUE THREAD

**Issue by zzwxrchi** [docker-mailserver/docker-mailserver#3292]
### Subject

I would like some feedback concerning a use case

### Description

Hi guys.

Someone hacked into one of my email accounts to send a bunch of spam. I deleted this account and changed the password for all other accounts. However, the mail server is still sending spam from the deleted account.

It seems are emails that could not have been sent before and are in queue. How can I stop their queue or delete them ?

The logs:

```console
$ docker compose logs -t | grep 266DB1A36D6

mailserver  | 2023-04-25T22:52:49.512347648Z Apr 26 00:52:49 mail postfix/qmgr[938]: 266DB1A36D6: from=<test@xxxxxx.com (**THE DELETED ACCOUNT**)>, size=22843, nrcpt=1 (queue active)
mailserver  | 2023-04-25T22:52:53.660017080Z Apr 26 00:52:53 mail postfix/smtp[16781]: 266DB1A36D6: host mta7.am0.yahoodns.net[67.195.228.109] said: 421 4.7.0 [TSS04] Messages from "XXX.XXX.XXX.XXX (**MY IP**)" temporarily deferred due to unexpected volume or user complaints - 4.16.55.1; see https://postmaster.yahooinc.com/error-codes (in reply to MAIL FROM command)
mailserver  | 2023-04-25T22:52:53.660087359Z Apr 26 00:52:53 mail postfix/smtp[16781]: 266DB1A36D6: lost connection with mta7.am0.yahoodns.net[67.195.228.109] while sending RCPT TO
mailserver  | 2023-04-25T22:52:55.047460578Z Apr 26 00:52:55 mail postfix/smtp[16781]: 266DB1A36D6: to=<SOMEONE@yahoo.com>, relay=mta7.am0.yahoodns.net[67.195.228.110]:25, delay=109300, delays=109294/2.8/2.6/0.17, dsn=4.7.0, status=deferred (host mta7.am0.yahoodns.net[67.195.228.110] said: 421 4.7.0 [TSS04] Messages from 193.84.177.134 temporarily deferred due to unexpected volume or user complaints - 4.16.55.1; see https://postmaster.yahooinc.com/error-codes (in reply to MAIL FROM command))
```

Thank you very much !!

**Comment by polarathene** [comment]
This is not the best answer, but should clear the entire queue (_all users mail presently in queue removed won't be delivered, thus any legit user mail sent may not be notified_). Run `postsuper -d ALL` command inside the DMS container: `docker exec container_name postsuper -d ALL`

You can find [more info and similar commands](https://bobcares.com/blog/postfix-delete-mail-queue/) with a search engine with keywords like "Postfix clear queue".
