### ISSUE TITLE
[QUESTION]: `NOQUEUE: reject: RCPT, Sender address rejected: not owned by user sender@example.com`

### ISSUE THREAD

**Issue by KasraFallahi** [docker-mailserver/docker-mailserver#3297]
### Subject

Other

### Description

Hi, I get this log when I try to send an email from my mail server:

    NOQUEUE: reject: RCPT from unknown[IP_ADDR]: 553  5.7.1 <sender@example.com>: Sender address rejected: not owned by user sender@example.com; from=<sender@example.com> to=<reciever@example.org> proto=ESMTP helo=<[IP_ADDR]>
I use LDAP configurations and this is .env file of docker container:

    OVERRIDE_HOSTNAME=mail.example.com
    DMS_DEBUG=0
    LOG_LEVEL=info
    ONE_DIR=1
    ACCOUNT_PROVISIONER=LDAP
    POSTMASTER_ADDRESS=admin@example.com
    ENABLE_UPDATE_CHECK=1
    UPDATE_CHECK_INTERVAL=1d
    PERMIT_DOCKER=host
    SPOOF_PROTECTION=1
    ENABLE_SRS=0
    ENABLE_OPENDKIM=1
    ENABLE_OPENDMARC=1
    ENABLE_POLICYD_SPF=1
    ENABLE_POP3=1
    ENABLE_CLAMAV=1
    ENABLE_RSPAMD=1
    ENABLE_RSPAMD_REDIS=0
    RSPAMD_LEARN=0
    RSPAMD_GREYLISTING=1
    RSPAMD_HFILTER=1
    RSPAMD_HFILTER_HOSTNAME_UNKNOWN_SCORE=6
    ENABLE_AMAVIS=1
    AMAVIS_LOGLEVEL=0
    ENABLE_DNSBL=1
    ENABLE_FAIL2BAN=1
    FAIL2BAN_BLOCKTYPE=drop
    ENABLE_MANAGESIEVE=1
    POSTSCREEN_ACTION=enforce
    SSL_TYPE=letsencrypt
    SSL_DOMAIN=example.com
    ENABLE_QUOTAS=1
    LOGROTATE_INTERVAL=weekly
    POSTFIX_INET_PROTOCOLS=all
    ENABLE_SPAMASSASSIN=0
    SPAMASSASSIN_SPAM_TO_INBOX=1
    ENABLE_SPAMASSASSIN_KAM=0
    MOVE_SPAM_TO_JUNK=1
    SA_TAG=2.0
    SA_TAG2=6.31
    SA_KILL=10.0
    SA_SPAM_SUBJECT=***SPAM*****
    ENABLE_FETCHMAIL=0
    FETCHMAIL_POLL=300
    #LDAP Section
    ENABLE_LDAP=1
    ACCOUNT_PROVISIONER=LDAP
    LDAP_SERVER_HOST="ldap://LDAP_IP_ADDR"
    LDAP_SEARCH_BASE="dc=example,dc=com"
    LDAP_BIND_DN="cn=admin,dc=example,dc=com"
    LDAP_QUERY_FILTER_USER="(&(mail=%s)(mailEnabled=TRUE))"
    LDAP_QUERY_FILTER_GROUP="(&(mailGroupMember=%s)(mailEnabled=TRUE))"
    LDAP_QUERY_FILTER_ALIAS="(&(mailAlias=%s)(mailEnabled=TRUE))"
    LDAP_QUERY_FILTER_DOMAIN="(|(mail=*@%s)(mailAlias=*@%s)(mailGroupMember=*@%s))"
    DOVECOT_USER_FILTER="(&(objectClass=inetOrgPerson)(mail=%u))"
    DOVECOT_PASS_FILTER="(&(objectClass=inetOrgPerson)(mail=%u))"
    DOVECOT_MAILBOX_FORMAT=maildir
    DOVECOT_AUTH_BIND=yes
    ENABLE_POSTGREY=0
    POSTGREY_DELAY=300
    POSTGREY_MAX_AGE=35
    POSTGREY_TEXT="Delayed by Postgrey"
    POSTGREY_AUTO_WHITELIST_CLIENTS=5
    ENABLE_SASLAUTHD=1
    SASLAUTHD_MECHANISMS=ldap
    SASLAUTHD_LDAP_SERVER="ldap://10.0.0.2:1389"
    SASLAUTHD_LDAP_FILTER="(&(uid=%U)(objectClass=person))"
    SRS_SENDER_CLASSES=envelope_sender
    RELAY_PORT=25
    DOVECOT_USER_ATTRS="homeDirectory=home,=uid=5000,=gid=5000"

**Comment by polarathene** [comment]
This is because you have enabled `SPOOF_PROTECTION=1`. This prevents a mail account from sending as anybody else.

There is some information shared [here](https://github.com/docker-mailserver/docker-mailserver/issues/3289#issuecomment-1521333815) if you want to read more about it.

Presently we lack documentation / support for how to configure allowing more addresses for an account to send as. If you don't need this disable the feature, this is one of the reasons it is not enabled by default.
