### ISSUE TITLE
other: if-statement style change

### ISSUE THREAD

**Issue by casperklein** [docker-mailserver/docker-mailserver#3302]
### Subject

Other

### Description

@georglauterbach @polarathene

I think we talked before and there was con-sense. But before providing a PR I wanted to get sure 😉

I'd like to change the style of our if-statements from

```bash
if [[ ${#} -lt 3 ]]
then
  _log 'error' 'At least three parameters must be given'
  __usage
  exit 1
fi
```

to

```bash
if [[ ${#} -lt 3 ]]; then
  _log 'error' 'At least three parameters must be given'
  __usage
  exit 1
fi
```

**Comment by polarathene** [comment]
Fine by me :+1:

**Comment by georglauterbach** [comment]
While you're at it, we may as well do the same with functions:

```bash
# old
function _foo
{
  ...
}

# new
function _foo() {
  ...
}
```

---

But please wait until the majority of _current_ PRs (for v12.1.0 and v13.0.0) are merged, to avoid merge conflicts as much as possible.

**Comment by casperklein** [comment]
> While you're at it, we may as well do the same with functions:

I had the same idea 👍

**Comment by georglauterbach** [comment]
#2803 & #3239 are still blocking; thereafter we're good to go IMO.

**Comment by polarathene** [comment]
I am doubtful #3239 would get addressed any time soon. The contributor mostly addressed a rebase of an old PR AFAIK, and I left a fair amount of feedback to consider for it to be properly implemented for DMS.

May be better to defer that or consider an alternative of adapting it to a docs guide if remaining integration work is too much effort to pursue.

The PR itself only modifies one existing script file where function/conditionals style would matter, and introduces one new script. Wouldn't be difficult to adjust to the new style afterwards on the PR.

**Comment by georglauterbach** [comment]
They we should just wait for #2803. I think @LucidityCrash will add the tests soon so we can merge the PR :)
