### ISSUE TITLE
other: cannot delete emails from mailserver

### ISSUE THREAD

**Issue by oregonpillow** [docker-mailserver/docker-mailserver#3303]
### Subject

Other

### Description

If i connect to mailserver using IMAP on a client e..g phone or laptop, if i delete an email on the client it's gone for 5 mins, then it simply returns as "new email" again...no matter what i've tried. 
Please can someone guide me through what might be the problem. I would be extremely grateful.

Thanks.

**Comment by georglauterbach** [comment]
You provided simply not enough information to help in any meaningful way. Please provide more info.

**Comment by georglauterbach** [comment]
No response. Closing this for now. Please use the bug report template when looking for solving such an issue _if you believe this to be a bug with DMS_. Please remember: the issue tracker is not for personal support.
