### ISSUE TITLE
HELP PLEASE

### ISSUE THREAD

**Issue by infortek1991** [docker-mailserver/docker-mailserver#3315]
### Subject

Other

### Description

Hallo,

I try to configure this "docker-mailserver" on MikroTik as a Container. Unfortunately it's not working properly, because map volume from mirkotik to /tmp/docker-mailserver/ not working properly. I try to configure a server from another configuration, but not working, every time i have a comunication "gmail.com loops back to myself". I don't know how configure thi server correct. Please for help. I used to new server mailbox files in attached.
Please for help
[Mail Server on Ubuntu with Postfix Dovecot MariaDB - Part 2 - Create Database for Mail Server.txt](https://github.com/docker-mailserver/docker-mailserver/files/11425186/Mail.Server.on.Ubuntu.with.Postfix.Dovecot.MariaDB.-.Part.2.-.Create.Database.for.Mail.Server.txt)
[Mail Server on Ubuntu with Postfix Dovecot MariaDB - Part 3 - Install and Configure Postfix Server.txt](https://github.com/docker-mailserver/docker-mailserver/files/11425187/Mail.Server.on.Ubuntu.with.Postfix.Dovecot.MariaDB.-.Part.3.-.Install.and.Configure.Postfix.Server.txt)
[Mail Server on Ubuntu with Postfix Dovecot MariaDB - Part 4 - Install and Configure Dovecot Server.txt](https://github.com/docker-mailserver/docker-mailserver/files/11425188/Mail.Server.on.Ubuntu.with.Postfix.Dovecot.MariaDB.-.Part.4.-.Install.and.Configure.Dovecot.Server.txt)

**Comment by georglauterbach** [comment]
Believe me when I tell you: do don't want to run this container on MikroTik. I Love MikroTik, I use it myself, but this container is too heavy.

Other than that, the issue tracker is **not** for personal help or guidance. Moreover, your platform is unsupported.
