### ISSUE TITLE
Some typos in documentation

### ISSUE THREAD

**Issue by ghnp5** [docker-mailserver/docker-mailserver#3322]
As I'm looking at the documentation and upgrading, I just want to let you know of a few typos:

https://docker-mailserver.github.io/docker-mailserver/latest/config/best-practices/dkim_dmarc_spf/#dkim

> check_pubkey = true; # you wan't to use this in the beginning

"wan't" -> "want" ?

> If there is a mismatch, a warning will be omitted to the Rspamd log /var/log/supervisor/rspamd.log.

"omitted" -> "emitted"

--

https://docker-mailserver.github.io/docker-mailserver/latest/config/environment/#rspamd_hfilter

> increasing it's default

"it's" -> "its"

--

mailserver.env

> Can be used to enable or diable the Hfilter group module.

"diable" -> disable

**Comment by ghnp5** [comment]
@georglauterbach

https://github.com/docker-mailserver/docker-mailserver/blob/03c0b116c737ac15a6a02b6396ebbe91c4f9c290/target/scripts/startup/setup.d/dmarc_dkim_spf.sh#L54

This line should say "Set up OpenDMARC"

**Comment by georglauterbach** [comment]
> @georglauterbach
> 
> https://github.com/docker-mailserver/docker-mailserver/blob/03c0b116c737ac15a6a02b6396ebbe91c4f9c290/target/scripts/startup/setup.d/dmarc_dkim_spf.sh#L54
> 
> This line should say "Set up OpenDMARC"

You're right! Can you please [provide a Pull Request](https://docker-mailserver.github.io/docker-mailserver/edge/contributing/issues-and-pull-requests/#pull-requests)?:)

**Comment by ghnp5** [comment]
@georglauterbach  https://github.com/docker-mailserver/docker-mailserver/pull/3330
