### ISSUE TITLE
rmdir: failed to remove '/etc/rspamd/override.d': Not a directory

### ISSUE THREAD

**Issue by ghnp5** [docker-mailserver/docker-mailserver#3327]
### Subject

I would like some feedback concerning a use case

### Description

I've just restarted DMS, and I got these warnings at startup:

> [   INF   ]  Welcome to docker-mailserver 12.1.0
> [   INF   ]  Checking configuration
> [ WARNING ]  This container was (likely) improperly restarted which can result in undefined behavior
> [ WARNING ]  Please destroy the container properly and then start DMS again
> [   INF   ]  Configuring mail server
> mv: cannot stat '/etc/cron.d/amavisd-new': No such file or directory
> rmdir: failed to remove '/etc/rspamd/override.d': Not a directory
> [ WARNING ]  (Rspamd setup) Could not remove '/etc/rspamd/override.d' (not empty?) - not linking '/tmp/docker-mailserver/rspamd/override.d/'

This only happened after the first start, after enabling Rspamd.

**Comment by georglauterbach** [comment]
Please use the bug report template. It seems you are using a volume that somehow acts on `/etc/rspamd/override.d`, but because you did not use the bug report template, I cannot say for sure.

**Comment by ghnp5** [comment]
Thanks - see #3328
