### ISSUE TITLE
rspamd: moving mails from junk to trash triggers learn-ham in autolearn.

### ISSUE THREAD

**Issue by Nepochal** [docker-mailserver/docker-mailserver#3333]
### Subject

Moving mails from junk to trash triggers learn-ham in autolearn.

### Description

The autolearn feature for rspamd uses the following config:

```
  # From Junk folder to elsewhere
  imapsieve_mailbox2_name = *
  imapsieve_mailbox2_from = Junk
  imapsieve_mailbox2_causes = COPY
  imapsieve_mailbox2_before = file:/usr/lib/dovecot/sieve-pipe/learn-ham.sieve
```

This results in a ham classification if mails from the junk folder are moved to thrash. Is this intended? What is the correct method to delete spam mails without classifying them as ham?

Kind regards.

**Comment by georglauterbach** [comment]
I haven't thought about this case, you're right. I will investigate.

**Comment by Nepochal** [comment]
Thank you.
