### ISSUE TITLE
Problems with DKIM and rspamd

### ISSUE THREAD

**Issue by Nebucatnetzer** [docker-mailserver/docker-mailserver#3343]
### Subject

I would like to configure a not documented mail server use case

### Description

I've read this issue (https://github.com/docker-mailserver/docker-mailserver/issues/3220) but I wasn't able to solve my problems with it.

I tried to create the DKIM keys with the script but I got the message the following message:
My volumes are on an NFS share, I checked the permissions and set them to `113:115` for giving rspamd write permission.

```
root@219790313dc2:/# setup config dkim
[   INF   ]  Creating DKIM keys of type 'rsa' and lenght '2048' with selector 'mail' for domain 'EXAMPLE.org'
cannot open output file /tmp/docker-mailserver/rspamd/dkim/rsa-2048-mail-EXAMPLE.org.private.txt: Permission denied
[  ERROR  ]  Creating keys failed
[  ERROR  ]  Aborting
```

I then tried to reuse the keys from my previous OpenDKIM setup but that gave me the following message:

```
023-05-15 16:03:25 #860(rspamd_proxy) <f3e9c9>; proxy; dkim_module_load_key_format: cannot load dkim key /tmp/docker-mailserver/rspamd/dkim/EXAMPLE.ch/mail.private: cannot stat key file: '/tmp/docker-mailserver/rspamd/dkim/EXAMPLE.ch/mail.private' Permission denied
2023-05-15 16:03:26 #860(rspamd_proxy) <f3e9c9>; proxy; rspamd_redis_connected: skip obtaining bayes tokens for BAYES_HAM of classifier bayes: not enough learns 0; 200 required
2023-05-15 16:03:26 #860(rspamd_proxy) <f3e9c9>; proxy; rspamd_redis_connected: skip obtaining bayes tokens for BAYES_SPAM of classifier bayes: not enough learns 0; 200 required
```

This is the part of the `rspamadm configdump` I've adapted to work with the OpenDKIM keys.

```
dkim_signing {
    use_esld = true;
    enable_password = "FOO";
    symbol = "DKIM_SIGNED";
    allow_envfrom_empty = true;
    sign_networks [
        "127.2.4.7",
    ]
    sign_authenticated = true;
    check_pubkey = true;
    allow_username_mismatch = false;
    sign_local = true;
    allow_hdrfrom_mismatch = false;
    selector = "dkim";
    try_fallback = true;
    use_redis = false;
    domain {
        FOO.ch {
            path = "/tmp/docker-mailserver/rspamd/dkim/FOO.ch/mail.private";
            selector = "mail";
        }
        EXAMPLE.ch {
            path = "/tmp/docker-mailserver/rspamd/dkim/EXAMPLE.ch/mail.private";
            selector = "mail";
        }
    }
    key_prefix = "DKIM_KEYS";
    enabled = true;
    use_domain = "header";
    allow_hdrfrom_multiple = false;
}
```

**Comment by georglauterbach** [comment]
_This actually is (just) a permission error_, for which I actually lack the time and nerve to investigate. Try with

```console
# ls -lh /tmp/docker-mailserver/rspamd/
# ls -lh /tmp/docker-mailserver/rspamd/dkim
# ls -lh /tmp/docker-mailserver/rspamd/dkim/*
```

or put the keys in `/tmp` and try to fix it there first to avoid directory nesting. You might try `su` and run commands as the `_rspamd` user to see whether the user has access rights.

Truth be told: the error is most certainly somewhere on your side, and I don't have time to figure out where. I'm confident the setup inside DMS is correct. The NFS mount you're using there doesn't make things easier though.

I know, this was straightforward from me, but this issue tracker is not for personal support, and your issue (permissions error due to incorrect setup) falls under personal support.

**Comment by Nebucatnetzer** [comment]
No worries, I thought about putting it into the discussion section first but since it felt so related to the other issue I thought it might belong more to the issue.
Since I was missing a few hints on how to migrate from OpenDKIM to rspamd I could extend this issue with a PR to extend the documentation, once I know how to piece it together properly.

I probably run it on my workstation and check what kind of files and permissions it creates on a bare system.
Could be that the NFS shares are related, they worked fine with OpenDKIM however.
At least with reading the keys, I've created them on the old server where everything was locally.

Just for the record, the Redis data doesn't live on the NFS share since DBs don't like it.

**Comment by Nebucatnetzer** [comment]
It was related to the NFS share.
For some reason the user `_rspamd` wasn't able to create or read files when provided the full path to the DKIM keys.
When I executed the commands directly in the directory (cd into the it beforehand) it worked fine.
No idea what the problem was.
I moved the keys on to the server itself now.
