### ISSUE TITLE
other: cp: cannot create directory '/var/lib/amavis/tmp': Invalid argument

### ISSUE THREAD

**Issue by zeraturing** [docker-mailserver/docker-mailserver#3346]
### Subject

I would like to contribute to the project

### Description

May 16 02:27:46 mail amavis[7009]: Using primary internal av scanner code for ClamAV-clamd
May 16 02:27:46 mail amavis[7009]: Found secondary av scanner ClamAV-clamscan at /usr/bin/clamscan
May 16 02:27:46 mail amavis[7009]: (!!)TROUBLE in pre_loop_hook: No TEMPBASE directory: /var/lib/amavis/tmp at /usr/sbin/amavisd-new line 13183.
May 16 02:27:46 mail amavis[7009]: (!)_DIE: Suicide () TROUBLE in pre_loop_hook: No TEMPBASE directory: /var/lib/amavis/tmp at /usr/sbin/amavisd-new line 13183.
May 16 02:27:46 mail amavis[7019]: starting. /usr/sbin/amavisd-new at mail.aiass.cc amavisd-new-2.11.1 (20181009), Unicode aware, LC_CTYPE="C.UTF-8"
May 16 02:27:46 mail amavis[7019]: perl=5.032001, user=, EUID: 109 (109);  group=, EGID: 111 111 (111 111)
May 16 02:27:46 mail amavis[7019]: Net::Server: Group Not Defined.  Defaulting to EGID '111 111'
May 16 02:27:46 mail amavis[7019]: Net::Server: User Not Defined.  Defaulting to EUID '109'
May 16 02:27:46 mail amavis[7019]: No ext program for   .zoo, tried: zoo
May 16 02:27:46 mail amavis[7019]: No ext program for   .doc, tried: ripole
May 16 02:27:46 mail amavis[7019]: No decoder for       .F
May 16 02:27:46 mail amavis[7019]: No decoder for       .doc
May 16 02:27:46 mail amavis[7019]: No decoder for       .zoo
May 16 02:27:46 mail amavis[7019]: Using primary internal av scanner code for ClamAV-clamd
May 16 02:27:46 mail amavis[7019]: Found secondary av scanner ClamAV-clamscan at /usr/bin/clamscan
May 16 02:27:46 mail amavis[7019]: (!!)TROUBLE in pre_loop_hook: No TEMPBASE directory: /var/lib/amavis/tmp at /usr/sbin/amavisd-new line 13183.
May 16 02:27:46 mail amavis[7019]: (!)_DIE: Suicide () TROUBLE in pre_loop_hook: No TEMPBASE directory: /var/lib/amavis/tmp at /usr/sbin/amavisd-new line 13183.

**Comment by georglauterbach** [comment]
File a bug **_proper_** report. This really isn't too difficult.
