### ISSUE TITLE
feature request: BIMI support

### ISSUE THREAD

**Issue by frugan-it** [docker-mailserver/docker-mailserver#3348]
### Context

Hi there,

is there any plans to support [BIMI](https://bimigroup.org/) in the near future?

Here are some useful links:

- https://bimigroup.org/bimi-open-source-tools-for-receivers/
- https://marc.info/?t=151315437400004&r=1&w=2

### Description

none

### Alternatives

none

### Applicable Users

everyone

### Are you going to implement it?

No, and I understand that it is highly likely no one will implement it. Furthermore, I understand that this issue will likely become stale and will be closed.

### What are you going to contribute?

nothing

**Comment by casperklein** [comment]
As far as I understand, you'll need to set some DNS records and host a svg file + certificate somewhere. But that is out of the scope of DMS.

**Comment by frugan-it** [comment]
> As far as I understand, you'll need to set some DNS records and host a svg file + certificate somewhere. But that is out of the scope of DMS.

Ok, from what I understand about BIMI, what you say concerns outgoing emails, but doesn't Postfix also come into play in validating incoming emails?
Otherwise, what's the point of tools like these?

- https://github.com/marcbradshaw/mail-bimi/
- https://github.com/fastmail/authentication_milter/

**Comment by casperklein** [comment]
I may be wrong. I just a quick look. I thought, verification is done in the client.

**Comment by frugan-it** [comment]
I believe both verifications are possible (MTA, MUA)..

> As BIMI records are accepted by Yahoo! (and other Verizon Media services), Fastmail, and now Gmail, other mailbox providers may be interested in adding support for BIMI.  In an effort to support their effort, open source milter-based tools have been made available for common mail platforms (e.g. **Postfix**).
> https://bimigroup.org/bimi-open-source-tools-for-receivers/
