### ISSUE TITLE
SSL_accept() failed

### ISSUE THREAD

**Issue by zeraturing** [docker-mailserver/docker-mailserver#3351]
### Subject

Other

### Description

May 17 10:35:53 mail dovecot: imap-login: Disconnected: Connection closed: SSL_accept() failed: error:1408F10B:SSL routines:ssl3_get_record:wrong version number (disconnected before auth was ready, waited 0 secs): user=<>, rip=x.x.x.x, lip=x.x.x.x, TLS handshaking: SSL_accept() failed: error:1408F10B:SSL routines:ssl3_get_record:wrong version number, session=<j63/i9r73sPesspc>
May 17 10:35:53 mail dovecot: imap-login: Login: user=<qq@name.cc>, method=PLAIN, rip=x.x.x.x, lip=x.x.x.x, mpid=21157, TLS, session=<Z88BjNr738Pesspc>
May 17 10:36:54 mail postfix/smtps/smtpd[21250]: connect from unknown[x.x.x.x]
May 17 10:37:59 mail postfix/smtps/smtpd[21250]: SSL_accept error from unknown[x.x.x.x]: Connection reset by peer
May 17 10:37:59 mail postfix/smtps/smtpd[21250]: lost connection after CONNECT from unknown[x.x.x.x]
May 17 10:37:59 mail postfix/smtps/smtpd[21250]: disconnect from unknown[x.x.x.x] commands=0/0
May 17 10:38:54 mail postfix/smtps/smtpd[21250]: connect from unknown[x.x.x.x]
May 17 10:38:54 mail postfix/smtps/smtpd[21250]: Anonymous TLS connection established from unknown[x.x.x.x]: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
May 17 10:38:54 mail postfix/smtps/smtpd[21250]: lost connection after CONNECT from unknown[x.x.x.x]
May 17 10:38:54 mail postfix/smtps/smtpd[21250]: disconnect from unknown[x.x.x.x] commands=0/0
May 17 10:39:04 mail postfix/smtps/smtpd[21250]: connect from unknown[x.x.x.x]
May 17 10:39:04 mail postfix/smtps/smtpd[21250]: SSL_accept error from unknown[x.x.x.x]: lost connection
May 17 10:39:04 mail postfix/smtps/smtpd[21250]: lost connection after CONNECT from unknown[x.x.x.x]
May 17 10:39:04 mail postfix/smtps/smtpd[21250]: disconnect from unknown[x.x.x.x] commands=0/0
May 17 10:39:04 mail postfix/smtps/smtpd[21483]: connect from unknown[x.x.x.x]
May 17 10:40:09 mail postfix/smtps/smtpd[21483]: SSL_accept error from unknown[x.x.x.x]: Connection reset by peer

**Comment by casperklein** [comment]
For the record, if the request aren't from you, I bet those were spam attempts.
