### ISSUE TITLE
docs: v13 sieve instructions are no longer valid

### ISSUE THREAD

**Issue by mholti** [docker-mailserver/docker-mailserver#3355]
### Preliminary Checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.
- [X] I searched the issue tracker but was unable to find my issue.
- [X] I read

  - the [extended documentation in general](https://docker-mailserver.github.io/docker-mailserver/latest/) but found nothing to resolve the issue;
  - the [documentation on debugging](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/), tried the proposed steps to debug the problem, but was still unable to resolve the issue;
  - this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree;
  - the [documentation about filing a bug report](https://docker-mailserver.github.io/docker-mailserver/latest/contributing/issues-and-pull-requests/#filing-a-bug-report).

### What operating system is the host running?

Linux

### Which operating system version?

Ubuntu 22.04.2 LTS

### What computer architecture is the host running?

AMD64 (x86_64)

### What container orchestration tool are you using?

Docker

### DMS version

:edge

### What happened and when does this occur?

Sieve isn't working anymore when .dovecot.sieve is a symbolic link to sieve/<userid>.sieve, all mails are put in INBOX
Thunderbird modifies sieve-setup to this symbolic link...

### What did you expect to happen?

depending on .dovecot.sieve mails should be put in different folders

### What level of experience do you have with containers, mail servers, and using a terminal?

- [ ] I am inexperienced with containers
- [X] I am rather experienced with containers
- [ ] I am inexperienced with mail servers
- [X] I am rather experienced with mail servers
- [ ] I am uncomfortable with using a terminal (CLI)
- [X] I am rather comfortable with using a terminal (CLI)

**Comment by georglauterbach** [comment]
Home directories changed with a recent PR. You need to migrate the data manually (this was a breaking change).

Old home dir: `/var/mail/DOMAIN/USER/`

New home dir: `/var/mail/DOMAIN/USER/home/`

**Comment by mholti** [comment]
Hi,
this seems a lack of documentation. The docs for :edge say:
`All user defined sieve scripts that are managed by ManageSieve are stored in the user's home folder in /var/mail/example.com/user1/sieve.`
I moved my filters directly to .dovecot.sieve and it works. Next is to move it to the new home-dir...
I'll close this bug report
Thanks,
Michael

**Comment by georglauterbach** [comment]
Oh, our docs need an update then 🙃

**Comment by polarathene** [comment]
Related discussion: https://github.com/orgs/docker-mailserver/discussions/3353#discussioncomment-5944902

**Comment by georglauterbach** [comment]
I will provide a PR for that since this is still blocking for v13.0.0.
