### ISSUE TITLE
[QUESTION]: Fail2Ban not banning logged SASL login failures?

### ISSUE THREAD

**Issue by woeisme** [docker-mailserver/docker-mailserver#3357]
### Subject

I would like some feedback concerning a use case

### Description

I came across this [link](https://enricorossi.org/blog/2022/fail2ban_postfix_sasl/)

and seem to be experiencing quite a lot of these messages in my log file that don't ever end up banned.
Could this be the culprit?

I also noticed DMS runs as debian 11.7 but uname -a lists an Ubuntu kernel

**Comment by polarathene** [comment]
You really should use the bug report template so that we have more information, especially about how you've configured DMS.

---

> `postfix/smtpd[88112]: warning: unknown[141.98.10.70]: SASL LOGIN authentication failed: UGFzc3dvcmQ6`

I don't know much about the Fail2Ban setup, but it seems to be configured for that by default.

If you look around online, you'll get results [like this one](https://github.com/fail2ban/fail2ban/discussions/3354) which provide more information on how to debug the issue and potential causes.

From the link you provided, there is `mode = aggressive`, while the config we provide in DMS is:

https://github.com/docker-mailserver/docker-mailserver/blob/da8d3654b83eb78fdd2b22b1fe2c6b5eaf779869/target/fail2ban/jail.local#L26-L33

Notice the [referenced comment](https://github.com/docker-mailserver/docker-mailserver/issues/3256#issuecomment-1511188760) there for more info, which links to the [Fail2Ban default jail config for Postfix](https://github.com/fail2ban/fail2ban/blob/5d9603c104fd50c6320d69dec394a28a452606f5/config/filter.d/postfix.conf#L58-L73). That documents your options a bit better, and we can see that `auth` is probably relevant for this SASL error, but if you're comfortable with `aggressive` it should cover all the other modes mentioned.

You'll need to modify this config yourself. The config for DMS I showed above is [added into our image here](https://github.com/docker-mailserver/docker-mailserver/blob/da8d3654b83eb78fdd2b22b1fe2c6b5eaf779869/Dockerfile#L144), and we have [docs for modifying Fail2Ban configuration](https://docker-mailserver.github.io/docker-mailserver/latest/config/security/fail2ban/#custom-files).

---

> I also noticed DMS runs as debian 11.7 but `uname -a` lists an Ubuntu kernel

This is because you're running Docker on Ubuntu. Docker containers are not like VM guests with their own kernel. They share the same host kernel.

**Comment by markus-seidl** [comment]
I've just noticed this as well, I don't know if this is new, but I have a lot of these messages in my logs:

```
Jun 19 17:38:53 mail-6467bff798-nptxm postfix/smtps/smtpd[23399]: Anonymous TLS connection established from unknown[141.98.10.151]: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
Jun 19 17:38:53 mail-6467bff798-nptxm postfix/smtps/smtpd[23399]: warning: unknown[141.98.10.151]: SASL LOGIN authentication failed: authentication failure
Jun 19 17:38:53 mail-6467bff798-nptxm postfix/smtps/smtpd[23399]: lost connection after AUTH from unknown[141.98.10.151]
Jun 19 17:38:53 mail-6467bff798-nptxm postfix/smtps/smtpd[23399]: disconnect from unknown[141.98.10.151] ehlo=1 auth=0/1 rset=1 commands=2/3
Jun 19 17:39:32 mail-6467bff798-nptxm postfix/smtps/smtpd[23399]: connect from unknown[141.98.10.151]
Jun 19 17:39:32 mail-6467bff798-nptxm postfix/smtps/smtpd[23399]: Anonymous TLS connection established from unknown[141.98.10.151]: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
Jun 19 17:39:32 mail-6467bff798-nptxm postfix/smtps/smtpd[23399]: warning: unknown[141.98.10.151]: SASL LOGIN authentication failed: authentication failure
Jun 19 17:39:32 mail-6467bff798-nptxm postfix/smtps/smtpd[23399]: lost connection after AUTH from unknown[141.98.10.151]
Jun 19 17:39:32 mail-6467bff798-nptxm postfix/smtps/smtpd[23399]: disconnect from unknown[141.98.10.151] ehlo=1 auth=0/1 rset=1 commands=2/3
Jun 19 17:40:13 mail-6467bff798-nptxm postfix/smtps/smtpd[23399]: connect from unknown[141.98.10.151]
Jun 19 17:40:13 mail-6467bff798-nptxm postfix/smtps/smtpd[23399]: Anonymous TLS connection established from unknown[141.98.10.151]: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
Jun 19 17:40:13 mail-6467bff798-nptxm postfix/smtps/smtpd[23399]: warning: unknown[141.98.10.151]: SASL LOGIN authentication failed: authentication failure
Jun 19 17:40:13 mail-6467bff798-nptxm postfix/smtps/smtpd[23399]: lost connection after AUTH from unknown[141.98.10.151]
Jun 19 17:40:13 mail-6467bff798-nptxm postfix/smtps/smtpd[23399]: disconnect from unknown[141.98.10.151] ehlo=1 auth=0/1 rset=1 commands=2/3
Jun 19 17:40:54 mail-6467bff798-nptxm postfix/smtps/smtpd[23399]: connect from unknown[141.98.10.151]
Jun 19 17:40:54 mail-6467bff798-nptxm postfix/smtps/smtpd[23399]: Anonymous TLS connection established from unknown[141.98.10.151]: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
Jun 19 17:40:54 mail-6467bff798-nptxm postfix/smtps/smtpd[23399]: warning: unknown[141.98.10.151]: SASL LOGIN authentication failed: authentication failure
Jun 19 17:40:54 mail-6467bff798-nptxm postfix/smtps/smtpd[23399]: lost connection after AUTH from unknown[141.98.10.151]
Jun 19 17:40:54 mail-6467bff798-nptxm postfix/smtps/smtpd[23399]: disconnect from unknown[141.98.10.151] ehlo=1 auth=0/1 rset=1 commands=2/3
Jun 19 17:41:35 mail-6467bff798-nptxm postfix/smtps/smtpd[23399]: connect from unknown[141.98.10.151]
Jun 19 17:41:38 mail-6467bff798-nptxm postfix/smtps/smtpd[23399]: Anonymous TLS connection established from unknown[141.98.10.151]: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
Jun 19 17:41:41 mail-6467bff798-nptxm postfix/smtps/smtpd[23399]: warning: unknown[141.98.10.151]: SASL LOGIN authentication failed: authentication failure
Jun 19 17:41:41 mail-6467bff798-nptxm postfix/smtps/smtpd[23399]: lost connection after AUTH from unknown[141.98.10.151]
Jun 19 17:41:41 mail-6467bff798-nptxm postfix/smtps/smtpd[23399]: disconnect from unknown[141.98.10.151] ehlo=1 auth=0/1 rset=1 commands=2/3
Jun 19 17:42:15 mail-6467bff798-nptxm postfix/smtps/smtpd[23399]: connect from unknown[141.98.10.151]
Jun 19 17:42:17 mail-6467bff798-nptxm postfix/smtps/smtpd[23399]: Anonymous TLS connection established from unknown[141.98.10.151]: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
Jun 19 17:42:21 mail-6467bff798-nptxm postfix/smtps/smtpd[23399]: warning: unknown[141.98.10.151]: SASL LOGIN authentication failed: authentication failure
Jun 19 17:42:22 mail-6467bff798-nptxm postfix/smtps/smtpd[23399]: lost connection after AUTH from unknown[141.98.10.151]
Jun 19 17:42:22 mail-6467bff798-nptxm postfix/smtps/smtpd[23399]: disconnect from unknown[141.98.10.151] ehlo=1 auth=0/1 rset=1 commands=2/3
```

to my knowledge, fail2ban is activated:

```
root@mail-6467bff798-nptxm:/# export
declare -x ACCOUNT_PROVISIONER="LDAP"
declare -x AMAVIS_LOGLEVEL="-1"
declare -x CLAMAV_MESSAGE_SIZE_LIMIT="25M"
declare -x DEFAULT_RELAY_HOST=""
declare -x DMS_DEBUG="1"
declare -x DOVECOT_INET_PROTOCOLS="all"
declare -x DOVECOT_MAILBOX_FORMAT="maildir"
declare -x DOVECOT_TLS="no"
declare -x ENABLE_AMAVIS="1"
declare -x ENABLE_CLAMAV="1"
declare -x ENABLE_DNSBL="0"
declare -x ENABLE_FAIL2BAN="1"
declare -x ENABLE_FETCHMAIL="0"
declare -x ENABLE_LDAP="1"
declare -x ENABLE_MANAGESIEVE="0"
declare -x ENABLE_OPENDKIM="1"
declare -x ENABLE_OPENDMARC="1"
declare -x ENABLE_POLICYD_SPF="1"
declare -x ENABLE_POP3="0"
declare -x ENABLE_POSTGREY="0"
declare -x ENABLE_QUOTAS="1"
declare -x ENABLE_RSPAMD="0"
declare -x ENABLE_RSPAMD_REDIS="0"
declare -x ENABLE_SASLAUTHD="1"
declare -x ENABLE_SPAMASSASSIN="1"
declare -x ENABLE_SPAMASSASSIN_KAM="0"
declare -x ENABLE_SRS="0"
declare -x ENABLE_UPDATE_CHECK="1"
declare -x FAIL2BAN_BLOCKTYPE="drop"
```

**Comment by polarathene** [comment]
@markus-seidl this has been explained earlier by me above: https://github.com/docker-mailserver/docker-mailserver/issues/3357#issuecomment-1556103035

If you'd like to, try making the change to aggressive mode [with `user-patches.sh`](https://docker-mailserver.github.io/docker-mailserver/latest/config/advanced/override-defaults/user-patches/).

We copy the referenced jail file internally via our Dockerfile:

https://github.com/docker-mailserver/docker-mailserver/blob/e380cc30657c33a2dc24ed528c5ffbd7784ec810/Dockerfile#L179

So `user-patches.sh` can replace the line at that location:

```bash
#! /bin/bash

# Change jail mode to a higher level (including SASL auth logins):
# https://github.com/docker-mailserver/docker-mailserver/issues/3357
sed -i 's/^mode = extra/mode = aggressive/' /etc/fail2ban/jail.local
```

**Comment by markus-seidl** [comment]
Sorry, @polarathene and thanks for your answer. I investigated further and I think it's not a fail2ban issue. When I query the net tables inside the container:

```
$:/# nft list table inet f2b-table
table inet f2b-table {
	set addr-set-postfix {
		type ipv4_addr
		flags interval
		elements = { 141.98.10.150, 141.98.10.151,
			     187.155.253.141, 194.180.48.208,
			     194.180.48.209, 194.180.48.212,
			     194.180.48.213, 194.180.48.214,
			     194.180.48.215, 194.180.48.216 }
	}

	set addr-set-postfix-sasl {
		type ipv4_addr
		flags interval
		elements = { 141.98.10.150, 141.98.10.151,
			     187.155.253.141, 194.180.48.208,
			     194.180.48.209, 194.180.48.212,
			     194.180.48.213, 194.180.48.214,
			     194.180.48.215, 194.180.48.216 }
	}

	chain f2b-chain {
		type filter hook input priority filter - 1; policy accept;
		meta l4proto { tcp } ip saddr @addr-set-postfix drop
		meta l4proto { tcp } ip saddr @addr-set-postfix-sasl drop
	}
}
```

This looks correct to my eye, but the IPs are not blocked. I guess it's an issue with nft -> k3s -> iptables. The container has the cap NET_ADMIN. Maybe that helps the original poster also.

**Comment by markus-seidl** [comment]
In the end a reboot of the system solved the issue. I noticed that the host iptables stopped working (I-tables incompatible with nft something, something.)
I guess some update broke the compatibility and needed a reboot (nft is mostly located inside the kernel, so in the end I've upgraded the packages and with the reboot the kernel as well).
