### ISSUE TITLE
Documentation appears to have incorrect URLs in the Get All Files section of Usage

### ISSUE THREAD

**Issue by johnvanham** [docker-mailserver/docker-mailserver#3375]
### Subject

Other

### Description

Hi,

The documentation appears to have incorrect links in the `Get All Files` section of `Usage` to the template docker compose file and mailserver .env

https://docker-mailserver.github.io/docker-mailserver/latest/usage/#get-all-files

When running in a bash shell:

```
jvh@jvh-laptop-lin:~$ DMS_GITHUB_URL="https://github.com/docker-mailserver/docker-mailserver/blob/latest"
wget "${DMS_GITHUB_URL}/docker-compose.yml"
wget "${DMS_GITHUB_URL}/mailserver.env"
--2023-05-28 22:00:41--  https://github.com/docker-mailserver/docker-mailserver/blob/latest/docker-compose.yml
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-05-28 22:00:42 ERROR 404: Not Found.

--2023-05-28 22:00:42--  https://github.com/docker-mailserver/docker-mailserver/blob/latest/mailserver.env
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-05-28 22:00:43 ERROR 404: Not Found.
```

And visiting the links manually also return a 404 e.g. https://github.com/docker-mailserver/docker-mailserver/blob/latest/docker-compose.yml

The documentation is great, but just thought I'd let you know I'd spotted this - it doesn't seem to be mentioned in the currently open issues unless I've missed it somewhere?

**Comment by casperklein** [comment]
Already fixed with: https://github.com/docker-mailserver/docker-mailserver/pull/3337

"The problem" is, that our documentation is versioned. It defaults to `latest`. On the top of the page, you can select `edge` instead of `latest` to see the fixed documentation:

https://docker-mailserver.github.io/docker-mailserver/edge/usage/#get-all-files

**Comment by johnvanham** [comment]
Ah, sorry I missed that! I assumed it must have been solved already but couldn't see that anywhere.
