### ISSUE TITLE
other: how to replicate mailserver?

### ISSUE THREAD

**Issue by NashiraDeer** [docker-mailserver/docker-mailserver#3383]
### Subject

I would like to configure a not documented mail server use case

### Description

How to replicate Docker Mailserver across multiple servers ensuring redundancy?

**Comment by polarathene** [comment]
Not supported, you can participate in https://github.com/docker-mailserver/docker-mailserver/issues/2048 if you would like to contribute, otherwise subscribe to that and hope someone else does? :)
