### ISSUE TITLE
other: update usage instructions

### ISSUE THREAD

**Issue by blairun** [docker-mailserver/docker-mailserver#3394]
### Subject

I would like to contribute to the project

### Description

The instructions on [this documentation page](https://docker-mailserver.github.io/docker-mailserver/latest/usage/#get-all-files) didn't work for me. 

```
DMS_GITHUB_URL="https://github.com/docker-mailserver/docker-mailserver/blob/latest"
wget "${DMS_GITHUB_URL}/docker-compose.yml"
wget "${DMS_GITHUB_URL}/mailserver.env"
```

Maybe change to this:

```
DMS_GITHUB_URL="https://raw.githubusercontent.com/docker-mailserver/docker-mailserver/master"
wget "${DMS_GITHUB_URL}/compose.yml"
wget "${DMS_GITHUB_URL}/mailserver.env"
```

**Comment by georglauterbach** [comment]
Absolutely 🚀 can you provide a PR?:)

**Comment by casperklein** [comment]
Thanks for reporting, this issue has already been addressed.

Duplicate of: https://github.com/docker-mailserver/docker-mailserver/issues/3375
Already fixed: https://github.com/docker-mailserver/docker-mailserver/pull/3337
