### ISSUE TITLE
feature request: Add ability to disable RCVD_IN_DNSWL_HI

### ISSUE THREAD

**Issue by chascode** [docker-mailserver/docker-mailserver#3419]
### Context

This feature request is related to spam filtering.

### Description

SpamAssassin's score is frequently cancelled out by whitelisted addresses.

Example score of an email that is 100% spam:

    X-Spam-Status: No, score=-1.12 tagged_above=-10000 required=3
        tests=[DKIM_SIGNED=0.1, DKIM_VALID=-0.1, DKIM_VALID_AU=-0.1,
        HTML_FONT_LOW_CONTRAST=0.001, HTML_MESSAGE=0.001, PYZOR_CHECK=3.985,
        RCVD_IN_DNSWL_HI=-5, RCVD_IN_MSPIKE_H2=-0.001, SPF_HELO_NONE=0.001,
        SPF_NONE=0.001, T_SCC_BODY_TEXT_LINE=-0.01, URIBL_BLOCKED=0.001,
        URIBL_ZEN_BLOCKED_OPENDNS=0.001] autolearn=ham autolearn_force=no

As you can see `RCVD_IN_DNSWL_HI` tricks SpamAssassin into thinking spam emails are not spam.

### Alternatives

I haven't considered any alternatives.

### Applicable Users

Anyone who doesn't like spam.

### Are you going to implement it?

No, and I understand that it is highly likely no one will implement it. Furthermore, I understand that this issue will likely become stale and will be closed.

### What are you going to contribute?

I do not have the ability to contribute anything, sorry. However, if required, I'd happily send a private message containing the full source of affected emails (as long as my personal details are never made public).

**Comment by casperklein** [comment]
Because of this, I am no fan of DNS black/white lists and recommend to not use them. However, if you want to keep them, you could exclude the ones making trouble:

```bash
# Removed DNS-WLs: list.dnswl.org=127.0.[0..255].0*-2 list.dnswl.org=127.0.[0..255].1*-3 list.dnswl.org=127.0.[0..255].[2..3]*-4
postconf "postscreen_dnsbl_sites = zen.spamhaus.org=127.0.0.[2..11]*3 bl.mailspike.net=127.0.0.[2;14;13;12;11;10] b.barracudacentral.org*2 bl.spameatingmonkey.net=127.0.0.2 dnsbl.sorbs.net psbl.surriel.com"
```

Within the container you can check the currently configured lists with: `postconf postscreen_dnsbl_sites`.

You can put the above command to remove the DNS-WLs in your user-patches.sh file:

- https://docker-mailserver.github.io/docker-mailserver/latest/config/advanced/override-defaults/user-patches/
- https://docker-mailserver.github.io/docker-mailserver/latest/faq/#how-to-adjust-settings-with-the-user-patchessh-script

**Comment by chascode** [comment]
Thanks for the workaround, @casperklein.

Before the patch `postconf postscreen_dnsbl_sites` returns an empty string and after the patch the string returns the same value as in your example.  Is the empty string before the patch expected?

**Comment by casperklein** [comment]
Probably my fault. If postscreen_dnsbl_sites is empty, then `ENABLE_DNSBL` is to 0 in your `mailserver.env` and no DNS BL takes effect in postscreen.
As the name (postscreen_dnsbl_sites ) suggests, it's related to postscreen, not spamassassin.

Are you sure, it's SA related and not rspamd?

**Comment by chascode** [comment]
I'm not 100% sure but I suspect it's rspamd because when I run `cd /etc && grep -rl RCVD_IN_DNSWL_HI` inside the container I get:

    rspamd/scores.d/rbl_group.conf
    rspamd/modules.d/rbl.conf
    rspamd/composites.conf

**Comment by casperklein** [comment]
Do you have rspamd enabled (`ENABLE_RSPAMD=0`)?

**Comment by chascode** [comment]
`echo $ENABLE_RSPAMD` returns `0`

**Comment by polarathene** [comment]
If it's not too much trouble, can you view our docs for rspamd to try enabling that?

It can replace quite a few of prior services, but one of those is SpamAssassin. It would be good to know if you experience better quality with rspamd enabled / configured as we are considering switching to it by default in future :+1: 

---

According to [this information](https://serverfault.com/a/1125292), `RCVD_IN_DNSWL_HI` default score is `-5`, however even if that was `0`, the [score would not be high enough for being marked with spam detected headers](https://docker-mailserver.github.io/docker-mailserver/latest/config/environment/#sa_tag), it would qualify for spam info headers though.
