### ISSUE TITLE
bug report: Postgrey error can't open lock file

### ISSUE THREAD

**Issue by Tandokude** [docker-mailserver/docker-mailserver#3423]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

Using podman v3.0.1 on Debian 11, I create the container via a bash script with the latest tag for docker-mailserver. Using command podman start mailserver, I can see it starts. When using podman logs mailserver I get the following over and over:
023/07/11-07:46:51 postgrey (type Net::Server::Multiplex) starting! pid(3950)
Binding to TCP port 10023 on host 127.0.0.1 with IPv4
Setting gid to "109 109"
Setting uid to "107"
ERROR: can't open lock file: /var/lib/postgrey/postgrey.lock

I have gone into the container and confirmed the permissions on /var/mail-state/lib-postgrey is postgrey:postgrey with 700

### 👟 Reproduction Steps

Podman start mailserver
podman logs mailserver

### 🐋 DMS Version

12.1.0

### 💻 Operating System and Architecture

Debian 11

### ⚙️ Container configuration files

```yml
SERVICE="container-mailserver"
IMAGE="ghcr.io/docker-mailserver/docker-mailserver:latest"

systemctl --user stop $SERVICE

# Build mailserver

rm /run/user/$UID/$SERVICE.service-cpid
rm /run/user/$UID/$SERVICE.service-cid

mkdir -p $HOME/containers/mailserver/mail-data
mkdir -p $HOME/containers/mailserver/mail-state
mkdir -p $HOME/containers/mailserver/mail-logs

podman create --name mailserver --replace \
--env-file=$HOME/containers/mailserver/env/mailserver.env \
--hostname mail.thatitguy.net \
--network=slirp4netns:port_handler=slirp4netns \
-p 10025:25 \
-p 10143:143 \
-p 10465:465 \
-p 10587:587 \
-p 10993:10993 \
-v $HOME/containers/mailserver/mail-data/:/var/mail/:rw,Z \
-v $HOME/containers/mailserver/mail-state/:/var/mail-state/:rw,Z \
-v $HOME/containers/mailserver/mail-logs/:/var/log/mail/:rw,Z \
-v $HOME/containers/mailserver/config/:/tmp/docker-mailserver/:rw,Z \
-v /etc/localtime:/etc/localtime:ro \
-v $HOME/certs:/etc/certs:ro \
--conmon-pidfile /run/user/$UID/$SERVICE.service-cpid \
--cidfile /run/user/$UID/$SERVICE.service-cid \
$IMAGE
```

**Comment by polarathene** [comment]
> I have gone into the container and confirmed the permissions on `/var/mail-state/lib-postgrey` is `postgrey:postgrey` with `700`

Does the lock file exist?

Try running the container as privileged or similar to rule out other restraints. I know at least with Podman an update this year removed the chroot capability as a default which differs from Docker, might be you need to opt-in for another capability. You also appear to be running SELinux which might also play a role?

I assume this doesn't reproduce with Docker and is Podman specific? Would you be able to confirm that in your environment?

**Comment by Tandokude** [comment]
> > I have gone into the container and confirmed the permissions on `/var/mail-state/lib-postgrey` is `postgrey:postgrey` with `700`
> 
> Does the lock file exist?
> 
> Try running the container as privileged or similar to rule out other restraints. I know at least with Podman an update this year removed the chroot capability as a default which differs from Docker, might be you need to opt-in for another capability. You also appear to be running SELinux which might also play a role?
> 
> I assume this doesn't reproduce with Docker and is Podman specific? Would you be able to confirm that in your environment?

No, the lock file does not exist.
I am currently running docker-mailserver on another rootless podman server (under my own user) and docker. Both I created before v12, possibly v11 and just continued to upgrade with no changes to the env file.  Also not currently utilizing SElinux, same issue if I remove the Z on all volumes. 
_

**Comment by polarathene** [comment]
Can you reproduce the error with a fresh container (not re-using any existing one) in Podman (new volumes) with v12? And if you can does that still reproduce with v11.3?

It would be good to pinpoint if the failure is with a specific version of DMS that you can reliably reproduce, if it's restricted to your current deployment environment/state, or if it was due to a change outside of DMS (earlier version that once worked now fails too).

If you're able to reproduce with a fresh setup, you could try commenting out the state volume which may not encounter the error, then we'd know it's specific to the volume mounting. If you can't reproduce then your current setup might work with the state volume removed (keeps state internal), and then probably with a fresh volume for state, in which case the issue is due to something with your current state contents.

It would be good if another user can chime in about experiencing the same issue, especially with Docker (preferably non-rootless) as we're primarily focused on that environment. Might be an issue with rootless?

**Comment by Tandokude** [comment]
I will try with a fresh container on both v11.3 and 12, and report back tomorrow when I get time. Just seems odd to be a rootless issue if I'm currently running it on another rootless podman instance. Granted that is Debian 12 with podman v4.3.1 vs v3.0.1 in Debian 11 where I'm having the issue.

**Comment by Tandokude** [comment]
Alright, not sure what to make of this, I stayed on v12 of docker-mailserver and the only change I made was I cleared out the mail-logs and mail-state folders. Then I made mail-state on my host chmod 777, after starting it was happy.  I shut the container back down, I modified the permission back to 755 and it was still fine............................

total 10328
drwx------  2 postgrey postgrey     4096 Jul 13 15:09 .
drwxrwxr-x 11 root     root         4096 Jul 13 15:02 ..
-rw-------  1 postgrey postgrey   303103 Jul 13 15:09 __db.001
-rw-------  1 postgrey postgrey    32767 Jul 13 15:09 __db.002
-rw-------  1 postgrey postgrey    49151 Jul 13 15:09 __db.003
-rw-------  1 postgrey postgrey 10485759 Jul 13 15:09 log.0000000001
-rw-------  1 postgrey postgrey     8192 Jul 13 15:02 postgrey.db
-rw-------  1 postgrey postgrey        0 Jul 13 15:02 postgrey.lock
-rw-------  1 postgrey postgrey     8192 Jul 13 15:02 postgrey_clients.db

**Comment by polarathene** [comment]
Ok so you can no longer reproduce the issue? Might have been an issue with existing state volume when you updated the image to a new version, but this is the first time someone is reporting this error so it's hard to say.

**Comment by Tandokude** [comment]
I can only reproduce it if I completely blow away the mail-state folder on the host and do not set the permission to 777.  If I let the startup script run at least once on the mail-state folder with full permissions it's then happy from then on even if permissions are curtailed back.
