### ISSUE TITLE
other: Do I need to restart docker-mailserver when a certificate renews?

### ISSUE THREAD

**Issue by Volper212** [docker-mailserver/docker-mailserver#3446]
### Subject

I have questions about TLS/SSL/STARTTLS/OpenSSL

### Description

I have set up SSL for my mail server and I have Certbot running in standalone mode. The docs say:
> You don't have to do anything else. Enjoy!

Does this include automatically using the new certificate on the server when it renews? Or do I have to restart something in a post-renewal hook? If so, how do I do that?

**Comment by georglauterbach** [comment]
> Does this include automatically using the new certificate on the server when it renews?

Yes

**Comment by Volper212** [comment]
Yes, I'm using Let'sEncrypt with Certbot. Thank you. How will I check if the certificate reloaded on the mail server after it renews?

**Comment by georglauterbach** [comment]
The changedetector service should show it in case [`LOG_LEVEL?](https://docker-mailserver.github.io/docker-mailserver/latest/config/environment/#log_level) is set appropriately. I think `supervisorctl` can show you logs for each service individually, so just try a bit, I don't know the exact command by heart at the moment.

**Comment by russeree** [comment]
If the SSL environment is set to manual will it automatically update? Example 

I drop in a new cert file that replaces the old one, will DMS catch that change and apply it?

Thanks

**Comment by polarathene** [comment]
There was a recent discussion with CertBot where the user had trouble with renewing. I responded [breaking down how our support in DMS works for all our SSL modes](https://github.com/orgs/docker-mailserver/discussions/3429#discussioncomment-6534815), should be a good reference for you all.

---

> Does this include automatically using the new certificate on the server when it renews?

Provided you're not using LDAP (_change detection service does not yet support it_), the container should be monitoring for the certificate files to be updated.

However, as the linked discussion above covers, this didn't happen for the user. It's unclear why, they have not responded back. Provided you've mounted the files correctly and the container detects the new updated files, it should all work properly.

---

> How will I check if the certificate reloaded on the mail server after it renews?

You can shell into the container like the linked discussion above details if necessary. They also share a website that checks the connection where you can see if the expiration date has been updated.

The logs for the change detection service should be located at `/var/log/supervisor/changedetector.log` in the container. We do have a [`supervisorctl` command for retrieving logs](http://supervisord.org/running.html#supervisorctl-actions) (`tail`), but it doesn't output the full contents of that log file, only a portion of the end.

```bash
# Full log file:
docker exec container_name cat /var/log/supervisor/changedetector.log

# Logs from supervisorctl
docker exec container_name supervisorctl tail changedetector
```

---

> I drop in a new cert file that replaces the old one, will DMS catch that change and apply it?

Yes, if you've setup manual certs correctly with ENV, when the container starts it will make an internal copy and watch the original source path, once it detects the files have been updated it should copy those files to the internal location and reload Postfix and Dovecot to update to the new certificate files.

**Comment by russeree** [comment]
Thank you @polarathene that response was beyond excellent.
