### ISSUE TITLE
feature request: Mark Spam as Read

### ISSUE THREAD

**Issue by H4R0** [docker-mailserver/docker-mailserver#3449]
### Context

While Spam/Junk is detected and moved into the Junk folder it still pops up as unread messages.

Junk detection is pretty good so it would make sense to mark the mails as read so they don't bother the user.

I did this myself for some time using a sieve filter and haven't missed any important messages so far.

### Description

Just like `MOVE_SPAM_TO_JUNK` there should be a `MARK_SPAM_AS_READ` environment variable.

If `MARK_SPAM_AS_READ` is set to `1` it will create a sieve filter with the following content:

```
if header :contains "X-Spam-Flag" "YES" {
    setflag "\\Seen";
}
```

### Alternatives

Manual setup via sieve filter, maybe added to documentation.

### Applicable Users

Any user that is annoyed by getting Spam/Junk which has to be marked as read / opened.

### Are you going to implement it?

Yes, because I know the probability of someone else doing it is low and I can learn from it.

### What are you going to contribute?

See Description.

I created this issue to discuss whether this should actually be implemented, any feedback is welcome.

Note: to test whether the sieve filter works you can send yourself a mail with the test string:
`XJS*C4JDBQADN1.NSBN3*2IDNEN*GTUBE-STANDARD-ANTI-UBE-TEST-EMAIL*C.34X`

**Comment by casperklein** [comment]
Sounds like a good addition. You can provide a PR, we will review it. If you have any questions, let us know.

**Comment by H4R0** [comment]
I've implemented it here https://github.com/H4R0/docker-mailserver/tree/mark-spam-read

It's only missing tests, manually tested works fine.

Just need to figure out how the testing works, e.g. check for read flag.

**Comment by casperklein** [comment]
I found this:

https://github.com/docker-mailserver/docker-mailserver/blob/85603193a2f4aae0a72c929446470edafd91d865/test/tests/parallel/set1/spam_virus/spam_junk_folder.bats#L69

Is the mail, after marked as read, moved to the `cur` subdirectory: `  _should_receive_spam_at '/var/mail/localhost.localdomain/user1/.Junk/cur/'`?
