### ISSUE TITLE
Shared calendar

### ISSUE THREAD

**Issue by MarcS1975** [docker-mailserver/docker-mailserver#3466]
### Context

Is there a package that would include a shared calendar integrated with the mail server?

### Description

 I am looking to use mailserver for a small team of 3 on our own server and we are used to sharing calendars via Exchange.

Function overview 

Create cal entries from received emails (invitee).
Create cal invites via email and send (invitor).
Add/remove people from meetings via email

### Alternatives

MS Exchange

### Applicable Users

All email users working in teams and needing to share their calendar including calendar invites via email.

### Are you going to implement it?

Yes, because I know the probability of someone else doing it is low and I can learn from it.

### What are you going to contribute?

Ideas

**Comment by casperklein** [comment]
DMS does not provide a calendar. You'll have to use a 3rd party application for that.

**Comment by MarcS1975** [comment]
I may be off topic then but is there any particular package that works well
with DMS?

**Comment by casperklein** [comment]
What do you mean by "works well". Mail and calendar are two different things/products. As they are not dependent on each other, every solution should work well.
As said, you could take a look at nextcloud.

**Comment by MarcS1975** [comment]
ok - i will look elsewhere
thanks
