### ISSUE TITLE
other: Alias map with wildcard

### ISSUE THREAD

**Issue by smalchow** [docker-mailserver/docker-mailserver#3469]
### Subject

I would like to configure a not documented mail server use case

### Description

Hi,

i am trying to configure a catch (almost) all address, something like

_$some_arbitrary_string.fixed@domain.com -> fixed-mailbox@domain.com_

I found the documentation for catchall here

https://docker-mailserver.github.io/docker-mailserver/edge/faq/#how-can-i-configure-a-catch-all

and tried it, but something like

_*.fixed.domain.com recipient@domain.com_

does not work. Also the resulting file (in the container) /etc/postfix/virtual does not seem to be included in the configuration.

Can someone point me to the right direction

Cheers
Soeren

**Comment by casperklein** [comment]
Afaik, this is not possible with DMS (out of the box).

Take a look here, if you want to hack something together:

- https://serverfault.com/questions/365235/configuring-postfix-to-catch-all-with-a-suffix-using-virtual-alias-map
- https://serverfault.com/questions/76852/postfix-catch-all-for-emails-which-include-a-unique-id
