### ISSUE TITLE
other: auto renew in crontab

### ISSUE THREAD

**Issue by vahidalvandi** [docker-mailserver/docker-mailserver#3474]
### Subject

I have questions about TLS/SSL/STARTTLS/OpenSSL

### Description

i want to set cronjobs every night to check renew ssl do this corrent . and 

**Docker mail server must be restarted?**

`sudo crontab -e`

`0 0 * * * sudo docker run --rm -it -v "${PWD}/docker-data/certbot/certs/:/etc/letsencrypt/" -v "${PWD}/docker-data/certbot/logs/:/var/log/letsencrypt/" -p 80:80 -p 443:443 certbot/certbot renew`

**Comment by casperklein** [comment]
>> Docker mail server must be restarted?

Certificate changes should be detected automatically by the changedetection service. This will restart/reload the necessary other services like postfix/dovceot.

PS: Why not just test the certificate renewal and verify it to be sure?

**Comment by vahidalvandi** [comment]
PS: Why not just test the certificate renewal and verify it to be sure? 😉

How is the Command executed?

**Comment by casperklein** [comment]
You can check the currently used certificate with:

`docker exec mailserver openssl s_client -showcerts -connect localhost:25 -starttls smtp -servername mail.example.com`

**Comment by vahidalvandi** [comment]
Does that mean it can renew ssl by executing this?

**Comment by polarathene** [comment]
Please review [our SSL / TLS docs (_specifically the LetsEncrypt Certbot section_)](https://docker-mailserver.github.io/docker-mailserver/v12.1/config/security/ssl/#example-using-docker-for-lets-encrypt) which has a tip about renewals and a link for automating them on the host via cron or systemd-timer.

![dms docs](https://github.com/docker-mailserver/docker-mailserver/assets/5098581/114d9822-4db0-4b6b-bed8-8462d7229a81)

![certbot docs](https://github.com/docker-mailserver/docker-mailserver/assets/5098581/90f5d7ff-ae83-4a40-ab30-17d55c353779)

If you are using a Docker image to run certbot you'll need to setup your own scheduled task. Reference the docs. You do not need to check expiry, certbot should check that and renew the cert within 30 days of expiry, so just schedule the command to run on your docker host system each week or so.

If you use Traefik or Caddy, these can provision LetsEncrypt certs and will automatically renew as long as their daemon is running. Traefik has DMS support integrated with `acme.json` handling via our change-detection service (_presently unsupported if LDAP is enabled for DMS_).
