### ISSUE TITLE
other: i want two env files

### ISSUE THREAD

**Issue by kpddadyo72419** [docker-mailserver/docker-mailserver#3476]
### Subject

Other

### Description

I hope the author can provide two env files. One should include the essential configurations such as DKIM and dns settings, while the other should contain optional advanced configurations like MySQL, Redis, LDAP, Spam and so on.

**Comment by polarathene** [comment]
We do not control Docker / Compose projects. We cannot change that.

Compose can support what you want in a different way, by creating separate `.yaml` config to extend a base `compose.yaml` config (_also see the side-bar on the left, `include` and `merge`_): https://docs.docker.com/compose/multiple-compose-files/extends/

Actually the support for ENV files can take a list, so you can have what you want already: https://docs.docker.com/compose/compose-file/05-services/#env_file
