### ISSUE TITLE
bug report: Postfix `main.cf:smtpd_milters` appends `$rspamd_milter` on restarts

### ISSUE THREAD

**Issue by polarathene** [docker-mailserver/docker-mailserver#3482]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

A [user has identified a bug](https://github.com/orgs/docker-mailserver/discussions/3481#discussioncomment-6720861) similar to one recently resolved by https://github.com/docker-mailserver/docker-mailserver/pull/3380 where a setting is updated by appending a value, but repeated restarts do not check if it was already appended (_internal config is expected to be deterministic at startup, not modified from prior restart_).

https://github.com/docker-mailserver/docker-mailserver/blob/8f971713360c4620046c7f223fe66df9ea800253/target/scripts/startup/setup.d/security/rspamd.sh#L141

This `sed` approach has been used a fair bit and may result in similar bugs elsewhere.

---

### Internal state persisting across restarts is a known concern

This isn't too surprising; maintainers are well aware of DMS not playing well with restarts. We've given explicit advice in many issues to [properly restart DMS](https://github.com/docker-mailserver/docker-mailserver/issues/3462#issuecomment-1669120153) via either:
- `docker compose down` (_`ctrl +c` alone is not equivalent_) + `docker compose up`
- `docker compose up --force-recreate` (_no `down` command required_).

Our docs also try raise awareness in [Usage guide](https://docker-mailserver.github.io/docker-mailserver/v12.1/usage/#get-up-and-running) (_perhaps should also mention in [Debugging docs](https://docker-mailserver.github.io/docker-mailserver/v12.1/config/debugging/)_):

<img width="542" alt="image" src="https://github.com/docker-mailserver/docker-mailserver/assets/5098581/c9d0227f-504e-4704-bff0-e8e9c27d6d3a">

Internal configs being changed may not be deterministic with current scripts otherwise. While this approach won't help if any volume mounted configs (_that aren't copied internally_) were modified by DMS, but we tend to have less assumptions by scripts in those cases to avoid the problem.

### 🐋 DMS Version

12.1 / edge

### 💻 Operating System and Architecture

N/A

**Comment by polarathene** [comment]
Assigning to @georglauterbach as you previously resolved the `$dkim_milter` and this is rspamd related.

No rush, AFAIK it's not causing any major problems and is only a result of user restarting the container in an unsupported manner.

**Comment by georglauterbach** [comment]
I was annoyed at work and needed to do something else entirely, so I quickly wrote up the solution.
