### ISSUE TITLE
other: I need help configuring DKIM

### ISSUE THREAD

**Issue by jpsanchezl10** [docker-mailserver/docker-mailserver#3491]
### Description

I want to set up DKIM, so people won't spoof my email.
I read the documentation on [DKIM, DMARC & SPF](https://docker-mailserver.github.io/docker-mailserver/edge/config/best-practices/dkim_dmarc_spf/) but I'm not getting it.

What DNS records I need to add?
What do I need to modify in my docker ?

**Comment by polarathene** [comment]
Please search existing issues where you'd probably find this information, it's one of the top suggestions for troubleshooting before raising an issue, we'd like you to put a bit of effort in.

Recent advice on setting up DKIM with the rspamd feature:
- https://github.com/docker-mailserver/docker-mailserver/issues/3431#issuecomment-1643227106
- https://github.com/docker-mailserver/docker-mailserver/issues/3431#issuecomment-1650699035
- https://github.com/docker-mailserver/docker-mailserver/issues/3431#issuecomment-1656415645

For OpenDKIM as described in our docs you've linked and read:

## 1. [Generate a key as described](https://docker-mailserver.github.io/docker-mailserver/edge/config/best-practices/dkim_dmarc_spf/#generating-keys), then restart the container:

   ![image](https://github.com/docker-mailserver/docker-mailserver/assets/5098581/d7a5a03f-b93c-42d6-8163-a4d5bc009036)

   ![image](https://github.com/docker-mailserver/docker-mailserver/assets/5098581/e8a07c2f-52e2-433b-8807-23399b78ba93)

   ![image](https://github.com/docker-mailserver/docker-mailserver/assets/5098581/29ec3a44-f039-43f3-b15e-b57ed19f3383)

## 2. [Configure the DNS as described](https://docker-mailserver.github.io/docker-mailserver/edge/config/best-practices/dkim_dmarc_spf/#dkim-dns), it is very clear with links to explain better Web UI or Zone file:

  ![image](https://github.com/docker-mailserver/docker-mailserver/assets/5098581/2087590d-6bb3-4d1d-95d3-9848cd26b77b)

  ![image](https://github.com/docker-mailserver/docker-mailserver/assets/5098581/1aa847a0-7509-4234-bf28-030e3353607e)

## 3. For DNS via Web UI (_like Cloudflare which you're using_), it's a DNS `TXT` record type as our docs mention, and you need to paste in the generated files contents (_as explained in this part of our DKIM DNS docs_):

   ![image](https://github.com/docker-mailserver/docker-mailserver/assets/5098581/476ac576-53e5-4155-b254-16b749777b4c)

### 4. Summary

```bash
# DMS container is running with volume mount for `/tmp/docker-mailserver`
# You should have at least one account added already, eg: `setup email add hello@example.com`
# Create the DKIM key:
docker exec -it <CONTAINER NAME> setup config dkim
# When DMS container is restarted, it will sign email sent with DKIM

# Now Update DNS for people who receive your mail to verify the DKIM signature
# DKIM key was created and exists in `/tmp/docker-mailserver/opendkim/`, check your folder on your host for the `opendkim/` folder.
# We generated DKIM key with defaults, there should be a file called `mail.txt`,
# open it and like the docs above explain, copy/paste the files contents somewhere and change it to something like (all one line):

v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqQMMqhb1S52Rg7VFS3EC6JQIMxNDdiBmOKZvY5fiVtD3Z+yd9ZV+V8e4IARVoMXWcJWSR6xkloitzfrRtJRwOYvmrcgugOalkmM0V4Gy/2aXeamuiBuUc4esDQEI3egmtAsHcVY1XCoYfs+9VqoHEq3vdr3UQ8zP/l+FP5UfcaJFCK/ZllqcO2P1GjIDVSHLdPpRHbMP/tU1a9mNZ5QMZBJ/JuJK/s+2bp8gpxKn8rh1akSQjlynlV9NI+7J3CC7CUf3bGvoXIrb37C/lpJehS39KNtcGdaRufKauSfqx/7SxA0zyZC+r13f7ASbMaQFzm+/RRusTqozY/p/MsWx8QIDAQAB

# Now add this to your DNS Web UI as a TXT record as the value
# The DNS TXT record name should be from `mail.txt` which was `mail._domainkey`
# This DNS record is not for `mail.example.com`, but for the mail account you added, such as `example.com`
# If you have done it correctly, you can test as docs explain:
dig +short TXT mail._domainkey.example.com
```

Use a web service to check the DKIM key is setup correctly as well [like the docs mention](https://docker-mailserver.github.io/docker-mailserver/edge/config/best-practices/dkim_dmarc_spf/#dkim-debug).

If your DNS provider does not support the default key size generated (RSA 4096), you should generate a smaller key instead:

![image](https://github.com/docker-mailserver/docker-mailserver/assets/5098581/da640d17-2414-4b95-9183-114e8e9c6124)

2048 is a good size, 1024 should work for everyone (_and probably ok](https://github.com/docker-mailserver/docker-mailserver/issues/3431#issuecomment-1656956863)_), although if security is a big concern for you and you don't want to update the key again 2048 is a bit more comfortable. The current default 4096 is excessive and should really be changed..
