### ISSUE TITLE
Undeliverable mail, invalid header section

### ISSUE THREAD

**Issue by EmaX093** [docker-mailserver/docker-mailserver#3501]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

Hi! We have a problem receiving emails from a particular client, our docker-mail-server rejects his incoming mails. 
We don't have problems with anyone else. Only them. So I think is a problem related to his mail server, but i would like to learn what is happening here.

```
From: Content-filter at mail.pppp.com.ar
[mailto:postmaster@mail.pppp.com.ar]
Sent Date: miércoles, 23 de agosto de 2023 08:09
To: bbbb@aaaaa.com.ar
Subject: Undeliverable mail, invalid header section

The message WAS NOT relayed to:
  <mmmm@zzzz.com.ar>:
   554 5.6.0 Bounce, id=2764068-18 - BAD HEADER

This nondelivery report was generated by the program amavisd-new at host
mail.pppp.com.ar. Our internal reference code for your message is
2764068-18/fszQHvIpmZMx

INVALID HEADER

  Improper folded header field made up entirely of whitespace (char 20 hex):
    X-Spam-Report: ...that system for details.  Content previ[...]

Return-Path: <bbbb@aaaaa.com.ar>
From: "Jane Doe" <bbbb@aaaaa.com.ar>
Message-ID: <003f01d9d5b2$3218ee90$964acbb0$@aaaaa.com.ar>
Subject: RE: Presupuesto Servicio
```

### 🐋 DMS Version

v12.1.0

### 💻 Operating System and Architecture

Debian GNU/Linux 11 (bullseye) x86_64

**Comment by polarathene** [comment]
> `Improper folded header field made up entirely of whitespace (char 20 hex)`

That is what is happening... There is a mail header that is all empty white-space (_space bar ` `, aka `0x20`_).

This was processed and reported from the Amavis service. You can choose to disable that like our ENV docs show if you don't want to use it. Otherwise, you can look up Amavis docs for a way to adjust the configuration.

But it is telling you the client mail is the problem, so technically you should have them fix whatever is causing the bad header. They must be doing something differently, either how they create the mail to send, or some different software that is behaving badly.

**Comment by EmaX093** [comment]
> > `Improper folded header field made up entirely of whitespace (char 20 hex)`
> 
> That is what is happening... There is a mail header that is all empty white-space (_space bar ` `, aka `0x20`_).
> 
> This was processed and reported from the Amavis service. You can choose to disable that like our ENV docs show if you don't want to use it. Otherwise, you can look up Amavis docs for a way to adjust the configuration.
> 
> But it is telling you the client mail is the problem, so technically you should have them fix whatever is causing the bad header. They must be doing something differently, either how they create the mail to send, or some different software that is behaving badly.

I would investigate amavis Docs if i can configure this.

Thank You, I appreciate the time You took to answer me.

**Comment by EmaX093** [comment]
The client have no clue what to do to fix this problem on their side, so I fixed this by creating a file "amavis.cf" in "config" folder of docker-mailserver -as suggested by @polarathene - and added this below:

`use strict;

#
# Place your configuration directives here.  They will override those in
# earlier files.
#
# See /usr/share/doc/amavisd-new/ for documentation and examples of
# the directives you can use in this file
#

# disable check for empty bad header
$allowed_header_tests{'empty'} = 0;

# complete list of headers
# other     catchall for everything else - normally not used
# mime      Bad MIME (sub)headers or bad MIME structure
# 8bit      Invalid non-encoded 8-bit characters in header
# control   Invalid control characters in header (CR or NUL)
# empty     Folded header field made up entirely of whitespace
# long      Header line longer than RFC 2822 limit of 998 characters
# syntax    Header field syntax error missing Missing required header field
# multiple  Duplicate or multiple occurrence of a header field

#------------ Do not modify anything below this line -------------
1;  # ensure a defined return`

This file overrides /etc/amavis/conf.d/50-user as documentation says.

I hope this can help somebody with the same problem.
