### ISSUE TITLE
question: Can I use an S3 bucket to store my DMS data?

### ISSUE THREAD

**Issue by jpsanchezl10** [docker-mailserver/docker-mailserver#3510]
### Subject

I would like to configure a not documented mail server use case

### Description

I want to store all the docker email data in a S3 bucket .

**Comment by polarathene** [comment]
You should explain why this is important to you, and what you've tried.

A quick google will suggest you could use a NFS mount for S3 storage. This is not advised though, look at Dovecot docs and NFS compatibility.

---

If you don't want to demonstrate any effort, nor why remote storage is important to you, you should try your luck on the community discussions:

![image](https://github.com/docker-mailserver/docker-mailserver/assets/5098581/97957911-2cef-41d8-82e5-6005ee325f2d)

Quick search of our issue tracker for `S3` will land you on this [Dovecot S3 via `obox` plugin](https://github.com/docker-mailserver/docker-mailserver/issues/1919#issue-860737549), only available via [Dovecot Pro](https://github.com/docker-mailserver/docker-mailserver/issues/1919#issuecomment-822129820).

**Comment by georglauterbach** [comment]
This may potentially be non-trivial. If you are using [Kubernetes](https://kubernetes.io/) **already**, you may look at [this article](https://www.suse.com/c/deploy-s3gw-with-rancher-and-longhorn-storage/). If you're not using Kubernetes, I'd advocate against starting with it for the pure sake of switching to S3. It's great, but switching to it should be done for different reasons.
