### ISSUE TITLE
question: Is 2GB of RAM used by the container normal?

### ISSUE THREAD

**Issue by jpsanchezl10** [docker-mailserver/docker-mailserver#3512]
### Subject

Project Question 

### Description

The docker mail server by itself is using about 1.9-2Gb ram by itself . is this normal ?

**Comment by casperklein** [comment]
[Is ClamAV enabled](https://docker-mailserver.github.io/docker-mailserver/latest/faq/#minimum)?

**Comment by polarathene** [comment]
ClamAV uses about 1GB of RAM to work, and it needs double that when handling updates. So 2GB would not be surprising. If you don't need anti-virus feature, disable it and the container should use much less memory.
