### ISSUE TITLE
other: ClamAV minor updates available

### ISSUE THREAD

**Issue by Codelica** [docker-mailserver/docker-mailserver#3537]
### Subject

Something else that requires developers attention

### Description

Just a quick note to consider before a next release, ClamAV has a minor bump available.

```
Your ClamAV installation is OUTDATED!
Local version: 0.103.8 Recommended version: 0.103.10
```

**Comment by casperklein** [comment]
In the meantime, you have three options:

1. Using the `:edge` docker image
2. Building your own image
3. Update a running container with something like: `docker exec -it mailserver bash -c "apt update && apt upgrade"`
