### ISSUE TITLE
Email service as a subscription service

### ISSUE THREAD

**Issue by vahidalvandi** [docker-mailserver/docker-mailserver#3571]
### Subject

I would like to contribute to the project

### Description

I want to offer the email service as a subscription service to my customers.
For example, one of my clients needs 5 accounts and each account needs a maximum of 1 gigabyte of space. Can dms provide me with this type of service? 

and access email with web ui ? for each client

**Comment by polarathene** [comment]
No, you need to implement this yourself or find a service that provides that for you.
