### ISSUE TITLE
feature request: Dovecot LUA support

### ISSUE THREAD

**Issue by Zepmann** [docker-mailserver/docker-mailserver#3575]
### Context

Dovecot [supports Lua](https://doc.dovecot.org/admin_manual/lua/). One use case is [to extend its authentication options](https://doc.dovecot.org/configuration_manual/authentication/lua_based_authentication/#authentication-lua-based-authentication).

DMS currently does not include dovecot-lua. 

### Description

There is a dovecot-lua package available in Dovecot's deb repositories which are used to create the DMS image. Include this when building the image. The current version depends on Lua 5.3, which should be included as well. 

### Alternatives

Currently I patch Lua support into the docker-mailserver container upon initial startup (through user-patches.sh). I would like this to be included by default.

### Applicable Users

Any users who use an authentication backend that does not fit in any other category. One example from my use case is HTTP basic authentication against Nextcloud (DAV), over HTTPS of course.

### Are you going to implement it?

Yes, because I know the probability of someone else doing it is low and I can learn from it.

### What are you going to contribute?

I'll try to make a pull request for this later. It should not be too difficult considering that nothing new needs to be developed. It just needs to be enabled.

So:
- Enable Dovecot Lua support (include dovecot-lua and dependencies).
- Write some light documentation. I don't think it is necessary to create new environment variables to compose the container. Lua-based authentication is an advanced topic. To use it, it would be best [to rely on Dovecot configuration overrides](https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/override-defaults/dovecot/). I'll add a usage example in the documentation.

**Comment by polarathene** [comment]
I would probably discourage this until more demand is expressed for it.

`user-patches.sh` is probably the way to go if you don't want to maintain your own `Dockerfile` to extend the image. We don't release too often and you can configure your `compose.yaml` to use `build` to reference a `Dockerfile` for this purpose rather easily.

Perhaps you can explain why that's too inconvenient for a niche request? Or why you need this authentication for Nextcloud in particular? I believe Nextcloud supports other authentication modes that can be compatible with Dovecot, what is special about this one?

**Comment by Zepmann** [comment]
@polarathene

Lua support is already included in the Docker image. Extending it to Dovecot would be a minimal effort without disadvantages.

The reason why I would like to have it included in a release is because I run docker-mailserver on a machine with limited resources, and building it would take ages. Furthermore, I think it is not worth it to set up an entire separate build infrastructure just to include LUA.

My `user-patches.sh` is a workaround and not a durable solution. It currently uses a dovecot-lua package that is newer than the dovecot package included in v12.1.0 since only the latest debs are available. It works, but mismatched versions might one day not work. I also need to include lua-5.3 as a dependency as the image only has lua-5.1.

> Or why you need this authentication for Nextcloud in particular? I believe Nextcloud supports other authentication modes that can be compatible with Dovecot, what is special about this one?

Can you give some examples of other authentication methods supported by Nextcloud which allow Dovecot to authenticate its users against it?

You seem quite skeptical about this proposal. Can you give some arguments as to why not to include it, considering that Lua itself is already included and dovecot-lua would be a minimal addition without any drawbacks if not used?

I will not spend any time and energy on this if the decision is already made beforehand to reject a pull request. Can any contributors shine a light on this?

**Comment by polarathene** [comment]
> The reason why I would like to have it included in a release is because I run docker-mailserver on a machine with limited resources, and building it would take ages.

You're already doing it with `user-patches.sh` each time the container is run, which is inefficient.

> Furthermore, I think it is not worth it to set up an entire separate build infrastructure just to include LUA.

I'm not sure what you envision as "entire separate build infrastructure"? Literally instead of `user-patches.sh` you have a `Dockerfile` that uses `FROM mailserver/docker-mailserver:12.1` for example, followed by your own additions. You then have have your `compose.yaml` reference that.

`docker compose up` will build that image instead of pulling an image to run directly. The `Dockerfile` image build is just a local image with a small layer of your changes on top of the base layer (our DMS release). Updating just shifts the version tag to bump to the `Dockerfile` instead of the `image` field in `compose.yaml`.

You're really not introducing much here to complexity or infrastructure. If anything it should be better than your current `user-patches.sh` approach?

---

> My user-patches.sh is a workaround and not a durable solution. It currently uses a dovecot-lua package that is newer than the dovecot package included in v12.1.0 since only the latest debs are available.
> It works, but mismatched versions might one day not work. I also need to include lua-5.3 as a dependency as the image only has lua-5.1.

If you need to rely on packages that aren't available directly from the main debian repos, that may get some pushback from other maintainers. We already have problems from this situation and the current default to build newer Dovecot than Debian ships is holding back an image update already for us, there is talk about migrating away from Debian as our base image with this issue as a motivator.

So while I understand the benefit to you, we are reluctant to introduce more maintenance burden of that situation happening. If that was not a concern, you'd be fine with the suggested `Dockerfile` approach to extend DMS.

---

> Can you give some examples of other authentication methods supported by Nextcloud which allow Dovecot to authenticate its users against it?

You do it the other way around, and use a common authentication backend for both like LDAP, [Nextcloud supports this](https://docs.nextcloud.com/server/latest/admin_manual/configuration_user/user_auth_ldap.html)..

I don't know how many users you need to support, but if it's only a few this is very simple to configure LDAP for. We also have a feature request for OAuth / OIDC. At a glance this is not something Nextcloud seems to support delegating auth for unfortunately.

There is a [third-party auth option the Nextcloud docs mention](https://docs.nextcloud.com/server/latest/admin_manual/configuration_user/user_auth_ftp_smb_imap.html) for using IMAP to handle auth, in which case Dovecot could provide your users via DMS and Nextcloud auths against that instead.

I take it you're referring to [this Nextcloud API](https://docs.nextcloud.com/server/latest/admin_manual/configuration_user/user_provisioning_api.html) for your feature request.

---

> You seem quite skeptical about this proposal. Can you give some arguments as to why not to include it, considering that Lua itself is already included and dovecot-lua would be a minimal addition without any drawbacks if not used?

You're welcome to pursue a PR if you want to, I'm only giving a heads-up that it may not get approved.

If it's small and not a maintenance concern to us, it could be possible to include. Normally we defer to `user-patches.sh` for niche features, then to adding docs for benefit of others users to implement. Then if there is enough demand to warrant it we'd be more willing to approve of niche features.

---

> I will not spend any time and energy on this if the decision is already made beforehand to reject a pull request. Can any contributors shine a light on this?

The discouragement is only to not waste your time. If that's not a concern for you to implement the PR give it a go and we'll go from there.

You could lay out the changes here if they're small before pursuing a PR. Feel free to wait on the opinion of other maintainers, I am just relaying the usual stance. We have enough trouble maintaining the project as-is, so we're reluctant to approve every niche request that comes along (_even when they're individually small additions, it piles up as a whole_).

Often the features are offloaded onto us to support instead of the contributor, once that happens it's more work to eventually drop it if we have reason to. Some add friction to changes like the plan to change base image for example.

**Comment by Zepmann** [comment]
> > The reason why I would like to have it included in a release is because I run docker-mailserver on a machine with limited resources, and building it would take ages.
> 
> You're already doing it with `user-patches.sh` each time the container is run, which is inefficient.

I do not build it. I patch it in: downloading the binaries (deb files) and injecting them in the container filesystem.
 
> > Furthermore, I think it is not worth it to set up an entire separate build infrastructure just to include LUA.
> 
> I'm not sure what you envision as "entire separate build infrastructure"? Literally instead of `user-patches.sh` you have a `Dockerfile` that uses `FROM mailserver/docker-mailserver:12.1` for example, followed by your own additions. You then have have your `compose.yaml` reference that.

How would I do that without adjusting packages.sh?
 
> `docker compose up` will build that image instead of pulling an image to run directly. The `Dockerfile` image build is just a local image with a small layer of your changes on top of the base layer (our DMS release). Updating just shifts the version tag to bump to the `Dockerfile` instead of the `image` field in `compose.yaml`.

That's building. I want to avoid building.

> You're really not introducing much here to complexity or infrastructure. If anything it should be better than your current `user-patches.sh` approach?

Not if it requires more CPU time.
 
> > My user-patches.sh is a workaround and not a durable solution. It currently uses a dovecot-lua package that is newer than the dovecot package included in v12.1.0 since only the latest debs are available.
> > It works, but mismatched versions might one day not work. I also need to include lua-5.3 as a dependency as the image only has lua-5.1.
> 
> If you need to rely on packages that aren't available directly from the main debian repos, that may get some pushback from other maintainers. We already have problems from this situation and the current default to build newer Dovecot than Debian ships is holding back an image update already for us, there is talk about migrating away from Debian as our base image with this issue as a motivator.

I use the same package repositories that docker-mailserver uses. Note that for Dovecot the Debian repository of Dovecot is used, not the main Debian repositories. See packages.sh.

> So while I understand the benefit to you, we are reluctant to introduce more maintenance burden of that situation happening. If that was not a concern, you'd be fine with the suggested `Dockerfile` approach to extend DMS.

I do not see how it would be more maintenance to include one deb file from an already used repository when building the image. I tested it. The change is literally a single line in packages.sh. There are no conflicts since the deb package is in sync with the other components, since Dovecot's repository is used.

> > Can you give some examples of other authentication methods supported by Nextcloud which allow Dovecot to authenticate its users against it?
> 
> You do it the other way around, and use a common authentication backend for both like LDAP, [Nextcloud supports this](https://docs.nextcloud.com/server/latest/admin_manual/configuration_user/user_auth_ldap.html)..

My use case is that I do not want email users to use their main password to authenticate against email. If in that scenario an email address and its password is compromised, all authentication factors are compromised. See https://github.com/nextcloud/server/issues/40838 for more information.

I cannot make this happen if LDAP (in my case [lldap](https://github.com/lldap/lldap)) is used as an authentication backend.

> I don't know how many users you need to support, but if it's only a few this is very simple to configure LDAP for. We also have a feature request for OAuth / OIDC. At a glance this is not something Nextcloud seems to support delegating auth for unfortunately.

I know how to configure LDAP and use it.

Off-topic to this request, but Nextcloud [can be used as an OIDC identity provider](https://apps.nextcloud.com/apps/oidc).
 
> There is a [third-party auth option the Nextcloud docs mention](https://docs.nextcloud.com/server/latest/admin_manual/configuration_user/user_auth_ftp_smb_imap.html) for using IMAP to handle auth, in which case Dovecot could provide your users via DMS and Nextcloud auths against that instead.

See my use case. The two factors that are used for Nextcloud authentication are not to be used for mail authentication. Nextcloud provides an application password that when compromised, does not compromise the user's two factors (at most, only the user's mail, calendar and contacts).

> I take it you're referring to [this Nextcloud API](https://docs.nextcloud.com/server/latest/admin_manual/configuration_user/user_provisioning_api.html) for your feature request.

No, I do not. User provisioning is done in Nextcloud through LDAP as backend. Authentication is done through OIDC (Authelia as frontend), which uses LDAP as a backend for authentication.

> > You seem quite skeptical about this proposal. Can you give some arguments as to why not to include it, considering that Lua itself is already included and dovecot-lua would be a minimal addition without any drawbacks if not used?
> 
> You're welcome to pursue a PR if you want to, I'm only giving a heads-up that it may not get approved.

Understood. I am just looking for reasons why it might not. So far, I do not read any good reasons. That is no guarantee that a PR might be rejected, of course. Also, I'm happy that your critical about this.
 
> If it's small and not a maintenance concern to us, it could be possible to include. Normally we defer to `user-patches.sh` for niche features, then to adding docs for benefit of others users to implement. Then if there is enough demand to warrant it we'd be more willing to approve of niche features.

I just tested it by building it myself. All I did was add dovecot-lua to the package list in packages.sh (and disable my user-patches.sh, of course). Lua support in Dovecot works immediately. I would not like to use user-patches.sh, since the deb packages in the image do not have to be in sync with the deb packages in Dovecot's repository.

Adding dovecot-lua as a package seems like minimal maintenance to me. I can write the documentation for its usage as well.

> > I will not spend any time and energy on this if the decision is already made beforehand to reject a pull request. Can any contributors shine a light on this?
> 
> The discouragement is only to not waste your time. If that's not a concern for you to implement the PR give it a go and we'll go from there.

Does the above additional information benefit the fate of the PR (of a single line) positively?

> You could lay out the changes here if they're small before pursuing a PR. Feel free to wait on the opinion of other maintainers, I am just relaying the usual stance. We have enough trouble maintaining the project as-is, so we're reluctant to approve every niche request that comes along (_even when they're individually small additions, it piles up as a whole_).

I think I just did. :)

> Often the features are offloaded onto us to support instead of the contributor, once that happens it's more work to eventually drop it if we have reason to. Some add friction to changes like the plan to change base image for example.

I have no idea how the suggested change would impact a future base image change. Maybe someone with a long-term vision of docker-mailserver as a project can shine a light on this.

**Comment by casperklein** [comment]
> Does the above additional information benefit the fate of the PR (of a single line of added script code + documentation) positively?

The package size of `dovecot-lua` is about 1,6MB. I think that's fine to add to our image. If you provide some documentation / examples, chances are high IMO to get approved.

**Comment by polarathene** [comment]
> I do not build it. I patch it in: downloading the binaries (deb files) and injecting them in the container filesystem.

If you're not using `user-patches.sh` to accomplish it all, can you share a rough set of steps of what you're doing?

You can add additional files into the image with `COPY` in a `Dockerfile`. Alternatively you can use `docker cp` to copy into a container, and a similar command can make that an image IIRC, but `Dockerfile` would be the smarter way to go.

> How would I do that without adjusting `packages.sh`?

`user-patches.sh` or `RUN` in a `Dockerfile`.

> That's building. I want to avoid building.

I honestly don't see the issue. If you're really concerned you can build it on another system then use `docker save` to export a tarball and `docker load` to import it as an image onto your Docker host system.

You can also have a CI on Github that builds your image and publishes it to GHCR like we do, and just pull from that. That isn't too much effort, you can reference our own Github Actions workflows for a build and publish and you're most of the way there.

> Not if it requires more CPU time.

How often do you think you'll be building a new Docker image? As I said DMS does not release that often for this to be a real problem.

---

> I use the same package repositories that docker-mailserver uses. Note that for Dovecot the Debian repository of Dovecot is used, not the main Debian repositories. See `packages.sh`.

If you are adding a few lightweight packages and not adding any new repos / sources, it'll probably get approved but I would still advise roughing out the changes to make here and getting a 👍 from another maintainer if you're concerned with the time/effort to put such a PR together.

> I do not see how it would be more maintenance to include one deb file from an already used repository when building the image. I tested it. The change is literally a single line in `packages.sh`.
> There are no conflicts since the deb package is in sync with the other components, since Dovecot's repository is used.

You're more familiar with what changes you're wanting to push, it wasn't very clear earlier (plus it was about 2am for me 😅 )

There's one Dovecot package (`xapian`) that we had been using from Debian repos until the Dovecot community repo was used, this caused breakage and the workaround was to compile the package ourselves during our image build.

We do not want to have that problem introduced again, if your PR introduces a package that later does hit that issue, or isn't readily available from a future base image (_Fedora or Alpine are being discussed_), it'll be dropped.

Provided there is no maintenance burden offloaded onto the project, then there's no issue.

---

> I just tested it by building it myself. All I did was add dovecot-lua to the package list in packages.sh (and disable my user-patches.sh, of course). Lua support in Dovecot works immediately.
> Adding dovecot-lua as a package seems like minimal maintenance to me. I can write the documentation for its usage as well.
> Does the above additional information benefit the fate of the PR (of a single line of added script code + documentation) positively?

> I think I just did. :)
> A single package (dovecot-lua) would be added to [target/scripts/build/packages.sh](https://github.com/docker-mailserver/docker-mailserver/blob/master/target/scripts/build/packages.sh).

Yes this sounds fine so long as we don't get any new `xapian` like issues down the road 👍 

> I have no idea how the suggested change would impact a future base image change. Maybe someone with a long-term vision of docker-mailserver as a project can shine a light on this.

As mentioned, if it becomes a maintenance problem it may get dropped. This will happen for `xapian` once Dovecot 2.4 / 3.0 is out IIRC with an alternative replacement that doesn't have the same maintenance concerns.
