### ISSUE TITLE
other: Dkim generation works only after adding a user

### ISSUE THREAD

**Issue by jaimebw** [docker-mailserver/docker-mailserver#3601]
### Subject

I would like some feedback concerning a use case

### Description

Hi! I was trying to setup an email server following the [tutorial](https://docker-mailserver.github.io/docker-mailserver/latest/examples/tutorials/basic-installation/). When it came the moment to generate the Dkim key, something odd happened. Basically, I got the next output:

```bash
./setup.sh config dkim
[ WARNING ]  No entries found, no keys to make
```

Everything on my end was looking good. I created an email user and ran the same command, and it generated the key. 
Is this the intended behaviours?
I'm currently running this on an AWS EC2 Amazon Linux 2 instance. I can try to repeat it again if this is not the case.

**Comment by georglauterbach** [comment]
The page you linked contains three individual examples; which one exactly did you follow? I assume it is [this one](https://docker-mailserver.github.io/docker-mailserver/latest/examples/tutorials/basic-installation/#using-dms-as-a-local-mail-relay-for-containers)?

I have identified the location of this check in our code:

https://github.com/docker-mailserver/docker-mailserver/blob/cb62ce20e6f49d211a8f264b11feaed65582a338/target/bin/open-dkim#L128-L131

How this plays with your relay setup I don't know exactly. @polarathene any ideas?

**Comment by polarathene** [comment]
> @polarathene any ideas?

Using the `domain` arg and providing an explicit mail domain to create a key for should work.

Should be using `setup config dkim` with `docker exec` these days rather than `./setup.sh`, although it shouldn't make much of a difference it is a bit more explicit.

---

DKIM key just needs an asymmetric keypair (private + public keys), and then taking then adapting the public key for a DNS `TXT` record. Our `setup config dkim` command handles that for you, but you can also do it more manually as roughly documented here: https://github.com/docker-mailserver/docker-mailserver/pull/3231#discussion_r1161355541

**Comment by jaimebw** [comment]
> The page you linked contains three individual examples; which one exactly did you follow? I assume it is [this one](https://docker-mailserver.github.io/docker-mailserver/latest/examples/tutorials/basic-installation/#using-dms-as-a-local-mail-relay-for-containers)?
> 
> I have identified the location of this check in our code:
> 
> https://github.com/docker-mailserver/docker-mailserver/blob/cb62ce20e6f49d211a8f264b11feaed65582a338/target/bin/open-dkim#L128-L131
> 
> How this plays with your relay setup I don't know exactly. @polarathene any ideas?

I used the "Using DMS as a local mail relay for containers" example.

**Comment by jaimebw** [comment]
> > @polarathene any ideas?
> 
> Using the `domain` arg and providing an explicit mail domain to create a key for should work.
> 
> Should be using `setup config dkim` with `docker exec` these days rather than `./setup.sh`, although it shouldn't make much of a difference it is a bit more explicit.
> 
> DKIM key just needs an asymmetric keypair (private + public keys), and then taking then adapting the public key for a DNS `TXT` record. Our `setup config dkim` command handles that for you, but you can also do it more manually as roughly documented here: [#3231 (comment)](https://github.com/docker-mailserver/docker-mailserver/pull/3231#discussion_r1161355541)

I'll follow this next time. Thanks for the tip.
