### ISSUE TITLE
other: how to configure a postfix alias that pipes to a script

### ISSUE THREAD

**Issue by jwaes** [docker-mailserver/docker-mailserver#3649]
### Subject

I would like some feedback concerning a use case

### Description

I want to use docker-mailserver as a smtp-only node to pass through mails to Odoo (erp system)

Therefore i need to get something like this into the `alias` or `virtual` config files.

`email@address: "|/odoo-directory/addons/mail/static/scripts/odoo-mailgate.py -d <database-name> -u <userid> -p <password>"`

Using the `setup` script it really sees this as a user and escapes it to a string.

`Nov 21 22:35:25 mail postfix/local[4834]: E52E5A4389F: to=<"|/usr/local/bin/odoo-mailgate.py - [...] status=bounced (unknown user: "|/usr/local/bin/odoo-mailgate.py [...]`

What would be the best aproach for this ?

**Comment by polarathene** [comment]
You can configure a mail transport in `master.cf` to have mail handed over to a process/command.

DMS doesn't have explicit support for it, but Postfix also provides a transport map configuration, which can match by email address (_by full address, local-part, domain-part, or regex_).

I'm not able to walk you through those steps, but you should be able to find the docs or guides with a search engine easily enough.
- `master.cf` will be 1-2 lines and you can add that to DMS via the `postfix-master.cf` file feature (see DMS docs). It'll apply those changes to the internal `master.cf` for you and needs to follow the `postconf` command syntax for `master.cf`.
- Alternatively, use our `user-patches.sh` file (see DMS docs) for appending your own file snippet to the `/etc/postfix/master.cf` file. This will add it after DMS finishes setup scripts, just remember to proper re-create your container, as `restart` or `stop + start` will use the same container and that would naively append the same content each time, resulting in duplicate lines.
- The transport maps config you'll need to mount (_Somewhere in `/tmp/docker-mailserver` should be fine, or you could place in a custom location, but try avoid `/etc/postfix`_). This then needs to be referenced by the Postfix `main.cf` file, which like prior advice you can use `postfix-main.cf` or `user-patches.sh`.

Mail should then arrive to DMS, and the transport map will redirect anything that matches it's config to the transport of your choosing (_eg: your custom python script_).
