### ISSUE TITLE
bug report: `milter-reject: END-OF-MESSAGE from xxx.xxx.xxx.xxx Spam message rejected; `

### ISSUE THREAD

**Issue by jessec** [docker-mailserver/docker-mailserver#3658]
### 📝 Preliminary Checks

- [ ] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

When I use an email client from my home everything is ok. When I setup the email account in my CRM (espocrm) I get the message below and the message won't be send to the recipient. 

I did some digging and as far as I can see the message comes from rspamd see below.

What I don't understand is why is an email send from my home address with an email client allowed and from a CRM on a VPS server it is not allowed. I used multiple VPS servers / multiple IP addresses. I'm a bit lost. Is it possible to maybe white list my CRM?

### 👟 Reproduction Steps

As a test I increased the spam reject level in `/etc/rspamd/actions.conf`:

```
reject = 1500; # Reject when reaching this score
```

And then I got this:

```
Nov 26 13:03:46 xslafhd postfix/sender-cleanup/cleanup[1139]: warning: incoming/949973E65C: too many reverse jump records
Nov 26 13:03:46 xslafhd postfix/sender-cleanup/cleanup[1139]: warning: milter8_message: error reading incoming/949973E65C: Success
Nov 26 13:03:46 xslafhd postfix/sender-cleanup/cleanup[1139]: 949973E65C: milter-reject: END-OF-MESSAGE from static.91.45.: 4.3.0 Queue file write error; from=<> to=<> proto=ESMTP helo=<7d0ddf7be8cd>
```

And with a `reject = 15` I get this:

```
milter-reject: END-OF-MESSAGE from xxx.xxx.xxx.xxx Spam message rejected; 
```

```
worker {
    rspamd_proxy {
        upstream {
            local {
                self_scan = true;
                default = true;
                hosts = "localhost";
            }
        }
        count = 2;
        milter = true;
        max_retries = 5;
        discard_on_reject = false;
        timeout = 120;
        spam_header = "X-Spam";
        quarantine_on_reject = false;
        reject_message = "Spam message rejected";
        bind_socket = "127.0.0.1:11332";
    }
}
```

I also tried to add the IP address of the CRM to the `local_addrs` but that also didn't help 

Is it possible that I need to add the IP of my CRM to a whitelist in rspam?

https://rspamd.com/doc/modules/whitelist.html

### 🐋 DMS Version

v0.0.0

### 💻 Operating System and Architecture

Unknown

### ⚙️ Container configuration files

```yml
# Share your compose.yaml here, redact anything sensitive
# example.com is a good placeholder if you don't want to share your real domain
# If there is more than one domain, use example1.com, example2.com, etc
```

### 📜 Relevant log output

```
...
```

**Comment by tzerber** [comment]
Sounds to me that either your VPS is sending email with something like sendmail trying to pretend it's the actual mail host, OR something is wrong with the DNS settings on what host can use what VPS for MX/mail delivery so it triggers spam checks, or a messy combination of both. 

Are you sure your CRM is actually using the SMTP settings to send mail (host port etc etc) and not just the localhost's mail functions / some weirdness like php's sendmail?

**Comment by polarathene** [comment]
If this is rspamd related, @georglauterbach will likely expect you to open a proper bug report (_**EDIT:** or update this one, I've assisted you a bit with that_).

We are quite clear when you try to report an issue without the context we request to open a [`Q&A` on Github Discussions](https://github.com/orgs/docker-mailserver/discussions):

![image](https://github.com/docker-mailserver/docker-mailserver/assets/5098581/a57fdbec-d303-42cf-9164-43c4520c9d64)

---

@jessec I have converted your issue to the expected bug report template, you still need to update the:
- Confirm that you've done the preliminary checks (_do give the debugging page a look, v13 docs are published now and improved_).
- Container config (_`compose.yaml` + anything else like `.env` referenced_).
- OS DMS runs on.
- DMS version used.

**Comment by jessec** [comment]
I will do fill in the bug report. But just wanted to update this. I installed my crm (espocrm) local here at home and everything worked same as with the thunderbird email client. So I will focus my attention on the postfix/rspamd.

**Comment by polarathene** [comment]
> I added my vps server to the rspamd whitelist like in the gist below and everything worked.

I'm not familiar with the rspamd config here, but in general you should be cautious of allowing an IP address to bypass restrictions.

If other software were to try send mail from the VPS that you did not actually authorize, that kind of config can accidentally permit such. Which is usually why you want to restrict only to authenticated connections, rather than any connection from the VPS.

---

> Two of my vps servers where blacklisted and that caused rspamd to reject them as valid senders even when I had valid login credentials.
> This was the confusion since I assumed that as long as I can login I am per defenition a valid sender and it will skip all checks.

I think this was addressed in v13 release?:
- Docs for [`RSPAMD_CHECK_AUTHENTICATED`](https://docker-mailserver.github.io/docker-mailserver/v13.0/config/environment/#rspamd_check_authenticated) (default enabled)
- Changelog for [new `RSPAMD_CHECK_AUTHENTICATED` ENV in v13](https://github.com/docker-mailserver/docker-mailserver/blob/b037288e5ad20b11fab4f375eaf0fe51f2783cd9/CHANGELOG.md?plain=1#L45)

There is a bug fix release soon related to this new addition, so you may need to wait on that.

If it doesn't resolve the issue for you, then there may be another config that @georglauterbach knows of that rspamd requires. I know there is a few related to IP addresses that aren't integrated with `PERMIT_DOCKER` for example IIRC.

**Comment by jessec** [comment]
> It would be interesting to know how a `192.168.` address ends up on a blacklist; I mean, this is a private IP space after all.

The `192.168.` address is from the gist I just copied that in the real whitelist I used the IP of my VPS.

**Comment by jessec** [comment]
> > I added my vps server to the rspamd whitelist like in the gist below and everything worked.
> 
> I'm not familiar with the rspamd config here, but in general you should be cautious of allowing an IP address to bypass restrictions.
> 
> If other software were to try send mail from the VPS that you did not actually authorize, that kind of config can accidentally permit such. Which is usually why you want to restrict only to authenticated connections, rather than any connection from the VPS.
> 
> > Two of my vps servers where blacklisted and that caused rspamd to reject them as valid senders even when I had valid login credentials.
> > This was the confusion since I assumed that as long as I can login I am per defenition a valid sender and it will skip all checks.
> 
> I think this was addressed in v13 release?:
> 
> * Docs for [`RSPAMD_CHECK_AUTHENTICATED`](https://docker-mailserver.github.io/docker-mailserver/v13.0/config/environment/#rspamd_check_authenticated) (default ~enabled~ disabled)
> * Changelog for [new `RSPAMD_CHECK_AUTHENTICATED` ENV in v13](https://github.com/docker-mailserver/docker-mailserver/blob/b037288e5ad20b11fab4f375eaf0fe51f2783cd9/CHANGELOG.md?plain=1#L45)
> 
> There is a bug fix release soon related to this new addition, so you may need to wait on that.
> 
> If it doesn't resolve the issue for you, then there may be another config that @georglauterbach knows of that rspamd requires. I know there is a few related to IP addresses that aren't integrated with `PERMIT_DOCKER` for example IIRC.

Yes I agree this degrades security somewhat but in my case I find that acceptable. Off course other situations might differ.
