### ISSUE TITLE
bug report: Test on rspamd private key files not working as expected

### ISSUE THREAD

**Issue by mpatton125** [docker-mailserver/docker-mailserver#3665]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

target/scripts/startup/setup.d/security/rspamd.sh

`if find "$(realpath -eL "${FILE}")" -user _rspamd -or -group _rspamd -or -perm -o=r -exec false {} +; then`

Should likely be:

`if find "$(realpath -eL "${FILE}")" \( -user _rspamd -or -group _rspamd -or -perm -o=r \) -exec false {} +; then`

As it currently stands the test does not appear to work correctly, failing to -exec false when conditions are true - which causes "does not appear to have correct permissions/ownership for Rspamd to use it" message in logs.

### 👟 Reproduction Steps

```
-r--r--r--. 1 _rspamd _rspamd 1704 Oct  5 13:47 rsa-2048-mail-nine-hells.net.private.txt
```

Causes "does not appear to have correct permissions/ownership for Rspamd to use it" message in logs.

### 🐋 DMS Version

v13.0.0

### 💻 Operating System and Architecture

Fedora 39 x86_64

### ⚙️ Container configuration files

```yml
[Container]
Image=docker.io/mailserver/docker-mailserver:latest
ContainerName=mailserver
Environment=TZ=Australia/Sydney PERMIT_DOCKER=none SSL_TYPE=letsencrypt POSTMASTER_ADDRESS=mike@nine-hells.net ENABLE_RSPAMD=1 ENABLE_OPENDKIM=0 ENABLE_OPENDMARC=0 ENABLE_POLICYD_SPF=0 ENABLE_AMAVIS=0 ENABLE_SPAMASSASSIN=0 POSTFIX_INET_PROTOCOLS=ipv4 DOVECOT_INET_PROTOCOLS=ipv4 ENABLE_FAIL2BAN=1
Label=io.containers.autoupdate=registry
#Network=default.network
Network=pasta:-I,eth0
PublishPort=5025:25
PublishPort=5465:465
PublishPort=5587:587
PublishPort=5993:993
PublishPort=11334:11334
Volume=/storage/docker/mailserver/config/:/tmp/docker-mailserver/
Volume=/storage/docker/mailserver/config/postfix-policyd-spf.conf:/etc/postfix-policyd-spf-python/policyd-spf.conf
Volume=/storage/docker/mailserver/mail-data/:/var/mail/
Volume=/storage/docker/mailserver/mail-state/:/var/mail-state/
Volume=/storage/docker/mailserver/mail-logs/:/var/log/mail/
Volume=/storage/docker/mailserver/statistic.conf:/etc/rspamd/statistic.conf
Volume=/etc/localtime:/etc/localtime:ro
Volume=/storage/docker/caddy/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/mail.nine-hells.net/mail.nine-hells.net.crt:/etc/letsencrypt/live/mail.nine-hells.net/fullchain.pem
Volume=/storage/docker/caddy/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/mail.nine-hells.net/mail.nine-hells.net.key:/etc/letsencrypt/live/mail.nine-hells.net/privkey.pem
PodmanArgs=--hostname mail.nine-hells.net --cap-add=NET_ADMIN

[Service]
Restart=always

[Install]
WantedBy=default.target
```

### 📜 Relevant log output

```Text
[ WARNING ]  (Rspamd setup) Rspamd DKIM private key file '/tmp/docker-mailserver/rspamd/dkim/rsa-2048-mail-nine-hells.net.private.txt' does not appear to have correct permissions/ownership for Rspamd to use it
[ WARNING ]  (Rspamd setup) Rspamd DKIM private key file '/tmp/docker-mailserver/rspamd/dkim/rsa-2048-mail-nine-hells.net.private.txt' does not appear to have correct permissions/ownership for Rspamd to use it
```

**Comment by mpatton125** [comment]
I tested my above amendment (original comment) and it appears to work correctly.

**Comment by 2GetApp** [comment]
I can confirm this bug. After upgrading from 12.1.0 to 13.0.0, the warning message appears and the outbound emails are no longer signed with dkim keys (outbound emails were signed correctly when using 12.1.0).
And I also checked my private.txt file. It has 440 permission and 112:114 ownership (corresponding to _rspamd:_rspamd in the container).

**Comment by polarathene** [comment]
This would be due to the review discussion here: https://github.com/docker-mailserver/docker-mailserver/pull/3627#discussion_r1388697547

I only tested with my original suggestion which was a bit simpler.

@georglauterbach will resolve this as it's his area of DMS, hopefully with an addition to the test suite to better detect this 😅

**Comment by mpatton125** [comment]
Correct me if I am wrong, but my understanding was that this change would produce a warning message only and wouldn't impact the actual dkim functionality?  Were there any other dkim changes for v13.0.0 that might have prevented dkim signing?

**Comment by cybermcm** [comment]
Did switch to rspamd yesterday during upgrade to v13. Tried until midnight to get around the WARN message in the log file about DKIM private key file ;-). I can confirm that my mails aren't DKIM signed any longer.
Thanks for your hard work despite this bug.

**Comment by Dubbeldrank** [comment]
Running into the same problem here, i do have a question next to this. What are the correct permissions/ownership for the private key file?

**Comment by Dubbeldrank** [comment]
> @Dubbeldrank: If the key is generated with the inline script is defaults to _rspamd:_rspamd and 600 permission

Ahh, the 600 is still on there, but i changed ownership because it was weird. HBut i forgot that it relates to the user inside the container. So i might have to change it back, just need to know the user id and the group id again. For when a fix is released.

**Comment by cybermcm** [comment]
> Ahh, the 600 is still on there, i changed ownership because it was weird. But i forgot that it relates to the user inside the container. So i might have to change it back, just need to know the user id and the group id again for when a fix is released.

Just do it inside your container:
`docker exec -it mail chown _rspamd:_rspamd /tmp/docker-mailserver/rspamd/dkim/private.key`
change container name and private key file name

**Comment by georglauterbach** [comment]
I will provide a PR today (tonight) and release v13.0.1. Keep the outputs of the commands I posted flowing in :)

**Comment by Dubbeldrank** [comment]
Here is my output:

`[1] root@mail:/# rspamadm configdump dkim_signing
*** Section dkim_signing ***
key_prefix = "DKIM_KEYS";
use_domain = "header";
allow_hdrfrom_mismatch = false;
domain {
    <domain>.<tld> {
        path = "/tmp/docker-mailserver/rspamd/dkim/rsa-2048-mail-<domain>.<tld>.private.txt";
        selector = "mail";
    }
}
allow_username_mismatch = false;
sign_authenticated = true;
use_esld = true;
selector = "dkim";
enabled = true;
symbol = "DKIM_SIGNED";
allow_envfrom_empty = true;
allow_hdrfrom_multiple = false;
sign_local = true;
sign_networks [
    "127.2.4.7",
]
check_pubkey = true;
try_fallback = true;
use_redis = false;

*** End of section dkim_signing ***

[2] root@mail:/# ls -lh /etc/rspamd/{local,override}.d/
/etc/rspamd/local.d/:
total 76K
-rw-r--r-- 1 root root 238 Nov 26 16:32 actions.conf
-rw-r--r-- 1 root root 372 Nov 27 12:47 antivirus.conf
-rw-r--r-- 1 root root  83 Nov 27 12:47 clickhouse.conf
-rw-r--r-- 1 root root  80 Nov 27 12:47 elastic.conf
-rw-r--r-- 1 root root  87 Nov 26 16:32 greylist.conf
-rw-r--r-- 1 root root 485 Nov 26 16:32 hfilter_group.conf
-rw-r--r-- 1 root root 136 Nov 26 16:32 logging.inc
-rw-r--r-- 1 root root  88 Nov 27 12:47 metric_exporter.conf
-rw-r--r-- 1 root root 103 Nov 26 16:32 milter_headers.conf
-rw-r--r-- 1 root root  79 Nov 27 12:47 neural.conf
-rw-r--r-- 1 root root 122 Nov 26 16:32 options.inc
-rw-r--r-- 1 root root 115 Nov 27 12:47 redis.conf
-rw-r--r-- 1 root root  83 Nov 27 12:47 reputation.conf
-rw-r--r-- 1 root root 273 Nov 26 16:32 settings.conf
-rw-r--r-- 1 root root  85 Nov 27 12:47 spamassassin.conf
-rw-r--r-- 1 root root  87 Nov 27 12:47 url_redirector.conf
-rw-r--r-- 1 root root  96 Nov 26 16:32 worker-controller.inc
-rw-r--r-- 1 root root 111 Nov 26 16:32 worker-normal.inc
-rw-r--r-- 1 root root 390 Nov 26 16:32 worker-proxy.inc

/etc/rspamd/override.d/:
total 8.0K
-rw-r--r-- 1 root root 466 Nov 27 12:47 dkim_signing.conf
-rw-r--r-- 1 root root 103 Nov 27 12:47 worker-controller.inc

[3] root@mail:/# ls -lh /tmp/docker-mailserver/rspamd/**
-rw-r--r-- 1 root root  126 Jul 13 13:17 /tmp/docker-mailserver/rspamd/custom-commands.conf

/tmp/docker-mailserver/rspamd/dkim:
total 12K
-rw-r----- 1 _rspamd _rspamd 1.7K Jul 13 11:44 rsa-2048-mail-<domain>.<tld>.private.txt
-rw-r--r-- 1 root    root     411 Jul 13 11:44 rsa-2048-mail-<domain>.<tld>.public.dns.txt
-rw-r--r-- 1 root    root     451 Jul 13 11:44 rsa-2048-mail-<domain>.<tld>.public.txt

/tmp/docker-mailserver/rspamd/override.d:
total 8.0K
-rw-r--r-- 1 _rspamd _rspamd 466 Jul 13 11:44 dkim_signing.conf
-rw-r--r-- 1 root    root    103 Oct 27 01:01 worker-controller.inc`

**Comment by cybermcm** [comment]
my output:
```
root@mail:/# rspamadm configdump dkim_signing
*** Section dkim_signing ***
check_pubkey = true;
use_domain = "header";
allow_hdrfrom_mismatch = false;
allow_username_mismatch = true;
sign_networks [
    "127.2.4.7",
]
sign_authenticated = true;
use_esld = true;
selector = "dkim";
symbol = "DKIM_SIGNED";
domain {
    <domain>.net {
        selector = "mail";
        path = "/tmp/docker-mailserver/rspamd/dkim/rsa-2048-mail-<domain>.net.private.txt";
    }
}
allow_envfrom_empty = true;
allow_hdrfrom_multiple = false;
sign_local = false;
try_fallback = false;
use_redis = false;
key_prefix = "DKIM_KEYS";
enabled = true;

*** End of section dkim_signing ***
```

```
root@mail:/# ls -lh /etc/rspamd/{local,override}.d/
/etc/rspamd/local.d/:
total 76K
-rw-r--r-- 1 root root 238 Nov 26 16:32 actions.conf
-rw-r--r-- 1 root root 372 Nov 27 07:38 antivirus.conf
-rw-r--r-- 1 root root  83 Nov 27 07:38 clickhouse.conf
-rw-r--r-- 1 root root  80 Nov 27 07:38 elastic.conf
-rw-r--r-- 1 root root  87 Nov 26 16:32 greylist.conf
-rw-r--r-- 1 root root 485 Nov 26 16:32 hfilter_group.conf
-rw-r--r-- 1 root root 136 Nov 26 16:32 logging.inc
-rw-r--r-- 1 root root  88 Nov 27 07:38 metric_exporter.conf
-rw-r--r-- 1 root root 103 Nov 26 16:32 milter_headers.conf
-rw-r--r-- 1 root root  79 Nov 27 07:38 neural.conf
-rw-r--r-- 1 root root 122 Nov 26 16:32 options.inc
-rw-r--r-- 1 root root 115 Nov 27 07:38 redis.conf
-rw-r--r-- 1 root root  83 Nov 27 07:38 reputation.conf
-rw-r--r-- 1 root root 273 Nov 26 16:32 settings.conf
-rw-r--r-- 1 root root  85 Nov 27 07:38 spamassassin.conf
-rw-r--r-- 1 root root  87 Nov 27 07:38 url_redirector.conf
-rw-r--r-- 1 root root  96 Nov 26 16:32 worker-controller.inc
-rw-r--r-- 1 root root 111 Nov 26 16:32 worker-normal.inc
-rw-r--r-- 1 root root 390 Nov 26 16:32 worker-proxy.inc

/etc/rspamd/override.d/:
total 4.0K
-rw-r--r-- 1 root root 512 Nov 27 07:38 dkim_signing.conf
```

```
root@mail:/# ls -lh /tmp/docker-mailserver/rspamd/**
/tmp/docker-mailserver/rspamd/dkim:
total 12K
-rw------- 1 _rspamd _rspamd 1.7K Nov 26 22:30 rsa-2048-mail-<domain>.net.private.txt
-rw-r--r-- 1 root    root     411 Nov 26 22:30 rsa-2048-mail-<domain>.net.public.dns.txt
-rw-r--r-- 1 root    root     451 Nov 26 22:30 rsa-2048-mail-<domain>.net.public.txt

/tmp/docker-mailserver/rspamd/override.d:
total 4.0K
-rw-r--r-- 1 _rspamd _rspamd 512 Nov 26 23:24 dkim_signing.conf

```

**Comment by georglauterbach** [comment]
Or simply delete `/etc/rspamd/local.d/settings.conf` and restart Rspamd (`supervisorctl restart rspamd`) which is easier.

**Comment by Dubbeldrank** [comment]
Merging is blocked unfortunately. Was hoping for a fix this morning.

**Comment by georglauterbach** [comment]
Sorry for the delay; working on PR feedback took longer than anticipated. We want to ship a proper release; I will try to get it done today.

**Comment by georglauterbach** [comment]
The hotfix will be available on `:edge` in half an hour - feel free to test and report back any issues that you might still encounter. We will try to merge #3666 ASAP to release v13.0.1.

**Comment by jessec** [comment]
> The hotfix will be available on `:edge` in half an hour - feel free to test and report back any issues that you might still encounter. We will try to merge #3666 ASAP to release v13.0.1.

I have a server that was created 36 hours ago and doesn't sign dkim is it possible that it is related to this issue? If so what version should I use to fix it :edge or an older version?

**Comment by polarathene** [comment]
[v13.0.1](https://github.com/docker-mailserver/docker-mailserver/releases/tag/v13.0.1) is released. Sorry for the delay, CI is building the new image release and should be available shortly.

**Comment by cybermcm** [comment]
@polarathene: Thanks, image is ready, DKIM is working. Logfiles still shows `Welcome to docker-mailserver 13.0.0` on start ;-)

**Comment by polarathene** [comment]
> `Welcome to docker-mailserver 13.0.0` on start ;-)

Whoops! Looks like I missed a spot 😬 

I've addressed that here: https://github.com/docker-mailserver/docker-mailserver/pull/3676

I don't think it warrants a new patch release, but if anyone does have an issue with the slight inaccuracy with that log message let me know.

**Comment by matthijs-oosterhoff** [comment]
I just noticed this issue on my DMS instance. Nice to see that there a fix available so quickly! Keep up the good work 👍
