### ISSUE TITLE
question: Why does DMS log `warning: TLS library problem: error:1408F10B:SSL`

### ISSUE THREAD

**Issue by duelidave** [docker-mailserver/docker-mailserver#3670]
### Subject

I would like some feedback concerning a use case

### Description

Hi there, 

i'm not sure what is happening. My DMS does not start anymore since a few days (maybe since the update to version 13) im not sure about this tbh.

Anyways i dont see anything suspicious except this in all of my log files. 

```
Nov 28 00:27:22 mail postfix/submissions/smtpd[765]: connect from traefik.proxy[172.18.0.2]
Nov 28 00:27:22 mail postfix/submissions/smtpd[765]: SSL_accept error from traefik.proxy[172.18.0.2]: -1
Nov 28 00:27:22 mail postfix/submissions/smtpd[765]: warning: TLS library problem: error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:331:
Nov 28 00:27:22 mail postfix/submissions/smtpd[765]: lost connection after CONNECT from traefik.proxy[172.18.0.2]
Nov 28 00:27:22 mail postfix/submissions/smtpd[765]: disconnect from traefik.proxy[172.18.0.2] commands=0/0
Nov 28 00:27:24 mail postfix/submissions/smtpd[765]: connect from traefik.proxy[172.18.0.2]
Nov 28 00:27:24 mail postfix/submissions/smtpd[765]: SSL_accept error from traefik.proxy[172.18.0.2]: -1
Nov 28 00:27:24 mail postfix/submissions/smtpd[765]: warning: TLS library problem: error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:331:
Nov 28 00:27:24 mail postfix/submissions/smtpd[765]: lost connection after CONNECT from traefik.proxy[172.18.0.2]
Nov 28 00:27:24 mail postfix/submissions/smtpd[765]: disconnect from traefik.proxy[172.18.0.2] commands=0/0

```

does anyone know what this is about? i tried googling but could not make sense of that. i mean my traefik setup is ok i think since all my other services are working fine.

im using traefik setup with letsencrypt. if you need more details please let me know. 
Im happy about any advice since im clueless rn. 

regards,
dave

**Comment by polarathene** [comment]
We are quite clear when you try to report an issue without the context we request, that you should instead open a [`Q&A` on Github Discussions](https://github.com/orgs/docker-mailserver/discussions):

![image](https://github.com/docker-mailserver/docker-mailserver/assets/5098581/a57fdbec-d303-42cf-9164-43c4520c9d64)

If you do attempt to raise a proper bug report, you'll be advised to [check out the debugging docs page](https://docker-mailserver.github.io/docker-mailserver/v13.0/config/debugging/):

![image](https://github.com/docker-mailserver/docker-mailserver/assets/5098581/b35fa5c4-4882-43ec-9b12-c19ce5cbab09)

And from there right at the top you'll get some common advice:

![image](https://github.com/docker-mailserver/docker-mailserver/assets/5098581/28ba469b-f17d-46dc-b34b-c7f07e923edd)

- Try restarting DMS correctly.
- If that doesn't work, then check the validity of your certificate files.
- Verify that changing back to v12.1 works fine, and going back to v13 afterwards breaks again.

---

> I'm using traefik setup with letsencrypt. if you need more details please let me know.
> I'm happy about any advice since I'm clueless.

If the above doesn't help, raise a proper bug report, or ask the community on the [GH discussions page](https://github.com/docker-mailserver/docker-mailserver/discussions).

**Comment by duelidave** [comment]
holy shit. i was searching for quite some hours now. and somehow i didnt see a fucking twist in my ips from the `haproxy_trusted_networks` in the `config/dovecot.cf` file. 

This somehow fucks me up every few months when treafik and all my service (my host machine) is having a restart. ip adress from traefik is changing and i have to make adjustments to the trusted_networks CIDR entrys. Im not sure how to fix that except giving a very wirde ip range. 

so everybody stumbling upon this: **take a close look at ip adresses**

**Comment by duelidave** [comment]
oh, didn't know about that yet :-) but why wouldn't docker be able to assign ip ranges for the networks right? i will give it a try! many thanks

**Comment by duelidave** [comment]
now that i'm thinking of that again:

wouldn't it be nice to include this in the traefik example? 

if you want me to, i could create a PR that includes the dns in the compose and give a little hint for the haproxy config??

**Comment by polarathene** [comment]
> if you want me to, i could create a PR that includes the dns in the compose and give a little hint for the haproxy config??

If you see value in it go for it! 😎 

I am not that familiar with haproxy and I've barely used Traefik, but we welcome contributions to the docs ❤️
