### ISSUE TITLE
other: dms version dkim fix

### ISSUE THREAD

**Issue by jessec** [docker-mailserver/docker-mailserver#3672]
### Subject

I would like some feedback concerning a use case

### Description

One of my servers didn't sign with dkim and then I read this: https://github.com/docker-mailserver/docker-mailserver/issues/3665#issuecomment-1829437925

> _The hotfix will be available on :edge in half an hour - feel free to test and report back any issues that you might still encounter. We will try to merge https://github.com/docker-mailserver/docker-mailserver/pull/3666 ASAP to release v13.0.1._

I have a server that was created 36 hours ago and doesn't sign dkim is it possible that it is related to this issue?

If so what version should I use to fix it `:edge`, or an older version?

**Comment by medebb** [comment]
´´´
REPOSITORY                                    TAG       IMAGE ID       CREATED        SIZE
ghcr.io/docker-mailserver/docker-mailserver   edge      f2a02dcc2372   12 hours ago   620MB
´´´
With this image mails are signed.

**Comment by polarathene** [comment]
I'm getting a little annoyed since [I've brought this up to you already very recently](https://github.com/docker-mailserver/docker-mailserver/issues/3658#issuecomment-1827052210).

You are ignoring this:

> _Please do not use this form to bypass doing a proper bug report._
> _The issue tracker is for anything relevant to the project itself, **not individual support queries**._
> _If you don't want to fill out a bug report, please **ask support questions at our community discussions page**:_ https://github.com/orgs/docker-mailserver/discussions

---

> doesn't sign dkim is it possible that it is related to this issue?

If you enabled rspamd and had the same error, quite possibly. You didn't indicate if you used v12.1.0 (should work) or v13.0.0, don't use `:latest`. If you filed a proper bug report, we'd have this information to better respond to you.

> If so what version should I use to fix it :edge, or an older version?

You quoted an issue that told you that v12.1.0 was signing with DKIM correctly, and the comment you've quoted states `:edge` contains the fix, try them?

If you were instead using `:edge` already in the past, you need to tell Docker to force pull the tag so you get the latest update for the `:edge` tag (_similar to the problem you can have with `:latest` tag, and why you shouldn't use `:latest`_).

**Comment by georglauterbach** [comment]
Re-pull the very _latest_ (no pun intended) `:edge` and try again.

**Comment by jessec** [comment]
OK I get it. I will post this kind of questions in the discussions page. It's just that the tag "help wanted" made sense to me and the label "bug" not.




> I'm getting a little annoyed since [I've brought this up to you already very recently](https://github.com/docker-mailserver/docker-mailserver/issues/3658#issuecomment-1827052210).
> 
> You are ignoring this:
> 
> > _Please **do not use this form to bypass** doing a proper bug report._
> > _The issue tracker is for anything relevant to the project itself, **not individual support queries**._
> > _If you don't want to fill out a bug report, please **ask support questions at our community discussions page**:_ https://github.com/orgs/docker-mailserver/discussions
> 
> > doesn't sign dkim is it possible that it is related to this issue?
> 
> If you enabled rspamd and had the same error, quite possibly. You didn't indicate if you used v12.1.0 (should work) or v13.0.0, don't use `:latest`. If you filed a proper bug report, we'd have this information to better respond to you.
> 
> > If so what version should I use to fix it :edge, or an older version?
> 
> You quoted an issue that told you that v12.1.0 was signing with DKIM correctly, and the comment you've quoted states `:edge` contains the fix, try them?
> 
> If you were instead using `:edge` already in the past, you need to tell Docker to force pull the tag so you get the latest update for the `:edge` tag (_similar to the problem you can have with `:latest` tag, and why you shouldn't use `:latest`_).

**Comment by jessec** [comment]
> Re-pull the very _latest_ (no pun intended) `:edge` and try again.

I did this and everything works now. 

BTW what would be the best version to run in production?


Thanks!
