### ISSUE TITLE
feature request: Dovecot Mail Compression Plugin

### ISSUE THREAD

**Issue by dracossan** [docker-mailserver/docker-mailserver#3673]
### Context

To be able to activate the mail compression from the docker image with some ENV variables to decrease space usage on servers.

### Description

[Compress plugin](https://doc.dovecot.org/3.0/configuration_manual/mail_compress_plugin/#mail-compress-plugin) can be used to read compressed mbox, maildir or dbox files. It can also be used to write (via IMAP, [LDA](https://doc.dovecot.org/3.0/configuration_manual/protocols/lda/#lda) and/or [LMTP Server](https://doc.dovecot.org/3.0/configuration_manual/protocols/lmtp_server/#lmtp-server)) compressed messages to [dbox](https://doc.dovecot.org/3.0/admin_manual/mailbox_formats/dbox/#dbox-mbox-format) or [Maildir](https://doc.dovecot.org/3.0/admin_manual/mailbox_formats/maildir/#maildir-mbox-format) mailboxes.

### Alternatives

Use compressed file system which is not ideal on admin point of view.

### Applicable Users

All.

### Are you going to implement it?

No, and I understand that it is highly likely no one will implement it. Furthermore, I understand that this issue will likely become stale and will be closed.

### What are you going to contribute?

Tried to implement myself with no success. Following this [discussion](https://github.com/orgs/docker-mailserver/discussions/3664), i will try again and give feedback to anyone interested.

**Comment by georglauterbach** [comment]
If you have questions or are stuck at some point, ping us here and we'll try to help you.
