### ISSUE TITLE
Rspamd: provide RFC7489 compliance for SPF, DKIM & DMARC

### ISSUE THREAD

**Issue by georglauterbach** [docker-mailserver/docker-mailserver#3690]
### About

Rspamd should comply with [RFC7489](https://www.rfc-editor.org/rfc/rfc7489#page-24) to the best of its abilities.

### DMS' Action Scores

[Milter action scores](https://github.com/rspamd/rspamd/blob/master/conf/actions.conf) are configured to:

```txt
greylist = 4;
add_header = 6;
reject = 11;
```

### Symbols

[DMARC policies](https://mxtoolbox.com/DMARC/knowledgebase#/DMARC) can be

1. Allow
2. Allow but with failure (either SPF or DKIM failed)
3. N/A (non-existent)
4. Quarantine
5. Reject

[DKIM policies](https://mxtoolbox.com/DMARC/knowledgebase#/DKIM) can be

1. Allow
2. N/A (non-existent)
3. Temp-Fail
7. Perm-Fail

[SPF policies](https://mxtoolbox.com/DMARC/knowledgebase#/SPF) can be

2. Allow
3. N/A (non-existent)
8. Soft-fail
9. Fail

### Behavior

Here is a table of possible combinations of what can happen with SPF, DKIM & DMARC.

| SPF                   | DKIM                   | DMARC                                   | Action            |
| :-------------------- | :--------------------- | :-------------------------------------- | :---------------- |
| R_SPF_ALLOW    (  -1) | R_DKIM_ALLOW    (  -1) | DMARC_POLICY_ALLOW               (  -1) | pass       (  -3) |
| R_SPF_ALLOW    (  -1) | R_DKIM_ALLOW    (  -1) | DMARC_POLICY_NA                  ( 0.5) | pass       (-1.5) |
| R_SPF_ALLOW    (  -1) | R_DKIM_ALLOW    (  -1) | DMARC_POLICY_SOFTFAIL            ( 1.5) | pass       (-0.5) |
| R_SPF_ALLOW    (  -1) | R_DKIM_NA       (   1) | DMARC_POLICY_ALLOW_WITH_FAILURES (   0) | pass       (   0) |
| R_SPF_ALLOW    (  -1) | R_DKIM_NA       (   1) | DMARC_POLICY_NA                  ( 0.5) | pass       ( 0.5) |
| R_SPF_ALLOW    (  -1) | R_DKIM_NA       (   1) | DMARC_POLICY_SOFTFAIL            ( 1.5) | pass       ( 1.5) |
| R_SPF_ALLOW    (  -1) | R_DKIM_TEMPFAIL ( 1.5) | DMARC_POLICY_ALLOW_WITH_FAILURES (   0) | pass       ( 0.5) |
| R_SPF_ALLOW    (  -1) | R_DKIM_TEMPFAIL ( 1.5) | DMARC_POLICY_NA                  ( 0.5) | pass       (   1) |
| R_SPF_ALLOW    (  -1) | R_DKIM_TEMPFAIL ( 1.5) | DMARC_POLICY_SOFTFAIL            ( 1.5) | pass       (   2) |
| R_SPF_ALLOW    (  -1) | R_DKIM_PERMFAIL ( 4.5) | DMARC_POLICY_ALLOW_WITH_FAILURES (   0) | pass       ( 3.5) |
| R_SPF_ALLOW    (  -1) | R_DKIM_PERMFAIL ( 4.5) | DMARC_POLICY_NA                  ( 0.5) | greylist   (   4) |
| R_SPF_ALLOW    (  -1) | R_DKIM_PERMFAIL ( 4.5) | DMARC_POLICY_SOFTFAIL            ( 1.5) | greylist   (   5) |
| R_SPF_NA       ( 1.5) | R_DKIM_ALLOW    (  -1) | DMARC_POLICY_ALLOW_WITH_FAILURES (   0) | pass       ( 0.5) |
| R_SPF_NA       ( 1.5) | R_DKIM_ALLOW    (  -1) | DMARC_POLICY_NA                  ( 0.5) | pass       (   1) |
| R_SPF_NA       ( 1.5) | R_DKIM_ALLOW    (  -1) | DMARC_POLICY_SOFTFAIL            ( 1.5) | pass       (   2) |
| R_SPF_NA       ( 1.5) | R_DKIM_NA       (   1) | DMARC_POLICY_QUARANTINE          ( 1.5) | greylist   (   4) |
| R_SPF_NA       ( 1.5) | R_DKIM_NA       (   1) | DMARC_POLICY_REJECT              ( 5.5) | add_header (   8) |
| R_SPF_NA       ( 1.5) | R_DKIM_NA       (   1) | DMARC_POLICY_NA                  ( 0.5) | pass       (   3) |
| R_SPF_NA       ( 1.5) | R_DKIM_NA       (   1) | DMARC_POLICY_SOFTFAIL            ( 1.5) | greylist   (   4) |
| R_SPF_NA       ( 1.5) | R_DKIM_TEMPFAIL ( 1.5) | DMARC_POLICY_QUARANTINE          ( 1.5) | greylist   ( 4.5) |
| R_SPF_NA       ( 1.5) | R_DKIM_TEMPFAIL ( 1.5) | DMARC_POLICY_REJECT              ( 5.5) | add_header ( 8.5) |
| R_SPF_NA       ( 1.5) | R_DKIM_TEMPFAIL ( 1.5) | DMARC_POLICY_NA                  ( 0.5) | pass       ( 3.5) |
| R_SPF_NA       ( 1.5) | R_DKIM_TEMPFAIL ( 1.5) | DMARC_POLICY_SOFTFAIL            ( 1.5) | greylist   ( 4.5) |
| R_SPF_NA       ( 1.5) | R_DKIM_PERMFAIL ( 4.5) | DMARC_POLICY_QUARANTINE          ( 1.5) | add_header ( 7.5) |
| R_SPF_NA       ( 1.5) | R_DKIM_PERMFAIL ( 4.5) | DMARC_POLICY_REJECT              ( 5.5) | reject     (11.5) |
| R_SPF_NA       ( 1.5) | R_DKIM_PERMFAIL ( 4.5) | DMARC_POLICY_NA                  ( 0.5) | add_header ( 6.5) |
| R_SPF_NA       ( 1.5) | R_DKIM_PERMFAIL ( 4.5) | DMARC_POLICY_SOFTFAIL            ( 1.5) | add_header ( 7.5) |
| R_SPF_SOFTFAIL ( 2.5) | R_DKIM_ALLOW    (  -1) | DMARC_POLICY_ALLOW_WITH_FAILURES (   0) | pass       ( 1.5) |
| R_SPF_SOFTFAIL ( 2.5) | R_DKIM_ALLOW    (  -1) | DMARC_POLICY_NA                  ( 0.5) | pass       (   2) |
| R_SPF_SOFTFAIL ( 2.5) | R_DKIM_ALLOW    (  -1) | DMARC_POLICY_SOFTFAIL            ( 1.5) | pass       (   3) |
| R_SPF_SOFTFAIL ( 2.5) | R_DKIM_NA       (   1) | DMARC_POLICY_QUARANTINE          ( 1.5) | greylist   (   5) |
| R_SPF_SOFTFAIL ( 2.5) | R_DKIM_NA       (   1) | DMARC_POLICY_REJECT              ( 5.5) | add_header (   9) |
| R_SPF_SOFTFAIL ( 2.5) | R_DKIM_NA       (   1) | DMARC_POLICY_NA                  ( 0.5) | greylist   (   4) |
| R_SPF_SOFTFAIL ( 2.5) | R_DKIM_NA       (   1) | DMARC_POLICY_SOFTFAIL            ( 1.5) | greylist   (   5) |
| R_SPF_SOFTFAIL ( 2.5) | R_DKIM_TEMPFAIL ( 1.5) | DMARC_POLICY_QUARANTINE          ( 1.5) | greylist   ( 5.5) |
| R_SPF_SOFTFAIL ( 2.5) | R_DKIM_TEMPFAIL ( 1.5) | DMARC_POLICY_REJECT              ( 5.5) | add_header ( 9.5) |
| R_SPF_SOFTFAIL ( 2.5) | R_DKIM_TEMPFAIL ( 1.5) | DMARC_POLICY_NA                  ( 0.5) | greylist   ( 4.5) |
| R_SPF_SOFTFAIL ( 2.5) | R_DKIM_TEMPFAIL ( 1.5) | DMARC_POLICY_SOFTFAIL            ( 1.5) | greylist   ( 5.5) |
| R_SPF_SOFTFAIL ( 2.5) | R_DKIM_PERMFAIL ( 4.5) | DMARC_POLICY_QUARANTINE          ( 1.5) | add_header ( 8.5) |
| R_SPF_SOFTFAIL ( 2.5) | R_DKIM_PERMFAIL ( 4.5) | DMARC_POLICY_REJECT              ( 5.5) | reject     (12.5) |
| R_SPF_SOFTFAIL ( 2.5) | R_DKIM_PERMFAIL ( 4.5) | DMARC_POLICY_NA                  ( 0.5) | add_header ( 7.5) |
| R_SPF_SOFTFAIL ( 2.5) | R_DKIM_PERMFAIL ( 4.5) | DMARC_POLICY_SOFTFAIL            ( 1.5) | add_header ( 8.5) |
| R_SPF_FAIL     ( 4.5) | R_DKIM_ALLOW    (  -1) | DMARC_POLICY_ALLOW_WITH_FAILURES (   0) | pass       ( 3.5) |
| R_SPF_FAIL     ( 4.5) | R_DKIM_ALLOW    (  -1) | DMARC_POLICY_NA                  ( 0.5) | greylist   (   4) |
| R_SPF_FAIL     ( 4.5) | R_DKIM_ALLOW    (  -1) | DMARC_POLICY_SOFTFAIL            ( 1.5) | greylist   (   5) |
| R_SPF_FAIL     ( 4.5) | R_DKIM_NA       (   1) | DMARC_POLICY_QUARANTINE          ( 1.5) | add_header (   7) |
| R_SPF_FAIL     ( 4.5) | R_DKIM_NA       (   1) | DMARC_POLICY_REJECT              ( 5.5) | reject     (  11) |
| R_SPF_FAIL     ( 4.5) | R_DKIM_NA       (   1) | DMARC_POLICY_NA                  ( 0.5) | add_header (   6) |
| R_SPF_FAIL     ( 4.5) | R_DKIM_NA       (   1) | DMARC_POLICY_SOFTFAIL            ( 1.5) | add_header (   7) |
| R_SPF_FAIL     ( 4.5) | R_DKIM_TEMPFAIL ( 1.5) | DMARC_POLICY_QUARANTINE          ( 1.5) | add_header ( 7.5) |
| R_SPF_FAIL     ( 4.5) | R_DKIM_TEMPFAIL ( 1.5) | DMARC_POLICY_REJECT              ( 5.5) | reject     (11.5) |
| R_SPF_FAIL     ( 4.5) | R_DKIM_TEMPFAIL ( 1.5) | DMARC_POLICY_NA                  ( 0.5) | add_header ( 6.5) |
| R_SPF_FAIL     ( 4.5) | R_DKIM_TEMPFAIL ( 1.5) | DMARC_POLICY_SOFTFAIL            ( 1.5) | add_header ( 7.5) |
| R_SPF_FAIL     ( 4.5) | R_DKIM_PERMFAIL ( 4.5) | DMARC_POLICY_QUARANTINE          ( 1.5) | add_header (10.5) |
| R_SPF_FAIL     ( 4.5) | R_DKIM_PERMFAIL ( 4.5) | DMARC_POLICY_REJECT              ( 5.5) | reject     (14.5) |
| R_SPF_FAIL     ( 4.5) | R_DKIM_PERMFAIL ( 4.5) | DMARC_POLICY_NA                  ( 0.5) | add_header ( 9.5) |
| R_SPF_FAIL     ( 4.5) | R_DKIM_PERMFAIL ( 4.5) | DMARC_POLICY_SOFTFAIL            ( 1.5) | add_header (10.5) |

### Rspamd Configuration File

Please see [`scores.d/policies_group.conf`](https://github.com/docker-mailserver/docker-mailserver/blob/master/target/rspamd/scores.d/policies_group.conf)

### The Code that Generates All of This

<details>
 <summary>Click me to unveil the Rust code behind the scenes.</summary>

```rust
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
enum MilterActions {
    Reject = 11,
    AddHeader = 6,
    Greylist = 4,
    Pass = 0,
}

impl SPFResult {
    fn weight(&self) -> f32 {
        match self {
            Self::RSpfAllow => -1.0,
            Self::RSpfNa => 1.5,
            Self::RSpfSoftfail => 2.5,
            Self::RSpfFail => 4.5,
        }
    }
}

impl DKIMResult {
    fn weight(&self) -> f32 {
        match self {
            Self::RDkimAllow => -1.0,
            Self::RDkimNa => 1.0,
            Self::RDkimTempfail => 1.5,
            Self::RDkimPermfail => 4.5,
        }
    }
}

impl DMARCResult {
    fn weight(&self) -> f32 {
        match self {
            Self::DmarcPolicyAllow => -1.0,
            Self::DmarcPolicyAllowWithFailures => 0.0,
            Self::DmarcPolicyNa => 0.5,
            Self::DmarcPolicySoftfail => 1.5,
            Self::DmarcPolicyQuarantine => 3.0,
            Self::DmarcPolicyReject => 5.5,
        }
    }
}

impl MilterActions {
    fn into_float(self) -> f32 {
        self as usize as f32
    }

    fn from_combination(combination: Combination) -> (Self, f32) {
        let score = combination.0.weight() + combination.1.weight() + combination.2.weight();
        let action = if score >= Self::Reject.into_float() {
            Self::Reject
        } else if score >= Self::AddHeader.into_float() {
            Self::AddHeader
        } else if score >= Self::Greylist.into_float() {
            Self::Greylist
        } else {
            Self::Pass
        };

        (action, score)
    }
}

impl std::fmt::Display for MilterActions {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        let self_string = match self {
            Self::Reject => "reject",
            Self::AddHeader => "add_header",
            Self::Greylist => "greylist",
            Self::Pass => "pass",
        };
        self_string.fmt(f)
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
enum SPFResult {
    RSpfAllow,
    RSpfNa,
    RSpfSoftfail,
    RSpfFail,
}

impl std::fmt::Display for SPFResult {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        let self_string = match self {
            Self::RSpfAllow => "R_SPF_ALLOW",
            Self::RSpfNa => "R_SPF_NA",
            Self::RSpfSoftfail => "R_SPF_SOFTFAIL",
            Self::RSpfFail => "R_SPF_FAIL",
        };
        self_string.fmt(f)
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
enum DKIMResult {
    RDkimAllow,
    RDkimNa,
    RDkimTempfail,
    RDkimPermfail,
}

impl std::fmt::Display for DKIMResult {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        let self_string = match self {
            Self::RDkimAllow => "R_DKIM_ALLOW",
            Self::RDkimNa => "R_DKIM_NA",
            Self::RDkimTempfail => "R_DKIM_TEMPFAIL",
            Self::RDkimPermfail => "R_DKIM_PERMFAIL",
        };
        self_string.fmt(f)
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
enum DMARCResult {
    DmarcPolicyAllow,
    DmarcPolicyNa,
    DmarcPolicySoftfail,
    DmarcPolicyAllowWithFailures,
    DmarcPolicyQuarantine,
    DmarcPolicyReject,
}

impl std::fmt::Display for DMARCResult {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::DmarcPolicyAllow => "DMARC_POLICY_ALLOW",
            Self::DmarcPolicyNa => "DMARC_POLICY_NA",
            Self::DmarcPolicySoftfail => "DMARC_POLICY_SOFTFAIL",
            Self::DmarcPolicyAllowWithFailures => "DMARC_POLICY_ALLOW_WITH_FAILURES",
            Self::DmarcPolicyQuarantine => "DMARC_POLICY_QUARANTINE",
            Self::DmarcPolicyReject => "DMARC_POLICY_REJECT",
        }
        .fmt(f)
        // self_string.fmt(f)
    }
}

type Combination = (SPFResult, DKIMResult, DMARCResult);

fn produce_combinations() -> Vec<Combination> {
    let mut combinations = vec![];

    use DKIMResult::*;
    use DMARCResult::*;
    use SPFResult::*;

    for spf in [RSpfAllow, RSpfNa, RSpfSoftfail, RSpfFail] {
        for dkim in [RDkimAllow, RDkimNa, RDkimTempfail, RDkimPermfail] {
            // SPF and DKIM succeeded
            if spf == RSpfAllow && dkim == RDkimAllow {
                combinations.push((spf, dkim, DmarcPolicyAllow));

            // SPF failed
            } else if spf == RSpfNa || spf == RSpfSoftfail || spf == RSpfFail {
                if dkim == RDkimAllow {
                    combinations.push((spf, dkim, DmarcPolicyAllowWithFailures));
                } else {
                    combinations.push((spf, dkim, DmarcPolicyQuarantine));
                    combinations.push((spf, dkim, DmarcPolicyReject));
                }

            // DKIM failed
            } else if dkim == RDkimNa || dkim == RDkimTempfail || dkim == RDkimPermfail {
                if spf == RSpfAllow {
                    combinations.push((spf, dkim, DmarcPolicyAllowWithFailures));
                } else {
                    combinations.push((spf, dkim, DmarcPolicyQuarantine));
                    combinations.push((spf, dkim, DmarcPolicyReject));
                }
            } else {
                panic!("Leftover combination: {} {}", spf, dkim);
            }

            // these can always happen
            combinations.push((spf, dkim, DmarcPolicyNa));
            combinations.push((spf, dkim, DmarcPolicySoftfail));
        }
    }

    combinations
}

fn print_row(combination: Combination) {
    let (action, score) = MilterActions::from_combination(combination);
    println!(
        "| {:14} ({:>4}) | {:15} ({:>4}) | {:32} ({:>4}) | {:10} ({:>4}) |",
        combination.0,
        combination.0.weight(),
        combination.1,
        combination.1.weight(),
        combination.2,
        combination.2.weight(),
        action,
        score
    );
}

fn main() {
    println!(
        "| {:14}        | {:15}        | {:32}        | {:10}        |",
        "SPF", "DKIM", "DMARC", "Action"
    );
    println!("| :-------------------- | :--------------------- | :-------------------------------------- | :---------------- |");

    for combination in produce_combinations() {
        print_row(combination);
    }
}

#[test]
fn combinations_produce_correct_milter_action() {
    use DKIMResult::*;
    use DMARCResult::*;
    use SPFResult::*;

    let combinations = produce_combinations();

    macro_rules! is_equal {
        ($combination:expr, $milter_action:expr) => {
            assert!(combinations.contains(&$combination));
            assert!(MilterActions::from_combination($combination).0 == $milter_action);
        };
    }

    is_equal!(
        (RSpfAllow, RDkimAllow, DmarcPolicyAllow),
        MilterActions::Pass
    );
    is_equal!(
        (RSpfAllow, RDkimNa, DmarcPolicyAllowWithFailures),
        MilterActions::Pass
    );
    is_equal!(
        (RSpfAllow, RDkimTempfail, DmarcPolicyAllowWithFailures),
        MilterActions::Pass
    );
    is_equal!(
        (RSpfAllow, RDkimPermfail, DmarcPolicyAllowWithFailures),
        MilterActions::Pass
    );
    is_equal!(
        (RSpfAllow, RDkimPermfail, DmarcPolicyAllowWithFailures),
        MilterActions::Pass
    );
    is_equal!(
        (RSpfAllow, RDkimPermfail, DmarcPolicyAllowWithFailures),
        MilterActions::Pass
    );

    is_equal!(
        (RSpfNa, RDkimPermfail, DmarcPolicyReject),
        MilterActions::Reject
    );
    is_equal!(
        (RSpfFail, RDkimNa, DmarcPolicyReject),
        MilterActions::Reject
    );
    is_equal!(
        (RSpfFail, RDkimTempfail, DmarcPolicyReject),
        MilterActions::Reject
    );
    is_equal!(
        (RSpfFail, RDkimPermfail, DmarcPolicyReject),
        MilterActions::Reject
    );
}

#[test]
fn certain_combinations_must_not_exist() {
    use DKIMResult::*;
    use DMARCResult::*;
    use SPFResult::*;

    let combinations = produce_combinations();

    macro_rules! must_not_exist {
        ($combination:expr) => {
            assert!(!combinations.contains(&$combination));
        };
    }

    must_not_exist!((RSpfAllow, RDkimAllow, DmarcPolicyReject));
    must_not_exist!((RSpfNa, RDkimAllow, DmarcPolicyReject));
    must_not_exist!((RSpfSoftfail, RDkimAllow, DmarcPolicyReject));
    must_not_exist!((RSpfFail, RDkimAllow, DmarcPolicyReject));
    must_not_exist!((RSpfAllow, RDkimNa, DmarcPolicyReject));
    must_not_exist!((RSpfAllow, RDkimTempfail, DmarcPolicyReject));
    must_not_exist!((RSpfAllow, RDkimTempfail, DmarcPolicyReject));

    must_not_exist!((RSpfAllow, RDkimAllow, DmarcPolicyQuarantine));
    must_not_exist!((RSpfNa, RDkimAllow, DmarcPolicyQuarantine));
    must_not_exist!((RSpfSoftfail, RDkimAllow, DmarcPolicyQuarantine));
    must_not_exist!((RSpfFail, RDkimAllow, DmarcPolicyQuarantine));
    must_not_exist!((RSpfAllow, RDkimNa, DmarcPolicyQuarantine));
    must_not_exist!((RSpfAllow, RDkimTempfail, DmarcPolicyQuarantine));
    must_not_exist!((RSpfAllow, RDkimTempfail, DmarcPolicyQuarantine));
}
```

</details>

You can copy this code and run it to print the table seen above. When you use Cargo, you may also use `cargo test` to check whether changes still conform to specifications.

### You Think There is Something Wrong Here?

In case you think a value should be changed, please copy the Rust code, apply your changes to the top, and then test the result. You may add additional tests to `combinations_produce_correct_milter_action` as well. Please justify why you disagree with the current setup.

**Comment by ap-wtioit** [comment]
finally i had some time to look at this.

I think the soft-fail and hard-fail columns for DKIM should be named TEMPFAIL and HARDFAIL (i could only find the term softfail in [SPF RFC7208](https://datatracker.ietf.org/doc/html/rfc7208#section-2.6.5) not in [DKIM RFC6376](https://datatracker.ietf.org/doc/html/rfc6376))

Work in Progress (will be continued):

For the following
| SPF       | DKIM      | DMARC      | Action            |
| :-------- | :-------- | :--------- | :---------------- |
| Pass      | Soft-Fail | None       | greylist          |
| Pass      | Soft-Fail | Quarantine | add_header ?      |
| Pass      | Soft-Fail | Reject     | reject            |

As noted in [6.6.2](https://www.rfc-editor.org/rfc/rfc7489#section-6.6.2).  Determine Handling Policy
> DMARC evaluation can only yield a "pass" result after one of the
   underlying authentication mechanisms passes for an aligned
   identifier.  If neither passes and one or both of them fail due to a
   temporary error, the Receiver evaluating the message is unable to
   conclude that the DMARC mechanism had a permanent failure; they
   therefore cannot apply the advertised DMARC policy.  When otherwise
   appropriate, Receivers MAY send feedback reports regarding temporary
   errors.

I would argue a DKIM soft-fail (assuming you meant TEMPFAIL from DKIM, so a temporary DNS error) with SPF pass would mean DMARC pass and therefore no action should be taken (apart from maybe greylisting)

**Comment by georglauterbach** [comment]
Thanks @ap-wtioit for your response! :)

> Can we send mails to quarantine with rspamd? When not using rspamd (we are not using rspamd) mails end up in quarantined queue and can be managed with postqueue/postsuper. I would say they should go to quarantine.

It looks like there is: <https://rspamd.com/doc/faq.html#what-are-rspamd-actions>. I have just discovered that there are few more actions that I didn't know of myself. Hence, we can add `quarantine` to the list of available actions.

> I would prefer to send this to quarantine. But i see the issue with maybe not everyone monitoring those quarantine queues in DMS/postqueue.

This is actually a real concern IMO. Hence, we should discuss whether we want to stick with `reject` instead of `quarantine`... I may be able to add a toggle `RSPAMD_USE_QUARANTINE_INSTEAD_OF_REJECT` to apply a configuration in which we do not reject but transfer to quarantine instead.

---

I updated the table and tested around with the Rspamd symbols. Matching all actions was impossible... so I settled for a bit more conservative approach and took less restrictive actions. This may not be 100% compliant with the RFC, but **remember** that Rspamd adds more symbols than just those for SPF, DKIM and DMARC. Hence, the score can decrease or increase also based on other factors. The following is a best-effort approach for matching rules: we try not to overshoot, and being below the threshold of an action is okay as long as it is not too much (-1 to be precise)

```md
| SPF                 | DKIM                 | DMARC                        | Action            |
| :------------------ | :------------------- | :--------------------------- | :---------------- |
| R_SPF_ALLOW      -1 | R_DKIM_ALLOW      -1 | DMARC_NA                   1 | pass              |
| R_SPF_ALLOW      -1 | R_DKIM_ALLOW      -1 | DMARC_POLICY_QUARANTINE    1 | pass              |
| R_SPF_ALLOW      -1 | R_DKIM_ALLOW      -1 | DMARC_POLICY_REJECT        2 | pass              |
| R_SPF_ALLOW      -1 | R_DKIM_NA          0 | DMARC_NA                   1 | pass              |
| R_SPF_ALLOW      -1 | R_DKIM_NA          0 | DMARC_POLICY_QUARANTINE    1 | pass              |
| R_SPF_ALLOW      -1 | R_DKIM_NA          0 | DMARC_POLICY_REJECT        2 | pass              |
| R_SPF_ALLOW      -1 | R_DKIM_TEMPFAIL  1.5 | DMARC_NA                   1 | pass              |
| R_SPF_ALLOW      -1 | R_DKIM_TEMPFAIL  1.5 | DMARC_POLICY_QUARANTINE    1 | pass              |
| R_SPF_ALLOW      -1 | R_DKIM_TEMPFAIL  1.5 | DMARC_POLICY_REJECT        2 | pass              |
| R_SPF_ALLOW      -1 | R_DKIM_PERMFAIL  4.5 | DMARC_NA                   1 | greylist          |
| R_SPF_ALLOW      -1 | R_DKIM_PERMFAIL  4.5 | DMARC_POLICY_QUARANTINE    1 | greylist          |
| R_SPF_ALLOW      -1 | R_DKIM_PERMFAIL  4.5 | DMARC_POLICY_REJECT        2 | greylist          |
| R_SPF_NA        1.5 | R_DKIM_ALLOW      -1 | DMARC_NA                   1 | pass              |
| R_SPF_NA        1.5 | R_DKIM_ALLOW      -1 | DMARC_POLICY_QUARANTINE    1 | pass              |
| R_SPF_NA        1.5 | R_DKIM_ALLOW      -1 | DMARC_POLICY_REJECT        2 | pass              |
| R_SPF_NA        1.5 | R_DKIM_NA          1 | DMARC_NA                   1 | greylist          |
| R_SPF_NA        1.5 | R_DKIM_NA          1 | DMARC_POLICY_QUARANTINE    1 | greylist          |
| R_SPF_NA        1.5 | R_DKIM_NA          1 | DMARC_POLICY_REJECT        2 | greylist          |
| R_SPF_NA        1.5 | R_DKIM_TEMPFAIL  1.5 | DMARC_NA                   1 | greylist          |
| R_SPF_NA        1.5 | R_DKIM_TEMPFAIL  1.5 | DMARC_POLICY_QUARANTINE    1 | greylist          |
| R_SPF_NA        1.5 | R_DKIM_TEMPFAIL  1.5 | DMARC_POLICY_REJECT        2 | greylist          |
| R_SPF_NA        1.5 | R_DKIM_PERMFAIL  4.5 | DMARC_NA                   1 | rewrite_subject   |
| R_SPF_NA        1.5 | R_DKIM_PERMFAIL  4.5 | DMARC_POLICY_QUARANTINE    1 | rewrite_subject   |
| R_SPF_NA        1.5 | R_DKIM_PERMFAIL  4.5 | DMARC_POLICY_REJECT        2 | rewrite_subject   |
| R_SPF_SOFTFAIL  2.5 | R_DKIM_ALLOW      -1 | DMARC_NA                   1 | pass              |
| R_SPF_SOFTFAIL  2.5 | R_DKIM_ALLOW      -1 | DMARC_POLICY_QUARANTINE    1 | pass              |
| R_SPF_SOFTFAIL  2.5 | R_DKIM_ALLOW      -1 | DMARC_POLICY_REJECT        2 | pass              |
| R_SPF_SOFTFAIL  2.5 | R_DKIM_NA          1 | DMARC_NA                   1 | greylist          |
| R_SPF_SOFTFAIL  2.5 | R_DKIM_NA          1 | DMARC_POLICY_QUARANTINE    1 | greylist          |
| R_SPF_SOFTFAIL  2.5 | R_DKIM_NA          1 | DMARC_POLICY_REJECT        2 | add_header        |
| R_SPF_SOFTFAIL  2.5 | R_DKIM_TEMPFAIL  1.5 | DMARC_NA                   1 | greylist          |
| R_SPF_SOFTFAIL  2.5 | R_DKIM_TEMPFAIL  1.5 | DMARC_POLICY_QUARANTINE    1 | add_header        |
| R_SPF_SOFTFAIL  2.5 | R_DKIM_TEMPFAIL  1.5 | DMARC_POLICY_REJECT        2 | add_header        |
| R_SPF_SOFTFAIL  2.5 | R_DKIM_PERMFAIL  4.5 | DMARC_NA                   1 | rewrite_subject   |
| R_SPF_SOFTFAIL  2.5 | R_DKIM_PERMFAIL  4.5 | DMARC_POLICY_QUARANTINE    1 | rewrite_subject   |
| R_SPF_SOFTFAIL  2.5 | R_DKIM_PERMFAIL  4.5 | DMARC_POLICY_REJECT        2 | rewrite_subject   |
| R_SPF_FAIL      4.5 | R_DKIM_ALLOW      -1 | DMARC_NA                   1 | greylist          |
| R_SPF_FAIL      4.5 | R_DKIM_ALLOW      -1 | DMARC_POLICY_QUARANTINE    1 | greylist          |
| R_SPF_FAIL      4.5 | R_DKIM_ALLOW      -1 | DMARC_POLICY_REJECT        2 | greylist          |
| R_SPF_FAIL      4.5 | R_DKIM_NA          1 | DMARC_NA                   1 | add_header        |
| R_SPF_FAIL      4.5 | R_DKIM_NA          1 | DMARC_POLICY_QUARANTINE    1 | add_header        |
| R_SPF_FAIL      4.5 | R_DKIM_NA          1 | DMARC_POLICY_REJECT        2 | rewrite_subject   |
| R_SPF_FAIL      4.5 | R_DKIM_TEMPFAIL  1.5 | DMARC_NA                   1 | add_header        |
| R_SPF_FAIL      4.5 | R_DKIM_TEMPFAIL  1.5 | DMARC_POLICY_QUARANTINE    1 | add_header        |
| R_SPF_FAIL      4.5 | R_DKIM_TEMPFAIL  1.5 | DMARC_POLICY_REJECT        2 | rewrite_subject   |
| R_SPF_FAIL      4.5 | R_DKIM_PERMFAIL  4.5 | DMARC_NA                   1 | reject            |
| R_SPF_FAIL      4.5 | R_DKIM_PERMFAIL  4.5 | DMARC_POLICY_QUARANTINE    1 | reject            |
| R_SPF_FAIL      4.5 | R_DKIM_PERMFAIL  4.5 | DMARC_POLICY_REJECT        2 | reject            |

```

where the actions' scores are

```ini
greylist = 4
add_header = 6
rewrite_subject = 7
reject = 11
```

Depending on other symbols, the score can still change! The score with the SPF, DKIM and DMARC symbols from above is now not too high (we don't want to reject legitimate e-mails), but accurate enough to be within the region of that the RFC demands. Spam mails are likely to contain other issues that Rspamd _should_ catch, so increasing the score should be fine I guess in this case.

---

PS: I updated some of the `greylist` actions to `pass` and some of the `greylist` actions became `add_header`, where I saw fit.

**Comment by georglauterbach** [comment]
I will now go ahead and test this config on my machine.

**Comment by georglauterbach** [comment]
It seems to be working quite nicely; I do not get a lot of spam though, so my testing may be very limited TBH. If someone tries the configuration above and reports back, I'd be very happy.

In the meantime, I have created a draft PR for the changes, which is currently planned for v14.0.0.

**Comment by Nebucatnetzer** [comment]
I get plenty of span but it’s not clear to me how to test this.
Where do I have to put the files and execute them?
In addition do we maybe have to store the table in symbols.ini instead of symbols.txt?

**Comment by georglauterbach** [comment]
Just save the score configuration (from above) as `/etc/rspamd/scores.d/policies_group.conf`. This should suffice.

**Comment by 2GetApp** [comment]
I am at ghcr.io/docker-mailserver/docker-mailserver:latest now and I found some problems.
The weight of R_DKIM_NA symbol is assigned to 0 in /etc/rspamd/scores.d/policies_group.conf (https://github.com/docker-mailserver/docker-mailserver/blob/master/target/rspamd/scores.d/policies_group.conf#L53), but the table above shows there are two values for R_DKIM_NA (0 or 1), I am not very familiar with rspamd configuration. Is the weight the same as the score or is it the multiplier?

And in the table, I think this line is also problematic:
`| R_SPF_FAIL      4.5 | R_DKIM_NA          1 | DMARC_POLICY_REJECT        2 | rewrite_subject   |`
If a mail fails SPF check and does not contain a valid DKIM signature, and DMARC policy suggests reject, it should be rejected.

**Comment by georglauterbach** [comment]
> The weight of R_DKIM_NA symbol is assigned to 0 (https://github.com/docker-mailserver/docker-mailserver/blob/v13.3.1/target/rspamd/scores.d/policies_group.conf#L53) but the table above shows there are two values for R_DKIM_NA (0 or 1), I am not very familiar with rspamd configuration. Is the weight the same as the score or is it the multiplier?

This seems to be a mistake in the configuration on our side indeed; I just confirmed that the default configuration ships the wrong value. I will provide a PR to fix this.

> And in the table, I think this line is also problematic: `| R_SPF_FAIL 4.5 | R_DKIM_NA 1 | DMARC_POLICY_REJECT 2 | rewrite_subject |` If a mail fails SPF check and does not contain a valid DKIM signature, and DMARC policy suggests reject, shouldn't it be rejected?

You can try to increase the value of `DMARC_POLICY_REJECT` [yourself](https://docker-mailserver.github.io/docker-mailserver/latest/faq/#how-to-adjust-settings-with-the-user-patchessh-script) and see whether this works for you. Generally speaking, you are right. I will try to take a look at the configuration again.

> As for the other cases, if a mail passes SPF and DKIM checks, but the SPF/DKIM domain does not align with the From header, it will fail DMARC alignment test. In that case, how will the mail be handled according to RFC7489?

Can DKIM pass in Rspamd if it is not aligned with `From`? I do not think Rspamd has a dedicated symbol - DKIM is simply not aligned then, which results in `R_DKIM_TEMPFAIL` if there was no error in DNS.
