### ISSUE TITLE
MIME-Version header rewritten incorrectly

### ISSUE THREAD

**Issue by soeftware** [docker-mailserver/docker-mailserver#3694]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

Mailserver incorrectly rewrites MIME-Version header to Mime-Version (wrong capitalization). This happens on all outgoing mails.

Sample log line:
```
Aug 31 05:56:46 mail postfix/sender-cleanup/cleanup[305448]: EFC7890449D: replace: header MIME-Version: 1.0 from {redacted}; from={redacted} to={redacted} proto=ESMTP helo=<[127.0.0.1]>: Mime-Version: 1.0
```

### 👟 Reproduction Steps

Send a mail via SMTP

### 🐋 DMS Version

eb2abda

### 💻 Operating System and Architecture

Ubuntu focal

**Comment by georglauterbach** [comment]
This was corrected in https://github.com/docker-mailserver/docker-mailserver/commit/66f3bbc062c6b3f6a9b0d20408aaced566825a7b and subsequently landed in DMS with [v12.0.0](https://github.com/docker-mailserver/docker-mailserver/releases/tag/v12.0.0) on April 10 2023.
