### ISSUE TITLE
bug report: opendkim service doesn't start on k8s

### ISSUE THREAD

**Issue by jf-gl** [docker-mailserver/docker-mailserver#3698]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

Opendkim service fail start on k8s with the message : Starting OpenDKIM: install: invalid user ''
Any idea ?

Thanks.

### 🐋 DMS Version

v13.0.0

### 💻 Operating System and Architecture

Kubernetes v1.26.7 linux/amd64

### 📜 Relevant log output

```Text
Starting OpenDKIM: install: invalid user ''
```

**Comment by georglauterbach** [comment]
I didn't have this issue  back when I used OpenDKIM. Please elaborate on the setup and share more log/General information.

**Comment by jf-gl** [comment]
Thanks for your reply.
Here in attached the log, deployment and configuration files.

[logs.txt](https://github.com/docker-mailserver/docker-mailserver/files/13702052/logs.txt)
[manager-mail-environment-configmap.yaml.txt](https://github.com/docker-mailserver/docker-mailserver/files/13702053/manager-mail-environment-configmap.yaml.txt)
[manager-mail-deployment.yaml.txt](https://github.com/docker-mailserver/docker-mailserver/files/13702054/manager-mail-deployment.yaml.txt)

**Comment by georglauterbach** [comment]
What's in your `/etc/opendkim.conf`?

**Comment by jf-gl** [comment]
See opendkim.conf in attached file.

[opendkim.conf.txt](https://github.com/docker-mailserver/docker-mailserver/files/13716280/opendkim.conf.txt)

**Comment by georglauterbach** [comment]
I have got to admit, I don't know the cause as of now. I'd start by re-enabling the tmp-dir, i.e.

```yaml
            # other
#            - name: tmp-files
#              mountPath: /tmp
#              readOnly: false
```

The log you posted does not contain the error you posted though, which makes debugging difficult.

**Comment by adameus03** [comment]
@jf-gl Have you resolved it by any chance?

**Comment by polarathene** [comment]
@adameus03 consider [trying our rspamd support instead](https://github.com/docker-mailserver/docker-mailserver/issues/4202#issuecomment-2381026609)?

**Comment by jf-gl** [comment]
> @jf-gl Have you resolved it by any chance?

Hi Adameus,

No, the project was put on hold.
Have you got the same issue ?

**Comment by georglauterbach** [comment]
> After some time I managed to get opendkim signing the outgoing emails. `Starting OpenDKIM: install: invalid user ''` mentioned in this issue was a result of executing `systemctl start opendkim` inside the container in my case (though it probably could have a different origin in the OP's case). In the FAQ section of the project I found that `hypervisorctl` should be used instead for managing the services inside the container. With some additional issues involving the different `/tmp/docker-mailserver/opendkim/...` and `/etc/opendkim/...` paths and their use in the `/etc/opendkim.conf` file and adding opendkim keys as additional volume to the container so that opendkim doesn't complain about /tmp directory permissions, I managed to get the DKIM signing to work :)

Could you please point me toward the documentation that recommends using `hypervirsorctl`? It should be `supervisorctl`.

**Comment by adameus03** [comment]
> > After some time I managed to get opendkim signing the outgoing emails. `Starting OpenDKIM: install: invalid user ''` mentioned in this issue was a result of executing `systemctl start opendkim` inside the container in my case (though it probably could have a different origin in the OP's case). In the FAQ section of the project I found that `hypervisorctl` should be used instead for managing the services inside the container. With some additional issues involving the different `/tmp/docker-mailserver/opendkim/...` and `/etc/opendkim/...` paths and their use in the `/etc/opendkim.conf` file and adding opendkim keys as additional volume to the container so that opendkim doesn't complain about /tmp directory permissions, I managed to get the DKIM signing to work :)
> 
> Could you please point me toward the documentation that recommends using `hypervirsorctl`? It should be `supervisorctl`.

Of course I meant `supervisorctl`, sorry for that
