### ISSUE TITLE
other: How to add wildcard mailbox users?

### ISSUE THREAD

**Issue by Okdesk** [docker-mailserver/docker-mailserver#3699]
### Subject

I would like to configure a not documented mail server use case

### Description

Not seeing this documented officially: how do I add wildcard mailbox users?

Say I have a domain mydomain.com, and I need to receive **all** communications directed to *@mydomain.com, e.g., support@mydomain.com, jane@mydomain.com, joe@mydomain.com, etc.

How do I go about this?

**Comment by dweipert-3138720606** [comment]
I think what you want is a catch-all alias.
Here's the documentation for that: https://docker-mailserver.github.io/docker-mailserver/latest/faq/#how-can-i-configure-a-catch-all

**Comment by georglauterbach** [comment]
@dweipert-3138720606  is absolutely correct.

I'm closing this now. If you have further troubles, continue this thread.
