### ISSUE TITLE
[TODO]: Tests(Fail2Ban) - Make failed login test case reliable

### ISSUE THREAD

**Issue by polarathene** [docker-mailserver/docker-mailserver#3713]
### Description

This test case is quite flakey, and fails on PRs that have nothing to do with it.

```
not ok 52 [Fail2Ban] ban ip on multiple failed login in 132455ms
# (from function `assert_success' in file test/test_helper/bats-assert/src/assert_success.bash, line 42,
#  from function `_send_email' in file test/helper/sending.bash, line 33,
#  in test file test/tests/parallel/set1/spam_virus/fail2ban.bats, line 77)
#   `CONTAINER_NAME=${CONTAINER2_NAME} _send_email 'auth/smtp-auth-login-wrong' "${CONTAINER1_IP} 465"' failed
#
# -- command failed --
# status : 1
# output :
# --
#
```

Seems like it's something to do with `_send_email` failing?

https://github.com/docker-mailserver/docker-mailserver/blob/ee87291225f55feb4a4c96b2383c55827db54736/test/tests/parallel/set1/spam_virus/fail2ban.bats#L77

https://github.com/docker-mailserver/docker-mailserver/blob/ee87291225f55feb4a4c96b2383c55827db54736/test/helper/sending.bash#L22-L34

Specifically this line:

https://github.com/docker-mailserver/docker-mailserver/blob/ee87291225f55feb4a4c96b2383c55827db54736/test/helper/sending.bash#L32

---

Chances are it's been banned before the test case can check (_expects to first succeed with `_send_email` twice?_), then:

https://github.com/docker-mailserver/docker-mailserver/blob/ee87291225f55feb4a4c96b2383c55827db54736/test/tests/parallel/set1/spam_virus/fail2ban.bats#L79-L83

Generally we expect `_send_mail` to be successful when it's used, but this is a situation where it's non-deterministic, sometimes failing.

**Comment by georglauterbach** [comment]
Closing this as https://github.com/docker-mailserver/docker-mailserver/pull/3732 has been merged. Please re-open in case this issue still persists.
