### ISSUE TITLE
feature request: Allow SMTPUTF8 to be enabled

### ISSUE THREAD

**Issue by williamdes** [docker-mailserver/docker-mailserver#3748]
### Context

Action: failed
Status: 5.6.7
Diagnostic-Code: X-Postfix; SMTPUTF8 is required, but was not offered by host
    xxx[xxxx]

### Description

I received this in a daemon email. Is there a reason it is disabled ?
https://github.com/docker-mailserver/docker-mailserver/blob/8f391e4d5aa6449fcf8a4762df23cba98c52bc4c/target/scripts/startup/setup.d/postfix.sh#L23

https://www.postfix.org/SMTPUTF8_README.html

### Alternatives

-

### Applicable Users

-

### Are you going to implement it?

No, and I understand that it is highly likely no one will implement it. Furthermore, I understand that this issue will likely become stale and will be closed.

### What are you going to contribute?

no

**Comment by polarathene** [comment]
> I received this in a daemon email. Is there a reason it is disabled ?

Yes, Dovecot does not support it. For more information see https://github.com/docker-mailserver/docker-mailserver/pull/3750

You may enable it via `postfix-main.cf` if you do not use Dovecot.
