### ISSUE TITLE
bug report: /usr/bin/jaq - binary format error (image uses x86 binary for arm installation)

### ISSUE THREAD

**Issue by IvanI3** [docker-mailserver/docker-mailserver#3764]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

DMS installed in k8s with ARM architecture, but /usr/bin/jaq binary is in x86 binary format

### 👟 Reproduction Steps

# cat /var/log/supervisor/update-check.log:
(23) Failed writing body
[ WARNING ]  2024-01-09 10:57:56  Update check failed

# file /usr/bin/jaq
/usr/bin/jaq: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), statically linked, no section header

### 🐋 DMS Version

v13.2.0

### 💻 Operating System and Architecture

Kubernetes 1.28, Debian GNU/Linux 11 (bullseye), aarch64

**Comment by polarathene** [comment]
This was closed from merging the suggested fix, but if you could verify `:edge` provides the expected binary now (_via `file` like was shared above_) that'd be appreciated 👍
