### ISSUE TITLE
bug report: existing rspamd DKIM private key files are owned by dovenull instead of _rspamd user

### ISSUE THREAD

**Issue by jasperw1996** [docker-mailserver/docker-mailserver#3800]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

After updating DMS from 13.2.0 to 13.3.0 I get a warning at startup that the DKIM private key files would not have the correct permissions. 
- There was a similar issue two months ago: https://github.com/docker-mailserver/docker-mailserver/issues/3665
- This time, however, the check seems to work correctly and the private key files are actually owned by the wrong group/user (`dovenull`).

The bug seems to be related with https://github.com/docker-mailserver/docker-mailserver/commit/e3331b0f44b1d9c1c513389ad5b6f3b09e51dc16

If we look at `/etc/passwd` in DMS v13.3.0, we notice that:
- the new user `_mta-sts` has UID 109 and GID 111, which was used by `amavis` before.
- `amavis` has `110:112` which was used by `dovecot` before.
- `dovecot` has `111:113` which was used by `dovenull` before.
- And finally, `dovenull` is using `112:114` – the UID/GID pair that belonged to `rspamd` in DMS 13.2.0. Apparently, that's why user `dovenull` now has control over our DKIM private files.

```Text
root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
games:x:5:60:games:/usr/games:/usr/sbin/nologin
man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
backup:x:34:34:backup:/var/backups:/usr/sbin/nologin
list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
irc:x:39:39:ircd:/run/ircd:/usr/sbin/nologin
gnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/usr/sbin/nologin
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
_apt:x:100:65534::/nonexistent:/usr/sbin/nologin
clamav:x:200:200::/var/lib/clamav:/usr/sbin/nologin
postfix:x:101:102::/var/spool/postfix:/usr/sbin/nologin
fetchmail:x:102:65534::/var/lib/fetchmail:/bin/false
postsrsd:x:103:104::/var/lib/postsrsd:/usr/sbin/nologin
opendkim:x:104:106::/run/opendkim:/usr/sbin/nologin
opendmarc:x:105:107::/run/opendmarc:/usr/sbin/nologin
postgrey:x:106:108::/var/lib/postgrey:/usr/sbin/nologin
policyd-spf:x:107:109::/nonexistent:/usr/sbin/nologin
debian-spamd:x:108:110::/var/lib/spamassassin:/usr/sbin/nologin
_mta-sts:x:109:111::/var/lib/mta-sts/:/usr/sbin/nologin
amavis:x:110:112:AMaViS system user,,,:/var/lib/amavis:/bin/sh
dovecot:x:111:113:Dovecot mail server,,,:/usr/lib/dovecot:/usr/sbin/nologin
dovenull:x:112:114:Dovecot login user,,,:/nonexistent:/usr/sbin/nologin
_rspamd:x:113:115:rspamd spam filtering system,,,:/var/lib/rspamd:/usr/sbin/nologin
redis:x:114:116::/var/lib/redis:/usr/sbin/nologin
syslog:x:115:65534::/home/syslog:/usr/sbin/nologin
docker:x:5000:5000::/home/docker:/bin/bash
```

Changing permissions manually seems to fix the problem by running:

```bash
docker exec -ti mailserver sh -c 'chown _rspamd:_rspamd /tmp/docker-mailserver/rspamd/dkim \
  && chown _rspamd:_rspamd /tmp/docker-mailserver/rspamd/dkim/*.private.txt'`
```

Adding the chown command to the Rspamd startup script should fix this issue without requiring manual intervention. But it would break backward compatibility, too. Maybe there is an opportunity to set `_mta-sts`'s UID/GID to a fixed (higher) value so that `amavis`, `dovecot`, `dovenull` and `_rspamd` can keep their "original" (G)UIDs?

(Feel free to correct me – it's my first bug report and I have to admit that I only understand half of what I write here :D )

### 👟 Reproduction Steps

1. Generate DKIM keys with DMS <13.3.0 (Rspamd enabled)
2. Update DMS to 13.3.0 and start it
3. Check container logs – and verify wrong permissions with `docker exec -ti mailserver ls -la /tmp/docker-mailserver/rspamd/dkim`

```Text
drwxr-xr-x 2 dovenull dovenull 4096 Jan 21 16:05 .
drwxr-xr-x 4 root    root    4096 Jan 21 16:05 ..
-rw------- 1 dovenull dovenull 1675 Jan 21 16:05 rsa-2048-mail-example.com.private.txt
-rw-r--r-- 1 root    root     411 Jan 21 16:05 rsa-2048-mail-example.com.public.dns.txt
-rw-r--r-- 1 root    root     451 Jan 21 16:05 rsa-2048-mail-example.com.public.txt
```

### 🐋 DMS Version

v13.3.0

### 💻 Operating System and Architecture

Fedora CoreOS 39 x86_64 (running Podman – but also tested with Docker on Debian x86_64)

### 📜 Relevant log output

```Text
[ WARNING ]  (Rspamd setup) Rspamd DKIM private key file '/tmp/docker-mailserver/rspamd/dkim/rsa-2048-mail-example.com.private.txt' does not appear to have correct permissions/ownership for Rspamd to use it
```

**Comment by polarathene** [comment]
Normally this is an issue we [resolve at startup for the `mail-state` volume](https://github.com/docker-mailserver/docker-mailserver/blob/3cbcdb2d6517b6c61818afb49c0eb58ee82b6202/target/scripts/startup/setup.d/mail_state.sh#L79-L84) as it's a known problem when packages are added/removed which can implicitly introduce new UID/GIDs which can shuffle the existing ones.

Thanks for spotting this and the detailed report, that's very much appreciated ❤️ 

We'll need something similar to our `mail-state` fix script for the config volume too then since that's where these keys are presently being stored. Although in this case it shouldn't matter, AFAIK they're meant to be copied to an internal location and permissions should be corrected for that instead where it matters.

Rspamd is @georglauterbach area so he'd know where to look regarding this and where it's most appropriate to fix.

**Comment by Codelica** [comment]
> Maybe there is an opportunity to set _mta-sts's UID/GID to a fixed (higher) value so that amavis, dovecot, dovenull and _rspamd can keep their "original" (G)UIDs?

That would be the best way to go IMO, as there is potentially more involved that just DKIM keys.  For example I have some customer local maps.

**Comment by polarathene** [comment]
> For example I have some custom local maps

Can you provide more context?

This type of shuffling of UID/GID can happen implicitly and not always easy to catch. I suppose we could create all users/groups we know about prior to installing packages, it was something I investigated a while back.

There's rarely a need for this in the config volume, and with internal usage we'd typically manage those permissions / ownership corrections ourselves.

I can see how that'd be an issue if you're adding custom files directly to a service rather than leveraging our config volume support (_which sometimes is lacking support for certain config additions / changes_), but that's also a common support issue where configs we expect to have control over are modified then the user updates DMS to a new release and due to their older config replacement which lacks a change DMS expects introduces some breakage/bug for them.

**Comment by georglauterbach** [comment]
Thanks for the detailed report! This is indeed hard to catch in a PR review..

This warrants 13.3.1 for sure! The fix proposed by @polarathene seemd valid. I don't know exactly when I can implement it though, may take a bit of time.

**Comment by bjoerns1983** [comment]
Stumbled upon the same problem updating vom 13.2. to 13.3 today.
Thanks for the permission fix. Is this permanent?

**Comment by jasperw1996** [comment]
> Two things we need to clarify first, though: what's the better fix? Setting the UID/GID oder using `chown`. @jasperw1996 mentioned a break in backwards compatibility; can you elaborate please?:)
Yes :) If we just chown it and then go back to DMS v13.2.0, we might have the same permission problem there – because then it's probably redis (UID 113 and GID 115) who would be in control of our key files. 
On the other hand, settings the (G)UIDs would require manual intervention for everybody who already applied the "quickfix" mentioned before (chown via docker exec). I would personally prefer this approach though :) It would at least prevent any kind of "permission carousel" in the future :D

**Comment by jasperw1996** [comment]
> Stumbled upon the same problem updating vom 13.2. to 13.3 today. Thanks for the permission fix. Is this permanent?

It depends on the solution the maintainers choose, I think :)
If they decide to set the UID/GUID back to 112:114, you might need to run this again after updating to v13.3.1.

**Comment by Codelica** [comment]
@polarathene re: 
>> For example I have some custom local maps

> Can you provide more context?

Sorry for the late reply here, life got complicated yesterday.  As far as my use for a couple custon local maps in RSPAMd, keep in mind I'm definitely still new to the project, so I could easly be doing this the *wrong way*. ;)

Basically I have `/tmp/docker-mailserver/` bind mounted to a local directory for config, in which I have `rspamd/local.d/multimap.conf` which adds a couple local domain-based maps (for whitelist and blacklist overrides) stored in `rspamd/local-maps/LOCAL_WL_FROM_DOMAIN.map` and `rspamd/local-maps/LOCAL_BL_FROM_DOMAIN.map`. In doing so I can quickly edit those lists via the RSPAMd Web UI "configuration" page.  My `rspamd/local-maps` directory and the maps inside it are `_rspamd:_rspamd` owned, but I don't remember off-hand if I set that to allow editing or if it was the result of the RSPAMd Web UI being used for edits.

**Comment by polarathene** [comment]
If you're using the `/tmp/docker-mailserver/` user config location with supported directories/folders we provide and the user/group is predictable for that content, we can definitely correct ownership there, but my preference is that we do so via an internal copy (_which rspamd support does for some of the config files AFAIK, not yet for DKIM files however_).

---

> If they decide to set the UID/GUID back to 112:114, you might need to run this again after updating to v13.3.1.

That won't happen. The shifting UID/GID is from package manager having a different install order as our packages are added/removed between releases. When a package adds a user or group it implicitly increments to the next ID available, we don't have much control over that.

There's the 72 line script I wrote a year ago that could be adopted to create these users and groups in advance. The packages will then use that and we'll have stable UID/GID values if we provide explicit ones.
- I'd rather not do this as that seems to be more of a maintenance burden if we want to keep those configuration differences in sync between how packages created users. I also see it as a bit error prone towards contributions / general maintenance.
- A simpler approach IMO is to update `/etc/passwd`, /`etc/group`, `/etc/shadow` entries for users/groups that we want to map our own static UID/GID to, followed by adjusting all files with that prior ownership via `chown`.
  - We can do this post-install, all within the same image layer at build.
  - We only need a list of user/group names to find those IDs to update, and the new IDs can be a 16-bit hash with an offset (_say 10000_), which avoids any conflict with the users/groups assigned unrelated to those we care about. UID/GID range is 32-bit, we only have about 20 users, so there's less than 2% chance of collision in a 16-bit (2 byte) range.

It may seem hacky / over-complicated, I'm open to better solutions but that is a fix that can be handled in a few lines:
- A list of users of groups provided via variable that can be looped over
- `sed` to replace file entries
- `find` + `chown` to correct ownership

Seems intuitive to grok and maintain?

**Comment by polarathene** [comment]
> AFAIK they're meant to be copied to an internal location and permissions should be corrected for that instead where it matters.
> 
> Rspamd is @georglauterbach area so he'd know where to look regarding this and where it's most appropriate to fix.

The above assumption is presently not the case and I can't introduce the fix I'd like in a bug fix release :(

It'll have to wait until the DKIM refactor work.

---

> Changing permissions manually seems to fix the problem by running:
> 
> ```shell
> docker exec -ti mailserver sh -c 'chown _rspamd:_rspamd /tmp/docker-mailserver/rspamd/dkim \
>   && chown _rspamd:_rspamd /tmp/docker-mailserver/rspamd/dkim/*.private.txt'`
> ```
> 
> Adding the chown command to the Rspamd startup script should fix this issue without requiring manual intervention.
> But it would break backward compatibility, too.

For now we'll just go with this as the rspamd DKIM path is semi-fixed at that location (_if you used `setup config dkim`_).

We can't do much about the backwards compatibility concern, if you need to rollback you'll need to manually adjust permissions. The UID / GID mapping changing between releases is known and expected, it's just rare that we have such ownership managed in `/tmp/docker-mailserver` volume, it's not really intended for that but slipped through review 😩 

I'd still like to improve on the issue in future and have stable UID/GID values assigned without this issue.

**Comment by georglauterbach** [comment]
Downgrading ("backwards-compatibility" is not the same IMO) is not a supported path with DMS; so we need not to worry about it.

**Comment by jasperw1996** [comment]
> Downgrading ("backwards-compatibility" is not the same IMO)

You're right, I should work on my wording!😅
Thank you very much for fixing this so quickly – and for the detailed explanation! :)

**Comment by Codelica** [comment]
@polarathene I see my custom RSPAMd config from `/tmp/docker-mailserver/rspamd/local.d/` gets copied into `/etc/rspamd/local.d/` so it shouldn't be a concern, but what would you suggest for the custom map files it references (which I have in `/tmp/docker-mailserver/rspamd/local-maps/` currently) as far as potential permission changes between versions.  I can definitely run `docker exec mailserver chown -R _rspamd:_rspamd /tmp/docker-mailserver/rspamd/local-maps` but just curious if I'm missing a "better" or more supported solution.

**Comment by georglauterbach** [comment]
Since this kind of issue should not happen too often, I think using `chown` manually here is the best course of action for now @Codelica

**Comment by polarathene** [comment]
> but what would you suggest for the custom map files it references (which I have in `/tmp/docker-mailserver/rspamd/local-maps/` currently) as far as potential permission changes between versions.

`/tmp/docker-mailserver` isn't really meant to be concerned with permissions. It is just a location for users to provide config and where some of our scripts that generate / update config there (`setup ...`, typically as `root`).

Anything where permissions matter internally is something that should only be an issue with custom files being directly mounted / referenced when there is no `/tmp/docker-mailserver` to internal copy + ownership support available.

When that ownership is a user / group DMS manages, that is planned in a future release to become static across releases so you will eventually not have the issue, but for now you will need to make sure it's correct across releases.

**Comment by ghnp5** [comment]
@georglauterbach

I see there is an update today, which the changelog says:

> Rspamd: We now ensure correct ownership (_rspamd:_rspamd) for the Rspamd DKIM directory and files (/tmp/docker-mailserver/rspamd/dkim/)

However, I'm still getting the same errors in the docker logs.
