### ISSUE TITLE
bug report: OAUTH2 auth results in eventual client IP ban if fail2ban enabled

### ISSUE THREAD

**Issue by benniekiss** [docker-mailserver/docker-mailserver#3801]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

with OAUTH2 enabled, sign-in with Roundcube is successful, however, the client IP is eventually banned by fail2ban.

The reason is because `!include auth-oauth2.conf.ext` comes after `!include auth-passwdfile.inc`. 

Simply moving `!include auth-oauth2.conf.ext` above `!include auth-passwdfile.inc` is enough to prevent a ban, however, there was some [discussion](https://github.com/docker-mailserver/docker-mailserver/pull/3480/files#r1443857640) on the PR related to other issues with the ordering. 

### 👟 Reproduction Steps

enable OAUTH2, enable fail2ban, sign in to account with OAUTH2, wait for fail2ban to trigger because regular passdb lookup fails before oauth2 is used.

### 🐋 DMS Version

v13.3.0

### 💻 Operating System and Architecture

Fedora CoreOS

**Comment by polarathene** [comment]
> with OAUTH2 enabled, sign-in with Roundcube is successful, however, the client IP is eventually banned by fail2ban.
> 
> The reason is because `!include auth-oauth2.conf.ext` comes after `!include auth-passwdfile.inc`.

I have also noticed during local testing that Dovecot will log this failure of an earlier DB not working. It probably should have clicked that it could trigger Fail2Ban log monitoring 😬 

I believe we can put the OAuth2 passdb as the first one like you've suggested and configure it not to log failures as a proper solution.

That last part is important as you'd get the same problem then for users authenticating with an actual password instead of OAuth2 access token. The reason it is ok to not monitor logs for failed attempts on OAuth2 is the "password" (access token) is much more likely to have higher entropy than an attacker trying to guess an accounts actual password which could be weak and brute forced (which Fail2Ban is trying to guard against).

That or if we can configure Dovecot to only emit an auth failure after trying all PassDBs 🤔

**Comment by benniekiss** [comment]
> That last part is important as you'd get the same problem then for users authenticating with an actual password instead of OAuth2 access token.

actually, in my testing, I dont think passdb auth triggers fail2ban when they are reordered since the `mechanism` parameter is set for the oauth dovecot passdb, so its only used in instances of oauth attempts, iirc

**Comment by polarathene** [comment]
@georglauterbach this is probably something we could fix before merging breaking changes for v14, I'll look into it today and it should be possible to push as a v13.3.1 once I have a PR ready? (_along with the [rspamd dkim ownership issue raised](https://github.com/docker-mailserver/docker-mailserver/issues/3800)_)

**Comment by polarathene** [comment]
> i believe its because the `mechanism` parameter is set for the oauth dovecot passdb, so its only used in instances of oauth attempts, iirc

Awesome! Thanks for pointing that out, I see that we should probably restrict the mechanisms for the file based passdb then 👍 

https://github.com/docker-mailserver/docker-mailserver/blob/3cbcdb2d6517b6c61818afb49c0eb58ee82b6202/target/dovecot/auth-passwdfile.inc#L10-L13

https://github.com/docker-mailserver/docker-mailserver/blob/3cbcdb2d6517b6c61818afb49c0eb58ee82b6202/target/dovecot/auth-master.inc#L2-L8

LDAP we don't have an explicit config file in our source, but Dovecot has one at `/etc/dovecot/conf.d/auth-ldap.conf.ext` (among others):

```
passdb {
  driver = ldap

  # Path for LDAP configuration file, see example-config/dovecot-ldap.conf.ext
  args = /etc/dovecot/dovecot-ldap.conf.ext
}
```

So we may need to add our own config for fixing that concern there too 🤔 

---

https://github.com/docker-mailserver/docker-mailserver/blob/3cbcdb2d6517b6c61818afb49c0eb58ee82b6202/target/dovecot/auth-oauth2.conf.ext#L1-L7

`auth_mechanisms = $auth_mechanisms oauthbearer xoauth2` appends these additional mechanisms to [the existing enabled/allowed mechanisms](https://doc.dovecot.org/configuration_manual/authentication/authentication_mechanisms/#authentication-authentication-mechanisms) while a PassDB can [restrict it's supported mechanisms via it's own `mechanisms` field](https://doc.dovecot.org/configuration_manual/authentication/password_databases_passdb/#passdb-setting) as seen with the OAuth2 config above.

**Comment by georglauterbach** [comment]
> @georglauterbach this is probably something we could fix before merging breaking changes for v14, I'll look into it today and it should be possible to push as a v13.3.1 once I have a PR ready? (_along with the [rspamd dkim ownership issue raised](https://github.com/docker-mailserver/docker-mailserver/issues/3800)_)

Agreed! 👍🏼
