### ISSUE TITLE
Documentation outdated: sieve - dovecot

### ISSUE THREAD

**Issue by telenieko** [docker-mailserver/docker-mailserver#3806]
### Subject

Something else that requires developers attention

### Description

Hi,

This part of the documentation is outdated and links to the old Dovecot wiki which no longer exists:

https://github.com/docker-mailserver/docker-mailserver/blob/3cbcdb2d6517b6c61818afb49c0eb58ee82b6202/docs/content/config/advanced/mail-sieve.md?plain=1#L55-L61

The current link would be to https://doc.dovecot.org/configuration_manual/sieve/plugins/extprograms/#pigeonhole-plugin-extprograms and I understand that the syntax has also changed.

Sorry I can't be of much more help, I'm just skimming through the docs to see if this amazing projects of yours could work for my use case :)

**Comment by polarathene** [comment]
Cheers for the report!

While I'm not able to go through and update the examples any time soon, I have updated the docs to communicate that concern better to the reader. The Dovecot docs link has been updated to the one you've provided.
