### ISSUE TITLE
question: Why do I get the error `Sender address rejected: not owned by user`? (`reject_authenticated_sender_login_mismatch`)

### ISSUE THREAD

**Issue by cfis** [docker-mailserver/docker-mailserver#3824]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

This is more of a question about relay server setup than a bug.

I am testing docker-mailserver on a home machine. It uses a postfix server on aws (mail2.example.com) as a relay. Since port 25 is blocked by Comcast, communication is done over port 587. In particular:

mail2@example.com ------ 587  --- > mail@example.com

`mail2` forwards to `mail` using the user `relay@example.com`  which has been added to postfix-accounts.cf (and the password is known to mail2 via sasl_password).

Assume an email is received by `mail2`, say for myself at `cfis@example.com`, and is forwarded to `mail`. That results in this error in the log:

```
docker-mailserver-59cc9899d4-lfnbn postfix/submission/smtpd[3078]: NOQUEUE: reject: RCPT from mail2.example.com[x.x.x.x]: 553 5.7.1 <root@mail2.example.com>: Sender address rejected: not owned by user relay@example.com; from=<root@mail2.example.com> to=<cfis@example.com> proto=ESMTP helo=<mail2.example.com>
```
This is caused by the inclusion of `reject_authenticated_sender_login_mismatch` in `mua_sender_restrictions`.

If I override `mua_sender_restrictions` to remove `reject_authenticated_sender_login_mismatch`, then the relay user delivers the email to the correct account without error.

However, is there a better way to set this up? I want ports 465 and 587 to require authentication, so `mail2` has to login as some user. And port 25 is blocked by comcast. I figured this would be a common issue, but an internet search revealed people with the same issue but without clear guidance on the best solution.

Thanks!

### 🐋 DMS Version

v13.3.1

### 💻 Operating System and Architecture

Fedora

### ⚙️ Container configuration files

```yml
This is using Kubernetes, see https://github.com/cfis/docker-mailserver-helm
```

**Comment by polarathene** [comment]
You have either added [this yourself or someone decided to add this to the configuration](https://github.com/cfis/docker-mailserver-helm/blob/2ee2dbbea44cb76f875c9c700250477e3a82a9f7/charts/docker-mailserver/values.yaml#L86) you modified.  (**EDIT:** You introduced the change in [this commit](https://github.com/cfis/docker-mailserver-helm/commit/cf26af7b74bbab9a7ba9f3d715b907d1d778b54e#diff-2f08c7e15a1b1dfb9c2630715f664c0396047fd35ef4967bb27db3fa95f6a435R94)

[`SPOOF_PROTECTION=1`](https://docker-mailserver.github.io/docker-mailserver/v13.3/config/environment/) is not a feature enabled by default, it has [some known issues to address](https://github.com/docker-mailserver/docker-mailserver/issues/2819) before I'm comfortable with that.

If you have problems in future, it's recommended to [follow our troubleshooting guidance](https://docker-mailserver.github.io/docker-mailserver/v13.3/config/debugging/), or in this case with the information you had about the cause you could run a search over the source on github and you'd find this:

https://github.com/docker-mailserver/docker-mailserver/blob/ed1e1ebbd3eeb61b059967d94c54d8881112fba4/target/postfix/main.cf#L73-L74

https://github.com/docker-mailserver/docker-mailserver/blob/ed1e1ebbd3eeb61b059967d94c54d8881112fba4/target/scripts/startup/setup.d/security/spoofing.sh#L23-L27

The first one provides the context of `SPOOF_PROTECTION=1`, the 2nd snippet shows that we disable it when `SPOOF_PROTECTION=0`.

---

> If I override `mua_sender_restrictions` to remove `reject_authenticated_sender_login_mismatch`, then the relay user delivers the email to the correct account without error.

No need to override as above clarifies. Just opt-out of the feature or grant a user permission to send as additional addresses.

The docs for this are lacking (partly why the feature is disabled by default), it was [contributed a long time ago with this file](https://github.com/docker-mailserver/docker-mailserver/blob/ed1e1ebbd3eeb61b059967d94c54d8881112fba4/target/postfix/sender_login_maps.pcre). That regex allows only the authenticated DMS account to send mail as themselves, however it's a bit buggy in implementation IIRC.

Closest to documentation is this LDAP comment I added related to LDAP config for the same feature:

https://github.com/docker-mailserver/docker-mailserver/blob/ed1e1ebbd3eeb61b059967d94c54d8881112fba4/test/tests/serial/mail_with_ldap.bats#L62-L70

AFAIK the table lookup is based on the sender address being submitted, and the value mapping is to one or more login usernames (in DMS this is typically an email address) permitted to use that sender address.

For non-LDAP this is the list of tables that are checked:

https://github.com/docker-mailserver/docker-mailserver/blob/ed1e1ebbd3eeb61b059967d94c54d8881112fba4/target/scripts/startup/setup.d/security/spoofing.sh#L18

That covers virtual aliases (`setup alias add ...`) and local system aliases (`root` / `amavis` / etc), while `sender_login_maps.pcre` is just to match the login user. If the docker config volume (`/tmp/docker-mailserver/`) was also provided a regexp config file, that is also used to lookup what is valid. There isn't a config included officially that is specifically only for this feature unfortunately.

If you disable the feature, then an authenticated user can send as any sender address (even if DMS doesn't manage it).

**Comment by cfis** [comment]
Hi @polarathene - thanks for the detailed reply.

I actually did read the code you pointed out at https://github.com/docker-mailserver/docker-mailserver/blob/ed1e1ebbd3eeb61b059967d94c54d8881112fba4/target/scripts/startup/setup.d/security/spoofing.sh#L4 (by searching the code base as you mentioned) before posting. But I realize now that I misread it, and that it is overriding the original value set at https://github.com/docker-mailserver/docker-mailserver/blob/ed1e1ebbd3eeb61b059967d94c54d8881112fba4/target/postfix/main.cf#L74.

Thanks for pointing out the `SPOOF_PROTECTION` setting, I will update `values.yaml` file to have `SPOOF_PROTECTION=` I'm trying to match what I understand to be the default values from the configuration guide.

As for `smtpd_sender_login_maps`, yes I looked through those too and saw the pcre:/etc/postfix/regexp and realized it noted that it returned back the sender. But I have to admit, after reading the postfix documentation on it a few times, I still don't understand what the point of the setting is.

Anyway, so what I understand from your answer is there isn't a mechanism to enable `reject_authenticated_sender_login_mismatch` but have a "blessed" user that the relay server can login as that can then distribute email to other local accounts?

**Comment by polarathene** [comment]
> But I realize now that I misread it, and that it is overriding the original value set at

No worries, I know that it can be tricky. We could do with more maintainers, it's a slow process to improve areas like that due to other priorities 😓 

Do you have a suggestion for how we could prevent that confusion for any future users going through the same experience?

---

> I'm trying to match what I understand to be the default values from the configuration guide.

If you'd like the defaults DMS has, we try to document that on the ENV page (_they're bolded values_), or you can check `/etc/dms-settings` in the container which AFAIK writes the DMS config with defaults (_unless an explicit value was configured_) there.

We have some community contributed guides on the docs page, but they're in need of revision, just a lack of time presently.

---

> I have to admit, after reading the postfix documentation on it a few times, I still don't understand what the point of `smtpd_sender_login_maps` is.

[`smtpd_sender_login_maps`](https://www.postfix.org/postconf.5.html#smtpd_sender_login_maps) is for restricting the sender addresses available to the user submitting mail.

At a business for example, John should not be able to send mail pretending to be Jane. He can perhaps send not only as his own personal address but also as `marketing@example.com`, but that's all.

Someone else wanted the feature to restrict the damage a compromised service could do. So if you had a service only intended for sending some reports, it would not be able to manipulate the sender address to seem more appropriate for sending password reset mails to users.

---

> Anyway, so what I understand from your answer is there isn't a mechanism to enable `reject_authenticated_sender_login_mismatch` but have a "blessed" user that the relay server can login as that can then distribute email to other local accounts?

Sorry, I don't quite get what you're asking for there. You can use the `postfix-regexp.cf` file with `SPOOF_PROTECTION=1` to have a pattern that allows any local-part of a domain address for example to be sent by a specific user. The only potential issue with that is it also becomes an alias that any mail arriving would be aliased to that user to receive too.
