### ISSUE TITLE
Helm Chart

### ISSUE THREAD

**Issue by cfis** [docker-mailserver/docker-mailserver#3825]
### Subject

I would like to contribute to the project

### Description

I was wondering if there was interest in having contributions to the `docker-mailserver-helm`? I did submit a PR there a couple of weeks ago, but it remains open (see https://github.com/docker-mailserver/docker-mailserver-helm/pull/89). 

Over the last couple of weeks I have been experimenting with running docker-mailserver on a local Kubernetes bare-metal cluster. Although its wasn't my intention, I have ended up making a number of changes to the chart which can be seen here - https://github.com/cfis/docker-mailserver-helm. 

I realize its a lot of changes which can be overwhelming, so let me summarize them:

* Always create 4 PersistentVolumeClaims - `mail-config`, `mail-state`, `mail-data`, `mail-log` (previously just one was created). This matches what the docker container does from what I see.
* This has a big advantage that is allows configurations to be modified in the container (previously they were in configmaps which are readonly). See https://github.com/cfis/docker-mailserver-helm/blob/master/charts/docker-mailserver/values.yaml#L294.
* Thus, I then removed mention of setup.sh, and instead documented how to login into a running container and use the `setup` program to configure your server - see the updated README. See https://github.com/cfis/docker-mailserver-helm/blob/master/charts/docker-mailserver/README.md#getting-started
* Default to enabling rspamd based on docker-mailserver documentation. See https://github.com/cfis/docker-mailserver-helm/blob/master/charts/docker-mailserver/values.yaml#L94
* Added rspamd ingress support. See https://github.com/cfis/docker-mailserver-helm/blob/master/charts/docker-mailserver/templates/ingress-rspamd.yaml
* Inlined some configuration files in values.yaml (versus separate config files) and allow them to include Heml directives. See https://github.com/cfis/docker-mailserver-helm/blob/master/charts/docker-mailserver/values.yaml#L457
* Removed rainloop (no longer maintained)
* Removed cert-manager (you should set that up separately)
* Removed haproxy (you should set that up separately)
* Updated to version 13.3.1
* Added full support for PROXY protocol, meaning if you enable it the chart will add new ports that are PROXY enabled 10465, 10587, 10993, 10995 while leaving the default ports untouched so they can be used by other apps in your Kubernetes cluster such as NextCloud, Gitlab, etc). For example, https://github.com/cfis/docker-mailserver-helm/blob/master/charts/docker-mailserver/templates/service.yaml#L54

If there is interest, I can submit a big PR or individual PRs for discussion. But unfortunately, there doesn't seem to be any maintainers with time to review such changes, so also happy to commit them directly if that makes sense.

Thanks!

**Comment by georglauterbach** [comment]
I will take care of this, thanks for pinging!

**Comment by georglauterbach** [comment]
Closing this as completed.
