### ISSUE TITLE
v14.0.0: with switching to debian:12 bookworm opendmarc behaviour changes

### ISSUE THREAD

**Issue by ap-wtioit** [docker-mailserver/docker-mailserver#3828]
### Subject

I would like some feedback concerning a use case

### Description

With switching to debian:12 opendmarc is updated from:
```
opendmarc: OpenDMARC Filter v1.4.0
	SMFI_VERSION 0x1000001
	libmilter version 1.0.1
	Active code options:
		WITH_SPF
		WITH_SPF2
```
to
```
opendmarc: OpenDMARC Filter v1.4.2
	SMFI_VERSION 0x1000001
	libmilter version 1.0.1
	Active code options:
		WITH_SPF
		WITH_SPF2
```

bringing the following changes:
* 1.4.1: https://github.com/trusteddomainproject/OpenDMARC/commit/376720be62dac35e2719e8822f562fc8e0f6bca2
* 1.4.2: https://github.com/trusteddomainproject/OpenDMARC/commit/6925ffe626f9a695d9e834e76b9471100969a06a

The following change in opendmarc:
> Added config option HoldQuarantinedMessages (default false), which
		controls if messages with p=quarantine will be passed on to 
		the mail stream (if False) or placed in the MTA's "hold" 
		queue (if True).  Issue [#105](https://github.com/trusteddomainproject/OpenDMARC/issues/105).  Patch by Marcos Moraes, on
		the OpenDMARC mailing list.

Changes the behaviour how DMS handles such failed messages from putting them in the hold queue to letting them into the INBOX of the user.

The change can be reverted with adding the following to /etc/opendmarc.conf either in user-patches or by building your own image and changing target/opendmarc/opendmarc.conf:
```
HoldQuarantinedMessages true
```

Should we add this behaviour change in the changelog or should we restore the old behaviour? (We are monitoring the hold queue for our servers and therefore prefer the hold queue to decide what's to be done with possible malicious mail but i know that those mails are kinda invisible to other people using DMS as their mailserver)

**Comment by georglauterbach** [comment]
Nice observation! IMO we should put this into the changelog, but not revert, because as you statet, the hold queue is invisible for most users (me actually included). I have no objections aginst doing it the other way around since I am not using OpenDMARC in my setup.

**Comment by polarathene** [comment]
> Should we add this behaviour change in the changelog or should we restore the old behaviour?

Changelog please.

OpenDMARC project changing the default is probably a decision they have better context on and we should trust that. Users that disagree with it may configure that differently and if we have enough vocal users of DMS where it should be changed and is justified well we can look at doing that if needed.

**Comment by georglauterbach** [comment]
@ap-wtioit could you please submit a PR? :)

**Comment by polarathene** [comment]
> could you please submit a PR? :)

Taken care of it: https://github.com/docker-mailserver/docker-mailserver/pull/3841

@ap-wtioit may want to have a glance over in case I missed anything.

**Comment by ap-wtioit** [comment]
#3841 looks good and documents that the default can be changes with user-patches
