### ISSUE TITLE
feature request: Version for armv7 (like version v11.3.1)

### ISSUE THREAD

**Issue by wege2003** [docker-mailserver/docker-mailserver#3832]
### Context

Can you please create a version for armv7 docker image also.
Now there are only arm64 and amd64 but an armv7 would be nice, so everyone can runs it on Raspi 3/4

### Description

Can you please create a version for armv7 docker image also.
Now there are only arm64 and amd64 but an armv7 would be nice, so everyone can runs it on Raspi 3/4

### Alternatives

no alternatives

### Applicable Users

for every user which is on armv7

### Are you going to implement it?

Yes, because I know the probability of someone else doing it is low and I can learn from it.

### What are you going to contribute?

i have tried to build an image but i missed it :(

**Comment by polarathene** [comment]
> Now there are only arm64 and amd64 but an armv7 would be nice, so everyone can runs it on Raspi 3/4

We don't support this anymore.

If there was enough users interested in it, and it didn't add maintenance burden we could consider it but the [decision was made some time ago](https://github.com/docker-mailserver/docker-mailserver/issues/2642).

- As that link mentions RPi 3 is capable of supporting ARM64 images, but you need to install the 64-bit OS AFAIK.
- The cost of a replacement device is small enough for an individual that we'd rather avoid the maintenance concerns it burdens us with, we don't have time to support anything specific for ARMv7 users and it would waste our CI (_and CI cache if we used that_).

---

> i have tried to build an image but i missed it :(

```bash
# Get the src and build the image locally based on release tag:
git clone https://github.com/docker-mailserver/docker-mailserver --branch v13.3.1 --depth 1
docker build --tag dms:13.3.1 .

# Confirm image is running / working with minimal DMS config:
docker run --rm -it --hostname mail.example.test --name my-dms dms:13.3.1
# Add an account to prevent DMS shutting down:
docker exec -it my-dms setup email add hello@example.test bad-password

# Shell access to the DMS container if you want to do anything else in there:
docker exec -it my-dms bash

# Convert to compose.yaml with your actual config and use `image: dms:13.3.1`
```

That should work 👍
