### ISSUE TITLE
other: How to setup mailserver as local relay

### ISSUE THREAD

**Issue by kingnarmer** [docker-mailserver/docker-mailserver#3867]
### Subject

How to setup mailserver as local relay

### Description

How to setup docker-mailserver as local relay for servers on local subnets behind firewall. The servers uses postfix client to forward to local relay and then local relay forwards email out . The IP scheme is 10.x.x.x  and 192.168.x.x . I need the mail server to act as internal relay for domain xyz.domain.com . 

Thanks

**Comment by georglauterbach** [comment]
Took me 5 secs to enter "local relay" in our documentation and use the first result.

This issue violates community guidelines; in particular the "Man, I really should have taken 10 seconds to search through the documentation that maintainers spend a lot of effort and time on before I open an issue that can easily be found in the docs".

ref: https://docker-mailserver.github.io/docker-mailserver/latest/examples/tutorials/basic-installation/#using-dms-as-a-local-mail-relay-for-containers
