### ISSUE TITLE
other: "catch all" mailbox, but still send a bounce back

### ISSUE THREAD

**Issue by ghnp5** [docker-mailserver/docker-mailserver#3868]
### Subject

I would like to configure a not documented mail server use case

### Description

Hello!

(apologies if this is already documented!)

At the end of `postfix-virtual.cf`, I have:

```
@mydomain.com catchall@mydomain.com
```

This way, if no aliases above it matched, it will send the email to that "catch all" mailbox, and no email is lost. (in case of typos, etc)

However, I'd like to still send a bounce back with the reason code that the mailbox does not exist.

Is it possible to do this?

Thanks!!

**Comment by georglauterbach** [comment]
I see what you want and why you want it, but from a logical PoV, this makes no sense:

1. Either you have a **catch-all** that catches all e-mails for arbitrary accounts; one that you configured on-purpose
2. Or you don't have such an alias, in which case DMS rejects the e-mail and sends a bounce notification

Having a bounce-notification with the reason "the e-mail was sent to an account that does not exist" while the e-mail was delivered to an existing account seems wrong at best, misleading at worst to me.

**Comment by ghnp5** [comment]
Thank you.

If it's not possible, it's not possible.

But I don't agree that it's wrong to do that.

Simply, the "catch-all" isn't a monitored webmail (as a lot of junk goes there), and I have a cron that expires the emails after 30 days. So, most likely the emails arriving there will never be read, so I'd like to let the sender know that the address is invalid.

The "catch-all" mailbox is there for debugging purposes and other things - we never know when it can be useful. (it's been useful to me already, a few times)

If a bouce isn't possible, then I guess the closest I can have is an auto-response.

Thanks again.

**Comment by polarathene** [comment]
I think you'd have to implement a milter/content-filter that submits the mail internally for delivery, while also rejecting the mail?

If you don't want the mail rejected (_like it normally would be when the user doesn't exist_), but to send a bounce it could be done in sieve, but it seems that `reject` and `fileinto` conflict and you can only actually do one action.

- https://www.emaildiscussions.com/showthread.php?threadid=44260
- https://www.reddit.com/r/ProtonMail/comments/1agsgmc/can_someone_help_with_the_creation_of_sieve/
- https://support.tigertech.net/sieve#the-sieve-reject-jmp

```sieve
require ["fileinto", "reject", "copy"];
fileinto :copy "INBOX.Junk";
reject "I am rejecting this email";
```

From `.dovecot.sieve.log`:

```
.dovecot: line 3: error: reject/ereject action conflicts with other action: the store action (.dovecot: line 2) tries to deliver the message.
```

Also note the reference links caution on becoming a backscatter source abused by spammers.

**Comment by ghnp5** [comment]
Thank you for looking into this, and for the tips. 👍🏼
I understand.
Have a good day, you both!
