### ISSUE TITLE
Deploy Unboud as recursive DNS server (recommended for Rspamd)

### ISSUE THREAD

**Issue by cmonty14** [docker-mailserver/docker-mailserver#3871]
### Subject

I would like some feedback concerning a use case

### Description

It's recommended in [Rspamd documenation](https://rspamd.com/doc/faq.html#resolver-setup) to deploy Unbound:
_Therefore, it is strongly advised to employ your own recursive resolver when using Rspamd or any other email-related technology. Our recommended choice is to set up Unbound or, for more advanced setups, the Knot Resolver. You can find basic setup information for Unbound here._

I deployed [mvance/unbound](https://github.com/MatthewVance/unbound-docker) successfully.

What must be modified in DMS to ensure a working setup?

**Comment by casperklein** [comment]
You have to add the DNS element to your compose file and point to your unbound: https://docs.docker.com/compose/compose-file/05-services/#dns

**Comment by cmonty14** [comment]
> You have to add the DNS element to your compose file and point to your unbound: https://docs.docker.com/compose/compose-file/05-services/#dns

None of these settings is required.

My understanding is that this would modify `/etc/resolv.conf`, however anything related to DNS is fully managed by _Unbound_ incl. the relevant settings in `/etc/resolv.conf` that has this config:
```
❯ cat /etc/resolv.conf
# Generated by resolvconf
nameserver 127.0.0.1
```

That means by any  circumstances this must not be modified by DMS.

**Comment by casperklein** [comment]
If 127.0.0.1 on your host is your unbound, then you don't have to do anything. [Docker container are using the host's DNS](https://docs.docker.com/network/#dns-services).

**Comment by georglauterbach** [comment]
[Our documentation also suggests using custom DNS resolvers](https://docker-mailserver.github.io/docker-mailserver/edge/config/security/rspamd/#rbls-real-time-blacklists-dnsbls-dns-based-blacklists), but for the actually important parts, which are DNSBLs. Rspamd does not actually need it per se, but it also queries DNSBLs. Most DNSBLs require you to access them _with your own, **recursive**_ resolver. Whether you use Unbound, or something else that does recursive DNS resolution, does not matter (I use coreDNS).
