### ISSUE TITLE
Rspamd create dkim key permissions errors

### ISSUE THREAD

**Issue by jwynn6** [docker-mailserver/docker-mailserver#3873]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

When generating dkim keys I get a permissions error, but only for writing the private key, the public key gets written just fine.  I've reproduced the error on edge and 13.3.1. 

I thought it might have something to do with  #3800  but following the permissions changes there has not resolved it.  I see that the directory ownership gets set properly every time I generate keys.

The mounted volume at `/tmp/docker-mailserver/rspamd`  shows the correct ownership and same ownership on the host.  I've even tested making the the folder fully read/write for all users. 

Here is the output of  ` docker exec -it mailserver setup config dkim --force domain <domain>`

### 🐋 DMS Version

v13.3.1

### 💻 Operating System and Architecture

Ubuntu 22.04

### 📜 Relevant log output

```Text
[  DEBUG  ]  Domain set to '<domain>'
[   INF   ]  Creating DKIM keys of type 'rsa' and length '2048' with selector 'mail' for domain '<domain>'
cannot save privkey to file: /tmp/docker-mailserver/rspamd/dkim/rsa-2048-mail-<domain>.private.txt, Permission denied
[   INF   ]  Successfully created DKIM keys
[  DEBUG  ]  Public key written to '/tmp/docker-mailserver/rspamd/dkim/rsa-2048-mail-<domain>.public.txt'
[  DEBUG  ]  Private key written to '/tmp/docker-mailserver/rspamd/dkim/rsa-2048-mail-<domain>.private.txt'
ls: cannot access '/tmp/docker-mailserver/rspamd/dkim': Permission denied
[ WARNING ]  The Rspamd user ('_rspamd') seems to be unable to list files in the keys directory ('/tmp/docker-mailserver/rspamd/dkim') - Rspamd may experience permission errors later
[   INF   ]  '/tmp/docker-mailserver/rspamd/override.d/dkim_signing.conf' exists, not supplying a default ('--force' does not overwrite this file, manual adjustment required)
[   INF   ]  Here is the content of the TXT DNS record mail._domainkey.<domain> that you need to create:
```

**Comment by polarathene** [comment]
In the meantime, you can create the DKIM keypair and config for rspamd as described here: https://github.com/docker-mailserver/docker-mailserver/issues/3630#issuecomment-1903401956

That should be compatible AFAIK 👍 We may switch to that approach in v15

**Comment by georglauterbach** [comment]
Mhhh, this looks very weird. Thank you for reaching out and reporting this bug; this helps us maintainers improving the scripts. Let's go over this one by one:

1. Why does `rspamadm` not fail when this happens: `cannot save privkey to file: /tmp/docker-mailserver/rspamd/dkim/rsa-2048-mail-<domain>.private.txt, Permission denied`? This makes checking for errors more difficult. I just checked, but `su` does properly propagate exit statuses, hence `__do_as_rspamd_user` should work just fine. I will implement a patch that checks a temporary log file.
2. The STDOUT of the `ls` command is useless; I will take care of that.
3. The permission errors are left for you to resolved, though @jwynn6; can you show us the output of `docker exec -ti <CONTAINER NAME> ls -lh /tmp/docker-mailserver/ | grep 'rspamd'` and `docker exec -ti <CONTAINER NAME> ls -lh /tmp/docker-mailserver/rspamd/`? I suspect that the `dkim` directory in `/tmp/docker-mailserver/rspamd/` does not have the correct ownerships / permissions.
