### ISSUE TITLE
feature request: Disable subject rewriting / change thresholds for Rspamd

### ISSUE THREAD

**Issue by some-user123** [docker-mailserver/docker-mailserver#3885]
### Context

Mails with a spam score above 7 have the subject line rewritten by rspamd.

### Description

I'd like to be able to disable this behavior using environment variables by changing the threshold to a higher value.
(like `SA_TAG`, `SA_TAG2`, `SA_KILL`).

### Alternatives

Changing the prefix to an empty string `""` could result in the same result (like `SA_SPAM_SUBJECT`).

### Applicable Users

Users of rspamd.

### Are you going to implement it?

No, and I understand that it is highly likely no one will implement it. Furthermore, I understand that this issue will likely become stale and will be closed.

### What are you going to contribute?

I can test and give feedback. I don't think I'm capable of implementing it without third party support. Maybe that would be a nice option to offer:
[x] I would be willing to implement it, but need support.

**Comment by casperklein** [comment]
This is already implemented, but not released yet. There will be a new `SPAM_SUBJECT` environment variable.
