### ISSUE TITLE
bug report: tail: /var/log/mail/mail.log: file truncated

### ISSUE THREAD

**Issue by vincentDcmps** [docker-mailserver/docker-mailserver#3895]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

Hi
I use DMS on docker in nomad cluster and my data are on NFS share.
following an issue with my NAS I have reboot this one. 
following this on the runner I can't remount NFS share.
I have a message saying that a process is always using the folder
I note in DMS log the message
``` 
tail: /var/log/mail/mail.log: file truncated
```

this process seem in D state in HTOP when I try to stop container this process can't be kill and I need to reboot the worker to remount correctly my share.

### 👟 Reproduction Steps

- use nfs share
- reboot nfs server

### 🐋 DMS Version

v13.13.1

### 💻 Operating System and Architecture

arch linux

**Comment by polarathene** [comment]
DMS does not have official support for NFS, it's known to have issues with Dovecot too IIRC.

The container tails that log file once it's run setup scripts and starts services, outputting that to stdout.

---

It's unlikely you'll receive much support. The log may be handled by a logrotate service daily I think. Just backup the location, delete the log file, or the entire volume for logs if you do not need the existing logs and that should be fine.
