### ISSUE TITLE
other: using GlimeAI

### ISSUE THREAD

**Issue by georglauterbach** [docker-mailserver/docker-mailserver#3902]
### Subject

Something else that requires developers attention

### Description

I have recently opened [an issue](https://github.com/authelia/authelia/issues/6708) over at [`authelia/authelia`](https://github.com/authelia/authelia) and received a very decent answer from [Glime AI](https://github.com/apps/glime-ai). I thought this was something we could benefit from as well, especially when giving users a first answer to their issues.

Therefore, I applied at <https://glimelab.ai/> for access. Currently, they're in closed beta. I have already received feedback. They have started parsing our repo, and will report back to me for a trial. I have told them I will coordinate with other maintainers on this. I offered "promotional space" to them in return; I thought of something like Netlify that we already use for documentation previews.

Please let me know what you think.

**Comment by polarathene** [comment]
While it's interesting that it'd have access to all my verbose comments to digest, I'm also a bit doubtful on how well it understands/processes my answers that include imagery, collapsed details sections, referenced sections of code at certain points in time (_similar with docs links or third-party links_)...I know some issue threads aren't exactly focused either or contain incorrect answers.

I'd love to be wrong, but if it doesn't prove itself and ends up being noise or worse, misinformation - how long would you want to keep it around for?

---

> I have recently opened [an issue](https://github.com/authelia/authelia/issues/6708) over at [`authelia/authelia`](https://github.com/authelia/authelia) and received a very decent answer from [Glime AI](https://github.com/apps/glime-ai).

I see quite a bit of words and repetition, but not quite sure how that answer is helpful towards the issue you raised? You already seemed to know as much as it did?

DMS is especially quite technical in nature. Even if Glime understands the services we configure for, it's not likely to understand the context of our own configuration layers? It'd need to grok our codebase and docs (_which aren't perfect by any means_), along with the services themselves and know when generic advice like ChatGPT might output would not actually be applicable in DMS, or not in the usual way. On top of that we have compose config, but not all user reports are Docker Compose based 🤷‍♂️ 

My impression is it'll process our existing issues/PRs/discussions (_of this repo and not the entire organization I'd hope?_), and act as a knowledgebase / FAQ responder. Only issue with that is the older the content, the less relevant it is as the project has changed quite a bit over the years. I often link back to older content in the project for a context paper trail which maybe it can leverage if it understands that.

---

> Please let me know what you think.

Doubtful, but curious.

We rank well on search engines which helps discovery of the project. If Glime is enabled for the project but not producing value as hoped it may work against that?

I'd much rather steer them towards processing all our PRs/commits and encourage them to pivot towards making a decent AI maintainer for us 😆 (_just look at [these recent OSS stats](https://www.phoronix.com/news/Intel-2023-Survey-Results), I can relate to the burnout stat for sure_)

**Comment by casperklein** [comment]
I'm curious to see if that brings advantages/requires less maintainer capacity in the future to answer issues 👍

I share Brennan concerns. But if it doesn't fit, we can remove it at any time.

> We rank well on search engines which helps discovery of the project. If Glime is enabled for the project but not producing value as hoped it may work against that?

Good point. I haven't thought about this. Search engines may lower the ranking, when AI generated text is detected.

**Comment by georglauterbach** [comment]
I understand the concerns, and I already clearly communicated our intentions via e-mail to the staff that takes care of the closed-beta. Therefore, I suggest we try a test period of, let's say, 2 or 3 weeks in case we get access, and then evaluate whether we have seen benefits. If we come to the conclusion that there is none (or there may even be harm), then we go ahead and remove it from the repository again.

All in all, I am not a fan of throwing buzzwords (especially AI) around, but I can see how such a tool would benefit us: we have certain issues that exist because people don't read our docs like they should. Especially in these cases, a tool like Glime could help. I have not looked at the configuration options. Maybe we can run Glime only on issues marked with a certain tag? This way, we can stop Glime from running on feature requests for example, only testing it on questions and bug reports?

---

> I see quite a bit of words and repetition, but not quite sure how that answer is helpful towards the issue you raised? You already seemed to know as much as it did?

It was a confirmation of what I thought, which I found to be good.

> I'd much rather steer them towards processing all our PRs/commits and encourage them to pivot towards making a decent AI maintainer for us 😆 (just look at [these recent OSS stats](https://www.phoronix.com/news/Intel-2023-Survey-Results), I can relate to the burnout stat for sure)

Indeed, maintainer fatigue is a serious problem. I hope that we can mitigate this problem in the future.
