### ISSUE TITLE
feature request: customize Logrotate format

### ISSUE THREAD

**Issue by fabiendv** [docker-mailserver/docker-mailserver#3914]
### Context

After setting up a mailer server, I've seen the env variable to change the frequency of log rotation. But nothing about the format.

### Description

I'd like to add a new variable to specify Logrotate format.

### Alternatives

Steaming logs

### Applicable Users

Any developers who are conscientious about maintaining tidy logs.

### Are you going to implement it?

Yes, because I know the probability of someone else doing it is low and I can learn from it.

### What are you going to contribute?

Add new env variables to customize Logrotate format.

**Comment by casperklein** [comment]
Can you elaborate, what you exactly mean by format? Logrotate just "rotates" the files + compresses them. The content of the log files is not altered.

The format inside those files is defined by `rsyslog`. But that's independent from `logrotate`.

For example, the time format in those logs changed with the base image update to Debian 12. To keep the old format (<= Debian 11), you can use [user-patches.sh](https://docker-mailserver.github.io/docker-mailserver/latest/config/advanced/override-defaults/user-patches/) for that:

``` bash
echo "[CUSTOMIZE]  Use old time format in rsyslog"
sedfile -i '1i # Custom: Old timestamp format - no "high precision timestamps"' /etc/rsyslog.conf
sedfile -i '2i $ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat'        /etc/rsyslog.conf
```

**Comment by polarathene** [comment]
> Steaming logs

This will be available when DMS eventually adopts Vector for log management.

---

> For example, the time format in those logs changed with the base image update to Debian 12. To keep the old format (<= Debian 11), you can use [user-patches.sh](https://docker-mailserver.github.io/docker-mailserver/latest/config/advanced/override-defaults/user-patches/) for that

Perhaps we should add a docs entry about that since I guess it's going to be less discoverable in the changelog, especially for new users?

**Comment by fabiendv** [comment]
By saying format, I mean file name.

Instead of being `myLog.1` with a number that indicates the rotation number, I'd like to add the date.

**Comment by casperklein** [comment]
I was not aware, that this is possible with rsyslog. If you know how to do it, feel free to contribute 👍

Recently `LOGROTATE_COUNT` was addedd in https://github.com/docker-mailserver/docker-mailserver/pull/3907. You can take a look to know, which code parts have to be adjusted.
