### ISSUE TITLE
feature request: Move spam to mailbox associated to the `\Junk` special-use attribute

### ISSUE THREAD

**Issue by UltraCoderRU** [docker-mailserver/docker-mailserver#3918]
### Context

For now, I can rename Junk mailbox (and others) as described in [documentation](https://docker-mailserver.github.io/docker-mailserver/latest/examples/use-cases/imap-folders/). But additional changes may be necessary, namely replacing 'Junk' string to selected mailbox name in two other files:
1. If `MOVE_SPAM_TO_JUNK=1`, in file `/usr/lib/dovecot/sieve-global/after/spam_to_junk.sieve`
2. If `RSPAMD_LEARN=1`, in file `/etc/dovecot/conf.d/90-sieve.conf`

This can be done in `user-patches.sh` using, for example, `sed` utility. But I think we can do better.

### Description

Dovecot 2.3 added support for [RFC 8579](https://datatracker.ietf.org/doc/html/rfc8579.html). If we enable Sieve extension 'special-use', we can rewrite `spam_to_junk.sieve` as follows:
```
require ["fileinto","special-use"];

if anyof (header :contains "X-Spam-Flag" "YES",
          header :contains "X-Spam" "Yes") {
    fileinto :specialuse "\Junk" "Junk";
}
```
This will eliminate the need to patch the file `spam_to_junk.sieve`.

Unfortunately, some changes in IMAPSieve plugin required to solve the problem with `90-sieve.conf` (allowing to specify special-use attribute in `imapsieve_mailboxXXX_name` and `imapsieve_mailboxXXX_from` settings). I've already [suggested](https://dovecot.org/mailman3/hyperkitty/list/dovecot@dovecot.org/thread/QDU2BIJFTU7YRUJUZFKXG5COUQYTREME/) this feature in Dovecot mailing list and waiting for reply.

### Alternatives

Of course, instead we can add new configuration parameter like `JUNK_MAILBOX_NAME` in docker-mailserver. But what will happen, if user rename Junk mailbox and forget to set/change this parameter?

### Applicable Users

Users, who rename Junk mailbox on their servers (for translation purpose or because they just prefer 'Spam' over 'Junk').

### Are you going to implement it?

Yes, because I know the probability of someone else doing it is low and I can learn from it.

### What are you going to contribute?

I've tested changes to `spam_to_junk.sieve` on recent version of docker-mailserver, and it works.
For some reason I can not run project tests locally. I can successfully build image, but when I run `make clean tests` I get this error:
_The directory named as part of the path /var/log/mail/rspamd.log does not exist in section 'program:rspamd' (file: '/etc/supervisor/conf.d/dms-services.conf')_
What am I doing wrong?

**Comment by georglauterbach** [comment]
> The directory named as part of the path `/var/log/mail/rspamd.log` does not exist in section 'program:rspamd' (file: '/etc/supervisor/conf.d/dms-services.conf')
>
> What am I doing wrong?

That is weird.. I have not seen this before 🤔

**Comment by UltraCoderRU** [comment]
> That is weird.. I have not seen this before 🤔

Problem solved. I used **docker.io** (v24.0.5) package from official Ubuntu repository. After replacing it with **docker-ce** from download.docker.com, I can run tests. I noticed some warnings when building with Ubuntu version:
_/bin/bash: line 1: warning: here-document at line 1 delimited by end-of-file (wanted 'EOF')_
They are result of `RUN <<EOF` commands in Dockerfile. Maybe, the **buildx** is required for correct building?

**Comment by georglauterbach** [comment]
Yes, buildx is required. I think our documentation states this as well.
