### ISSUE TITLE
other: is there an easy way to disable all delays on incoming mail?

### ISSUE THREAD

**Issue by seanhly** [docker-mailserver/docker-mailserver#3945]
### Subject

I would like some feedback concerning a use case

### Description

I've been using this service ever since I found it.  I love that it handles most of the elements of a mailserver with very little input from me.

However, it's really stung me on a few occasions, e.g. by causing a lengthy delay between an email arriving to the server and its actual arrival into the server maildir for my user.

I've read previously that postgrey is the culprit here, and I've tried creating a list of whitelist clients:
```bash
grep -r ryanair /etc/postgrey/
> /etc/postgrey/whitelist_clients:ryanair.com
```

However, this has had no impact, and I'm starting to have my doubts that postgrey is the problem.

I don't usually mind a bit of a delay on mail arriving, and I understand the historic reasons for this as a spam deterrent.  But these days many websites issue login links via email, and in the case of a few websites (e.g. Ryanair), the login link expires 5-10 minutes after it is sent.  This creates a bit of a nightmare situation when the time delay on arriving mail with docker mailserver is roughly 9 minutes 30 seconds.  I basically have to enter meditation mode for 9 minutes 30 seconds, then race against the clock to pull my mail from the server and input the code in the browser.  Usually I lose this race multiple times, and it takes about an hour in total to login.

At this point, I care less about spam and more about my ability to login to places.  So I was wondering if there were any quick one liners I could use to *completely* disable any time delay on mail arriving into the maildir?

All the best, and thanks for the great software!
Seán

**Comment by georglauterbach** [comment]
I have encountered the situation with Ryanair as well, and for me, the culprit was a greylisting mechanism (of Postgrey actually). In Ryanair's case, it is because they send from AWS nodes that change each time they contact your mail server (and AFAIK Postgrey greylists in the remote mail server's hostname). Hence, there is an element of luck involved.

The answer that Glime provided is actually quite good: The cure, at least for me, was using Rspamd, which packs greylisting too, but works quite differently. Take a look at [our Rspamd docs](https://docker-mailserver.github.io/docker-mailserver/edge/config/security/rspamd/) and try it out :) Make sure to pick the correct version of the docs for your DMS deployment.

**Comment by polarathene** [comment]
Glime AI did well here 👍 

---

> I'm starting to have my doubts that postgrey is the problem.

Easily verifiable by disabling Postgrey?

As has been suggested, you'll probably want to give rspamd a look. The more success stories we hear from using rspamd than problems, the sooner it'll become the new default out of the box :)

---

> in the case of a few websites (e.g. Ryanair), the login link expires 5-10 minutes after it is sent. This creates a bit of a nightmare situation when the time delay on arriving mail with docker mailserver is roughly 9 minutes 30 seconds.

Try the ENV [`POSTGREY_DELAY=30`](https://docker-mailserver.github.io/docker-mailserver/v13.3/config/environment/#postgrey_delay) as per our Postgrey ENV docs, or whatever value in seconds that better suits you?

> I was wondering if there were any quick one liners I could use to _completely_ disable any time delay on mail arriving into the maildir?

Sure, try `ENABLE_POSTGREY=0` (_the default_) to take Postgrey out of the equation entirely, or set the delay to 0 (_although that would [defeat the purpose of using postgrey](https://www.vpnreactor.com/greylisting-org-acquistion/).._).

**Comment by seanhly** [comment]
Thanks folks!  I've just disabled postgrey.  I would also like to question its necessity within this container.  Maybe there are cases I'm not aware of, but I think docker-mailserver would mostly be used by individuals and small businesses.  In these cases, is greylisting even that important?  The original purpose was to reduce spam detection load on the server side, but if there are only a small handful of users on the system, this seems redundant.

Apparenly frustrations with greylisting go a long way back: http://articles.marco.org/238

**Comment by casperklein** [comment]
>  I would also like to question its necessity within this container. 

It's disabled by default. So when you enable it, you should be aware about the pro/cons.

In my experience, it causes more trouble (delayed mails) than it prevents spam. There are nowadays way more/better options to detect/prevent spam mails.

**Comment by georglauterbach** [comment]
Er are very hesitant when it comes to removing features. With upcoming versions, we will make Rspamd the default and disable other anti-spam measures by default. Removing them is not planned yet, but at some point in the future we will do a cleanup, of course, the remove old, dangling, unnecessary services.
