### ISSUE TITLE
other: how to build docker-mailserver with PostgreSQL 

### ISSUE THREAD

**Issue by liuhr-ncu** [docker-mailserver/docker-mailserver#3950]
### Subject

I would like some feedback concerning a use case

### Description

“docker-mailserver employs only configuration files, no SQL database.”But what should I do if I need to use PostgreSQL database? Because now I need to connect the database in my application for mailbox account management.

**Comment by polarathene** [comment]
> For your requirement, you could develop an external application or script that interacts with PostgreSQL for account management purposes. This application could then modify the relevant DMS configuration files (such as `postfix-accounts.cf` for user accounts) based on the data in your PostgreSQL database.

While that is a technically valid approach, going to that effort it may be easier to just read the Postfix docs for configuring for a DB.

That said, I don't think DMS will smoothly support such as the startup scripts assume an account provisioner we know of is configured. That'd probably need an opt-out option to not conflict with a third-party provisioner. Thus the advice from Glime here to bridge the external DB via our `setup ...` commands or their associated configs directly is more appropriate 👍 

---

> what should I do if I need to use PostgreSQL database?
> Because now I need to connect the database in my application for mailbox account management.

We do not have support for that, you'd have to figure that out yourself and maintain it. You could potentially upstream changes that would make that easier to support, we've accepted similar before from a contributor that needed Lua in Dovecot for account management.

You may have better luck with an alternative to DMS which does embrace databases for account management.

**Comment by georglauterbach** [comment]
In short: you don't. DMS is built on the premise that everything is stored in files. Other projects are more suited towards using databases.
