### ISSUE TITLE
feature request: storage limit for a email account

### ISSUE THREAD

**Issue by MicheleAwada** [docker-mailserver/docker-mailserver#3951]
### Context

since it would be useful to have a limit to make sure if you give a custom email to someone they dont transgres the boundries and steal all your vps's storage.

### Description

It would be nice to have a storage limit for users, for example i can say
setup email update example@example.com --datalimit=1000000000
which is equal to 1gb
or 0 would be the same as infinity

### Alternatives

im not sure.

### Applicable Users

for people using these emails as services for clients

### Are you going to implement it?

No, and I understand that it is highly likely no one will implement it. Furthermore, I understand that this issue will likely become stale and will be closed.

### What are you going to contribute?

i might contribute, but i dont know linux programming languages and such, so it would be difficult

**Comment by georglauterbach** [comment]
What you're looking for is called quotas; have a look at our docs and search for `ENABLE_QUOTAS`.
