### ISSUE TITLE
feature request: Does Docker Mailserver support the jmap protocol

### ISSUE THREAD

**Issue by wangyixiang0103** [docker-mailserver/docker-mailserver#3957]
### Context

https://jmap.io/spec-mail.html#emailget

### Description

https://jmap.io/spec-mail.html#emailget

### Alternatives

Does Docker Mailserver support the jmap protocol

### Applicable Users

Does Docker Mailserver support the jmap protocol

### Are you going to implement it?

Yes, because I know the probability of someone else doing it is low and I can learn from it.

### What are you going to contribute?

Does Docker Mailserver support the jmap protocol

**Comment by polarathene** [comment]
We use Postfix, so it would be expected a future version of Postfix will get that feature eventually, then DMS will.

In the meantime, you could find another software that can receive mail from Postfix to relay via JMAP? `stalwart` (rust based) seems to be capable of that task. You will probably want to wait until v14 release of DMS (until then see our `edge` version docs) where the relay host support has been improved.

**Comment by pbek** [comment]
The JMAP server of stalwart seems to have moved to https://github.com/stalwartlabs/mail-server.

**Comment by polarathene** [comment]
> The JMAP server of stalwart seems to have moved

Yes the repo was recently archived and moved into the one you reference as a crate.

I know when the JMAP support with stalwart was announced the blog post mentioned about being able to proxy to Postfix as they did not have their own SMTP solution at the time (2 years ago), but a quick glance over the repo and docs and it's not clear if that's still something they support?

Is there a reason you'd want JMAP with DMS vs using Stalwart entirely instead?

**Comment by pbek** [comment]
No real "need". I just wanted to see if there is a way to play around with JMAP in docker-mailserver with https://aerc-mail.org or https://github.com/nextcloud/mail/issues/2931 and see if there is a speed improvement over IMAP.
