### ISSUE TITLE
Userdb alias dummy accounts use wrong home directory

### ISSUE THREAD

**Issue by profplump** [docker-mailserver/docker-mailserver#3990]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

Dummy accounts created by target/scripts/helpers/accounts.sh have the wrong home directory

Pull #3335 changes the default home directory for userdb entries, but only updates one of the two places such lines are generated by target/scripts/helpers/accounts.sh. See commit e04f0a573c63585a1cfc1efa283fabfd16f420af which should have updated line 160 in _create_dovecot_alias_dummy_accounts in the same way line 80 was updated (adding /home to end)

These dummy accounts are enabled by default and allow IMAP logins so it would be nice if they actually worked. As it stands users can login to an address they recognize with their usual password but it contains none of their mail. Adjusting mail_location in 10-mail.conf permits both real and alias logins to work, but only if the home path is constructed consistently

### 👟 Reproduction Steps

`ENABLE_QUOTAS=1` (this is the default)

```
setup email add foo@baz.com
setup alias add bar@baz.com foo@baz.com
```

`cat /etc/dovecot/userdb` to see that bar@baz.com user has a different home directory than foo@baz.com

### 🐋 DMS Version

v13.3.0

### 💻 Operating System and Architecture

Alpine x86_64

**Comment by polarathene** [comment]
> These dummy accounts are enabled by default and allow IMAP logins so it would be nice if they actually worked.

They're only created as a workaround for Dovecot Quota's support which is enabled by default. A side-effect is that you can login as an alias, but that's not intentionally supported.

That said, I don't have an issue with the proposed correction as I don't think anyone is going to resolve the need for the workaround any time soon.
