### ISSUE TITLE
Helm Chart Admin Access

### ISSUE THREAD

**Issue by cfis** [docker-mailserver/docker-mailserver#4037]
### Subject

I would like to contribute to the project

### Description

@georglauterbach @polarathene - I realized I don't admin access to the docker-mailserver-helm repo (https://github.com/docker-mailserver/docker-mailserver-helm). Can either of you grant it to me? I want to review the github chart publish workflow and how it is setup but that requires access to admin settings.

FYI - there have been a s been a steady stream of PRs to the repo, so there seems to be at least some interest in it.

**Comment by georglauterbach** [comment]
I will have a look tomorrow.

**Comment by georglauterbach** [comment]
Done :)

**Comment by georglauterbach** [comment]
CC @docker-mailserver/helm-maintainers @docker-mailserver/admin-maintainers @docker-mailserver/core-moderators @docker-mailserver/core-maintainers @docker-mailserver/core-administrators 

---

While in the process of resolving this issue, I took the time to review the current organization & team structure. I renamed the teams slightly (`-` -> `/` to better visualize the "namespacing" of the team).

1. I have added @polarathene to the @docker-mailserver/core-administrators team (removing him from the moderators team at the same time).
2. I made @casperklein a maintainer in the @docker-mailserver/core-maintainers team. I'd be happy to invite you to the @docker-mailserver/core-administrators team, if you'd like to join.
3. I removed @erik-wramner from the @docker-mailserver/core-maintainers team.
4. I have moved @fbartels and @wernerfred from the @docker-mailserver/core-administrators team to the @docker-mailserver/core-maintainers team with member access. @fbartels will remain as a team member on DockerHub for the `mailserver/docker-mailserver` image.
5. I have removed myself from @docker-mailserver/core-maintainers.

Everyone should now be in one and only one team in the `core` namespace, plus additionally in supplementary teams for the `docker-mailserver/docker-mailserver-{helm,admin}` repositories as maintainers.

**Comment by fbartels** [comment]
Hi @georglauterbach,
since my contributions are quite minimal since I no longer use docker-mailserver professionally I would also not be offended if you remote me from the remaining groups. If you need my input on something I am of course glad to help.

**Comment by georglauterbach** [comment]
I can of course do that @fbartels; I will move you to moderators :)

When it comes to DockerHub: I would very much like to have a +1 in the organization in case I cannot access my account, and we need to do something. If someone else is willing to step in here, please let us know!

**Comment by polarathene** [comment]
Thanks for taking the time to tackle this ❤️ 

> **If someone else is willing to step in here, please let us know!** The only thing required is a DockerHub account, and a high trust factor of course.

I may create an account in future once I have some projects of my own to publish, probably months away at earliest though 👍

**Comment by georglauterbach** [comment]
> > **If someone else is willing to step in here, please let us know!** The only thing required is a DockerHub account, and a high trust factor of course.
> 
> I may create an account in future once I have some projects of my own to publish, probably months away at earliest though 👍

When you're ready, please let me know :) No pressure here; just so that we have a proper perspective.

**Comment by williamdes** [comment]
Hi team,
Could you please completely remove myself from this project. I intend to migrate to @stalwartlabs a mail server written in Rust. You will see me closing my issues when the migration is done. Thank you for maintaining this project over the years!

**Comment by georglauterbach** [comment]
> Hi team,
> 
> Could you please completely remove myself from this project. I intend to migrate to @stalwartlabs a mail server written in Rust. You will see me closing my issues when the migration is done. Thank you for maintaining this project over the years! 

I can do that too. Thank you for helping us :) I was recently made aware of this project as well, I will have a look at the project, too.

**Comment by casperklein** [comment]
> I'd be happy to invite you to the @docker-mailserver/core-administrators team, if you'd like to join.

👍 

> When it comes to DockerHub: I would very much like to have a +1 in the DockerHub organization in case I cannot access my account, and we need to do something. If someone else is willing to step in here, please let us know! The only thing required is a DockerHub account, and a high trust factor of course.

You can add me there too as a backup. I have an DH account and a high trust factor 😆

**Comment by georglauterbach** [comment]
> > I'd be happy to invite you to the @docker-mailserver/core-administrators team, if you'd like to join.
> 
> 👍
> 
> > When it comes to DockerHub: I would very much like to have a +1 in the DockerHub organization in case I cannot access my account, and we need to do something. If someone else is willing to step in here, please let us know! The only thing required is a DockerHub account, and a high trust factor of course.
> 
> You can add me there too as a backup. I have an DH account and a high trust factor 😆

Perfect; I invited you and removed @fbartels. @polarathene the organization on DockerHub is now full again (max 3 people; IDK why they have such a low limit..).
