### ISSUE TITLE
question: `SPAM_SUBJECT` what do the docs mean by "reducing the value of a subject prefix"?

### ISSUE THREAD

**Issue by ghnp5** [docker-mailserver/docker-mailserver#4048]
### Subject

Something else that requires developers attention

### Description

Hello,

The description of the new `SPAM_SUBJECT` variable says:

> NOTE: By default spam is delivered to a junk folder, reducing the value of a subject prefix for spam.

Can someone please clarify what does "reducing the value of a subject prefix" mean?

Thank you!

**Comment by ghnp5** [comment]
Humm.. not sure why I got a reply in Spanish, lol..
and, it did not help clarifying what "reducing" means.

**Comment by polarathene** [comment]
> The description of the new `SPAM_SUBJECT` variable says:
> 
> > NOTE: By default spam is delivered to a junk folder, reducing the value of a subject prefix for spam.
> 
> Can someone please clarify what does "reducing the value of a subject prefix" mean?

Perhaps we could word that better.

- The usefulness of `SPAM_SUBJECT` to prepend a string to the email title seemed redundant when it's already delivered into the Junk folder.
- There was no known good reasons where it was still valuable/worthwhile to use that `SPAM_SUBJECT` feature, since all mail in junk would start with that?
- If you don't have a separate junk folder, only then would it be helpful at distinguishing between legitimate and junk mail.

---

> not sure why I got a reply in Spanish

The AI assistant is usually helpful, but lately it's been replying in Spanish for some reason :(

**Comment by casperklein** [comment]
> If you don't have a separate junk folder,

For example, when you have a POP3 only setup and not using IMAP.

**Comment by ghnp5** [comment]
Thank you @polarathene (and @casperklein) for the clarifications!
I understand now what you tried to say with it. Yeah, it probably needs a bit of clarification, to avoid future confusion.

In my case, I have:
```
SPAMASSASSIN_SPAM_TO_INBOX=1
MOVE_SPAM_TO_JUNK=0
```

So `SPAM_SUBJECT` is still relevant to me.

Many thanks!!

(you can close this issue if you wish, or leave it open if you want to improve the description perhaps)

**Comment by polarathene** [comment]
> or leave it open if you want to improve the description

Do you have any suggestions?

Alternatively we can link to this issue as a way to provide additional clarity.

**Comment by ghnp5** [comment]
So, the problem is that "reducing the value" made me think that you were referring to a numeric value. So, I wasn't understanding what "numeric value could be reduced" on a "spam prefix". That's why the sentence wasn't making sense to me.

After your clarifications, this is what I suggest:

```
# NOTE: By default, spam is delivered to a junk folder, so this prefix may be redundant.
# However, this prefix can be useful if you set SPAMASSASSIN_SPAM_TO_INBOX=1 or MOVE_SPAM_TO_JUNK=0.
```

**Comment by polarathene** [comment]
> The description of the new `SPAM_SUBJECT` variable says:
> 
> > NOTE: By default spam is delivered to a junk folder, reducing the value of a subject prefix for spam.

I thought this was in the actual docs / changelog, not the demo `.env` that I'd like to remove at some point 😓 

https://github.com/docker-mailserver/docker-mailserver/blob/eb165ded65859794bbeca66e529a3466ceee298b/mailserver.env#L133-L136

> ![image](https://github.com/docker-mailserver/docker-mailserver/assets/5098581/07313206-3a7b-40fc-ba21-c44adcdeca04)

> ![image](https://github.com/docker-mailserver/docker-mailserver/assets/5098581/0b77b360-242d-4f79-b218-e5420de54d26)

Although there is a similar "reducing" statement but less likely to be as confusing (_just lacking context for the why_):

> ![image](https://github.com/docker-mailserver/docker-mailserver/assets/5098581/8e212dfe-cd74-4d95-928d-0c2d69a085ca)

---

I'll update the comment with your suggestion, thanks! :)

**Comment by ghnp5** [comment]
> I thought this was in the actual docs / changelog, not the demo .env that I'd like to remove at some point 😓

oh... I hope you don't, though! :)

It's very useful to me.

On every release, I do a comparison (side by side, in VS Code) of the demo and my config, which makes it extremely easier to see what's new, removed or changed.

I also do read the Release Notes, but it's already very stressful to read them to ensure I haven't missed anything, and at least having the demo ".env" file already helps a lot in ensuring I'm aware of what changed in the env variables.

**Comment by polarathene** [comment]
> which makes it extremely easier to see what's new, removed or changed.

This is why we have a `CHANGELOG.md` though? As you can see from the image above, it clearly had an ENV section and the changes applied there.

We also have a docs page for ENV which likewise could be compared.

---

One issue with `mailserver.env` is that unlike our docs page for ENV we're quite a bit more limited on how we can document settings there, and sometimes updates are not in sync or in this case of the same quality.

The main gripe I have with it though is bug reports. Users may only change a few ENV, but they only provide `compose.yaml` with a reference to that file. Then when we ask for them to show us the actual ENV they're using that is non-default we often still get a copy/paste of the whole file.

---

The `mailserver.env` won't be removed unless the ENV docs get another revision for a quick overview table. At that point you'd have very little benefit at knowing what changed between versions.

**Comment by ghnp5** [comment]
Thank you.
I understand what you say, and I agree with your points about when users report bugs.

I was looking now for the ENV docs you mentioned:
https://docker-mailserver.github.io/docker-mailserver/v14.0/config/environment/

Yeah, I guess that I could look to compare this page between the current version and the previous version, and see what's new.
That could work for me.

Thank you 👍🏻
