### ISSUE TITLE
feature request: Bring back the `dovecot-solr` package

### ISSUE THREAD

**Issue by erm967** [docker-mailserver/docker-mailserver#4052]
Please re-enable the solr plugin it is 1000 times better than xapian that keeps failing and uses way too much memory.

It's possible to use `solr9` that was updated 2 days ago and supports both arm64 and amd64, however it requires some work and it is not well described in dovecot documentation. I can write a better documentation if you need it.

The steps are: 

```bash
docker compose start solr (or up -d)
docker compose exec solr create -c dovecot
```

The dovecot database can be created also in the compose file like this:

```yaml
  solr:
    image: solr:latest
    container_name: solr
    volumes:
      - /path/to/solr-dovecot:/var/solr
    networks:
      - backend
    command:
      - solr-precreate
      - dovecot
    restart: always
```

Start it once than stop it: `docker compose stop solr`

Copy the schema file overwriting existing ones:

```bash
rm -f /path/to/solr-dovecot/data/dovecot/conf/schema.xml
rm -f /path/to/solr-dovecot/data/dovecot/conf/managed-schema
rm -f /path/to/solr-dovecot/data/dovecot/conf/solrconfig.xml
```

Download the correct schema from github: 

```bash
curl -o /path/to/solr-dovecot/data/dovecot/conf/schema.xml https://github.com/dovecot/core/raw/a9cbc569ad0d3d827d81bf954088987b2de1d27c/doc/solr-schema-9.xml
curl -o /path/to/solr-dovecot/data/dovecot/conf/solrconfig.xml 
  https://github.com/dovecot/core/raw/a9cbc569ad0d3d827d81bf954088987b2de1d27c/doc/solr-config-9.xml
```

The dovecot scheme requires the ICU plugin but the scheme in the dovecot repo references to an old version so `solrconfig.xml` needs to be patched like this:

```diff
--- /var/data/dms/config/dovecot/solr-dovecot/data/dovecot/conf/solrconfig.xml	2024-05-03 15:55:51.708712626 +0200
+++ solr-config-9.xml	2024-06-06 18:26:52.543138695 +0200
@@ -76,7 +76,7 @@
 
     <!-- Load ICU analyser -->
     <lib dir="/opt/solr/modules/analysis-extras/lib" regex="icu4j-70.1.jar"/>
-    <lib dir="/opt/solr/modules/analysis-extras/lib" regex="lucene-analysis-icu-9.10.0.jar"/>
+    <lib dir="/opt/solr/modules/analysis-extras/lib" regex="lucene-analysis-icu-9.8.0.jar"/>
   <!-- an exact 'path' can be used instead of a 'dir' to specify a
        specific jar file.  This will cause a serious error to be logged
        if it can't be loaded.
```

Using `solr9` works perfectly the only complication is the patch to `solrconfig.xml` so that it refers to the current library version.

_Originally posted by @erm967 in https://github.com/docker-mailserver/docker-mailserver/issues/4024#issuecomment-2152947388_

**Comment by erm967** [comment]
obviously the patch goes in the other side:
```
--- solr-config-9.xml	2024-06-06 18:26:52.543138695 +0200
+++ /var/data/dms/config/dovecot/solr-dovecot/data/dovecot/conf/solrconfig.xml	2024-05-03 15:55:51.708712626 +0200
@@ -76,7 +76,7 @@
 
     <!-- Load ICU analyser -->
     <lib dir="/opt/solr/modules/analysis-extras/lib" regex="icu4j-70.1.jar"/>
-    <lib dir="/opt/solr/modules/analysis-extras/lib" regex="lucene-analysis-icu-9.8.0.jar"/>
+    <lib dir="/opt/solr/modules/analysis-extras/lib" regex="lucene-analysis-icu-9.10.0.jar"/>
   <!-- an exact 'path' can be used instead of a 'dir' to specify a
        specific jar file.  This will cause a serious error to be logged
        if it can't be loaded.
```

**Comment by polarathene** [comment]
https://github.com/docker-mailserver/docker-mailserver/pull/4025#issuecomment-2151941002

You only need to add the package to the image. Is there a reason that is not ok?

The current guidance you've provided seems a bit prone to the type of maintenance issues that motivated dropping official Solr support.

If there is sufficient interest from users we can look at bringing the package back in. I'm not sure about bringing back docs if they are going to become outdated when software updates.

**Comment by polarathene** [comment]
> better than xapian that keeps failing and uses way too much memory.

Do you have more information regarding the failure and memory usage? When you say Solr is better is it actually better, or is Xapian not even comparable because you can't get it to run?

I think it was Docker v25 release this year that should fix a container runtime issue that can affect some software. It may also require Containerd v2.

To see if you have this problem try `docker run --rm -it alpine ash -c 'ulimit -Hn'

If the number is very large (1 billion or more) you have the bug. I know how to fix that, so if you're experiencing it let me know.

---

Otherwise, I'd suggest the advice I linked regarding `compose.yaml` with an inline `Dockerfile` (or external) that adds the package for you.

**Comment by erm967** [comment]
Yes I think I will follow your advice and just install the package, I was using dovecot native previously and ditched it because of the various problems it has. Yesterday I indexed all my mails with xapian but it was a bit frustrating.
```
core@localhost ~/docker-mailserver $ docker run --rm -it alpine ash -c 'ulimit -Hn'
1048576

```
I use dovecot as a mail archive that stores 12 years of emails, I use mdbox and emails are divided in various folders like year/argument, I also use the virtual plugin to create virtual folders 'All' '2023' '2022' 'bank' so I am able to search everywhere or where I need to. Now the biggest problem with xapian is that searching the All virtual folder is horribly slow, it probably depend on how it is implemented, with solr is superfast. The server has an I57500 and 48G ram, emails are stored on a sata ssd, and the os is fedora corelinux.
Yesterday I tried to give xapian a chance but even using
```
service indexer-worker {
vsz_limit = G
}
```
I had a few error like:
```
2024-06-07T08:19:55.359248+02:00 mail2 dovecot: indexer-worker: Error: cannot allocate memory for thread-local data: ABORT
2024-06-07T08:19:55.368807+02:00 mail2 dovecot: indexer-worker(ermanno@boiafauss.eu)<134030><KFxqDIimYmY1CwIAdg0WSg:IzKNDYimYmaOCwIAdg0WSg>: Fatal: master: service(indexer-worker): child 134030 returned error 127
```
Solr works flawlessly even using just 1G ram.

Also I had a lot of errors like this:
```
2024-06-07T08:23:18.096049+02:00 mail2 xapian-docswriter: DW #30 (INBOX,/var/mail/boiafauss.eu/ermanno/xapian-indexes/db_5ec7680f9bee34665e1a0b00dfc10470) -  Retrying (/var/mail/boiafauss.eu/ermanno/xapian-indexes/db_5ec7680f9bee34665e1a0b00dfc10470) from 
2024-06-07T08:23:18.477922+02:00 mail2 xapian-docswriter: DW #29 (INBOX,/var/mail/boiafauss.eu/ermanno/xapian-indexes/db_5ec7680f9bee34665e1a0b00dfc10470) - Can't add document1 : InvalidArgumentError - Term too long (> 245): XBDY ‌
```
So some email/attachments are not searchable with xapian.

Also I like to be able to search the attachments as well, and sometimes I receive scanned pages sent as jpg or pics of documents so I use fts_tika:full to decode all attachments,  it has also tesseract and will ocr and index images as well.
This happens during the indexing and with xapian hogging so much memory and slowing down the server tika times out frequently during the indexing:
`2024-06-06T16:28:41.553401+02:00 mail2 dovecot: indexer-worker(ermanno@boiafauss.eu)<2734><YFe1Gl3HYWauCgAAdg0WSg>: Error: fts_tika: PUT http://tika:9998/tika/ failed: Request timed out (Request queued 60.105 secs ago, 1 send attempts in 60.082 secs, 60.071 in http ioloop, 0.000 in other ioloops, connected 60.082 secs ago)
`
This doesn't happen with solr.

**Comment by erm967** [comment]
Ok so I will use user-patches.sh,  it works well, thank you.
```
core@localhost /var/data/dms/config $ cat user-patches.sh 
#!/bin/bash

# This user patches script runs right before starting the daemons.
# That means, all the other configuration is in place, so the script
# can make final adjustments.
# If you modify any supervisord configuration, make sure to run
# "supervisorctl update" or "supervisorctl reload" afterwards.

# For more information, see
# https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/override-defaults/user-patches/
if ! [ -e "/usr/lib/dovecot/modules/lib*_fts_solr_plugin.so" ]; then
    apt update
    apt install dovecot-solr
    rm -rf /var/lib/apt/lists/*
    echo 'dovecot-solr installed'
fi

echo 'user-patches.sh successfully executed'

```

**Comment by polarathene** [comment]
Thank you for sharing insights on why Solr is a much better solution for you, that's appreciated!

If there is continued interest in Solr, we can bring the package back.

---

I believe when Dovecot 2.4 / 3.0 is released they'll have `fts-flatcurve` by default without any plugin issues, which will remove the need for the [`fts-xapian`](https://github.com/grosjo/fts-xapian) plugin that has introduced some compatibility issues for us to support in the past.

I can't tell if that'll improve the experience with Xapian for you though (_it has improved integration than the `fts-xapian` plugin apparently, so it may not have those issues you ran into_).

Links for reference:
- https://github.com/slusarz/dovecot-fts-flatcurve
- https://github.com/slusarz/dovecot-fts-flatcurve/issues/19 (virtual mailboxes fixes vs solr)
- https://github.com/slusarz/dovecot-fts-flatcurve/issues/38 (attachment indexing/search fixes)
- https://doc.dovecot.org/3.0/configuration_manual/fts/flatcurve/
- https://doc.dovecot.org/configuration_manual/fts/solr/#fts-backend-solr
- https://doc.dovecot.org/configuration_manual/fts/

---

> `1048576`

That's all good 👍 

You can get some potential bugs (_if `ulimit -Sn` returns a value above `1024`_) for software relying on legacy syscalls like `select()` (_which wasn't that uncommon, I recall Redis for example had these in source_).

Memory/CPU resource usage spiking shouldn't be that bad (_some databases or daemonized services allocate resources that span the soft range of file descriptors_), if it was in the billion range that is when GB of RAM and long stalls (10-60 mins or more) can be encountered.

**Comment by erm967** [comment]
Maybe flatcurve will solve some problems exp. with ram usage, but it's still xapian. xapian indexes are stored in every folder and are huge, if the server has many big folders it need to open all those huge files and search through them, it might work for a small installation with few emails/folders.
I thing I am going to file a bug report with dovecot-core because solrconfig.xml no longer works with recent solr releases.

**Comment by Codelica** [comment]
FWIW, I'm trying to solve a repeatable Xapian DB corruption issue on a server [here](https://github.com/grosjo/fts-xapian/issues/163#top).  It sounds like things will be moving to Flatcurve, which I'll be interested to try. :)  

> You can get some potential bugs (if ulimit -Sn returns a value above 1024) for software relying on legacy syscalls like select() (which wasn't that uncommon, I recall Redis for example had these in source).

@polarathene is there any chance the issue you're talking about might be involved?  

```bash
root@cloud:mailserver # docker run --rm -it alpine ash -c 'ulimit -Sn'
1048576
```

```bash
root@cloud:mailserver # docker run --rm -it alpine ash -c 'ulimit -Hn'
1048576
```

**Comment by polarathene** [comment]
> @polarathene is there any chance the issue you're talking about might be involved?

Possibly. You'd have to look through the source code for syscalls to `select` IIRC.

- That syscall is limited to _file descriptors_ (FDs) of 0-1023 I think. It doesn't work properly when an FD exceeds that.
- Some software daemonizes by closing any open FDs it inherits. Many software approached this by iterating over the FD soft limit (_that `ulimit -Sn` shows_).
  - That would become 1,000x slower in your case, and in the known worse-case 1,000,000x (_a soft limit of "infinity" resolves to over a billion_).
  - Some software also introduced allocations during startup. Databases like MySQL were in the worst case allocating many GB of memory, but for your amount it was nothing too serious IIRC.

For `compose.yaml`, use the [`ulimits`](https://docs.docker.com/compose/compose-file/05-services/#ulimits) setting:

```yaml
# Add this to your DMS service settings, it will reset the soft limit to 1024
ulimits:
  nofile:
    soft: 1024
```

For `docker run`, use [`--ulimit`](https://docs.docker.com/reference/cli/docker/container/run/#ulimit) option:

```console
# Soft limit:
$ docker run --ulimit nofile=1024:524288 --rm -it alpine ash -c 'ulimit -Sn'
1024

# Hard limit:
$ docker run --ulimit nofile=1024:524288 --rm -it alpine ash -c 'ulimit -Hn'
524288
```

For context, the soft limit is how many file descriptors a process may have. Each process has it's own individual count, it is not a cumulative limit across processes.

Older Docker (_and similar CRI that adopted a "fix" years ago_) configured the init system (_like systemd service files_) to maximize both the soft and hard limit to workaround certain software failing to work with the low defaults (`1024:4096`), especially software that expected a much higher soft limit like databases, but for whatever reason didn't bother to raise the soft limit to a value at or below the hard limit. The initial reason was Docker daemon itself failing to perform some maintenance commands like removing hundreds of containers (_a minimal container uses around 4-6 FDs IIRC?_).

That didn't introduce any major regressions until a systemd release (early 2019 I think?) started rolling out which introduced a change to implicitly adjust limits to `1024:524288`, but it also raised another related limit to the 2^30 (over a billion) value. That was used by the kernel to determine what configuring these file descriptor limits to `infinity` in a service file would do. Prior to that, it would default to the `2^20` (_over a million value, `1048576`_) hard-coded into the kernel itself. Hence regressions in software were more noticeable but only seemed to occur in container environments.

Systemd keeps the soft limit at `1024` for legacy compatibility reasons. But software that knowingly needs more should request to raise it at runtime, or a user can explicitly raise it themselves. Doing so at the container or Docker daemon level is ill-advised though since that applies it to all processes, but that's what was being done with the init configs distributed with CRIs like Docker Engine. I did the investigation into this and pushed the PR forward for Docker, so if you run a modern release you shouldn't have that problem anymore and you should get the default expected `1024:524288`.

Prior to that, you would find like your results either `2^20` or `2^30` for both soft and hard limits. The value you got depended on distro. Debian (and thus Ubuntu IIRC) would explicitly patch out the systemd change to adjust that kernel tunable, keeping `infinity` to resolve to `2^20`. So in your case no CPU or RAM resource issues should be occurring, only the `select()` syscall AFAIK.

Try reproduce with the soft limit adjusted to 1024 like shown above, and if you don't experience the issue anymore let me know. Otherwise this is not the reason 😅

**Comment by Codelica** [comment]
Wow! Thank you for the epic write-up. 👍  I will definitely give this a try when I get a chance this week.  One thing that seems curious though:

>  I did the investigation into this and pushed the PR forward for Docker, so if you run a modern release you shouldn't have that problem anymore and you should get the default expected 1024:524288.

I feel like this system is pretty current (fully updated Ubuntu 24 host), but I don't seem to see the expected values.

**Host:**

```bash
root@cloud:~ # lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04 LTS
Release:	24.04
Codename:	noble
root@cloud:~ # ulimit -Sn
1024
root@cloud:~ # ulimit -Hn
1048576
root@cloud:~ # cat /etc/sysctl.conf |grep 'fs.'
root@cloud:~ #
```

**Docker:**

```bash
root@cloud:~ # docker --version
Docker version 27.0.2, build 912c1dd
root@cloud:~ # containerd --version
containerd containerd.io 1.7.18 ae71819c4f5e67bb4d5ae76a6b735f29cc25774e
root@cloud:~ # docker run --rm -it alpine ash -c 'ulimit -Sn'
1048576
root@cloud:~ # docker run --rm -it alpine ash -c 'ulimit -Hn'
1048576
```

Regardless, I'll report back after limiting things.  Thanks again!

**Comment by Codelica** [comment]
@polarathene I didn't mean to take over this issue, but did give the limits a quick try, so I'll give one final message with the results.  Not really sure this is an "issue" for docker-mailserver anyway, unless a more recent version of fts-xapian fixes it.  (1.7.13 was suggested)

I added the following to my compose for docker-mailserver and verified it was honored in the container:

```yaml
    ulimits:
      nofile:
        soft: 1024
        hard: 524288
```

And used the following config for the plugin:

```
mail_plugins = $mail_plugins fts fts_xapian

plugin {
    fts = xapian
    fts_xapian = partial=3 full=20 verbose=1

    fts_autoindex = yes
    fts_enforced = yes
}

service indexer-worker {
    # limit size of indexer-worker RAM usage, ex: 512MB, 1GB, 2GB
    vsz_limit = 2GB
}
```
 
I had cleared out Xapian data for this problem account and kicked off indexing via `docker exec mailserver doveadm index -A \*`.  After about 1GB or so of indexes were written for the user, problems started -- core dumps.  First example log section:

```
...
2024-07-01T16:15:15.959350-06:00 mail dovecot: indexer-worker(theuser@thedomain.com)<4202><M7k/ENwog2ZiEAAAdz0kug:CqkCK9wog2ZqEAAAdz0kug>: FTS Xapian: Free memory = 2218 MB
2024-07-01T16:15:15.959359-06:00 mail dovecot: indexer-worker(theuser@thedomain.com)<4202><M7k/ENwog2ZiEAAAdz0kug:CqkCK9wog2ZqEAAAdz0kug>: FTS Xapian: New doc ready to index 10275
2024-07-01T16:15:15.959364-06:00 mail dovecot: indexer-worker(theuser@thedomain.com)<4202><M7k/ENwog2ZiEAAAdz0kug:CqkCK9wog2ZqEAAAdz0kug>: FTS Xapian: Cleanup 0 : Active : DW #3325 (INBOX,/var/mail/thedomain.com/theuser/xapian-indexes/db_4bdd452fa0f87a6689d80e00773d24ba) -  pos=12 remaining docs=0 terminated=0
2024-07-01T16:15:15.959368-06:00 mail dovecot: indexer-worker(theuser@thedomain.com)<4202><M7k/ENwog2ZiEAAAdz0kug:CqkCK9wog2ZqEAAAdz0kug>: FTS Xapian: Cleanup 1 : Active : DW #3330 (INBOX,/var/mail/thedomain.com/theuser/xapian-indexes/db_4bdd452fa0f87a6689d80e00773d24ba) -  pos=12 remaining docs=2 terminated=0
2024-07-01T16:15:15.959374-06:00 mail dovecot: indexer-worker(theuser@thedomain.com)<4202><M7k/ENwog2ZiEAAAdz0kug:CqkCK9wog2ZqEAAAdz0kug>: FTS Xapian: Cleanup 2 : Active : DW #3329 (INBOX,/var/mail/thedomain.com/theuser/xapian-indexes/db_4bdd452fa0f87a6689d80e00773d24ba) -  pos=12 remaining docs=0 terminated=0
2024-07-01T16:15:15.959378-06:00 mail dovecot: indexer-worker(theuser@thedomain.com)<4202><M7k/ENwog2ZiEAAAdz0kug:CqkCK9wog2ZqEAAAdz0kug>: FTS Xapian: Cleanup 3 : Active : DW #3328 (INBOX,/var/mail/thedomain.com/theuser/xapian-indexes/db_4bdd452fa0f87a6689d80e00773d24ba) -  pos=13 remaining docs=1 terminated=0
2024-07-01T16:15:16.159609-06:00 mail dovecot: indexer-worker(theuser@thedomain.com)<4202><M7k/ENwog2ZiEAAAdz0kug:CqkCK9wog2ZqEAAAdz0kug>: FTS Xapian: Cleanup 0 : Active : DW #3325 (INBOX,/var/mail/thedomain.com/theuser/xapian-indexes/db_4bdd452fa0f87a6689d80e00773d24ba) -  pos=12 remaining docs=0 terminated=0
2024-07-01T16:15:16.159624-06:00 mail dovecot: indexer-worker(theuser@thedomain.com)<4202><M7k/ENwog2ZiEAAAdz0kug:CqkCK9wog2ZqEAAAdz0kug>: FTS Xapian: Cleanup 1 : Active : DW #3330 (INBOX,/var/mail/thedomain.com/theuser/xapian-indexes/db_4bdd452fa0f87a6689d80e00773d24ba) -  pos=12 remaining docs=2 terminated=0
2024-07-01T16:15:16.159628-06:00 mail dovecot: indexer-worker(theuser@thedomain.com)<4202><M7k/ENwog2ZiEAAAdz0kug:CqkCK9wog2ZqEAAAdz0kug>: FTS Xapian: Cleanup 2 : Active : DW #3329 (INBOX,/var/mail/thedomain.com/theuser/xapian-indexes/db_4bdd452fa0f87a6689d80e00773d24ba) -  pos=12 remaining docs=0 terminated=0
2024-07-01T16:15:16.159633-06:00 mail dovecot: indexer-worker(theuser@thedomain.com)<4202><M7k/ENwog2ZiEAAAdz0kug:CqkCK9wog2ZqEAAAdz0kug>: FTS Xapian: Cleanup 3 : Active : DW #3328 (INBOX,/var/mail/thedomain.com/theuser/xapian-indexes/db_4bdd452fa0f87a6689d80e00773d24ba) -  pos=13 remaining docs=1 terminated=0
2024-07-01T16:15:16.166027-06:00 mail xapian-docswriter: DW #828 (Family,/var/mail/thedomain.com/theuser/xapian-indexes/db_4093ea370ef97a6689d80e00773d24ba) -  Doc 2481 Size(text)=2816 Stems=640517 : Populate 2368 / 2816 Header=XBDY TextLength=97
2024-07-01T16:15:16.168016-06:00 mail xapian-docswriter: DW #828 (Family,/var/mail/thedomain.com/theuser/xapian-indexes/db_4093ea370ef97a6689d80e00773d24ba) -  Doc 2481 Size(text)=2816 Stems=640519 : Populate 2367 / 2816 Header=XBDY TextLength=7758
2024-07-01T16:15:16.247869-06:00 mail xapian-docswriter: DW #3328 (INBOX,/var/mail/thedomain.com/theuser/xapian-indexes/db_4bdd452fa0f87a6689d80e00773d24ba) - Can't add document2 : std::exception
2024-07-01T16:15:16.247885-06:00 mail xapian-docswriter: DW #3328 (INBOX,/var/mail/thedomain.com/theuser/xapian-indexes/db_4bdd452fa0f87a6689d80e00773d24ba) -  Retrying (/var/mail/thedomain.com/theuser/xapian-indexes/db_4bdd452fa0f87a6689d80e00773d24ba) from std::exception
2024-07-01T16:15:16.355411-06:00 mail xapian-docswriter: DW #828 (Family,/var/mail/thedomain.com/theuser/xapian-indexes/db_4093ea370ef97a6689d80e00773d24ba) -  Doc 2481 Size(text)=2816 Stems=642168 : Populate 2366 / 2816 Header=XBDY TextLength=19
2024-07-01T16:15:16.355940-06:00 mail xapian-docswriter: DW #828 (Family,/var/mail/thedomain.com/theuser/xapian-indexes/db_4093ea370ef97a6689d80e00773d24ba) -  Doc 2481 Size(text)=2816 Stems=642168 : Populate 2365 / 2816 Header=XBDY TextLength=7742
2024-07-01T16:15:16.483721-06:00 mail xapian-docswriter: DW #828 (Family,/var/mail/thedomain.com/theuser/xapian-indexes/db_4093ea370ef97a6689d80e00773d24ba) -  Doc 2481 Size(text)=2816 Stems=643001 : Populate 2364 / 2816 Header=XBDY TextLength=84
2024-07-01T16:15:16.486211-06:00 mail xapian-docswriter: DW #828 (Family,/var/mail/thedomain.com/theuser/xapian-indexes/db_4093ea370ef97a6689d80e00773d24ba) -  Doc 2481 Size(text)=2816 Stems=643001 : Populate 2363 / 2816 Header=XBDY TextLength=7695
2024-07-01T16:15:16.600761-06:00 mail xapian-docswriter: DW #828 (Family,/var/mail/thedomain.com/theuser/xapian-indexes/db_4093ea370ef97a6689d80e00773d24ba) -  Doc 2481 Size(text)=2816 Stems=643148 : Populate 2362 / 2816 Header=XBDY TextLength=76
2024-07-01T16:15:16.601712-06:00 mail xapian-docswriter: DW #828 (Family,/var/mail/thedomain.com/theuser/xapian-indexes/db_4093ea370ef97a6689d80e00773d24ba) -  Doc 2481 Size(text)=2816 Stems=643148 : Populate 2361 / 2816 Header=XBDY TextLength=7733
2024-07-01T16:15:16.630756-06:00 mail dovecot: indexer-worker(theuser@thedomain.com)<4202><M7k/ENwog2ZiEAAAdz0kug:CqkCK9wog2ZqEAAAdz0kug>: Fatal: master: service(indexer-worker): child 4202 killed with signal 11 (core dumped)
2024-07-01T16:15:16.718714-06:00 mail dovecot: indexer-worker(theuser@thedomain.com)<11621><8HjNCv4og2ZiEAAAdz0kug:3ZjMKnQqg2ZlLQAAdz0kug>: FTS Xapian: Starting with partial=3 full=20 verbose=1 lowmemory=250 MB vs freemem=3858 MB
2024-07-01T16:15:16.720705-06:00 mail dovecot: indexer-worker(theuser@thedomain.com)<11621><8HjNCv4og2ZiEAAAdz0kug:3ZjMKnQqg2ZlLQAAdz0kug>: FTS Xapian: Set box 'Junk' (c0c90b10a4f87a6689d80e00773d24ba)
2024-07-01T16:15:16.720723-06:00 mail dovecot: indexer-worker(theuser@thedomain.com)<11621><8HjNCv4og2ZiEAAAdz0kug:3ZjMKnQqg2ZlLQAAdz0kug>: FTS Xapian: 'Junk' (/var/mail/thedomain.com/theuser/xapian-indexes/db_c0c90b10a4f87a6689d80e00773d24ba) indexes do not exist. Initializing DB
2024-07-01T16:15:16.722278-06:00 mail dovecot: indexer-worker(theuser@thedomain.com)<11621><8HjNCv4og2ZiEAAAdz0kug:3ZjMKnQqg2ZlLQAAdz0kug>: FTS Xapian: Opening DB (RO) /var/mail/thedomain.com/theuser/xapian-indexes/db_c0c90b10a4f87a6689d80e00773d24ba
2024-07-01T16:15:16.725666-06:00 mail dovecot: indexer-worker(theuser@thedomain.com)<11621><8HjNCv4og2ZiEAAAdz0kug:3ZjMKnQqg2ZlLQAAdz0kug>: FTS Xapian: Set box 'Junk' (c0c90b10a4f87a6689d80e00773d24ba)
2024-07-01T16:15:16.725677-06:00 mail dovecot: indexer-worker(theuser@thedomain.com)<11621><8HjNCv4og2ZiEAAAdz0kug:3ZjMKnQqg2ZlLQAAdz0kug>: FTS Xapian: Opening DB (RO) /var/mail/thedomain.com/theuser/xapian-indexes/db_c0c90b10a4f87a6689d80e00773d24ba
2024-07-01T16:15:16.726927-06:00 mail dovecot: indexer-worker(theuser@thedomain.com)<11621><8HjNCv4og2ZiEAAAdz0kug:3ZjMKnQqg2ZlLQAAdz0kug>: FTS Xapian: Set box 'Junk' (c0c90b10a4f87a6689d80e00773d24ba)
2024-07-01T16:15:16.727019-06:00 mail dovecot: indexer-worker(theuser@thedomain.com)<11621><8HjNCv4og2ZiEAAAdz0kug:3ZjMKnQqg2ZlLQAAdz0kug>: FTS Xapian: Free memory = 3858 MB
... continues
```

So I can only assume that's when the index db corruption occurs and all best are off from there on.

**Comment by polarathene** [comment]
> I feel like this system is pretty current (fully updated Ubuntu 24 host), but I don't seem to see the expected values.

You might need to ensure you also have containerd v2. I'm not sure if that was released yet or bundled with the Docker Engine packages.

It's also possible that either Docker or Containerd projects reverted the fix in their service files... I'll check.

- Docker Engine still has the fix since v25: https://github.com/moby/moby/commit/c8930105bc9fc3c1a8a90886c23535cc6c41e130
- containerd v2 merged the fix 10 months ago, but v2 still not yet released: https://github.com/containerd/containerd/pull/8924

So you'll likely have a `containerd.service` file that still sets `infinity`, you would need to use a systemd unit [drop-in override](https://github.com/moby/moby/issues/45436#issuecomment-1534520189) so [the relevant setting is unset](https://github.com/polarathene/containerd/commit/3ca39ef01608fdd44245c0173bf071682b3bfe3c), or to set it to `1024:524288` (higher hard limit is ok).

Otherwise, just set container limits explicitly per container like discussed earlier, or wait until that containerd v2 release lands.

---

> I had cleared out Xapian data for this problem account and kicked off indexing via `docker exec mailserver doveadm index -A \*`. After about 1GB or so of indexes were written for the user, problems started -- core dumps

Oh ok, so not a soft limits issue then.

I'd be interested to know if this occurs with the successor flatcurve, which is still xapian based.

If someone else can reproduce your failure, I have no issue with bringing back `dovecot-solr` package 👍

**Comment by Codelica** [comment]
@polarathene I lied, one last message.   It turns out there is a [regression](https://github.com/grosjo/fts-xapian/issues/163#issuecomment-2201553781) in fts-xapian 1.7.12 which DMS v14.0 uses.  I edited `target/scripts/build/compile.sh` and the `dockerfile` to use 1.7.13 as suggested, built a test image and it completed all 20+ GB of mail indexes for the user.  It also cleaned up a variety of other fts indexing errors I was seeing, and seems quicker overall.  Definitely worth a look for V14.x.

**Comment by polarathene** [comment]
> Definitely worth a look for V14.x.

Done!: https://github.com/docker-mailserver/docker-mailserver/pull/4095

Thanks for troubleshooting that and letting us know ❤️

**Comment by ihortarasenko** [comment]
Please bring back `dovecot-solr` package. The solr integration has been working flawlessly in v13 for years, but it's too complicated to get it work in v14 (at least, for me). 

I'm using this `user-patches.sh`script (https://github.com/docker-mailserver/docker-mailserver/issues/4052#issuecomment-2154300936) but keep getting various errors at the container startup. It seems my deployment is hitting both breaking changes related to Dovecot in v14. And I can't figure out which one is preventing dovecot to start.

P.S. Thanks a lot for maintaining this amazing project!

```
2024-06-22 12:22:12-07:00 INFO  start-mailserver.sh: Checking configuration
2024-06-22 12:22:12-07:00 INFO  start-mailserver.sh: Configuring mail server
sievec: Fatal: Plugin 'fts_solr' not found from directory /usr/lib/dovecot/modules
chown: cannot access '/usr/lib/dovecot/sieve-global/after/spam_to_junk.svbin': No such file or directory
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
Get:2 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Get:4 http://deb.debian.org/debian bookworm/main arm64 Packages [8685 kB]
Get:5 http://deb.debian.org/debian bookworm-updates/main arm64 Packages [13.7 kB]
Get:7 http://deb.debian.org/debian-security bookworm-security/main arm64 Packages [157 kB]
Get:6 https://rspamd.com/apt-stable bookworm InRelease [3161 B]
Get:8 https://rspamd.com/apt-stable bookworm/main arm64 Packages [1569 B]
Fetched 9115 kB in 1s (6782 kB/s)
Reading package lists...
Building dependency tree...
Reading state information...
1 package can be upgraded. Run 'apt list --upgradable' to see it.
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  dovecot-solr
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 1374 kB of archives.
After this operation, 1449 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bookworm/main arm64 dovecot-solr arm64 1:2.3.19.1+dfsg1-2.1 [1374 kB]
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
Fetched 1374 kB in 0s (5915 kB/s)
Selecting previously unselected package dovecot-solr.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 20539 files and directories currently installed.)
Preparing to unpack .../dovecot-solr_1%3a2.3.19.1+dfsg1-2.1_arm64.deb ...
Unpacking dovecot-solr (1:2.3.19.1+dfsg1-2.1) ...
Setting up dovecot-solr (1:2.3.19.1+dfsg1-2.1) ...
Processing triggers for dovecot-core (1:2.3.19.1+dfsg1-2.1) ...
invoke-rc.d: WARNING: No init system and policy-rc.d missing! Defaulting to block.
dovecot-solr installed
Fatal: Dovecot is not running (read from /run/dovecot/master.pid)
user-patches.sh successfully executed
```

**Comment by polarathene** [comment]
> it's too complicated to get it work in v14 (at least, for me).

It's really not, this is all you need to do ( _Adapted from:_ https://github.com/docker-mailserver/docker-mailserver/pull/4025#issuecomment-2174716418 )

```yaml
# Edit your `compose.yaml` for DMS:
services:
  dms:
    # This setting now refers to the default image tag for the image built below:
    image: local/dms:14.0
    # Local build, no need to try pull `image` remotely:
    pull_policy: build
    # Inlined Dockerfile, your `compose.yaml` has all you need to extend DMS, no extra files needed:
    build:
      dockerfile_inline: |
        FROM docker.io/mailserver/docker-mailserver:14.0
        RUN apt-get update && apt-get install dovecot-solr
```

---

The [current `edge` version of our docs](https://docker-mailserver.github.io/docker-mailserver/edge/examples/tutorials/dovecot-solr/#add-the-required-dovecot-solr-package) also cover that and the alternative `user-patches.sh` method:

> ![image](https://github.com/docker-mailserver/docker-mailserver/assets/5098581/2282d61b-c18f-4edf-bfce-706be7dde462)

---

If you still think DMS should have the `dovecot-solr` package included, please also [👍 the request](https://github.com/docker-mailserver/docker-mailserver/issues/4052#issue-2338715252) so maintainers have better visibility of interest.

The workarounds as shown above are quite minimal, considering you already have to do extra work to run and maintain Solr integration that DMS never handled.

---

> It seems my deployment is hitting both breaking changes in v14 related to Dovecot. And I'm finding it difficult to determine which one prevents dovecot from starting.

As for your actual issue, DMS only added the `dovecot-solr` package.. there was no additional integration. You're not going to get a better experience than the above with ARM64 apparently: https://github.com/docker-mailserver/docker-mailserver/pull/4025#issuecomment-2171765054

So you'll need to remain on v13.3, move away from either Solr / ARM64, or get the problem resolved upstream and then wait until that package is available to Debian (_could be quite a while in my experience_).
