### ISSUE TITLE
question: Why does `DEFAULT_RELAY_HOST` fail to authenticate? (DMS release prior to v14)

### ISSUE THREAD

**Issue by Zephyrante** [docker-mailserver/docker-mailserver#4130]
### Subject

I would like some feedback concerning a use case

### Description

Hi there,

I have been using docker-mailserver for arround a year now and noticed that the emails that go through default relay are not going out, im using aws ses as a relay and when i set it up also as DEFAULT_RELAY_HOST in the .env file i get credentials error:

```
Jul 23 09:11:00 mail postfix/smtp[54905]: 2C0A14087210: to=<xxxx@xxxxx.es>, relay=email-smtp.eu-west-1.amazonaws.com[52.18.165.220]:587, delay=0.53, delays=0.02/0.06/0.43/0.03, dsn=5.0.0, status=bounced (host email-smtp.eu-west-1.amazonaws.com[52.18.165.220] said: 530 Authentication required (in reply to MAIL FROM command))
```

From what i gathered i had to do some extra setup, i tried this without any success; [Postfix Configuration](https://www.cloudpanel.io/tutorial/how-to-configure-amazon-ses-with-postfix/)

Any hint on what am i not doing right?

Thanks in advance, have a great day

Regards
Luis

**Comment by polarathene** [comment]
> Any hint on what am i not doing right?

Use v14 of DMS:

https://github.com/docker-mailserver/docker-mailserver/blob/32c0a346fcec975ba133443d98e3a1e7c0d78714/CHANGELOG.md?plain=1#L140-L143

**Comment by Zephyrante** [comment]
> > Any hint on what am i not doing right?
> 
> Use v14 of DMS:
> 
> https://github.com/docker-mailserver/docker-mailserver/blob/32c0a346fcec975ba133443d98e3a1e7c0d78714/CHANGELOG.md?plain=1#L140-L143
> 
> For reference, here is a working demonstration of the relay host feature:
> 
> [#4136 (comment)](https://github.com/docker-mailserver/docker-mailserver/issues/4136#issuecomment-2253693490)

Thx for the info, ill check how painfull it is to go from v12 to v14

**Comment by polarathene** [comment]
> from v12 to v14

If it's an issue, you can try without `DEFAULT_RELAY_HOST` and use the other two separate ENV that are equivalent. There may be some bugs though that were resolved since.
