### ISSUE TITLE
other: Proposal to change Getmail working directory

### ISSUE THREAD

**Issue by mazzz1y** [docker-mailserver/docker-mailserver#4149]
### Subject

I would like some feedback concerning a use case

### Description

As a continuation of the discussion in: https://github.com/docker-mailserver/docker-mailserver/pull/4018

1) Currently, getmail uses the directory `/tmp/docker-mailserver/getmail` to store its state about the current sync status: https://getmail6.org/faq.html#faq-about-oldmail
  In my opinion, this directory should be changed to `/var/mail-state/getmail` or something similar. "State" data should not be stored inside the /tmp/docker-mailserver directory because this "config" directory is often included in a Git repository by users.

2) As an additional improvement for managing getmail, I propose changing the path of the getmail configuration files `getmail-<ID>.cf` to a subdirectory under /tmp/docker-mailserver/getmail, instead of storing the getmail configuration in the root of /tmp/docker-mailserver.
  I have many getmail configs, and they're making a mess in the /tmp/docker-mailserver folder.

**Comment by polarathene** [comment]
I made a mistake in [earlier comment](https://github.com/docker-mailserver/docker-mailserver/pull/4018#issuecomment-2261494000) thinking `/var/mail-state` mapped to directories  of `/var/run/` not [`/var/lib/`](https://github.com/docker-mailserver/docker-mailserver/blob/2f8ad142eccfe3d6291373629c5b1dbf89b71f52/target/scripts/startup/setup.d/mail_state.sh#L20-L32), as I thought this was mostly state that could be discarded (_I guess with getmail state that's true too, perhaps similar to redis DB for rspamd_).

Fail2Ban is also keeping track of banned IPs I think? It might be helpful to also better document awareness of the more valuable state the volume handles.

I think my reason for dropping the `/var/mail-state` location was that it was never used in previous releases if you had a bind volume for that location, the symlink wasn't valid. I don't recall the docs mentioning such a location either, and in the PR I note that it seemed to be where mail was stored if `getmail` was not configured to hand it off to Dovecot.

Am I mistaken about that? I'm not sure if I ran it locally to check. Or is the mail content part of those oldmail files and always stored regardless of if sending the pulled mail to Dovecot?

---

> 1. Currently, getmail uses the directory `/tmp/docker-mailserver/getmail` to store its state about the current sync status: https://getmail6.org/faq.html#faq-about-oldmail

Quoting link for convenience:

> _**What are these `oldmail*` files? Can I delete or trim them?**_
> _`getmail` stores its state - its "memory" of what it has seen in your POP/IMAP account - in the `oldmail` files._
> 
> _**Do NOT delete or edit these files.** You'll make getmail re-retrieve all your old mail, or even prevent getmail from running. The files are tiny by modern storage standards; you could have a million of these files and still not have to worry about the disk space they take up for a thousand years._

---

> 2\. As an additional improvement for managing getmail, I propose changing the path of the getmail configuration files `getmail-<ID>.cf` to a subdirectory under /tmp/docker-mailserver/getmail, instead of storing the getmail configuration in the root of /tmp/docker-mailserver.

Yeah that's fine. This sort of improvement is something I'd like to see for quite a few files with the Config Volume. `postfix-accounts.cf` and related files should really be under a common `postfix/` subdir with just the suffix as the filename (`accounts.cf`). Might consider this for v15.

**Comment by casperklein** [comment]
> Or is the mail content part of those oldmail files and always stored regardless of if sending the pulled mail to Dovecot?

I think it works like that (not tested).

Another thing I learned while reading about getmail(6):

There is [getmail](https://pyropus.ca./software/getmail/), currently in version 5.X, which is still maintained. However it's not ported to python3 yet and requires python2. [getmail6](https://getmail6.org/) is a getmail fork ported to python3. There might be confusion, that getmail6 is getmail version 6. But that's wrong. The original author of getmail is not happy* about the forks name getmail6. He requested a name change, but that was declined by the getmail6 fork author.
We should make clear, that we are using getmail6 (docs, directory names).

*Whole discussion: https://marc.info/?l=getmail&m=163525929112722&w=2

**Comment by mazzz1y** [comment]
> Or is the mail content part of those oldmail files and always stored regardless of if sending the pulled mail to Dovecot?

Guys, I think there's a bit of a misunderstanding. The "oldmail" files contain only the IDs of processed emails to avoid reprocessing them upon the next trigger of getmail. These files do not contain the content of the emails.

The ID is not stored in the oldmail file until the emails are successfully sent to Dovecot or another "retriever" (in terms of getmail).

Getmail creates one oldmail file per configuration.

**Comment by casperklein** [comment]
I overlooked the "content" part in the quoted sentence. I sure meant, those files only include the IDs of already processed files, not their content of course.

**Comment by polarathene** [comment]
> We should make clear, that we are using getmail6 (docs, directory names).

@casperklein Is this still something you want to pursue?

**Comment by casperklein** [comment]
Nope, TBH I don't think it's worth the effort. I also noticed some inconsistencies, for example getmail6 tags itself as just getmail when logging to syslog. Sticking to the "getmail" wording and linking to the getmail6 docs should be fine.

**Comment by polarathene** [comment]
> for example getmail6 tags itself as just getmail when logging to syslog.

Pretty sure that is due to [`--tag getmail`](https://github.com/docker-mailserver/docker-mailserver/pull/4156/files#diff-d3b48ace5764dc8d3913568f3f701d41fb4c26fe6120b549eed72afa22d6b093R14-R16)? Getmail has no involvement in `logger`

**EDIT:** Oh right, the syslog output feature offered by getmail itself 🤔

**Comment by casperklein** [comment]
> Pretty sure that is due to [`--tag getmail`](https://github.com/docker-mailserver/docker-mailserver/pull/4156/files#diff-d3b48ace5764dc8d3913568f3f701d41fb4c26fe6120b549eed72afa22d6b093R14-R16)?

I switched from getmail6 to getmail on purpose, see the commit (message) [`c0ac4f5` (#4156)](https://github.com/docker-mailserver/docker-mailserver/pull/4156/commits/c0ac4f5fedff949ca68ec95c4d037bb69638744f)

> **EDIT:** Oh right, the syslog output feature offered by getmail itself 🤔

Yeah. The fork didn't change it's name across the code/docu. It calls itself getmail version 6, but that's wrong.

That's really odd (for the users). Forking a project and renaming it to something else is normally fine. But forking a project and just releasing a new version, while the original is still in development, really messes things up. When the original getmail releases a version 6, the chaos will be perfect 😆
