### ISSUE TITLE
bug report: configured dovecot stats/metrics are always 0

### ISSUE THREAD

**Issue by litetex** [docker-mailserver/docker-mailserver#4164]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

I tried to configure dovecot [statistics](https://doc.dovecot.org/configuration_manual/stats/)/[metrics](https://doc.dovecot.org/configuration_manual/stats/openmetrics/) inside DMS like this
``dovecot.cf``
```
// Proxying code from https://docker-mailserver.github.io/docker-mailserver/latest/examples/tutorials/mailserver-behind-proxy/#dms-postfix-dovecot (last infobox)
haproxy_trusted_networks=192.168.0.0/16 172.16.0.0/12 10.0.0.0/8

service imap-login {
  inet_listener imaps-proxied {
    haproxy = yes
    port = 10993
    ssl = yes
  }
}

// ...

// Example as described inside https://doc.dovecot.org/configuration_manual/stats/openmetrics/
service stats {
  inet_listener http {
    port = 9900
  }
}

metric auth_success {
  filter = (event=auth_request_finished AND success=yes)
}

metric imap_command {
  filter = event=imap_command_finished
  group_by = cmd_name tagged_reply_state
}

metric smtp_command {
  filter = event=smtp_server_command_finished
  group_by = cmd_name status_code duration:exponential:1:5:10
}

metric mail_delivery {
  filter = event=mail_delivery_finished
  group_by = duration:exponential:1:5:10
}
```

However the metrics are always the same and never change to other values.

I also tried to manually run ``doveadm stats dump`` however this results in:
``Fatal: net_connect_unix(/run/dovecot/stats-reader) failed: No such file or directory``

### 👟 Reproduction Steps

See description

### 🐋 DMS Version

14.0.0

### 💻 Operating System and Architecture

irrelevant

**Comment by polarathene** [comment]
We disabled stats intentionally IIRC:
- https://github.com/docker-mailserver/docker-mailserver/pull/2292
- https://github.com/docker-mailserver/docker-mailserver/pull/2336

I seem to have summarized the reason here: https://github.com/docker-mailserver/docker-mailserver/pull/2292#issuecomment-1200034250

> The new stats were disabled to avoid the error log noted at the start of this PR I think. If you go through my responses here, I do seem to suggest that it [may have been fixable via adjusting permissions correctly](https://github.com/docker-mailserver/docker-mailserver/pull/2292#issuecomment-967770593), followed by [this reference / snippet](https://github.com/docker-mailserver/docker-mailserver/pull/2292#issuecomment-985115787) which may have been the only required changes (_instead of the `mode = 0` this PR introduced_), in addition to `stats_writer_socket_path=` which was noted as a way to disable the writer.

> I don't think we ever had official support for stats with the project, so the intention was to make those opt-in instead for users that specifically needed it.
> 
> If there was enough interest expressed for such we could add some toggle support, otherwise our usual advice is to defer to documenting for others how to leverage `user-patches.sh` to make the change.

---

The config that disables the plugin is here:

https://github.com/docker-mailserver/docker-mailserver/blob/cb963a9a8b68c4aa8191cf40c67162a5eb3043e0/target/dovecot/60-stats.conf#L1-L13

If you remove or modify that, you should be able to configure stats I think?

**Comment by litetex** [comment]
Thank you for the quick and details feedback :)

Yes I indeed didn't know about this. I will try it out later once I have some spare time.

Further improvement idea: Add a short mention somewhere inside the docs (FAQ for example), so that other people looking for the same question get the answer faster :)

**Comment by polarathene** [comment]
> Add a short mention somewhere inside the docs (FAQ for example), so that other people looking for the same question get the answer faster :)

You are the first user to show interest in this, we'd welcome a contribution to the docs, or a follow-up comment with the configuration changes you end up with to use the feature as intended (docs can then link to that).

**Comment by litetex** [comment]
Okay so I managed to get stats when doing this:
1. Add the following to ``user-patches.sh``
```bash
# Reenable stats
rm -f /etc/dovecot/conf.d/60-stats.conf
sed -i '/stats_writer_socket_path=/d' /etc/dovecot/dovecot.conf
```
2. Inside ``dovecot.cf`` add:
```bash
// See also https://doc.dovecot.org/configuration_manual/stats/openmetrics/
service stats {
  inet_listener http {
    port = 9900
  }
}

// Demo metrics
metric auth_success {
  filter = (event=auth_request_finished AND success=yes)
}

metric imap_command {
  filter = event=imap_command_finished
  group_by = cmd_name tagged_reply_state
}

metric smtp_command {
  filter = event=smtp_server_command_finished
  group_by = cmd_name status_code duration:exponential:1:5:10
}

metric mail_delivery {
  filter = event=mail_delivery_finished
  group_by = duration:exponential:1:5:10
}
```

Works like a charm now ^^
