### ISSUE TITLE
bug report: start-mailserver.sh says the alias will not be added twice

### ISSUE THREAD

**Issue by pitilux** [docker-mailserver/docker-mailserver#4170]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

Hi DMS maintainers,

I'm helping manage a DMS instance and for a while we've seen the following line in our log at startup:
```
WARN  start-mailserver.sh: Alias 'first.name@domain.example' will not be added to '/etc/dovecot/userdb' twice
```
After investigation, it appears this alias is not duplicated in the `/tmp/docker-mailserver/postfix-virtual.cf` file. However this file contains the following 2 lines (in this order):
```
first-name@domain.example account1@anotherdomain.example
first.name@domain.example account2@anotherdomain.example
```
Could it be that the grep check in [`_create_dovecot_alias_dummy_accounts()`](https://github.com/docker-mailserver/docker-mailserver/blob/v14.0.0/target/scripts/helpers/accounts.sh#L138) is missing the `-F` option? Would the dot `.` in `first.name` then be interpreted as any character matching the previous entry `first-name@domain.example`?

I haven't run any test since this is our production server and I haven't taken the time to install a clean DMS instance to try reproducing it.

### 🐋 DMS Version

v14.0.0

### 💻 Operating System and Architecture

Debian 12

**Comment by pitilux** [comment]
I've dug into the codebase a little bit and found that the PR #2640 removed the `-F` option.

**Comment by polarathene** [comment]
> removed the `-F` option.

https://github.com/docker-mailserver/docker-mailserver/pull/2640/files#r896772365

Maybe my alternative advice would be better then?

```bash
if grep -qF "${DOVECOT_USERDB_LINE}" "${DOVECOT_USERDB_FILE}"
```

**Comment by georglauterbach** [comment]
> > removed the `-F` option.
> 
> https://github.com/docker-mailserver/docker-mailserver/pull/2640/files#r896772365
> 
> Maybe my alternative advice would be better then?
> 
> ```diff
> -if grep -qi "^${ALIAS}:" "${DOVECOT_USERDB_FILE}"; then
> +if grep -qxF "${DOVECOT_USERDB_LINE}" "${DOVECOT_USERDB_FILE}"
> ```

CC @casperklein Have we done anything about this issue yet? :)

**Comment by pitilux** [comment]
I proposed a PR to fix this issue (and provided some tests as requested in the previous comment).
