### ISSUE TITLE
bug report: target/dovecot/auth-ldap.conf.ext missing in Dockerfile

### ISSUE THREAD

**Issue by nowheretobefound** [docker-mailserver/docker-mailserver#4173]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

When fixing Issue #3801 ,  "Correctly support multiple Dovecot PassDBs" https://github.com/docker-mailserver/docker-mailserver/pull/3812 there was added a new file to the repository :
target/dovecot/auth-ldap.conf.ext

However I cant see that file being copied into the container image in the Dockerfile, so the container images is missing the updated the file, so the original issue persist.

### 👟 Reproduction Steps

Same as for Issue #3801, fail2ban will still ban you if using oauth

### 🐋 DMS Version

14.0.0

### 💻 Operating System and Architecture

Debian 12

**Comment by nowheretobefound** [comment]
There also seems to be a typo in :
mechanism = plain login

missing `s`in mechanisms

**Comment by polarathene** [comment]
> However I cant see that file being copied into the container image in the Dockerfile, so the container images is missing the updated the file, so the original issue persist.
>
> There also seems to be a typo in : `mechanism = plain login` missing `s` in "mechanisms"

Thank you for spotting and reporting the missing copy and typo! ❤️ 

---

@georglauterbach @casperklein sorry I forgot that I was given more permissions and accidentally [committed directly to master branch](https://github.com/docker-mailserver/docker-mailserver/commit/4e85f799fc39365d87bbe7bc7b9151dae7f31a31) via `github.dev`. I thought we had a guard to enforce PRs that forbids commits/pushes directly to master, but maybe my promoted role is exempt from that restriction 😬

**Comment by georglauterbach** [comment]
> @georglauterbach @casperklein sorry I forgot that I was given more permissions and accidentally [committed directly to master branch](https://github.com/docker-mailserver/docker-mailserver/commit/4e85f799fc39365d87bbe7bc7b9151dae7f31a31) via `github.dev`. I thought we had a guard to enforce PRs that forbids commits/pushes directly to master, but maybe my promoted role is exempt from that restriction 😬

![image](https://github.com/user-attachments/assets/c771c4b9-a641-45ab-809c-80d4c5cff957)

Yes. Yes indeed. 😆
