### ISSUE TITLE
other: Add `autoexpunge` to mailboxes

### ISSUE THREAD

**Issue by loeffelpan** [docker-mailserver/docker-mailserver#4174]
### Subject

I would like to configure a not documented mail server use case

### Description

I would like to add `autoexpunge` for my `Trash` and `Junk` mailbox.
I tried to add this to `user-patches.sh` like in #3434 but it doesn't work.
```
#!/bin/bash

# Dovecot: Auto-Delete Junk and Trash
doveadm mailbox metadata set -u <account> Junk autoexpunge 30d
doveadm mailbox metadata set -u <account> Trash autoexpunge 90d
```
When trying this commands with a running instance of dms I got the following error.
`Fatal: Invalid metadata key 'autoexpunge': Must begin with /private or /shared`

I'm not sure which one to use. But anyway `/private/autoexpunge` and `/shared/autoexpunge` give me the same error.
`Error: Failed to set attribute: Mailbox attributes not enabled`

Any way to enable this feature in dms?
Help would be very appreciated.

**Comment by casperklein** [comment]
Maybe this helps: https://doc.dovecot.org/2.3/configuration_manual/imap_metadata/

**Comment by loeffelpan** [comment]
Thanks for pushing me into the right direction.
I ended up with this in `dovecot.cf` within `dms/config` storing the dict into same path as maildir.
```
mail_attribute_dict = file:/var/mail/%d/%n/dovecot-attributes

protocol imap {
  imap_metadata = yes
}
```
Running `doveadm mailbox metadata set -u <account> Junk /private/autoexpunge 30d` gives me no error and the dict file is created as above. Not sure if it's working, but we will see.

But I'm still not sure which one to use: `/private/autoexpunge` or `/shared/autoexpunge`?
Also `user-patches.sh` gives me some error.
```
2024-09-09 22:08:29+02:00 INFO  start-mailserver.sh: Welcome to docker-mailserver v14.0.0
2024-09-09 22:08:29+02:00 INFO  start-mailserver.sh: Checking configuration
2024-09-09 22:08:29+02:00 INFO  start-mailserver.sh: Configuring mail server
doveadm(jan@kbw3.eu)<917><>: Error: auth-master: userdb lookup(jan@kbw3.eu): connect(/run/dovecot/auth-userdb) failed: No such file or directory
doveadm(jan@kbw3.eu): Error: User lookup failed: Internal error occurred. Refer to server log for more information.
doveadm(jan@kbw3.eu)<918><>: Error: auth-master: userdb lookup(jan@kbw3.eu): connect(/run/dovecot/auth-userdb) failed: No such file or directory
doveadm(jan@kbw3.eu): Error: User lookup failed: Internal error occurred. Refer to server log for more information.
2024-09-09 22:08:33+02:00 INFO  start-mailserver.sh: Starting daemons
```
Maybe `doveadm` does not work when deamons not running? Any other way to run this automatically?

**Comment by casperklein** [comment]
> I don't know the command to insert that, @casperklein is a bit more familiar with such and might suggest sedfile I think.

```bash
sed -i '/mailbox Junk {/a\     autoexpunge 30d' $file

# same as above, but print an error message if the replacement fails
sedfile -i '/mailbox Junk {/a\     autoexpunge 30d' $file
```

**Comment by loeffelpan** [comment]
Okay. I don't want to mess with config files shipped with dms.
So I have to setup `dovecot.cf` with dict and metadata enabled as described before and run `doveadm mailbox metadata set ...` once manually per mailbox and account.

That would work. But I decided to give another simple a try and ended up with this.

dovecot.cf:
```
# Delete Junk after 30 days and Trash after 90 days
namespace inbox {
  mailbox Junk {
    autoexpunge = 30d
  }

  mailbox Trash {
    autoexpunge = 90d
  }
}
```
This one just adds `autoexpunge` to the mailboxes without messing any config file shipped with dms.
`doveconf` give me this.
```
  mailbox Drafts {
    auto = subscribe
    autoexpunge = 0
    autoexpunge_max_mails = 0
    comment = 
    driver = 
    special_use = \Drafts
  }
  mailbox Junk {
    auto = subscribe
    autoexpunge = 30 days
    autoexpunge_max_mails = 0
    comment = 
    driver = 
    special_use = \Junk
  }
  mailbox Sent {
    auto = subscribe
    autoexpunge = 0
    autoexpunge_max_mails = 0
    comment = 
    driver = 
    special_use = \Sent
  }
  mailbox Trash {
    auto = subscribe
    autoexpunge = 90 days
    autoexpunge_max_mails = 0
    comment = 
    driver = 
    special_use = \Trash
  }
```
I will see wether it works or not.
Thanks for any help.

**Comment by polarathene** [comment]
> That would work. But I decided to give another simple a try and ended up with this in `dovecot.cf`.

Awesome, thanks for trying that out. I was thinking it might merge but I wasn't 100% sure 🎉

**Comment by loeffelpan** [comment]
@polarathene Sorry for bothering you again in this closed issue.
I noticed, that this is correctly configured regarding `doveconf` but not working so far.
As we see in my `doveconf` output above there is `autoexpunge_max_mails = 0` set for each mailbox, what avoids autoexpunge at all. Adding `autoexpunge_max_mails = xxx` to `dovecot.cf` should solve this.

However I found another issue.
`autoexpunge` relies on `date.saved` field of each mail. **Unfortunately this equals containers start time for every mail.**

Any idea on this?

**Comment by polarathene** [comment]
> However I found another issue.
> `autoexpunge` relies on `date.saved` field of each mail. **Unfortunately this equals containers start time for every mail.**

Could you expand on that please? How are you inspecting the field?

I'm not sure what would be modifying the file content like that, only a chown at startup which could affect a `mtime` FS attribute, so Dovecot must be doing something else if it alters this `date.saved` field.

> Any idea on this?

I am unable to commit any time into investigating this, but if you identify a bug and how to fix it we can discuss how to approach getting that fix into DMS if necessary.

**Comment by loeffelpan** [comment]
I think I figured it out!
As described [here](https://doc.dovecot.org/main/core/config/namespaces.html#namespace/mailbox/autoexpunge) I need to set `mail_always_cache_fields = date.save` to ensure dovecot to keep the original value for `date.saved`.

Summarized I ended up with this in `dovecot.cf`.
```
# Delete Junk after 30 days and Trash after 90 days
mail_always_cache_fields = date.save
namespace inbox {
  mailbox Junk {
    autoexpunge = 30d
    autoexpunge_max_mails = 100	
  }

  mailbox Trash {
    autoexpunge = 90d
    autoexpunge_max_mails = 100
  }
}
```

**Comment by loeffelpan** [comment]
I will not let your quastions unanswered.
Maybe this can be helpful for anyone else.

> Could you expand on that please? How are you inspecting the field?

You can inspect that with `doveadm fetch -u <account> "date.saved any.field" Trash` inside the container for example. This shows a timestamp close to container start or at least creation.

I read somewhere, that dovecot uses `ctime` for that if `date.saved` is not cached. My best guess is that `ctime` is set when the filesystem/volume is mounted on container creation/start.

May also have something to do with `podman` instead of `docker`.

However this is solved for me with configuration above.
