### ISSUE TITLE
bug report: built-in documentation does not give an example for rspamd-dkim's keytype

### ISSUE THREAD

**Issue by Artoria2e5** [docker-mailserver/docker-mailserver#4180]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

Under rspamd-enable, the call chain for `docker exec -it <CONTAINER NAME> setup config dkim` (as recommended) goes like:
* https://github.com/docker-mailserver/docker-mailserver/blob/cace9c56d932bbd53a36f5bc36f21a676d92a708/target/bin/setup#L134
* https://github.com/docker-mailserver/docker-mailserver/blob/cace9c56d932bbd53a36f5bc36f21a676d92a708/target/bin/open-dkim#L10
* https://github.com/docker-mailserver/docker-mailserver/blob/cace9c56d932bbd53a36f5bc36f21a676d92a708/target/bin/rspamd-dkim

Each of these scripts have their help texts. Of these:

* The first does not mention `keytype` at all. Which is fine, really, since RSA is the main thing and we have the most important ones down.
* The second help text is not invoked on the rspamd path, so let's ignore it.
* The third describes the option, but has no example to go with it.

### 👟 Reproduction Steps

Click the links!

### 🐋 DMS Version

git cace9c56d932bbd53a36f5bc36f21a676d92a708

### 💻 Operating System and Architecture

GitHub source browser

**Comment by georglauterbach** [comment]
Thank you for your feedback. Could you please provide a PR that adds an example to [`target/bin/open-dkim`](https://github.com/docker-mailserver/docker-mailserver/blob/94751e00c9787c5223e39bd0cd5b139a0c1f6255/target/bin/open-dkim#L48-L56)?
