### ISSUE TITLE
How to allow anonymous email sending from my local network.

### ISSUE THREAD

**Issue by szguoxz** [docker-mailserver/docker-mailserver#4182]
### Description

I have done everything possible, config mynetworks, smptd-recipient restrictions, ..., etc, It insists reject my email: Host rejected, access denied.

Who can show me a proper way to set it up that I don't have to login to send email from my own local network?
I already config the docker to use HOST mode for network,

For everything else, the server works fine. I use it for a while now.

**Comment by polarathene** [comment]
Why is credentials a problem? You should only be submitting mail via ports 587 or 465.

DMS does not require credentials to receive mail on port 25, but that port will do security checks as that port is intended for untrusted third party to deliver mail. Port 25 is not for submitting mail to be sent out.

---

You've not filed a proper bug report, ignoring the expectations communicated to you when you opened an issue. You should instead go to the Discussions section and open a question there for community support. This is for DMS issue tracking not personal support.

If you search the issues an discussions you will find other users with your same desire to bypass security checks, along with responses from me. Some of my responses in the past have explained how to workaround that at your own risk.

As per the requirements of filing a report, you are expected to put in the effort to look for this information and demonstrate that. You've briefly cited some context but shared no config. You should also not use host mode networking, it's not required to use DMS the way you're asking and may cause some issues.

---

Please open a discussion instead and wait on someone from the community to provide answers if searching for them from past issues/discussions is asking too much.
