### ISSUE TITLE
bug report: rspamd -> clamav doesn't scan mails

### ISSUE THREAD

**Issue by tekvsakdan** [docker-mailserver/docker-mailserver#4189]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

Clamav doesn't scan mail if rspamd is enabled and amavis is disabled by recommendation from manual. Basically nothing happens. It does not show up in any of the logs. Whatever I put in `antivirus.conf` does not work. It work fine with amavis.

```
enabled = true;

ClamAV {
    type = "clamav";
    servers = "/var/run/clamav/clamd.ctl";
    action = "reject";
    message = '${SCANNER} FOUND VIRUS "${VIRUS}"';
    scan_mime_parts = false;
    symbol = "CLAM_VIRUS";
    log_clean = true;
    max_size = 25000000;
    timeout = 10;
    retransmits = 2;
}
```

### 👟 Reproduction Steps

1. run docker command
2. log file `rspamd.log` shows that the antivirus is enabled
3. send EICAR.txt or EICAR.zip to my e-mail
4. email was not scanned/rejected

### 🐋 DMS Version

v14.0.0

### 💻 Operating System and Architecture

Debian 12.7 / amd64

### ⚙️ Container configuration files

```yml
docker run -d \
    --restart=always \
    --net=host \
    --name=mailserver \
    --cap-add=NET_ADMIN \
    --dns=9.9.9.10 \
    --dns=149.112.112.10 \
    -e LOG_LEVEL=debug \
    -e ENABLE_RSPAMD=1 \
    -e ENABLE_CLAMAV=1 \
    -e ENABLE_OPENDKIM=0 \
    -e ENABLE_OPENDMARC=0 \
    -e ENABLE_POLICYD_SPF=0 \
    -e ENABLE_AMAVIS=0 \
    -e ENABLE_SPAMASSASSIN=0 \
    -e ENABLE_POSTGREY=0 \
    -e ENABLE_FAIL2BAN=1 \
    -e SPOOF_PROTECTION=1 \
    -e SSL_TYPE=letsencrypt \
    -e NETWORK_INTERFACE=eth0 \
    -e POSTFIX_MESSAGE_SIZE_LIMIT=25000000 \
    -v /srv/docker/dms/mail-data/:/var/mail/ \
    -v /srv/docker/dms/mail-state/:/var/mail-state/ \
    -v /srv/docker/dms/mail-logs/:/var/log/mail/ \
    -v /srv/docker/dms/config/:/tmp/docker-mailserver/ \
    -v /srv/docker/certbot/certs/:/etc/letsencrypt \
    -v /etc/localtime:/etc/localtime:ro \
    --hostname=mail.example.com \
    mailserver/docker-mailserver:latest
```

### 📜 Relevant log output

```Text
rspamd.log after startup

2024-09-21 10:14:05 #750(main) <pru76z>; lua; lua_redis.lua:603: use default Redis settings for antivirus
2024-09-21 10:14:05 #750(main) <pru76z>; lua; antivirus.lua:209: added antivirus engine ClamAV -> CLAM_VIRUS
2024-09-21 10:14:05 #750(main) <pru76z>; cfg; rspamd_init_lua_filters: init lua module antivirus from /usr/share/rspamd/plugins/antivirus.lua; digest: d0f8ebf97e

rspamd.log after sending mail

2024-09-21 10:40:51 #798(rspamd_proxy) <1e3913>; proxy; rspamd_task_write_log: id: <555497d6-660e-442a-a164-706617d198c7@example.com>, qid: <4A0209816BD>, ip: 1.2.3.4, user: mickey.mouse@example.com, from: <mickey.mouse@example.com>, (default: F (no action): [0.00/11.00] [DKIM_SIGNED(0.00){example.com:s=mail;}]), len: 1018, time: 48.959ms, dns req: 1, digest: <adbbf710cfb899809074ce1d616982d0>, rcpts: <admin@example.com>, mime_rcpts: <admin@example.com>, settings_id: authenticated
2024-09-21 10:40:51 #798(rspamd_proxy) <1e3913>; proxy; rspamd_protocol_http_reply: regexp statistics: 0 pcre regexps scanned, 0 regexps matched, 176 regexps total, 0 regexps cached, 0B scanned using pcre, 0B scanned total
```

**Comment by georglauterbach** [comment]
Can you please put `X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*` into the _body_ of the test e-mail to check whether it is rejected? :) This way, we can verify that ClamAV is actually working, but probably not configured for scanning attachments.

Our tests check whether this works, so I expect it to work for you. Checking attachments should nevertheless be done as well.

**Comment by georglauterbach** [comment]
Just FYI: [GTube patterns](https://rspamd.com/doc/other/gtube_patterns.html) are disabled by default, if you proceed with testing them next. You would need this too:

https://github.com/docker-mailserver/docker-mailserver/blob/94751e00c9787c5223e39bd0cd5b139a0c1f6255/test/config/rspamd_full/user-patches.sh#L8

**Comment by tekvsakdan** [comment]
I have found what the problem is.

`lsof /var/run/clamav/clamd.ctl` returns empty response.

So I added to clamd.conf

`nano /etc/clamav/clamd.conf`

```
TCPSocket 3310
TCPAddr localhost
```

`supervisorctl restart clamav`

`nano /etc/rspamd/local.d/antivirus.conf`

```
#servers = "/var/run/clamav/clamd.ctl";
servers = 127.0.0.1:3310
```

`supervisorctl restart rspamd`

```
wget https://secure.eicar.org/eicar.com --no-check-certificate && gzip eicar.com
swaks --to receiver@domain.xx --from sender@doamin.xx --attach - --server localhost < eicar.com.gz
```
And it works.

```
<** 554 5.7.1 ClamAV FOUND VIRUS "Win.Test.EICAR_HDB-1"
 -> QUIT
<-  221 2.0.0 Bye

```

**Comment by tekvsakdan** [comment]
I have found what the problem is.

`lsof /var/run/clamav/clamd.ctl` returns empty response.

So I added to clamd.conf

`nano /etc/clamav/clamd.conf`

```
TCPSocket 3310
TCPAddr localhost
```

`supervisorctl restart clamav`

`nano /etc/rspamd/local.d/antivirus.conf`

```
#servers = "/var/run/clamav/clamd.ctl";
servers = 127.0.0.1:3310
```

`supervisorctl restart rspamd`

```
wget https://secure.eicar.org/eicar.com --no-check-certificate && gzip eicar.com
swaks --to receiver@domain.xx --from sender@doamin.xx --attach - --server localhost < eicar.com.gz
```
And it works.

```
<** 554 5.7.1 ClamAV FOUND VIRUS "Win.Test.EICAR_HDB-1"
 -> QUIT
<-  221 2.0.0 Bye

```

I followed the instructions on the website https://www.allerstorfer.at/clamav-with-rspamd-and-ispconfig-on-ubuntu/.

**Comment by polarathene** [comment]
## Working example for EICAR detection (Amavis and Rspamd)

```yaml
services:
  dms:
    image: mailserver/docker-mailserver:14.0.0
    hostname: mail.example.test
    environment:
      ENABLE_CLAMAV: 1
      # Enable Rspamd + Disable equivalent services (comment out to switch back to standard defaults for Amavis):
      ENABLE_RSPAMD: 1
      ENABLE_AMAVIS: 0
      ENABLE_OPENDKIM: 0
      ENABLE_OPENDMARC: 0
      ENABLE_POLICYD_SPF: 0
      # NOTE: Only used for the example for using swaks internally to send mail on port 25
      PERMIT_DOCKER: container
    # NOTE: Normally you'd use `volumes` with external files instead of this Compose feature:
    # (Alternatively just run `setup email add john.doe@example.test secret` when you shell into the DMS container)
    configs:
      - source: dms-accounts
        target: /tmp/docker-mailserver/postfix-accounts.cf

# Using the Docker Compose `configs.content` feature instead of volume mounting separate files.
# NOTE: This feature requires Docker Compose v2.23.1 (Nov 2023) or newer:
# https://github.com/compose-spec/compose-spec/pull/446
# NOTE: `$` literals in `content` are repeated to escape and prevent the `compose.yaml` variable interpolation feature.
configs:
  # DMS expects an account to be configured to run, this example provisions one in advance:
  # Login credentials:
  # user: "john.doe@example.test" password: "secret"
  dms-accounts:
    content: |
      john.doe@example.test|{SHA512-CRYPT}$$6$$sbgFRCmQ.KWS5ryb$$EsWrlYosiadgdUOxCBHY0DQ3qFbeudDhNMqHs6jZt.8gmxUwiLVy738knqkHD4zj4amkb296HFqQ3yDq4UXt8.
```

```console
# Start DMS container and shell into it:
$ docker compose up --force-recreate -d
$ docker compose exec -it dms bash

# Make sure the socket file is created before testing mail:
$ ls -lah /var/run/clamav
total 12K
drwxr-xr-x 1 clamav root   4.0K Sep 27 01:16 .
drwxr-xr-x 1 root   root   4.0K Sep 27 01:16 ..
srw-rw-rw- 1 clamav clamav    0 Sep 27 01:16 clamd.ctl

# ClamAV socket is working as shown above, then send a test mail within the container:
# It will fail with the reason shown in output below (Virus detected, mail rejected):
$ swaks --helo not-relevant.test --server 0.0.0.0 --port 25 --from hello@not-relevant.test --to john.doe@example.test --body 'X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*'
<** 554 5.7.1 ClamAV FOUND VIRUS "Eicar-Signature"
 -> QUIT
<-  221 2.0.0 Bye
=== Connection closed with remote host.

# Verify virus detection logged:
$ grep -i eicar /var/log/mail.log
2024-09-27T01:23:12.083146+00:00 mail postfix/cleanup[1003]: 97184C589B: milter-reject: END-OF-MESSAGE from localhost[127.0.0.1]: 5.7.1 ClamAV FOUND VIRUS "Eicar-Signature"; from=<hello@not-relevant.test> to=<john.doe@example.test> proto=ESMTP helo=<not-relevant.test>

# If this were for Amavis instead of Rspamd:
$ grep -i eicar /var/log/mail.log
2024-09-27T01:13:13.793450+00:00 mail amavis[776]: (00776-01) Blocked INFECTED (Eicar-Signature) {DiscardedInbound,Quarantined}, [127.0.0.1]:52086 <hello@not-relevant.test> -> <john.doe@example.test>, quarantine: h/virus-hs_7HBbSeOYL, Queue-ID: 8EDDCC5847, Message-ID: <20240927011313.001064@mail.example.test>, mail_id: hs_7HBbSeOYL, Hits: -, size: 275, 140 ms
2024-09-27T01:13:13.794448+00:00 mail postfix/smtp-amavis/smtp[1070]: 8EDDCC5847: to=<john.doe@example.test>, relay=127.0.0.1[127.0.0.1]:10024, delay=0.22, delays=0.06/0.01/0.01/0.14, dsn=2.7.0, status=sent (250 2.7.0 Ok, discarded, id=00776-01 - INFECTED: Eicar-Signature)
```

**Environment details:**

- Arch: `x86_64`
- OS: Windows 11 with WSL2 + Docker Desktop
- Kernel: `5.15.123.1-microsoft-standard-WSL2`
- Docker Engine: `26.1.1`
- Docker Compose: `2.27.0`
- 16GiB system memory

---

## Needs further context before considering suggested fix

Given the above, I did not need to change rspamd + clamav config to use TCP IP+port vs unix socket? I am curious what the difference is from your side that is not compatible.

I know that sockets have been problematic in the past for some users, but these tend to be on macOS or running Podman / Docker in rootless mode I think?

Until that context is understood, I do not think that changing from a unix socket is a solution.

## Troubleshooting advice

Could you please try running the `compose.yaml` I've provided above on your system and running the shell commands I showed? Do you get a different experience or does it work?

If your results are the same with the example I provided, then there is something about your real config that needs to be known as the problem.
- Please ensure you destroy the container so that it runs with only state persisted from volumes (`docker compose up --force-recreate`)
- If you still have the issue, try again but disable all your volumes, ensure you have a new enough version of Docker Compose to copy/paste the `configs` settings in the above `compose.yaml` example. Alternatively without `volumes` or `configs` when you shell into the container start with `setup email add john.doe@example.test secret` and continue with the example commands above.
- If this still fails, you'll need to take the same approach of disabling config, I would start with the network ones, especially your decision to use host mode networking which may have some compatibility concerns with DMS assumptions.
- Make sure you `--force-recreate` each time you restart DMS for this troubleshooting process to rule out any mishaps until you reach the point that it works again like the minimal reproduction `compose.yaml` above demonstrates.

**Comment by tekvsakdan** [comment]
Your approach works. My approach also works when I omit `--network=host`. It looks like the problem is in the `host` command. The reason I chose to use host is because I can see the ip of the clients in the logs.

**Comment by polarathene** [comment]
> It looks like the problem is in the `host` command. The reason I chose to use host is because I can see the ip of the clients in the logs.

Host can be reached via IPv6? That's usually where that issue happens. It should no longer be an issue with Docker from v27 AFAIK, otherwise see our docs for IPv6 which explain the problem and how to resolve that.

If you have a reverse-proxy in front of it like Traefik or Cloudflare you'd need to also configure PROXY protocol (_again covered on our docs, just use the search box to find guidance_).

After you tackle that you would not need host mode networking. Although I'm not sure why that would cause an issue with unix sockets but TCP IP+port works 🤔 If you prefer to use the config workaround you shared that's fine, but host mode networking does introduce some differences that it's generally discouraged for DMS.

**Comment by tekvsakdan** [comment]
Since I need the client-ip, I ran it as a `network=host`. This is my workaround.

I installed the clamav container.

```
docker run -d \
	-p 3310:3310 \
	--name=clamav \
	--hostname=clamav \
	clamav/clamav:latest
```

I added `config/rspamd/override.d/antivirus.conf`

```
enabled = true;

ClamAV {
    type = "clamav";
    #servers = "/var/run/clamav/clamd.ctl";
    servers = 1.2.3.4:3310;
    action = "reject";
    message = '${SCANNER} FOUND VIRUS "${VIRUS}"';
    scan_mime_parts = false;
    symbol = "CLAM_VIRUS";
    log_clean = true;
    max_size = 25000000;
    timeout = 10;
    retransmits = 2;
}
```

and I am running the mail server container with `-e ENABLE_CLAMAV=0` because I have an external server.

**Comment by polarathene** [comment]
> I am running the mail server container with `-e ENABLE_CLAMAV=0` because I have an external server.

Well that is new, the original report showed you used the clamav from DMS container. With external clamav you definitely can't use unix socket unless it's on the same docker host and you share it with DMS via a volume.

---

> Since I need the client-ip, I ran it as a `network=host`.

As I covered in my previous comment you can keep the client IP without `network=host`, just need to ensure correct configuration.

**Comment by tekvsakdan** [comment]
You misunderstood. I now use as workaround -e ENABLE_CLAMAV=0 and external clamav servers because -e ENABLE_CLAMAV=1 on network=host doesn't work with local socket on Debian.

However, there are some reports on the web that clamav local socket does not work on Debian 12.6. Maybe that's why it doesn't work for me with network=host.

I think it's a bug in Debian 12. 

I'll close this.

**Comment by tekvsakdan** [comment]
There seems to be a problem with the folder permissions. If we give

```
chmod 777 /var/run/clamav
supervisorctl restart **rspamd**
```

then it works.

**Comment by polarathene** [comment]
> The problem is because the folder `/var/run/clamav` has `clamav:root`.

From my earlier comment above:

```console
$ ls -lah /var/run/clamav
total 12K
drwxr-xr-x 1 clamav root   4.0K Sep 27 01:16 .
drwxr-xr-x 1 root   root   4.0K Sep 27 01:16 ..
srw-rw-rw- 1 clamav clamav    0 Sep 27 01:16 clamd.ctl
```

The socket has `clamav` ownership both user and group, that should be sufficient AFAIK? As shown in my own results, there is no problem with that, and I can't see any reason `network=host` would affect that.

However, this does mean that only the `root` user or `clamav` would have permission to access. This is a non-issue for Amavis which has been added to the `clamav` group:

```console
$ grep clamav /etc/group
clamav:x:200:amavis
amavis:x:999:clamav
```

So if anything, you would need rspamd in that clamav group. Yet that was not required for my reproduction example to work, nor does it explain why your suggestion would help, both `root` and `clamav` can write to `/var/run/clamav`, just not Amavis that is in the `clamav` group, it is only granted group access to the socket.
