### ISSUE TITLE
[TODO]: Remove `mysql` from valid `SASLAUTHD_MECHANISMS`

### ISSUE THREAD

**Issue by maxswjeon** [docker-mailserver/docker-mailserver#4251]
### Subject

I would like to contribute to the project

### Description

Currently, the bundled saslauthd does not support mysql authentication mechanism, but is included in [master/mailserver.env](https://github.com/docker-mailserver/docker-mailserver/blob/master/mailserver.env) which is very misleading.

```
usage: saslauthd [options]

option information:
  -a <authmech>  Selects the authentication mechanism to use.
  -c             Enable credential caching.
  -d             Debugging (don't detach from tty, implies -V)
  -r             Combine the realm with the login before passing to authentication mechanism
                 Ex. login: "foo" realm: "bar" will get passed as login: "foo@bar"
                 The realm name is passed untouched.
  -O <option>    Optional argument to pass to the authentication
                 mechanism.
  -l             Disable accept() locking. Increases performance, but
                 may not be compatible with some operating systems.
  -m <path>      Alternate path for the saslauthd working directory,
                 must be absolute.
  -n <procs>     Number of worker processes to create.
  -s <kilobytes> Size of the credential cache (in kilobytes)
  -t <seconds>   Timeout for items in the credential cache (in seconds)
  -v             Display version information and available mechs
  -V             Enable verbose logging
  -h             Display this message.

saslauthd 2.1.28
authentication mechanisms: sasldb getpwent kerberos5 pam rimap shadow ldap
```

**Comment by casperklein** [comment]
Good catch. That seems to be a bug/regression:

```
environment:
  - ENABLE_SASLAUTHD=1
  - SASLAUTHD_MECHANISMS=mysql
```

 ```
mail  | 2024-11-05 13:22:00,548 WARN exited: saslauthd_mysql (exit status 1; not expected)
mail  | 2024-11-05 13:22:01,552 INFO spawned: 'saslauthd_mysql' with pid 2898
mail  | 2024-11-05 13:22:01,559 INFO success: saslauthd_mysql entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
mail  | 2024-11-05 13:22:01,560 WARN exited: saslauthd_mysql (exit status 1; not expected)
mail  | 2024-11-05 13:22:02,563 INFO spawned: 'saslauthd_mysql' with pid 2899
mail  | 2024-11-05 13:22:02,571 INFO success: saslauthd_mysql entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
mail  | 2024-11-05 13:22:02,571 WARN exited: saslauthd_mysql (exit status 1; not expected)
mail  | 2024-11-05 13:22:03,574 INFO spawned: 'saslauthd_mysql' with pid 2900
mail  | 2024-11-05 13:22:03,581 INFO success: saslauthd_mysql entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
mail  | 2024-11-05 13:22:03,582 WARN exited: saslauthd_mysql (exit status 1; not expected)
```

```
root@mail:/# cat /var/log/supervisor/saslauthd_mysql.log
saslauthd[2542] :unknown authentication mechanism: mysql
saslauthd[2553] :unknown authentication mechanism: mysql
saslauthd[2594] :unknown authentication mechanism: mysql
saslauthd[2601] :unknown authentication mechanism: mysql
saslauthd[2619] :unknown authentication mechanism: mysql
```

**Comment by polarathene** [comment]
> which is very misleading

It was contributed by a third-party many years ago (before 2020), they did not have a need for the mechanism but added a bunch of these to the supervisor config for whatever reason.

It's likely that the mechanism was available in the past, I can't recall exactly when DMS switched from Ubuntu to Debian as a base image, but it's also possible that a debian upgrade dropped the mechanism too.

**EDIT:** Had a look going back to Debian 10 and also with Fedora equivalent packages for `saslauthd` and the SQL plugin, but neither seem to make an authentication mechanism for `mysql` available. Perhaps this was available in the past or the contribution itself was not properly thought out.

- [2010 article](https://ryandoyle.net/posts/bringing-postfix-cyrus-sasl-saslauthd-pam_mysql_and_mysql_all_together/) notes that this required using `pam` with a plugin to auth with mysql.
- [Official Cyrus docs](https://www.cyrusimap.org/imap/concepts/features/authentication-sql.html) also refer to SQL auth as via PAM.

It seems in the past there may have been a `mysql` auth mechanism, but it [was replaced](https://phil.lavin.me.uk/2011/11/solved-debian-wheezy-sasl-login-authentication-failed-no-mechanism-available/#comment-24963) by the [SQL plugin](https://github.com/cyrusimap/cyrus-sasl/blob/master/docsrc/sasl/options.rst#sql-plugin) for generic SQL support via `auxprop`. Postfix [documents both auxprop and PAM methods](https://www.postfix.org/SASL_README.html#auxprop_sql).

---

Officially DMS has only ever supported `ldap` and `rimap` mechanisms. We could drop the others?

FWIW Postfix defaults to delegating auth to Dovecot, and Dovecot does not require saslauthd for LDAP support. `rimap` is only useful if you don't use our bundled Dovecot, but instead want remote imap server to handle the authentication, which is what the contributor wanted IIRC.

**Comment by casperklein** [comment]
> Officially DMS has only ever supported ldap and rimap mechanisms. We could drop the others?

IMO we should remove `mysql`, but keep `shadow`. There are no complains about it and maybe someone is using it.

**Comment by polarathene** [comment]
> There are no complains about it and maybe someone is using it.

I'd rather we have a known use-case than a maybe. We can add a deprecation notice to the release notes as a precaution but as it'll be a major release it's also quite easy to just bring back via patch release.

Even without the release I've documented how users can add a supervisord service in the past, which is fine for niche support.

I'm not sure how worthwhile saslauthd is to DMS since LDAP works fine without it. Main value is for Postfix when Dovecot isn't enabled due to `SMTP_ONLY=1` IIRC. Most users aren't likely to need it

**Comment by maxswjeon** [comment]
I really lost track for less than a week because of my main job, but I really surprised by the contributors and maintainer's quick response! I really approciate your work.
