### ISSUE TITLE
[bugs]Second login will break the ip whitelisting limit!

### ISSUE THREAD

**Issue by PunkFleet** [docker-mailserver/docker-mailserver#4287]
@polarathene 
I went through the official recommended override, but it seems there is a bug here.
The first attempt to log in gets rejected, but the second login goes through with no problem.

```
2024-12-11T17:05:41.619875+00:00 mail dovecot: imap-login: Login: user=<test@example.com>, method=PLAIN, rip=27.128.28.245, lip=10.89.0.9, mpid=980, TLS, session=<I6yHmwEpqLsbgBz1>
2024-12-11T17:05:42.501298+00:00 mail dovecot: imap(test@example.com)<980><I6yHmwEpqLsbgBz1>: Disconnected: Connection closed (NAMESPACE finished 0.281 secs ago) in=58 out=568 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
2024-12-11T17:06:17.948953+00:00 mail postfix/submissions/smtpd[1039]: connect from unknown[27.128.28.245]
2024-12-11T17:06:18.254865+00:00 mail postfix/submissions/smtpd[1039]: Anonymous TLS connection established from unknown[27.128.28.245]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature ECDSA (prime256v1) server-digest SHA256
2024-12-11T17:06:20.059749+00:00 mail postfix/submissions/smtpd[1039]: disconnect from unknown[27.128.28.245] ehlo=1 auth=1 quit=1 commands=3
2024-12-11T17:06:21.874301+00:00 mail dovecot: imap-login: Login: user=<test@example.com>, method=PLAIN, rip=27.128.28.245, lip=10.89.0.9, mpid=1054, TLS, session=<NfftnQEpvrsbgBz1>
2024-12-11T17:06:22.992662+00:00 mail dovecot: imap(test@example.com)<1054><NfftnQEpvrsbgBz1>: Disconnected: Connection closed (LIST finished 0.284 secs ago) in=94 out=766 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
```
there my compose.yaml
```
...
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/:Z
      - ./docker-data/dms/mail-state/:/var/mail-state/:Z
      - ./docker-data/dms/mail-logs/:/var/log/mail/:Z
      - ./docker-data/dms/config/:/tmp/docker-mailserver/:Z
      # IP Whitelist
      - ./docker-data/dms/config/postfix/trusted_clients:/etc/postfix/trusted_clients:Z
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/etc/letsencrypt:Z
```
and
```
[root@mail ~]# ls docker-data/dms/config
dovecot-masters.cf  dovecot-quotas.cf  opendkim  postfix  postfix-accounts.cf  postfix-master.cf  postfix-virtual.cf  user-patches.sh
[root@mail ~]# cat docker-data/dms/config/postfix-master.cf
submission/inet/smtpd_client_restrictions=cidr:/etc/postfix/trusted_clients,permit_sasl_authenticated,reject
submissions/inet/smtpd_client_restrictions=cidr:/etc/postfix/trusted_clients,permit_sasl_authenticated,reject
[root@mail ~]# cat docker-data/dms/config/postfix/trusted_clients
!164.25.121.225 REJECT
[root@mail ~]# podman exec -it mailserver cat /etc/postfix/trusted_clients
!164.25.121.225 REJECT
[root@mail ~]# 
```

I did check it many times, so I shouldn't have overlooked anything, right?

_Originally posted by @PunkFleet in https://github.com/docker-mailserver/docker-mailserver/discussions/3847#discussioncomment-11535769_

**Comment by polarathene** [comment]
> The first attempt to log in gets rejected, but the second login goes through with no problem.

Could you be a bit more clearer in your observations with connections from the logs?

I see two imap logins for Dovecot and one for postfix submissions (port 465).

The config being for Postfix is thus only going to work with Postfix. It restricts connections allowed on Postfix ports.

Dovecot is used for authentication in both cases, but it would not know of the IP for connections to Postfix AFAIK, when port 465 for Postfix gets a connection, it'll delegate the credentials check to Dovecot.

---

@casperklein is familiar with Fail2Ban config, and that is more likely what you're interested in actually configuring?

I am not sure if DMS supports it easily, but you would want F2B to have a rule that blocks any IP to your [ports that require authentication](https://github.com/docker-mailserver/docker-mailserver/blob/96bffd79791e1cc85fe81a5e797384236fcca2e0/compose.yaml#L12-L15), except your allowed IP/subnet addresses. This way mail can still be delivered from anyone to port 25.

---

Another option is to use a reverse proxy like the [referenced discussion](https://github.com/orgs/docker-mailserver/discussions/3847#discussioncomment-8424736) you followed for config describes in my answer there. Probably easier, but make sure you then handle PROXY protocol like [our docs example](https://docker-mailserver.github.io/docker-mailserver/v14.0/examples/tutorials/mailserver-behind-proxy/#configuration) details.

**Comment by polarathene** [comment]
Furthermore, your logs show the remote IP as `27.128.28.245` while the config you have trusted `164.25.121.225`. That doesn't seem right?

**Comment by PunkFleet** [comment]
> Could you be a bit more clearer in your observations with connections from the logs?
> 
> I see two imap logins for Dovecot and one for postfix submissions (port 465).
> 
> The config being for Postfix is thus only going to work with Postfix. It restricts connections allowed on Postfix ports.
> 
> Dovecot is used for authentication in both cases, but it would not know of the IP for connections to Postfix AFAIK, when port 465 for Postfix gets a connection, it'll delegate the credentials check to Dovecot.

The configuration should be correct if that seems to be the case, it's just that the effect it achieves is not a one-step process.

> Furthermore, your logs show the remote IP as 27.128.28.245 while the config you have trusted 164.25.121.225. That doesn't seem right?


Yes,My intention was to only allow `164.25.121.225`, but it actually does nothing to ban `27.128.28.245`  or anything when using the thunderbrid client.

**Comment by polarathene** [comment]
> Yes, my intention was to only allow `164.25.121.225`, but it actually does nothing to ban `27.128.28.245` or anything when using the thunderbird client.

Ok so we have established that only ports to Postfix with the config you've used will be restricted. As your logs show that IP gets disconnected, so it seems to be working fine?

For the IMAP port you'll need to look at their docs for equivalent config, or take a different approach. Do note that with the Fail2Ban service running it'll ban IPs with enough failed login attempts so you should be fine.

---

If your concern is about someone guessing your password eventually by working around those bans by trying again with different IPs, you really don't have to worry about that if you [use a password with enough entropy](https://github.com/docker-mailserver/docker-mailserver/issues/4011#issuecomment-2105501410) (_example: `detailed snail summons slim lab coat`_). Choose higher entropy than 48-bit if you're concerned someone would invest in targeting you directly for an attack to justify the cost, and don't re-use the password elsewhere.

If you have other users where such an entropy baseline can't be enforced for their passwords, then going the extra effort to apply restrictions to which IP can connect can be a valid approach.

**Comment by PunkFleet** [comment]
> > Yes, my intention was to only allow `164.25.121.225`, but it actually does nothing to ban `27.128.28.245` or anything when using the thunderbird client.
> 
> Ok so we have established that only ports to Postfix with the config you've used will be restricted. As your logs show that IP gets disconnected, so it seems to be working fine?
> 
> For the IMAP port you'll need to look at their docs for equivalent config, or take a different approach. Do note that with the Fail2Ban service running it'll ban IPs with enough failed login attempts so you should be fine.
> 
> If your concern is about someone guessing your password eventually by working around those bans by trying again with different IPs, you really don't have to worry about that if you [use a password with enough entropy](https://github.com/docker-mailserver/docker-mailserver/issues/4011#issuecomment-2105501410) (_example: `detailed snail summons slim lab coat`_). Choose higher entropy than 48-bit if you're concerned someone would invest in targeting you directly for an attack to justify the cost, and don't re-use the password elsewhere.
> 
> If you have other users where such an entropy baseline can't be enforced for their passwords, then going the extra effort to apply restrictions to which IP can connect can be a valid approach.

Thank you for your help. I'm still very new to this industry and am switching from legacy postfix to DMS for security reasons. i thought ip whitelisting was an out-of-the-box feature, but that's ok, i'm sure this advice will be secure enough for me.

**Comment by polarathene** [comment]
If you're looking for a more modern mail server you might want to look at stalwart? I haven't given it a proper look yet but it seems like it could be quite a nice alternative and may better support what you want out of the box? It replaces both Postfix and Dovecot along with offering a web UI for management and more modern config format (TOML).

**Comment by casperklein** [comment]
You can try this within the container:

```
nft add table inet filter
nft add chain inet filter input '{ type filter hook input priority 0; }'
nft add rule inet filter input ip saddr 1.2.3.4 tcp dport 25 accept
nft add rule inet filter input tcp dport 25 drop
```

This should only allow access to port 25 for IP address 1.2.3.4

To make this persistent, you can use the [user-patches.sh](https://docker-mailserver.github.io/docker-mailserver/latest/faq/#how-to-adjust-settings-with-the-user-patchessh-script)
